### ISSUE TITLE
成功部署但无法访问

### ISSUE THREAD

**Issue by doubleZ0108** [Yidadaa/ChatGPT-Next-Web#1]
您好，非常感谢您的工作，非常简单便捷！
但成功部署之后发现无法打开，可能涉及到网络环境。我现有的网络可以正常登录chatgpt访问，但无法打开xxx.vercel.app，请问可能是什么问题吗？
> ps. 对于这种国外的服务器我之前使用过netlify，当时也是访问很慢，后来用cloudflare配合阿里云进行加速，请问对于本工程有什么加速方案吗？

非常感谢您的时间，以上。

**Comment by Yidadaa** [comment]
应该是 DNS 污染的问题，如果你有自己的域名的话，可以直接参照 [Vercel 的文档](https://vercel.com/docs/concepts/projects/domains/add-a-domain) 绑定你的域名，之后就可以直连了。

至于 cloudflare 配合阿里云加速，应该也适用于本项目，不过我没有搞过，这个文档可能会对你帮助：https://vercel.com/guides/using-cloudflare-with-vercel

**Comment by doubleZ0108** [comment]
好的，非常感谢
我刚才用netlify部署了一下该项目，可以成功访问
但您提供默认的部署方案配合阿里云和cloudflare还是没法访问
后续我尝试下直接绑定域名的方法，感谢

**Comment by Yidadaa** [comment]
vercel 的项目居然可以直接部署到 netlify 上吗，我研究一下，看看能不能加个一键部署的按钮上去，谢谢分享，这个 issue 我先 close 了。
