### ISSUE TITLE
你好大佬，这个按钮考虑不考虑方向上下反转一下

### ISSUE THREAD

**Issue by JeazW** [Yidadaa/ChatGPT-Next-Web#10]
![image](https://user-images.githubusercontent.com/75829171/227448118-7035aa38-40ed-4259-a12c-99d09fff1320.png)
现在这个不应该是上传的意思么哈哈，抱歉占用公共资源,一点小建议

**Comment by Yidadaa** [comment]
本意是导出的意思，确实有点不够直观，之后顺手改了。
