### ISSUE TITLE
[Feature] 可以支持client-side only嘛

### ISSUE THREAD

**Issue by abrasumente233** [Yidadaa/ChatGPT-Next-Web#1000]
类似 chatbot-ui，所有api请求直接在浏览器端跟openai通信，不通过host server中转，api key也储存在浏览器，这样就不用担心在host上预填api key，服务器被攻击，或者code太弱导致api key被滥用。

**Comment by Yidadaa** [comment]
https://nextjs.org/docs/advanced-features/static-html-export

项目暂时不支持，可以导出静态文件，但是没有对接口做兼容，你可以研究下怎么处理。

**Comment by abrasumente233** [comment]
好诶，感谢

**Comment by abrasumente233** [comment]
不过我最近时间不多，等不及的朋友可以先研究下

**Comment by guotao** [comment]
怎么用client-side？没看到配置项。

**Comment by Yidadaa** [comment]
现已支持通过 `yarn export` 构建纯静态产物，可以直接扔到任意静态文件服务器上部署。
