### ISSUE TITLE
[Bug] 附带历史消息数没有生效

### ISSUE THREAD

**Issue by tisfeng** [Yidadaa/ChatGPT-Next-Web#1002]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**

设置的【附带历史消息数】是 8，但这个值似乎根本没有生效，详情请看截图。

之前是正常的，大概是最近的版本才有这个问题。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**

<img width="1409" alt="iShot_2023-04-22_15 55 31" src="https://user-images.githubusercontent.com/25194972/233771127-4d54d1b1-763b-4f2b-bc26-ab139da637ac.png">

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/25194972/233771132-8920bbcb-a556-47dd-aa7b-803be375f70f.png">

**一些必要的信息**
 - 系统：macos 13.2
 - 浏览器： chrome
 - 版本： ee0f847
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
提供一下控制台 Log 截图

**Comment by tisfeng** [comment]
我刚升到最新版 8d0a420，测试还是一样，没有带历史消息 

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/25194972/233772611-d6ec62f8-b9ee-4db7-b1db-2b7c8fb497c5.png">

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/25194972/233772690-d213ffae-738c-41fb-a20b-1d3fefe98f48.png">

**Comment by Yidadaa** [comment]
其他的对话有这个问题吗？

**Comment by tisfeng** [comment]
奇怪，我新建一个对话，好像又没有这个问题 🥲

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/25194972/233773637-e04a48e8-de52-4b4a-bda1-60f9b4fead54.png">

**Comment by tisfeng** [comment]
试了一下之前已有的对话，都有这个问题，而新建的对话正常。。

**Comment by tisfeng** [comment]
为什么控制台会一直报这个错？

https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=1&q=in:inbox

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/25194972/233773955-b5f55a16-b799-4825-bcd7-5458b5948075.png">

**Comment by AprilNEA** [comment]
这看起来像是你的浏览器插件在发送非法的跨域请求，或者您部署的本仓库代码经过恶意修改

**Comment by tisfeng** [comment]
> 这看起来像是你的浏览器插件在发送非法的跨域请求，或者您部署的本仓库代码经过恶意修改

用无痕浏览器试了一下，没有这个错，可能是某个插件出了问题。刷新一下也没有继续报错了。

**Comment by Yidadaa** [comment]
@tisfeng 应该是版本更新，导致旧数据不兼容导致的，我现在没做什么数据兼容逻辑，遇到问题就先清除浏览器缓存吧

**Comment by tisfeng** [comment]
ok
