### ISSUE TITLE
[Feature] 可以支持ACCESS_TOKEN吗

### ISSUE THREAD

**Issue by wanghuohuoyan** [Yidadaa/ChatGPT-Next-Web#1008]
**这个功能与现有的问题有关吗？**
无法使用api，key的钱被被人破解用完，也无法注册账号，没国外信用卡付费

**你想要什么功能或者有什么建议？**
想知道能不能支持ACCESS_TOKEN

**有没有可以参考的同类竞品？**
同类型chenzhaoyu94/chatgpt-web

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
#794

**Comment by wanghuohuoyan** [comment]
> #794

好的，谢谢。还是感谢大佬写出的优秀项目，UI好看
