### ISSUE TITLE
[Bug] 我这边api用法不对吗 

### ISSUE THREAD

**Issue by hlf2016** [Yidadaa/ChatGPT-Next-Web#1012]
headers 里面 token 和 code 都有了 这个报错看不太懂啊
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/24551738/233793250-8fe31866-c793-4cf1-aabd-9ed6bf6baa88.png">

**Comment by Yidadaa** [comment]
header 里需要指定 path，比如 `v1/chat/completions`
