### ISSUE TITLE
[Feature] docker部署完后，回复ECONNREFUSED

### ISSUE THREAD

**Issue by ZhuJianglai** [Yidadaa/ChatGPT-Next-Web#1014]
我是使用docker部署的，完成后在对话的时候提示这个
```json
{
  "cause": {
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "224.0.0.1",
    "port": 443
  }
}
```
![image](https://user-images.githubusercontent.com/32724206/233794268-b4fd1608-82ea-4443-b889-c03fdad2636c.png)
是配置问题么还是？

**Comment by jackiegk** [comment]
应该是你网络故障，或者用得代理链接无效

**Comment by yellow13441** [comment]
注意：如果你的代理是在本地启动，而不是在Docker容器内启动。
Notice: If your proxy is launched locally instead of within a Docker container.
1. docker: Add `--net=host` in your command.
2. docker-compose: Add network_mode: "host"` in your docker-compose.yml.
