### ISSUE TITLE
弱弱问一下,这个原理是啥?openai服务器看到的请求ip是中国的还是vercel服务器的?主要还是担心封号

### ISSUE THREAD

**Issue by xiangnanscu** [Yidadaa/ChatGPT-Next-Web#1017]
我都研究了下, 比如我部署在自定义域名`xx.com`上, 打开这个网页开始提问, 发现请求是发往`xx.com/api/chat-stream`. 这就触及到我的知识盲区了. 按理说xx.com指向的是vercel一个静态站点,这个`/api/chat-stream`是谁来转发到openai服务器的呢?

**Comment by Yidadaa** [comment]
这不是静态站，你可以去看下 nextjs 是干嘛的，会在 vercel 服务器中转。
