### ISSUE TITLE
[Bug] 代理失败，dev环境可以，生产环境不行

### ISSUE THREAD

**Issue by PuddingJoker** [Yidadaa/ChatGPT-Next-Web#1021]
代理失败，dev环境可以，生产环境不行是为什么呢

**Comment by INTKILOW** [comment]
PROXY_URL windows 下面不好用啊dev 也不好用
 用的clashx

**Comment by INTKILOW** [comment]
{
  "cause": {
    "name": "ConnectTimeoutError",
    "code": "UND_ERR_CONNECT_TIMEOUT",
    "message": "Connect Timeout Error"
  }
}

**Comment by PuddingJoker** [comment]
我是指项目中的base_url，开发的时候在本地可以用，但是我在dockerfile中添加完proxy_url，打包就无法使用


张无忌 ***@***.***> 于2023年4月23日周日 13:20写道：

**Comment by Yidadaa** [comment]
RPOXY_URL 是梯子代理，BASE_URL 是 openai 服务代理，搞清楚。

**Comment by Yidadaa** [comment]
PROXY_URL 只在 docker 里有用，BASE_URL 在任何情况下都有用

**Comment by PuddingJoker** [comment]
但是我使用dockerfile构建的话，openai服务代理是写在.env.local的BASE_URL里面，然后构建，部署还是无法发问题请求[image:
image.png][image: image.png]  这是为什么呀

Yifei Zhang ***@***.***> 于2023年4月23日周日 14:15写道：

**Comment by PuddingJoker** [comment]
构建了在本地跑是可以发请求的，部署到网上就不行

pudding chan ***@***.***> 于2023年4月23日周日 14:20写道：

**Comment by PuddingJoker** [comment]
帮忙解决这个问题后 我去你们那边捐赠一下 实在是好项目 但是就差这一步

pudding chan ***@***.***> 于2023年4月23日周日 14:22写道：

**Comment by Yidadaa** [comment]
不要放到 .env.local 里，那是开发时用的，打包完 docker 镜像，用 -e 传进去，我寻思文档写得很清楚？

**Comment by PuddingJoker** [comment]
-e传到base_url吗，还是不行啊 ，这是我打包后运行的命令： docker run -d --name next -p 3000:3000 \
    -e OPENAI_API_KEY="sk-gX******8" \
    -e BASE_URL="openai.*******" \
    next:1.0
[image: image.png]
[image: image.png]

Yifei Zhang ***@***.***> 于2023年4月23日周日 14:39写道：

**Comment by Yidadaa** [comment]
BASE_URL="https://openaixxxxx"

**Comment by PuddingJoker** [comment]
不是不能使用https吗，假设我的openaikeys是 sk-test，baseurl是 www.badu.com，能否麻烦您按照 docker
run -d --name next -p 3000:3000 \
    -e OPENAI_API_KEY="sk-gX******8" \
    -e BASE_URL="openai.*******" \
    next:1.0
这个格式，把模拟的命令发给我看一下，非常感谢！

Yifei Zhang ***@***.***> 于2023年4月23日周日 15:44写道：

**Comment by Yidadaa** [comment]
`-e BASE_URL="https://baidu.com"`

鬼知道你用谁家的 openai 代理？支持 https 就用 https，不支持就用 http，但是你不能不写啊

**Comment by gsons** [comment]
> PROXY_URL windows 下面不好用啊dev 也不好用 用的clashx

clashx客户端可以启用tunnel模式 ，这样就会走正向代理了

**Comment by guotao** [comment]
> > PROXY_URL windows 下面不好用啊dev 也不好用 用的clashx
> 
> clashx客户端可以启用tunnel模式 ，这样就会走正向代理了

这样设置会不会全局流量都走clashx？
