### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by onijiang0** [Yidadaa/ChatGPT-Next-Web#1023]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
gpt的回复全乱码

**如何复现**
请告诉我们你是通过什么操作触发的该问题。
我搭建了一个用了chatgpt api 的qq机器人之后就这样了，重新部署回复依然是乱码
**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![}LI8PO1PX`K4 )CTFU1OO](https://user-images.githubusercontent.com/110103071/233823339-192d9a6d-a002-45cf-9230-81c21faefbb3.png)
![0_`MAI%QLB{) _ZPLKFFCO](https://user-images.githubusercontent.com/110103071/233823377-5a09685c-a161-468f-90de-4c688da2b35f.png)

**一些必要的信息**
 - 系统： windows 11
 - 浏览器：edge
 - 版本：71aa9d0
 - 部署方式： vercel

**Comment by Yidadaa** [comment]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/16968934/233826176-dc203f8b-b5f7-43e6-ad0f-a3f25a7b0e0e.png">
