### ISSUE TITLE
[Feature] 建议添加OPENAI_ACCESS_TOKEN的环境变量

### ISSUE THREAD

**Issue by xiaokuqwq** [Yidadaa/ChatGPT-Next-Web#1024]
使用 Web API 所需的 accessToken
[(获取 accessToken)](https://chat.openai.com/api/auth/session) 
来省略使用API KEY的成本

**Comment by Yidadaa** [comment]
#794

**Comment by xiaokuqwq** [comment]
我觉得应该将选择权交给用户，其实是不稳定

**Comment by xiaokuqwq** [comment]
> #794

我觉得应该选择权交给用户，即使是不稳定的

**Comment by Yidadaa** [comment]
说得倒是轻松，到时候他们跑来问的是我

**Comment by Pa55w0rd** [comment]
> 说得倒是轻松，到时候他们跑来问的是我

hahahah
