### ISSUE TITLE
[Bug] docker 部署报错

### ISSUE THREAD

**Issue by INTKILOW** [Yidadaa/ChatGPT-Next-Web#1027]
部署命令（使用privoxy，curl www.google.com.hk 可以）
docker run -d -p 3000:3000 -e PROXY_URL="http://172.0.0.1:8118" yidadaa/chatgpt-next-web

报错
{
  "cause": {
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "224.0.0.1",
    "port": 443
  }
}

怎么解决着急

**Comment by Yidadaa** [comment]
代理问题，自行排查

**Comment by INTKILOW** [comment]
--net=host 加上 之后打字效果没了

**Comment by Yidadaa** [comment]
#209
