### ISSUE TITLE
[Bug] Nginx配置反代以及ssl后经常出现ECONNRESET错误

### ISSUE THREAD

**Issue by mmm1h** [Yidadaa/ChatGPT-Next-Web#1029]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
Nginx配置反代以及ssl后经常出现ECONNRESET错误

**如何复现**
定期出现 不是必现，偶尔会发生，然后刷新下网页或者过一会儿又好了

**截图**
![image](https://user-images.githubusercontent.com/34388791/233830887-6f2c72ec-9bef-4e9f-9aad-0074caf9479c.png)
![image](https://user-images.githubusercontent.com/34388791/233831198-d2cf68c2-2ce3-4f73-a8be-d5cd1f9c0c8c.png)

**一些必要的信息**
 - 系统：[ windows 10]
 - 浏览器： [chrome]
 - 版本： [b7b16aa]
 - 部署方式：[docker ]

下面是Nginx配置
```nginx
server {
    listen   3001 ssl http2;
    server_name  xx.xxx.xx;

    ssl_certificate      /etc/nginx/conf.d/op.crt;
    ssl_certificate_key  /etc/nginx/conf.d/op.key;
    ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_session_cache    shared:SSL:50m;
    ssl_session_timeout  6m;

	client_max_body_size 128M;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_read_timeout 60;
        proxy_connect_timeout 60;
        proxy_send_timeout 60;
        proxy_redirect     off;
        proxy_buffering off;
        proxy_cache off; 
        chunked_transfer_encoding on;
        keepalive_timeout 300; 
        tcp_nopush on;
        tcp_nodelay on;
        proxy_ssl_session_reuse on;
        }
}
```

**Comment by Yidadaa** [comment]
前端可以用nginx做些什么？

搭建静态资源服务器
反向代理分发后端服务（可以和nodejs搭配实现前后端分离）和跨域问题
根据User Agent来重定向站点
开发环境或测试环境切换（切换host）
url重写，使用rewrie规则本地映射
资源内容篡改
获取cookie做分流
资源合并
gzip压缩
压缩图片
sourceMap调试

---

这个项目和上面哪一项都不沾边，搞不清楚你们为什么这么执着于加 ngnix。

**Comment by AprilNEA** [comment]
请优先排查客户端的问题，切换设备和网络环境

**Comment by mmm1h** [comment]
> 前端可以用nginx做些什么？
> 
> 搭建静态资源服务器 反向代理分发后端服务（可以和nodejs搭配实现前后端分离）和跨域问题 根据User Agent来重定向站点 开发环境或测试环境切换（切换host） url重写，使用rewrie规则本地映射 资源内容篡改 获取cookie做分流 资源合并 gzip压缩 压缩图片 sourceMap调试
> 
> 这个项目和上面哪一项都不沾边，搞不清楚你们为什么这么执着于加 ngnix。

已经有证书部署了，所以就一并采用了https进行各项服务的访问，如果找不到原因的话我就关了ssl验证吧，反正能用

**Comment by mmm1h** [comment]
> 请优先排查客户端的问题，切换设备和网络环境

切换设备也会出现，切换网络环境问题不会复现 localhost或者http

**Comment by guotao** [comment]
> 前端可以用nginx做些什么？
> 
> 搭建静态资源服务器 反向代理分发后端服务（可以和nodejs搭配实现前后端分离）和跨域问题 根据User Agent来重定向站点 开发环境或测试环境切换（切换host） url重写，使用rewrie规则本地映射 资源内容篡改 获取cookie做分流 资源合并 gzip压缩 压缩图片 sourceMap调试
> 
> 这个项目和上面哪一项都不沾边，搞不清楚你们为什么这么执着于加 ngnix。

@mmm1h 加 nginx 应该只是想套 ssl，和反代问题应该是两个不太相关的。我不是用的docker部署，@mmm1h 可以看看 BASE_URL 配置是不是有问题。
