### ISSUE TITLE
[Feature] 增强自定义prompt模板的功能建议

### ISSUE THREAD

**Issue by chaosgpt** [Yidadaa/ChatGPT-Next-Web#1032]
**这个功能与现有的问题有关吗？**
现在的prompt模板主要用的是两个固定的来源，虽然也可以添加自定义的prompt模板，但是发现是浏览器缓存的，跨浏览器后就无法使用。

**你想要什么功能或者有什么建议？**
建议可以导入md|csv等格式文件的方式来增加自定义prompt模板内容，并缓存在服务器,一次导入整个实例都能使用。

**其他信息**
可能实现的思路：
1.在线抓取符合格式的md链接，并缓存到本地服务器。
2.在本工程的repo新建一个文件夹来读取custom.md文件，服务启动的时候一同加载。这样用户就可以随时添加自己的prompt模板更新。

**Comment by Yidadaa** [comment]
你可以修改 `./scripts/fetch.mjs`，加这个功能没几行代码
