### ISSUE TITLE
能否刚进入网页就直接需要输入密码

### ISSUE THREAD

**Issue by andlqs** [Yidadaa/ChatGPT-Next-Web#1039]
防止域名被扫描和污染

**Comment by shuaiplus** [comment]
nginx反向代理

**Comment by Yidadaa** [comment]
#741

**Comment by shuaiplus** [comment]
小白建议使用宝塔
![image](https://user-images.githubusercontent.com/100134295/233884453-4ff8ad87-268e-464f-94c3-f417ff1d2b85.png)
