### ISSUE TITLE
两个小疑问，有关复制按钮和CODE

### ISSUE THREAD

**Issue by t7aliang** [Yidadaa/ChatGPT-Next-Web#104]
1、我在宝塔用Docker部署的。但是页面上的复制按钮不能用，剪不到剪贴板，这个原因在哪里呢。
2、那个CODE1，CODE2，和CODE3都是什么……（可能问的见笑了），不知道怎么设置，也没看出它的作用。
3、我的页面好像不能自动向下滚动，GPT回复我的时候，要手动往下拉动。不知道是不是都这样。
我的环境变量是这样写的：
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION=18.15.0
YARN_VERSION=1.22.19
OPENAI_API_KEY=xxxxxxxxxxxxxx 
```
另外，期待那个密码访问的功能今后加进来。
最后，感谢作者和贡献者，也感谢项目的捐赠者，你们的贡献在推动文明的进步。

**Comment by gtang8** [comment]
1. 你设置了Code在终端输入这个code才能使用。
2. 请教Vercel怎样设置Code？

**Comment by t7aliang** [comment]
> 1. 你设置了Code在终端输入这个code才能使用。
> 2. 请教Vercel怎样设置Code？

我开始是这样理解的，然后在环境变量设置了CODE=code1,code2,code3
但是有没有这行变量是一样的，没有什么效果，不知道是哪里还需要配置。

**Comment by gtang8** [comment]
> 

Docker上已经实现CODE来控制终端，但是Vercel上的CODE输入后终端找不到输入CODE方法。
![image](https://user-images.githubusercontent.com/74369627/228253353-d5358114-fa23-4a0c-98ca-d77316857c9d.png)
![image](https://user-images.githubusercontent.com/74369627/228253502-4fc5258b-03cc-422b-a409-6270cee1f6ab.png)
下图是在docker上输入CODE
![image](https://user-images.githubusercontent.com/74369627/228253782-9dcd2000-213f-464c-accd-242f6edd439f.png)

**Comment by t7aliang** [comment]
> 你需要重新部署。

👌，刚看到今天上了1.6，我重新部署一下。

**Comment by tanpengsccd** [comment]
可能准确点说 是“[服务]访问密码”
