### ISSUE TITLE
[Bug] 根据要求生成的图片无法显示是怎么回事？

### ISSUE THREAD

**Issue by ZhuJianglai** [Yidadaa/ChatGPT-Next-Web#1040]
**Describe the bug**
根据要求生成的图片无法显示是怎么回事？

**Screenshots**
![image](https://user-images.githubusercontent.com/32724206/233850123-87d8485d-e3ab-45aa-a3fb-2933a61dc2ff.png)
这个是回复中的图片显示(https://i.imgur.com/OcXPgV7.png)](https://i.imgur.com/OcXPgV7.png)
![image](https://user-images.githubusercontent.com/32724206/233850206-99bd5def-884d-4c37-88ef-1ec370aaa78f.png)

**Deployment**
- [v ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Yidadaa** [comment]
#52 #431 #88
