### ISSUE TITLE
[Feature] 一键将md格式的对话内容新建为github的仓库文件,标题就是摘要+时间戳

### ISSUE THREAD

**Issue by xiangnanscu** [Yidadaa/ChatGPT-Next-Web#1041]
把github token填在environment. 这样便于不断的学习和存档. 你觉得怎样?

**Comment by xiangnanscu** [comment]
这是我昨天手动整的, 我忽然意识到这个功能, 符合本仓库一键的特色:
https://github.com/xiangnanscu/xiangnanscu.github.io/blob/main/about-pg-insert-or-get_or_create.md

**Comment by Yidadaa** [comment]
自行实现吧，大多数人用不到这个功能。

**Comment by Yidadaa** [comment]
之后会加 webdav 云存储
