### ISSUE TITLE
本地部署报错

### ISSUE THREAD

**Issue by echo-LuGuang** [Yidadaa/ChatGPT-Next-Web#1042]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
执行`yarn install`后执行`yarn dev`报错

**如何复现**
执行`yarn install`后执行`yarn dev`报错

**截图**
![image](https://user-images.githubusercontent.com/50095011/233891679-fce8df1b-3b29-45e5-972b-6796ec2c6924.png)

**一些必要的信息**
 - 系统：[windwos11]
 - 浏览器： [chrome]
 - 部署方式：[本地]

**Comment by Yidadaa** [comment]
升级到 nodejs 18 重试
