### ISSUE TITLE
[Bug] 通过docker部署后反向代理输出文字不是逐个打印

### ISSUE THREAD

**Issue by yn-ayw** [Yidadaa/ChatGPT-Next-Web#1044]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
[Bug] 通过docker部署后反向代理输出文字不是逐个打印，而是等半天所有的字一起出来。

**如何复现**
宝塔反向代理

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：ubuntu18.04
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：docker

**Comment by saoman** [comment]
@yn-ayw  楼主最后怎么解决的

**Comment by liuxingchi** [comment]
我也碰到了一样的问题，不知道咋回事

**Comment by yn-ayw** [comment]
> 我也碰到了一样的问题，不知道咋回事，能帮忙看下咋回事不 @Yidadaa 你解决了没 @yn-ayw



> @yn-ayw 楼主最后怎么解决的

如果你使用 ngnix 反向代理，需要在配置文件中增加下列代码：

# 不缓存，支持流式输出
proxy_cache off;  # 关闭缓存
proxy_buffering off;  # 关闭代理缓冲
chunked_transfer_encoding on;  # 开启分块传输编码
tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
keepalive_timeout 300;  # 设定keep-alive超时时间为65秒
如果你是在 netlify 部署，此问题依然等待解决，请耐心等待。
