### ISSUE TITLE
我在vercel的settings环境里面修改了core，但是新的core用不了，只能用第一次设置的core，改了等于没改，几个浏览器都试了[Bug] 

### ISSUE THREAD

**Issue by daoyuanyi** [Yidadaa/ChatGPT-Next-Web#1045]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by daoyuanyi** [comment]
我在vercel的settings环境里面修改了core，但是新的core用不了，只能用第一次设置的core，改了等于没改，几个浏览器都试了

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by daoyuanyi** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yifei ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 下午2:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Yidadaa/ChatGPT-Next-Web] 我在vercel的settings环境里面修改了core，但是新的core用不了，只能用第一次设置的core，改了等于没改，几个浏览器都试了[Bug]  (Issue #1045)






https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.
