### ISSUE TITLE
[Bug] Vercel Analytics 无法接收数据

### ISSUE THREAD

**Issue by Epiphany7725** [Yidadaa/ChatGPT-Next-Web#1047]
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
安装了分析包，但是网站依旧没有得到数据
![image](https://user-images.githubusercontent.com/59392437/233918660-1beb8e06-bf93-41aa-b047-ca853815fdc1.png)
![image](https://user-images.githubusercontent.com/59392437/233918712-c809133f-8c39-4242-8c86-7941461a8455.png)

**Comment by Yidadaa** [comment]
有延迟，过段时间就有了，建议自己接入谷歌或者百度的分析。
