### ISSUE TITLE
[Bug] proxychains4在mac下dev无法代理

### ISSUE THREAD

**Issue by EngsShi** [Yidadaa/ChatGPT-Next-Web#1051]
**Describe the bug**
mac环境dev调试，mac版proxychains4代理，proxychains启动时正常挂载，但是实际接口并未走代理通道。
编译docker没问题

**To Reproduce**
1. 配置proxychains.conf
`strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5 127.0.0.1 51837
`
2. 调试启动 proxychains4 -f ./proxychains.conf npm run dev
`
[proxychains] config file found: ./proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
`
3. 没有代理成功的 [proxychains] 日志，clash并未收到请求
`
[Proxy]  v1/chat/completions
[Base Url] https://api.openai.com
[Chat Stream]  [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
`

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1 (22E261)
 - Node v18.14.0
 - proxychains-ng 4.16  install with brew

**Comment by Yidadaa** [comment]
我建议你可以先用其他的 openai-proxy 项目，在 cloudflare 上搭建一个 openai 代理，然后通过修改 BASE_URL 的方式去访问，这样要比本地的梯子稳很多。

**Comment by lupguo** [comment]
1. 我在MAC本地运行也有同样的问题，proxychains也是同样的配置，一样的错误（Proxychains验证curl是正常可用的）。
本地希望网络走NextWeb Client -> MAC Local SOCKS5 -> OpenAI的链路，对React和NextJs不熟悉，不清楚这里网络转发是如何走的？
2. 通过公司网络（公司网已经直接支持访问Google等），没有任何代理配置，直接在webstorm里面运行`yarn run dev`，通过访问`127.0.0.1:3000`端口则可以正常访问和使用Chat，不清楚这里网络有什么差异？

**Comment by Yidadaa** [comment]
@lupguo 由于要兼容 vercel edge function 运行时，无法在 server function 内部使用 proxy，所以只能用 proxychains 曲线救国，可以等待 standalone 编译支持后，这个问题就不存在了 #1000

**Comment by lupguo** [comment]
@EngsShi @Yidadaa MAC的proxychains不生效的原因是因为MAC的SIP机制的一些现在，直接用`/usr/local/bin/yarn run dev`是相当于走默认网络，没有从代理出去。

解决办法，不走默认系统自带的yarn就可以正常代理
```
brew install yarn
proxychains4 /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn run dev
```

参考：https://github.com/rofl0r/proxychains-ng/issues/78
