### ISSUE TITLE
添加Edge Function运行区域设置

### ISSUE THREAD

**Issue by FourLeafTec** [Yidadaa/ChatGPT-Next-Web#106]
本来想提个PR的，但是测试过后发现我的实现不行，改成提issue了

Vercel设置Edge Function通过控制台设置不了，需要修改api里的config配置 [doc](https://vercel.com/docs/concepts/functions/edge-functions#edge-function-regions)
这块通过Project -> View Runtime Logs -> Functions，然后选择一个api就能看到了
可以确认现在的Edge Function的Region是global

我开始想通过添加环境变量EDGE_REGIONS来设置这块，结果上去一测试发现不对了，config直接无效了
通过测试发现Vercel读取api中的config比运行process.env早，所以环境变量设置的会变成未设置

这个config.regions配置即不支持表达式，也不支持functional，甚至也不支持执行方法返回

我目前在自己的fork里写死了Region了，不过毕竟不方便

**Comment by Yidadaa** [comment]
你是想指定 edge function 的运行区域？这个应该直接在 vercel 的控制台改就行了？

**Comment by Yidadaa** [comment]
region 设置会影响什么吗？服务的可用性？

**Comment by FourLeafTec** [comment]
从头说吧，我实际碰到的问题是访问chat-stream接口后台报EDGE_FUNCTION_INVOCATION_TIMEOUT 504错误

看前面的issue，怀疑亚洲区域是否会对Api访问造成影响
现在证明应该不是，不过作为一个挺有趣的课题，我觉得也可以想想

然后说我现在的情况，chat-stream接口一直访问不到，在POST方法入口设置了打印
```
export async function POST(req: NextRequest) {
  try {
    console.log("post chat steam start");
    const stream = await createStream(req);
    console.log("post chat steam end")
    return new Response(stream);
  } catch (error) {
    console.error("[Chat Stream]", error);
  }
}
```
这三处都无法打印，无论vercel还是docker还是codespaces里

**Comment by FourLeafTec** [comment]
找到问题在哪了

1. 注释config.runtime=edge,之后就能正常打印输出了
2. 我的账号计划和账单有问题，所以服务器响应的不是流式内容，而是固定内容，这部分内容没法被parser正常feed进去，内容如下

```
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

**Comment by flyapple2016** [comment]
能在vercel.json增加一个区域设置吗，设置成变量。
{
  "regions": ["sfo1"]
}
