### ISSUE TITLE
超出api请求速度限制

### ISSUE THREAD

**Issue by bengdada** [Yidadaa/ChatGPT-Next-Web#1060]
{
    "error": {
        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-WMuGHLZQoOmBPmuwmqhmHOru on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
        "type": "requests",
        "param": null,
        "code": null
    }
}
我知道这个是免费API的请求速率限制：
希望可以支持多个api 或者 有一个延迟回复请求，直接报错，请求就丢失了
我就瞎说哈，能用已经很感激了

**Comment by Yidadaa** [comment]
#363
