### ISSUE TITLE
[Bug] 关于更新不显示与访问密码不发挥作用 by daxiao

### ISSUE THREAD

**Issue by daxiao88** [Yidadaa/ChatGPT-Next-Web#1061]
关于更新不显示与访问密码不发挥作用
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ X] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [X ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
1.我的项目 已经更新到6B36B25,但是网页还是说我 d745d06。而且通过“前往更新”，去到github，显示的也是6B36B25
2.我在VERCEL，设置了环境变量，其中 有CODE密码。但在网页版中，把这个访问密码删除，也可以正常使用。那么，这个访问密码不是形同虚设了？

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
无法 上传

**一些必要的信息**
 - 系统：[比如 windows 10/
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]找不到，不好意思
 - 部署方式：[ vercel

**Comment by Yidadaa** [comment]
1. 检测更新有一小时左右的延迟
2. 重新部署 https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2

**Comment by daxiao88** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件已经收到。

**Comment by Yidadaa** [comment]
1. 项目一直都会更新，之后会放宽更新检测的周期
2. 修改环境变量后需要重新部署 vercel 项目才会生效，注意，不是新建一个项目，而是参考文档里点击 redeploy 按钮重新部署： https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2
3. 找找 add 按钮在哪

**Comment by daxiao88** [comment]
非常感谢。
问题1已经解决。主要原因是在环境变更变更 之后，要去重新部署，而不是新建项目。现在已经更新到最新版本了。
但是问题2，没有解决。
问题3，那个ADD按钮没有的。只有一个提示。

**Comment by daxiao88** [comment]
总算找到图片上传的地方了

![图片3](https://user-images.githubusercontent.com/117962022/234329229-2d8e8c60-60fa-49d0-8e6d-7c7664b6eda3.png)
上图，是显示已经解决问题，同步为最新的了。但是刚刚晚上又有更新，还没有及时同步过去。

![图片1](https://user-images.githubusercontent.com/117962022/234329214-7d5681b3-ad53-4dd3-ba0a-83a2f6bf0b50.png)
上图，是我的访问密码为空，但是正常访问。
![图片4](https://user-images.githubusercontent.com/117962022/234330433-735192de-c330-49d4-ac1b-c7f8051be1d5.png)
上图，是说明昨天已经设置2个密码了。包括api key,code.今天按照上图，再设置了一个code.
但是仍然是可以不问密码，或者随意填写密码都可以访问的。

**Comment by Yidadaa** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/16968934/234364395-94f1f044-deb3-4cd5-97ac-33a37536c8dd.png">

**Comment by Yidadaa** [comment]
你把前端的 api key 删了就知道了
