### ISSUE TITLE
[Bug] docker部署的怎么改这些基本文字，我从目录里找不到

### ISSUE THREAD

**Issue by shuaiplus** [Yidadaa/ChatGPT-Next-Web#1063]
![image](https://user-images.githubusercontent.com/100134295/234054498-9bfc7e25-8e24-4a49-9f08-050adba2bf7f.png)

 - 系统：[windows 10]
 - 浏览器： [chrome]
 - 版本： [最新版]
 - 部署方式：[docke]

**Comment by Yidadaa** [comment]
自己研究吧
