### ISSUE TITLE
[Bug] 未设置访问密码的情况下，系统提示“现在是未授权状态，请点击左下角设置按钮输入访问密码。”

### ISSUE THREAD

**Issue by yelcat** [Yidadaa/ChatGPT-Next-Web#1066]
**描述问题**
未设置访问密码的情况下，系统提示“现在是未授权状态，请点击左下角设置按钮输入访问密码。”

**如何复现**
未启用访问密码

**截图**

<img width="893" alt="截屏2023-04-25 09 28 40" src="https://user-images.githubusercontent.com/225305/234152730-94a1b6e9-105c-48fc-8e0f-9b1be435587f.png">

**Comment by Yidadaa** [comment]
API key 有问题，检查一下。

**Comment by Coolwinds** [comment]
一样的问题，打开后提示未授权，但其实可以继续对话。修改过一次api key
