### ISSUE TITLE
[Feature] 有没有可能支持多个API Key？

### ISSUE THREAD

**Issue by leozzyzheng** [Yidadaa/ChatGPT-Next-Web#1070]
**这个功能与现有的问题有关吗？**
无关

**你想要什么功能或者有什么建议？**
考虑到GPT-4或者其他API的收费价格跟GPT-3.5不在一个量级上，可能会为更贵的API申请单独的账号和KEY，所以希望能通过不同的Code来使用对应的KEY，这样可以更好的管理费用情况。

**有没有可以参考的同类竞品？**
暂时没有看到竞品

**其他信息**
无

**Comment by Yidadaa** [comment]
不支持不同 CODE 的映射，你可以自己修改代码实现此功能

**Comment by leozzyzheng** [comment]
欢迎此类PR吗？

**Comment by Yidadaa** [comment]
映射估计不太好配置？可以搞成 API_KEYS="code1=api1,code2=api2" 的形式

**Comment by leozzyzheng** [comment]
我感觉分成多个环境变量好点

API_KEY=
CODE=api0,api00,api000
API_KEY1=
CODE1=api1,api11,api111

这样不影响现有用法和使用人群
