### ISSUE TITLE
[Feature] 对话操作功能优化建议

### ISSUE THREAD

**Issue by GotoFox** [Yidadaa/ChatGPT-Next-Web#1071]
单条对话系统返回数据长度超长的时候，返回数据顶部的操作（复制、重试、删除）等功能按钮需要翻到最前面进行操作，似乎不太友好，是不是可以放到对话底部或侧边

![image](https://user-images.githubusercontent.com/68596145/234164954-c3a8d855-d76d-4c65-b61d-23844deb2519.png)

**Comment by Yidadaa** [comment]
到时候又会有人来问我为什么不放在顶上了，个人喜好问题罢了
