### ISSUE TITLE
[Feature] 支持通过URL地址直接创建与某个prompt相关联的对话

### ISSUE THREAD

**Issue by TrueRux** [Yidadaa/ChatGPT-Next-Web#1072]
**你想要什么功能或者有什么建议？**
可以考虑支持通过URL地址直接创建与某个prompt相关联的对话，例如<https://chat.xxx.com/prompt/translator>，这样就很方便地创造了一个关于翻译的对话场景。
可以在对话列表添加一个分享按钮用于生成链接或者链接二维码

**Comment by wwb7700** [comment]
这个建议非常好，希望可以采纳

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/897fc023-78af-461a-890e-021928b8813e)
