### ISSUE TITLE
[Bug] 本地部署成功,但是 api 报 Timeout

### ISSUE THREAD

**Issue by JaterLee** [Yidadaa/ChatGPT-Next-Web#1075]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [✔️] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [✔️] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
本地部署成功,但是 api 报 Timeout
{
  "cause": {
    "name": "ConnectTimeoutError",
    "code": "UND_ERR_CONNECT_TIMEOUT",
    "message": "Connect Timeout Error"
  }
}
终端代理是OK的, 不知道是哪个环节有问题, 请帮忙指点一下

**截图**
<img width="508" alt="image" src="https://user-images.githubusercontent.com/13514877/234182823-6cccd21a-1a66-4e44-ab58-4f9486238919.png">

**一些必要的信息**
 - 系统：macos 12.5.1
 - 浏览器： chrome
 - 版本：71aa9d0
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by Yidadaa** [comment]
本地部署只有 docker 支持代理，或者使用 proxychains 自行配置代理，具体搜 issue
