### ISSUE TITLE
设置是否显示gpt4.0

### ISSUE THREAD

**Issue by 1zyao** [Yidadaa/ChatGPT-Next-Web#108]
在看项目的源码中发现有这样一段：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/7f3cbaa064e063cf8295163e87105123f4c05bbc/app/store/app.ts#L53-L80
看起来在环境变量中把ENABLE_GPT4设置成false就行了但是在实际测试之后发现仅仅只是不能选gpt-4 gpt-4-0314 gpt-4-32k gpt-4-32k-0314在列表中仍然可以看见
如图：
![image](https://user-images.githubusercontent.com/107829654/228249495-0d759c64-7371-4105-bee3-c7c50b22e72a.png)

**Comment by Yidadaa** [comment]
你可以直接把 `ALL_MODELS` 里关于 gpt-4 的选项删掉
