### ISSUE TITLE
[Bug] app.ts 中用户输入记录打印失效

### ISSUE THREAD

**Issue by huangyuzhang** [Yidadaa/ChatGPT-Next-Web#1082]
**Describe the bug**
`./app/store/app.ts` 中 264 行存在打印用户输入的代码

```ts
console.log("[User Input] ", sendMessages);
```

但是本地测试和vercel的log中均没有展现

**To Reproduce**
simply run dev or build the app and send a message.

**Expected behavior**
在log中打印出用户输入的内容

**Deployment**
- [x] local
- [x] Vercel
- [ ] Server

**Comment by Yidadaa** [comment]
打在前端了，不是服务端
