### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LPtrichor** [Yidadaa/ChatGPT-Next-Web#1083]
请问一下在本地部署报下面这个错误咋办？
![image](https://user-images.githubusercontent.com/78304742/234263020-daa81ed9-e3ff-4a12-b0c5-ca9b6ca2d898.png)

**Comment by Yidadaa** [comment]
这哪里报错了，这不是一切正常？

而且你用错命令了，用 yarn build && yarn start
