### ISSUE TITLE
[Bug] 正常聊天提示请求接口失败invalid_request_error

### ISSUE THREAD

**Issue by wk901119** [Yidadaa/ChatGPT-Next-Web#1086]
正常聊天提示请求接口失败
model:gpt-3.5-turbo
错误如下
{
  "error": {
    "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}

**Comment by Yidadaa** [comment]
openai 的问题。
