### ISSUE TITLE
能增加多api并发吗？现在一个api访问一下就等半天[Feature] 

### ISSUE THREAD

**Issue by kugecf** [Yidadaa/ChatGPT-Next-Web#1087]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
#363
