### ISSUE TITLE
[Feature] 能否增加图片上传功能？？

### ISSUE THREAD

**Issue by kevins0116** [Yidadaa/ChatGPT-Next-Web#1091]
能否增加图片上传功能？？GPT4 API 已经用了 一个多月了   自制的miniGPT4 也挂载了  客户端缺少 图片上传功能，另外服务端和客户端能否做个分离 这样方便整合API 我用GPT4+miniGPT4 整合了一个API 接口 部署在独立服务器上，不知道怎么对接 这个客户端.....

**Comment by Yidadaa** [comment]
gpt3.5 和 gpt4 的 api 都不支持图片，暂时不准备支持 minigpt。

你可以通过修改 BASE_URL 来转发请求到你自己的服务上。

**Comment by kevins0116** [comment]
用Php写了一个 转发服务器 不能实现流传输  客户端应该是要修改些什么的奈何 vue3 next 不是特别懂..... 不知道怎么修改客户...

**Comment by kevins0116** [comment]
客户端其实可以加一个图片上传功能 后端可以融合 openai 的 img 接口 实现绘图功能
