### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wangzhen666999** [Yidadaa/ChatGPT-Next-Web#1097]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
docker部署：
docker run -d -p 3000:3000 -e OPENAI_API_KEY="sk-xxx" -e PROXY_URL="http://127.0.0.1:7890/" yidadaa/chatgpt-next-web

**如何复现**

**截图**
问题
![image](https://user-images.githubusercontent.com/66821718/234535210-8e53d923-98dd-4eee-b07b-bfdd04feafd6.png)

**一些必要的信息**
 - 系统： windows 10
 - 浏览器： chrome
 - 部署方式：docker

**Comment by wangzhen666999** [comment]
麻烦大佬帮忙看看  问题咋样能解决  谢谢！

**Comment by Yidadaa** [comment]
```
docker run -d -p 3000:3000 -e OPENAI_API_KEY="sk-xxx" --net=host -e PROXY_URL="http://127.0.0.1:7890" yidadaa/chatgpt-next-web
```

**Comment by wangzhen666999** [comment]
&nbsp;您好！
&nbsp;我本地有clash代理，本地docker启动服务，初始启动脚本为docker run -d -p 3000:3000 -e OPENAI_API_KEY="sk-xxx" -e PROXY_URL="http://127.0.0.1:7890" yidadaa/chatgpt-next-web ，启动服务后，聊天显示如下：

然后，换成启动脚本run -d -p 3000:3000 -e OPENAI_API_KEY="sk-xxx" --net=host -e PROXY_URL="http://127.0.0.1:7890" yidadaa/chatgpt-next-web
现在前端页面打不开了 



请问我这是啥子原因 求大佬帮助




送一轮明月&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yidadaa/ChatGPT-Next-Web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 下午5:41
***@***.***&gt;;
抄送:&nbsp;"送一轮明月 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yidadaa/ChatGPT-Next-Web] [Bug]  (Issue #1097)





 
Closed #1097 as completed.
