### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LycorisWind** [Yidadaa/ChatGPT-Next-Web#1099]
- [×] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [×] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
vecel部署，已按照操作文档fork本项目，并设置了自动更新，然而每次更新时都会出现部署错误的问题，需要手动重新部署。

**如何复现**
每次更新时。

**截图**

![Screenshot_20230426_173955](https://user-images.githubusercontent.com/109772864/234542061-1043e32b-6849-4c6f-8379-143e9f60bac4.jpg)
![Screenshot_20230426_170617_com tencent mm_edit_218914396752011](https://user-images.githubusercontent.com/109772864/234542080-8a9116b9-44a9-4526-8372-4e3308c25105.jpg)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器： edge
 - 版本： 2deb5cb
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
vercel 的问题，重新部署几次。
