### ISSUE TITLE
部署完在现要修改key哪修改key

### ISSUE THREAD

**Issue by 1441853031** [Yidadaa/ChatGPT-Next-Web#11]

**Comment by JeazW** [comment]
vercel部署后还可以在后台修改变量

**Comment by Yidadaa** [comment]
在你 Vercel 项目的 Environment Variables 页面修改：

文档：https://vercel.com/docs/concepts/projects/environment-variables

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/16968934/227459217-e452be75-da5d-40ce-93af-0a383a62bafb.png">
