### ISSUE TITLE
代码块 copy 复制按钮不生效

### ISSUE THREAD

**Issue by dev-lyw** [Yidadaa/ChatGPT-Next-Web#110]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/110804800/228269632-d4b0fc6a-548e-4e69-a49b-bfe9318b4394.png">

**Comment by Yidadaa** [comment]
请确认是否已经授予剪切板权限，详情查阅 https://web.dev/async-clipboard/#%E5%AE%89%E5%85%A8%E5%92%8C%E6%9D%83%E9%99%90

**Comment by geekbb** [comment]
<img width="436" alt="CleanShot 2023-03-28 at 23 15 12@2x" src="https://user-images.githubusercontent.com/46196358/228285023-8370bba9-ebc3-43e3-803e-f2778548ddf0.png">
 有效啊！
