### ISSUE TITLE
[Bug] NotFoundError: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by perandre** [Yidadaa/ChatGPT-Next-Web#1100]
**Describe the bug**
Error message after a reply timed out.

**To Reproduce**
In a conversation, continue chatting until it doesn't work anymore. This error has only been triggered a couple of times, both times it just appears as the bot is "thinking" for several minutes, then the error shows. 

**Deployment**
Server

**Desktop (please complete the following information):**
 - OS: Mac OS latest
 - Browser: Chrome latest

**Additional Logs**

    at div
    at div
    at eT (https://chat.example.io/_next/static/chunks/app/page-98631271340bf97d.js:1:35814)
    at div
    at div
    at eM (https://chat.example.io/_next/static/chunks/app/page-98631271340bf97d.js:1:39495)
    at div

**Comment by Yidadaa** [comment]
What's your version of code? Are you using latest code?

Attaching browser log and server log may help.

**Comment by perandre** [comment]
Latest code from stable branch.

I'll look at logs later when I'm back at a computer.
