### ISSUE TITLE
[Feature] 自定义网站标题与图标

### ISSUE THREAD

**Issue by morningos** [Yidadaa/ChatGPT-Next-Web#1104]
**这个功能与现有的问题有关吗？**
无关

**你想要什么功能或者有什么建议？**
- 可不可能增加两个环境变量，用来自定义网站的图标和标题？
- 当网站需要输入密码时，刚进入首页就弹窗提示输入密码

**有没有可以参考的同类竞品？**
无

**其他信息**
最近给朋友用，感觉输入密码的流程有些麻烦

**Comment by Yidadaa** [comment]
1. 不可以
2. 之后会做

**Comment by Yidadaa** [comment]
#1039
