### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wqjuser** [Yidadaa/ChatGPT-Next-Web#1109]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在像iPhone se2这样的小屏手机上，上下两部分区域占用了比较大的面积造成中间的对话列表显示的内容很小，能否在小屏手机上缩小上下两部分占用的屏幕面积呢？

**如何复现**
小屏手机的通用问题

**截图**

<img width="375" alt="微信图片_20230427120233" src="https://user-images.githubusercontent.com/19888942/234756594-36ccfa8c-742c-40c4-8243-14a573b7c324.png">

**一些必要的信息**
 - 系统：iPhone se2
 - 浏览器： chrome
 - 版本： 最新版本
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
灵活使用“添加到主屏幕”功能。
