### ISSUE TITLE
[Feature] 是否支持 WebSocket ?

### ISSUE THREAD

**Issue by wang20150419** [Yidadaa/ChatGPT-Next-Web#1111]
**这个功能与现有的问题有关吗？**
无关

**你想要什么功能或者有什么建议？**
如果能支持 Websocket，则可以很方便地 使用 cloudflare 中转。
当然，现在的方式也可 cloudflare 中转，但是需要申请一个新域名。假定我已有一个域名并使用 cloudflare中转，如果支持 Websocket的话，就可使用现有域名了。
（对WEB开发不懂，可能概念上有问题。只是一个设想）

**有没有可以参考的同类竞品？**
无

**其他信息**
无

**Comment by Yidadaa** [comment]
你知道自己在说什么吗？
