### ISSUE TITLE
[Bug] 余额显示

### ISSUE THREAD

**Issue by umonaca** [Yidadaa/ChatGPT-Next-Web#1117]
一个多人网站是不应该把余额显示在界面上的，这部分信息应该属于只有管理员才能从后台知道的隐私。
![chrome_XQkNhATE1o](https://user-images.githubusercontent.com/53662960/235033659-110b2371-0765-4fb6-9743-0b825979428c.jpg)

**Comment by Yidadaa** [comment]
自己改代码去掉，这个项目是给私人部署用的
