### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zui-lang** [Yidadaa/ChatGPT-Next-Web#1121]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
通过Vercel部署，有报错，报错提示
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
但是通过设置中的余额查询显示还有18刀的余额，在https://chat.openai.com/中是可以正常使用的
**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![image](https://user-images.githubusercontent.com/77880495/235041776-a26358c3-59eb-4688-b4f0-a2c7d7441534.jpeg)
![image](https://user-images.githubusercontent.com/77880495/235041801-ade6309a-681d-43ce-aa46-609cf02d40ac.png)
**一些必要的信息**
 - 系统：ios 16
 - 浏览器：chrome
 - 版本： 6419ce3
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
