### ISSUE TITLE
[Feature] model settings per conversation

### ISSUE THREAD

**Issue by TTTPOB** [Yidadaa/ChatGPT-Next-Web#1123]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that the ChatGPTWeb application only allows me to choose a model globally for each conversation, whereas I find it would be more useful to have per-conversation model settings.

**Describe the solution you'd like**
I would like the ability to choose and change the model for each conversation individually. This way, I can utilize different models like gpt3.5-turbo, gpt4-0314, or any additional models that may become available in the future, depending on the context and requirements of each conversation.

**Describe alternatives you've considered**

**Additional context**
Having per-conversation model settings would enhance the flexibility and versatility of ChatGPTWeb by allowing users to select the most appropriate model for each conversation, resulting in improved chat experience and satisfaction.

**您的功能请求是否与问题有关？请描述。**
是的，问题在于ChatGPTWeb应用程序只允许我为每个对话全局选择一个模型，而我认为应该有每个对话的模型设置。这样，我可以根据每个对话的上下文和需求使用不同的模型，例如gpt3.5-turbo，gpt4-0314等。

**请描述您想要的解决方案。**
我希望在可以每个对话中单独选择和更改模型。这样，根据每个对话的上下文和需求，我可以使用不同的模型，例如gpt3.5-turbo、gpt4-0314或将来可能提供的其他模型。

**描述您考虑过的替代方案。**

**附加背景信息**
每个对话的模型设置将增强ChatGPTWeb的灵活性和多功能性，允许用户为每个对话选择最合适的模型，从而提高聊天体验和满意度。

**Comment by Yidadaa** [comment]
#1124
