### ISSUE TITLE
[Bug] Mask model config not works

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#1124]
**Describe the bug**
Mask model config not works

**To Reproduce**
Create chat from template, and send some messages.

**Expected behavior**
Should use mask model config, not global config.

**Deployment**
All

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by cishan-zz** [comment]
好像有一部分是有作用的。随机性和话题新鲜度没问题。BUG是上下文条数
