### ISSUE TITLE
[Bug] 中文回复乱码

### ISSUE THREAD

**Issue by admina1222** [Yidadaa/ChatGPT-Next-Web#1129]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
让它写小说，它回答一开始正常，但是到了后面似乎乱码了。具体如图，多次复现该问题。经测试似乎使用GPT-4才会出现问题。

**如何复现**
提问：帮我写一篇中文奇幻小说或者类似的提问方式。

**截图**
<img width="1191" alt="截屏2023-04-28 11 52 37" src="https://user-images.githubusercontent.com/76727661/235050958-e9dd878b-a8bc-4a76-bc09-34adc95a1c6c.png">
<img width="1191" alt="截屏2023-04-28 11 43 55" src="https://user-images.githubusercontent.com/76727661/235050984-bd04f11e-c00f-4298-b121-8b44528bb6af.png">
<img width="1191" alt="截屏2023-04-28 12 16 57" src="https://user-images.githubusercontent.com/76727661/235053037-f754c3ec-c7b2-490b-aa1c-5b909c78311d.png">

**一些必要的信息**
 - 系统：macOS 13.3.1
 - 浏览器： chrome
 - 版本： 6419ce3
 - 部署方式：vercel部署

**Comment by Yidadaa** [comment]
设置里调整 temperature

**Comment by Yidadaa** [comment]
到 0 和 1 之间
