### ISSUE TITLE
[Feature] 有计划使用Access Token方式登录吗

### ISSUE THREAD

**Issue by Tky2022** [Yidadaa/ChatGPT-Next-Web#1133]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
是否有计划支持使用：Access Token方式

**有没有可以参考的同类竞品？**
[chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web#%E4%BB%8B%E7%BB%8D)
[pandora](https://github.com/pengzhile/pandora)

**其他信息**
1、发现使用Access Token的方式在使用体验上会感觉到更加智能；
2、这是类似于直接登录的免费使用方法；
3、依然还是使用体验上的，或许可以接入第三方；
4、更方便的跨端跨网使用；
5、不过使用上有效的问题暂时不清楚是否可以自动延续；
6、更广泛的支持能力；

**Comment by Tky2022** [comment]
https://github.com/Chanzhaoyu/chatgpt-web#%E5%A1%AB%E5%86%99%E5%AF%86%E9%92%A5
![image](https://user-images.githubusercontent.com/108245618/235061778-a1d8133a-4020-4a66-bc87-d39d668d87e7.png)

**Comment by Yidadaa** [comment]
不稳定，不支持

**Comment by Tky2022** [comment]
好的

**Comment by Tky2022** [comment]
> 不稳定，不支持

好的
