### ISSUE TITLE
[Bug] 用了这个docker之后，为什么我的open ai API key提示泄露了？

### ISSUE THREAD

**Issue by weicun581** [Yidadaa/ChatGPT-Next-Web#1134]
![image](https://user-images.githubusercontent.com/29628953/235062957-d33289cb-8f94-4ec4-984c-d2dbdc24db07.png)

**Comment by Yidadaa** [comment]
自己看看是不是存 github 去了

**Comment by MichelleLi9097** [comment]
我一直在用，没有出现这种情况

Yifei Zhang ***@***.***> 于2023年4月28日周五 14:32写道：
