### ISSUE TITLE
[Bug] 最新的代码部署到 Netfily 报错

### ISSUE THREAD

**Issue by jasonarcadedevhouse** [Yidadaa/ChatGPT-Next-Web#1135]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by Neu070224** [comment]
描述問題：
       最新的代碼部署到vercel沒有問題，部署到netlify就報錯；

如何復現：
      代碼自動部署到netlify，和vercel一樣部署；

build異常日志如下：
8:14:18 PM: Bundling of edge function failed
8:14:18 PM: ────────────────────────────────────────────────────────────────
8:14:18 PM: ​
8:14:18 PM: Error message
8:14:18 PM: Could not load edge function at '/opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/index.ts'. More on the Edge Functions API at https://ntl.fyi/edge-api.
8:14:18 PM: ​
8:14:18 PM: Error location
8:14:18 PM: While bundling edge function
8:14:18 PM: ​
8:14:18 PM: Resolved config

**Comment by Yidadaa** [comment]
我推荐用 vercel，其他的没时间管

**Comment by Neu070224** [comment]
> 我推荐用 vercel，其他的没时间管

多谢楼主的贡献！我们也在您代码的基础上，新增了STT功能，不知道是否可以上传到主分支？

**Comment by Yidadaa** [comment]
可以提交一个 pr
