### ISSUE TITLE
[Bug] 当在“设置”切换到gpt-4模型之后，新建聊天，提示 "The model: `gpt-4` does not exist"

### ISSUE THREAD

**Issue by RalstonLiu** [Yidadaa/ChatGPT-Next-Web#1139]
**Describe the bug**
当在“设置”切换到gpt-4模型之后，新建聊天，提示模型不存在。

我的账户已经获得了gpt-4的API使用权限。

**Screenshots**

<img src="https://img.laoda.de/i/2023/04/28/fg3fi9-0.webp" alt="image-20230428093359912" style="zoom:25%;" />

<img src="https://img.laoda.de/i/2023/04/28/r1h81l-0.webp" alt="image-20230428163504971" style="zoom: 33%;" />

<img src="https://img.laoda.de/i/2023/04/28/r2bx3n-0.webp" alt="image-20230428163649367" style="zoom:33%;" />

**Deployment**
- Docker

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Browser: 版本 112.0.5615.137（正式版本） (arm64)
 - Version chatgpt-next-web 6419ce3

**Comment by zky001** [comment]
可以切换到gpt-4-0314的那个模型
![image](https://user-images.githubusercontent.com/9131265/235104291-9d6183c1-b3c1-4b9c-8971-ffe7a0a78538.png)

**Comment by Yidadaa** [comment]
openai 的问题，我实测可以用 gpt4

**Comment by RalstonLiu** [comment]
> 可以切换到gpt-4-0314的那个模型 ![image](https://user-images.githubusercontent.com/9131265/235104291-9d6183c1-b3c1-4b9c-8971-ffe7a0a78538.png)

刚刚试了下这个OK，谢谢

**Comment by RalstonLiu** [comment]
> openai 的问题，我实测可以用 gpt4

感谢作者，我刚刚试了下gpt-4，确实又可以用了 = =

**Comment by Sha1rholder** [comment]
我也出现了该问题，切模型到0314也没用，怎么回事呢？

**Comment by sd4324530** [comment]
浏览器换成无痕，就可以了，是不是和浏览器缓存有关啊
