### ISSUE TITLE
不支持arm的docker吗

### ISSUE THREAD

**Issue by style6** [Yidadaa/ChatGPT-Next-Web#114]
不支持arm的docker吗

**Comment by AprilNEA** [comment]
可以尝试自行构建

**Comment by gugui90** [comment]
root@ip-172-31-38-211:~/chatgpt# bash setup.sh 
fatal: destination path 'ChatGPT-Next-Web' already exists and is not an empty directory.
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
Enter OPENAI_API_KEY: xxx
Enter CODE: 123
Enter PORT: 3000
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
菜鸟一个, 求问这是啥意思 这两个文件不存在搞不太明白

**Comment by Yidadaa** [comment]
@gugui90 用 docker 部署吧

**Comment by hibobmaster** [comment]
我构建了支持arm的image
docker pull hibobmaster/chatgptnextweb:latest

**Comment by Yidadaa** [comment]
@hibobmaster 能否提供 Dockerfile 脚本，提个 PR？
