### ISSUE TITLE
Error: Could not find a production build

### ISSUE THREAD

**Issue by dqzboy** [Yidadaa/ChatGPT-Next-Web#1140]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
最新版本yarn启动没有prod环境

**如何复现**
yarn start 启动

**截图**
Error: Could not find a production build
![image](https://user-images.githubusercontent.com/42825450/235101303-c861d001-af9f-4235-96b4-0520aadb6a6b.png)

**一些必要的信息**
 - 系统：centos 7
 - 浏览器: chrome
 - 版本： 最新版本
 - 部署方式：源码编译

**Comment by Yidadaa** [comment]
漏了 yarn build

**Comment by dqzboy** [comment]
我是yarn build之后才执行的yarn start；使用yarn dev可以正常启动

**Comment by Yidadaa** [comment]
nodejs 版本？

项目库本身不太可能出问题，不然早就挂一片了。

**Comment by dqzboy** [comment]
nodejs：v16.19.1   今天更新之后出现的问题  之前版本没问题的
安装方式是编译安装的

**Comment by Yidadaa** [comment]
升级到 18 重试下

**Comment by dqzboy** [comment]
18版本 centos7 升级上去有问题  我先yarn dev使用着
