### ISSUE TITLE
[Feature] langchain LLM API as chat option, alternative to GPTs 

### ISSUE THREAD

**Issue by seshubonam** [Yidadaa/ChatGPT-Next-Web#1146]
**Is your feature request related to a problem? Please describe.**
Code is great! No problem with implementation. 

**Describe the solution you'd like**
Can you guide where to change the code for adding an external API as one of the LLM options, I have a langchain implementation that can be accessed through an API. Would like to connect this model to this chat app as an option. 

If current GPT models are connected through APIs, I'm assuming another API in a standard format should be possible to add within the code. 
Kindly let me know if this is possible and what standard the API format should be. 

**Describe alternatives you've considered**
Alternative is to just wait for the dev gods to deliver!

**Comment by Yidadaa** [comment]
Of course you can! check this https://github.com/go-skynet/LocalAI

You can deploy your service with a mimic endpoint, which accepts the request params same as OpenAI, and change the BASE_URL to your service endpoint.

**Comment by Yidadaa** [comment]
You can find my email in my github profile. No special reasons for open source, code just for fun :)
