### ISSUE TITLE
[Feature] 将 Prompt 模板放在新建面具预设部分

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#1147]
**这个功能与现有的问题有关吗？**
/

**你想要什么功能或者有什么建议？**

1、聊天页中的`prompt按钮`和`面具`感觉有点冲突，可以将 prompt 模板放在编辑预设面具中，增加一个快捷导入 prompt 按钮。然后把聊天页的`prompt按钮`拿掉，对话框 / 激活 prompt 倒是可以保留。

2、当新建预设角色面具时，觉得应该直接弹出预设设置框，而不是先增加预设再对其编辑，操作逻辑有点别扭。

3、还有一点不理解，增加预设时，system和user，谁的效果更好，默认的预设好像是user，但是我看新建预设时，默认选中的是system

4、默认预设是只读，只读的话，就没必要显示那么多东西了，直接用一个文本把prompt显示出来就行，或者把只读状态拿掉，默认预设也可以编辑。

一点点体验上的建议和直观感受，采不采纳由作者决定，辛苦~

**有没有可以参考的同类竞品？**
/

**其他信息**
/

**Comment by Yidadaa** [comment]
1. 面具是一系列 prompt 的组合，不代表可以替代预设 prompt，聊天时输入其他预设 prompt 是非常高频的操作。
2. 之后会改
3. 去问 chat gpt
4. 不置可否
