### ISSUE TITLE
[Feature] 将此工具变成电脑插件

### ISSUE THREAD

**Issue by CMXX648** [Yidadaa/ChatGPT-Next-Web#1149]
不久后能实现将该网页变成电脑插件，桌面浮窗，点击即用吗？

如果可以的话，希望能为此项目提供一份动力

**Comment by mushan0x0** [comment]
你说的是AI0x0吗。。 https://ai0x0.com

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/29084441/235213876-6e934844-de59-4ea9-a039-053a9e1f6425.png">

**Comment by Yidadaa** [comment]
@mushan0x0 好东西
