### ISSUE TITLE
[Feature] 修改标题的UI不统一

### ISSUE THREAD

**Issue by mushan0x0** [Yidadaa/ChatGPT-Next-Web#1150]
**这个功能与现有的问题有关吗？**

#817 这里面也提到过，有点不太好看

<img width="735" alt="image" src="https://user-images.githubusercontent.com/29084441/235215116-2cced0e0-2a40-4637-b8d2-3c0242eb1845.png">

**你想要什么功能或者有什么建议？**

使用统一的界面UI实现

**Comment by Yidadaa** [comment]
之后统一做
