### ISSUE TITLE
[Bug] 进入设置弹窗end date must come after start date，

### ISSUE THREAD

**Issue by joezhn2020** [Yidadaa/ChatGPT-Next-Web#1154]
进入设置会弹窗end date must come after start date，余额不能查询

**Comment by 1395173231** [comment]
可以尝试像我这样修改代码, 以修复这个问题: https://github.com/Yidadaa/ChatGPT-Next-Web/commit/870ff6a77abbaa1ffa7a368860894e7faa0e8aec

**Comment by 1395173231** [comment]
> > 可以尝试像我这样修改代码, 以修复这个问题: [870ff6a](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/870ff6a77abbaa1ffa7a368860894e7faa0e8aec)
> 
> 修改后仍无法获取余额
> ![image](https://user-images.githubusercontent.com/57057288/235291319-0fa6d348-5e00-4c8b-b883-3de6d669370c.png)
> ![image](https://user-images.githubusercontent.com/57057288/235291320-5a66ac63-6838-480f-a7db-09dec49bd249.png)
> 
如果你使用了cdn,需要刷新一下缓存
![Screenshot_20230429_165920_Samsung Internet.jpg](https://user-images.githubusercontent.com/35016247/235296041-03092473-9a92-48d0-b7c2-16265eb165f4.jpg)
