### ISSUE TITLE
[Bug] end_date must come after start_date,无法获取余额

### ISSUE THREAD

**Issue by 1395173231** [Yidadaa/ChatGPT-Next-Web#1156]
4月29日无法获取余额,获取月初时间存在逻辑错误,导致startOfMonth为5月1日
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/b0cd8579f12624a4f7c494244e1ea80858746ee3/app/requests.ts#LL105C43-L105C43

**Comment by Yidadaa** [comment]
#1154

**Comment by Yidadaa** [comment]
耐心等待修复
