### ISSUE TITLE
[Feature] 有没可能加个注册用户界面

### ISSUE THREAD

**Issue by KingfuZhang** [Yidadaa/ChatGPT-Next-Web#1157]
限制注册的用户使用，管理员可以给他开通或关闭使用权限？
譬如有时候我把这个网站的密码给了朋友，朋友又给了其他人，导致API余额迅速减少，我也可以查询到有多少人使用这个网站

**Comment by liqiujiong** [comment]
社区不提供这个功能，商业化功能请自行二开
