### ISSUE TITLE
[Bug] 部署时报错，复现率100%

### ISSUE THREAD

**Issue by NianBroken** [Yidadaa/ChatGPT-Next-Web#1158]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [X] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [X] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [X] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
部署时报错，复现率100%

**如何复现**
重新部署时仍报错

**截图**
![image](https://user-images.githubusercontent.com/57057288/235284509-5c2669c7-63bf-4ff1-9012-9c675b9271a5.png)

**一些必要的信息**
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
skip check
