### ISSUE TITLE
[Feature] 面具启动页 如何默认不勾选？

### ISSUE THREAD

**Issue by BarrySong** [Yidadaa/ChatGPT-Next-Web#1163]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请问 设置 里的 面具启动页，如何默认不勾选？

**截图**
![image](https://user-images.githubusercontent.com/23122409/235288302-f35a6264-ba67-41e2-9114-d25a6cbc6544.png)

**一些必要的信息**
 - 系统：[任何设备]
 - 浏览器： [ chrome, safari]
 - 版本： [b0cd857]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
自己改代码咯

**Comment by VMCoud** [comment]
config.ts文件dontShowMaskSplashScreen: false, 改为true
