### ISSUE TITLE
CI/CD is slow

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#117]
<img width="435" alt="image" src="https://user-images.githubusercontent.com/16968934/228331850-719f6f6f-10c3-43cb-b691-42d5b5812a81.png">

The linking of npm packages has become slower, taking 1m20s compared to the previous 32s.

To resolve this issue, it is recommended that we separate devDependencies from dependencies to optimize package linking.

**Comment by MrThanlon** [comment]
这还慢啊
