### ISSUE TITLE
[Bug] 携带消息数未遵循面具设置，使用的全局设置

### ISSUE THREAD

**Issue by Bisstocuz** [Yidadaa/ChatGPT-Next-Web#1177]
**Describe the bug**
当全局设置携带消息数设置为 6，面具携带消息数设置为 2 时，发送请求 `chat-stream` 仍会发送 6 条历史数据。

**To Reproduce**

**Expected behavior**
遵循面具的局部设置。

**Screenshots**

**Deployment**
- [x] Docker
- [ ] Vercel
- [x] Server

**Desktop (please complete the following information):**
 - Version 2,0

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
#1124
