### ISSUE TITLE
关于chatgpt回答对话框的建议

### ISSUE THREAD

**Issue by yanglyu902** [Yidadaa/ChatGPT-Next-Web#118]
非常喜欢这个项目！有两个小建议：
1. chatgpt在写回答的时候，随着文字变多，对话框在不断地向上移动，导致很难看清内容。[官方](https://chat.openai.com/chat)的解决方案是如果用鼠标滚轮上滑，那么对话框的位置就被固定，下方新生成的文字不会影响对话框的位置。希望可以implement一下这个逻辑。
2. 对话框移动导致的另一个问题是在chatgpt生成对话时用户很难点击到`stop`按钮，因为按钮位置随着对话框在不断上移（甚至在跟着文字左右移动）。希望可以把`stop`按钮换一个固定的位置，或者引入1中的固定对话框的feature。

谢谢！

**Comment by hk112019** [comment]
+1
