### ISSUE TITLE
[Feature] One-Click Fly.io Deployment

### ISSUE THREAD

**Issue by fanbinne** [Yidadaa/ChatGPT-Next-Web#1180]
Like Vercel but with Docker things

**Comment by Yidadaa** [comment]
Plans
All plans require a credit card. Each organization starts on the Hobby plan, which is a straightforward pay-as-you-go option. 

We don't offer a "free tier." Instead, we offer some free resource allowances that apply to all plans, including the Hobby plan, and includes enough usage per month to run a small full-stack app, full-time, for free.

**Comment by Yidadaa** [comment]
https://fly.io/docs/about/pricing/

**Comment by alonemeow** [comment]
Fly.io's free allowance is enough actually. @Yidadaa

**Comment by devsfactory** [comment]
fly.io looks cool, and not blocked China
