### ISSUE TITLE
[Bug] 修改\app\store\config.ts参数后，默认的配置参数未发送改变（已清除缓存、已使用无痕浏览器）

### ISSUE THREAD

**Issue by NianBroken** [Yidadaa/ChatGPT-Next-Web#1184]
**Describe the bug**
修改`\app\store\config.ts`参数后，默认的配置参数未发送改变（已清除缓存、已使用无痕浏览器）

**To Reproduce**
任何时候

**Expected behavior**
修改`\app\store\config.ts`后，设置界面的默认参数能随之改变。

**Screenshots**
![image](https://user-images.githubusercontent.com/57057288/235404899-54613bc9-9a79-49e3-9d2d-2d539f242267.png)
![image](https://user-images.githubusercontent.com/57057288/235404910-98d691fe-3492-4e3d-b60b-2138c7c46f37.png)
![image](https://user-images.githubusercontent.com/57057288/235404923-7b088ab4-9737-4b38-abf2-ecde5ff98f1d.png)

**Deployment**
- [x] Docker
- [x] Vercel
- [x] Server

**Desktop (please complete the following information):**
Microsoft Edge
版本 112.0.1722.64 (正式版本) (64 位)

**Smartphone (please complete the following information):**
小米10

**Additional Logs**
没有

**Comment by Yidadaa** [comment]
我不会提供任何代码二开的建议或者指导，请自行摸索。
