### ISSUE TITLE
[BUG]相同自定义API，在其他项目可正常使用，但在本项目使用时返回404 page not found

### ISSUE THREAD

**Issue by NianBroken** [Yidadaa/ChatGPT-Next-Web#1185]
在[BetterChatGPT](https://github.com/ztjhz/BetterChatGPT "BetterChatGPT")中填入免费API`https://free.churchless.tech/v1/chat/completions`时可正常使用。
![image](https://user-images.githubusercontent.com/57057288/235415180-7b97401c-a156-4a34-8bf6-39edd5b799ad.png)
![image](https://user-images.githubusercontent.com/57057288/235415230-0e4b9a70-a67c-4a4c-b591-ba8aceffda58.png)

但在[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/ "ChatGPT-Next-Web")的环境变量`BASE_URL`中填入`https://free.churchless.tech/v1/chat/completions`或`free.churchless.tech/v1/chat/completions`却返回`404 page not found`
![image](https://user-images.githubusercontent.com/57057288/235415041-105cd3fd-fc76-4914-b299-71a81295723e.png)
![image](https://user-images.githubusercontent.com/57057288/235415118-46f6b285-6ef1-4461-bbd3-911407a952cb.png)

**Comment by 1395173231** [comment]
> 在[BetterChatGPT](https://github.com/ztjhz/BetterChatGPT)中填入免费API`https://free.churchless.tech/v1/chat/completions`时可正常使用。 ![image](https://user-images.githubusercontent.com/57057288/235415180-7b97401c-a156-4a34-8bf6-39edd5b799ad.png) ![image](https://user-images.githubusercontent.com/57057288/235415230-0e4b9a70-a67c-4a4c-b591-ba8aceffda58.png)
> 
> 但在[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/)的环境变量`BASE_URL`中填入`https://free.churchless.tech/v1/chat/completions`或`free.churchless.tech/v1/chat/completions`却返回`404 page not found` ![image](https://user-images.githubusercontent.com/57057288/235415041-105cd3fd-fc76-4914-b299-71a81295723e.png) ![image](https://user-images.githubusercontent.com/57057288/235415118-46f6b285-6ef1-4461-bbd3-911407a952cb.png)

只需填写baseurl而不是完整路径，https://free.churchless.tech

**Comment by Joackk** [comment]
> > 在[BetterChatGPT](https://github.com/ztjhz/BetterChatGPT)中填入免费API`https://free.churchless.tech/v1/chat/completions`时可正常使用。 ![image](https://user-images.githubusercontent.com/57057288/235415180-7b97401c-a156-4a34-8bf6-39edd5b799ad.png) ![image](https://user-images.githubusercontent.com/57057288/235415230-0e4b9a70-a67c-4a4c-b591-ba8aceffda58.png)
> > 但在[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/)的环境变量`BASE_URL`中填入`https://free.churchless.tech/v1/chat/completions`或`free.churchless.tech/v1/chat/completions`却返回`404 page not found` ![image](https://user-images.githubusercontent.com/57057288/235415041-105cd3fd-fc76-4914-b299-71a81295723e.png) ![image](https://user-images.githubusercontent.com/57057288/235415118-46f6b285-6ef1-4461-bbd3-911407a952cb.png)
> 
> 只需填写baseurl而不是完整路径，https://free.churchless.tech

如果路径不是/v1/chat/completions，而是/chat/completions，也是直接填写url即可吗？
