### ISSUE TITLE
移动端关闭设置界面后，会出现bug，每次必现，如图

### ISSUE THREAD

**Issue by ruixing1001** [Yidadaa/ChatGPT-Next-Web#119]
![image](https://user-images.githubusercontent.com/128834242/228401241-494dcd53-42cc-4007-8086-893249cb6d8a.png)

**Comment by iSource** [comment]
@Yidadaa 导致这个问题的原因是：**移动端关闭Settings页面时，触发了<Chat>中textarea的自动聚焦功能，但是此时的SideBar是show状态。**

我在考虑2个方案：
1. 简单的去掉autoFocus功能，以规避这个问题的出现，但是<Chat>渲染后的autoScroll功能依赖于autoFocus。
2. 如果要保留autoFocus功能，可能需要在React渲染时能感知到是full模式还是mini模式。

长远来看增加对展示模式的感知（full模式/mini模式），有利于多端更方便做个性化。
