### ISSUE TITLE
[Bug] 本地运行以后有这个错误，不太懂react，有大佬讲讲是怎么回事吗？ 有3个错误，谢谢你

### ISSUE THREAD

**Issue by ourcss** [Yidadaa/ChatGPT-Next-Web#1197]
本地运行以后有这个错误，不太懂react，有大佬讲讲是怎么回事吗？
有3个错误

**Comment by ourcss** [comment]
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/105355582/235579147-082d49af-794a-4a77-b0a9-936d6e33688d.png">

**Comment by ourcss** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/105355582/235579217-713a4cac-775a-4760-a517-bd248595d8ac.png">

**Comment by ourcss** [comment]
也是最新拉取的代码，yarn 安装依赖运行就报这3个错误

**Comment by Yidadaa** [comment]
启动时用 yarn build && yarn start，为什么不看文档？
