### ISSUE TITLE
[Feature] 优化新建预设

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#1198]
**这个功能与现有的问题有关吗？**
/

**你想要什么功能或者有什么建议？**
新建预设时，预设会直接加进去，万一我又不想加了，点了叉号`×`，还是会存在一条空白预设，可不可以加一个`确认添加`的按钮，点确认添加按钮且预设不为空时（为空时提醒用户添加至少一条预设），才会被添加进去。
![1](https://user-images.githubusercontent.com/48620527/235581781-298a8fd6-e3c4-496d-aff8-706b80ef2191.gif)

然后左上角改为新建...可能更好一些，右下角按钮在新建时去掉，变成`确认添加`按钮。
![image](https://user-images.githubusercontent.com/48620527/235581767-5c046dd6-585a-4e95-9176-264d518590fb.png)

作者辛苦😊

**有没有可以参考的同类竞品？**
/

**其他信息**
/

**Comment by Yidadaa** [comment]
不行，我不同意
