### ISSUE TITLE
socks5/http/https proxy

### ISSUE THREAD

**Issue by MrThanlon** [Yidadaa/ChatGPT-Next-Web#120]

**Comment by MrThanlon** [comment]
WIP

**Comment by wk-mike** [comment]
是由于nodejs不支持http_proxy导致的，https://github.com/Yidadaa/ChatGPT-Next-Web/issues/166

**Comment by Yidadaa** [comment]
已被 BASE_URL 替代。 #172

**Comment by MrThanlon** [comment]
> 已被 BASE_URL 替代。 #172

不冲突，两者都可以有，BASE_URL仍然需要配置反向代理

**Comment by jeanlyn** [comment]
是的, 代理跟BASE_URL不冲突, 可以参考另一项目的做法: https://github.com/ddiu8081/chatgpt-demo

**Comment by Yidadaa** [comment]
考虑使用 undici 的 fetch api：

https://github.com/nodejs/undici#undicifetchinput-init-promise

**Comment by Yidadaa** [comment]
需要考虑的因素：
- 打包后尺寸增长
- 是否支持流式响应

**Comment by wenerme** [comment]
@Yidadaa  可以 Docker 镜像使用 node-fetch，加代理检测，用 node 16

**Comment by gaogao1030** [comment]
这个有个本地开发的方案可以参考下。
本地的科学上网客户端一般都会有本地http代理端口和地址， 那么node-fetch的参数 agent 就可以设置代理服务器
```
import nodeFetch from "node-fetch"; 
import httpsProxyAgent from "https-proxy-agent"; 
const agent = new httpsProxyAgent({
  protocol: 'http:',
  host: "127.0.0.1",//本地代理地址
  port: 1087 //本地http代理端口
});

function genFetch(isProxy) {
  return function (url, opts){
    opts = opts || { timeout: 3000 }
    if (isProxy > 0) { Object.assign(opts, { agent }) }
    return nodeFetch(url, opts)
  }
}

const proxyFetch = genFetch(true)
proxyFetch("google.hk")
  .then(response => {
    return response.json();
  })
  .then(data => {
    console.log('Received data:', data);
  })
  .catch(error => {
    console.error('Error:', error);
  });
```

**Comment by GrayXu** [comment]
希望这个能加入到Roadmap里

**Comment by Yidadaa** [comment]
目前问题比较复杂，貌似 nextjs 无法通过环境变量来指定 runtime，导致无法同时兼容 edge function 部署与本地部署。

**Comment by quark-zju** [comment]
如果你有 Linux 可以试试看 proxychains，理论上可以让动态链接到 libc 的程序（包括 node）强行使用代理。

**Comment by etodong** [comment]
作者是 部署到国内还是国外了， 你的demo 国内访问很快，需要在服务器端配置代理吗，我新手，代码看的比较慢哦~

**Comment by SmolderingGiraffe** [comment]
> 如果你有 Linux 可以试试看 proxychains，理论上可以让动态链接到 libc 的程序（包括 node）强行使用代理。

有类似的需求，用作者的 docker image 重新 build 试了下是可以的
```dockerfile
FROM yidadaa/chatgpt-next-web:latest
WORKDIR /app

RUN apk add --no-cache proxychains-ng

ENV OPENAI_API_KEY=""
ENV CODE=""

EXPOSE 3000

CMD ["proxychains", "node","server.js"]
```

**Comment by wenerme** [comment]
pr #295  镜像 wener/chatgpt-next-web:latest

打算维护一个 standalone 的 fork

**Comment by yoko-murasame** [comment]
我这里维护了一份基于 proxychains 重新打包 作者的 docker image的分支，只需要自己build后启动，可以在启动时指定代理参数了（我自己已经在使用中，暂时没发现啥问题），具体看文档：https://github.com/yoko-murasame/ChatGPT-Next-Web/blob/main/DockerfileForProxy/readme.md

**Comment by gaogao1030** [comment]
> 

检查一下是不是用错端口了，注意要用科学上网工具上的本机 http 监听端口不是sock端口。因为node-fetch的请求走的是http(注意agent模块是https-proxy-agent不是http-proxy-agent，因为目标地址是https)。
补充一下我的信息：我这里使用的是v2ray，本机监听http端口是1087，所以这里我配置的就是1087端口。（截止回复这条消息前跑了下没有问题）

**Comment by gaogao1030** [comment]
> > 这个有个本地开发的方案可以参考下。 本地的科学上网客户端一般都会有本地http代理端口和地址， 那么node-fetch的参数 agent 就可以设置代理服务器。 Openai那的接口我科学服务器上做了反代处理所以我只需要处理抓取提示词这边就行（不代理有时候会报请求被重置的错误）。具体代码可以参考[gaogao1030@bdfddb8](https://github.com/gaogao1030/ChatGPT-Next-Web/commit/bdfddb85617ba33d84d723a184f7ef5d7a585029)
> 
> 我试过了，但是会报错 [Fetch] failed to fetch cn prompts FetchError: request to https://cdn.jsdelivr.net/gh/PlexPt/awesome-chatgpt-prompts-zh@main/prompts-zh.json failed, reason: Client network socket disconnected before secure TLS connection was established

检查一下是不是用错端口了，注意要用科学上网工具上的本机 http 监听端口不是sock端口。因为node-fetch的请求走的是http(注意agent模块是https-proxy-agent不是http-proxy-agent，因为目标地址是https)。
补充一下我的信息：我这里使用的是v2ray，本机监听http端口是1087，所以这里我配置的就是1087端口。（截止回复这条消息前跑了下没有问题）

**Comment by Yidadaa** [comment]
@yoko-murasame 这个方案看起来是唯一可行的方案，稍后我会更新到主线

**Comment by authors-01-earshottt** [comment]
@Yidadaa @yoko-murasame
#654 这个PR很棒，启动容器的时候多加一个环境变量PROXY_URL，容器内的node调用chatgpt api时就会走PROXY_URL指定的代理了。
我的容器已经用上了最新的代码，效果很好。我用到的环境变量是这样的：

```bash
OPENAI_API_KEY: "xxx"
CODE: "user1,user2"
PROXY_URL: "socks5://172.33.33.33:9088"
```

如果要用http/https代理，改成这样就可以了
```bash
PROXY_URL: "http://172.33.33.33:9088"
PROXY_URL: "https://172.33.33.33:9088"
```

**Comment by Yidadaa** [comment]
已经合入主线。
