### ISSUE TITLE
[Feature] chatgpt 3.5 turbo回答速度太慢

### ISSUE THREAD

**Issue by ahui9605** [Yidadaa/ChatGPT-Next-Web#1200]
**这个功能与现有的问题有关吗？**
没有关系，只是一个小小的建议

**你想要什么功能或者有什么建议？**
在正常的网络连接下，当提出问题的时候，chatgpt turbo回答速度比较慢。是否可以考虑添加和设置回答速度显示快一点

**有没有可以参考的同类竞品？**
和官方网页版的chatgpt plus比较，一段大概700字数的文章回答只需要10秒左右就回答完了。这个turbo按理说应该是比plus快很多但我用了以后需要大概40多秒才回答完毕

**其他信息**
无

**Comment by Yidadaa** [comment]
这是 openai 的限制，我要是这么牛逼还搁这写代码？

**Comment by ahui9605** [comment]
> 这是 openai 的限制，我要是这么牛逼还搁这写代码？

不管你是最近遇到了什么不愉快的事情还是见到过这种类似的要求问题使你恼怒，我建议你作为一个开发者都要有一个较好的素质和教养来回答问题，而不是在这里发癫。我接受你前半段的回答但我不会接受你后半段所说的问题。我只是一个新手才刚刚接触chatgpt，我还没有完全的掌握清楚，只是好奇询问一下并受到这种待遇，更何况这是从一个获得2万stars数的开发者嘴里说出来的，这颠覆了我对高stars的开发者有些人品还是不怎么样的，素质有待提高。

**Comment by Yidadaa** [comment]
你说得对，但是我没必要在网上对所有人都保持什么狗屁素质，我对你来说不过是网上一个陌生的开发者，你对我来说不过是每天几十个排着队来问我傻逼问题的小白罢了。

我他妈又不从你们这些人手里赚钱，这破项目纯粹就是我业余时间自娱自乐，那我凭什么要消耗我的耐心去给你们这些小白来解答这些随便百度几下就能得到答案的问题？甚至大部分问题我他妈都已经在文档里写得明明白白了，难道我还要摆出一副海底捞服务员的笑脸他妈的在这浪费五一假期的一个小时再他妈的花上大几百字给你分析解释为什么 openai 的响应数据为什么这么慢？

我他妈给你打几行字回复都已经是在做慈善了，爱用用，不用滚，就这么简单，不服你就去报警。

**Comment by ahui9605** [comment]
> 你说得对，但是我没必要在网上对所有人都保持什么狗屁素质，我对你来说不过是网上一个陌生的开发者，你对我来说不过是每天几十个排着队来问我傻逼问题的小白罢了。
> 
> 我他妈又不从你们这些人手里赚钱，这破项目纯粹就是我业余时间自娱自乐，那我凭什么要消耗我的耐心去给你们这些小白来解答这些随便百度几下就能得到答案的问题？甚至大部分问题我他妈都已经在文档里写得明明白白了，难道我还要摆出一副海底捞服务员的笑脸他妈的在这浪费五一假期的一个小时再他妈的花上大几百字给你分析解释为什么 openai 的响应数据为什么这么慢？
> 
> 我他妈给你打几行字回复都已经是在做慈善了，爱用用，不用滚，就这么简单，不服你就去报警。

首先文档里并没有提到chatgpt速度慢是因为openai的问题，我也百度过 还去以前的issues里找了一段时间都没找到类似的问题我才去问的 而不是你嘴里说的张嘴就问，伸手就来的人。那是他们 请不要拿我来和他们比较
其次，我也并没有说要求你解释多么详细 你只要回答前半句然后close issue就行了 再不行直接无视等其他的人也可以帮你回答 加上后半句是想干啥呢？一个论坛本来就是大家互相帮助回答 又不是只有你一个人
最后，你大可不必这种态度 我也无意打破你的五一假期 祝你假期愉快

**Comment by zjsxply** [comment]
我今天也发现这个问题了，刚才实测：
1. Vercel 部署 Next Web，使用 120 刀 3.5 API：10 汉字 / 秒
2. 本地挂梯自行调用 API：20 汉字 / 秒
3. 本地挂梯上官网用免费账号的 3.5：30 汉字 / 秒
4. 本地挂梯上官网用 PLUS 的 3.5：60 汉字 / 秒
不知道是不是 Vercel 的问题，希望作者可以抽空排查一下 @Yidadaa
