### ISSUE TITLE
[Bug] Prompts function not working properly

### ISSUE THREAD

**Issue by bentwnghk** [Yidadaa/ChatGPT-Next-Web#1201]
**Describe the bug**
#1126 The issue still persists, even after applying the updates.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome, Edge]

**Comment by Yidadaa** [comment]
please provide a screen record

**Comment by bentwnghk** [comment]
[https://mr5drive.com/s/aH35XtkHcCZL7EM](url)

**Comment by yanCode** [comment]
@Yidadaa @bentwnghk , you are right, after @Yidadaa's fix, this issue can still reproduce my local env. 
(mac osx, m1 chipset, 16G Ram, latest Chrome browser ).
if you want to reproduce it and finding the reason, please follow bellow steps:
```
const onPromptSelect = (prompt: Prompt) => {
    setPromptHints([]);
    inputRef.current?.focus();
    setTimeout(() => setUserInput(prompt.content), 60);
  };
```
inside this event handler, you can add a line of `console.log("onPromptSelect is calling")`
then run the server locally, do it multi times, you can find many times  (9 of 10 in my local env) selecting Prompts fails, when failing, you can see  `console.log("onPromptSelect is calling")` prints nothing.

for me, i think before the click event starts in the selected prompt item, the blur event listener already started to work
```
onBlur={() => {
              setTimeout(() => {
                if (document.activeElement !== inputRef.current) {
                  setAutoScroll(false);
                  setPromptHints([]);
                }
              }, 100);
            }}
```
in which it sets `setPromptHints([])`, so it looks a prompt is clicked, but actually before it getting clicked, `onBlur` already removed any the prompts, so the prompt click event never been triggered.

I am provide a pull request to this issue right away.

**Comment by yanCode** [comment]
this is a footage i updated to discord https://discord.com/channels/1089481140232011828/1089481141372846174/1103141893547761684 
FYI

**Comment by Yidadaa** [comment]
Can not reproduce this problem on windows 11 (ms edge), but I can guess the reason, and I will submit a pr to try to fix it later.

**Comment by bentwnghk** [comment]
Merging the pull request #1220 has successfully fixed this issue 👍
