### ISSUE TITLE
[Bug]  yarn build

### ISSUE THREAD

**Issue by hnsongbiao** [Yidadaa/ChatGPT-Next-Web#1202]
PS E:\github\chatgpt\Yidadaa> yarn build
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ yarn fetch && next build
warning package.json: License should be a valid SPDX license expression
$ node ./scripts/fetch-prompts.mjs
[Fetch] fetching cn prompts...
[Fetch] fetching en prompts...
[Fetch] failed to fetch cn prompts Error: Request timeout
    at Timeout._onTimeout (file:///E:/github/chatgpt/Yidadaa/scripts/fetch-prompts.mjs:16:14)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[Fetch] saved to ./public/prompts.json

**Comment by Yidadaa** [comment]
检查网络是否通畅

**Comment by hnsongbiao** [comment]
网络是通的，用梯子访问的
