### ISSUE TITLE
[Feature] Pin session to top

### ISSUE THREAD

**Issue by seven4x** [Yidadaa/ChatGPT-Next-Web#1204]
**这个功能与现有的问题有关吗？**
没有

**你想要什么功能或者有什么建议？**
能够增加会话收藏功能

**有没有可以参考的同类竞品？**
没有

**其他信息**
如果会话很多的话，有些会话里有一些有价值的内容，在需要的时候通过收藏可以快速定位
![image](https://user-images.githubusercontent.com/1982168/235679607-31c897bd-0de6-46a0-ba3b-0c59a0e59b61.png)

**Comment by Yidadaa** [comment]
之后会增加 pin 到顶部功能，但优先级比较低

**Comment by hnsongbiao** [comment]
对话数据是否可以存储到数据库，因为涉及到计费计算

**Comment by hnsongbiao** [comment]
对话数据是否可以存储到数据库，因为涉及到计费计算

**Comment by hnsongbiao** [comment]
对话数据是否可以存储到数据库，因为涉及到计费计算

**Comment by daiaji** [comment]
感觉置顶会比较好用
