### ISSUE TITLE
[Bug] 每轮对话无法自动生成标题

### ISSUE THREAD

**Issue by congjinruo** [Yidadaa/ChatGPT-Next-Web#1207]
**Describe the bug**
我是每隔一两周会更新网站，发现从某个版本开始，无法自动生成每轮对话的标题，现在全部显示新的聊天。全新部署也不行。

**Expected behavior**
正常应该会从对话内容自动概括本轮的对话标题。

**Deployment**
是用最新代码，docker本地打包成tar进行部署的，没有直接用dockerhub的镜像。
```shell
docker build -t chatgpt-next-web .
docker save -o chatgpt-next-web.tar chatgpt-next-web
```
- [x] Docker
- [ ] Vercel
- [ ] Server

**screenshots**
<img width="867" alt="image" src="https://user-images.githubusercontent.com/18540738/235721779-299a5845-d0bc-4568-a51d-db8fbd991cd1.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [112]

**Additional Logs**
用的gpt-3.5-turbo，当前版本：435e82c，切换浏览器无痕模式也不行。  
之前那个版本一切正常，现在这个版本除了聊天非常ok，对话框标题和余额显示都不行了，就很奇怪，余额显示无所谓，对话框标题没有很难区分历史记录了就。

**Comment by Yidadaa** [comment]
/api/chat 会在 gpt 回答结束后立即发出

**Comment by congjinruo** [comment]
> 实测 vercel 部署不存在该问题，或许你的 ngnix 配置把 /api/chat 请求拦截了，你可以开一个新的聊天，然后打开浏览器控制台的网络选项卡，然后随便问个长一点的问题：解释一下快排，给出时间复杂度以及证明。然后观察 /api/chat 是否发送成功。

找到原因了，我这边回答结束是会立刻调一个`/api/openai`的接口
<img width="854" alt="image" src="https://user-images.githubusercontent.com/18540738/235732526-4906e639-192b-4727-895f-4b1c6e1924a7.png">
短暂的200之后（大约一分钟之后），会出现一个`net::ERR_HTTP2_PROTOCOL_ERROR 200`的错误，根据我的排查，是反向代理openai的接口的nginx/1.14.1配置问题。把这一行注释掉就行了`chunked_transfer_encoding off;`，虽然我没搞懂为什么。
```shell
    location / {
        proxy_pass  https://api.openai.com/;
        proxy_ssl_server_name on;
        proxy_set_header Host api.openai.com;
        proxy_set_header Connection '';
        #chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```
