### ISSUE TITLE
[Bug] docker和node部署成功，但只能通过ip访问，域名访问一直在加载...

### ISSUE THREAD

**Issue by SeduceQAQ** [Yidadaa/ChatGPT-Next-Web#1208]
**反馈须知**
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
通过docker部署之后，可以通过ip直接访问，但是通过域名访问的时候一直在加载，排查了半天也不知道问题出在哪了
详情看下面截图↓

同样的nginx配置文件，在另一个项目是好使的，我只改了一下upstream的端口到3000，通过域名访问就一直在加载。。。
nginx配置文件:
```
    proxy_cache off;  # 关闭缓存
    proxy_buffering off;  # 关闭代理缓冲
    chunked_transfer_encoding on;  # 开启分块传输编码
    tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
    
    upstream chatgpt-web {
        server 127.0.0.1:3000 weight=1;
    }

    server {
        listen 80;
        server_name www.example.com example.com;
        location / {
                return 301 https://www.example.com;
        }
    }
    server {
        listen 443 ssl;
        server_name www.example.com;
        ssl_certificate /etc/nginx/origin-example.com.pem;
        ssl_certificate_key /etc/nginx/origin-example.com.key;
        location / {
                proxy_pass http://chatgpt-web;
        }
    }
```

然后我又试了一下node直接部署，一样的问题，ip可以，域名不行

所有的配置方面应该是没有问题的，之前同样的配置跑的chatgpt-web这个项目，这次只改了一下端口
我能想到的，套了一个cf的cdn，但是这个应该不影响，其它都是一模一样的，就很奇怪

**截图**
ip可以访问：
![Snipaste_2023-05-03_00-06-22](https://user-images.githubusercontent.com/47859387/235722583-3a46fe8c-adc2-4687-b0a3-6c1cc3c01ef7.png)
域名无法访问，一直在加载：
![Snipaste_2023-05-02_23-52-35](https://user-images.githubusercontent.com/47859387/235722655-6c25805c-812c-4c24-a61c-aa4bb2cf21be.png)

**一些必要的信息**
 - 系统： centos stream 9
 - 访问使用的浏览器： chrome
 - 版本： latest
 - 部署方式：docker

**Comment by SeduceQAQ** [comment]
我重装了一遍系统，重新部署了一遍又好使了，复现不了了🤣
但我记得是一个js文件在报404
然后控制台发起的请求数量比较少，只有不到10个请求，还夹杂着一个404
深切怀疑是cf的cdn服务器出问题了🤔
麻烦了，以后如果复现的话，我再重新提issues😂

**Comment by RyanNiu** [comment]
_next/static/chunks/webpack-a86f7c25f475551f.js  这个js 404，我是第二次出现这个问题，上一次通过重新，重新部署解决了 [这次并没有，目前IP仍可正常访问，截图如下
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/23376595/229955a1-2b01-43fa-998c-52650da3e8c6)

**Comment by ooahz** [comment]
额，这个问题我遇到了![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/57132258/8641a2e6-3514-4241-98de-f0319a33d5e7)
