### ISSUE TITLE
[虫子]

### ISSUE THREAD

**Issue by hanxu1355146559** [Yidadaa/ChatGPT-Next-Web#1209]
**Describe the bug**
直接部署在自己的私人服务器时,部署完成后无论使用pnpm start还是yarm run start,进入到密码验证环节,但是没有密码框.
但是点击“清除所有数据”后,密码框会回复,但当我再次向密码框输入密码后进入对话窗,再次提示我需要身份验证,进入到密码页面,密码框再次消失.
以上问题重复出现,只有第一次刚刚安装好后自带的第一遍是可以使用的,一旦关闭终端窗口后,再次打开不论使用pnpm还是yarm命令都无法正常对话.

**To Reproduce##
正常对话页面-进入设置页面输入密码-密码框消失-点击“清除所有数据”-密码框回归-输入密码-进入对话页面-要求进入密码页面输入密码-密码框消失.
以此往复.

**Screenshots**
①
![BUG1](https://pan.hanxu1355146559.cn/d/Aliyundrive/Disk/Upload/bug1.png)
②
![BUG2](https://pan.hanxu1355146559.cn/d/Aliyundrive/Disk/Upload/bug2.png)

**Deployment**
- [❌] Docker
- [❌] Vercel
- [✅] Server
因我想部署在自己服务器,且没有docker,因此只能选择本地部署方案

**服务器:**
 CentOS7.9

**访问设备:**
macOS12.6.1:Safari+Chrome
iOS16.4.1:Safari

此问题出现较长时间,如需更多数据请通过邮箱联系我
1355146559@qq.com

**Comment by Yidadaa** [comment]
你必须在环境变量里指定了  CODE ，密码框才会出现，修改 .env.local 文件内容，填入 CODE=xxxx，然后重新 start 就行了。
