### ISSUE TITLE
关于提示词补全的建议

### ISSUE THREAD

**Issue by Sauiear** [Yidadaa/ChatGPT-Next-Web#121]
非常感谢作者做的提示词补全的功能，有关功能完善，我有一点建议，建议提示词补全默认为禁用，或者当用户输入“/”之后在进行提示词补全。如果能做出相应修改，多谢了。

**Comment by realskyrin** [comment]
+ 1

**Comment by Yidadaa** [comment]
提示词功能正在逐步完善中，请耐心等待。

**Comment by xiaozhang959** [comment]
作者您好，关于提示词功能我有个建议，我觉得您也可以做成这种的
![](https://files.catbox.moe/meavqb.png)

就是在创建新聊天那里新增一个模型对话的，然后预设一些供用户选择
![](https://files.catbox.moe/k4p4bi.png)

这样好像会比直接在输入框中输入会舒服点
![图片](https://user-images.githubusercontent.com/89305607/228620043-58c8cc3c-e1a7-4a6b-98a5-f26b1ef44fd0.png)

**Comment by Yidadaa** [comment]
已经修改为使用 / 触发。
