### ISSUE TITLE
[Feature] how do I change the default language 

### ISSUE THREAD

**Issue by blkluv** [Yidadaa/ChatGPT-Next-Web#1210]
I’m trying to change the default CN language to EN? Thanks

**Comment by Yidadaa** [comment]
The language is auto detected by your browser, if your language is not supported yet, it will use CN.

**Comment by Yidadaa** [comment]
@blkluv 

Because I did not provide other languages' built-in templates, you can submit a pr with en(or any other langs) built-in templates inside.
