### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yafeng520** [Yidadaa/ChatGPT-Next-Web#1211]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
更新至2.0版本后，原来的聊天记录都没了。

**如何复现**
更新至2.0版本，清除浏览器缓存。

**截图**
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/17778563/235810924-fc38cb12-1d04-4586-9abe-d52233fc5e0e.png">

**一些必要的信息**
 - 系统：macos 13
 - 浏览器： chrome
 - 版本： 435e82c
 - 部署方式：vercel
@Yidadaa

**Comment by Yidadaa** [comment]
清除缓存当然就没了
