### ISSUE TITLE
.next 生成的全部都是需要部署的文件吗？

### ISSUE THREAD

**Issue by hnsongbiao** [Yidadaa/ChatGPT-Next-Web#1212]
![Uploading 1111.png…]()

通过执行 yarn build 之后，.next 生成的全部都是需要部署的文件（夹）吗？

**Comment by Yidadaa** [comment]
差不多，如果你不懂，不要浪费时间折腾，老老实实用 docker 或者 vercel

**Comment by hnsongbiao** [comment]
vercel无法注册和登录，希望能有一个本地或者ecs部署的方案

**Comment by hnsongbiao** [comment]
vercel使用github登录后提示

This user account is blocked. Contact registration@vercel.com for more information.

**Comment by Yidadaa** [comment]
那就用 docker 部署
