### ISSUE TITLE
[Feature] 隐藏PC端网页顶部对话名

### ISSUE THREAD

**Issue by lb-fes** [Yidadaa/ChatGPT-Next-Web#1217]
**这个功能与现有的问题有关吗？**

搜过，没找到

**你想要什么功能或者有什么建议？**

隐藏PC端网页顶部对话名（左侧已经有对话名了），使屏幕纵向能有更多显示空间。

右上角三个按钮可以考虑移到下方输入框上方。

![Snipaste_2023-05-03_10-48-55](https://user-images.githubusercontent.com/51531901/235824203-8d44f2d5-ae07-4688-8346-1525def899a3.png)

**Comment by Yidadaa** [comment]
侧边栏可以隐藏，拖动侧边栏右边界试试。

**Comment by lb-fes** [comment]
> 侧边栏可以隐藏，拖动侧边栏右边界试试。

。。。

我想隐藏的是顶部对话名，不是侧边栏。

我的意思是顶部的跟侧边栏的重复了，顶部对话名占据了PC端屏幕垂直方向上的很大一部分空间，

留给对话内容的显示空间并不是很多。

**Comment by Yidadaa** [comment]
自己改代码吧，我不可能变更设计
