### ISSUE TITLE
无法使用Vercel

### ISSUE THREAD

**Issue by hnsongbiao** [Yidadaa/ChatGPT-Next-Web#1223]
![Uploading 企业微信截图_16831049717021.png…]()

Vercel登录后提示：

This user account is blocked. Contact registration@vercel.com for more information.

还有其他部署资源可以使用吗？或者请提供一个本地部署的方法吧（或者ECS），

.next目录全部资源都是静态资源吗？我可以直接部署在IIS上吗？

**Comment by Yidadaa** [comment]
你账号被 vercel 风控了，建议用 docker 部署。
