### ISSUE TITLE
 Vercel部署过一段时间会报错[Bug] 

### ISSUE THREAD

**Issue by Arturia169** [Yidadaa/ChatGPT-Next-Web#1224]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
Vercel部署过一段时间会收到官方的邮件提示部署报错，但是网页能正常打开使用

**如何复现**
过一段时间就会发一封

**截图**
![image](https://user-images.githubusercontent.com/69199123/235891571-9a39e8d7-7b93-44ba-ab97-ba491b42ba49.png)
![image](https://user-images.githubusercontent.com/69199123/235891629-afdf83a6-5b1c-486d-bc7a-a10d3fb9d03b.png)
![image](https://user-images.githubusercontent.com/69199123/235892296-a8fde266-24d5-48fd-8ae8-7bb1cfc01305.png)

**一些必要的信息**
 - 系统： windows 10
 - 浏览器： [Edge]
 - 版本： [435e82c]
 - 部署方式：[vercel部署]

**Comment by Yidadaa** [comment]
vercel 的问题
