### ISSUE TITLE
[Bug] Docker部署下使用快捷键 / 无法正常调用提示词

### ISSUE THREAD

**Issue by Gitqiubai** [Yidadaa/ChatGPT-Next-Web#1227]
**描述该 Bug**
使用docker部署的应用无法正常使用 / 快捷键使用提示词

**重现 Bug**
重现行为的步骤：
clone最新的Dockerfile构建和yidadaa/chatgpt-next-web镜像这两种方式部署Docker应用，在部署完成后使用快捷键 / 呼出提示词的时候`无法同项目的demo一样使用方向键和鼠标选中提示词，将提示词填充到输入栏框中`，使用了Edge浏览器、Firefox浏览器、微信浏览器均出现一样的状况，浏览器的控制台处也并未出现错误。使用vercel部署的版本为`e0053d5`没有对应的问题.

WEB应用版本：当前版本：435e82c
Docker镜像版本：latest

**期望行为**
清晰、简洁地描述您期望发生的情况。

**截图**
如果可能，请添加截图以帮助解释您的问题。

**部署**
- [x] Docker
- [ ] Vercel
- [ ] Server

**桌面端（请填写以下信息）：**
- 操作系统：Window10 1903
- 浏览器：Edge
- 版本：版本 112.0.1722.64（正式版本）（64 位）

**额外日志**
在此添加与该问题相关的任何日志。

**Comment by Gitqiubai** [comment]
![BUG](https://user-images.githubusercontent.com/40193959/235925947-6546e6f8-0201-4c87-a570-00f35c9bac2b.gif)

**Comment by Yidadaa** [comment]
这个问题昨天刚修复，还没发 docker 版本。
