### ISSUE TITLE
[Feature] 建议增加语音朗读功能

### ISSUE THREAD

**Issue by ccinoo** [Yidadaa/ChatGPT-Next-Web#1228]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。
无

**你想要什么功能或者有什么建议？**
尽管告诉我们。
>>建议增加语音朗读功能，这样可以保护眼睛，听更轻松简单。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。
>>可以参考以下程序中，点击“speech按钮”朗读功能。
https://github.com/okisdev/ChatChat

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
#540
