### ISSUE TITLE
[Feature] 是否会增加联网搜索功能呢

### ISSUE THREAD

**Issue by strivingwang** [Yidadaa/ChatGPT-Next-Web#1231]
**类似于：**
![chrome_ZcXevdhp6H](https://user-images.githubusercontent.com/21355112/236097030-9258350f-7d62-46a6-b092-4cd08ed28aeb.png)

**Comment by tiamohf** [comment]
这是什么应用，能否分享一下

**Comment by Yidadaa** [comment]
#165
