### ISSUE TITLE
[Bug] API KEY 无效

### ISSUE THREAD

**Issue by dgqyushen** [Yidadaa/ChatGPT-Next-Web#1233]
**Describe the bug**
通过nodejs进行本地调试的时候，在.env文件中写好了CODE（密码）与 AUTH_KEY，启动项目后想共享给其他人一起使用（他们自备KEY），他们填写KEY之后仍然提示需要输入密码，疑似没有通过自己的AUTH_KEY绕过密码

![3G F_6TGP$6HU F} _72}8N](https://user-images.githubusercontent.com/31363750/236116099-0092a822-9237-45fb-bea3-9bf1e7e89ca7.png)

![QB FAW$ H$BD% ZN}VT~QE](https://user-images.githubusercontent.com/31363750/236116128-3d3cd9b7-b270-43f5-9949-8a4ba796acd6.png)

![39B)45`LA@V`_P~ZC5W1@2W](https://user-images.githubusercontent.com/31363750/236116144-c0cae302-92fa-4760-9486-8ffaae072365.png)

**Comment by jh410** [comment]
你并没有输入访问密码，他怎么给你访问
