### ISSUE TITLE
[Bug] 手机夸克浏览器无法正常导出聊天记录

### ISSUE THREAD

**Issue by Undertone0809** [Yidadaa/ChatGPT-Next-Web#1234]
**Describe the bug**
- 使用手机夸克浏览器进行聊天的时候无法对聊天记录进行导出，点击按钮之后没有反应。
- 尝试过其他浏览器，如Edge，Chorme，小米自带浏览器都可以正常导出，只有夸克点击导出按钮之后没有反应。
- 用的红米K60的手机，但是感觉应该不是手机的问题。
- 暂时还没有评测过其他机型，不知道其他安卓夸克的用户是否有这个问题

![8894067e4b0acbac6878dcf671d11ad](https://user-images.githubusercontent.com/72488598/236125646-cfded57b-262f-4d77-9100-be7ed9c7ea1a.jpg)

**Comment by Yidadaa** [comment]
夸克的问题
