### ISSUE TITLE
[Bug] OPENAI_API_KEY，CODE未设置进去

### ISSUE THREAD

**Issue by hqzh** [Yidadaa/ChatGPT-Next-Web#1236]
**描述问题**
[这个方案无法解决](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/265)

**一些必要的信息**
 - 系统：[Ubuntu20.04-Docker20]

 - 部署脚本：去掉引号也没解决
 ```bash
docker run -d -p 3000:3000 \
   -e OPENAI_API_KEY="sk-xxx" \
   -e CODE="1024" \
   --net=host \
   -e BASE_URL="https://service-xxxx.com/release"  \
   yidadaa/chatgpt-next-web
```
![image](https://user-images.githubusercontent.com/26128706/236157981-507c01d2-7b4a-4066-b813-d1ef1b24c834.png)

**Comment by Yidadaa** [comment]
CODE 是你作为网站管理员设置的网页密码，别人必须在设置页填入你设置的 CODE 才能使用，不然就一直提示未授权，除非你点左下角设置按钮填入 CODE 作为 访问码。

你要是想直接一进来就能使用，就不要在启动 docker 的时候设置 CODE 环境变量。
