### ISSUE TITLE
[Bug] Can not delete cloned mask

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#1237]
**To Reproduce**
1. select a built-in mask
2. clone it
3. can not delete cloned mask

**Expected behavior**
Should allow to delete cloned mask.

**Deployment**
All

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by HysenX-LI** [comment]
目前有被这个问题困扰的朋友可以暂时通过删除cookie来解决，需要注意的是，在删除cookie之后，你网站上的其他数据也会被删除掉
