### ISSUE TITLE
输出Excel公式带有$符号的时候不显示[Bug] 

### ISSUE THREAD

**Issue by wk-mike** [Yidadaa/ChatGPT-Next-Web#1238]
如果询问公式，gpt返回`=IF(COUNTIF($A$1:$A$23,B1)=0,B1,"")`的时候，不会显示美元符号 `$` 
猜测应该是自动变成斜体了。包括我输入这个公式，也会自动变成斜体。

![image](https://user-images.githubusercontent.com/19682026/236168689-722e9e05-06d9-4ac3-a8c3-629f4620753a.png)

**Comment by Yidadaa** [comment]
$ 是 latex 公式的起止符号，你要求 chatgpt 将所有的 excel 公式用 md 的 code 语法裹起来就行了。
