### ISSUE TITLE
[Bug] Fail to pull the docker image

### ISSUE THREAD

**Issue by ztxjack** [Yidadaa/ChatGPT-Next-Web#1242]
**Describe the bug**
got message "mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'"
when pulling the image

**To Reproduce**
1. docker pull yidadaa/chatgpt-next-web
2. the OS is ubuntu18 and docker version is 19.03.1

Could someone help take a look at this problem? Thanks

**Comment by Yidadaa** [comment]
use docker 20
