### ISSUE TITLE
[Feature] 是否可以增加一个停止按钮

### ISSUE THREAD

**Issue by dqzboy** [Yidadaa/ChatGPT-Next-Web#1244]
**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
gpt回答时，是否可以添加类似官方或chatgpt-web那种stop按钮；这样可以确保在网络不稳定的情况下可以知道gpt是否在回答

**有没有可以参考的同类竞品？**
chatgpt-web或官网
<img width="164" alt="Snipaste_2023-05-04_21-37-28" src="https://user-images.githubusercontent.com/42825450/236222726-784a6891-ffb7-47a4-9f5f-778a3a3d67aa.png">

**Comment by yanCode** [comment]
@Yidadaa , is it possible to add a tooltip on the icon buttons, sometimes, it's hard to guess what this button really does.

**Comment by Yidadaa** [comment]
@yanCode of course i can, but i hate i18n

**Comment by yanCode** [comment]
> @yanCode of course i can, but i hate i18n

why not adding the tooltip UI by yourself, and requesting any one(s) want to contriube to the i18n textings of each language it supports. as a highly started project, I can see it can be easy to do .

**Comment by Yidadaa** [comment]
that's the point, any time you want to add a new i18n text, no matter you want to translate it instantly or not, you still have to modify a tons of files. This may be a bad design pattern, I may refactor it later.
