### ISSUE TITLE
[Bug] 能否替换或者去除谷歌在线样式的引用

### ISSUE THREAD

**Issue by jiangyuhong** [Yidadaa/ChatGPT-Next-Web#1251]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在vercel部署后,使用自定义域名访问会加载 https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300;400;700;900&display=swap 文件,这个文件在正常的网络下无法访问,导致打开网站的速度很慢.能否把它去掉或者替换掉?

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
![20230505090237](https://user-images.githubusercontent.com/2521699/236369121-49fa6280-da50-419b-8dfd-f63f03afb013.jpg)

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by ClarenceDan** [comment]
可以自己改，删掉layout.tsx中的谷歌字体的引用：


        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300;400;700;900&display=swap"
          rel="stylesheet"
        ></link>

然后修改globales.scss中的font-family，去掉Noto Sans SC

**Comment by Yidadaa** [comment]
后续换成这种： https://nextjs.org/docs/pages/api-reference/components/font

**Comment by Yidadaa** [comment]
先别关，我准备今晚改。

**Comment by Yidadaa** [comment]
使用镜像：https://github.com/cdnjs/cdnjs/issues/682#issuecomment-374459748
