### ISSUE TITLE
[不是Bug]大家是怎么隐藏页面的？

### ISSUE THREAD

**Issue by kahoch** [Yidadaa/ChatGPT-Next-Web#1252]
防止域名被扫描和污染，套了zereTrust也只能隐藏自己域名下的，可是vercel强制“赠送”的域名删不掉，大家是怎么处理的？

**Comment by Yidadaa** [comment]
别人看不到 vercel 给你的域名

**Comment by kahoch** [comment]
@Yidadaa 扫得到，见https://github.com/lzwme/chatgpt-sites.git
