### ISSUE TITLE
[QA] 配置固定 KEY 发布应用，是否会触发 OpenAI 规则呢？

### ISSUE THREAD

**Issue by kavout-it** [Yidadaa/ChatGPT-Next-Web#1254]
你好，非常感谢分享！ 有个问题一直不清楚，请教一下：
使用 ChatGPT Next Web 搭建项目，配置自己固定的 KEY，发布到互联网上公开访问。这样是否违反 OpenAI 的使用规则？
对自己的 KEY 和 OpenAI 账号有没有影响呢？

或者还需要配合什么额外工作，确保不会触犯 OpenAI 滥用等相关规则？

**Comment by Yidadaa** [comment]
openai 开放 api key 就是让你自己部署应用的，不然塔开放 api 干啥
