### ISSUE TITLE
通过域名访问有些问题就是一直加载中

### ISSUE THREAD

**Issue by hqzh** [Yidadaa/ChatGPT-Next-Web#1257]
![image](https://user-images.githubusercontent.com/26128706/236379982-108e3f19-92e2-4393-9d7b-5d20c0e98f54.png)

![78eb2e7fcb0775a476962677b7aadfc](https://user-images.githubusercontent.com/26128706/236380082-a3c6f76c-64f0-473b-8fe6-1535f59b234c.png)
![image](https://user-images.githubusercontent.com/26128706/236380358-4281d3eb-1c08-443c-a147-6ff598c1b25d.png)

docker部署的，ip访问没问题（但是截取好短），域名访问有些问题一直加载中

```
docker run -d -p 3000:3000 \
  -e OPENAI_API_KEY="sk-xxx" \
  -e CODE="1024" \
  --net=host \
  -e BASE_URL="https://service-xxxx.com/release"  \
  yidadaa/chatgpt-next-web
```
系统：[	CentOS 7.9 64bit-Docker version 23.0.5, build bc4487a]

**Comment by Yidadaa** [comment]
#1208

**Comment by hqzh** [comment]
> #1208
我的第一张图是域名访问，只是有些问题无法加载，比如图里我问serverless问题，但是其他问题就可以。
我那个问题和#1208问题不一样呀，我的控制台只有一个跳转log,资源也没报错。域名访问地址http://gpt.hqzh.fun/，ip访问地址：http://159.75.255.5:3000/  
@Yidadaa

**Comment by Yidadaa** [comment]
和你的 ngnix 配置有关，我不太懂 ngnix，你可以搜搜别人的 ngnix 配置

**Comment by hqzh** [comment]
> 和你的 ngnix 配置有关，我不太懂 ngnix，你可以搜搜别人的 ngnix 配置

请问图三通过ip访问回答被截取很短也是nginx问题嘛？我看设置是写的2000，这也才100多就截取了@Yidadaa

**Comment by hqzh** [comment]
我使用的是腾讯[云函数](https://github.com/Ice-Hazymoon/openai-scf-proxy)代理

**Comment by Yidadaa** [comment]
有折腾服务器和云函数的功夫，你还不如花几分钟注册个 vercel 的号部署，然后绑个域名上去，分分钟结束。

**Comment by hqzh** [comment]
解决了，是云函数设置响应时间短了

**Comment by feichaoyu** [comment]
> 有折腾服务器和云函数的功夫，你还不如花几分钟注册个 vercel 的号部署，然后绑个域名上去，分分钟结束。

我绑定了腾讯云的域名，提问就会invalid api，
<img width="320" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/42114893/79c59f7a-9e18-43e4-b3db-e9fc648a4c12">
直接用vercel域名提问就可以

**Comment by hqzh** [comment]
你这个情况我没遇到过，vercel我也部署了
