### ISSUE TITLE
[Bug] 用vercel绑定域名后，返回的代码不高亮显示

### ISSUE THREAD

**Issue by itliuwk** [Yidadaa/ChatGPT-Next-Web#1263]
**描述问题**
使用vercel的域名可以正常显示，绑定自己的域名后就无法显示代码高亮了

**如何复现**
用vercel绑定域名后，返回的代码不高亮显示

**截图**
绑定域名前
![image](https://user-images.githubusercontent.com/26169320/236399697-ccbb982f-4315-4ac4-b18e-620c9ffe2ca7.png)

绑定域名后
![image](https://user-images.githubusercontent.com/26169320/236399398-666047a1-161e-4bf4-93d8-d8e3dd488add.png)

**一些必要的信息**
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
gpt 返回的代码没有用 markdown 的 code 语法裹起来，你让它重新回答。
