### ISSUE TITLE
大佬，如何查询API key使用了多少额度，而不是整个账户使用了多少额度？

### ISSUE THREAD

**Issue by SunnyGPT** [Yidadaa/ChatGPT-Next-Web#1264]
这个查询额度的功能很牛哔，太强了！请问作者大佬，怎么改可以查询指定key用了多少额度呢？
比如我邀请团队成员，团队成员用他的账号创建了key，如何单独查询他使用了多少额度呢。目现在查的是整个主账户用了多少而不是key的成员用了多少，这样一来多个子账号就没法精确查了。

**Comment by Yidadaa** [comment]
查不到，openai 没提供这个功能。

**Comment by SunnyGPT** [comment]
> 查不到，openai 没提供这个功能。

大佬多少钱可以帮我写一个反代理统计使用token并计算金额的页面？我打算用cloudflare workers+kv来反代统计，但我一点经验都没有，想让gpt4帮我写都不知道它写的对不对。

**Comment by Yidadaa** [comment]
我不接私活，你可以进群找人开发。

**Comment by SunnyGPT** [comment]
> 我不接私活，你可以进群找人开发。

群满了进不去啊哥哥

**Comment by SunnyGPT** [comment]
> 我不接私活，你可以进群找人开发。

大佬能拉一下吗？

**Comment by Yidadaa** [comment]
611800285
