### ISSUE TITLE
[Feature] 向openai或者代理发送请求时是否可以指定源地址

### ISSUE THREAD

**Issue by slinar** [Yidadaa/ChatGPT-Next-Web#1268]
**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
- 部署环境：国内物理机(centos)
- 线路：国内三网BGP与香港IPLC，三网BGP是默认路由，香港IPLC用的ip rule与ip route策略路由
- 代理：cloudflare workers
- 目前存在的问题：向openai或者代理站点发出请求时使用BGP也就默认路由出去的，这样延迟就会比较大而且不稳定。如果可以指定源地址就可以通过ip rule匹配源地址把数据包发给香港IPLC的网关，这样延迟会小很多。
- 可能的解决方法：环境变量设置源地址，项目读取这个环境变量。使用这个地址向openai或者代理发送请求

**有没有可以参考的同类竞品？**
无

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
这是代理需要考虑的事情，和本项目无关。
