### ISSUE TITLE
[Bug] vercel 域名访问报错

### ISSUE THREAD

**Issue by tianqiliang** [Yidadaa/ChatGPT-Next-Web#1271]
![image](https://user-images.githubusercontent.com/45453418/236443531-e2536dd2-0529-4bcf-b39c-7fdb8d84cd7f.png)

![image](https://user-images.githubusercontent.com/45453418/236443874-eb9371d1-ffe9-4eb0-b79c-f618f7707fda.png)

### vercel 部署后指定了我自己的个人域名

现在出现了问题，红框内的域名访问会报错，如上图所示

**Comment by wahaha116** [comment]
请问你是怎么解决的呢？

**Comment by banditsmile** [comment]
也遇到同样的问题了，解决了吗？

**Comment by banditsmile** [comment]
> 请问你是怎么解决的呢？

在cloudflare配置域名的时候有个设置代理选项，把那个选项去掉就可以了
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/2239356/af4cc796-9416-418a-80cb-32c78642432b)
