### ISSUE TITLE
[Bug]/出来的提示词列表，鼠标点击一条后提示词没有进入输入框

### ISSUE THREAD

**Issue by ericliu0408** [Yidadaa/ChatGPT-Next-Web#1277]
/出来的提示词列表，鼠标点击一条后，提示词没有进入输入框，要连续点好几下才行

![image](https://user-images.githubusercontent.com/102401968/236504580-8d6548c0-1a69-46a2-ab14-7203552f0b44.png)

**Comment by Yidadaa** [comment]
更新代码
