### ISSUE TITLE
使用 GPT4 模型出错

### ISSUE THREAD

**Issue by vincentor** [Yidadaa/ChatGPT-Next-Web#128]
我的账号是开了 ChatGPT Plus 的，在官网页面可以选择使用 GPT4，但在自己部署的这个，如果选择 GPT4 模型(试了所有 gpt4 开头的都不行），请求的时候会无法响应并提示出错。如下图
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/2193194/228424644-35b56e86-b8c3-4956-a69e-268940e031d0.png">

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/2193194/228424591-a215016e-923d-43e7-b0fb-cc60e3a1e40d.png">

日志如下
[POST] /api/chat-stream reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true

**Comment by Yidadaa** [comment]
gpt plus 不代表你能用 gpt4 api，现在 gpt4 api 只能申请获得。
