### ISSUE TITLE
怎么禁止获取会话标题的

### ISSUE THREAD

**Issue by bwlab2016** [Yidadaa/ChatGPT-Next-Web#1281]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
怎么禁止获取标题的，经过查看，发现每次请求都要发送使用四到五个字直接返回这句话的简要主题，不要解释、不要标点、不要语气词、不要多余文本，如果没有主题，请直接返回“闲聊” 提示语来获取标题，这对于api消耗很大。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by bwlab2016** [comment]
每次问问题，都要发送当前聊天框所有内容追加《使用四到五个字直接返回这句话的简要主题，不要解释、不要标点、不要语气词、不要多余文本，如果没有主题，请直接返回“闲聊“》 这句话 然后发送，消耗直接翻倍，本来上下来就应该限制一下，5条左右就好了，不但全部发送，而且还重复发送一遍就是为了获取那个没用的标题。这样token消耗直接翻了好几倍

**Comment by bwlab2016** [comment]
我是想禁止获取标题，或者设置第一次请求的时候获取，就像chatgpt官方的那样，或者单独设置一下获取标题的上下文长度，比如就给个0，这样不让它获取之类的，谁知道怎么配置

**Comment by KumoLJT** [comment]
你确定是每次请求都会发送吗？我这边查看控制台是只有每次会话的第一次completions之后会再发一次completions获取标题，之后就不会附带获取主题的内容了。

**Comment by bwlab2016** [comment]
![image](https://user-images.githubusercontent.com/16678336/236598526-49063724-0fb2-4cc9-ad5c-d1c37c86b908.png)

大佬帮忙看看，你看前面已经发了很多内容了，不是第一次发送了，但是它还是发送2个，

> 你确定是每次请求都会发送吗？我这边查看控制台是只有每次会话的第一次completions之后会再发一次completions获取标题，之后就不会附带获取主题的内容了。

**Comment by bwlab2016** [comment]
> 你确定是每次请求都会发送吗？我这边查看控制台是只有每次会话的第一次completions之后会再发一次completions获取标题，之后就不会附带获取主题的内容了。

我是个菜鸟，用的docker部署的，是不是代码不是最新的原因

**Comment by Yidadaa** [comment]
新开一个对话
