### ISSUE TITLE
[Feature] 添加对话设置选项，继承全局设置

### ISSUE THREAD

**Issue by reece00** [Yidadaa/ChatGPT-Next-Web#1282]
实际功能可以转换为全局选项修改后重置所有有继承标签的对话设置。
并且在全局选项中添加默认继承全局选项。
我开了多个对话但并不需要不一样的设置，修改设置后一个个重置为默认太慢了

**Comment by Yidadaa** [comment]
不使用面具，点击“直接开始”，就会使用全局设置

**Comment by reece00** [comment]
你再念念我第三行说的什么？

**Comment by Yidadaa** [comment]
你他妈好好读读老子说的话到底是什么意思再来教我怎么用我自己写的工具行吗？
