### ISSUE TITLE
OpenAI error

### ISSUE THREAD

**Issue by blkluv** [Yidadaa/ChatGPT-Next-Web#1285]
No matter what OpenAI key I use I receive this error? 

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by colorsakura** [comment]
**You exceeded your current quota, please check your plan and billing details**

**Comment by blkluv** [comment]
> **You exceeded your current quota, please check your plan and billing details**

I've checked my usage and Ive haven't exceeded anything. I have other keys working normal under the same account. 

I deleted a key used in the git repo and added another to see if it was a isolated issue.

**Comment by Yidadaa** [comment]
usually, this error is caused by openai, if you still encounter this problem, please contact openai for support.
