### ISSUE TITLE
[Bug] Mermaid提示Syntax error in text

### ISSUE THREAD

**Issue by Kosette** [Yidadaa/ChatGPT-Next-Web#1294]
**Describe the bug**
无法正常渲染mermaid。经过确认应该是mermaid本身的一个兼容问题，流程图中不能出现中文标点，会被识别为unrecognized text，无法正常渲染。因而可能需要向上游提交请求。

**To Reproduce**
```
graph TD;
  A[开始]-->B(if 吃饭了吗?)
  B-- 是 -->C(好的，继续工作)
  B-- 否 -->D{饿了吗?}
  D-- 是 -->E(那去吃吧)
  D-- 否 -->C(好的，继续工作)
  C-->F[结束]
  E-->F
```
上述的中文逗号换成英文逗号可以正常渲染，否则会出现错误。

**Screenshots**
![image](https://user-images.githubusercontent.com/35268640/236618545-1df811fc-b8b6-4883-bfe9-3e4ccdd6399a.png)

**Comment by Kosette** [comment]
找到一个相关的 issue：https://github.com/mermaid-js/mermaid/issues/687 ，这么久了估计也没打算修了。chatgpt没办法保证将包含中文标点的语句都用引号包裹起来，因此这个问题估计暂时无法解决。

**Comment by Yidadaa** [comment]
凑合用吧，估计是没处理特殊的 unicode 字符

**Comment by Kosette** [comment]
> 凑合用吧，估计是没处理特殊的 unicode 字符

鉴于这个问题，希望能够在设置中加一个启用 mermaid 的开关。

在渲染失败的情况下除非把源码复制到其它地方，否则无法查看，且影响版面。此外存在问题的会话会有对话历史显示为空白的问题，应该也是该问题引起的 bug。

**Comment by Yidadaa** [comment]
会话空白与这个无关

**Comment by yzy1996** [comment]
> > 凑合用吧，估计是没处理特殊的 unicode 字符
> 
> 鉴于这个问题，希望能够在设置中加一个启用 mermaid 的开关。
> 
> 在渲染失败的情况下除非把源码复制到其它地方，否则无法查看，且影响版面。此外存在问题的会话会有对话历史显示为空白的问题，应该也是该问题引起的 bug。

右键可以复制出来源码的。

**Comment by Yidadaa** [comment]
v2.3 已经增加 fallback 逻辑，包含不合法字符时自动 fallback 回代码模式。
