### ISSUE TITLE
全屏聊天框宽度

### ISSUE THREAD

**Issue by JeazW** [Yidadaa/ChatGPT-Next-Web#13]
全屏聊天气泡间距会不会太宽了，不过我改的也没有好太多，大佬可以考虑下怎们调整下。
![width](https://user-images.githubusercontent.com/75829171/227495853-3c184801-5441-475b-8959-56b5a7172cee.jpg)

**Comment by Yidadaa** [comment]
可以在设置里关闭“紧凑边框”，紧凑边框是为了安装为独立 app 时使用的，网页模式下最好关闭此选项。
