### ISSUE TITLE
[Bug] Iphone端访问设置的各种Input总是触发自动放大

### ISSUE THREAD

**Issue by PaRaD1SE98** [Yidadaa/ChatGPT-Next-Web#1300]
**Describe the bug**
如题，Iphone端访问
- 设置页面的各种输入框
- 设置/自定义提示此列表/编辑模态框/搜索提示词输入框

总是触发自动放大，只有聊天输入框不会。

**Expected behavior**
也测试了安卓端chrome，没有这个问题，

参考了聊天输入框的style，起作用的是这个:
```
@media only screen and (max-width: 600px) {
  .chat-input {
    font-size: 16px;
  }
```
是否应该将所有输入框的最小字体都设置为16px来避免自动放大？

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone13Pro]
 - OS: [e.g. iOS16.1.1]
 - Browser [safari,chrome]

**Comment by wsw2000** [comment]
safari 浏览器会默认把<input> 元素都放大显示

**Comment by Yidadaa** [comment]
Safari 里点击分享按钮，选择“添加到主屏幕”，然后之后每次都从桌面 icon 进入，就不会触发放大了。

**Comment by PaRaD1SE98** [comment]
刚刚测试了，依然会

https://user-images.githubusercontent.com/78383353/236637988-c4cc43bb-08dd-4f0b-9810-f2bf00920a04.mp4
