### ISSUE TITLE
[Feature] Load builtin prompts, masks and config from url

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#1302]
Add a env var named `BUILTIN_CONFIG_URL`, it will load prompts, masks and default model config from the specific url in building stage.

```json
{
  "prompts": [],
  "masks": [],
  "modelConfig": {},
}
```

**Comment by DirkSchlossmacher** [comment]
This would be AWESOME! 
I was trying to find a way to modify the deployment steps so the source for prompt templates is no longer the public archive, but a curated, own repository. 
Thanks for your work! @Yidadaa  ❤️
