### ISSUE TITLE
fork本项目后，自动上游同步更新

### ISSUE THREAD

**Issue by MoGuangYu** [Yidadaa/ChatGPT-Next-Web#1304]
![IMG_20230507_012401](https://user-images.githubusercontent.com/49760068/236638460-12c4a063-c7dd-43d7-a3c6-468e40e4cf0e.jpg)
为什么vercel自动部署还是失败的啊，只能删除库在重新构建吗

**Comment by Yidadaa** [comment]
vercel 的问题

**Comment by again2k** [comment]
我也发现了，vercel 不能在短时间内多次 deploy ，所以更新频繁的话容易出错。

**Comment by yzy1996** [comment]
修改为一天更新一次吧。
