### ISSUE TITLE
[Bug] 20230505Docker版本的http auth问题

### ISSUE THREAD

**Issue by franocisgar** [Yidadaa/ChatGPT-Next-Web#1305]
用docker部署后，nginx反代同时使用http auth后，会不断要求重新验证，用user:pass@domain 来登录的话就会输入授权密码后就直接

~~~
出错了，稍后重试吧
~~~

之前还是可以用http auth前置反代的。

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/741#issuecomment-1537172117

**Comment by hibobmaster** [comment]
@Yidadaa 这里能不能换个请求头，`Authorization` 和 basic_auth 的请求头冲突
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/bc523d302b7c05050a71cf0460588049aab9d2f9/app/api/auth.ts#L30
我看原来貌似用的是 `token` 来获取用户输入的api key 
应该是这个 commit 引入的: https://github.com/Yidadaa/ChatGPT-Next-Web/commit/48ebd74859042aaa3d8cdbb74a61bd7391400b89

**Comment by Ma-Chang-an** [comment]
> @Yidadaa 这里能不能换个请求头，`Authorization` 和 basic_auth 的请求头冲突
> 
> https://github.com/Yidadaa/ChatGPT-Next-Web/blob/bc523d302b7c05050a71cf0460588049aab9d2f9/app/api/auth.ts#L30
> 
> 
> 我看原来貌似用的是 `token` 来获取用户输入的api key
> 应该是这个 commit 引入的: [48ebd74](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/48ebd74859042aaa3d8cdbb74a61bd7391400b89)

@Yidadaa  我有同样的问题，我使用华为云FunctionGraph来部署了ChatGPT-Next-Web，通过华为云的APIG网关来访问页面，当不适用密码是访问正常，可以正常chat，但是当我设置了Code环境变量，并在设置页面输入了密码后，所有HTTPS请求都会被APIG网关拦截，报错401认证错误，原因就是华为云的APIG网关会使用Authorization字段进行鉴权，但是ChatGPT-Next-Web的前端会把密码、API key得信息填写到Authorization字段导致华为云APIG网关鉴权失败，所以建议换一个请求头域段来承载这两个信息，下面是我测试过程的截图，图一是不使用Code密码的访问情况，图二是使用CODE密码的访问情况
