### ISSUE TITLE
希望可以加上传到versel[Feature] 

### ISSUE THREAD

**Issue by snownightflower** [Yidadaa/ChatGPT-Next-Web#1306]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by aidisheng101** [comment]
正如底部已经挂了本项目的友情链接, 在顶部我也想打一个logo链接到我的官网,再写几个字 放上联系方式 
望采纳 非常感谢项目. 

另外界面 我觉得界面有点复杂,可以模仿一下 chatbotui 的界面就很简洁哦.
