### ISSUE TITLE
[Bug] 对话界面频繁出现数据未加载情况 v2.2

### ISSUE THREAD

**Issue by GotoFox** [Yidadaa/ChatGPT-Next-Web#1307]
**Describe the bug**
项目版本v2.2，已更新至最新版，截图也已在 [chatgpt.nextweb.fun](https://chatgpt.nextweb.fun/) 复现
数据无法正常加载，静默等待长时间也无法正常加载

**To Reproduce**
当前对话条数较多之后切换到其他对话再切回会出现截图情况，数据无法正常加载，必须执行键盘按下或鼠标按下等其他操作之后才会正常显示数据，否则静默等待一直保持无法加载情况。

**Expected behavior**
无

**Screenshots**
![image](https://user-images.githubusercontent.com/68596145/236652832-c9083290-cc2a-43a0-aad4-2bf79d965535.png)

**Deployment**
- [ ] Docker
- Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Win11 22H2
 - Browser: Google Chrome
 - Version: 113.0.5672.64

**Comment by fuyuntt** [comment]
OS: MacOS
Browser: Google Chrome
也有同样的情况

**Comment by NathanDrake99** [comment]
![微信图片_20230508173735](https://user-images.githubusercontent.com/13790928/236792331-1c2af2be-c946-4eba-99a3-4709fc8db9fc.png)
有人知道这是啥情况吗？更新到最新版了

**Comment by zhuSilence** [comment]
> ![微信图片_20230508173735](https://user-images.githubusercontent.com/13790928/236792331-1c2af2be-c946-4eba-99a3-4709fc8db9fc.png) 有人知道这是啥情况吗？更新到最新版了

你的 key 没额度了吧
