### ISSUE TITLE
[Feature] 插件Idea分享 chatapi-translate

### ISSUE THREAD

**Issue by liqiujiong** [Yidadaa/ChatGPT-Next-Web#1313]
**这个功能与现有的问题有关吗？**
英文提问获取的内容更加准确，并且花费的token更少。通过提问进行翻译，以及对结果进行翻译。
参考项目：https://github.com/aitsc/chatapi-translate

**你想要什么功能或者有什么建议？**
插件化，用户直接配置Googlekey 就可以使用

**效果展示**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/5794205/ca73d248-4ebd-4c5b-b77a-545dc699b1e3)

**Comment by darth-pika-hu** [comment]
@liqiujiong 虽然你写的中文，但是我好像看不懂

**Comment by dgqyushen** [comment]
> @liqiujiong 虽然你写的中文，但是我好像看不懂

它的意思是指，我们问中文，但是next-web帮我们转换为英文来进行询问，花费的token更少，然后gpt用英文回复，next-web帮我们转换成中文

**Comment by darth-pika-hu** [comment]
多花点钱不就行了？直接用英语问更直接，省钱还可以练习一下水平。On May 9, 2023, at 8:03 PM, dgqyushen ***@***.***> wrote:﻿

@liqiujiong 虽然你写的中文，但是我好像看不懂

它的意思是指，我们问中文，但是next-web帮我们转换为英文来进行询问，花费的token更少，然后gpt用英文回复，next-web帮我们转换成中文

**Comment by liqiujiong** [comment]
> 哈哈，他多花点钱不就行了？直接用英语问更直接，省钱还可以练习一下水平。 On May 9, 2023, at 8:03 PM, dgqyushen ***@***.***> wrote:﻿ @liqiujiong 虽然你写的中文，但是我好像看不懂 它的意思是指，我们问中文，但是next-web帮我们转换为英文来进行询问，花费的token更少，然后gpt用英文回复，next-web帮我们转换成中文 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

在3.5的API上确实没必要。在4.0接口，本身就贵，如果再用中文，token消耗量是英文的5倍

**Comment by Cp0204** [comment]
意义不大，翻译器机翻，还生硬。

**Comment by daiaji** [comment]
以3.5为例子

> 题目（5星难度）：
> 
> 国庆长假期间，老王和老李两家聚餐。
> 
> 老李问：你家3个小孩都多大了啊？
> 
> 老王说：他们年龄之积是36。
> 
> 老李说：我不知道他们多大。
> 
> 老王说：他们年龄之和与咱们今天饭桌上菜的盘数相同。
> 
> 老李说：我还是不知道他们多大。
> 
> 老王说：年龄最小的孩子名叫小明。
> 
> 老李迅速知道了3个孩子的年龄。
> 
> 请问小明今年多大了？
> 
> 给出解题逻辑分析

这个题目给出的回复非常离谱

> 解题逻辑分析：
> 
> 根据题目的描述，我们可以得到以下信息：
> 
> 1. 三个孩子的年龄之积是36。
> 2. 老李不知道他们的年龄之和。
> 3. 老王说年龄之和与饭桌上菜的盘数相同。
> 4. 老李还是不知道他们的年龄。
> 5. 年龄最小的孩子名叫小明。
> 
> 我们可以根据这些信息逐步推断出小明的年龄：
> 
> 首先，我们列出所有可能的年龄组合，使得年龄之积等于36：
> 
> 1, 1, 36
> 1, 2, 18
> 1, 3, 12
> 1, 4, 9
> 1, 6, 6
> 2, 2, 9
> 2, 3, 6
> 3, 3, 4
> 
> 根据老李的回答，他无法确定孩子的年龄之和，这意味着有多个组合的年龄之和是相同的。我们列出这些可能的年龄之和：
> 
> 38 (1+1+36)
> 21 (1+2+18)
> 16 (1+3+12)
> 14 (1+4+9)
> 13 (1+6+6)
> 13 (2+2+9)
> 11 (2+3+6)
> 10 (3+3+4)
> 
> 根据老王的回答，年龄最小的孩子名叫小明，这意味着没有重复的年龄。我们可以排除年龄之和为13的情况，因为在这种情况下，有两个孩子的年龄相同，无法确定最小的孩子。
> 
> 剩下的年龄之和为38、21、16、14、11和10。根据题目的描述，老李最终知道了孩子的年龄，这意味着年龄之和必须是唯一的。
> 
> 只有年龄之和为16的情况下，老李才能确定孩子的年龄。因此，小明今年的年龄为6岁。
> 
> 综上所述，小明今年6岁。

> To solve this puzzle, we need to find the ages of the three children based on the given clues. Let's go step by step:
> 
> 1. Mr. Wang said that the product of their ages is 36. This means that the ages of the three children are three numbers that multiply to give 36. Let's list all the possible combinations:
> 
>    1, 1, 36
>    1, 2, 18
>    1, 3, 12
>    1, 4, 9
>    1, 6, 6
>    2, 2, 9
>    2, 3, 6
>    3, 3, 4
> 
> 2. Mr. Li said that he doesn't know their ages. This means that the product of their ages (36) is not enough information for him to determine their ages.
> 
> 3. Mr. Wang said that the sum of their ages is the same as the number of dishes on the table. This means that the sum of the three numbers should be a unique number among the combinations listed above.
> 
>    The sums of the combinations are:
>    38
>    21
>    16
>    14
>    13
>    13
>    11
>    10
> 
> 4. Mr. Li said that he still doesn't know their ages. This means that the sum of their ages (as determined from step 3) is not enough information for him to determine their ages.
> 
> 5. Mr. Wang said that the youngest child's name is Xiaoming. This means that there is a unique youngest child among the combinations listed above.
> 
>    From the combinations, we can see that there is only one combination where one of the numbers is the smallest: 1, 6, 6. In this case, Xiaoming is the youngest child, and his age is 1.
> 
> Therefore, Xiaoming is 1 year old this year.

4.0的话中文好很多但是

> 我们发现只有年龄和为13的组合有两个：
> 
> 1. 1 + 6 + 6
> 2. 2 + 2 + 9
> 
> 第三步，老王透露最小的孩子是小明，这个信息让老李迅速知道了三个孩子的年龄。这意味着在这两个可能的组合中，只有一个组合有一个孩子的年龄明显小于其他两个孩子的年龄。所以正确的组合是：
> 
> 2 + 2 + 9
> 
> 因此，小明今年2岁。

她是如何正确推导出错误答案的？
如果翻译成英文的话，GPT的智商能提高很多。
