### ISSUE TITLE
[Feature] Railway Deploy -- one-click method?

### ISSUE THREAD

**Issue by alonemeow** [Yidadaa/ChatGPT-Next-Web#1314]

**Comment by Yidadaa** [comment]
why not vercel?

**Comment by asaketsu** [comment]
yes, why?

**Comment by devsfactory** [comment]
railway.app is not blocked in China and free!

**Comment by Yidadaa** [comment]
Railway's free plan does not support yiu use it 7*24 of a month. Free plan only has 500 hours credit.

**Comment by Yidadaa** [comment]
Buy a cheap domain and bind it on vercel, wont cost you more 10 yuan.
