### ISSUE TITLE
[Feature] 是否考虑调整现在余额显示逻辑

### ISSUE THREAD

**Issue by tjefferson** [Yidadaa/ChatGPT-Next-Web#1316]
**这个功能与现有的问题有关吗？**
现在余额显示的是_本月已使用_，而用户更关心的可能是_累计已使用_或者_还剩余_。

**你想要什么功能或者有什么建议？**
建议默认查询当天往前的近90天的已使用余额，这样对于处理免费试用期用户得到的应该就是累计已使用了。

**有没有可以参考的同类竞品？**
自己前段时间探索通过API查api key使用额度的时候在Python里用的这个接口，今天再次使用了接口还可用：https://api.openai.com/dashboard/billing/usage?end_date=2023-05-07&start_date=2023-02-07

**Comment by Yidadaa** [comment]
我是付费用户，我只关心本月订阅用量
