### ISSUE TITLE
快捷部署失败

### ISSUE THREAD

**Issue by TonyHuang0711** [Yidadaa/ChatGPT-Next-Web#132]
![05d02098de70605de0e18ad4174de8e](https://user-images.githubusercontent.com/60097976/228430495-a8191f23-ef08-4982-91ae-961ead50f2a9.png)

**Comment by ruixing1001** [comment]
重试下吧，vercel的问题，我们都可以的

**Comment by Yidadaa** [comment]
建议给 vercel 反馈。

**Comment by TonyHuang0711** [comment]
我后续使用了runway.app 跟vercel差不多 而且部署成功了&nbsp; 我猜测可能是新注册vercel的用户被block了



---原始邮件---
发件人: "ous50 | ousfifty | ***@***.***&gt;
发送时间: 2023年3月30日(周四) 凌晨2:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Yidadaa/ChatGPT-Next-Web] 快捷部署失败 (Issue #132)




  
重试下吧，vercel的问题，我们都可以的
  
我都试了差不多一个星期了，都是出错

**Comment by ous50** [comment]
> 我后续使用了runway.app 跟vercel差不多 而且部署成功了&nbsp; 我猜测可能是新注册vercel的用户被block了
> […](#)
> ---原始邮件--- 发件人: "ous50 | ousfifty | ***@***.***&gt; 发送时间: 2023年3月30日(周四) 凌晨2:32 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Yidadaa/ChatGPT-Next-Web] 快捷部署失败 (Issue #132) 重试下吧，vercel的问题，我们都可以的 我都试了差不多一个星期了，都是出错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我现在直接fork了一份，然后再手动配置就部署成功了
