### ISSUE TITLE
[Bug] The auto-complete feature cannot be directly turned off

### ISSUE THREAD

**Issue by ImAmelie** [Yidadaa/ChatGPT-Next-Web#1322]
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**

聊天界面的提示词补全按钮，打开后无法直接关闭，只有选择一个提示词后界面才会关闭。
我只是想浏览一下提示词都有哪些，但是没法直接关闭这个界面，我输入了 `/` 再删除 `/` 才关闭了这个界面。

**如何复现**

新建聊天，点击输入框上面第 3 个按钮。
官网地址可以复现此 Bug
<https://chatgpt.nextweb.fun/>

**截图**

![Bug](https://user-images.githubusercontent.com/7888766/236690799-1477577a-f523-4ccb-9590-4eca449790e5.png)

**一些必要的信息**

 - 系统：windows 11
 - 浏览器：chrome
 - 版本： 23230507
 - 部署方式：<https://chatgpt.nextweb.fun/>

**Comment by Yidadaa** [comment]
这个不是 bug，就是这么设计的，不然会造成候选 prompt 无法被点选。
