### ISSUE TITLE
[Bug] Docker deployment encountered the following issues, Can you help me see how to solve it？

### ISSUE THREAD

**Issue by yyds-space** [Yidadaa/ChatGPT-Next-Web#1324]
root@VM-24-5-ubuntu:# docker logs gptweb
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
http 127.0.0.1 7890
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16
Listening on port 3000 url: http://fd530bfe4852:3000/
[OpenAI Route] params { path: [ 'v1', 'chat', 'completions' ] }
[Auth] allowed hashed codes: []
[Auth] got access code:
[Auth] hashed access code: d41d8cd98f00b204e9800998ecf8427e
[User IP] 114.242.100.67
[Time] 5/8/2023, 2:15:39 AM
[Auth] use user api key
[Proxy] v1/chat/completions?path=v1&path=chat&path=completions
[Base Url] https://api.openai.com/
[proxychains] Strict chain ... 127.0.0.1:7890 ... timeout
[OpenAI] [TypeError: fetch failed] {
cause: [Error: connect ECONNREFUSED 224.0.0.1:443] {
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '224.0.0.1',
port: 443
}
}

**Comment by Yidadaa** [comment]
补充以下信息：
- 是否能直连 openai
- 启动命令是什么

**Comment by yyds-space** [comment]
连通：curl https://api.openai.com/v1/engines/davinci-codex/completions -H "Authorization: Bearer sk-xxx"
结果：连接超时
启动命令：docker run -d -p 3000:3000    -e OPENAI_API_KEY="sk-xxx"    -e CODE="123456"    -e PROXY_URL="http://127.0.0.1:7890"    --name gptweb    yidadaa/chatgpt-next-web

**Comment by Yidadaa** [comment]
架个代理，或者换个国外的服务器。

**Comment by yyds-space** [comment]
thanks!

**Comment by wangsensnow** [comment]
> thanks!

这种方式管用吗，我出现了同样的抛错。但是我的服务器是能访问到api地址的。使用docker-compose方式启动，非代理方式没问题，代理方式启动，每次调用接口就会抛这个错误。
