### ISSUE TITLE
[Bug] Vercel 部署CODE不是可选项

### ISSUE THREAD

**Issue by yyds-space** [Yidadaa/ChatGPT-Next-Web#1327]
![image](https://user-images.githubusercontent.com/53456544/236731950-a0a76058-e66a-4866-9ef9-c11aad92deee.png)

**Comment by GOWxx** [comment]
提供两个解决方法
- 链接里有`CODE`相关的删除，重新进入页面。
- 随便填一个，部署好后去环境变量里删除`CODE`，重新布署生效。
