### ISSUE TITLE
本地运行可以请求到chatGPT的Api，部署到vercel上后就无法请求了，vercel上也配置了openapi-key

### ISSUE THREAD

**Issue by jiantao88** [Yidadaa/ChatGPT-Next-Web#133]
![image](https://user-images.githubusercontent.com/7411102/228431760-32b8726c-0406-4b08-b04d-c1ad9f7f6b41.png)
![image](https://user-images.githubusercontent.com/7411102/228431976-dc945a5a-9218-431f-b7ef-230554ea490e.png)

是哪里配置不对吗？

**Comment by ruixing1001** [comment]
vercel配置完需要重新部署的
