### ISSUE TITLE
如何如何自定义请求URL？部署过程中没看到，尝试修改next.config.mjs也不对

### ISSUE THREAD

**Issue by SunnyGPT** [Yidadaa/ChatGPT-Next-Web#1336]
请问大佬，如何如何自定义请求URL？部署过程中没看到，尝试修改next.config.mjs里面的  destination: "https://api.openai.com/:path*",但是没用。找半天没找到，人麻了。

**Comment by Yidadaa** [comment]
环境变量 BASE_URL
