### ISSUE TITLE
[Bug] 选择使用gpt-4，但调用的是gpt-4-0314。

### ISSUE THREAD

**Issue by feeneyko** [Yidadaa/ChatGPT-Next-Web#1338]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
选择使用gpt-4模型，但在openai api usage界面显示调用的是gpt-4-0314。

**如何复现** **截图**
![image](https://user-images.githubusercontent.com/102637502/236959959-04afe2bc-fde1-4040-9359-61ca846c12ea.png)
![image](https://user-images.githubusercontent.com/102637502/236960000-fb4c937f-776b-40f5-aae3-38aafe8ae451.png)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器：chrome, safari
 - 版本： 20230508
 - 部署方式：vercel

感谢！

**Comment by Yidadaa** [comment]
openai 默认逻辑

**Comment by G2-star** [comment]
我也是GPT-4 API,我每天的Daily usage breakdown都是显示3.5和4的混合,所以这确实是openAI的默认逻辑 @feeneyko

**Comment by feeneyko** [comment]
> 我也是GPT-4 API,我每天的Daily usage breakdown都是显示3.5和4的混合,所以这确实是openAI的默认逻辑 @feeneyko

好的，谢谢
