### ISSUE TITLE
[Bug] 最近版本里的访问密码，与nginx中auth_basic冲突

### ISSUE THREAD

**Issue by sk163** [Yidadaa/ChatGPT-Next-Web#1339]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
之前用nginx配置chatgpt-next-web访问，又加了一层auth_basic，目前只要nginx加了这个，chatgpt-nex-web就报访问密码错误。
怀疑是header中用到了同一个字段：Authorization

**如何复现**
nginx中添加auth_basic，auth_basic_user_file配置

**截图**

**一些必要的信息**
 - 系统：windows 10/ macos 12
 - 浏览器： chrome,edge
 - 版本： 20230508
 - 部署方式：docker

**Comment by sk163** [comment]
清除数据后，正常了

**Comment by brodyxchen** [comment]
> 清除数据后，正常了

是哪个版本，v2.3吗？
我用docker image v2.3，清除浏览器数据后，没效果，还是一直弹nginx的登录

**Comment by sk163** [comment]
> > 清除数据后，正常了
> 
> 是哪个版本，v2.3吗？ 我用docker image v2.3，清除浏览器数据后，没效果，还是一直弹nginx的登录

是v2.3，不光要清除数据，还需要放行/api/***的路径才可以

**Comment by ivanberry** [comment]
放行后就能成功嘛？ 我最先发现了这个问题的，后面回退版本了，放行api接口不安全吧~

**Comment by sk163** [comment]
> 放行后就能成功嘛？ 我最先发现了这个问题的，后面回退版本了，放行api接口不安全吧~

我是放行api就行了，api会有程序本身的访问密码做验证，所以我就觉得新版本改的和nginx的auth basic有冲突

**Comment by Yidadaa** [comment]
@sk163 的方法是正解。

https://www.reddit.com/r/nginx/comments/111snvk/nginx_basic_auth_conflicts_with_upstream_services/

Ngnix Basic Auth 就是会有这种问题，后面我会进一步打薄转发层，基本不会考虑拆分 Authorization 头。

**Comment by GrayXu** [comment]
@sk163 不知道能不能给出一个配置例子呢，感谢！

**Comment by sk163** [comment]
> @sk163 不知道能不能给出一个配置例子呢，感谢！

就是nginx里再增加一个location，默认的带auth_basic校验，/api的路径不需要auth_basic校验
      location / {
        auth_basic "Please enter your username and password";
        auth_basic_user_file /xxx/xxx/htpasswd;
        proxy_pass https://xxxxxx/;
        ....
      }

      location /api {
        proxy_pass https://xxxxxx/api;
        .....
      }

**Comment by ivanberry** [comment]
> > @sk163 不知道能不能给出一个配置例子呢，感谢！
> 
> 就是nginx里再增加一个location，默认的带auth_basic校验，/api的路径不需要auth_basic校验
> 
> ```
>   location / {
>     auth_basic "Please enter your username and password";
>     auth_basic_user_file /xxx/xxx/htpasswd;
>     proxy_pass https://xxxxxx/;
>     ....
>   }
>   
>   location /api {
>     proxy_pass https://xxxxxx/api;
>     .....
>   }
> ```

这种方式，那就是部署时需要程序配置code罗，把不是要配置几个密码~~

1. nginx 密码
2. 应用的密码

不是很友好

**Comment by isr4z6er** [comment]
> 

不设置应用密码的话，似乎只要参照作者发的链接，在过完Nginx校验之后，proxy_pass给应用之前清掉Authorization header就可以了

我改了下自己的，目前看着好像ok

**Comment by MelBourbon** [comment]
Can somebody maybe explain a little bit in English what the solution is to use basic auth in nginx when deploying with docker? It seems there is a solution but I can not find it.
