### ISSUE TITLE
vercel 出错了，稍后重试  504 问题

### ISSUE THREAD

**Issue by gooker** [Yidadaa/ChatGPT-Next-Web#134]
尝试在vercel 删除重新deploy  修改区域,手动指定api key 都是无效, 稍后重试

vercel日志显示 
[POST] /api/chat-stream reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true

看了几个issue也说不出来什么,

但是 我用下面这个没有问题, 就是界面比next-web差一些
https://github.com/ourongxing/chatgpt-vercel

希望有指点一下,1分钟搭建快,用不起来啊

**Comment by AprilNEA** [comment]
这是 Vercel 的问题，请联系 Vercel

**Comment by gooker** [comment]
解决办法, #133  
https://vercel.com/xxx/xxx/deployments
redeploy

![image](https://user-images.githubusercontent.com/5688076/228437713-fe480eb5-66cf-43a1-8754-ae1e99166955.png)
