### ISSUE TITLE
[Bug] 返回不支持 v1/chat/completions，建议使用v1/completions

### ISSUE THREAD

**Issue by LNqueen** [Yidadaa/ChatGPT-Next-Web#1341]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
我使用时出现这个问题：
{
  "error": {
    "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}

**截图**
![image](https://user-images.githubusercontent.com/30171606/236983112-fa71f016-5b19-416b-854c-4d4b65624417.png)

**一些必要的信息**
 - 系统： windows 10
 - 浏览器： edge
 - 版本： 20230508
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
openai 的问题，或者你 key 有问题。
