### ISSUE TITLE
[Bug] 切换了模型gpt-4，但是去openai后台查看用的是gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by maple-dawn** [Yidadaa/ChatGPT-Next-Web#1342]
切换了模型gpt-4，但是去openai后台查看用的是gpt-3.5-turbo-0301，我确认我有gpt4的api权限，也在其他客户端用过
![0f27abf44f6f65c6967d64adc0edbd8](https://user-images.githubusercontent.com/2296214/236987805-71a913fd-cc79-430e-b0f1-34c5fdaaf11e.png)
![4e16f09df02b090863e8acbab279d6a](https://user-images.githubusercontent.com/2296214/236987851-dab7ecc8-fa02-47c1-ab5d-bb1d0fd6aea9.png)

![690ccab61ffd932d78e03a3b0a4c6ac](https://user-images.githubusercontent.com/2296214/236988230-5d2ca65b-bc23-4b03-9c4d-0982e24f906b.png)

**Comment by occamrazor1492** [comment]
你咋申请的

**Comment by StereoApp** [comment]
是不是用的之前的“面具”，面具里面的模型没改

**Comment by maple-dawn** [comment]
> 是不是用的之前的“面具”，面具里面的模型没改

面具是什么，我昨天用最新版本部署的

**Comment by maple-dawn** [comment]
> 你咋申请的

刚出的时候，在openai官网申请的

**Comment by maple-dawn** [comment]
> > 是不是用的之前的“面具”，面具里面的模型没改
> 
> 面具是什么，我昨天用最新版本部署的

去看了下，是用了面具，我试试不用面具

**Comment by maple-dawn** [comment]
> > > 是不是用的之前的“面具”，面具里面的模型没改
> > 
> > 
> > 面具是什么，我昨天用最新版本部署的
> 
> 去看了下，是用了面具，我试试不用面具

是用了面具的问题，我不用面具就正常了

**Comment by yay2008** [comment]
我也遇到了这个问题 但是没用面具

**Comment by emmmnaadada** [comment]
同样的问题

**Comment by maple-dawn** [comment]
遇到这个问题的朋友，提问gpt前，可以看看这里的模型是不是选了gpt4
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/2296214/7a25a5ac-00e6-4111-845b-487066cddb84)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/2296214/64d8a325-a49f-45ed-a505-e061833e8efb)
