### ISSUE TITLE
[Feature] 能否提供使用相同的Prompt， 批量泛化处理文件能力， 

### ISSUE THREAD

**Issue by chenzixin1** [Yidadaa/ChatGPT-Next-Web#1344]
**这个功能与现有的问题有关吗？**

有时候， 例如翻译一个文件， 文件长度远远超过 token 长度限制， 我需要有一个应用按照合适的大小读取文件， 然后丢给gpt 处理。 而且这个时候， 都要使用相同的prompt 。 

**你想要什么功能或者有什么建议？**

用途大大提升， 例如工单总结， 长文档翻译等等，规避了token 过长的问题

**有没有可以参考的同类竞品？**
[可以给出参考产品的链接或者截图。](https://github.com/ObservedObserver/chatgpt-i18n)

类似这个， 但是这个的Prompt 是固定的， 而且功能上，也只能适用于i18n 的翻译， 我需要的是泛化能力

**其他信息**

**Comment by Yidadaa** [comment]
你自己写脚本处理，这不是本项目的使用场景
