### ISSUE TITLE
[Feature] 建议加入对DALL•E的支持

### ISSUE THREAD

**Issue by rggt5656** [Yidadaa/ChatGPT-Next-Web#1358]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
建议加入对OpenAI的DALL•E图片生成模型的支持。我的设想是可以在设置里单独加入一个模型选择，可以选择DALL•E，另一种方式是选择gpt-3.5或者4模型时通过特定的命令(例如/img )调用DALL•E。

**有没有可以参考的同类竞品？**
例如这个chatgpt telegram机器人就支持生成图片，用的DALL•E:   https://github.com/TBXark/ChatGPT-Telegram-Workers

**其他信息**
由于DALL•E也是OpenAI家的，集成起来应该不是太复杂的，因为可以和gpt用同一个api key。虽然这个模型价格略贵，但是我有2500刀余额没地方用。

**Comment by zhuSilence** [comment]
> **这个功能与现有的问题有关吗？** 如果有关，请在此列出链接或者描述问题。
> 
> **你想要什么功能或者有什么建议？** 建议加入对OpenAI的DALL•E图片生成模型的支持。我的设想是可以在设置里单独加入一个模型选择，可以选择DALL•E，另一种方式是选择gpt-3.5或者4模型时通过特定的命令(例如/img )调用DALL•E。
> 
> **有没有可以参考的同类竞品？** 例如这个chatgpt telegram机器人就支持生成图片，用的DALL•E: https://github.com/TBXark/ChatGPT-Telegram-Workers
> 
> **其他信息** 由于DALL•E也是OpenAI家的，集成起来应该不是太复杂的，因为可以和gpt用同一个api key。虽然这个模型价格略贵，但是我有2500刀余额没地方用。

感觉你是来炫富的

**Comment by darth-pika-hu** [comment]
同来炫富

**Comment by Yidadaa** [comment]
你可以使用 #1428 这个 pr 的代码，不过目前我不准备合入主线，绘画并不是本应用的主要功能。

**Comment by Yidadaa** [comment]
或许等我把聊天相关的功能完善后会考虑合入与绘画相关的 pr。

**Comment by Yidadaa** [comment]
DALL E 效果太拉了，应该不可能加这玩意儿了。
