### ISSUE TITLE
[Bug] 历史摘要部分出现限制信息

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#1362]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
没有发送任何消息，出现了这个信息

**如何复现**
、

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48620527/c04c8154-5588-47d6-b3c8-c744b698e3de)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器： chrome
 - 版本： 20230509
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
出错了而已，很正常
