### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by aaluopy** [Yidadaa/ChatGPT-Next-Web#1373]
**这个功能与现有的问题有关吗？**
没有

**你想要什么功能或者有什么建议？**
**建议：希望支持设置每个角色的欢迎词（或者问候语）**
说明：定义角色的时候至少包含以下3个参数：名字，提示词，问候语。
名字就是角色名字，方便查找；提示词就是角色的定义；问候语就是打开与角色的聊天框之后，角色说的一句话。
目前打开聊天框是显示的角色的提示词，感觉这样不是有优雅。

**有没有可以参考的同类竞品？**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/121002916/0ea85ab8-16da-4c22-afff-961982b61151)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/121002916/966f29d2-639a-4968-80d7-426c6a551bb7)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/121002916/9a78d2a8-da8a-4a8f-807d-35e990255b1d)

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
你手动在面具里加一句 assistant 角色的欢迎语不就行了。

**Comment by Yidadaa** [comment]
<img width="1007" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/667eeb09-e944-459e-9fd6-5df62857b018">

<img width="1007" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/de7a22e0-2c27-4ea1-a70a-e6e9bf0e8c75">
