### ISSUE TITLE
[Request] the Discord Channel needs more managment

### ISSUE THREAD

**Issue by yanCode** [Yidadaa/ChatGPT-Next-Web#1374]
Hi @Yidadaa,
I'd like to take this ticket as a reminder that if you have some time, could you check out the Discord channel for this project? It's currently overrun by bots that are spamming endless nude and inappropriate content, making it almost impossible for real users to communicate. It would be great if you could assign some management members to keep the channel clean and user-friendly.

**Comment by Yidadaa** [comment]
I am going to close Discord Channel, and planning to migrate to telegram with more restricts.

**Comment by Yidadaa** [comment]
Have deleted discord channel.
