### ISSUE TITLE
[Feature] 如何使用GPT-4

### ISSUE THREAD

**Issue by allanming** [Yidadaa/ChatGPT-Next-Web#1375]
和chatgpt-web的配置方式一样吗？
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/29364324/13ad7d7b-50e8-476c-9d01-0b40461cfe5c)

**Comment by Yidadaa** [comment]
不一样，你必须有 gpt-4 api 权限才能用 gpt-4。
