### ISSUE TITLE
Zero, One and Few Shot Prompting

### ISSUE THREAD

**Issue by realskyrin** [Yidadaa/ChatGPT-Next-Web#138]
Few-show 可以简单的理解为在发送 prompt 时提前做一个 context mock，通过少量引导可以显著提升 AI 回复质量的技巧。

例如这个查单词小工具
```python
#!/usr/bin/env python3
# This is an English word search assistant.

import json
import requests
import sys
import os

OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
OPENAI_BASE_URL = os.environ.get('OPENAI_BASE_URL')


def query(message):
    message = json.dumps(message)

    if len(sys.argv) > 1:
        prompt = "你是一个英语单词查询助手，每当用户发送一个英语单词给你，你都要以固定格式响应用户，" \
                 "如果用户发给你的不是一个单词，回复 'invalid token'"

        response_few_shot_text = "run [/rʌn/]" \
                                 "\n\nn. 奔跑;竞赛;连续的演出\nHe went for a run after work. (他下班后去跑步了)" \
                                 "\n\nv. 奔跑;运行\nI like to run in the park every morning. (我喜欢每天早上在公园里跑步)" \
                                 "\n\nadj. 连续的;流畅的\nThis printer is really fast and runs smoothly. (这台打印机速度非常快，而且运行流畅)"
    else:
        print("This is an English word search assistant")
        print("Usage: qr word")
        return

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {OPENAI_API_KEY}"
    }

    data = {
        "model": "gpt-3.5-turbo",
        "temperature": 0,
        "top_p": 1,
        "frequency_penalty": 1,
        "presence_penalty": 1,
        "stream": False,
        "messages": [
            {"role": "system", "content": prompt},
            {"role": "user", "content": "run"},
            {"role": "assistant", "content": response_few_shot_text},
            {"role": "user", "content": message}
        ]
    }

    response = requests.post(OPENAI_BASE_URL, headers=headers, data=json.dumps(data))

    answer = json.loads(response.content)["choices"][0]["message"]["content"].strip()
    print("\033[32m---🤖---------\033[0m")
    print(answer)
    print("\033[32m--------------\033[0m")


if __name__ == "__main__":
    query(" ".join(sys.argv[1:]))
```
我在 request message 中 mock 了 system prompt、user 发送的第一个 prompt 以及 assistant 的一个 response
```
"messages": [
    {"role": "system", "content": prompt},
    {"role": "user", "content": "run"},
    {"role": "assistant", "content": response_few_shot_text},
    {"role": "user", "content": message}
]
```
那么我之后再发送任何单词，它都会很规范的返回结果 (返回单词的所有词性并造句)，因为 context 里已经 mock 了它返回的第一个结果，它知道接下来该怎么回复，而无需向它解释过多的东西
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/16552732/228439346-ff18b959-865d-4661-a64d-e8ad089667bf.png">

如果直接给它发消息作为 prompt 也就是直接一条 user prompt，效果就会差很多，有时候每个词性给出多条例句，或者就只给一个词性的例句

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/16552732/228440462-6fd5a57f-373b-442d-babe-c68184aaf204.png">
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/16552732/228440894-36fda931-9410-42e9-b7f4-ee3974878b7a.png">

这是 openai-cookbook 中关于 Few shot 的介绍：https://github.com/openai/openai-cookbook/blob/main/techniques_to_improve_reliability.md#few-shot-examples

除此之外，Few-shot 也有助于 AI 进行链式思维以提升结果的准确率，可以应用到很多场景。

我的想法是，可以给每个可以给每个 chat 单独设置 system、user、assistant 这些预设，简单一点的做法是给一个输入框，可以填入整个 request message 部分的 json :
```
"messages": [
    {"role": "system", "content": sys_prompt},
    {"role": "user", "content": "user_prompt"},
    {"role": "assistant", "content": response_few_shot_text},
    {"role": "user", "content": user_message}
]
```
请求的时候直接带上这个预设的 message。而且每次 request 仅带这个 message，不需要传入其它上下文，这样一来这个 chat 就变成一个相当稳定且节省 Token 的小工具了。

总之，这个项目非常很赞，只可惜自己不会前端所以以上想法没法直接提 PR，今天现在开始学前端 😂 

支持一波
![4321680072417_ pic](https://user-images.githubusercontent.com/16552732/228449797-dd6fc858-5322-4dcc-86cd-dffb2318593c.jpg)

**Comment by Yidadaa** [comment]
Prompt 列表是刚加的功能，后期会允许用户编辑单个对话的预设 prompt，和你说的功能应该是一致的，可以耐心等待。

**Comment by tisfeng** [comment]
学到了，Few-show 确实很有用 😌

**Comment by realskyrin** [comment]
一点UX构思
<img width="860" alt="image" src="https://user-images.githubusercontent.com/16552732/228723779-70159680-c0a1-494c-9043-452813908f6a.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/16552732/228725778-8ce2bc1c-ad77-48d8-8c27-72b5f5085cb3.png">

后续如果可能的话，可以把全局设置中的模型、随机性那部分挪到 Chat 设置的层级，使每个 Chat 的定义更灵活

**Comment by Cranberrycrisp** [comment]
赞，很有用的技巧

**Comment by tiwentichat** [comment]
> Prompt 列表是刚加的功能，后期会允许用户编辑单个对话的预设 prompt，和你说的功能应该是一致的，可以耐心等待。

如果用户每次对话都单独预设system role感觉有些繁琐，看到[chatgpt-vercel](https://github.com/ourongxing/chatgpt-vercel)这个项目里面是直接加到系统设置里面的。应该也是一种可以参考的方式

**Comment by realskyrin** [comment]
> > Prompt 列表是刚加的功能，后期会允许用户编辑单个对话的预设 prompt，和你说的功能应该是一致的，可以耐心等待。
> 
> 如果用户每次对话都单独预设system role感觉有些繁琐，看到[chatgpt-vercel](https://github.com/ourongxing/chatgpt-vercel)这个项目里面是直接加到系统设置里面的。应该也是一种可以参考的方式
>
这是可选的而不是强制的，如果不给对话设置 system、user、assistant 这些 in-context，那它就只是一个普通会话，不影响其原有属性。

**Comment by realskyrin** [comment]
另外多普及一点，in-context 中的 user、assistant prompt 和 system prompt 一样重要，要不然它们也没必要出现在 API 的示例中。OpenAI 的论文里有很多试验结果已经表明了 Few-shot 可以提升模型解决针对性问题的能力，一个 shot 其实就是 in-context 中的一个 user + assistant 的一问一答，给的例子越多它越准。

比如我上面给出的英语查单词小程序就是 1 shot，针对更复杂的应用场景你可以做 8 shot、25 shot。比较遗憾的是，目前我看到的所有套壳，都没有自定义 Few-shot 的功能，都是 0 shot，可能是觉得这样更方便使用？或者是大家不了解 Few-shot 这个概念，这无疑是把这条强大 API 的能力给绑起来了。我认为一个好的 AI 工具是给 AI 松绑而不是相反。

**Comment by Yidadaa** [comment]
感谢提供信息，我会考虑在单个对话页加入更详细的 few shot 编辑界面，让用户提供更丰富的预设上下文信息。

**Comment by xiaodi007** [comment]
realskyrin你的想法非常棒，经过你的启发，我是这么思考这一功能的。以函数的形式封装每一个功能，比如翻译，英文纠正。在用户选择初始化页面的时候，选择需要导入的function。类似我们coding时候的import。下面我给出几个例子，这些例子，我在3.5测试过，没有问题。如果是4的话效果更佳。

> 首先需要给GPT定义函数的prompt。
```
Hello, ChatGPT! I hope you are doing well. I am reaching out to you for assistance with a specific function. I understand that you have the capability to process information and perform various tasks based on the instructions provided. In order to help you understand my request more easily, I will be using a template to describe the function, input, and instructions on what to do with the input. Please find the details below:

function_name: [Function Name]
input: [Input]
rule: [Instructions on how to process the input]

I kindly request you to provide the output for this function, based on the details I have provided. Your assistance is greatly appreciated. Thank you!
I will replace the text inside the brackets with the relevant information for the function I want you to perform. This detailed introduction should help you understand my request more efficiently and provide the desired output. The format is function_name(input) If you understand, just answer one word with ok.
```

> 然后编写函数trans_word(这是一个可以输入中文，翻译成英语的function)
```  
function_name: [trans_word]
input: ["text"]
rule: [I want you to act as an English translator, spelling corrector and improver. I will provide you with input forms including "text" in any language and you will detect the language, translate it and answer in the corrected of my text, in English.]
```
> 然后编写函数expand_word(输入英文，扩充文本)
```
function_name: [expand_word]
input: ["text"]
rule: [Please serve as a Chatterbox, spelling corrector, and language enhancer. I will provide you with input forms including "text" in any language, and output the original language.I want you to Keep the meaning same, but make them more literary.]
```
> 然后编写函数fix_english(输入英文，修改美化文本)
```
function_name: [fix_english]
input: ["text"]
rule: [Please serve as an English translator, spelling corrector, and language enhancer. I will provide you with input forms including "text", I want you to improve the text's vocabulary and sentences with more natural and native. Keep the meaning same.]
```
> finally, 到了最终的时候了, 调用函数、甚至可以链式调用。
```
trans_word('婆罗摩火山处于享有“千岛之国”美称的印度尼西亚。多岛之国印尼有4500座之多的火山，世界著名的十大活火山有三座在这里。')
fix_english('Act as an English Translator and Improver')
fix_english(expand_word(trans_word('婆罗摩火山处于享有“千岛之国”美称的印度尼西亚。多岛之国印尼有4500座之多的火山，世界著名的十大活火山有三座在这里。')))

```

> 多参数的function也不在话下，可以省略参数名，也可以显式指定
```
function_name: [pg]
input: ["length", "capitalized", "lowercase", "numbers", "special"]
what to do with input: [I want you to act as a password generator for individuals in need of a secure password. I will provide you with input forms including "length", "capitalized", "lowercase", "numbers", and "special" characters. Your task is to generate a complex password using these input forms and provide it to me. Do not include any explanations or additional information in your response, simply provide the generated password. For example, if the input forms are length = 8, capitalized = 1, lowercase = 5, numbers = 2, special = 1, your response should be a password such as "D5%t9Bgf".]

pg(length = 10, capitalized = 1, lowercase = 5, numbers = 2, special = 1)
pg(10,1,5,2,1)
```

畅想，最后可以积木式调用，形成无限扩展。还可以形成指定领域的package，供别人使用。面向GPT编程， 哈哈哈。如果大家觉得这个想法不错，可以一起搞搞事情。

**Comment by realskyrin** [comment]
> 畅想，最后可以积木式调用，形成无限扩展。还可以形成指定领域的package，供别人使用。面向GPT编程， 哈哈哈。如果大家觉得这个想法不错，可以一起搞搞事情。
>
你这个思路很好，事实上很多基于 GPT 做的复杂应用也是这个路子（巨硬家的各种 Copilot），把需求进行无限拆解，拆到能被 GPT 稳定完成的一个个 function，因为 API 是可以并发去 call 的。所以在这些 function call 完之后把结果再组装回来，就能搞出很惊艳的效果。OpenAI 的这条 completion API 真的是有无限可能，值得好好学习。

**Comment by Yidadaa** [comment]
@xiaodi007 [langchain](https://python.langchain.com/en/latest/getting_started/getting_started.html) 正在做这个事情，官方的 chatgpt plugin 应该也是类似的思路。

**Comment by Yidadaa** [comment]
目前已经增加 contextual prompt 自定义功能，可以自行指定前置对话列表，可以尝试一下，入口：
- 对话框顶部 toast
- header 记忆 button

**Comment by realskyrin** [comment]
> 目前已经增加 contextual prompt 自定义功能，可以自行指定前置对话列表，可以尝试一下，入口：
> 
> * 对话框顶部 toast
> * header 记忆 button

@Yidadaa 试了一下，设计的非常棒，基本上就是这个效果了，辛苦了☕️

我用了 2 shot 让它实现 Grammarly 的功能。前面的 response 看起来还可，后面问了句重复的，它说它前面翻译过了😂，看起来它还是记忆了预设 context 之外的信息，这种进行过 Few-shot 的工具**不需要任何除预设 context 之外的信息**，可以给个 CheckBox 让用户勾选是否记住上下文，否则会影准确性。

**Context prompt**
![WeChatfe5f6403ab638ef3acd0252b100088e4](https://user-images.githubusercontent.com/16552732/229403420-6ad7a1a2-0c0f-43be-8cbd-a2b10c7522ce.png)

**使用示例**
![WeChat66fe2b3488c77520c937b5e2d81772c8](https://user-images.githubusercontent.com/16552732/229403564-bc51a0ad-ace1-4de7-9cbd-d11e45503225.png)
![WeChat9c917ff3307882c7b0e1af290a61fa80](https://user-images.githubusercontent.com/16552732/229403580-f4b0684e-04d2-42b4-a4b1-c5ecdeaebdd9.png)

**Comment by tiwentichat** [comment]
66666，好用

**Comment by Yidadaa** [comment]
@realskyrin 

在设置里把历史消息数量设置为 0 就行。

**Comment by realskyrin** [comment]
> @realskyrin
> 
> 在设置里把历史消息数量设置为 0 就行。

👍👍👍  可以了

**Comment by zealotCE** [comment]
> @realskyrin
> 
> 在设置里把历史消息数量设置为 0 就行。

但是现在的版本里面如果这么做的话，会不太方便。
所以建议：
1. 能否增加记忆的模板管理，并选择对应的记忆模板。（默认新聊天不使用记忆模板）
2. 记忆模板，无法快速粘贴导入，建议增加支持

第一个需求的实现的话，就可以满足重复使用记忆的能力了。（不然对话删除了就得重新再添加记忆）

**Comment by realskyrin** [comment]
> > @realskyrin
> > 在设置里把历史消息数量设置为 0 就行。
> 
> 但是现在的版本里面如果这么做的话，会不太方便。 所以建议：
> 
> 1. 能否增加记忆的模板管理，并选择对应的记忆模板。（默认新聊天不使用记忆模板）
> 2. 记忆模板，无法快速粘贴导入，建议增加支持
> 
> 第一个需求的实现的话，就可以满足重复使用记忆的能力了。（不然对话删除了就得重新再添加记忆）

@zealotCE Json 模版导入导出这个功能确实刚需，便于小工具分享和导入，不过这是个新需求了，可以新开 issues 进行讨论

**Comment by Cp0204** [comment]
@zealotCE  这个建议，其实和 prompt store 的思路是相通的。我的想法是用 json 导入导出，包括

1. 一组 Few-show ，其实就是 messages 中的多组 content。
```json
{"messages": [
  {"role": "system","content": "Role definition"},
  {"role": "user","content": "Input"},
  {"role": "assistant","content": "Output"}
]}
```

2. 单个pormpt，其实就是一个 user content
```json
{"messages": [
  {"role": "user","content": "prompt"},
]}
```

这样就打通了`前置上下文`和`提示词`的功能。同样，希望`前置上下文`功能支持单个 Chat 自定义历史消息，很多时候用 Few-show 的 Chat 并不需要历史消息。

我已经把 ChatGPT 集成到程序里，审核中文内容（能理解含义，其他AI无法做到）、做心理咨询，都是通过固定的 Json 格式输出，方便程序进一步处理。按这样 ChatGPT 能扩展出很多功能，不仅仅是聊天AI。

**Comment by realskyrin** [comment]
> > 
> 
> 是的，确实是这样。 另外，这里面还需要增加一个需求，就是关闭记忆，仅使用预设的 Few-show 来进行。不然，连续的对话，会导致模型不按照最早的预期走。

确实需要一个 Chat 级别的 CheckBox 开关来控制是否携带出预设之外的 Context。全局的那个设置为 0 之后，新建的其它普通 Chat 就没有上下文了

**Comment by realskyrin** [comment]
@Yidadaa ，另外发现两个小问题，通过 Request Payload 看到请求 Message 中携带了一个 system 角色的历史记忆总结，这个会影响 Few-shot 的稳定，建议在 Chat 级别的开关去掉。还有个问题是 `\n` 换行符在 Payload 中被转成 `\\n` 不知道这是不是预期的情况，从返回结果中看这回导致它直接返回 \n\n在消息中，而不是两个换行。

![WeChat9ca5dc03d7de70cb8fc86ef1f84fccf1](https://user-images.githubusercontent.com/16552732/229494756-e2c5a2df-27b6-4921-bca7-6b2be951aa9d.png)

**Comment by ClarenceYk** [comment]
> @realskyrin
> 
> 在设置里把历史消息数量设置为 0 就行。

请问作者能否每个 chat 单独设置历史消息数量呢？

**Comment by Yidadaa** [comment]
之后会更新此功能。

**Comment by asaketsu** [comment]
感觉目前这种添加Few-show的方式太容易被清除破坏了
对不不想变动、固定格式的对话，不太方便
有没有更好的法子Yidadaa

**Comment by realskyrin** [comment]
@asaketsu 重置对话或者清除，并不会清理前置上下文，你升级最新版看看

**Comment by hostemail** [comment]
> > 目前已经增加 contextual prompt 自定义功能，可以自行指定前置对话列表，可以尝试一下，入口：
> > 
> > * 对话框顶部 toast
> > * header 记忆 button
> 
> @Yidadaa 试了一下，设计的非常棒，基本上就是这个效果了，辛苦了☕️
> 
> 我用了 3 shot 让它实现 Grammarly 的功能。前面的 response 看起来还可，后面问了句重复的，它说它前面翻译过了😂，看起来它还是记忆了预设 context 之外的信息，这种进行过 Few-shot 的工具**不需要任何除预设 context 之外的信息**，可以给个 CheckBox 让用户勾选是否记住上下文，否则会影准确性。
> 
> ## **Context prompt**
> ![WeChat58dabcb6050fca19304252c1004c036a](https://user-images.githubusercontent.com/16552732/229404448-bbf49e0b-68d6-4777-8bad-814bbf486002.png)
> ![WeChatfe5f6403ab638ef3acd0252b100088e4](https://user-images.githubusercontent.com/16552732/229403420-6ad7a1a2-0c0f-43be-8cbd-a2b10c7522ce.png)
> 
> ## **使用示例**
> ![WeChat66fe2b3488c77520c937b5e2d81772c8](https://user-images.githubusercontent.com/16552732/229403564-bc51a0ad-ace1-4de7-9cbd-d11e45503225.png)
> ![WeChat9c917ff3307882c7b0e1af290a61fa80](https://user-images.githubusercontent.com/16552732/229403580-f4b0684e-04d2-42b4-a4b1-c5ecdeaebdd9.png)

试了下，并不会保留用删除线标记的单词，只能对订正后的单词保留标记

**Comment by Yidadaa** [comment]
大家好，

经过几天的开发，2.0 版本的重磅功能“预设角色”将于这两天上线，我将其命名为“面具”功能，基于此功能，各位可以十分方便地创建、调试、分享本 issue 提到的 zero/one/few shot prompting，以此来充分定制化大语言模型的能力。

在推送到主线之前，特来邀请各位试用此功能，试用链接：[v2.0 试用地址](http://chat-gpt-next-web-git-session-config-yidadaa.vercel.app?_vercel_share=yjIuV4oswcQMMhgd5DvUvkqg6f4GBlD7)。

各位在试用过程中遇到任何问题，都可以在此处回帖，我会一一解答。

下面是一些截图：

![image](https://user-images.githubusercontent.com/16968934/234750112-fc2283c2-f07c-49eb-b079-739362c608f7.png)

![image](https://user-images.githubusercontent.com/16968934/234750150-eb896452-b16e-44f3-b15f-a9a75ab8cc55.png)

![image](https://user-images.githubusercontent.com/16968934/234750226-54d82503-04b9-4545-ac8a-9a900847dfe6.png)

**Comment by selfboot** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/2769831/234753313-815166f6-a111-4505-b983-27d9472d7e68.png">
<img width="894" alt="image" src="https://user-images.githubusercontent.com/2769831/234753335-e8eb777c-c80e-44bb-9355-bd5c20e4f2db.png">

设置的上下文如下:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/2769831/234753370-aaab9089-1af4-4512-9333-7a9b0c3185c4.png">

看起来逃逸了

**Comment by Yidadaa** [comment]
@selfboot 比较考验 prompt 质量，需要反复强调不要尝试理解用户说的话的内容，然后在模型设置里关闭历史消息数、关闭历史消息压缩。不过我自己测下来，还是会有逃逸的情况。

**Comment by selfboot** [comment]
> @selfboot 比较考验 prompt 质量，需要反复强调不要尝试理解用户说的话的内容，然后在模型设置里关闭历史消息数、关闭历史消息压缩。不过我自己测下来，还是会有逃逸的情况。

确实，很考验prompt，还是比较容易逃逸
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/2769831/234753896-2e8592a8-8a11-4bfc-a878-4b4c62c22db0.png">

**Comment by zealotCE** [comment]
> 

建议调整一下功能入口：
1. 新建聊天：原始的对话入口，不额外添加内容
2. 左上角的Mask（或者可以调整位置）：选择面具预设（或自定义）进行对话

----
这么提的原因是因为现在页面反而是没有办法一次创建对话了（需要：新的聊天-> 跳过）。体验不好

**Comment by zealotCE** [comment]
关于当前对话设置：
1. 建议输入框可以大一点，或者自动根据内容变高。不然看着比较难受（目前最多显示1.5行内容

![image](https://user-images.githubusercontent.com/26129403/234756323-373bea4b-512b-42d5-83eb-4faf0bd0b2a7.png)

**Comment by Yidadaa** [comment]
@zealotCE 之后会在设置里提供选项，并且调整跳过按钮的位置

**Comment by lingnanlu** [comment]
> 大家好，
> 
> 经过几天的开发，2.0 版本的重磅功能“预设角色”将于这两天上线，我将其命名为“面具”功能，基于此功能，各位可以十分方便地创建、调试、分享本 issue 提到的 zero/one/few shot prompting，以此来充分定制化大语言模型的能力。
> 
> 在推送到主线之前，特来邀请各位试用此功能，试用链接：[v2.0 试用地址](http://chat-gpt-next-web-git-session-config-yidadaa.vercel.app?_vercel_share=yjIuV4oswcQMMhgd5DvUvkqg6f4GBlD7)。
> 
> 各位在试用过程中遇到任何问题，都可以在此处回帖，我会一一解答。
> 
> 下面是一些截图：
> 
> ![image](https://user-images.githubusercontent.com/16968934/234750112-fc2283c2-f07c-49eb-b079-739362c608f7.png)
> 
> ![image](https://user-images.githubusercontent.com/16968934/234750150-eb896452-b16e-44f3-b15f-a9a75ab8cc55.png)
> 
> ![image](https://user-images.githubusercontent.com/16968934/234750226-54d82503-04b9-4545-ac8a-9a900847dfe6.png)

NB! 期待已久!

**Comment by Yidadaa** [comment]
v2.0 数据兼容性测试已经通过，预计今晚可以发布。

**Comment by xingstarx** [comment]
很赞，期待ing

**Comment by cishan-zz** [comment]
最新版里有两个是地方设置历史记录条数。但是似乎只有全局设置生效了。还是说这个BUG只是存在DOCKER版本里

**Comment by Cp0204** [comment]
bug：默认预设的克隆不能删除，例如文案写手->查看->克隆预设

**Comment by ifp1090** [comment]
这种面具可否批量投喂类似但不同的信息然后批量返回信息？

**Comment by darth-pika-hu** [comment]
> @selfboot 比较考验 prompt 质量，需要反复强调不要尝试理解用户说的话的内容，然后在模型设置里关闭历史消息数、关闭历史消息压缩。不过我自己测下来，还是会有逃逸的情况。

你把Temperature 设为0-0.2，Presence Penalty设为-0.2试试。

**Comment by Yidadaa** [comment]
@darth-pika-hu 很好的建议！关于默认值，有更好的建议吗？或许我应该把随机性默认设置为 0.7 比较好？

**Comment by darth-pika-hu** [comment]
> @darth-pika-hu 很好的建议！关于默认值，有更好的建议吗？或许我应该把随机性默认设置为 0.7 比较好？

@Yidadaa 我比较倾向于把Temperature的默认值设为0.5. 
可能比较有争议, 但是以我在工作中的实测来看, Bing Chat 的三个选项 More Precise, More Balanced, 和 More Creative, 其实对应的差不多就是0.3, 0.5, 0.7.

**Comment by Yidadaa** [comment]
那我之后改成 0.5 吧，不然很容易出现逃逸。

**Comment by ChoKhoOu** [comment]
> > 畅想，最后可以积木式调用，形成无限扩展。还可以形成指定领域的package，供别人使用。面向GPT编程， 哈哈哈。如果大家觉得这个想法不错，可以一起搞搞事情。
> 
> 你这个思路很好，事实上很多基于 GPT 做的复杂应用也是这个路子（巨硬家的各种 Copilot），把需求进行无限拆解，拆到能被 GPT 稳定完成的一个个 function，因为 API 是可以并发去 call 的。所以在这些 function call 完之后把结果再组装回来，就能搞出很惊艳的效果。OpenAI 的这条 completion API 真的是有无限可能，值得好好学习。


如果 function 有很多个，并且足够复杂的话，用户能使用的上下文最大长度就会相应的变少。我比较好奇的是怎么尽可能减少这种 function 的 token 占用量？
可能将 Mask（沿用 Yidadaa 对角色提示的定义） 设计成单一职责可以一定程度解决这个问题。但如果把这个问题延伸到 ChatGPT 的 plugin 系统，一个插件中触发某个 api 的 description（描述该 api 何时触发，传入什么，返回什么） 最长为 200 个 token。如果现在有 10 个 plugin，并且每个 plugin 拥有 3 个 api。 那么此时 plugin 的 token 最坏情况下已经达到了 6000， 已经超过 gpt3.5 的限制了。

**Comment by Yidadaa** [comment]
@ChoKhoOu 这是无解的问题

**Comment by darth-pika-hu** [comment]
@ChoKhoOu @Yidadaa 有解的，很少人知道。首先要不怕花钱，而且需要配合别的参数调整。办法非常简单：就是你要提前告诉GPT说内容比较长，一共几部分，你要等我都给你了，你把几部分要当成一个完整内容来回应我的要求。然后你告诉他说这是第一部分，内容是balabala；这是第二部分......；这是最后的内容，balabala。

https://chatgpt-prompt-splitter.jjdiaz.dev

**Comment by Yidadaa** [comment]
@darth-pika-hu 

你发的这些经验是针对网页版的 ChatGPT，OpenAI 已经帮你做了记忆工作，当然可以通过切分 Prompt 来实现，但是 API 是没有任何记忆能力的，每次 API 调用都要想办法把记忆传入，但是单次交互总长就只有 4096，肯定要遗忘掉某些信息才行。所以对于 API 来说，这是无解的问题。

**Comment by darth-pika-hu** [comment]
- @Yidadaa 我用的就是API，网页版的容易飘，就是忘记前文，API可以调整，比较稳定。你尽管试试，用如下参数：

Model: GPT-4
Max Token: 4000
Temperature: 0.2
Presence Penalty: 0.6
Attached Message Count: 32
History Compression Threshold: 0

**Comment by Yidadaa** [comment]
我觉得我们对&ldquo;无解的问题&rdquo;理解有偏差，我们讨论的不是一个东西。


---Original---
From: &quot;Darth ***@***.***&gt;
Date: Mon, May 22, 2023 19:56 PM
To: ***@***.***&gt;;
Cc: &quot;Yifei ***@***.******@***.***&gt;;
Subject: Re: [Yidadaa/ChatGPT-Next-Web] Zero, One and Few Shot Prompting(Issue #138)




  
@Yidadaa 我用的就是API，网页版的容易飘，就是忘记前文，API可以调整，比较稳定。你尽管试试，用如下参数：
  
Model: GPT-4
 Max Token: 4000
 Temperature: 0.2
 Presence Penalty: 0.6
 Attached Message Count: 32
 History Compression Threshold: 0
 
&mdash;

**Comment by yanyongqi911** [comment]
出现BUG了，不能用啊，怎么解决？错误代码：
{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": null
  }
}

**Comment by realskyrin** [comment]
> > > 畅想，最后可以积木式调用，形成无限扩展。还可以形成指定领域的package，供别人使用。面向GPT编程， 哈哈哈。如果大家觉得这个想法不错，可以一起搞搞事情。
> > 
> > 
> > 你这个思路很好，事实上很多基于 GPT 做的复杂应用也是这个路子（巨硬家的各种 Copilot），把需求进行无限拆解，拆到能被 GPT 稳定完成的一个个 function，因为 API 是可以并发去 call 的。所以在这些 function call 完之后把结果再组装回来，就能搞出很惊艳的效果。OpenAI 的这条 completion API 真的是有无限可能，值得好好学习。
> 
> 如果 function 有很多个，并且足够复杂的话，用户能使用的上下文最大长度就会相应的变少。我比较好奇的是怎么尽可能减少这种 function 的 token 占用量？
> 
> 可能将 Mask（沿用 Yidadaa 对角色提示的定义） 设计成单一职责可以一定程度解决这个问题。但如果把这个问题延伸到 ChatGPT 的 plugin 系统，一个插件中触发某个 api 的 description（描述该 api 何时触发，传入什么，返回什么） 最长为 200 个 token。如果现在有 10 个 plugin，并且每个 plugin 拥有 3 个 api。 那么此时 plugin 的 token 最坏情况下已经达到了 6000， 已经超过 gpt3.5 的限制了。

OpenAI 官方支持了 Function calling, 稳定性终于得到解决，这是一个比 Plugins 更有价值的 Feature
https://openai.com/blog/function-calling-and-other-api-updates

@xiaodi007 @ChoKhoOu @Yidadaa

**Comment by Yidadaa** [comment]
插件功能将于 2023/07 开始开发，这将是本项目的 3.0 版本的重要更新功能。

**Comment by realskyrin** [comment]
> 插件功能将于 2023/07 开始开发，这将是本项目的 3.0 版本的重要更新功能。

泰酷辣！！！

**Comment by daiaji** [comment]
> Prompt 列表是刚加的功能，后期会允许用户编辑单个对话的预设 prompt，和你说的功能应该是一致的，可以耐心等待。

实际上，我们应该允许编辑所有对话，包括system、user和assistant的内容。在编辑后，可以清除历史摘要并重新发送。

我认为assistant的回答有待改进，希望她能改善用词风格，并纠正一些不恰当或因记忆错误而导致的用词问题。

此外，我自己的回复也可能存在错误，希望能进行修正。

**Comment by ifp1090** [comment]
请问新的插件可否支持：
1. GPT的文字语音转换，比如用ChatGPT当作英语教练来通过语音练习对话？
2. GPTshare功能可否支持某个页面自定义对话的分享？传统shareGPT的页面分享是整页分享出去的，但分享者也许只需要分享一部分的对话？
期待答复，谢谢！

**Comment by ifp1090** [comment]
>  我的意思是，类似「[Voice Control for ChatGPT](https://voicecontrol.chat)」浏览器插件的文本转语音功能，而不是GPT自己的翻译。

**Comment by 2-3-5-7** [comment]
> 您好，我尝试了自己create mask，效果不错。但是我发现一个问题。比如我在笔记本电脑上创建了mask，但是在手机端访问的时候就没有这个mask。或者我的朋友访问的时候，也没有mask。我想知道如何让这个create 的mask可以供所有人使用呢？希望能获得您的帮助，感谢🙏

所有数据都保存在浏览器本地 local storage，目前你想要分享给别人用，可以用 storage explorer 浏览器插件导出成 json 文件，然后在另一个浏览器导入。

**Comment by toyo2333** [comment]
我按你代码中的例子，在新版本的功能里添加了 system promp和那个run的问题以及回答例子

但是后续问其他问题，还是会出现，多条例句的情况。

这是什么原因呢？

**Comment by tel-gukan** [comment]
> 

哥们你的api没钱了啊

**Comment by tel-gukan** [comment]
@yanyongqi911 哥们你API 没钱了啊

**Comment by tel-gukan** [comment]
回复
出现BUG了，不能用啊，怎么解决？错误代码：
{
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": null
}
}

**Comment by Yidadaa** [comment]
[Tips] 如何使用用户输入模板 How to use Input Template  https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2144

**Comment by lyh0825** [comment]
> 另外多普及一点，in-context 中的 user、assistant prompt 和 system prompt 一样重要，要不然它们也没必要出现在 API 的示例中。OpenAI 的论文里有很多试验结果已经表明了 Few-shot 可以提升模型解决针对性问题的能力，一个 shot 其实就是 in-context 中的一个 user + assistant 的一问一答，给的例子越多它越准。
> 
> 比如我上面给出的英语查单词小程序就是 1 shot，针对更复杂的应用场景你可以做 8 shot、25 shot。比较遗憾的是，目前我看到的所有套壳，都没有自定义 Few-shot 的功能，都是 0 shot，可能是觉得这样更方便使用？或者是大家不了解 Few-shot 这个概念，这无疑是把这条强大 API 的能力给绑起来了。我认为一个好的 AI 工具是给 AI 松绑而不是相反。

麻烦可以给出相关的论文link吗

**Comment by Altap826** [comment]
Placement needs English translation Lataie Collins McCall Collins SUPREME Court chambers Laura M Jordan
