### ISSUE TITLE
[Feature] 增加对Azure openai的支持

### ISSUE THREAD

**Issue by yexia553** [Yidadaa/ChatGPT-Next-Web#1384]
**Is your feature request related to a problem? Please describe.**
openai还是要梯子才能访问，Azure openai没有这个限制，相对来说方便一些，大佬可以增加对Azure openai的支持吗？

**Describe the solution you'd like**
实现可以参考https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/quickstart?pivots=programming-language-python&tabs=command-line ，希望有用

谢谢~

**Comment by Yidadaa** [comment]
参考 https://github.com/Yidadaa/ChatGPT-Next-Web/pull/935

个人建议直接用这个：https://github.com/haibbo/cf-openai-azure-proxy
