### ISSUE TITLE
[Bug] 聊天记录中如果有链接，且链接后有文字会会被识别到一起。

### ISSUE THREAD

**Issue by Ya-chunJen** [Yidadaa/ChatGPT-Next-Web#1386]
**Describe the bug**
聊天记录中如果有链接，且链接后有文字会会被识别到一起。

**To Reproduce**
1. 发送内容：[https://www.baidu.com/s?wd=%E4%B8%BA%E4%B8%BA%E5%A5%BD。你好](https://www.baidu.com/s?wd=%E4%B8%BA%E4%B8%BA%E5%A5%BD%E3%80%82%E4%BD%A0%E5%A5%BD)

**Expected behavior**

**Screenshots**

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/37361257/44e1abed-b049-4e74-97c4-b870de3aefa8)

**Comment by Yidadaa** [comment]
请使用正确的 markdown 语法。

**Comment by Ya-chunJen** [comment]
1、不用要求用户严格按照Markdown语法输入；

**Comment by Ya-chunJen** [comment]
2、整合素材库 一起提交给ChatGPT，返回的内容可能并不会严格按钮Markdown格式返回。
