### ISSUE TITLE
如何修改会话名称呢？

### ISSUE THREAD

**Issue by LetheTK** [Yidadaa/ChatGPT-Next-Web#139]
看了文档和设置，没找到如何修改对话名称，只能自己生成吗？
自动生成的名称并不好，想修改没找到方法

**Comment by AprilNEA** [comment]
重复 issue

**Comment by LetheTK** [comment]
> 重复 issue

抱歉，找到之前的issue了，但是那个也没有解决办法

**Comment by Yidadaa** [comment]
#112

**Comment by linking123** [comment]
更新部署才看到。。能不能再优化下，使左侧列表上可修改会话名称？
