### ISSUE TITLE
[Feature] 可以增加知识库上传功能吗

### ISSUE THREAD

**Issue by Huiguorou12** [Yidadaa/ChatGPT-Next-Web#1390]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
等插件

**Comment by Mydtlwn** [comment]
@Yidadaa 可以增加一个covid-19毒株更新库的插件吗？具体信息可以采用pango阻止key-alias文件和lineage.txt文件，文件名我只用了，因为我记不住全名。
