### ISSUE TITLE
[Feature] 请问如何自定义默认身份设定？

### ISSUE THREAD

**Issue by MaydayV** [Yidadaa/ChatGPT-Next-Web#1391]
通过修某个文件内设定好身份，在提问时每次都会默认使用这个身份。除非切换选择其他的预设。

比如我要设定，让它拒绝回答关于任何国家的政治问题，在出现相关提问的时候，会根据设定的身份来拒绝回答。

**Comment by Yidadaa** [comment]
在这加：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/c39d75b448415b844750df69d7ace84948da8040/app/store/chat.ts#L255
