### ISSUE TITLE
点击左下角的设置出现了这个问题

### ISSUE THREAD

**Issue by maokaigang** [Yidadaa/ChatGPT-Next-Web#140]
Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by maokaigang** [comment]
TypeError: Cannot read properties of undefined (reading 'toString')

**Comment by maokaigang** [comment]
浏览器：Chrome 版本 111.0.5563.110（正式版本） (arm64)、Safari
操作系统：macOS ventura 13.2.1

**Comment by maokaigang** [comment]
我是根据 “保持更新 Keep Updated” 后出现的这个问题，重新fork了一下repo。
<img width="303" alt="image" src="https://user-images.githubusercontent.com/45286363/228464944-0d250d95-8059-49cf-8c5a-cbd41dc63420.png">

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/45286363/228464820-65b84040-4e31-4675-b446-441297c18282.png">

**Comment by Yidadaa** [comment]
应该是这行导致的问题：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/components/settings.tsx#L235

往 zustand store 里增加新的字段之后就会出现该问题，临时解决方法

```
title={`${config.fontSize ?? 14}px`}
```

后续完全解决，需要加强 store version number 和 zustand persist merge 函数的使用。

关联 PR: #89

**Comment by adminqe** [comment]
> 建议附上控制台报错截图，最好包含 stack trace。

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80828999/228467565-d4da0706-8835-498b-82f0-ae87a4aaba53.png">

mac chrome

**Comment by Yidadaa** [comment]
请更新后重试下。

**Comment by maokaigang** [comment]
可以了
