### ISSUE TITLE
[Feature] 导入聊天记录

### ISSUE THREAD

**Issue by AnYiEE** [Yidadaa/ChatGPT-Next-Web#1403]
最近在和异地的几个朋友一起讨论一个比较专业的话题，希望向gpt4问一些问题。但这个项目是面向个人的，没有任何同步和对API的权限控制功能，他们也没有gpt4的API key。所以他们只能把自己想问的问题告诉我，我再问给gpt，最后再导出聊天记录给他们，协作效率比较低。

今天翻了翻issue，看到这个 https://github.com/Yidadaa/ChatGPT-Next-Web/issues/920 ，感觉这个办法同样只适合自用。有的时候我不希望别人用我自己的webdav，这时上传一份统一调教好的对话记录我想更适合这种情景，每个人可以就这份对话继续问gpt自己想问的问题。

长话短说，希望设计一个上传原始对话数据的功能，以快速回到合适的上下文。因为哪怕是一模一样的话，gpt也不一定一模一样地回复。

**Comment by Yidadaa** [comment]
会和 #580 一起做

**Comment by weathery** [comment]
导入markdown格式的历史对话记录，这个功能的需求比较强烈。清理浏览器或者换一台设备，就得重新再问问题，效率比较底。

**Comment by Yidadaa** [comment]
合入 #920
