### ISSUE TITLE
[Bug] 自动总结聊天和前情提要的设计严重破坏后面的聊天准确度

### ISSUE THREAD

**Issue by ywgx** [Yidadaa/ChatGPT-Next-Web#1406]
**描述问题**

聊天里面,会自动总结聊天记录,作为前情提要发给 AI, 但是AI 毕竟不是人,并不能真正理解聊天内容,导致每次聊几次后,后面内容严重失真

**Comment by Yidadaa** [comment]
你可以手动关闭自动总结

**Comment by Yidadaa** [comment]
<img width="1007" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/23c02790-ac96-4715-8865-d241a2b2075a">
