### ISSUE TITLE
[Bug] 英语环境下，半角引号会被自动替换成全角引号

### ISSUE THREAD

**Issue by darth-pika-hu** [Yidadaa/ChatGPT-Next-Web#1410]
**Describe the bug**
输入的英文的半角引号会被自动替换成中文全角引号

**To Reproduce**
在英文界面下，输入一段带有半角引号的英语，提交。然后就会发现那段话所有的引号都变成了中文全角引号。

**Expected behavior**
保留英文半角引号。

**Screenshots**
不用截图了，一试就看到了。

**Deployment**
- [X] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [all]
 - Browser [all]
 - Version [all]

**Comment by Yidadaa** [comment]
![Uploading image.png…]()

**Comment by Yidadaa** [comment]
<img width="509" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/c77dd889-5e96-4aad-9d11-5aede8b85371">

**Comment by darth-pika-hu** [comment]
> 这显然是你输入法自动转的，我没事转它干啥，你用电脑输入试试。
看视频
https://github.com/Yidadaa/ChatGPT-Next-Web/assets/103236915/41c15345-1fa4-4915-8acf-cde0795528dc

**Comment by mraiguo** [comment]
我有一样的问题，macos

![2023-07-02 01-25-40 2023-07-02 01_26_24](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/22299421/c8d6cbcb-7447-492b-b710-bf6728361a9c)

**Comment by Yidadaa** [comment]
@mraiguo 先检查你是不是装了什么插件，再看看你的输入法是不是开了什么配置，这就是个简单的输入框，我没有对用户输入做任何替换操作，不可能是这个项目的问题。

**Comment by darth-pika-hu** [comment]
@mraiguo 作者开发环境配置有问题，不确定是不是因为他的中文环境或者输入法导致的。我试了好多台Mac机器，也让别人试过了，这个问题在Mac英文环境下会出现，但是不影响使用。

**Comment by mraiguo** [comment]
> 我有一样的问题，macos
> 
> ![2023-07-02 01-25-40 2023-07-02 01_26_24](https://user-images.githubusercontent.com/22299421/250296258-c8d6cbcb-7447-492b-b710-bf6728361a9c.gif)

<img width="609" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/22299421/660cd374-f57a-4586-9517-44a62b17f477">
