### ISSUE TITLE
[Bug] AIGC过程中偶然性错误：Oops,something went wrong!

### ISSUE THREAD

**Issue by fntp** [Yidadaa/ChatGPT-Next-Web#1411]
**Describe the bug**
当我提完问题之后，在文字以打字机效果滚动显示的时候，突然报错

**Example**
直接上图吧，希望能对作者分析问题有作用：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46984923/4cc9d777-0f4f-4d50-83c3-a977a482c1ed)

**Comment by Yidadaa** [comment]
浏览器版本兼容性问题，建议使用最新版本的 chrome 或者 edge。

**Comment by fntp** [comment]
> 浏览器版本兼容性问题，建议使用最新版本的 chrome 或者 edge。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46984923/af9e310d-766d-421d-bd90-0202b07602ff)
Edge已经是最新版

**Comment by Yidadaa** [comment]
能否提供出错消息的原始文本？

**Comment by Yidadaa** [comment]
右键单击消息复制即可。

**Comment by fntp** [comment]
老哥说的是AIGC的内容还是我发问题的内容

**Comment by fntp** [comment]
好的，以下是完整的切点表达式：

```
execution(返回值类型 包名.类名.方法名(参数类型, ...))
```

其中，各个部分的含义如下：

- 返回值类型：方法返回值的类型，可以使用 `*` 表示任意类型。
- 包名.类名：要拦截的类的全限定名。
- 方法名：要拦截的方法名。
- 参数类型：要拦截的方法的参数类型，可以使用 `*` 表示任意类型，也可以使用具体的类型。

例如，如果要拦截类 `com.example.MyClass` 中的方法 `myMethod`，参数类型为 `int` 和 `String`，返回值类型为 `void`，可以使用以下切点表达式：

```
execution(void com.example.MyClass.myMethod(int, java.lang.String))
```

如果要拦截所有返回值类型为 `int` 的方法，可以使用以下切点表达式：

```
execution(int *(..))
```

这个切点表达式中，`*` 表示返回值类型可以是任意类型，`(..)` 表示方法参数可以是任意类型和数量。

**Comment by Yidadaa** [comment]
应该是触发了 markdown 的渲染错误，这问题不好定位，凑合用吧。
