### ISSUE TITLE
[Bug] {   "cause": {     "name": "ConnectTimeoutError",     "code": "UND_ERR_CONNECT_TIMEOUT",     "message": "Connect Timeout Error"   } } 部署到docker无法正常聊天

### ISSUE THREAD

**Issue by XAAIGTnG** [Yidadaa/ChatGPT-Next-Web#1412]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
架代理。

**Comment by XAAIGTnG** [comment]
这个错误是说无法访问openai吗

**Comment by XAAIGTnG** [comment]
> 架代理。

这个错误是指无法访问openai?

**Comment by Yidadaa** [comment]
是的，如果要架梯子，使用 PROXY_URL 设置一下环境变量

**Comment by XAAIGTnG** [comment]
> 是的，如果要架梯子，使用 PROXY_URL 设置一下环境变量

想问一下，如果我不调用openai的话，而是一个`ip+端口/v1/completions`的话，要改哪里呢

**Comment by Yidadaa** [comment]
用 BASE_URL 环境变量，设置成 ip+端口 就行

**Comment by hisaige** [comment]
有时候正常，有时候Connect Timeout Error，可否加个参数自定义超时时间

> 用 BASE_URL 环境变量，设置成 ip+端口 就行
