### ISSUE TITLE
[Bug] Clashes among hot keys 

### ISSUE THREAD

**Issue by yanCode** [Yidadaa/ChatGPT-Next-Web#1413]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/2328124/fa3df88b-3ba1-497e-8ae0-d7f093ca637a)

Please reproduce all the issues following my steps:
1. input a question `how can i make money from sleeping?`, send it. when it replies, clean the input text area. so far so good.

2. if you click the icon which I marked as **2** in the snapshot. the `Prompt list` modal pops up, representing a list of prompts for you to select. but if you hit `Arrow Up`, you can see the question you asked before as in **1** shows up in the input text area.   the best solution to it, I believe, is to input a `/` into the input area when clicking the icon. this not only fixes this bug, but also gives more consistency with opening the  'Prompt list' by typing `/`.  users can search prompts by directly typing after the `/`, or close the modal by removing `/`.  without this `/`, the user cannot close the modal, unless a prompt is selected, neither search prompts, unless manually type a `/`.

3. when switching chat window by hitting hot key 'cmd + arrow up' as in this commit https://github.com/Yidadaa/ChatGPT-Next-Web/pull/1361/commits/2b7f72deec7dec5ccbe5583c10e81af7cf136808,  the previous message `how can i make money from sleeping?` shows up again.

in a conclusion, the logic of pressing `Arrow up` key to restore previously sent question can handle the issue in 2, as long as it inputs a '/' in the input text area. but it should stop working when `cmd/alt/ctrl` are pressed as in 3.

I am going to submit a PR to all these bugs.

**Comment by Yidadaa** [comment]
I forgot to handle these cases. Looking forward to your pull request.
