### ISSUE TITLE
[Feature] 上下文截断功能

### ISSUE THREAD

**Issue by Juexe** [Yidadaa/ChatGPT-Next-Web#1415]
**你想要什么功能或者有什么建议？**
我想和一个 Mask 在一个对话内持续对话，希望能随时展开新的话题，而不用创建多个对话

**有没有可以参考的同类竞品？**
Poe 做的很好可以参考下。点击“清空上下文”并不会清空聊天记录，只是清除了上下文，并且重新带入预设的 Prompts
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/26461438/43c4aab6-5aa6-448f-9c32-c5529f36647e)

**Comment by bravohenry** [comment]
重新开一个聊天框不好吗

**Comment by yaojingguo** [comment]
重新开一个聊天框的话，聊天历史就没有了。@Juexe的诉求是清楚context，但是不清聊天记录。

**Comment by Yidadaa** [comment]
不错的功能，之后的版本会更新此功能。

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/7619e712-8e23-4e86-95f3-ae82c91ac3f7)
