### ISSUE TITLE
我写了一个绑卡教程，可以在这里分享吗？

### ISSUE THREAD

**Issue by woodchen-ink** [Yidadaa/ChatGPT-Next-Web#1418]
教程： https://woodchen.ink/1241.html

**Comment by Yidadaa** [comment]
发到 discussions 里去，别在这发。

https://github.com/Yidadaa/ChatGPT-Next-Web/discussions

**Comment by woodchen-ink** [comment]
> 发到 discussions 里去，别在这发。
> 
> https://github.com/Yidadaa/ChatGPT-Next-Web/discussions

好的，sorry
