### ISSUE TITLE
[Bug] 在飞书里打开新建聊天直接报错

### ISSUE THREAD

**Issue by JerryliDe** [Yidadaa/ChatGPT-Next-Web#1430]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
#703
