### ISSUE TITLE
[Bug] TypeError: Reflect.get called on non-object causing 500 error on Cloudflare Pages deployed application

### ISSUE THREAD

**Issue by jwjoel** [Yidadaa/ChatGPT-Next-Web#1436]
**Title**: TypeError: Reflect.get called on non-object causing 500 error on the deployed application

**Describe the bug**
The deployed application on Cloudflare Pages is not functioning properly. All endpoints produce a 500 error, and the specific error is `TypeError: Reflect.get called on non-object`. I have retried multiple times and ensured that I followed the deployment instructions provided for the Cloudflare Pages.

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the deployment instructions for Cloudflare Pages as outlined in the documentation.
2. Visit the deployed application (or just use mine at `https://chat-6ne.pages.dev/`).
3. Attempt to access any endpoint.
4. Encounter a 500 error with the `TypeError: Reflect.get called on non-object`.

**Logs**
```
{
  "outcome": "ok",
  ...
  "logs": [
    {
      "message": [
        "TypeError: Reflect.get called on non-object"
      ],
      "level": "error",
      "timestamp": 1683851965380
    }
  ],
  ...
  "event": {
    "request": {
      ...
    },
    "response": {
      "status": 500
    }
  },
  "id": 5
}
```

**Deployment**
- [ ] Docker
- [ ] Vercel
- [x] Cloudflare Pages (chat-6ne.pages.dev)

**Comment by Yidadaa** [comment]
Are you following this instruction? 

ttps://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/cloudflare-pages-en.md

BTW, cloudflare pages is not recommended, please consider to use Vercel.

**Comment by jwjoel** [comment]
> Are you following this instruction?
> 
> https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/cloudflare-pages-en.md
> 
> BTW, cloudflare pages is not recommended, please consider to use Vercel.

Yes, that's the one I was following.

**Comment by darth-pika-hu** [comment]
@jwjoel Cloudflare Pages is not an easy solution. It is very buggy. You have to do some development and debugging to make it work.
