### ISSUE TITLE
[Bug] 有个css加载了42s，是否可以把他注释掉呢

### ISSUE THREAD

**Issue by LiberatorHg** [Yidadaa/ChatGPT-Next-Web#1444]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我部署在服务器上，用chrome和edge的时候加载这个css很慢。

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/52238701/c5f9fb8d-0eb3-4525-be65-67fb0c04b517)

**一些必要的信息**
 - 系统：[windows 11]
 - 浏览器： [chrome, edge]
 - 版本： [最新版]
 - 部署方式：[docker+服务器部署]

**Comment by Yidadaa** [comment]
https://stackoverflow.com/questions/32759272/how-to-load-css-asynchronously

**Comment by MrrDrr** [comment]
https://fonts.proxy.ustclug.org/css2?family=Noto+Sans+SC:wght@300;400;700;900&display=swap
我也遇到了这个问题，可能ustclug的这个服务还是不稳定。但目前已经恢复了，ustclug已经把自己的服务301重定向了到了原始的google接口。不过google接口在国内的稳定性也是emmmmm

建议把字体下载到仓库里，一起部署。或者就用系统默认的字体。

**Comment by yorunning** [comment]
可以考虑用nextjs的`Font`优化，这是通过在编译时下载字体，生产环境不用外链字体了。但下载字体还是通过google的网站，如果使用vercel部署没问题，但用docker部署如果网络连通性不好可能存在下载超时。还没找到`next/font`替换下载端点的配置项。

**Comment by Yidadaa** [comment]
@yorunning next font 的字体优化设置之后不对中文字体生效，没什么用。
