### ISSUE TITLE
[Bug] Cloudflare pages 配置了环境变量BASE_URL, 但是没有生效

### ISSUE THREAD

**Issue by flawflew** [Yidadaa/ChatGPT-Next-Web#1445]
参照[cloudflare-pages-cn.md](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/cloudflare-pages-cn.md) 部署的.
但是最终请求的是https://5*****a.chatgpt-next-web-867.pages.dev/api/openai/v1/chat/completions
返回Error 500

**Comment by Yidadaa** [comment]
我建议你用 vercel。

**Comment by flawflew** [comment]
> 我建议你用 vercel。

能用, 但是要梯子. 国内体验很差. 对了QQ群满了, 有无2群?

**Comment by Yidadaa** [comment]
你绑个自定义域名就能连&nbsp;vercel&nbsp;了。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月12日(周五) 晚上6:09
收件人: ***@***.***&gt;;
抄送: &quot;Yifei ***@***.******@***.***&gt;;
主题: Re: [Yidadaa/ChatGPT-Next-Web] [Bug] Cloudflare pages 配置了环境变量BASE_URL, 但是没有生效 (Issue #1445)




   
我建议你用 vercel。
  
能用, 但是要梯子. 国内体验很差. 对了QQ群满了, 有无2群?
  
可以套CF，然后用优选Ip，国内访问速度很快
 
&mdash;

**Comment by darth-pika-hu** [comment]
@flawflew 直接改代码
