### ISSUE TITLE
[Feature] 提问

### ISSUE THREAD

**Issue by Winter-is-comingXK** [Yidadaa/ChatGPT-Next-Web#1448]
有考虑过为不同的人工智能模型提供统一的接口吗，可以让别的开发者适配不同的ai（例如文心一言、讯飞星火、阿里通义千问）
并且选择不同的模型时，设置页面也会改变，比如说文心需要提供cookie等等

**Comment by Yidadaa** [comment]
等我有了这次模型的权限再说，我现在一个都没有。

**Comment by Winter-is-comingXK** [comment]
> 等我有了这些模型的权限再说，我现在一个都没有。

我可以提供文心和星火的账号，你需要吗
