### ISSUE TITLE
[Bug] 请问为什么docker启动环境变量没有生效

### ISSUE THREAD

**Issue by zyoung1212** [Yidadaa/ChatGPT-Next-Web#1453]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
docker启动命令如下：
docker run -d -p 80:3000 \
   -e OPENAI_API_KEY="sk-xx" \
   -e CODE="123456789" \
   -e DISABLE_GPT4="1" \
   -e BASE_URL="http://xxx:3001" \
   yidadaa/chatgpt-next-web

输入命令，能看到环境变量：
docker exec -it 2ca4b env
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm
container=podman
NODE_VERSION=18.16.0
YARN_VERSION=1.22.19
DISABLE_GPT4=1
BASE_URL=http://xxx:3001
PROXY_URL=
OPENAI_API_KEY=sk-xx
CODE=123456789
HOME=/root

进入页面无需输入密码，apikey也没有被设置好

**一些必要的信息**
 - 系统：centos8  
docker -v
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 3.3.1
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：docker

**Comment by zyoung1212** [comment]
已解决，抱歉是我的问题。

**Comment by adamqc** [comment]
我也遇到了类似的问题。能否指点一下？谢谢。

**Comment by jackywu** [comment]
@zyoung1212 还没有更新到最新的docker镜像里面么？

**Comment by rockyou** [comment]
docker 20230614这个DOCKER版本中DISABLE_GPT4仍然没有生效
