### ISSUE TITLE
【BUG】反代域名后，跟AI对话会卡顿非实时输出，词汇量大后会报错不回复

### ISSUE THREAD

**Issue by Linxsh7** [Yidadaa/ChatGPT-Next-Web#1462]
反代域名后，跟AI对话会卡顿非实时输出，词汇量大后会报错不回复
如果不使用反代域名，就是正常的回复 正常输出结果，也不会报错

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E9%83%A8%E7%BD%B2%E7%9A%84%E7%89%88%E6%9C%AC%E6%B2%A1%E6%9C%89%E6%B5%81%E5%BC%8F%E5%93%8D%E5%BA%94
