### ISSUE TITLE
[Feature] 可以增加多api轮询吗？

### ISSUE THREAD

**Issue by Ptuer-swpu** [Yidadaa/ChatGPT-Next-Web#1465]
我知道作者之前回复过不会做，但是我发现其他类似项目可以实现这个给功能，但其他功能没有作者的完善，型问下作者是否可以去看靠一下其他项目，看看这个功能是否可行，毕竟多用户并行访问能力实在是太差了
以下是我发现的其他类似项目的跳转链接https://github.com/ourongxing/chatgpt-vercel

**Comment by Yidadaa** [comment]
https://mp.weixin.qq.com/s/L8HMOqkjflh9gAIiRpSKZQ
