### ISSUE TITLE
请问大家都是搭建在海外主机吗？

### ISSUE THREAD

**Issue by pkids** [Yidadaa/ChatGPT-Next-Web#1468]
请问大家都是搭建在海外主机吗？我是家里路由器安了小飞机，用笔记本电脑连路由器能上openai官网，nas连路由器，在ssh里ping openai.com也能连得上

`PING api.openai.com (104.18.6.192) 56(84) bytes of data.
64 bytes from 104.18.6.192 (104.18.6.192): icmp_seq=1 ttl=52 time=247 ms
64 bytes from 104.18.6.192 (104.18.6.192): icmp_seq=2 ttl=52 time=253 ms
64 bytes from 104.18.6.192 (104.18.6.192): icmp_seq=3 ttl=52 time=185 ms
64 bytes from 104.18.6.192 (104.18.6.192): icmp_seq=4 ttl=52 time=245 ms`

但是在nas里不管搭建ChatGPT-Next-Web 还是 ChatGPT-Web，都不行，都提示类似

`{
  "cause": {
    "errno": -3001,
    "code": "EAI_AGAIN",
    "syscall": "getaddrinfo",
    "hostname": "api.openai.com"
  }
}
`

在nas里安了个angntgpt倒是能访问

我有个米国虚拟主机，但是不是服务器，我想把PROXY_URL指向我那个虚拟主机里写的一个能接收post数据的php文件，那它来接收nas发送过来的信息，并且中转发送给openai.com，不过貌似也不行....

**Comment by Yidadaa** [comment]
为什么不用 vercel，7 块钱买个域名，两分钟解决。
