### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Winter-is-comingXK** [Yidadaa/ChatGPT-Next-Web#1472]
等我有了这些模型的权限再说，我现在一个都没有。

_Originally posted by @Yidadaa in https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1448#issuecomment-1546544981_
            我可以提供文心和星火的账号，你需要吗

**Comment by Yidadaa** [comment]
文心一言貌似没有提供 api？
