### ISSUE TITLE
[Bug] 文生图能力无法显示图片

### ISSUE THREAD

**Issue by huangkaoya** [Yidadaa/ChatGPT-Next-Web#1473]
**Describe the bug**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/29002330/9782e5b5-45e2-4454-a0d3-a6789a05737c)
无法显示图片

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
这是 chatgpt 返回的图片，不是 ai 绘画，不保证图片一定可用。
