### ISSUE TITLE
[Feature] 那只猫可以旁边自定义一个我自己的链接吗? 

### ISSUE THREAD

**Issue by snownightflower** [Yidadaa/ChatGPT-Next-Web#1477]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chaoyu1999** [comment]
我想你应该是在说把github的图标旁边再加个你自己的链接

**Comment by JerryChen0734** [comment]
自己改就行了

**Comment by Yidadaa** [comment]
https://mp.weixin.qq.com/s/m7sSi1J-g1gWvWVsUKSEYw
