### ISSUE TITLE
[Bug] the behavior of moving items using hotkey are not consistent

### ISSUE THREAD

**Issue by yanCode** [Yidadaa/ChatGPT-Next-Web#1480]
for prompt list,  if you use hotkey to move the items up, when the selected item comes to the first or the last, if you continue to hit the key to move onwards, it stops to move, I think this is more natural.

but the for UI of changing chat session, when it comes to the first chat session, if you hit the key to continue, it goes to the last item. while it's in the last item, if you want to continue to move, it goes to the very beginning.

I think the behavior should be consistent as in the Prompt List. 
I am going to create a PR to this issue.

**Comment by Yidadaa** [comment]
This is by design, prompt list is different from chat list, prompt list shows dynamic options, and chat list is always considered to be static.
