### ISSUE TITLE
[Feature] 能否考虑支持Access Token模式？

### ISSUE THREAD

**Issue by huomqh** [Yidadaa/ChatGPT-Next-Web#1484]
**你想要什么功能或者有什么建议？**
因为新的openai账号注册三个月后，不绑卡不能用apikey了，找了一圈发现一个项目pandora支持一种Access Token模式，获取网页的accesstoken填入项目就能用了。所以能否考虑也实现支持一下。

**有没有可以参考的同类竞品？**
https://github.com/pengzhile/pandora

**Comment by Yidadaa** [comment]
#1008
