### ISSUE TITLE
[Bug] 气泡渲染错误

### ISSUE THREAD

**Issue by imldy** [Yidadaa/ChatGPT-Next-Web#1488]
**Describe the bug**

对话气泡无法渲染某些格式的文本

**To Reproduce**
 
任意对话框输入`[测试]:测试`或者：
```
[测试]:
测试
```
或者`[张三]:你好`

**Expected behavior**
当作纯文本原样显示

**Screenshots**

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/53949747/40a1e809-74e6-452b-8b2f-e469ad87fe64)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 113.0.5672.93

**Comment by Yidadaa** [comment]
Github 的评论输入框也有这个问题，看来 markdown 语法本身就是这样。

**Comment by Yidadaa** [comment]
@Kosette 长知识了
