### ISSUE TITLE
发现修改单词回复限制，没有任何作用

### ISSUE THREAD

**Issue by tpjaord1983** [Yidadaa/ChatGPT-Next-Web#149]
![image](https://user-images.githubusercontent.com/36291579/228489038-33389d0a-e981-4666-aa29-f9c687b88f11.png)
难道是我设置错了？
我也没找到保存的按钮

**Comment by Yidadaa** [comment]
修改后默认保存，你可以通过查看控制台的网络请求判断是否生效。
