### ISSUE TITLE
DALL•E 这个功能建议可以做个 输入框切换按钮 不用打命令

### ISSUE THREAD

**Issue by kevins0116** [Yidadaa/ChatGPT-Next-Web#1494]
DALL•E 这个功能可以做个 输入框切换按钮  
例如：文字对话/绘画/语音（语音可以为下一步先做UI铺垫，哈哈）  这样就不用为 输入 /image  这样的指令 

另外今天测试有个小问题 安卓 对话列表 日期不显示....不知道是不是手机问题.....

**Comment by Yidadaa** [comment]
#1358
