### ISSUE TITLE
[Bug] 长回复时 stream 的数据没有按照文本块切分导致丢字

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#1498]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
长回复时 stream 的数据没有按照文本块切分，导致解析出错。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/c56cbb79-593b-441d-9689-d984a2d8be20)

**如何复现**
询问一个回复很长的问题即可。

**一些必要的信息**
- 已知 vercel 平台会引起该问题。

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/9e602eb5755a9fe6d912501c087cdd9cbf19abd9/app/client/platforms/openai.ts#L100

几种可能的解决办法：
- 基于括号匹配的方式解析返回的 json 数据流
- 使用 middleware rewrite 请求的方式转发请求，而不是在 edge function 中捕获转发

可能的原因：推测是使用 edge function 转发请求之后，stream 数据流被 vercel 的服务器 buffer 了，导致 openai 返回的数据分段无法被正确检测。

**Comment by Yidadaa** [comment]
最终方案：使用 `fetch-event-source` 库来解决这个问题。

**Comment by Ptuer-swpu** [comment]
仍然漏字

**Comment by Ptuer-swpu** [comment]
还是漏字啊，大佬
