### ISSUE TITLE
如何部署到自己阿里云服务器上？

### ISSUE THREAD

**Issue by ZhuningS** [Yidadaa/ChatGPT-Next-Web#15]
阿里云海外服务器

**Comment by Yidadaa** [comment]
你好，可以问问 chatgpt，使用下面的 prompt：

如何使用 pm2 和 yarn 部署 nextjs 到 ubuntu 服务器上，项目启动命令为 yarn start，端口为 3000，使用 ngnix 做反向代理，环境变量为 OPENAI_API_KEY
