### ISSUE TITLE
对话经常出现“出错了，稍后重试吧”，这是因为不是plus会员导致的吗？

### ISSUE THREAD

**Issue by tpjaord1983** [Yidadaa/ChatGPT-Next-Web#150]
对话经常出现“出错了，稍后重试吧”，这是因为不是plus会员导致的吗？
现在用的是免费版的apikey
3.5的版本，经常会出现输入继续的时候，接不上气，就显示“出错了”

**Comment by Yidadaa** [comment]
两个原因：
1. openai 服务器不够用，限流了
2. 你的 api key 用的人太多了，被 openai 限流了
