### ISSUE TITLE
[Bug] 在手机飞书内访问报错

### ISSUE THREAD

**Issue by JerryliDe** [Yidadaa/ChatGPT-Next-Web#1502]
**Describe the bug**

**To Reproduce**
1. 在手机飞书内访问
2. 直接报一大堆错

**Expected behavior**
请修复

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
#703 

不会对陈旧 webview 做兼容。
