### ISSUE TITLE
[Feature] 发现个chrome的插件，可以调用搜索引擎和chatgpt实现类似new bing的功能

### ISSUE THREAD

**Issue by firmitfeng** [Yidadaa/ChatGPT-Next-Web#1504]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
发现个chrome的插件，可以调用搜索引擎和chatgpt实现类似new bing的功能。具体的功能是将关键字在搜索引擎中的结果传给chatgpt，之后由chatgpt返回一个类似摘要的内容。使用上比较像new bing的chat功能。项目地址：https://github.com/qunash/chatgpt-advanced

**有没有可以参考的同类竞品？**
参考作者的github 页面 https://github.com/qunash/chatgpt-advanced

**其他信息**
觉得这个功能比较有趣，也比较实用，所以提交一下：）

**Comment by Yidadaa** [comment]
#165
