### ISSUE TITLE
[Bug]  openai.ts中openaiUrl.slice并不改变openaiUrl的值

### ISSUE THREAD

**Issue by Gan-Xing** [Yidadaa/ChatGPT-Next-Web#1509]
openai.ts文件中

if (openaiUrl.endsWith("/")) openaiUrl.slice(0, openaiUrl.length - 1);
这一段openaiUrl.slice并没改变openaiUrl的值，处理无效
改为下面代码
 path(path: string): string {
    let openaiUrl = useAccessStore.getState().openaiUrl;
    if (openaiUrl.endsWith("/"))
      openaiUrl = openaiUrl.slice(0, openaiUrl.length - 1);
    return [openaiUrl, path].join("/");
  }

**Comment by Yidadaa** [comment]
确实有问题，忘了赋值回去了，或者用 `splice`
