### ISSUE TITLE
Setting choose “GPT-4” Model can't response correctly

### ISSUE THREAD

**Issue by macshion** [Yidadaa/ChatGPT-Next-Web#1512]
模型选择为GPT-4时的回复（key有4的API权限）：
<img width="869" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/31300385/d18c4935-a965-4e65-9b7b-b0402ce5ca18">

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":"Hello"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":"!"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":" How"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":" can"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":" I"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":" help"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":" you"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":" today"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{"content":"?\n"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7GNHHlJuwvbdHb2wTzfubUvNoHZQj","object":"chat.completion.chunk","created":1684137083,"model":"gpt-4-0314","choices":[{"delta":{},"index":0,"finish_reason":"stop"}]}

data: [DONE]

**Comment by Yidadaa** [comment]
刷新页面就行了。
