### ISSUE TITLE
[Bug] gpt突然变得不通顺

### ISSUE THREAD

**Issue by Rayforward** [Yidadaa/ChatGPT-Next-Web#1514]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
1.以前(即星期五，5.13，17时)没发现，今天发现gpt的回复非常不通顺，会出现明显的疑似一句完整的话里少了一个字两个字的回答。
2.换了好几个浏览器，包括从来没用来打开网页的edge，但是发现手机上的chrome就没有这个问题，WIN10特供问题？
3.重新部署了下，用另一个域名打开，重新输入访问密码，问题依旧
**如何复现**
随便问什么

**截图**
![SharedScreenshot](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45681350/0366ff1b-983f-4387-a013-435cb712c94b)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器： waterfox、chrome、edge都是
 - 版本：20230514
 - 部署方式：vercel

**Comment by Quincynickyoung** [comment]
确实我也遇到了相似的问题，不知道是什么原因

**Comment by babyfacehl** [comment]
me too，掉字了

**Comment by Yidadaa** [comment]
等待 #1498 修复，重构导致的丢字。
