### ISSUE TITLE
[Bug]  出错了，稍后重试吧  ...

### ISSUE THREAD

**Issue by ZouloveGhack** [Yidadaa/ChatGPT-Next-Web#1516]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
不明

**描述问题**
我部署后就会出现出错了，稍后重试吧 我重新部署很多次还是一样我使用的是gpt-3.5-turbo API有设置我不清楚怎么回事
**如何复现**
就正常部署容器部署完后打开网站 https://chat-gpt-next-web-eta-sage-70.vercel.app/ 和AI聊天就这样
[POST] /api/openai/v1/chat/completions?nxtPpath=v1%2Fchat%2Fcompletions status=429
**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/28489226/c2aa478d-4157-4327-b0d9-6cd228e07067)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/28489226/b8120084-a966-4e4f-8fb0-51177eabad85)

**一些必要的信息**
 - 系统： windows 10
 - 浏览器： chrome
 - 版本： v2.4
 - 部署方式：vercel

**Comment by Ymjie** [comment]
me to

**Comment by OvOxin** [comment]
一样

**Comment by zhuSilence** [comment]
<img width="1351" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8224393/d2fd8abe-741a-4fa4-bafb-1c3954495ad6">
用你的站点，填了个自己的 key 没提示有错误呀，不过样式有点问题，代码块格式乱了。

**Comment by Yidadaa** [comment]
控制台截图提供一下

**Comment by kknnnyy** [comment]
今天把容器更新了也报一样的错误，下面是日志
[Auth] allowed hashed codes:  []
[Auth] got access code: 
[Auth] hashed access code: d41d8cd98f00b204e9800998ecf8427e
[Chat Stream]  [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
}

**Comment by tangtaojim** [comment]
- 一样出错了，稍后充实提示，
![ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/128790642/1e453df7-dea4-40bf-a1f0-330faaed2bba)

**Comment by ZouloveGhack** [comment]
> <img alt="图像" width="1351" src="https://user-images.githubusercontent.com/8224393/238325119-d2fd8abe-741a-4fa4-bafb-1c3954495ad6.png"> 用你的站点，填了自己的密钥没提示有错误呀，不过样式有点问题，代码块格式乱了。

奇怪怎么你可以用到😂

**Comment by skyintree** [comment]
> 

> <img alt="图像" width="1351" src="https://user-images.githubusercontent.com/8224393/238325119-d2fd8abe-741a-4fa4-bafb-1c3954495ad6.png">用你的站点，填了个自己的 key 没提示有错误呀，不过样式有点问题，代码块格式乱了。

代码块乱了的问题和这个没有关系，参考 #1498

**Comment by chejg** [comment]
我也出现同样的问题，不过解决了。
目前感觉原因是：
github上更新同步最新代码后，网页端并没有刷新，然后发起了对话，出现了”出错了，请稍微重试吧“，刷新代码后，在该对话下出现同样的错误。
发起新对话后一切正常。
