### ISSUE TITLE
[Bug] 企业微信浏览器报错

### ISSUE THREAD

**Issue by DayoWang** [Yidadaa/ChatGPT-Next-Web#1518]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
企业微信中打开，设置访问密码或API Key 无效，报错，使用别的浏览器访问正常

**如何复现**
用企业微信打开，设置访问密码或API Key均无效，报错，提示访问密码不正确或为空

**截图**
提示访问密码不正确或为空

**一些必要的信息**
 - 系统：[windows 10/ macos 12/ android 11 / ios 16]
 - 浏览器： [企业微信浏览器]
 - 版本： [20230515]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
不会处理任何 webview 兼容性问题。
