### ISSUE TITLE
[Bug] 设置里面设置模型，再切回来不生效，需要清浏览器缓存才行

### ISSUE THREAD

**Issue by polishgem** [Yidadaa/ChatGPT-Next-Web#1519]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
设置里的模型设置和对话内的模型设置是分离的，关注 #1478
