### ISSUE TITLE
我想请问下，请求的接口会请求两次，有一个重定向的308，我看了下接口地址多了个“/”,请问下这个是bug还是特别设计成这样？

### ISSUE THREAD

**Issue by slrem** [Yidadaa/ChatGPT-Next-Web#1535]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/31646684/96621255-bf45-49c9-8ad6-9219f5a36c8c)

**Comment by Yidadaa** [comment]
是 bug，什么版本的代码？

**Comment by Yidadaa** [comment]
昨晚应该已经修复了

**Comment by slrem** [comment]
docker的镜像，昨天下午拉的镜像

**Comment by Yidadaa** [comment]
docker&nbsp;慢一拍，等下次&nbsp;release&nbsp;吧


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月16日(周二) 下午2:06
收件人: ***@***.***&gt;;
抄送: &quot;Yifei ***@***.******@***.***&gt;;
主题: Re: [Yidadaa/ChatGPT-Next-Web] 我想请问下，请求的接口会请求两次，有一个重定向的308，我看了下接口地址多了个&ldquo;/&rdquo;,请问下这个是bug还是特别设计成这样？ (Issue #1535)




 
docker的镜像，昨天下午拉的镜像
 
&mdash;

**Comment by slrem** [comment]
好的，谢谢！
