### ISSUE TITLE
部署完成后无法对话，一直显示。。。 

### ISSUE THREAD

**Issue by itiamm** [Yidadaa/ChatGPT-Next-Web#1539]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/51830481/e0b46fc0-a391-477d-8620-c5bf9d218a98)

**Comment by Jialinvip** [comment]
是的，我也遇到了，V2.4版本，发不出消息，一直显示3个进度条在动，不会自动停止，也不会提示出错。以前发不出消息会提示：Error: "出错了，稍后重试吧",现在不提示了，什么情况呀？
