### ISSUE TITLE
[Bug] 发不出消息时，一直显示3个进度条在动，不会自动停止

### ISSUE THREAD

**Issue by Jialinvip** [Yidadaa/ChatGPT-Next-Web#1541]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。

V2.4版本，发不出消息，一直显示3个进度条在动，不会自动停止，也不会提示出错。以前发不出消息会提示：Error: "出错了，稍后重试吧",现在不提示了，什么情况呀？

**如何复现**
发不出消息时候。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
[http://pic.yupoo.com/gptvip/d550a3b5/3af405b9.png](url)

**一些必要的信息**
 - 系统：[比如 windows 10]
 - 浏览器： [比如 chrome]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[服务器部署]

**Comment by aussiekidd** [comment]
我也遇到相同问题

**Comment by taoabsilent** [comment]
俺也一样...第一次问题可以正常回答,第二次就会卡死

**Comment by taoabsilent** [comment]
刚测试了,同样的问题再问一遍就好了,不知道什么原因导致的.

**Comment by yanCode** [comment]
我想我这个bug的原因我已经知道了，我再做一些测试，确定下来之后我来提交pull request.

**Comment by Yidadaa** [comment]
merged: #1554
