### ISSUE TITLE
[Bug] 关于用户消息渲染出错的问题

### ISSUE THREAD

**Issue by chaoyu1999** [Yidadaa/ChatGPT-Next-Web#1543]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46945475/4884d90e-ba66-4f3c-a491-978a76400758)

> 如图，我发送的消息如下，消息中没有markdown格式的文本，但是我的消息还是会被渲染一部分，看起来不美观，希望能够修复：

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46945475/bbd76ff3-fe4a-4697-8632-4c0d9b2746ff)
**消息文本：**
请把这个代码改成只要后序遍历的：
void traverse(TreeNode* root) {
    stack<pair<TreeNode*, int>> stack;
    stack.push({root, 1}); // 1表示前序,2表示中序,3表示后序
    
    while (!stack.empty()) {
        auto top = stack.top();
        stack.pop();
        
        if (top.second == 1) { // 前序
            cout << top.first->val << " ";
            top.second = 2; // 下面访问左子树,所以切换到中序
            stack.push(top);
            if (top.first->left) stack.push({top.first->left, 1}); 
        } else if (top.second == 2) { // 中序
            cout << top.first->val << " ";
            top.second = 3; // 下面访问右子树,所以切换到后序
            stack.push(top);
            if (top.first->right) stack.push({top.first->right, 1});
        } else { // 后序
            cout << top.first->val << " ";
        }
    }
}

**Comment by Quorafind** [comment]
这其实是 Markdown 的一个默认渲染特性：因为在 Markdown 渲染中会将 tab 或者 四个空格来视作 \`\`\` ：https://www.markdownguide.org/extended-syntax/#:~:text=The%20basic%20Markdown%20syntax%20allows,have%20to%20indent%20any%20lines!

解决你这个问题的最佳办法是，你可以尝试用 \`\`\` 来包住这个代码
如以下：
````
```
void traverse(TreeNode* root) {
  stack<pair<TreeNode*, int>> stack;
  stack.push({root, 1}); // 1表示前序,2表示中序,3表示后序
  
    while (!stack.empty()) {
        auto top = stack.top();
        stack.pop();
        
        if (top.second == 1) { // 前序
            cout << top.first->val << " ";
            top.second = 2; // 下面访问左子树,所以切换到中序
            stack.push(top);
            if (top.first->left) stack.push({top.first->left, 1}); 
        } else if (top.second == 2) { // 中序
            cout << top.first->val << " ";
            top.second = 3; // 下面访问右子树,所以切换到后序
            stack.push(top);
            if (top.first->right) stack.push({top.first->right, 1});
        } else { // 后序
            cout << top.first->val << " ";
        }
    }
}
```
````
