### ISSUE TITLE
[Feature] Support Claude and Google PaLM

### ISSUE THREAD

**Issue by wk-mike** [Yidadaa/ChatGPT-Next-Web#1550]
希望能支持一下Claude，听说是免费的，感觉比较友好。Claude 已经接近 GPT4

网上收集的Claude优势：
- Claude 比 GPT3.5 质量好，响应又快
- Claude-instant API 也更新到了 v1.1  版本。
- 增强了代码能力，写作能力，指令遵循能力。
- 增强了安全性。
- Claude 支持 100k上下文，视频 demo ：100k上下文能做什么  https://vxtwitter.com/anthropicai/status/1656700154190389248

100k 上下文的 Claude 已经可以在 https://poe.com/Claude-instant-100k 体验，会员每月可用100次，会员价20美金/月
Claude 100k 用起来了！
1. 先把 claude 的 API 转成 OpenAI 的格式https://github.com/jtsang4/claude-to-chatgpt
2. 找到支持无限输入的客户端 ChatBox，并填写API
https://github.com/Bin-Huang/chatbox/releases
3.模型选择 GPT4，对应就是 claude 100k
3. 随便找一篇万字长文丢进去，居然算两万多token
4. 总结成功

感受
- 总结速度真的非常快，考虑到这么多字数，速度比 bing 还快，不能不满意。
- 视频字幕，会议纪要，小说章节，都能一分钟get精髓。
- 和高情商的 Claude 闲聊一天都保持记忆

可以将 Claude API 转换成 ChatGPT 的 API，在各个 ChatGPT 工具中使用。已支持最新的 100k 系列模型 https://github.com/jtsang4/claude-to-chatgpt

同类产品：
有这么一个项目刚刚支持了Claude API
https://github.com/swuecho/chat

这是很良性的竞争，让我们多支持下 OpenAI 以外的模型。

**Comment by Yidadaa** [comment]
我没有 api 权限

**Comment by wk-mike** [comment]
@Yidadaa 我也正在申请Claude API ，只有等申请到Claude API再来了

Claude   https://www.anthropic.com/product


申请链接：https://www.anthropic.com/earlyaccess


API说明：https://console.anthropic.com/docs/api

**Comment by Yidadaa** [comment]
早就申请了，没有回音

**Comment by Yidadaa** [comment]
如果有人原因贡献 Claude api，可以通过我主页邮箱发送给我，Claude 集成代码上线后即可收回。

**Comment by cwyalpha** [comment]
> 如果有人愿意贡献 Claude api key，可以通过我主页邮箱发送给我，Claude 集成代码上线后即可收回。

apikey已发送邮箱，model选择claude-v1.3-100k就是100k
目前也可以使用https://github.com/jtsang4/claude-to-chatgpt 套壳使用..

**Comment by Yidadaa** [comment]
@cwyalpha 已收到，感谢，近期会增加 palm 和 claude 的支持。

**Comment by Caixiaopig** [comment]
能支持Palm就太棒了，期待！

**Comment by gwoweiming** [comment]
PaLM 的api我有，不过这个不支持中文，如果有需要可以找我。

**Comment by Blues-star** [comment]
目前claude2新模型上线，支持100K上下文，期待对claude的支持

**Comment by Yidadaa** [comment]
国产大模型：
1. 讯飞
2. 通义千问
3. minimax

**Comment by CrazyZard** [comment]
追一下 ， claude2、azure 模型的调用， 等好久了 啥时候能上呀 。。。。

**Comment by orangefei** [comment]
同求claude 调用

**Comment by solaris256** [comment]
同求claude2的调用啊，能用cookie调用就行

**Comment by onlinedear** [comment]
期待早日上线

**Comment by sam1am** [comment]
I would like to add to this that I would like to be able to configure multiple chat back-ends and choose between them per conversation. Currently it seems you can only configure one back end and then choose the model on that back-end per conversation. 

I'd like llama2 and other models supported via openai compatible API's and be able to switch back and forth between them easily for different use cases.

**Comment by liangyimingcom** [comment]
同求claude2的调用啊

**Comment by Yidadaa** [comment]
由于 claude api 糟糕的跨域表现，以及 palm api 糟糕的跨语言支持，本项目在经过测试之后决定放弃其他模型的原生支持，如有需要集成这些模型，请使用 https://github.com/songquanpeng/one-api

**Comment by johnsmzr** [comment]
Please add support for claude 3, it's god-like.
