### ISSUE TITLE
[Bug] 设置页面中查询余额时报错，具体截图可见。

### ISSUE THREAD

**Issue by ycz87** [Yidadaa/ChatGPT-Next-Web#1552]
**Describe the bug**
设置页面中查询余额时报错，具体截图可见。

**To Reproduce**
1. 进入设置页面
2. 在余额查询中点击“重新检查”
3. 提示：“访问密码不正确或为空。。。。。”

**Expected behavior**
已确保密码和API正确，因为其他功能可以正常使用

**Screenshots**
![Snipaste_2023-05-17_08-02-42](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/891286/55cdc656-57c5-4c43-8de9-c3a027c649d7)

**Deployment**
- [ ] Docker
- [√] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 113

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.
采用了API2D的API，没试过原生API

**Comment by bob0627** [comment]
原生API应该没问题，我用azure的api也是提示这个，不影响使用，具体啥原因没研究。

**Comment by Yidadaa** [comment]
api2d 没有兼容这个接口。
