### ISSUE TITLE
[Bug] 没有回复，一直loading

### ISSUE THREAD

**Issue by Klauxs** [Yidadaa/ChatGPT-Next-Web#1558]
**Describe the bug**

**To Reproduce**
1. 使用vercel一键部署
2. 填入openaikey
3. 可以访问，不回复，一直三个点

**Expected behavior**
正常回复

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49930065/6c7497bd-27a2-482c-8e78-f48d663a7f59)

**Deployment**
- [ ] Docker
- [✅] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [2.4，]

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
更新一下你的代码，最新版本修复了这个问题。

**Comment by Klauxs** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49930065/2d7214de-ef3c-47b2-a69d-50415c8628b6)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49930065/a243d56b-8260-4407-bb97-2647e9712d9d)
刚更新了，还是这样。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49930065/b58ee43e-a2b1-4ba4-a38e-6fa435661168)

**Comment by junchao98** [comment]
我也遇到同样问题

**Comment by kevinwu06** [comment]
我也是
