### ISSUE TITLE
Chrome App的icon大小不对

### ISSUE THREAD

**Issue by Taragryen** [Yidadaa/ChatGPT-Next-Web#156]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/44627712/228511701-05ad46f2-5e9c-4985-9d20-7f35723245d9.png">
旁边的youtube也是chrome app，可以对比一下icon大小

**Comment by sunao1985** [comment]
<img width="758" alt="Xnip2023-04-18_14-48-03" src="https://user-images.githubusercontent.com/44838089/232694337-89747d85-4f35-4e3e-9a44-6d3032a8d088.png">
<img width="581" alt="Xnip2023-04-18_14-48-23" src="https://user-images.githubusercontent.com/44838089/232694352-4ca773df-2e36-490e-81dd-ce1931a050ba.png">

**Comment by sunao1985** [comment]
<img width="987" alt="image" src="https://user-images.githubusercontent.com/44838089/232694860-152dd61c-c7fc-48b2-8e07-901d0fde7033.png">
自己刚才制作了一个，替换后非常完美。
不过，还是希望作者能解决。

**Comment by sunao1985** [comment]
查了下文档，应该是按照图标sizes设置去匹配不同平台的。建议尝试下：
{
  "name": "My PWA",
  "short_name": "My PWA",
  "icons": [
    {
      "src": "icons/windows/icon-16x16.png",
      "sizes": "16x16",
      "type": "image/png"
    },
    {
      "src": "icons/windows/icon-32x32.png",
      "sizes": "32x32",
      "type": "image/png"
    },
    {
      "src": "icons/windows/icon-48x48.png",
      "sizes": "48x48",
      "type": "image/png"
    },
    {
      "src": "icons/windows/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "icons/windows/icon-256x256.png",
      "sizes": "256x256",
      "type": "image/png"
    },
    {
      "src": "icons/macos/icon.icns",
      "sizes": "1024x1024",
      "type": "image/png"
    }
  ],
  "start_url": "index.html",
  "display": "standalone",
  "theme_color": "#ffffff",
  "background_color": "#ffffff"
}
