### ISSUE TITLE
[Bug] 切换窗口会导致回答重新开始

### ISSUE THREAD

**Issue by morningos** [Yidadaa/ChatGPT-Next-Web#1566]
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**

切换窗口会导致回答重新开始。

**如何复现**

让他回复一个长对话，期间切换窗口或者标签页，会导致回答终止，重新开始。

**截图**

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/44289789/8a728959-9dbb-43c5-965e-b50003f4f65e)

**一些必要的信息**
 - 系统：Windows 10
 - 浏览器： Chrome, Edge
 - 版本： 20230516
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
@yanCode 好的，感谢，最近上班比较忙，没什么时间修 bug。

**Comment by Yidadaa** [comment]
fixed by #1573
