### ISSUE TITLE
如何启用https？

### ISSUE THREAD

**Issue by fearlessxjdx** [Yidadaa/ChatGPT-Next-Web#1567]
有便捷的方法在内部启用https吗？

我用的是docker镜像，我试着用nginx做反代来实现，但发现gpt的打字动画会消失，不知道原因。

**Comment by Yidadaa** [comment]
https 自己研究下 ngnix 怎么上 ssl 证书。

第二个问题看这里：https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1570#issuecomment-1550997269
