### ISSUE TITLE
[Bug] 在Android的WebView上，基础功能会有异常。

### ISSUE THREAD

**Issue by chenshuiguqq** [Yidadaa/ChatGPT-Next-Web#1568]
**Describe the bug**
我通过Android的客户端上嵌入WebView，加载我部署的ChatGPT-Next-Web服务。然后里面的功能使用不正常。
如下图：
<img width="491" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/42374492/5ceb4b54-3af0-4ad6-aedd-61635ea6e6bd">
“直接开始”和”不再展示“点击都无效。
<img width="487" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/42374492/d61aeaf1-b3c1-478f-b762-09aa646d8199">
聊天发问后，也一直处于加载中。在浏览器上是正常的。只有在Android的WebView控件上加载，会有问题。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
不会处理任何 webview 兼容性问题。
