### ISSUE TITLE
关于PROXY_URL环境变量的问题

### ISSUE THREAD

**Issue by lukesyy** [Yidadaa/ChatGPT-Next-Web#1569]
![微信截图_20230517154706](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/70319988/86a1f1c0-2b47-4339-b4ba-cd82f2b02956)
![1111](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/70319988/e0dd4425-24ac-4ec8-838b-a9587c9e4c05)

我不知道 我哪里配置的有问题 我测试了socks5 是可用的 但还是连接不上openai

**Comment by lukesyy** [comment]
> 

http 需要加 --net=host \ 吗

**Comment by lukesyy** [comment]
还是不行，我在研究研究其他方式

**Comment by Yidadaa** [comment]
#1556 或许也是类似的问题

**Comment by lukesyy** [comment]
![15155](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/70319988/a709ebc4-8f0a-43fb-9bdb-79d2c594edd5)


解决了 docker访问不到 localhost  需要服务器的真实IP

**Comment by lukesyy** [comment]
是的

**Comment by Yidadaa** [comment]
已经补充到项目 faq

**Comment by yinm0591** [comment]
@Yidadaa 容器里的web server绑定的是ipv6地址，下面的指令查看的：
```bash
 docker exec [容器名称] netstat -n -a | grep 3000
```

docker的ipv6兼容性不佳，是不是绑定容器里的ipv4地址3000端口会更好些？

**Comment by 123aluo** [comment]
用windows10 部署的，这个也是因为代理导致的吧，有什么好的解决办法么
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/131247961/d6c52618-7929-4f83-bc3c-2d0e49cce0fd)

**Comment by yanxile** [comment]
> 用windows10 部署的，这个也是因为代理导致的吧，有什么好的解决办法么 ![image](https://user-images.githubusercontent.com/131247961/239818966-d6c52618-7929-4f83-bc3c-2d0e49cce0fd.png)

我是win10的docker desktop 用wsl部署的。试了要用局域网IP。192.168.x.x的。具体ipconfig自己看吧。

**Comment by Yidadaa** [comment]
收集至 https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2105

**Comment by willfulpeople** [comment]
{
  "error": true,
  "message": "Failed to fetch"
}

**Comment by saber09130605** [comment]
本地调试的时候一直都是
`{
  "cause": {
    "errno": -4077,
    "code": "ECONNRESET",
    "syscall": "read"
  }
}
`
，如何才能本地调试啊，想加个文件检索功能
