### ISSUE TITLE
发送按钮遮挡输入框内的文字

### ISSUE THREAD

**Issue by GOWxx** [Yidadaa/ChatGPT-Next-Web#157]
### 问题描述

如图所示，输入足够多的文字即可复现。
<img width="914" alt="image" src="https://user-images.githubusercontent.com/12870715/228519013-53ab44a5-5720-44bb-87f0-93d0efb5efaa.png">

**Comment by GOWxx** [comment]
### 可能的解决思路

将发送按钮移到输入框外部
也可以把停止按钮、重新生成按钮都放到一起。


这也可以解决 #118 的第二个问题
> 2. 对话框移动导致的另一个问题是在chatgpt生成对话时用户很难点击到stop按钮，因为按钮位置随着对话框在不断上移（甚至在跟着文字左右移动）。

**Comment by Yidadaa** [comment]
`textarea` 增加额外的 padding bottom 即可。
