### ISSUE TITLE
[Bug] 最新版本，ChatGPT还是一直显示。。。

### ISSUE THREAD

**Issue by kmeykranz** [Yidadaa/ChatGPT-Next-Web#1571]
已经更新到最新版本，发送消息后，chatgpt还是一直显示。。。

**To Reproduce**
1. 显示已经是2023.5.17最新版本
2. 已经填入api key
3. 发送消息后，chatgpt一直显示。。。

**Screenshots**
![屏幕截图 2023-05-17 163738](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/120035670/50d11afc-1478-4c63-8407-01f047cf0b98)
![屏幕截图 2023-05-17 163708](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/120035670/cfe51142-e16c-4103-8f99-b752c8ac3d1a)

**Deployment**
- [ ] Vercel部署

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by Klauxs** [comment]
+1

**Comment by cailei1** [comment]
+1

**Comment by cxwx** [comment]
+2

**Comment by Yidadaa** [comment]
提供：
- 浏览器控制台截图
- vercel log 截图

**Comment by yanCode** [comment]
chrome控制台有报错的话一些填上来。目前已知当后台报rate limit的错的时候，会一直显示。。。
```
{
    "error": {
        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-Jm7MpQ****HGfJpj on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
        "type": "requests",
        "param": null,
        "code": null
    }
}
```
这个错误的http code是 `429 Too Many Requests`
这个原因是对于报错的http code，现有logic只处理了 `401`
```
 if (res.status === 401) {
              let extraInfo = { error: undefined };
              try {
                extraInfo = await res.clone().json();
              } catch {}

              responseText += "\n\n" + Locale.Error.Unauthorized;

              if (extraInfo.error) {
                responseText += "\n\n" + prettyObject(extraInfo);
              }

              return finish();
            }
```
@Yidadaa 应该在逻辑里把这些可能的报错的http code都cover住。

**Comment by Yidadaa** [comment]
@yanCode 看起来靠谱，应该判断一下 res.status !== 200 的情况

**Comment by kevinwu06** [comment]
![屏幕截图 2023-05-17 172137](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/120035670/978aec32-bf09-4cd8-a81f-b96e37a7df9e)
![屏幕截图 2023-05-17 172617](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/120035670/8ec92c47-1232-43d5-b430-49f644d80e16)
![屏幕截图 2023-05-17 172705](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/120035670/a4c78321-5e15-4748-a003-8c3d2d78fc3b)

**Comment by lovenjz** [comment]
同样的问题

**Comment by billgeneral** [comment]
@Yidadaa 这个问题要怎样解决？
