### ISSUE TITLE
[Feature]  可以加入知识库的功能吗

### ISSUE THREAD

**Issue by skykiah** [Yidadaa/ChatGPT-Next-Web#1575]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。
可以加入知识库的功能吗，使用Embedding 接入向量数据库 做本底知识库。
**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。
https://github.com/GanymedeNil/document.ai
**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
#960
