### ISSUE TITLE
[Feature] 希望增加对话分支的功能

### ISSUE THREAD

**Issue by mushan0x0** [Yidadaa/ChatGPT-Next-Web#1577]
**你想要什么功能或者有什么建议？**
ChatGPT 和文心一言的这样的对话分支功能，可以修改这次的查询生成不同的结果，在进行多轮会话的时候可以方便回溯修改之前的查询，和查看生成的不同结果，这个非常有用

**有没有可以参考的同类竞品？**
<img width="691" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/29084441/12d5635a-65ba-41ce-ba8b-a968fb8cf129">

**其他信息**
这样对整个对话数据结构改变很大，从线性结果变成树状了，但这个功能确实很有用，别的开源项目还没见过有人做出来过

**Comment by Yidadaa** [comment]
本质上是重试功能，感觉用处不是很大
