### ISSUE TITLE
temperature in settings should range from 0 to 2

### ISSUE THREAD

**Issue by tscherrie** [Yidadaa/ChatGPT-Next-Web#159]
temperature
Defaults to 1
sampling temperature to use, between 0 and 2. 

Would you please also add top_p, logit_bias and frequency_penalty?

Amazing project, thank you!

**Comment by Yidadaa** [comment]
https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p

> top_p
number
Optional
Defaults to 1
An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
**We generally recommend altering this or temperature but not both.**

The effect of the `top_p` parameter overlaps with that of `temperature`, so only one was kept.

**Comment by Yidadaa** [comment]
The `logit_bias` seemed too complex and not user-friendly to configure, so this option was hidden.

**Comment by Yidadaa** [comment]
https://platform.openai.com/docs/api-reference/parameter-details

Frequency and presence penalties have similar effects, so only one was kept.
