### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wangpre** [Yidadaa/ChatGPT-Next-Web#1593]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
希望把对话窗口这个悬浮窗去掉，很影响体验，特别是手机上访问时，想复制对话内容老是被挡住，必须滚动一下才行。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
<img width="260" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/53291931/992ff650-a739-4fa1-9097-bab3517862c5">

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by Yidadaa** [comment]
双击消息复制。

**Comment by wangpre** [comment]
> 双击消息复制。
更多时候不需要复制全部，而是选择性复制某一段内容

**Comment by wangpre** [comment]
这个提示并不是一个很重要的东西，没必要占用那么显眼的位置

**Comment by reece00** [comment]
删除标题和提示区的油猴脚本
https://greasyfork.org/zh-CN/scripts/473634-chatgpt-next-web%E6%A8%A1%E6%9D%BF%E7%BD%91%E7%AB%99%E5%88%A0%E9%99%A4%E6%A0%87%E9%A2%98

**Comment by jaydong2016** [comment]
> 删除标题和提示区的油猴脚本
> https://greasyfork.org/zh-CN/scripts/473634-chatgpt-next-web%E6%A8%A1%E6%9D%BF%E7%BD%91%E7%AB%99%E5%88%A0%E9%99%A4%E6%A0%87%E9%A2%98

好啊

**Comment by jaydong2016** [comment]
edge 装了好像没作用，去不掉，，，

**Comment by reece00** [comment]
我试过了能用啊，你不会没匹配吧，说明不写了在设置自己添加用户匹配吗
