### ISSUE TITLE
[Bug] Docker下，访问密码验证失败。

### ISSUE THREAD

**Issue by KKKKaras** [Yidadaa/ChatGPT-Next-Web#1599]
### 反馈须知

- [✅] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
 - [✅ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
 - [✅] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。
 
### 描述问题
Docker问密码验证失败。
※面具版本之前，没有遇到这个问题

访问密码利用： **NG**
・访问密码不正确或为空，请前往[设置]页输入正确的访问密码，或者填入你自己的 OpenAI API Key。
OpenAI Key利用： **OK**

排除OpenAI Key 错误，访问密码错误，没有使用basic auth

**Docker 环境：**
NODE_VERSION=18.16.0
HOSTNAME=eff0682ca823
YARN_VERSION=1.22.19
SHLVL=1
HOME=/root
PROXY_URL=
OPENAI_API_KEY=○○○○○○○
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CODE=“**qqqqqq**”
PWD=/app
/app # 

**浏览器日志：**
page-3766a50c8971eb4c.js:1     POST https://www.◯◯◯/api/openai/v1/chat/completions 401

**docker日志：**
[OpenAI Route] params  { path: [ 'v1', 'chat', 'completions' ] }
[Auth] allowed hashed codes:  [ '220cc5c5f11d◯◯◯◯◯◯◯◯◯' ]
[Auth] got access code: **qqqqqq**
[Auth] hashed access code: 343b1c4a3ea7◯◯◯◯◯◯◯◯
[User IP]  null
[Time]  5/18/2023, 7:16:49 AM

**Comment by Yidadaa** [comment]
你可以在打 hashed codes log 的地方把 hash 之前的 code 打出来，看看是不是解析对了

**Comment by xinhaojin** [comment]
不只是docker部署有这个问题，vercel部署也一样。还有弹窗：站点要求进行身份认证。不清楚是什么原因
