### ISSUE TITLE
非常好非常优质的项目

### ISSUE THREAD

**Issue by LinFeng1987** [Yidadaa/ChatGPT-Next-Web#16]
建议加上socks5代理

**Comment by Yidadaa** [comment]
这个项目重点是用 vercel 的能力一键快速部署，没有正儿八经的后端，如果想要 api proxy 功能，可以考虑使用其他优秀的开源项目，比如 [ChatGPT-Web](https://github.com/Chanzhaoyu/chatgpt-web)，它的功能会更完善一些。
