### ISSUE TITLE
经常出现“The user aborted a request”错误

### ISSUE THREAD

**Issue by mushan0x0** [Yidadaa/ChatGPT-Next-Web#160]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/29084441/228526603-cf7b334f-f110-4373-bc81-014aea783cb6.png">

**Comment by mushan0x0** [comment]
![image](https://user-images.githubusercontent.com/29084441/228526859-c5f967ee-09b3-455c-b5b5-eeccaa50c7f2.png)

或者Failed to fetch错误

**Comment by Yidadaa** [comment]
很有可能是响应超时导致的，能否提供控制台 log 截图。

**Comment by Yidadaa** [comment]
@AprilNEA 控制台有 log 吗？以及 network 选项卡录制的网络请求。

**Comment by mushan0x0** [comment]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/29084441/228530303-c174bdbb-5bd6-4aa3-affe-ff59b2266962.png">

**Comment by mushan0x0** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/29084441/228530713-67d5ace0-da14-4933-b244-9c6b28a07e05.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/29084441/228530803-a8fac9a2-c34c-4c34-bf6e-a27db8923eb4.png">

而且容易出现401，但是我并没有开启授权码的功能

**Comment by mushan0x0** [comment]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/29084441/228531045-1d70fad4-cf23-4319-9f08-a9cc8a28955b.png">

好像出错的都是来自service worker，是pwa导致的吗

**Comment by AprilNEA** [comment]
<img width="1411" alt="2" src="https://user-images.githubusercontent.com/37977109/228532042-1f41e452-4313-4af3-8625-9cd796d6af3b.png">

Node Runtime 也是一样

**Comment by AprilNEA** [comment]
![2](https://user-images.githubusercontent.com/37977109/228532307-74df94f7-1b56-4d3b-b5c8-e046c2239bde.png)
Node Runtime也是一样
