### ISSUE TITLE
[Feature] 能否考虑加入访问速率限制功能

### ISSUE THREAD

**Issue by rggt5656** [Yidadaa/ChatGPT-Next-Web#1603]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
例如某用户或者某ip一小时提问次数达到10次后限制继续提问。

**有没有可以参考的同类竞品？**
[https://github.com/Chanzhaoyu/chatgpt-web#环境变量](https://github.com/Chanzhaoyu/chatgpt-web#环境变量) 
该项目通过环境变量可以设置限制每小时最大请求次数。
**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
此功能需要数据库，自行增加此功能。
