### ISSUE TITLE
[Feature] localStorage跨设备同步

### ISSUE THREAD

**Issue by tomcatzh** [Yidadaa/ChatGPT-Next-Web#1608]
感谢大大做出这款产品，我目前将他部署在国内的服务器上为我自己和家人提供服务。我甚至会将我的网站映射成iOS和MacOS的APP，这样做很方便！

我留意到，程序使用local storage保存数据，具体的聊天数据用"chat-next-web-store"一个JSON字段就保存完毕了，这是一个很聪明的设定，尤其适合很多本专案的使用者用Vercel部署的情况。

但是现代人很多时候都会同时使用多台设备情况，比如我坐地铁的时候使用手机向GPT请教了一些想法，当我坐下来的时候，就想在电脑前实现这些想法，如果我的电脑和手机的聊天记录可以同步，那毫无疑问是更加方便的。

我自己发现，我可以手动传递“chat-next-web-store”的内容毫无疑问是可以刷新聊天记录的。我觉得可以开发一个额外的动作，让前端可以主动保存和刷新这个Key，最理想的，甚至可以做JSON的增量同步和合并就完美了。

如果咱们的项目依然希望适配Vercel，使用类似Google Firebase，AWS App Sync的方案也许可行。也可以在前端直接操作数据库。例如直接操作AWS DynamoDB。
极限情况下，甚至也可以把整个字段保存在一个S3文件就可以了（这时Vercel的程序只需要多填写一个AWS的AKSK和S3 Bucket即可）。

如果您不打算开发这个功能，或者暂时不会把这个功能排到很高的优先级，我有兴趣Fork和开发这个功能。
但能不能给一个嵌入这个功能的代码入口的架构建议，因为即使我Fork这个项目，我也希望可以长期的跟主项目保持同步，最好是可以Pull回主项目做出贡献的。尽可能希望合并时不给贵项目带来麻烦。

请大大不吝赐教！

**Comment by Yidadaa** [comment]
关注 #920
