### ISSUE TITLE
输入框代码显示问题

### ISSUE THREAD

**Issue by jokerwen1** [Yidadaa/ChatGPT-Next-Web#1609]
**这个功能与现有的问题有关吗？**
大佬，输入框里代码能不要区分开吗？看起来很别扭

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/89336685/89989263-2e59-4715-a5cd-d4efd1f396ea)

**Comment by Yidadaa** [comment]
建议你学习一下 markdown 语法。
