### ISSUE TITLE
支持GPT-4吗？

### ISSUE THREAD

**Issue by alexyueqi** [Yidadaa/ChatGPT-Next-Web#161]
支持GPT-4吗？选择模型是GPT-4，提示稍后再试。

**Comment by Yidadaa** [comment]
请确保你有 gpt-4 api 的使用权限。

**Comment by alexyueqi** [comment]
我今天检查了一下我的权限，确实是有GPT-4的权限，因为我在本地用pycharm的gpt插件选择GPT-4是可以访问成功的。
