### ISSUE TITLE
[Bug] 余额查询时提示访问密码不正确

### ISSUE THREAD

**Issue by lurenbeia** [Yidadaa/ChatGPT-Next-Web#1611]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49217897/3e399fc8-c480-44a8-9d56-8ad7da99e45a)

如图所示，我没有设置访问密码，直接使用的api key，在我检查余额时却提示了这个，在之前的版本中是没有这个问题的。

**Comment by ClarenceDan** [comment]
这个BUG是由于查询时候当key不正确时，调用了 locales.error.unauthorized 的文本

**Comment by lurenbeia** [comment]
> 这个BUG是由于查询时当key不正确时，调用了locales.error.unauthorized的文本

没有不正确啊，我的key是在正常使用的

**Comment by lurenbeia** [comment]
另外我发现，打卡设置页就会进行提示。

**Comment by reece00** [comment]
楼上的意思是查询出错就显示这个，你自己的地址不支持这个接口就这样

**Comment by lurenbeia** [comment]
> 楼上的意思是查询出错就显示这个，你自己的地址不支持这个接口就这样

明白了，是我闹乌龙了😂，能麻烦告诉下这个接口的地址吗？我在openai上没找到

**Comment by lurenbeia** [comment]
> 

表达有误，我是想知道 dashboard/billing/usage 这个是什么接口

**Comment by Yidadaa** [comment]
api2d 不支持余额查询。
