### ISSUE TITLE
为什么用docker部署在亚马逊服务器上不能流式输出内容

### ISSUE THREAD

**Issue by truynal** [Yidadaa/ChatGPT-Next-Web#1613]
问题描述：问了问题之后停顿了很久，然后一下子全部输出出来。
环境：docker部署在亚马逊服务器上。
启动脚本：
docker run -d -p 3000:3000 \
   -e OPENAI_API_KEY="mykey" \
   yidadaa/chatgpt-next-web

**Comment by Yidadaa** [comment]
用 ngnix 了吗？

**Comment by truynal** [comment]
> 用 ngnix 了吗？

用了，要关掉Nginx吗？

**Comment by truynal** [comment]
> 用 ngnix 了吗？

可是我不想使用默认的80端口，域名配置时不能选择自定义端口

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E9%83%A8%E7%BD%B2%E7%9A%84%E7%89%88%E6%9C%AC%E6%B2%A1%E6%9C%89%E6%B5%81%E5%BC%8F%E5%93%8D%E5%BA%94
