### ISSUE TITLE
[Feature] 希望能把对话历史一键填充到预设对话里

### ISSUE THREAD

**Issue by InitialXKO** [Yidadaa/ChatGPT-Next-Web#1615]
调教GPT时有时需要多次尝试，得到满意结果时，要一条条复制到预设对话里才能保存成面具，希望能一键填充已有的对话。

**Comment by daiaji** [comment]
能让，人直接编辑对话就好了，就像官方那样。
然后再保持对话到面具。
这样模板调教效率会高很多

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/3ba90084-d4c2-402f-8068-a92b7b7d1d46)
