### ISSUE TITLE
[Bug] 单个面具导入功能不生效

### ISSUE THREAD

**Issue by T9500** [Yidadaa/ChatGPT-Next-Web#1620]
**Describe the bug**
单个面具导入功能不生效.

**To Reproduce**
1. 在编辑**单个**面具时点击“下载预设”
2. 上传该预设“.json”文件
3. 观察到面具界面无反应，导入失败

**Expected behavior**
成功导入单个面具。观察手动在“.json”文件内容最外层加上[]后导入功能生效。另外，希望在导入全部面具时不导入内部默认面具，或者下载全部面具时不下载内部默认面具，只下载自定义的面具。避免导入全部面具后还要将重复的内部默认面具一个个删掉。

**Screenshots**
界面无反应

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: 最新的 chrome
 - Version: 最新的 commit

**Additional Logs**
Add any logs about the problem here.

**Comment by yanCode** [comment]
@T9500 我检查了一下代码，目前的逻辑是现在只支持在下载时候下载多个面具，也就是json内容做为一个数组array时才会导入成功。但是直接无视了单个面具，我感觉这是一个Bug, @Yidadaa 我将为这个问题提供一个PR，允许单个面具做为json内容时也可以正常导入，你看一下是否需要merge.
