### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wwy94621** [Yidadaa/ChatGPT-Next-Web#1625]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
今天升级了系统，上一个版本是还没有面具功能的最后一版。现在系统返回答复后，没一分钟会在下面增加一个空的"{}"，查看浏览器开发工具也会看到报错。

**如何复现**
每一次消息都会有这个情况

**截图**
![ChatGPT-01](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/15881207/a218eab8-04d4-4f13-b4ca-a1d1bcc88e34)
![ChatGPT-02](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/15881207/e69151f3-648c-487f-81a1-f8bedc873048)

**一些必要的信息**
 - 系统：[macos 12/ linux ]
 - 浏览器： [比如 chrome, edge]
 - 版本： [1.9.3]
 - 部署方式：[服务器部署]

**Comment by Yidadaa** [comment]
删除旧项目，重新拉取代码部署
