### ISSUE TITLE
[Bug] 输出结果混乱

### ISSUE THREAD

**Issue by xiaoMzjm** [Yidadaa/ChatGPT-Next-Web#1627]
**Describe the bug**
输出内容混乱

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16941859/cfb773a9-6d52-48ad-afb6-70f832079fab)

**To Reproduce**
1. 输入“java ^ 运算" 时出现的，但无法必现

**Expected behavior**
避免输出内容混乱

**Desktop (please complete the following information):**
 - OS [Windows 10]
 - Browser [Chrome 112.0.5615.138]
 - Version [20230519]

**Comment by Yidadaa** [comment]
用的第三方 api？

**Comment by xiaoMzjm** [comment]
您发给我的信件已经收到，谢谢！
       
              张佳铭
