### ISSUE TITLE
[Bug] no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by ZhiXuanWang** [Yidadaa/ChatGPT-Next-Web#1628]
root@onecloud:~# docker pull yidadaa/chatgpt-next-web
Using default tag: latest
latest: Pulling from yidadaa/chatgpt-next-web
no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by Yidadaa** [comment]
暂不支持 v7：
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/8d7f3bd2159682a2a0a4fd2ca185590e3438e3b5/.github/workflows/docker.yml#L46
