### ISSUE TITLE
[Feature] 模型选择需求

### ISSUE THREAD

**Issue by Dozengame** [Yidadaa/ChatGPT-Next-Web#1634]
chatgpt ios客户端发布后似乎增加了2个针对移动设备的模型

模型名称
ext-davinci-002-render-sha-mobile
gpt-4-mobile

似乎速度飞快，是否能加入到模型选择当中

参考来源：
https://twitter.com/wong2_x/status/1659446644570750978
https://www.reddit.com/r/ChatGPT/comments/13lp72x/you_can_use_chatgpt_ios_models_on_desktop/

**Comment by Yidadaa** [comment]
马上安排

**Comment by Yidadaa** [comment]
<img width="728" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/5be8e997-af36-4636-8a5d-fdbb44357857">

**Comment by Yidadaa** [comment]
应该是寄了

**Comment by Dozengame** [comment]
汗。。。那没办法了

**Comment by Yidadaa** [comment]
确认了一下，应该是只支持 accessToken 方式访问
