### ISSUE TITLE
部署的时候自行设置 BASE_URL 就行

### ISSUE THREAD

**Issue by mmwong1984** [Yidadaa/ChatGPT-Next-Web#1640]
部署的时候自行设置 BASE_URL 就行

_Originally posted by @Yidadaa in https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1638#issuecomment-1554662607_
            
因爲是必須填寫API碼，但是這個不要使用填寫API就可以使用的，因此才找你的

**Comment by mmwong1984** [comment]
確定能使用的

**Comment by Yidadaa** [comment]
更新代码即可，现已支持
