### ISSUE TITLE
面具页面在手机版显示不全，也无法滚动，部分面具呈灰色，但也点开[Bug] 

### ISSUE THREAD

**Issue by KennyLeung** [Yidadaa/ChatGPT-Next-Web#1642]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
桌面版的面具页面显示正常，但手机版显示不全，也无法滚动，部分面具呈灰色，不过也能点开使用。就是让人费解，以为不可用。由于不能滚动，所以只能点选能看到的面具。

**如何复现**
使用手机打开，或者桌面浏览器进入开发者页面，切换到手机模式，再点开面具页面。

**截图**
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/4188953/f7d18bb3-0a7e-4bfc-ba41-0c0eb2c593de)

**一些必要的信息**
 - 系统：[比如 windows 10/  android 13]
 - 浏览器： [比如 chrome, firefox]
 - 版本： [20230518]
 - 部署方式：[docker部署]

**Comment by Yidadaa** [comment]
这个页面的面具只是设计如此，要使用其他面具，点开“查看全部”
