### ISSUE TITLE
可以自己在项目中加一些html和js链接吗？

### ISSUE THREAD

**Issue by junyangfan** [Yidadaa/ChatGPT-Next-Web#1643]
可以自己在项目中加一些html和js链接吗？
建议自己可配置，比如我想加一个js脚本来统计访问量等
```
<script src="xxx"></script>
```

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/e5329dc28a1958505dfcabe500ee6ee177faeb74/app/layout.tsx#L37
