### ISSUE TITLE
[Feature] 会支持官方的插件吗

### ISSUE THREAD

**Issue by sdcxzx-tester** [Yidadaa/ChatGPT-Next-Web#1647]
**这个功能与现有的问题有关吗？**
官方已经支持插件,和浏览器模式,会跟进支持吗

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
尽量支持
