### ISSUE TITLE
[Bug] Code: UND_ERR_CONNECT_TIMEOUT

### ISSUE THREAD

**Issue by livejq** [Yidadaa/ChatGPT-Next-Web#1650]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
宿主机能正常访问 api.openai.com, 进入容器里面也可以正常Ping通，但是网页ChatGPT就是反馈超时

**如何复现**
我是通过路由器将部署的那台服务器的IP地址的所有访问目的地都路由到美国隧道出去访问的。一开始没有什么问题，但今天那条隧道突然断开了，我就改成了其它隧道，然后GPT就再也访问不了了，一直报超时。

**截图**

![20230520_16_23_17](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/42449253/be8aa331-6124-4ef4-899a-8ba787af841e)

**一些必要的信息**
 - 系统：[Windows 10]
 - 浏览器： [Chrome]
 - 版本： [版本 113.0.5672.127（正式版本） （64 位）]
 - 部署方式：[在 CentOS 7.9 上通过 docker 部署]

**Comment by Yidadaa** [comment]
尝试设置 PROXY_URL
