### ISSUE TITLE
[Bug]默认语言没有随浏览器语言变化

### ISSUE THREAD

**Issue by kylyzhh** [Yidadaa/ChatGPT-Next-Web#1651]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用vercel部署的时候，浏览器进行访问，默认语言没有随浏览器语言变化，始终显示英语

**如何复现**
vercel部署新版本后浏览器访问

**截图**
<img width="1303" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/53763846/fd80ae05-e220-4a21-9a82-b620e70c3d69">
<img width="1241" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/53763846/eb82679c-cf69-4775-8414-5ea7b7ce4218">
<img width="1455" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/53763846/7ef35eb1-529c-463b-b531-faab17439ba1">

**一些必要的信息**
 - 系统：macos 13/ android 13
 - 浏览器：chrome, safari
 - 版本：20230520
 - 部署方式：vercel

**Comment by ClarenceDan** [comment]
目前layout里写死了en，需要自动检测会比较麻烦，需要前端将网页浏览器环境回传到服务端，然后再由edge function来重新渲染，之前打算改改，后来发现能力有限放弃了（又不是不能用.jpg)
