### ISSUE TITLE
[Bug] 自动补全后直接按回车键，会选到错误的prompt

### ISSUE THREAD

**Issue by haochn** [Yidadaa/ChatGPT-Next-Web#1662]
**复现过程：**
 - 输入框输入 `/xx`
 - 按 enter 键
 - 自动补全"我希望你假定自己是雅思写作考官..."

**Screenshot**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/36954660/b52410eb-5041-40a8-8d87-d01735e21a4d)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/36954660/5d3cb8ed-15da-4052-acbd-f10be9eda5a8)

**Deployment**
   Vercel

**Desktop (please complete the following information):**
 - Browser [EDGE(chrome)]

**Comment by Yidadaa** [comment]
无法复现

**Comment by yanCode** [comment]
I can reproduce this bug, i am going to fix it.

**Comment by yanCode** [comment]
重现这个Bug的关键是，先输入一个'/', 这时看清最底下的prompt, (也就是index为0的) 这时不要做任何上下移动prompt的操作，而是直接在`/`后输一些查询内容，比如javascript. 这时会看到关于javascript这一条prompt会在最底部，且在UI上为选中状态，这时回车，你会发现input textarea里面的是第一次出现在最底下的prompt, 而不是关于javascript这一条
