### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ldboyghg** [Yidadaa/ChatGPT-Next-Web#1664]
通过自己的域名  ,页不能无墙访问了， 之前是可以的，请问怎么处理呢?

**Comment by ldboyghg** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19562731/cfb1a723-82dc-4ca4-a628-cd663aff5ec4)

**Comment by Yidadaa** [comment]
域名寄了，换
