### ISSUE TITLE
[Bug] 余额查询接口403

### ISSUE THREAD

**Issue by hnsongbiao** [Yidadaa/ChatGPT-Next-Web#1667]
请求地址
/api/openai/dashboard/billing/usage?start_date=2023-05-01&end_date=2023-05-22

返回

{"object":"error","message":"Only /v1/chat/completions && /v1/embeddings allowed now , your path {/dashboard/billing/usage}","code":40301}

docker部署配置使用第三方的代理接口
sudo docker run -d -p 80:3000 \
   -e OPENAI_API_KEY="fk197998-xxxxxxxxxx" \
   -e CODE="" \
   -e BASE_URL="https://openai.api2d.net" \

**Comment by Yidadaa** [comment]
第三方不支持这个接口

**Comment by hnsongbiao** [comment]
先前还是可以查询的

**Comment by Yidadaa** [comment]
报错里不是写的很清楚了？api2d 明确告诉你只支持两个接口，其他的都不支持。
