### ISSUE TITLE
可以通过前台设置或者代码里面指定系统角色吗？

### ISSUE THREAD

**Issue by tiwentichat** [Yidadaa/ChatGPT-Next-Web#167]
我尝试了修改里面几个role : "assistant"改成lawyer，doctor好像不生效 - -！
不知道有这种地方可以修改嘛

代码渣渣瑟瑟发抖求大佬看我

**Comment by Yidadaa** [comment]
请仔细阅读 openai 的 api 文档，和 role 字段没有关系。

https://platform.openai.com/docs/guides/chat

**Comment by Yidadaa** [comment]
你可以等待 system prompt 功能的加入，将于近期更新。

**Comment by tiwentichat** [comment]
好的，期待！感谢大佬！
