### ISSUE TITLE
[Bug] can't set default language

### ISSUE THREAD

**Issue by chaveamin** [Yidadaa/ChatGPT-Next-Web#1671]
**Describe the bug**
I've forked the repo to mine, added new language(Persian) and made it default. it can be changed in settings but it's not persian by default

**To Reproduce**
This is my language config file from local folder:
```
import CN from "./cn";
import FA from "./fa"; // My newly added language
import EN from "./en";
import TW from "./tw";
import FR from "./fr";
import ES from "./es";
import IT from "./it";
import TR from "./tr";
import JP from "./jp";
import DE from "./de";
import VI from "./vi";
import RU from "./ru";
import CS from "./cs";
import KO from "./ko";
import { merge } from "../utils/merge";

export type { LocaleType, RequiredLocaleType } from "./cn";

export const AllLangs = [
  "fa",
  "en",
  "cn",
  "tw",
  "fr",
  "es",
  "it",
  "tr",
  "jp",
  "de",
  "vi",
  "ru",
  "cs",
  "ko",
] as const;
export type Lang = (typeof AllLangs)[number];

export const ALL_LANG_OPTIONS: Record<Lang, string> = {
  fa: "فارسی",
  cn: "简体中文",
  en: "English",
  tw: "繁體中文",
  fr: "Français",
  es: "Español",
  it: "Italiano",
  tr: "Türkçe",
  jp: "日本語",
  de: "Deutsch",
  vi: "Tiếng Việt",
  ru: "Русский",
  cs: "Čeština",
  ko: "한국어",
};

const LANG_KEY = "lang";
const DEFAULT_LANG = "fa";

function getItem(key: string) {
  try {
    return localStorage.getItem(key);
  } catch {
    return null;
  }
}

function setItem(key: string, value: string) {
  try {
    localStorage.setItem(key, value);
  } catch {}
}

function getLanguage() {
  try {
    return navigator.language.toLowerCase();
  } catch {
    console.log("[Lang] failed to detect user lang.");
    return DEFAULT_LANG;
  }
}

export function getLang(): Lang {
  const savedLang = getItem(LANG_KEY);

  if (AllLangs.includes((savedLang ?? "") as Lang)) {
    return savedLang as Lang;
  }

  const lang = getLanguage();

  for (const option of AllLangs) {
    if (lang.includes(option)) {
      return option;
    }
  }

  return DEFAULT_LANG;
}

export function changeLang(lang: Lang) {
  setItem(LANG_KEY, lang);
  location.reload();
}

const fallbackLang = FA;
const targetLang = {
  fa: FA,
  en: EN,
  cn: CN,
  tw: TW,
  fr: FR,
  es: ES,
  it: IT,
  tr: TR,
  jp: JP,
  de: DE,
  vi: VI,
  ru: RU,
  cs: CS,
  ko: KO,
}[getLang()] as typeof CN;

// if target lang missing some fields, it will use fallback lang string
merge(fallbackLang, targetLang);

export default fallbackLang as typeof CN;
```

**Expected behavior**
All translated strings must be in Persian language
https://aminai-taupe.vercel.app/

**Screenshots**
![1](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/78597787/b62bd668-2b76-47b6-9cb0-9b4b6668475d)

**Deployment**
- [ ] Vercel

**Desktop:**
 - OS: [e.g. Windows]
 - Browser [chrome]
 - Version [22]

**Smartphone:**
 - Device: [iPhone6]

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
Open chrome dev tools, and type `navigator.language.toLowerCase()` in console, see what's the output?

`DEFAULT_LANG` only works when it can not detect user lang, or it will use the result of `navigator` api as default lang.

**Comment by Yidadaa** [comment]
If you wanna disable this feature, modify the logic of `getLanguage`, just `return DEFAULT_LANG`.

**Comment by chaveamin** [comment]
> Open chrome dev tools, and type `navigator.language.toLowerCase()` in console, see what's the output?
> 
> `DEFAULT_LANG` only works when it can not detect user lang, or it will use the result of `navigator` api as default lang.

The output is `'en-us'`

**Comment by Yidadaa** [comment]
That is expected behavior. You need to change the operating system language to Persian so that the browser can recognize the correct language.

**Comment by Yidadaa** [comment]
> If you wanna disable this feature, modify the logic of `getLanguage`, just `return DEFAULT_LANG`.

Or use this.

**Comment by chaveamin** [comment]
> If you wanna disable this feature, modify the logic of `getLanguage`, just `return DEFAULT_LANG`.

It solved the problem, Thanks
