### ISSUE TITLE
[Bug] Cannot disable Vercel CI/CD pipelines in GitLab fork

### ISSUE THREAD

**Issue by abicorios** [Yidadaa/ChatGPT-Next-Web#1676]
**Describe the bug**
I copied source code to GitLab. I try disable Vercel CI/CD pipelines. And I don't know how to disable it. I tried GitLab settings (repository Settings->CI/CD->Runners->Shared runners->disable, repository Settings->General->Visibility, project features, permissions->Repository->CI/CD->disable), I tried remove files `vercel.json` and `.gitpod.yml`. But I cannot kill these pipelines, they run on every commit. What the magic? 😭

**To Reproduce**
1. Send files of repository as initial commit to GitLab
2. Create some branch
3. Send some commit
4. I see CI/CD Vercel pipeline, and cannot disable it

**Expected behavior**
I hope, it is possible to fully disable Vercel CI/CD pipelines for fork of the project to GitLab.

**Comment by Yidadaa** [comment]
This is strange, maybe you can try to re-import it and see what will happen?

**Comment by abicorios** [comment]
I understand. GitLab pipelines were, because another person in our company have done some settings by the vercel.com interface, to atach the vercel pipelines to the repository.
