### ISSUE TITLE
[Feature] 为聊天页面的辅助按钮增加浮动文本 Add floating text to the auxiliary button of the chat page

### ISSUE THREAD

**Issue by HenMie** [Yidadaa/ChatGPT-Next-Web#1680]
**你想要什么功能或者有什么建议？**
在按钮上增加提示文本，可以让用户更清晰地知道这个按钮的功能。
Add descriptive text on the button to provide users with a clearer understanding of its functionality.

效果类似这样：
![image.png](https://s2.loli.net/2023/05/22/RL2cmNseOgFZKBl.png)
![image.png](https://s2.loli.net/2023/05/22/gKuEpY6N9HfoiMR.png)

**Comment by Jialinvip** [comment]
是的，其它按钮也建议加上提示文本，方便提前知道是什么按钮。

**Comment by Yidadaa** [comment]
点了就知道是干啥的了，之后统一加，现在懒得加翻译文本
