### ISSUE TITLE
[Bug] 导出图片渲染错误 Export image rendering error

### ISSUE THREAD

**Issue by HenMie** [Yidadaa/ChatGPT-Next-Web#1681]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
导出的设置页面显示正常，生成的图片渲染错误。

**如何复现**
正常流程生成图片即出现错误，目前100%复现。

**截图**
导出的设置页面：
![image.png](https://s2.loli.net/2023/05/22/evbut4T1qor6UwE.png)
![image.png](https://s2.loli.net/2023/05/22/BeHYyMxl8FhOUW2.png)

生成的图片
电脑端
![新的聊天.png](https://s2.loli.net/2023/05/22/zZ4t8kMgKTAHWoP.png)
手机端
![下载.png](https://s2.loli.net/2023/05/22/IWGVJuYLXNC5a3U.png)

**一些必要的信息**
电脑：
 - 系统：Ubuntu 22.04.2 LTS
 - 浏览器：Chrome 113.0.5672.126（正式版本） （64 位）

手机：
 - 系统：Android 12, MagicOS 7.0.0.135
 - 浏览器：狐猴浏览器 2.4.0.003

服务端：
 - 版本： 20230521
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
bot 头像是 svg 图片，暂时不支持 svg 图片的导出
