### ISSUE TITLE
疑问：如何使用 gpt-4-mobile 和 text-davinci-002-render-sha-mobile

### ISSUE THREAD

**Issue by zengboin** [Yidadaa/ChatGPT-Next-Web#1683]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用这两个模型后聊天报错：
```json
{
  "error": {
    "message": "The model `gpt-4-mobile` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```
```json
{
  "error": {
    "message": "The model `text-davinci-002-render-sha-mobile` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```
```
**如何复现**
聊天设置里面选择 `gpt-4-mobile` 或 `text-davinci-002-render-sha-mobile`

**截图**
https://github.com/Yidadaa/ChatGPT-Next-Web/assets/123235746/1cb0c586-7211-441a-baa4-9e9d7f169290

**一些必要的信息**
 - 系统：[MacOS]
 - 浏览器： [Edge]
 - 版本： [20230521]
 - 部署方式：[Docker]

**Comment by Yidadaa** [comment]
暂时不可用
