### ISSUE TITLE
[Bug]桌面图标图层问题

### ISSUE THREAD

**Issue by zui-lang** [Yidadaa/ChatGPT-Next-Web#1684]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
网页图标图层可能有bug，在ios端添加桌面中返回动画可以看出

**如何复现**
设备：iPhonexr，系统版本16.1.2，打开应用返回桌面即可出现
设备：ipadpro2018，系统15.6RC，在竖屏状态下打开会出现，横屏打开下可能因为遮挡不明显

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/77880495/c67b79b2-3b1c-4978-825f-914a6f2255dc)
这是iPhone XR的GIF动画
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/77880495/c8459b74-325a-4b41-b2b6-ed782b57b852)
这个是其中某一帧画面，图层bug用蓝色圈出
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/77880495/ff21007c-89e5-457c-bc55-04cb0a91062e)
这个是ipadpro在竖屏状态下的截图
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/77880495/1bf2db25-2b17-4259-8ff1-55f1ad4b617c)
这个是ipadpro在横屏下的截图
**一些必要的信息**
 - 系统：ios 16，ios 15
 - 浏览器：safari
 - 版本： deeeebc
 - 部署方式：vercel

**Comment by ClarenceDan** [comment]
这种细致的问题都被挖出来了,牛逼

**Comment by Yidadaa** [comment]
这看起来是 iOS 系统的 bug

**Comment by zui-lang** [comment]
之前都是在ipad上横屏使用一直没发现，今天在手机上添加一用就感觉动画怪怪的，应该是分辨率的问题，xr分辨率太低，所以后面的那个图层突出就特别明显> 这种细致的问题都被挖出来了,牛逼

**Comment by Yidadaa** [comment]
pwa 应用没有途径能控制桌面图标的蒙层样式，所以这大概率是 iOS 的 bug。

**Comment by zui-lang** [comment]
> pwa 应用没有途径能控制桌面图标的蒙层样式，所以这大概率是 iOS 的 bug。

我手机上有几个pwa应用都没有这个问题

**Comment by zui-lang** [comment]
> pwa 应用没有途径能控制桌面图标的蒙层样式，所以这大概率是 iOS 的 bug。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/77880495/ff741450-7dde-4771-b85e-cdf93352a0b2)
这四个都是pwa应用，使用了0.5倍速慢放
