### ISSUE TITLE
[Feature] “上下文清除”功能建议

### ISSUE THREAD

**Issue by JasonLeeForOnly** [Yidadaa/ChatGPT-Next-Web#1685]
**这个功能与现有的问题有关吗？**
”上下文清除”功能

**你想要什么功能或者有什么建议？**
需要一个清屏的效果，在完成一次完整的交互后可以清除或隐藏之前的会话内容，用以保持对当前会话的专注。
建议在点击”上下文清除”后，应该将之前的会话内容收起，更加符合实际的操作逻辑。

**有没有可以参考的同类竞品？**
![5ee3a6d7-7761-4935-b0d2-578b5df8d8cb](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/47520063/d19fa778-22c6-4eda-9a34-30096c5c53fd)

类似poe在点击Clear会话之后，会将之前的会话顶到上一页，保持接下来会话页面纯净。

**其他信息**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/47520063/a22f6589-c61d-4a3f-b88a-9586378cfc0a)

现有的“清除记忆”也无法做到清屏的效果了，我记得之前应该是可以的。

**Comment by JasonLeeForOnly** [comment]
poe中，向上滑动还是可以继续查看到之前的会话内容的。对应到chatgpt next web项目中，点击恢复上下文应该可以再把之前的会话内容陈陈列回来。

**Comment by Yidadaa** [comment]
看起来是无关痛痒的功能，但是实现起来会比较麻烦。

**Comment by JasonLeeForOnly** [comment]
> 看起来是无关痛痒的功能，但是实现起来会比较麻烦。

恩，结构上改动比较大，确实没那么好实现。不过为什么现在清除记忆也不清空会话内容了？

**Comment by Yidadaa** [comment]
因为清空上下文已经相当于清空了会话内容，只不过还能看到原来的会话记录而已。

清空记忆是用来解决记忆混乱导致的“幻觉”问题。

如果真的想清空对话，直接新建一个对话不就行了。

**Comment by sailxjx** [comment]
这功能感觉现在有 bug，点击清空上下文，再点击恢复上下文，之后发送的所有消息，都只会带最后一条消息了，所有新增的历史消息都不起作用

**Comment by sailxjx** [comment]
我预期的结果是只清空压缩过的历史摘要，因为如果历史消息出现幻觉，大不了删掉这几条消息，如果想清空全部上下文，可以直接新建对话，只有清空历史摘要是现在web上没有的功能

**Comment by Yidadaa** [comment]
@sailxjx 清空历史摘要在对话设置窗口底部的“清除记忆”。

**Comment by sailxjx** [comment]
恢复上下文那个键不知道有啥作用，点了仍然只会发送最后一条消息

**Comment by Yidadaa** [comment]
@sailxjx 应该是 bug。

**Comment by sailxjx** [comment]
点了“清除记忆”也会有同样的问题，就是发送上一条历史消息了，即使把历史消息数拉到很高

**Comment by icekree** [comment]
这个清楚记忆和清楚上下文应该分开
清除上下文：重新会话（保留前置）但不清空记录
清除记忆：清空记录

**Comment by Yidadaa** [comment]
清除记忆是指清空“历史摘要”。

**Comment by sailxjx** [comment]
不如直接改成「清空历史摘要」更容易理解，然后修复那个bug，应该就满足很多人的需求了。

**Comment by sailxjx** [comment]
另外在问一个问题，历史摘要的生成逻辑是怎样的，每次都取最后N条记录让chatgpt总结，还是每次取历史摘要+N条记录给chatgpt总结。
如果清空历史摘要，下次回复之后，重新生成摘要是基于什么记录

**Comment by Mydong** [comment]
> 1. 只有当未记忆内容大于设置的阈值时，才会触发摘要；
> 2. 基于最近总字数不大于阈值的消息来生成新的摘要，更早的消息会被直接遗弃。

`基于最近总字数不大于阈值的消息来生成新的摘要，更早的消息会被直接遗弃。`

可能就是更早的消息会被直接抛这个点，容易造成混乱；
常规使用的环境是：
最早（也就是开始的提问）是核心的需求，但可能最早的需求，gpt回复出来的答案，达不到满意的程度，因此，不断调试优化。最终达到一个可能满意的结果。然后，在这条下继续问相同的问题；
由于更早的消息是核心需求，抛弃后，后面总结的信息就容易偏离主题；
现在我的解决方法就是：

将最早的提问，以及期间认为不错的回复和提问，都复制粘贴到面具中，保留这些信息。会好点，不至于太过于偏离了原主题。
同时，牵扯到这个需求https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1615  😂

**Comment by Yidadaa** [comment]
Pin 一个 message 的功能是很有必要的，我最近调试 prompt 的时候也遇到了这个问题，我在思考怎么做这个交互。

**Comment by Mydong** [comment]
> Pin 一个 message 的功能是很有必要的，我最近调试 prompt 的时候也遇到了这个问题，我在思考怎么做这个交互。

前面我有一个issues中提到了一个项目，https://github.com/ourongxing/chatgpt-vercel
这个它是在头上上，做了pin，给回复消息的头像加了一个🔒

随便截图的两个
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/c5d05e3b-a43f-4fda-b6aa-946adbce6c5b)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/faeff41f-04f3-4907-b652-329b49af096c)

**Comment by Yidadaa** [comment]
Pin message 功能合并到 #1615 做
