### ISSUE TITLE
[Bug] Rate limit

### ISSUE THREAD

**Issue by TuShengTao** [Yidadaa/ChatGPT-Next-Web#1696]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
openai api Rate limit 问题，目前部署给其他人使用，无法满足多人同时使用需求，有时候会一直等待接口响应。

备注：目前自己思路是加一些 BASE_URL 和API_KEY的轮询逻辑，代理api使用阿里云函数计算成本忽略不计。

**如何复现**
ApiFox做一个接口请求并发测试就能复现
post请求接口：https://xxx.com/api/openai/v1/chat/completions

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/50161350/b56a9256-23f7-4eb1-b3bf-9694c3118d06)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器：  chrome
 - 版本： 20230520
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
两行代码就能实现轮询，我故意没加这个逻辑，违反了 openai 的滥用政策。

**Comment by Yidadaa** [comment]
如果你感兴趣，可以去我公众号《我的代码会好吗》查看
