### ISSUE TITLE
[Bug] 等待接口响应时，强制终止，可能导致无法重试和删除

### ISSUE THREAD

**Issue by StereoApp** [Yidadaa/ChatGPT-Next-Web#1697]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
如果遇到接口相应较慢的时候（GPT4更常见），接口可能会一直请求中，这时候一般会选择停止当前请求，马上重试下，就会比较快，但是此时如果点击聊天框上方的工具栏中的第一个暂停图标那个按钮就会导致这条对话，无法重试，无法删除，一直在上下文中。
**如何复现**
在openai接口还没有相应的时候（显示。。。的时候），点击工具栏中的暂停图标那个按钮
**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![Snipaste_2023-05-23_10-28-21.png](https://s2.loli.net/2023/05/23/qVrBuPX5ZWNc6UM.png)

**一些必要的信息**
 - 系统：[windows 10]
 - 浏览器： [chrome ver.113]
 - 版本： [ 2.6 ]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
不用管它，过段时间刷新页面，这条信息就能被删除了
