### ISSUE TITLE
[Feature] 希望增加一个对接midjourney的接口

### ISSUE THREAD

**Issue by darkelfzdy** [Yidadaa/ChatGPT-Next-Web#1698]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
希望利用这个项目对接上midjourney，https://github.com/yokonsan/midjourney-api

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
社区已经开源接入 Mid journey 版本的代码库，欢迎 star：https://github.com/Zo3i/chatgptWithMidjourney

**Comment by Licoy** [comment]
@darkelfzdy 这里你可以使用自建midjourney api服务给ChatGPT-Next-Web接入了midjourney，开源地址：https://github.com/Licoy/ChatGPT-Midjourney

**Comment by zhoujingryan** [comment]
> 社区已经开源接入 Mid journey 版本的代码库，欢迎 star：https://github.com/Zo3i/chatgptWithMidjourney

能否集成到这个项目中呢 
感觉要部署多个很麻烦=。=
