### ISSUE TITLE
bug:手机上回复的时候聊天内容到屏幕下边的时候，画面不会跟过去。

### ISSUE THREAD

**Issue by JeazW** [Yidadaa/ChatGPT-Next-Web#17]
会被输入框盖住
![image](https://user-images.githubusercontent.com/75829171/227560872-7e98b2b8-859a-43de-93e7-aecfd3aa0769.png)

**Comment by Yidadaa** [comment]
手机上的滚动体验不太好，默认在 iOS 设备上禁用了自动滚动。同时在 pc 上使用时，如果鼠标放到了聊天界面，同样也不会自动滚动。

**Comment by JeazW** [comment]
好的吧，原来早有考虑。这么晚还回issue，大佬辛苦。
