### ISSUE TITLE
点击重试后自动将聊天窗口滚动到最底部 / automatically scroll chat window to the bottom after clicking "Retry"

### ISSUE THREAD

**Issue by zilonghe** [Yidadaa/ChatGPT-Next-Web#170]
我在使用你们的产品时，会遇到网络不稳定导致消息发送失败的情况。这时，我会点击“重试”按钮，但是聊天窗口并不会自动滚动到最底部，导致我认为点击没有起到效果。

因此，建议添加一个功能，使得在点击重试按钮后自动将聊天窗口滚动到最底部，展示最新消息。

谢谢！

I've experienced network instability while using your product, which leads to message sending failure. When I click the "Retry" button, the chat window doesn't automatically scroll to the bottom, which makes me think that clicking the button didn't work.

Therefore, I suggest adding a feature that automatically scrolls the chat window to the bottom after clicking "Retry," showing the latest messages.

Thank you!

**Comment by Yidadaa** [comment]
done.
