### ISSUE TITLE
[Bug]  当直接使用docker进行升级的时候报错: socket hang up

### ISSUE THREAD

**Issue by 520hacker** [Yidadaa/ChatGPT-Next-Web#1702]
**Describe the bug**
当直接使用docker进行升级的时候报错: socket hang up

**To Reproduce**
1. update new version
sudo docker pull yidadaa/chatgpt-next-web:latest
latest: Pulling from yidadaa/chatgpt-next-web
Digest: sha256:c276366858214296fc50166539a2c0840f8f31b173958256a81c93e676a8a74f
Status: Image is up to date for yidadaa/chatgpt-next-web:latest
docker.io/yidadaa/chatgpt-next-web:latest
2. 启动新的node之后报错 socket hang up
3. 页面返回 Internal Server Error
4. 环境变量未变

**Expected behavior**
猜测是不是缺了环境变量？是在新版本迭代的时候出现了新的环境变量？

**Screenshots**
Error:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1049658/08fcd89d-98da-4007-9dfa-b4ab7a266074)
环境变量:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1049658/20b85bd2-aa0f-490c-96e0-2a660a7c33d2)
回滚之后一切正常
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1049658/7e713b19-e296-4955-b5a7-7f41885438d5)

**Deployment**
-  Docker

**Desktop (please complete the following information):**
 - OS: 群晖
 - Browser chrome
 - Version (sha256:c276366858214296fc50166539a2c0840f8f31b173958256a81c93e676a8a74f)

**Comment by Yidadaa** [comment]
试试这个：https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1556#issuecomment-1558719261

**Comment by 520hacker** [comment]
> 试试这个：[#1556 (comment)](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1556#issuecomment-1558719261)

感谢建议，不过no lucky.

 在设置了HOSTNAE的情况下依然是这个错误

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1049658/afa9a953-51e1-4d5a-9016-31e87be2d4c1)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1049658/94f37a16-aa3c-44d2-8de3-4a50ac0a3386)

**Comment by gtoxlili** [comment]
你 DockerFile 不是最新的吧？   localnet 127.0.0.0/255.0.0.0 还得把这条加进去

**Comment by 520hacker** [comment]
这个ticket可以关闭了。

最终我是放弃了继承原有的配置，从新从image创建容器搞定了。
可能的问题来自于原本我是使用的群晖的更新方法，即复制配置来创建新的容器。这个中间应该是什么地方是存在差异的。

sorry for waste your time.
