### ISSUE TITLE
docker 本地部署[Bug] 

### ISSUE THREAD

**Issue by xiaozhanghui** [Yidadaa/ChatGPT-Next-Web#1705]
头一两句话正常响应，再问就报错
{
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 4183a44a5c1752b1d21ea741f9ad286e in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

**Comment by Yidadaa** [comment]
openai 服务器炸了。
