### ISSUE TITLE
[Bug] The server had an error processing your request

### ISSUE THREAD

**Issue by GUOhk36** [Yidadaa/ChatGPT-Next-Web#1707]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
问出问题后，GPT的回答有较大的几率出现如下error
```
{
  "error": {
    "message": "`The server had an error processing your request`. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID b7fa0bf053a69b5d4bf78441b13e9fa5 in your email.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
```

**如何复现**
正常的问出问题，就有几率复现

**截图**
![2023-05-23_192351](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/128574267/be0ac71d-5dde-49ea-b5ca-5cdd1f1d95d9)

**一些必要的信息**
 - 系统：[比如 windows 10]
 - 浏览器： [比如 chrome]
 - 版本： [0522]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
openai 服务器不稳定。

**Comment by kelekekou8** [comment]
me too
