### ISSUE TITLE
[Bug] Nginx作为ssl和反代服务器，加上proxy_buffering依旧没有流式响应

### ISSUE THREAD

**Issue by LiberatorHg** [Yidadaa/ChatGPT-Next-Web#1709]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
以下是我的配置文件，之所以用nginx是为了把二级域名代理到该项目上

**如何复现**
试了重新部署gpt，和重新部署nginx都不好使，求指教谢谢

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/52238701/c85eea4d-7512-447e-958d-867c89b7a48d)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/52238701/e4c89806-819d-488c-bef1-c02066ff4918)

**一些必要的信息**
 - 系统：[windows 11]
 - 浏览器： [edge，chrome]
 - 版本： [20230521]
 - 部署方式：[docker部署在tx云上，nginx一个容器，gpt一个容器]

**Comment by yinm0591** [comment]
If you use nginx reverse proxy, you need to add the following code to the configuration file:
```
# No caching, support streaming output
proxy_cache off;  # Turn off caching
proxy_buffering off;  # Turn off proxy buffering
chunked_transfer_encoding on;  # Turn on chunked transfer encoding
tcp_nopush on;  # Turn on TCP NOPUSH option, disable Nagle algorithm
tcp_nodelay on;  # Turn on TCP NODELAY option, disable delay ACK algorithm
keepalive_timeout 300;  # Set keep-alive timeout to 65 seconds
```
Reference URL: https://github.com/Yidadaa/ChatGPT-Next-Web/blob/4c9e4e507cef6cfca873077b1c751982382e80bb/docs/faq-en.md

**Comment by LiberatorHg** [comment]
重装了nginx和本项目，莫名其妙好了，之前试了好多次
