### ISSUE TITLE
[Bug] Docker指定hostname无法包含大写字母

### ISSUE THREAD

**Issue by Suyknow** [Yidadaa/ChatGPT-Next-Web#1710]
在上一版本更新后，就遇到指定hostname无法包含大写字母的问题
以下是我用于创建docker的命令：

docker run -itd --name=ChatGPT-Next --hostname=ChatGPT-Next --restart=unless-stopped \
-p [my_port]:3000 \
-e OPENAI_API_KEY="[my_apikey]" \
-e CODE="[my_code]" \
yidadaa/chatgpt-next-web:latest

之前几个版本都正常使用，上一个版本开始，用以上命令创建docker，容器内的日志会报以下错误：

Invariant: failed to start render worker Error: getaddrinfo ENOTFOUND ChatGPT-Next
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ChatGPT-Next'
}

并且检查容器会发现，并没有给当前容器分配ip地址和端口。

但是，一旦把上述的Docker命令中 --hostname=ChatGPT-Next这个参数删去，就一切正常了。

并且经过几次尝试发现， --hostname=ChatGPT-Next会报错，但是--hostname=chatgpt-next就没问题，其他任何包含大写字母的--hostname也都不行。

**Comment by Yidadaa** [comment]
我寻思这应该和这个项目没什么关系

**Comment by Suyknow** [comment]
> 这个问题就很怪，最近完全没动过 dockerfile，而且第一次听说 hostname 大小写会影响部署

我又试了一遍，这个hostname的问题只出现在Docker镜像v2.5和目前的v2.6版本，同样的部署命令，给到v2.4的镜像就没问题

**Comment by ZJUprince** [comment]
同样有该问题

**Comment by Yidadaa** [comment]
有可能是升级 nextjs 版本导致的该问题，不过看起来并不是什么致命问题。

具体的原因不好排查，应该与 docker 没关系，先用小些 hostname 凑合用吧。
