### ISSUE TITLE
[Feature] 能否支持多个apikey轮询使用

### ISSUE THREAD

**Issue by ape6239** [Yidadaa/ChatGPT-Next-Web#1715]
白嫖的5美元，主要是找不到安全可靠的渠道充值。白嫖用户3次/min，如果有多个apikey就可以白嫖到底了。
反正每次调用都是全量数据发送，换key发送也无所谓。 目前测试应该是不支持，是否能支持此功能。

**Comment by Jialinvip** [comment]
对，强烈建议加这个功能，可以同时加上多个Key，随机调用或者负载均衡

**Comment by lincheng77** [comment]
强烈建议，也建议把失效的key 放到黑名单，下次不轮轮训，也建议增加主要轮训key，和备用的自己的key

**Comment by Yidadaa** [comment]
https://mp.weixin.qq.com/s/L8HMOqkjflh9gAIiRpSKZQ

**Comment by mmwong1984** [comment]
https://www.iyhua.com/439.html
