### ISSUE TITLE
[Feature] 建议把 复制、重试、删除 3个按钮功能在发送消息栏上面也来一遍。

### ISSUE THREAD

**Issue by DamonDBT** [Yidadaa/ChatGPT-Next-Web#1717]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19727006/96977176-7b05-41de-9c6c-e6ff0564111c)

现在发送的消息上只有右键复制功能，有时候需要重新问答，需要复制了再粘贴，希望可以上面也加上3个按钮。

**Comment by yangyayuan** [comment]
这个建议不错，好像有时候点击自己发送的内容时自动填充到输入框，但是这个bug不太稳定，向大模型提问时经常需要多次修改自己的问题才能得到比较满意的答案，这个时候能复制自己的提问修改修改再提交是一个很不错的体验。

**Comment by Yidadaa** [comment]
右键点击消息快捷复制。

**Comment by Yidadaa** [comment]
手机上可以双击消息快捷复制，后续会在程序里内置使用指南，列出来目前支持的快捷操作，现在由于 i18n 翻译的问题没时间做。
