### ISSUE TITLE
[Bug] No apikey, no pass CODE, the tips is broken!

### ISSUE THREAD

**Issue by whc23mj** [Yidadaa/ChatGPT-Next-Web#1720]
**Describe the bug**

![20230524103947](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/2191887/c2e441cc-2d18-4fe8-9aa5-36210a56903d)

**Comment by Yidadaa** [comment]
I can do nothing without more information provided.

**Comment by whc23mj** [comment]
Hi，Yidadaa
Vercel部署，不预设API-KEY和CODE的话，不显示输入密码或KEY的提示信息，输入信息返回如上图。
预设API-KEY和CODE的话，没有问题。

我记得早期版本是可以不预设API-KEY和CODE的，现在必须预设KEY了吗？
