### ISSUE TITLE
建议增加自定义 BASE_URL 代理接口配置

### ISSUE THREAD

**Issue by hnsongbiao** [Yidadaa/ChatGPT-Next-Web#1723]
建议增加自定义 BASE_URL 代理接口配置，

目前可以配置自己的 open api key，希望增加 BASE_URL  的自定义，这样扩展性更强大了，其它很多类似系统都是可以的

**Comment by Yidadaa** [comment]
合着你是完全没有看文档是吧

<img width="1098" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/c4a02bcd-73e6-4c53-b4db-aefca6bba38c">

**Comment by hnsongbiao** [comment]
看过了呢，我的意思是希望用户在配置页面自己设置  BASE_URL

**Comment by Pa55w0rd** [comment]
> 建议增加自定义 BASE_URL 代理接口配置，
> 
> 目前可以配置自己的 open api key，希望增加 BASE_URL

+1 ，在用户设置页面可以自定义api key，也想在这个页面添加一个自定义base_url

**Comment by Pa55w0rd** [comment]
> 合着你是完全没有看文档是吧
> 
> <img alt="image" width="1098" src="https://user-images.githubusercontent.com/16968934/240479672-c4a02bcd-73e6-4c53-b4db-aefca6bba38c.png">

+1 ，在用户设置页面可以自定义api key，也想在这个页面添加一个自定义base_url

**Comment by hnsongbiao** [comment]
#1000要怎么实现呢？在您的计划中吗？

**Comment by hnsongbiao** [comment]
谢谢，期待中
