### ISSUE TITLE
有些浏览器的页面会出现显示异常

### ISSUE THREAD

**Issue by wqjuser** [Yidadaa/ChatGPT-Next-Web#173]
有些浏览器的输入框会在ai流式回答的时候挡住回答能容，能否动态保持回答内容一直位于输入框的上方呢

**Comment by GOWxx** [comment]
需要提供更多信息，
在什么操作系统上使用哪款浏览器的什么版本，本项目部署的版本是什么。

**Comment by Yidadaa** [comment]
ios 手机默认禁用了自动滚动，这与 safari 浏览器的兼容性有关。
