### ISSUE TITLE
[Bug] 我将本地的3000端口，通过xxxxx.tech/chatgpt来访问，利用ngnix进行反向代理。但是出现了资源无法找到

### ISSUE THREAD

**Issue by zy-up** [Yidadaa/ChatGPT-Next-Web#1733]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我将本地的3000端口，通过xxxxx.tech/chatgpt/ 来访问，利用ngnix进行反向代理。但是出现了资源无法找到

**如何复现**
这是ngnix的配置

    location /chatgpt/ {
        proxy_pass http://192.168.1.245:3000/;
        proxy_cache off;  # 关闭缓存
        proxy_buffering off;  # 关闭代理缓冲
        chunked_transfer_encoding on;  # 开启分块传输编码
        tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
        tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
        keepalive_timeout 300;  # 设定keep-alive超时时间为65秒
    }

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73047489/29c76279-5908-48e6-9b51-d07f26b29a1e)

 - 系统：ubuntu20
 - 部署方式：docker

**Comment by Yidadaa** [comment]
#720
