### ISSUE TITLE
如何在設置讓模型顯示不同的名稱

### ISSUE THREAD

**Issue by mmwong1984** [Yidadaa/ChatGPT-Next-Web#1744]
例如當選擇gpt-3.5-turbo時，在選擇模型的時候顯示ChatGPT,而不是gpt-3.5-turbo.

**Comment by mmwong1984** [comment]
顺便问一下如何改应用程式名称
什么时候才开放插件功能
如何移除在设置页面的更新方块

**Comment by Yidadaa** [comment]
这些需要你自己阅读代码修改，我没有时间给你解答这些定制内容。
