### ISSUE TITLE
[Bug] 设置了code后出现  json TypeError: Can't modify immutable headers. 

### ISSUE THREAD

**Issue by myqlrs** [Yidadaa/ChatGPT-Next-Web#1746]
部署在vercel上并设置了code和api后，访问时只设置code出现 json TypeError: Can't modify immutable headers. [这个错，输入api可正常使用
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/39188546/eda18e43-0cc2-4960-b00a-c3c4d1428039)

**Comment by Yidadaa** [comment]
不要设置 PROTOCOL 环境变量。

**Comment by schoolfamer** [comment]
> 不要设置 PROTOCOL 环境变量。

俺也遇到了这个问题。俺的环境变量里面只配置了OPENAI_API_KEY和CODE
求大佬解惑

**Comment by hieroglyphicss** [comment]
我使用了API2D的key，也是这样，API2D是一个代理的APIkey

**Comment by Zvirtuosity** [comment]
> 不要设置 PROTOCOL 环境变量。

我也碰到了一样的问题

**Comment by andyweidong** [comment]
同上，都遇到了这个问题，什么也没配置，就会报TypeError: Can't modify immutable headers.

**Comment by YeZhaoZhao** [comment]
+1  TypeError: Can't modify immutable headers.

**Comment by schoolfamer** [comment]
我发现我只有在使用自定义域名的时候才会报错，vercel的域名正常。不知道其他几位是不是也一样的遭遇

**Comment by andyweidong** [comment]
@myqlrs 你的报错问题解决了吗

**Comment by myqlrs** [comment]
> 

没有，我把CODE去了，就正常使用了，一加上CODE就不行

**Comment by myqlrs** [comment]
> @myqlrs 你的报错问题解决了吗

没有，我把CODE去了，就正常使用了，一加上CODE就不行

**Comment by Zvirtuosity** [comment]
> > 不要设置 PROTOCOL 环境变量。
> 
> 我也碰到了一样的问题！只配置了OPENAI_API_KEY和CODE

我解决了！是配置错了环境变了里的key

1. 检查设置里的api key，是不是填错了！
2. 检查服务里的环境变量，是不是填错了！
优先级，应该是聊天页里填的code和api key，然后再到环境变量里的key

**Comment by Yidadaa** [comment]
新版代码已经修复该问题，手动同步代码即可。

**Comment by Kevin-free** [comment]
code 和 API key 都需要设置才可用吗？ 我怎么记得之前只设置 code 就可以，现在两个都要设置
