### ISSUE TITLE
[Bug] /bin/sh: syntax error: unexpected end of file (expecting "fi")

### ISSUE THREAD

**Issue by lunaflora** [Yidadaa/ChatGPT-Next-Web#1748]
**Describe the bug**
部署的时候出现unexpected end of file (expecting "fi")
dockerfile的问题
  if [ -z "$HOSTNAME" ]; then \
          export HOSTNAME="127.0.0.1" \
        fi; \

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
#1747
