### ISSUE TITLE
[Feature] 部分Mask面具，默认采用了【GPT-4】模型，新手容易误操作；可以考虑加上【防呆设计】

### ISSUE THREAD

**Issue by hanshou101** [Yidadaa/ChatGPT-Next-Web#1752]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
预置的面具列表中，【越狱模式 [Jailbreak]】、【GitHub Copilot】等几个面具，默认采用了【GPT4模型】。
当新手第一次采用面具时，容易造成误操作，进而流失大量的key余额。（也算是怪我菜吧  555）
（堪称流量刺客，555）
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19248935/3c1fa843-977f-466f-96a4-4093e3830725)

**如何复现**
点击【面具】，进入【预设角色面具】的列表。

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19248935/abd6c303-898a-48cb-8aa7-a9dcd018cff9)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19248935/c4445099-4821-4a44-a7e8-813d973c5756)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19248935/d0243eb5-e096-4bb8-b6fa-2ec1938043a5)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19248935/cd309218-3e58-435e-a573-e1bce3ffd8b8)
其实，在【列表界面】，已经显示了【对应模型版本】。（但是可能，第一次用这里的话，容易被忽略）
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19248935/a5e4e50a-d955-43a3-870b-e2cb7e509932)

**部分建议**
- 在选择，带【GPT-4】模型的面具时，可以弹出一条【确认提示】，以方便让 菜鸟用户 能够二次确认一下。
- 或者，在【对话列表】中，可以【显示当前使用模型】。（当前版本下，在对话记录中，无【模型版本】的显示）
- - ![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19248935/01e0db5e-58d7-4981-8404-e81d1b353a09)

**一些必要的信息**
 - 系统：Win10
 - 浏览器： Chrome113
 - 版本： 20230525
 - 部署方式：Vercel

**Comment by Yidadaa** [comment]
这个就见仁见智了，现在使用 mask 的流程已经足够繁琐了，不想再加一个确认的操作了。

**Comment by tqsJohn** [comment]
好奇你这个扣费项这么详细。。是第三方的么

**Comment by hanshou101** [comment]
> 好奇你这个扣费项这么详细。。是第三方的么

昂昂，是用的第三方的。
tokens是他们估算的。

要搭配他们的ApiProxy代理地址，才能用。
估计，可能是他们有一个key池，然后分到每个用户的，只是一个虚拟key。  他们内部自己做流量管理和记账的。

因为商业关联原因，第三方的名字我就不在这儿提了。
