### ISSUE TITLE
[Feature] Does it support ChatGPT Plus subscribed via iOS?

### ISSUE THREAD

**Issue by Gonesy** [Yidadaa/ChatGPT-Next-Web#1761]
I have subscribed ChatGPT Plus via ChatGPT iOS application. But seems it was not support in ChatGPT-Next-Web. If I switch the model to GPT-4, it returned the following error:
{
  "error": {
    "message": "The model: `gpt-4` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}

I have also generated a new API key, but still the issue remains.
Does it support this scenario? Or will it support it?

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-en.md#how-to-access-the-gpt-4-api

**Comment by Yidadaa** [comment]
ChatGPT Plus !== GPT 4 API
