### ISSUE TITLE
session 名字有问题？

### ISSUE THREAD

**Issue by addlistener** [Yidadaa/ChatGPT-Next-Web#1763]
<img width="2552" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/4531670/99d18372-43f8-4cf0-86af-e154b515449e">

你看我让gpt自己conclude就是对的。。这个标题也太离谱了

**Comment by Yidadaa** [comment]
中文 prompt 有时候会不太准，可以切换系统语言到英文
