### ISSUE TITLE
[Bug] 手机上的QQ浏览器或者UC浏览器，发送消息后，报错且无法展示回复的消息

### ISSUE THREAD

**Issue by JunYongHuang** [Yidadaa/ChatGPT-Next-Web#1764]
**描述问题**
在手机上的QQ浏览器或者UC浏览器，发送消息后，报错且无法展示回复的消息。
显示错误如下：
{
  "error": true,
  "message": "undefined is not an object (evaluating 'e.getReader')"
}

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
![c7d0693ffad26926efb7bcf68eee064](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/7039400/d4b3134e-752b-4b2a-bcd3-70c79b649080)

**一些必要的信息**
 - 系统：[iPhone X / ios 13]
 - 浏览器： [qq浏览器, uc浏览器]
 - 版本： [最新版本]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
不会处理任何浏览器兼容性问题。

**Comment by mrright2019** [comment]
> **描述问题** 在手机上的QQ浏览器或者UC浏览器，发送消息后，报错且无法展示回复的消息。 显示错误如下： { "error": true, "message": "undefined is not an object (evaluating 'e.getReader')" }
> 
> **如何复现** 请告诉我们你是通过什么操作触发的该问题。
> 
> **截图** ![c7d0693ffad26926efb7bcf68eee064](https://user-images.githubusercontent.com/7039400/241112431-d4b3134e-752b-4b2a-bcd3-70c79b649080.jpg)
> 
> **一些必要的信息**
> 
> * 系统：[iPhone X / ios 13]
> * 浏览器： [qq浏览器, uc浏览器]
> * 版本： [最新版本]
> * 部署方式：[vercel]

在编译完成的js文件中 搜索 e.getReader 修改其调用栈为 new Uint8Array(await e.arrayBuffer)) 即可

**Comment by leadscloud** [comment]
修改为new Uint8Array(await e.arrayBuffer)) 后无法流式传输。fetch-event-source使用这个修改后的就行  https://github.com/Xuan-Yu-San/fetch-event-source/blob/main/src/parse.ts

就改了这个，判断下getReader
```
export async function getBytes(response: Response, onChunk: (arr: Uint8Array) => void) {
    const reader = response.body?.getReader();
    if (reader) {
        let result = await reader.read();
        while (!result.done) {
            onChunk(result.value);
            result = await reader.read();
        }
    } else {
        onChunk(new Uint8Array(await response.arrayBuffer()));
    }
}
```
