### ISSUE TITLE
It was detected as gpt-3.5-turbo-0301 even though I was using gpt-3.5-turbo.

### ISSUE THREAD

**Issue by zexry619** [Yidadaa/ChatGPT-Next-Web#1768]
"I always use `gpt-3.5-turbo` on the web UI: https://im.ge/i/image.hDyOqP, but why does it show `gpt-3.5-turbo-0301` when I check the Usage: https://i.im.ge/2023/05/26/hDy6Tz.image.png? Is this normal or does it require additional settings?"

**Comment by Yidadaa** [comment]
It is OpenAI's default behavior.
