### ISSUE TITLE
对话框最后一条对话时间显示不全

### ISSUE THREAD

**Issue by Zoranner** [Yidadaa/ChatGPT-Next-Web#178]
Microsoft Edge
版本 111.0.1661.54 (正式版本) (64 位)

鼠标滚轮已经滚动到最底部，滚动条的位置似乎也有偏差。

![image](https://user-images.githubusercontent.com/20719726/228626651-813717e1-3cd1-4724-9e1e-de4f1e38be94.png)

**Comment by Yidadaa** [comment]
请尝试最新版本。
