### ISSUE TITLE
[Bug] report "Exceeded your current quota" but actually not

### ISSUE THREAD

**Issue by eSuper** [Yidadaa/ChatGPT-Next-Web#1794]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
提示报错，“超过你的配额”这个问题。

```js
{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": null
  }
}

```

<img width="585" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/92929085/ff7ec544-c916-4a8c-ae2f-5cf734a308d8">

但是检查余额，发现并没有用完。
<img width="686" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/92929085/cb8e24f9-2dee-49f6-bdae-7574c544faaf">

**如何复现**
请告诉我们你是通过什么操作触发的该问题。
正常访问网址，发现了这个问题

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：macOS
 - 浏览器： chrome
 - 版本： 20230602
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
赠送余额过期了。

**Comment by eSuper** [comment]
明白！谢谢您！🙏
