### ISSUE TITLE
[Bug] 访问密码不正确或为空，请前往设置页输入正确的访问密码，或者填入你自己的 OpenAI API Key。

### ISSUE THREAD

**Issue by whxat** [Yidadaa/ChatGPT-Next-Web#1796]
{
  "error": {
    "message": "",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}

**Comment by CoisiniFish** [comment]
解决了，谢谢

**Comment by prayzll** [comment]
请问怎么解决的呀

**Comment by fangyuan99** [comment]
填入自己的key还是有这个问题，请问怎么解决的

**Comment by WananEleven** [comment]
请问怎么解决？

**Comment by starsas** [comment]
请问怎么解决的

**Comment by starsas** [comment]
![be56e9a37e90c623f390239982251ee](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/87849265/9ce100b2-8ea7-4b28-a72f-e9c63df226f5)
右下角设置，要把转发地址也弄上去
