### ISSUE TITLE
[Feature] 能否加入使用accessToken的支持

### ISSUE THREAD

**Issue by shentong0722** [Yidadaa/ChatGPT-Next-Web#1797]
[目前能够实现的项目也很多（比如：(https://github.com/Chanzhaoyu/chatgpt-web#%E4%BB%8B%E7%BB%8D)但是个人更喜欢大佬的这个界面，所以想问问大佬能不能加入使用accessToken的支持，不管怎么说这个至少是免费的，使用api怎么着要花美刀]

**Comment by TeamFan** [comment]
作者之前好像说过，不可能添加

**Comment by shentong0722** [comment]
嗯，找到了，作者之前说访问不稳定，所以不做。。。但是感觉【pengzhile/pandora】这个项目用着没啥大问题，现在作者能否再考虑一下呢
