### ISSUE TITLE
[Bug] 一直显示没有额度

### ISSUE THREAD

**Issue by 805828526** [Yidadaa/ChatGPT-Next-Web#1803]
You exceeded your current quota, please check your plan and billing details.

但是我在官网查看的我的额度是满的
![1685848770129](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/109738886/94ba2a5f-fd4a-4dd6-a16d-182f1630d2a9)
![F_KN }LMG40OSB@ZJZB}W~6](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/109738886/6b5f27f4-1543-4f53-887a-7fd2e76b0c06)

**Comment by l-sw-123** [comment]
me too

**Comment by ZccccFDU** [comment]
yeah, I meet the same problems. It always reminds me "You exceeded your current quota, please check your plan and billing details", but I can use chat-GPT normally at https://chat.openai.com.
