### ISSUE TITLE
[Feature] 添加frequency_penalty字段配置功能，已经提交PR

### ISSUE THREAD

**Issue by AngelLiang** [Yidadaa/ChatGPT-Next-Web#1808]
你好，我想这个项目能使用frequency_penalty参数，已经提交PR，请验收。
相关PR：https://github.com/Yidadaa/ChatGPT-Next-Web/pull/1807

Hello, I think this project can use frequency_penalty parameter, PR has been submitted, please accept it.

**Comment by Yidadaa** [comment]
两者的用处高度相似，终端用户基本无法区分差别：

https://platform.openai.com/docs/api-reference/parameter-details
