### ISSUE TITLE
[Bug] 使用7777端口docker部署项目报Loading chunk 5846 failed

### ISSUE THREAD

**Issue by Tinyang** [Yidadaa/ChatGPT-Next-Web#1812]
具体报错内容：
ChunkLoadError: Loading chunk 5846 failed.
error: https://XXX:7777/_next/static/chunks/5846.7d3c836xx.js
版本：5月31号拉的最新docker image
浏览器：Chrome和Firefox均出现了该问题
怀疑是和用了非标端口有关，浏览器将7777识别成了请求路径而不是端口。（用两个月之前的版本docker image非标端口部署，没遇到这种问题）
补充说明：项目部署在docker里面，外面用Nginx做了反向代理和https

**Comment by Yidadaa** [comment]
ngnix 反向代理到 80 端口。

**Comment by edisonzf2020** [comment]
我也一样，2.7版还正常，2.8开始就报这个错，我的域名一只用ngnix 反向代理到 80 端口，现在只能用2.7版本
