### ISSUE TITLE
built in prompt autocompletion problem ?

### ISSUE THREAD

**Issue by wyonghao** [Yidadaa/ChatGPT-Next-Web#182]
prompt autocompletion problem. 无论是在用鼠标点击，还是用tab按键，都无法把预设的prompt的内容copy paste到对话框里面。请问这个功能怎么使用？firefox 在mac和pc上都是这个问题。
![image](https://user-images.githubusercontent.com/4404209/228647733-919a014d-c037-4d7b-bac2-8fc7d5777817.png)

**Comment by glongzh** [comment]
这功能是有问题。输入/后还要再输入才会出现prompt list，出来后，上下键无法选择，鼠标点击选择也无效

**Comment by Yidadaa** [comment]
在 MacOS 12.x Firefox 上自测没有问题，请使用新版本重新测一下。
