### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ser-MingShao** [Yidadaa/ChatGPT-Next-Web#1822]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
windows10上打包报错，Vscode控制台输入yarn next build，屡次未成功，未解，求解决

**如何复现**
yarn next build
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/67584847/7c030a2e-bf5e-4586-b971-6788bb470a28)

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/67584847/daa86634-618d-4c5d-ac95-a2eed261ff76)

**一些必要的信息**
 - 系统：[ windows 10]
 - 浏览器： [chrome, ]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[本地部署静态部署]

**Comment by Yidadaa** [comment]
这不是打包成功了？接下来运行 `yarn start`
