### ISSUE TITLE
[Feature] 账号登录的问题

### ISSUE THREAD

**Issue by toyo2333** [Yidadaa/ChatGPT-Next-Web#1825]
**其他信息**
我第一次看人推荐进来这个项目，小白，看不太懂。

使用这个工程是需要输入自己的ChatGTP的用户名和密码对么？那为什么这里只能输入密码https://chatgpt.nextweb.fun/#/settings 用户名在哪里输入呢？

**Comment by Yidadaa** [comment]
不需要账号密码，你需要生成 openai api key，具体可以自行百度。
