### ISSUE TITLE
[Bug] 没有设置CODE聊天时候还会提示访问密码不正确或为空

### ISSUE THREAD

**Issue by gzw13999** [Yidadaa/ChatGPT-Next-Web#1828]
**Describe the bug**
这样运行docker没有传递CODE聊天时提示  访问密码不正确或为空
```
docker run -d -p 127.0.0.1:3000:3000 \
   -e OPENAI_API_KEY="sk-......" \
   yidadaa/chatgpt-next-web
```
之前使用的是36天前的版本是可以实现不设置CODE参数的，今天心血来潮更新了下，结果不行了。

**Expected behavior**
我这地使用caddy做鉴权不需要再通过code参数做验证

**Deployment**
- [*] Docker

**Comment by gzw13999** [comment]
一个一个版本回退测试到了docker pull yidadaa/chatgpt-next-web:v2.1
问题解决。

**Comment by 6Oscar6** [comment]
我设置了密码，现在是最新版本，也显示：
访问密码不正确或为空，请前往[设置](/#/settings)页输入正确的访问密码，或者填入你自己的 OpenAI API Key。

```json
{
  "error": {
    "message": "",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}
```

**Comment by lpx0312** [comment]
楼上+1 ,我设置了CODE也提示    访问密码不正确或为空，请前往[设置](https://chatgpt.sktill.top/#/settings)页输入正确的访问密码，或者填入你自己的 OpenAI API Key。

**Comment by yinm0591** [comment]
@gzw13999 改成以下命令试试：

```bash
docker run -d -p 127.0.0.1:3000:3000 \
   -e "OPENAI_API_KEY=sk-......" \
   yidadaa/chatgpt-next-web:latest
```

**Comment by gzw13999** [comment]
> @gzw13999 改成以下命令试试：
> 
> ```shell
> docker run -d -p 127.0.0.1:3000:3000 \
>    -e "OPENAI_API_KEY=sk-......" \
>    yidadaa/chatgpt-next-web:latest
> ```

原来如此

**Comment by gzw13999** [comment]
刚才验证了下，不可行，和docker版本没关系吧 退回到v2.1版就好了

**Comment by yinm0591** [comment]
@gzw13999 我测试了以下命令是正常的。由于新版本调整了apikey和code的传递方式，你遇到的问题可能是：新版本与caddy的用户鉴权有冲突造成的。

```
docker run  -d -p 127.0.0.1:3000:3000 \
 -e OPENAI_API_KEY="sk-***" \
 yidadaa/chatgpt-next-web:latest
```

**Comment by gzw13999** [comment]
> @gzw13999 我测试了以下命令是正常的。由于新版本调整了apikey和code的传递方式，你遇到的问题可能是：新版本与caddy的用户鉴权有冲突造成的。
> 
> ```
> docker run  -d -p 127.0.0.1:3000:3000 \
>  -e OPENAI_API_KEY="sk-***" \
>  yidadaa/chatgpt-next-web:latest
> ```

是的，确实与caddy有关。

**Comment by SpyFax** [comment]
> @gzw13999 我测试了以下命令是正常的。由于新版本调整了apikey和code的传递方式，你遇到的问题可能是：新版本与caddy的用户鉴权有冲突造成的。
> 
> ```
> docker run  -d -p 127.0.0.1:3000:3000 \
>  -e OPENAI_API_KEY="sk-***" \
>  yidadaa/chatgpt-next-web:latest
> ```

也跟Traefik的basic auth有冲突

**Comment by Yidadaa** [comment]
为了保证接下来的客户端一致性，`Authorization` 头的用户不会改变，所以各位尝试其他方法做权限管控吧。

**Comment by 1368129224** [comment]
不能用basic auth了吗？

**Comment by Tacit-git** [comment]
chatgpt-next-web:
        restart: always
        environment:
            OPENAI_API_KEY: 'sk-xxxxxxxxxxxxxxxxxx'
        ports:
            - '3000:3000'
        container_name: chatgpt-next-web
        image: 'yidadaa/chatgpt-next-web'

出现类似的问题，各位解决了吗？

**Comment by gzw13999** [comment]
> `Authorization`

Authorization 字段冲突了，谁有解决办法。

**Comment by chunfengyao** [comment]
> > `Authorization`
> 
> Authorization 字段冲突了，谁有解决办法。

有个临时的解决办法：
给nginx添加hide header，也就是让真实后端识别为没有authorizztion头

目前是可以达到效果的，贴一下我这边的配置。

```
  location / {
        if ( $http_cookie !~* "auth-token" ) {
            rewrite ^ /chat-get-auth$request_uri$is_args$args last;
        }
        rewrite ^ /chat-real-proxy$request_uri$is_args$args last;
    }

    location ~ /chat-get-auth/(.*) {
        #仅验证过的用户可以访问
        auth_basic "Authorized Users Only";
        auth_basic_user_file /app/certs/auth_basic/nginx_auto_basic.proxy.conf;

        error_page 404 = /chat-real-proxy/$1$is_args$args;
    }

    location ~ /chat-real-proxy/(.*) {
        proxy_set_header  Authorization "";
        proxy_hide_header Authorization;
        #请求后端的文件服务
        proxy_pass http://172.20.0.205:3000/$1$is_args$args;
        # include conf.d/common/location_for_proxy_http.conf;

#        if ( $http_cookie !~* "auth-token" ) {
            #设置免验证的cookie，避免下次验证
            add_header Set-Cookie 'auth-token=421431432423123e4;expires=31 Dec 9999 00:00:00 UTC;path=/;Secure;HttpOnly;';
#        }
    }

```

**Comment by chunfengyao** [comment]
希望作者可以优化一下密码验证方案。如果是在App内部进行验证的话，机器人，或者网页扫描软件是可以很精准判断出当前网页是chatgpt-next-web，然后可以进行一系列的操作。但，如果是第一个请求就直接要求验证，并且是标准的nginx验证，扫描器无法立刻得知网页内容究竟是什么，这样可以进一步保护服务。

**Comment by LBBSLX** [comment]
{
  "error": {
    "message": "Incorrect API key provided: ak-code1. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}
请问设置了CODE也提示 访问密码不正确或为空，请前往[设置](https://chatgpt.sktill.top/#/settings)页输入正确的访问密码，或者填入你自己的 OpenAI API Key。这个怎么解决呢

**Comment by hellohawaii** [comment]
For caddy, you may use the following setting (I refer to @chunfengyao https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1828#issuecomment-1646517751):

```
YOU_DOMAIN {
   basicauth {
                YOUR_NAME HASHED_PASSWORD
    }
    reverse_proxy localhost:3000 {
        header_up -Authorization
    }
}
```

This works for me. I did not try using the CODE in ChatGPT-Next-Web.

**Comment by gzw13999** [comment]
> For caddy, you may use the following setting (I refer to @chunfengyao https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1828#issuecomment-1646517751):
> 
> ```
> YOU_DOMAIN {
>    basicauth {
>                 YOUR_NAME HASHED_PASSWORD
>     }
>     reverse_proxy localhost:3000 {
>         header_up -Authorization
>     }
> }
> ```
> 
> This works for me. I did not try using the CODE in ChatGPT-Next-Web.
很感谢，由于特殊情况我这里必须使用Caddy,最近几个月我一直在寻找解决办法，今天我看到你的恢复终于解决了困扰我很久的问题了.
