### ISSUE TITLE
建议引入官方API中 system 角色的设计

### ISSUE THREAD

**Issue by Zoranner** [Yidadaa/ChatGPT-Next-Web#183]
建议将对话框中第一条消息更改为 **`system`** 的角色，API参考：[Chat completions](https://platform.openai.com/docs/guides/chat/introduction#:~:text=%2C%0A%20%20messages%3D%5B%0A%20%20%20%20%20%20%20%20%7B-,%22role%22%3A%20%22system%22,-%2C%20%22content%22)。

同时建议新增以下特性：

1. 对话项目右上角增加编辑按钮，可通过弹出对话框修改对话项目名称以及 `system` 角色的消息内容；
2. 右上角新增清除对话记录的按钮，用于清除对话框中消息记录，**该操作不清除 `system` 消息**（方便对话项目多次重复使用）；
3. 修改与 `system` 角色更匹配的图标，另外该消息的消息气泡样式可特别处理，且无需显示时间；

![image](https://user-images.githubusercontent.com/20719726/228648845-b9e78ae3-1799-479b-b9a6-382468f61ad5.png)

参考项目：[Bin-Huang / chatbox](https://github.com/Bin-Huang/chatbox)

![image](https://user-images.githubusercontent.com/20719726/228652334-7db4f60b-ff95-4ed9-a603-c3285b88fece.png)

**Comment by realskyrin** [comment]
这个之前提过了，开发者说正在做：https://github.com/Yidadaa/ChatGPT-Next-Web/issues/138

**Comment by Yidadaa** [comment]
Duplicate #138
