### ISSUE TITLE
[Bug] windows下docker拉取镜像在使用面具>以文搜图,在输入框输入中文字符大概率会出现错误

### ISSUE THREAD

**Issue by qwerdome** [Yidadaa/ChatGPT-Next-Web#1830]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/74087938/52615750-0e73-4e33-9732-72d09e0ecef8)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/74087938/529a112d-b505-4db9-92e4-3f985f50c92a)

**Comment by Yidadaa** [comment]
Windows 版本和浏览器版本提供一下。

**Comment by qwerdome** [comment]
chrome 113.0.5672.129
windwos 10 家庭单语言版

**Comment by andy07559** [comment]
我也出现这样的情况

**Comment by qwerdome** [comment]
> Windows 版本和浏览器版本提供一下。
好像知道什么原因了，是腾讯翻译这个扩展导致的我关闭了扩展就没有出现了
![报错](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/74087938/29261e1b-9ad9-45ac-842c-2b07bfcef1b2)
