### ISSUE TITLE
这个配额是什么意思，设置那也能查到，为什么每问一句就弹出来这段代码？

### ISSUE THREAD

**Issue by ENDAYUAN** [Yidadaa/ChatGPT-Next-Web#1831]
删除重试复制{"错误"：{“消息”：“您超出了当前配额，请检查您的计划和账单详细信息。”，"类型": "insufficient_quota","param"：空，"代码"：空}}删除重试复制{"错误"：{“消息”：“您超出了当前配额，请检查您的计划和账单详细信息。”，"类型": "insufficient_quota","param"：空，"代码"：空}}

**Comment by Chenkeyi43** [comment]
看下你openai 的余额是不是过期了
