### ISSUE TITLE
[Feature] UI界面建议、关闭“有什么可以帮你的吗”提示词、添加“预设角色面具”页面的直达按钮、添加Windows本地部署的代理设置

### ISSUE THREAD

**Issue by AelecTi** [Yidadaa/ChatGPT-Next-Web#1832]
### 4个建议

* 关于UI界面，新的信息生成时消息气泡会越来越长，这时右上角的“复制 | 停止”按钮以及右下角的时间信息会随着气泡的右边缘一起移动，使用时有点不便
* 每次的会话开头有一个“有什么可以帮你的吗”的提示词，请问能否添加不显示的选项
* 进入“预设角色面具”的页面需要：页面左上角点击`面具` → 页面中部点击`查看全部`，考虑到这是经常要用的界面，能否单独设置一个按钮直达这个页面？
* 方便的话能否添加Windows本地部署配置代理的功能（而不是走WSL+proxychains）

感谢作者开发的UI界面，界面和动画很好看！[之前用的](https://github.com/anse-app/chatgpt-demo)没有保存不同对话以及预设的功能，于是找到了这个项目

> QQ群满了，~~请问作者要不要考虑创建一个Telegram的群组~~

**Comment by Yidadaa** [comment]
1. 已经充分讨论过了，不会再变了；
2. 如果已经有面具了，欢迎语就不会出现；
3. 聊天输入框上方，点击面具图标可直达；
4. 不是方便不方便的问题，nodejs 代理不好配置，你可以自己研究研究。
