### ISSUE TITLE
[Bug] docker部署后提示TypeError: Failed to parse URL from http/v1/chat/completions?path=v1&path=chat&path=completions

### ISSUE THREAD

**Issue by momolon** [Yidadaa/ChatGPT-Next-Web#1833]
docker部署后，输入问题，提示TypeError: Failed to parse URL from http/v1/chat/completions?path=v1&path=chat&path=completions

**Comment by Yidadaa** [comment]
检查你的环境变量，BASE_URL 不要乱设置。

**Comment by mbg17** [comment]
解决了吗？楼主
