### ISSUE TITLE
[Feature] 将对话气泡右上角的按钮固定

### ISSUE THREAD

**Issue by AelecTi** [Yidadaa/ChatGPT-Next-Web#1840]
## 你想要什么功能或者有什么建议？

将对话气泡右上角的按钮固定。

有时生成的对话可能有错误，需要在没生成完之前终止，这时想点击终止按钮就会这样：

![ChatGPT Next Web - Google Chrome 2023-06-06 18-41-51 (online-video-cutter com)](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/50296600/ffa5cd5f-7a84-4980-bf59-f0fda711acc2)

根本点不到，仿佛在打音游XD

**Comment by Yidadaa** [comment]
使用输入框上面的停止按钮进行停止。

<img width="413" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/6fadfbd3-e3f9-423b-8866-69be089257d3">
