### ISSUE TITLE
[Bug] 手机点击导出图片无反应

### ISSUE THREAD

**Issue by Mtoly** [Yidadaa/ChatGPT-Next-Web#1845]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在Safari中点击导出聊天记录为图片没有反应

**一些必要的信息**
 - 系统：ios14.4
 - 浏览器： safari
 - 版本： 20230602
 - 部署方式：docker

**Comment by Yidadaa** [comment]
导出图片所用的库兼容性比较差，目前已知在安卓和 pc 工作良好，pwa 中无法使用此功能。

请尝试:
- 升级最新系统
- 确认没有在 pwa 中使用此功能
