### ISSUE TITLE
[Bug] auth页面的意义是啥？

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#1849]
第一次访问 /auth 输入密码，第二次访问 密码直接显示了，好像也没啥判断是否正确的逻辑？
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/038ec35f-b458-4f08-a60e-8bb6677c5a27)

**Comment by Yidadaa** [comment]
之后会加判断逻辑，很多用户反馈说他们的用户在设置页面不知道往哪填访问码，加这个页面来防呆。
