### ISSUE TITLE
如何修改3000端口？

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#1857]
我idea本地启动，3000端口已经被其它应用占用，如何改成其它端口？

**Comment by Yidadaa** [comment]
https://stackoverflow.com/questions/60147499/how-to-set-port-in-next-js

**Comment by vual** [comment]
已解决，可以这样设置。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/d12f7ad8-4ed8-4721-9a08-8ea5835a9d1a)

**Comment by vual** [comment]
或者  yarn dev -p 3003

**Comment by mingouuu** [comment]
请问package.json在哪一个目录下呢？
