### ISSUE TITLE
[Bug] MD超链接解析错误

### ISSUE THREAD

**Issue by jazzii36** [Yidadaa/ChatGPT-Next-Web#1862]
![7e44e0a014946aff4cf867e6d23468d](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35281744/b8bb7f6e-7d7b-4f79-bb90-09532a73aebc)

**Comment by Yidadaa** [comment]
此行为是标准 md 解析行为，github markdown 也是这么解析的，你可以让 chatgpt 在链接后面加空格。
