### ISSUE TITLE
我购买了GPT plus在使用4.0的时候返回如下，麻烦问下是什么原因，谢谢。

### ISSUE THREAD

**Issue by jinzhaoj** [Yidadaa/ChatGPT-Next-Web#1866]
{
  "error": {
    "message": "The model: `gpt-4` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}

**Comment by Yidadaa** [comment]
plus 不代表你能用 gpt-4 api。

**Comment by jinzhaoj** [comment]
麻烦请教一个问题，为什么我开通了plus，GPT还在使用我收费的key

**Comment by lethelong** [comment]
plus意思不是你20刀包月随便用  只是你开通了会员权限，可以在调用高峰期无需排队等待直接使用gpt，官网上开通plus后是可以直接使用gpt4的，但是如过使用API，即使开通了plus也是要申请的，至于申请通不通过就看你的运气了。
