### ISSUE TITLE
[Bug] 使用谷歌浏览器，当打开自动英中翻译模式，提问和回答均不完整

### ISSUE THREAD

**Issue by bjdr69** [Yidadaa/ChatGPT-Next-Web#1873]
使用谷歌浏览器，当打开自动英中翻译模式，提问和回答均不完整
显示如下
<img width="571" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/131727738/f22c91a4-6537-42bb-b58a-8842a7994a53">
实际应为：
<img width="449" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/131727738/6caed832-94f1-44cf-962d-242b7c6de08b">

当前版本：20230608

**Comment by Yidadaa** [comment]
浏览器翻译会影响 dom 渲染，不要打开翻译模式。
