### ISSUE TITLE
English translation isn't perfect

### ISSUE THREAD

**Issue by benjaminv** [Yidadaa/ChatGPT-Next-Web#188]
There is room to improve the english copy of this project in general. 
For instance I had to switch to CHN to understand what the last item in settings `Presence Penalty` is. 

Funny enough Chatgpt 3 translates back to following Chinese,
存在惩罚 较大的值会增加谈论新话题的可能性。

How about follows,
EN: Threshold for topic expansion. Larger values allow for a higher chance of expanding the current topic to others.
CHS from Chatgpt: 话题多样性阈值。更大的值允许更高的概率将当前话题扩展到其他话题。

**Comment by MrThanlon** [comment]
pull requests are welcome

**Comment by Yidadaa** [comment]
I'm not a native English speaker. If you find any room for improvement in the English translation, please feel free to submit a formal PR to improve it.

**Comment by rossman22590** [comment]
I will do this task give me 2 days

**Comment by wyonghao** [comment]
> Presence Penalty

I think `Presence penalty` is the standard terminology that open AI uses.

**Comment by Yidadaa** [comment]
It appears that there have been no updated responses to this topic, and therefore, this issue is about to be closed.
