### ISSUE TITLE
[Bug] 点面具报错

### ISSUE THREAD

**Issue by calvin886886** [Yidadaa/ChatGPT-Next-Web#1881]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/109566006/3737eb29-ab80-4717-83a2-5b3ca074dfc0)

用docker拉的库    点面具就报错
版本是0521的一直没有办法升级到608

**Comment by Yidadaa** [comment]
检查是否开启了页面翻译，或者装了翻译插件。

开启一个私密标签页，打开本项目的演示站，确认是否能复现该问题。
