### ISSUE TITLE
[Bug] 安卓Chrome浏览器打开报错

### ISSUE THREAD

**Issue by sxchou** [Yidadaa/ChatGPT-Next-Web#1882]
安卓手机Chrome浏览器打开报错，其他浏览器没问题
![Screenshot_20230610_145511.jpg](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/125382693/8dca0d72-de94-42e1-80a0-dd8f0438adae)

**Comment by snownightflower** [comment]
这边也是一样,苹果ios 13.3系统 打开就你这样子 ,全部浏览器,微信打开都是这样子 . ios系统升级到新版的其他时间了 pc电脑端就就正常 求解答这个什么情况.

**Comment by Yidadaa** [comment]
提供一下安卓版本号，和 chrome 版本号

**Comment by sxchou** [comment]
测试过好几个安卓手机都一样，貌似跟版本号无关，苹果手机未测 chrome版本号78.0.3904.96

**Comment by JerryXu09** [comment]
我这边iPhone6(iOS12.5.7)打开也是像这样报错，但用iPhone12(iOS15.x)和iPad(iPadOS16.1)就不会报错

**Comment by Yidadaa** [comment]
提供一下部署方式，镜像版本，服务器操作系统版本。

**Comment by sxchou** [comment]
> 提供一下部署方式，镜像版本，服务器操作系统版本。

使用vercel一键部署的，后面使用了docker部署在阿里云也是同样的问题，包括别人部署的这个项目我也试过了也是一样的问题，也试过了很多手机，还试过了别人的项目https://chat2.jinshutuan.com/这个项目用chrome直接打不开，所以我觉得应该是浏览器的问题

**Comment by Yidadaa** [comment]
@sxchou 现在 Chrome 版本号都到 114 了，你从哪找的 78 的远古安装包

**Comment by JerryXu09** [comment]
我也是用vercel一键部署的，后来又根据文档重新fork且配置了自动更新，目前版本20230610

**Comment by sxchou** [comment]
> @sxchou 现在 Chrome 版本号都到 114 了，你从哪找的 78 的远古安装包

更新到Chrome 114.0.5735.61后可以正常打开了，很奇怪我试过4个手机都是版本低的么，而且今天我还特意用朋友的手机下了一个也报错😂

**Comment by xxhjkl** [comment]
> 提供一下部署方式，镜像版本，服务器操作系统版本。

部署方式：docker-compose
镜像版本：
root@test:~# docker images yidadaa/chatgpt-next-web
REPOSITORY                 TAG       IMAGE ID       CREATED      SIZE
yidadaa/chatgpt-next-web   latest    93ae8315c4bf   8 days ago   233MB

服务器操作系统版本：
debian 10

访问的浏览器是chrome 114.0.5735.110 手机safari 手机chrome也一样的错误。首页是能打开的，点击面具或者点击设置就会报错.

**Comment by xxhjkl** [comment]
> > 提供一下部署方式，镜像版本，服务器操作系统版本。
> 
> 部署方式：docker-compose 镜像版本： root@test:~# docker images yidadaa/chatgpt-next-web REPOSITORY TAG IMAGE ID CREATED SIZE yidadaa/chatgpt-next-web latest 93ae8315c4bf 8 days ago 233MB
> 
> 服务器操作系统版本： debian 10
> 
> 访问的浏览器是chrome 114.0.5735.110 手机safari 手机chrome也一样的错误。首页是能打开的，点击面具或者点击设置就会报错.

经排查是反代出问题了。和镜像无关。

**Comment by xzqiaochu** [comment]
> > > 提供一下部署方式，镜像版本，服务器操作系统版本。
> > 
> > 
> > 部署方式：docker-compose 镜像版本： root@test:~# docker images yidadaa/chatgpt-next-web REPOSITORY TAG IMAGE ID CREATED SIZE yidadaa/chatgpt-next-web latest 93ae8315c4bf 8 days ago 233MB
> > 服务器操作系统版本： debian 10
> > 访问的浏览器是chrome 114.0.5735.110 手机safari 手机chrome也一样的错误。首页是能打开的，点击面具或者点击设置就会报错.
> 
> 经排查是反代出问题了。和镜像无关。

请问下是反代哪里出问题了，我也遇到了相同的问题

**Comment by bentennysonyoung** [comment]
我出现了同样的报错。docker rm/rmi了images之后重新装，之后我卸载重装了docker，再装试了还是没用。在这期间，网页竟然还能显示，只是格式错乱。上面说反代出了问题，好像不是。解决方法是重新安装nginx 1.22和php 7.4，完美 Y^^Y ！
上述手机显示错误目测也是nginx或者php版本问题。
@xzqiaochu @xxhjkl
