### ISSUE TITLE
[FR]增加一个开关，不限制历史消息数量

### ISSUE THREAD

**Issue by duhd1993** [Yidadaa/ChatGPT-Next-Web#189]
除非超出4096 token的限制，好像没有必要限制历史消息数量

另外
`historyMessageCount: number; // -1 means all`

测试了下，改成-1就没有历史消息了，与这里的注释不服。

**Comment by Yidadaa** [comment]
这样随便聊几句就会触发 openai 的 token 上限，没什么意义。
