### ISSUE TITLE
[Bug] 密码不能有全角字符，否则部署后可以登录但无法使用

### ISSUE THREAD

**Issue by zhanghaotianle** [Yidadaa/ChatGPT-Next-Web#1891]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
用户的访问密码，即CODE不能使用全角字符，否则部署完成后虽然可以登录成功，但使用时会报错。

**如何复现**
na

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
<img width="538" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/70092734/fb73f457-c1fd-427b-9405-f79cfb959144">

**一些必要的信息**
 - 部署方式： vercel

**Comment by Yidadaa** [comment]
请问哪个网站允许使用全角字符当密码？
