### ISSUE TITLE
[Feature] vercel替代方案

### ISSUE THREAD

**Issue by sansejin1206** [Yidadaa/ChatGPT-Next-Web#1892]
**Is your feature request related to a problem? Please describe.**
今天我尝试部署项目到4everland上，可是一直以下错误，官网dashboard.4everland.org希望作者出一个部署教程。
![33878Y(@VV7L5V1AM2K8M6Q](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/64347551/dfdb58af-c8f4-46e4-929e-1aed47bc8106)
![3`KVR{AW RF`QNWV` R7%QD](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/64347551/cdee2426-678a-4411-a0b6-df5e8c85565f)

**Comment by fh12** [comment]
> **Is your feature request related to a problem? Please describe.** 今天我尝试部署项目到4everland上，可是一直以下错误，官网dashboard.4everland.org希望作者出一个部署教程。 ![33878Y(@VV7L5V1AM2K8M6Q](https://user-images.githubusercontent.com/64347551/244933870-dfdb58af-c8f4-46e4-929e-1aed47bc8106.png) ![3KVR{AW RFQNWV` R7%QD](https://user-images.githubusercontent.com/64347551/244933807-cdee2426-678a-4411-a0b6-df5e8c85565f.png)
哈喽 请问下最后解决了吗
