### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.  报这个错是啥问题

### ISSUE THREAD

**Issue by lhrbest** [Yidadaa/ChatGPT-Next-Web#1903]
You exceeded your current quota, please check your plan and billing details.

**Comment by ClarenceDan** [comment]
账号余额过期了，去openai官网自行查看吧

**Comment by JXQI** [comment]
直接访问chatgpt没问题的

**Comment by shateng** [comment]
https://platform.openai.com/account/usage   Free trial usage ：Expired   免费送的api过期了
