### ISSUE TITLE
[Bug] 设置密码不起作用，必须输入Key才能用，输入Key后密码为空也能用。

### ISSUE THREAD

**Issue by ixujue** [Yidadaa/ChatGPT-Next-Web#1905]
**Describe the bug**
按教程设置了密码不起作用，设置了CODE参数，首次打开会提示"请前往[登录]()页输入正确的访问密码，或者在[设置]()页填入你自己的 OpenAI API Key。"
输入了自己设置的密码还是会出现这样的提示，只有在Key中输入了可用的Key才可以，密码填不填没有影响。

**Expected behavior**

**Screenshots**
输入密码不输入Key的提示：
"请前往[登录]()页输入正确的访问密码，或者在[设置]()页填入你自己的 OpenAI API Key。"
```
{
  "error": {
    "message": "",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}
```

请问要怎么解决？

**Comment by Mydong** [comment]
> **Describe the bug** 按教程设置了密码不起作用，设置了CODE参数，首次打开会提示"请前往登录页输入正确的访问密码，或者在设置页填入你自己的 OpenAI API Key。" 输入了自己设置的密码还是会出现这样的提示，只有在Key中输入了可用的Key才可以，密码填不填没有影响。
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** 输入密码不输入Key的提示： "请前往登录页输入正确的访问密码，或者在设置页填入你自己的 OpenAI API Key。"
> 
> ```
> {
>   "error": {
>     "message": "",
>     "type": "invalid_request_error",
>     "param": null,
>     "code": "invalid_api_key"
>   }
> }
> ```
> 
> 请问要怎么解决？

你是不是没有理解这个要怎么用？

Key是必须的，没有你就用不了。

在这个基础上，如果你将key配置成了内置，则可以只用填写密码的形式，去使用这个内置的key。
否则，就是直接在前端自己输入自己的key。

**Comment by ixujue** [comment]
> 

部署的时候内置了Key，然后增加了CODE参数，用的时候密码处填对填错没有区别，所以我想问的是密码设置的问题。

**Comment by Yidadaa** [comment]
你的 api key 有问题。

**Comment by ixujue** [comment]
找到原因了，是我自己填参数名称的时候填错了字母……
OPENAI_API_KEY打成了OPEN_API_KEY，耽误大家时间了。
