### ISSUE TITLE
[Bug] An internal error occurred with Vercel.

### ISSUE THREAD

**Issue by wenwenwen888** [Yidadaa/ChatGPT-Next-Web#1909]
**Describe the bug**
自己修改过BASE_URL , 上周五都还能用
今天莫名就用不了了 , 问问题后一直在请求 , 然后就报错了
重新Redeploy也无用

**To Reproduce**
Vercel的Log
```
[POST] /api/openai/v1/chat/completions?nxtPpath=v1%2Fchat%2Fcompletions reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true
```

**Screenshots**
![QQ截图20230612142348](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17694586/340b3b9a-56c7-4100-aa28-efb4e4d57417)

**Comment by Yidadaa** [comment]
看起来是 vercel 的问题，请反馈给 vercel 官方。

**Comment by wenwenwen888** [comment]
换了Zeabur好了 , 还真是vercel 问题
