### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zfsncn** [Yidadaa/ChatGPT-Next-Web#1915]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**

聊天中出现如下错误，敬请专家们给予一些指点，谢谢：
"error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": null

**如何复现**
Vercel部署成功后，DOMAINS里打开聊天，输入Code密码，开始聊天就出现这样的错误。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
<img width="733" alt="截屏2023-06-12 17 46 07" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25717411/5aa5d12d-19f9-4ece-b1a3-faba30a2b782">

**一些必要的信息**
 - 系统：[macos 12]
 - 浏览器： [chrome, safari]
 - 版本： [20230612]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
号寄了，换一个。
