### ISSUE TITLE
[Feature] 可否在用户等待响应以及等待响应输出期间，禁用发送消息的行为

### ISSUE THREAD

**Issue by zlazlazl** [Yidadaa/ChatGPT-Next-Web#1918]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。
用户短时间内频繁发送，极易触发OpenAI对Key账号的限制

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。
可以参考官方的ChatGPT网站，也是响应限制发送的

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
你可以自己加，但还是鼓励使用 120 美元的账号。
