### ISSUE TITLE
[Feature] 讯息：Open ai的api 更新了 2023-06-13

### ISSUE THREAD

**Issue by Mydong** [Yidadaa/ChatGPT-Next-Web#1932]
[https://openai.com/blog/function-calling-and-other-api-updates](https://openai.com/blog/function-calling-and-other-api-updates)

Today, we’re following up with some exciting updates:

new function calling capability in the Chat Completions API
updated and more steerable versions of gpt-4 and gpt-3.5-turbo
new 16k context version of gpt-3.5-turbo (vs the standard 4k version)
75% cost reduction on our state-of-the-art embeddings model
25% cost reduction on input tokens for gpt-3.5-turbo
announcing the deprecation timeline for the gpt-3.5-turbo-0301 and gpt-4-0314 models
All of these models come with the same data privacy and security guarantees we introduced on March 1 — customers own all outputs generated from their requests and their API data will not be used for training.

**Comment by sagiwei** [comment]
`Function calling` is mind blowing

**Comment by chiyiliao** [comment]
Is it possible to allow self-entering API model names? Otherwise, if a new version of the model is released, we will have to wait for ChatGPT-Next-Web to be updated to use it.

**Comment by ecswang** [comment]
new models have been added, thanks to @suhipek

**Comment by Yidadaa** [comment]
#1929

**Comment by Yidadaa** [comment]
@chiyiliao 

Custom model provider will be supported later, I am working on it.
