### ISSUE TITLE
【单文件运行】解压即用的本地化 ChatGPT-Next-Web

### ISSUE THREAD

**Issue by sbwml** [Yidadaa/ChatGPT-Next-Web#1933]
在这个提交 https://github.com/Yidadaa/ChatGPT-Next-Web/commit/2a191aacb7d2d44de7c8cdd77b73e1f31651907f 发现 ChatGPT-Next-Web 原来可以直接导出静态文件的，这下不需要任何环境了，试了一下真的不要太方便，解压双击就运行

默认 3000 端口，自定义端口

```shell
  --port 8888
```

[chatgpt-next-426ce7f_linux_amd64.tar.gz](https://github.com/Yidadaa/ChatGPT-Next-Web/files/11740830/chatgpt-next-426ce7f_linux_amd64.tar.gz)
[chatgpt-next-426ce7f_linux_arm64.tar.gz](https://github.com/Yidadaa/ChatGPT-Next-Web/files/11740831/chatgpt-next-426ce7f_linux_arm64.tar.gz)
[chatgpt-next-426ce7f_windows_amd64.zip](https://github.com/Yidadaa/ChatGPT-Next-Web/files/11740834/chatgpt-next-426ce7f_windows_amd64.zip)

**Comment by sbwml** [comment]
缺点：他喵了个咪，用户端与 API 直连。。。在公网部署它不会在服务器上代理 API。。。

**Comment by Yidadaa** [comment]
急啥，二进制安装文件过两天我就集成到 ci/cd 里面自动发布了。

**Comment by jiangsasa** [comment]
你好，请问这个是怎么导出的呢，配置文件应该在哪里更改呢
