### ISSUE TITLE
[Bug] 用户自定义 api 接口，可导致网站内置的 key 暴露给用户

### ISSUE THREAD

**Issue by zjsxply** [Yidadaa/ChatGPT-Next-Web#1936]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用访问密码，自定义 api 接口，即可从 api 接口拿到 key。

用户用自己 key 的话就让他自定义 api 接口好了，但是网站本身的 key 能不走用户自定义的接口吗

**如何复现**

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：windows 10 [比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器：chrome [比如 chrome, safari]
 - 版本：20230614 [填写设置页面的版本号]
 - 部署方式：vercel [比如 vercel、docker 或者服务器部署]

**Comment by Yidadaa** [comment]
你再想想。

**Comment by zjsxply** [comment]
> 你再想想。

不知您是何意。我刚才测试过是可以拿到的，只要用户自行构建一个接口。

**Comment by Yidadaa** [comment]
你的访问码分发出去之后，是没有办法二次约束用户怎么使用访问码的，所以纠结你的访问码有没有被第三方 api 地址获取到是没有意义的，只要你不把 api key 告诉用户，就没什么大问题。

你要是不想让用户自定义接口地址，用这个环境变量：
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#hide_user_api_key-%E5%8F%AF%E9%80%89

**Comment by zjsxply** [comment]
> 你的访问码分发出去之后，是没有办法二次约束用户怎么使用访问码的，所以纠结你的访问码有没有被第三方 api 地址获取到是没有意义的，只要你不把 api key 告诉用户，就没什么大问题。
> 
> 你要是不想让用户自定义接口地址，用这个环境变量 `HIDE_USER_API_KEY ` ： https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#hide_user_api_key-%E5%8F%AF%E9%80%89

我想说的是用户只要有访问码，就可以拿到我的 API key。

步骤是：
1. 用户自建 API 接口
2. 用户自定义 API 接口地址，使用访问密码在网站上操作
3. 用户在自己 API 接口的日志中拿到网站内置的 API key

我不关心访问码是否泄露，也不关心用户的 API key 是否会被他所用的第三方 API 接口所泄露，但是我的 API key 我认为不该有可以规避的泄露风险。

期望的结果：
用户使用自己的 API key 时，自定义 API 接口生效；
用户使用访问密码时，只走网站内置接口 /api/openai

**Comment by Yidadaa** [comment]
自定义接口地址只会在前端被使用，不会

**Comment by Yidadaa** [comment]
请求的工作方式：
1. 用户在网页操作，发出请求，请求中携带网站访问码
2. 请求到达服务器，验证访问码是否正确
3. 如果正确，则替换为 openai api key，访问 openai 服务器
4. 返回请求。

当用户自定义了接口地址之后，上述流程变成了：
1. 用户操作网页，发出请求
2. 请求携带访问码，访问自定义接口地址

根本不会经过你的服务器，你的 api key 根本就不会被泄漏。

**Comment by zjsxply** [comment]
> 

哦哦我明白了，刚才仔细检查了一下测试过程发现确实是没发出去，谢谢作者解答
