### ISSUE TITLE
[Feature] gpt-3.5-turbo-16k已上线

### ISSUE THREAD

**Issue by chaosgpt** [Yidadaa/ChatGPT-Next-Web#1937]
请考虑添加最新的16k模型支持

<img width="1387" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/127708707/89bd7fc4-9630-4bdd-ad81-0ee48d9d9a1b">

**Comment by Yidadaa** [comment]
更新代码
