### ISSUE TITLE
[Bug] 自定义 API 接口地址后聊天报错 "Failed to fetch"

### ISSUE THREAD

**Issue by zjsxply** [Yidadaa/ChatGPT-Next-Web#1938]
**Describe the bug**

**To Reproduce**
将 `https://<domain>/v1` 填入作为 API 接口地址，可以查询余额，但聊天报错 `Failed to fetch`
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/54236626/11354685-97fa-47e0-9802-c586eaf60028)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/54236626/da0813f6-91eb-4800-adb3-78bf6fed7450)

将 `https://<domain>` 填入作为 API 接口地址，无法查询余额，聊天正常

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [x ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
首先你得确定 api 地址支持查询余额才行。

**Comment by zjsxply** [comment]
> 首先你得确定 api 地址支持查询余额才行。

复现过程已经表明 api 地址支持聊天且支持查询余额。

**Comment by Yidadaa** [comment]
@zjsxply 

你得看控制台的网络选项卡，看看网络请求成功没有，前端对余额查询做了缓存，就算查询失败也会展示缓存的结果。
