### ISSUE TITLE
[Bug] 长会话导出成image时生成的PNG图片失真严重无法查看

### ISSUE THREAD

**Issue by weathery** [Yidadaa/ChatGPT-Next-Web#1941]
**Describe the bug**
在Win10 22H2的Chrome浏览器下，比较长的会话记录导出成PNG格式图片时，图片内容失真严重，完全无法查看准确的文字。
比如：导出成的PNG图片大小超过1MB时，已经模糊不清了。为了排除个人操作系统环境因素干扰，已经使用照片、画图两个工具分别查看过，属于导出的PNG本身的压缩失真问题。

**To Reproduce**
会话中，对话次数超过80条（其中包括少数几次比较长的响应内容），导出预览正常，下载保存的图片失真严重。

**Expected behavior**
希望长的会话导出成图片时，可以正确查看图片里面的问题。

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by Yidadaa** [comment]
确实有这个问题，不过这么长的对话，导出来拿来干啥？

**Comment by weathery** [comment]
@Yidadaa 感谢回复！
我明白这个只是一个程序性能方面的问题，这个问题处理的优先级可以设置很低。
我也是今天突然遇到，的确导出长图的目的不明确，对我个人来说。

**Comment by Yidadaa** [comment]
如果需要分享超长对话，请选择分享到 sharegpt。
