### ISSUE TITLE
[BUG] 旧对文本话丢失

### ISSUE THREAD

**Issue by QAQQL** [Yidadaa/ChatGPT-Next-Web#1954]
**Describe the bug**
旧对文本话丢失/不显示

**To Reproduce**
1.新建对话项目
2.对话6~7次
3.滚轮上滚

**Expected behavior**

**Screenshots**
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/51136763/3023aaea-5e3d-4118-aeb4-78bacc18a396)
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/51136763/38082745-8038-4aae-833e-b4a08fd8737a)

**Deployment**
- [ ] Vercel

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [Firefox 115.0b4 (64 位)]
 - Version [
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/51136763/48863c25-fd22-49bb-9705-22d707e2c10e)
]
 - 
**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
1. 是否能在 chrome 中稳定复现？
2. 尝试是否能在 chrome/edge 浏览器上复现。

**Comment by Yidadaa** [comment]
确认为 bug，今晚修复。
