### ISSUE TITLE
[Bug] 控制台会报错

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#1956]
2个问题：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/adbaf766-f95e-42b0-b70e-33c2b0dd7753)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/565ee404-83d5-4ee6-96ac-ddfb807172f3)

**Comment by Yidadaa** [comment]
不用管它，上游库一直不修。
