### ISSUE TITLE
code受限的问题

### ISSUE THREAD

**Issue by zj23564** [Yidadaa/ChatGPT-Next-Web#196]
部署在vercel上，加入了code环境变量，使用英文逗号隔开。
最终使用的时候确实发现提示受限制了，然后让在设置页面填写code。这时候问题就来了，填写了code之后一样是受限制的。我确认再三code是没问题的。当然我也没发现设置页面哪里有保存按钮，我只能默认猜测是填写了code之后关闭设置页面就自动生效。

**Comment by Yidadaa** [comment]
请确认环境变量是否为全大写。

**Comment by zj23564** [comment]
> 请确认环境变量是否为全大写。

确认了，是大写，前后也无空格或者特殊字符。是不是我在设置页面里面直接填写后没有生效，因为确实没看到哪里有保存提示

**Comment by Yidadaa** [comment]
编辑环境变量之后需要重新部署才会生效，请确认。

**Comment by zj23564** [comment]
> 编辑环境变量之后需要重新部署才会生效，请确认。

确认了，是我的问题，不好意思，重新部署后只加入了CODE环境变量,key的环境变量没填写。
已经正常使用了，非常感谢
