### ISSUE TITLE
[Bug] 当文本过长时，历史消息未显示 History Message not Shown When Text is Long

### ISSUE THREAD

**Issue by JamesFlare1212** [Yidadaa/ChatGPT-Next-Web#1961]
**Describe the bug**

在Web页面中，当对话数量较多后，且文本框较长，就会出现文本框没法正常显示的情况。但是当切换别的页面，比如点击一下分享，设置等，先前没法加载的消息又能临时加载了。

最近的3条信息不管多长都能正常显示，导出页面勾选消息记录的消息也能显示。我猜是对用户页面外的消息有优化什么的，划出页面就不加载，省资源？然后这样的优化可能哪里有错误，导致重新回过去看那些长消息的时候没法正常显示。

When there are many conversations on a web page and the text box is long, the text box may not be displayed properly. However, when switching to other pages such as clicking on share or settings, messages that could not be loaded before can be temporarily loaded again.

Recently, the last three messages can be displayed normally no matter how long they are. The exported page also displays messages selected in message records. I guess there might have been some optimization for messages outside of the user's page so that they don't load when swiped out of view to save resources. However, this optimization may have caused errors which prevent normal display of those long messages when returning to them later.

**Screenshots**

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/107359951/7480cf2e-8b1a-41fb-b54e-0e10ae0dc950)

**Deployment**

Docker

**Desktop (please complete the following information):**

Windows 11 Edge 114.0.1823.43

**Comment by Yidadaa** [comment]
重复：#1954
