### ISSUE TITLE
[Feature] Add Wrap Text option

### ISSUE THREAD

**Issue by AncientCatz** [Yidadaa/ChatGPT-Next-Web#1962]
**Is your feature request related to a problem? Please describe.**
I'm having a hard time reading the text inside the code block because there is no wrap text option.

**Describe the solution you'd like**
Add a wrap text option for the text inside the code block to make the text easier for users to read.

**Describe alternatives you've considered**
Um, nothing.

**Additional context**
![Screenshot_2023-06-14-19-53-56-612_com lemurbrowser exts](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/69200720/70eb1fdf-ead9-4703-ac80-418919371560)

**Comment by Yidadaa** [comment]
maybe we should enable wrap text by default on mobile screen? i will add this feature later.

**Comment by AncientCatz** [comment]
> maybe we should enable wrap text by default on mobile screen? i will add this feature later.

Thanks for that! I really appreciate it.

**Comment by Yidadaa** [comment]
I tried to enable line breaks, but it looked very strange when reading the code. So I think it's better not to enable it. 

For your scenario, if you need to enable line breaks, you can use the prompt:
> Do not use code block to wrap the reply, just return it in plain text format.

Alternatively, you can manually modify this part of the forked project and delete this line of code:
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/9d1a84858cdd9e0c3567f54940da51c73a763b57/app/styles/markdown.scss#L826

**Comment by AncientCatz** [comment]
> I tried to enable line breaks, but it looked very strange when reading the code. So I think it's better not to enable it.
> 
> For your scenario, if you need to enable line breaks, you can use the prompt:
> 
> > Do not use code block to wrap the reply, just return it in plain text format.
> 
> Alternatively, you can manually modify this part of the forked project and delete this line of code:
> 
> https://github.com/Yidadaa/ChatGPT-Next-Web/blob/9d1a84858cdd9e0c3567f54940da51c73a763b57/app/styles/markdown.scss#L826

Can you show me the screenshot?
Regarding the prompt, I've tried not to use a code block. But ChatGPT doesn't follow the prompt and instead explains what I input.

**Comment by Yidadaa** [comment]
What screenshot do you need? Prompt, Code or ...?

**Comment by AncientCatz** [comment]
> What screenshot do you need? Prompt, Code or ...?

Code block with line breaks enabled.

**Comment by Yidadaa** [comment]
In chat:

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/59fa7749-8fdc-48fa-a656-ff92a245c76a)

**Comment by Yidadaa** [comment]
You can just fork this project, and delete that line of code, and deploy it on Vercel, and you will get your personalized web ui.
