### ISSUE TITLE
[Bug] TypeError: RequestInit: duplex option is required when sending a body.

### ISSUE THREAD

**Issue by App1ePine** [Yidadaa/ChatGPT-Next-Web#1963]
更新20230614版本
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/116413749/bdce3756-4aa5-4739-a36f-89d4cdf76289)

**Comment by Yidadaa** [comment]
部署方式？

**Comment by App1ePine** [comment]
你好。部署方式是本地部署。
git pull upstream main.
pnpm install
pnpm build
pnpm start

**Comment by Yidadaa** [comment]
nodejs 版本？操作系统版本？

**Comment by App1ePine** [comment]
➜  ~ neofetch
       _,met$$$$$gg.          root@digitalOcean
    ,g$$$$$$$$$$$$$$$P.       -----------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64
 ,$$P'              `$$$.     Host: Droplet 20171212
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-11-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 25 days, 19 hours, 43 mins
 $$P      d$'     ,    $$P    Packages: 410 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: zsh 5.8
 $$;      Y$b._   _,d$P'      Resolution: 1024x768
 Y$$.    `.`"Y$$$$P"'         Terminal: /dev/pts/0
 `$$b      "-.__              CPU: DO-Premium-AMD (2) @ 1.996GHz
  `Y$$                        GPU: 00:02.0 Red Hat, Inc. Virtio GPU
   `Y$$.                      Memory: 393MiB / 1982MiB
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
➜  ~ node -v
v20.2.0
➜  ~ pnpm -v
8.6.0

不知道是否是我之前安装了 sharp 包导致的，刚才删除仓库从新拉取打包运行没有复现这个问题了

**Comment by LazyYangi** [comment]
同问 node v16.20.0
[centos-7]

**Comment by Yidadaa** [comment]
项目最低 nodejs 版本为 node18。
