### ISSUE TITLE
历史对话无法查看消息 

### ISSUE THREAD

**Issue by Rhm12345** [Yidadaa/ChatGPT-Next-Web#1971]
对话大概10来次之后，翻滚到最开始的历史对话 无法查看信息 
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/76574849/682aa654-c263-4306-9d42-9292627939af)
 - 部署方式：docker部署 
 - 版本：最新版本
 - 浏览器：chrome
 - 系统：windows10
可以重现的。

**Comment by Dmw9527** [comment]
是的这个问题我也遇到了，我以为是设置附带历史消息数太少的问题，但是调多了也是那样，偶尔上拉停一会才能显示，这个问题我觉得还是影响很大的。希望可以优化一下

**Comment by Rhm12345** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yidadaa** [comment]
@Rhm12345 拉取最新镜像重新部署。

@Dmw9527 这是懒加载优化，如果不这样聊天界面会卡死，没有什么优化空间了。
