### ISSUE TITLE
[Bug] 历史对话无法查看消息（可能是响应式窗口的问题）

### ISSUE THREAD

**Issue by Mydong** [Yidadaa/ChatGPT-Next-Web#1975]
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1971

这个反馈的问题，今天也遇到了。

昨天更新的这个版本出现的比较频繁。
原来虽有遇到，但是扥过一会总归会加载出来。
昨天的镜像更新后，包括刚刚重新拉取了一下。等了好久，都没有出不来历史记录。

───────────

然后，本来调出工具箱看下网络响应。
结果发现，加载不出来的，刷新后加载出来了。于是，就看原因，发现。
没有开发者工具箱时（即全屏状态就会出现这个问题）。
有的时候，历史消息就出来了。o(╯□╰)o

以下是截图：
1. 全屏下───────────没有历史消息
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/a5e76194-6be4-40e8-90b6-78e371ff4bfd)
2. 调出开发者工具箱，刷新───────────历史消息就出现了（关闭工具箱，又没有了）
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/f05aac13-2b12-48cc-8851-4442400afa75)
备注：
尤其是，控制台在侧边的时候。刷新一定会出现历史消息。
但是在，在底部的时候，需要刷新两次，就会出现了。
然后，关闭控制台刷新，又没有历史消息了。

2.1 补充个动图，有控制台情况下，如果在已经加载出历史消息的情况下，如果在从底部回到顶部。则消息还是会消失，这是后，调整下窗口又出现了😂😂
![GIF 2023-06-15 11-28-48](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/83872e95-cbc5-44b1-9a4d-0061c057a98a)

**Comment by Yidadaa** [comment]
版本？

**Comment by Yidadaa** [comment]
你们反馈问题都不看我写的 issue 模版的吗？

**Comment by Mydong** [comment]
> 版本？

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/0fb45ac1-654d-40ed-922d-4aafb4218349)

重新部署了一遍，已经解决。不在出现反馈情况。
填了模板，问题复制过来的时候，给覆盖了😂。以后会注意。根据模板填写。

已经解决
