### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zzkzs01** [Yidadaa/ChatGPT-Next-Web#1976]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在聊天机器人返回详情链接时，url总是会包含句尾的句号，导致直接点击url链接跳转，跳转页面总是404。

**如何复现**
输入问题：“Spring PetClinic” ；“Spring Cloud GCP Samples”等都能得到url有问题的回答。

**截图**
这里github解析问题，无法上传。

**一些必要的信息**
 - 系统：Windows 10
 - 浏览器： Edge 114.0.1823.43 (正式版本) (64 位)
 - 版本： 20230526
 - 部署方式：我是用户，不清楚部署者的部署方式

**Comment by Yidadaa** [comment]
markdown 解析的正常行为，自己想办法用 prompt 去纠正或者避免。
