### ISSUE TITLE
[Bug] 使用了你们的代理地址，经常报错，https://chatgpt1.nextweb.fun/api/proxy

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#1979]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/26560575-d038-427d-8c85-0fe8c39f0c9c)

**Comment by vual** [comment]
[Base Url] https://chatgpt1.nextweb.fun/api/proxy
[OpenAI]   [TypeError: fetch failed] {
  cause:  [Error: read ECONNRESET] {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by Yidadaa** [comment]
那就不用，自己找个其他的换上。
