### ISSUE TITLE
Error: 由于权限不足，导致同步失败（这是预期的行为），请前往仓库首页手动执行[Sync fork]。[Bug] 

### ISSUE THREAD

**Issue by dand0285** [Yidadaa/ChatGPT-Next-Web#1980]
Error: 由于权限不足，导致同步失败（这是预期的行为），请前往仓库首页手动执行[Sync fork]。
如何sync fork？

**Comment by Yidadaa** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
