### ISSUE TITLE
[Feature] Please support RWKV 

### ISSUE THREAD

**Issue by xiaol** [Yidadaa/ChatGPT-Next-Web#1984]
Please add RWKV to model config settings.

You can try RWKV world 7B from RWKV runner https://github.com/josStorer/RWKV-Runner, 
and this project natively support openai API format

FYI:
<img width="261" alt="微信图片_20230613001354" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1669515/5415b545-be7a-4112-98f4-d8623d9b19ad">
![微信图片_20230613001434](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1669515/01d3b829-f9f7-4c22-b73f-9439f20c1d8f)
![微信图片_20230613001430](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1669515/991a51fc-d127-4575-a15f-5880e5dfe400)

**Comment by Yidadaa** [comment]
<img width="1141" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/5782171f-6cf6-4a74-9977-2799c697abce">
