### ISSUE TITLE
docker 一直打包失败是什么原因

### ISSUE THREAD

**Issue by DemonRR** [Yidadaa/ChatGPT-Next-Web#199]
> [deps 4/4] RUN   if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   else echo "Lockfile not found." && exit 1;   fi:                                      
#0 0.526 yarn install v1.22.19                                                                        
#0 0.549 warning package.json: License should be a valid SPDX license expression                      
#0 0.652 warning chatgpt-next-web@1.1: License should be a valid SPDX license expression              
#0 0.653 [1/4] Resolving packages...                                                                  
#0 7.875 warning @svgr/webpack > @svgr/plugin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
#0 120.9 error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
#0 120.9 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
Dockerfile:11
--------------------
  10 |     
  11 | >>> RUN \
  12 | >>>   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  13 | >>>   elif [ -f package-lock.json ]; then npm ci; \
  14 | >>>   else echo "Lockfile not found." && exit 1; \
  15 | >>>   fi
  16 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   else echo \"Lockfile not found.\" && exit 1;   fi" did not complete successfully: exit code: 1

**Comment by AprilNEA** [comment]
`docker`镜像需要被重新打包

**Comment by nephen** [comment]
就是构建的时候报错，有没有最新的docker镜像呀

**Comment by realskyrin** [comment]
Railway 部署遇到同样 error
<img width="898" alt="image" src="https://user-images.githubusercontent.com/16552732/228788805-9854e75d-b4d5-4e17-b88c-61c993678ea6.png">

**Comment by coolestowl** [comment]
A not-so-correct workaround is to remove the '--frozen-lockfile' from the yarn line in the Dockerfile and then build the image.

**Comment by DemonRR** [comment]
1.7.1我怎么也docker构建打包失败呀

**Comment by nephen** [comment]
> A not-so-correct workaround is to remove the '--frozen-lockfile' from the yarn line in the Dockerfile and then build the image.

can u build it successful?

**Comment by nephen** [comment]
docker pull nephen2023/chatgpt-next-web:v1.7.1

**Comment by coolestowl** [comment]
> > A not-so-correct workaround is to remove the '--frozen-lockfile' from the yarn line in the Dockerfile and then build the image.
> 
> can u build it successful?

yeah, I was able to build successfully after deleting the '--frozon-lockfile' in Dockerfile, but this behavior should not be recommended.

**Comment by Yidadaa** [comment]
Have updated Dockerfile, 已经更新了 Dockerfile
