### ISSUE TITLE
[Feature] Support More Tauri API

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#1994]
https://tauri.app/v1/api/js/

- replace `window.prompt` and `window.confirm` with dialog api;
- replace `copy/write` with clipboard api;
- replace download with dialog api (save to file).

**Comment by daiaji** [comment]
不知道是否是实现引起的问题，我在安卓版firefox上使用时ChatGPT-Next-Web 时，会发生有时候无法通过长按复制的问题。
