### ISSUE TITLE
[Bug] Vercel发布时，Building日志中有错误，上线后网络请求有个脚本找不到

### ISSUE THREAD

**Issue by ktangel** [Yidadaa/ChatGPT-Next-Web#1995]
**描述问题**
发布Vercel的building这一步时，会有一段错误：

```
./app/config/build.ts

10:53:18.365 | Module not found: Can't resolve 'child_process' in '/vercel/path0/app/config'
```
部署上线后，在开发者控制台的网络标签的请求记录里，会有一个请求的.js脚本地址是返回的404：

https://***域名****/_vercel/insights/script.js

不知道是不是build时的错误导致少生成了这个js文件。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：windows
 - 浏览器：edge
 - 版本：20230614
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
正常现象，不影响使用。
