### ISSUE TITLE
[Bug] 聊天记录早先的提问和结果丢失

### ISSUE THREAD

**Issue by ktangel** [Yidadaa/ChatGPT-Next-Web#1996]
**描述问题**

聊天记录聊上一些后，前面聊的记录会丢失一部分，有时候切换几次又会复原，有些又不会，一直是空的

**如何复现**

新开一个聊天，聊上一段对话后，切换到另一个聊天，再回来对话，或者对话途中切去别的程序一段时间再回来，往上找之前的提前和回答就会如截图那样没有消息

**截图**

![1686885233954](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11548772/5631f0da-aeae-4bc1-8096-dc8b575b3e78)
![1686885269281](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11548772/de896bc3-d4cd-4f99-8e00-c11250d022be)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器： Edge
 - 版本： 20230614
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
升级代码到最新。
