### ISSUE TITLE
非常喜欢这个项目，简便快捷，但有一些建议

### ISSUE THREAD

**Issue by echostars** [Yidadaa/ChatGPT-Next-Web#2]
感谢您创建这个项目，非常喜欢您的设计，因为工作的关系，我没有很多功能的开发能力。我使用过很多chatgpt项目，对比其他项目，我在使用中发现一些问题，想要向您请求一些意见：
1. 是否可以加入页面密码功能
2. 是否有加入prompt列表功能的计划
3. 代码部分是否可以加入颜色美化，light或dark模式
4. AI回复过程中是否可以加入停止或者重新生成的按钮
5. 在Enter输入过程中，没有其他快捷键换行
6. 查询API余额功能

**Comment by Yidadaa** [comment]
感谢反馈，这些功能之后会陆续加入。优先级：2 > 4 > 1 > 6，至于：
- 第 3 点，现在有代码 highlight，并且区分了 light / dark 模式，不过这依赖于 chatgpt 返回的 code block 是否标注了代码语言，如果没有标注代码语言，那就默认没有 highlight，默认黑底白字；
- 第 5 点，设置界面中提供了多种换行键，请查看是否能满足需求。

**Comment by echostars** [comment]
> 感谢反馈，这些功能之后会陆续加入。优先级：2 > 4 > 1 > 6，至于：
> 
> * 第 3 点，现在有代码 highlight，并且区分了 light / dark 模式，不过这依赖于 chatgpt 返回的 code block 是否标注了代码语言，如果没有标注代码语言，那就默认没有 highlight，默认黑底白字；
> * 第 5 点，设置界面中提供了多种换行键，请查看是否能满足需求。

谢谢，我今天又试了试代码highlight，不知道同样输出昨天黑底白字咋触发的，现在可以正常使用了。
然后设置里的换行，在Enter发送的模式下，无法使用*+Enter进行换行；在*+Enter发送的模式下，可以使用Enter换行。

**Comment by Yidadaa** [comment]
@echostars 

Enter 换行的问题已经修复，在 Enter 模式下，使用 Shift + Enter 即可触发换行。

**Comment by Yidadaa** [comment]
@echostars 

如果你是用 vercel 部署，可以在自己仓库里找到这个同名项目，然后参考\[说明\](https://github.com/Yidadaa/ChatGPT-Next-Web#%E4%BF%9D%E6%8C%81%E6%9B%B4%E6%96%B0-keep-updated)同步代码。

**Comment by echostars** [comment]
> @echostars 
> 
> 
> 
> 如果你是用 vercel 部署，可以在自己仓库里找到这个同名项目，然后参考[说明](https://github.com/Yidadaa/ChatGPT-Next-Web#%E4%BF%9D%E6%8C%81%E6%9B%B4%E6%96%B0-keep-updated)同步代码。

谢谢

**Comment by Cp0204** [comment]
> 感谢您创建这个项目，非常喜欢您的设计，因为工作的关系，我没有很多功能的开发能力。我使用过很多chatgpt项目，对比其他项目，我在使用中发现一些问题，想要向您请求一些意见：
> 
> 1. 是否可以加入页面密码功能
> 2. 是否有加入prompt列表功能的计划
> 3. 代码部分是否可以加入颜色美化，light或dark模式
> 4. AI回复过程中是否可以加入停止或者重新生成的按钮
> 5. 在Enter输入过程中，没有其他快捷键换行
> 6. 查询API余额功能

迫切需要1，不然像裸奔，链接泄露出去很容易一下就刷完了。

**Comment by Yidadaa** [comment]
这两天会更新这个功能。

**Comment by kevins0116** [comment]
I really like this project. It would be great if you could add user login. Could you provide me with a tutorial for compiling it locally?

**Comment by HanyangLin** [comment]
> > 感谢您创建这个项目，非常喜欢您的设计，因为工作的关系，我没有很多功能的开发能力。我使用过很多chatgpt项目，对比其他项目，我在使用中发现一些问题，想要向您请求一些意见：
> > 
> > 1. 是否可以加入页面密码功能
> > 2. 是否有加入prompt列表功能的计划
> > 3. 代码部分是否可以加入颜色美化，light或dark模式
> > 4. AI回复过程中是否可以加入停止或者重新生成的按钮
> > 5. 在Enter输入过程中，没有其他快捷键换行
> > 6. 查询API余额功能
> 
> 迫切需要1，不然像裸奔，链接泄露出去很容易一下就刷完了。

1. 最好能加上使用量限制。

**Comment by Yidadaa** [comment]
访问控制功能已经更新，请查阅文档。

**Comment by bohanyang** [comment]
请问设置页面在哪里输入授权码？

**Comment by Yidadaa** [comment]
已经增加停止、重试按钮，请更新 v1.3 版本。

**Comment by tiwentichat** [comment]
这个prompt列表可以放在最左面嘛？使用过一个类似的，也挺好的，但是是在输入框里面上下划拉的，实际使用不是那么方便。左侧空白区域，同时可以显示4-5个，然后下拉展开，不至于和输入框放一起
