### ISSUE TITLE
已经是最新代码了，还是一直提示更新怎么回事

### ISSUE THREAD

**Issue by ruixing1001** [Yidadaa/ChatGPT-Next-Web#20]
刚fork您的这个，但是还是提示要更新

**Comment by Yidadaa** [comment]
能否提供一下部署链接，如果不想公开，可以通过我主页的邮箱发送给我。

**Comment by Yidadaa** [comment]
看了下你 fork 的项目，发现你提交了新的 commit，这个的确会导致你的版本和远程版本不匹配，然后就会一直提示更新。

**Comment by ruixing1001** [comment]
可是我刚刚试了下重新部署的也提示更新，什么都没修改，部署链接我邮箱发您

**Comment by ruixing1001** [comment]
应该怎么操作才能不提示更新呢

**Comment by Yidadaa** [comment]
看了一下，应该是 fork 的方式不对。

请尝试以下操作：
1. 删除掉你现有的 repo；
2. 在本项目页面上，点 fork 按钮，fork 一份到你名下；
3. 去 vercel，先把原来的 vercel 项目删了
然后选择新建项目，从 github repo 新建，然后选取刚刚 fork 出来到你名下的那个项目，填入环境变量等部署完成。

上述操作全程不需要命令行操作，不要 push 任何修改到 fork 后的项目中，应该就没问题了。

**Comment by ruixing1001** [comment]
感谢感谢，按照这个步骤就没问题了，不过确实按照介绍上的一键部署，会一直提示哦

**Comment by Yidadaa** [comment]
好的，感谢反馈，稍后我会同步到文档里去，推荐大家使用 fork 的方式部署。
