### ISSUE TITLE
[Bug] 字数总是被限制

### ISSUE THREAD

**Issue by lucasjinreal** [Yidadaa/ChatGPT-Next-Web#2011]
已经设置了max tokne lenght 到 3000

回复总是终端

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/21303438/b8cc5d43-7e29-4ac2-9835-491630bcb70a)

测试的是本地的llamap cpp模型，我用ansor的前端就不会有这个问题，是参数设置的问题吗，应该如何匹配原始的参数

**Comment by Yidadaa** [comment]
提供控制台截图，本地 llama 侧截图。

**Comment by lucasjinreal** [comment]
我这边用的是桌面版

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/21303438/08f86a30-af6b-4990-84c5-098ad2d9f13b)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/21303438/985ddadf-fbaa-42cb-aa2a-e2801c588cea)

一样的后台，可能是参数的问题，但后台的确是一样的，anse比较符合预期

**Comment by Yidadaa** [comment]
@lucasjinreal 

目前 max_tokens 参数其实不会真的传到服务端，因为之前用户经常反馈该参数会导致 token 超限，可以看一下自己 llama 服务端有没有对 max_token 设置默认值。

此外，你可以直接在网页版里设置接口地址，用法与客户端是一致的，这样你可以在控制台查看有没有报错信息。

**Comment by Yidadaa** [comment]
@lucasjinreal 

不需要加 v1，能提供一下前端控制台截图吗？最好能包含控制台网络选项卡这个请求的截图。

**Comment by Yidadaa** [comment]
这种问题一般有两种可能的情况
1. 无法直接访问到这个 ip，如果你在使用本地客户端，你需要确认是否能直连该 ip（而不是透过任何本地代理）；如果你在使用本项目的演示站点，在浏览器里将代理启用到全局模式，然后再测试一次；
2. ip 没有启用跨域，浏览器拦截了。

具体的原因必须提供详细的控制台报错截图才能确定。

**Comment by lucasjinreal** [comment]
@Yidadaa 你好，这个ip我从终端curl时没有问题的。
怎么开启控制台调试呢，我用的是desktop app

**Comment by Yidadaa** [comment]
@lucasjinreal 

先用项目的演示站点测试一下，在设置界面修改“接口地址”为你要测试的地址，修改后请求是在你的浏览器中发出的，不用担心会泄漏。

终端 curl 无法代表真实情况，curl 会走你的 http_proxy 代理，但是目前客户端并不会主动读 http_proxy。
