### ISSUE TITLE
能否通过加入环境变量的方式增加对gpt4 api的支持

### ISSUE THREAD

**Issue by y22emc2** [Yidadaa/ChatGPT-Next-Web#2014]
如题
能否通过加入环境变量的方式增加对gpt4 api的支持；
想着把gpt 4的api key以环境变量的方式集成到里面/web内能集成多个chatgpt api key这样就不用麻烦一个key额度用完一直切来切去的了

**Comment by dockercore** [comment]
不能，因为openai API有校验

**Comment by Yidadaa** [comment]
可以做，但是不会做。
