### ISSUE TITLE
cloudflare提示Internal Server Error[Bug] 

### ISSUE THREAD

**Issue by ziluobu** [Yidadaa/ChatGPT-Next-Web#2019]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
不好意思qq群满了，本来要在那反馈的，发现进不去。
问题现象是，我根据你的文章在cloudflare部署成功，访问页面能打开了，但是和chat对话提示Internal Server Error，不知原因为何。
**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
<img width="939" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/5415871/7f9978ea-be12-4f36-98ad-e2b9e40597ae">
<img width="1164" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/5415871/5b6f593a-efcf-48a2-bc5e-f42c809232c9">
<img width="844" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/5415871/dcda0810-628e-4738-b9e3-95b3527e6d2a">

**Comment by ludy520** [comment]
遇到相同的问题

**Comment by Yidadaa** [comment]
请使用 vercel，然后再用 cloudflare 加速，直接在 cf 部署非常麻烦。

**Comment by ludy520** [comment]
vercel很尴尬，设置了BASE_URL后也是有问题，除非是在设置里面另外设置API接口地址，但是这样是不是被人可以看到了？

**Comment by Yidadaa** [comment]
@ludy520 肯定是你的环境变量格式设置错了，仔细检查一下，不要带 v1。
