### ISSUE TITLE
[Feature] 像chatgpt官网一样能编辑对话

### ISSUE THREAD

**Issue by quzard** [Yidadaa/ChatGPT-Next-Web#2022]
gpt经常需要不断调整对话进行调优，希望可以像chatgpt官网一样能编辑对话

**Comment by Yidadaa** [comment]
使用重试按钮。

**Comment by Yidadaa** [comment]
右键点击消息可以快速复制消息内容

**Comment by daiaji** [comment]
> 右键点击消息可以快速复制消息内容

现在主要是删除后再编辑很麻烦。
然後手动编辑assistant的输出对于调教来说还是比较有帮助。
