### ISSUE TITLE
对话内容正确显示数学表达式

### ISSUE THREAD

**Issue by edisonzf2020** [Yidadaa/ChatGPT-Next-Web#2023]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
尽管告诉我们。
经常咨询gpt一些数学类的知识，输入数学公式，它可以看懂，但是显示不是正确的数学公式
比如以下数学表达式：
{\displaystyle \operatorname {E} [X]=\sum _{i=0}^{1}x_{i}f_{X}(x)=0+p=p}

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。
bing可以显示
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/95912883/743f44ab-d437-44b9-ae21-257aeebf51ff)

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/6af80bc4-3a1d-46fa-a059-6410ffe40a54)
