### ISSUE TITLE
[Feature] Scrolling snapping to the bottom makes it hard to navigate

### ISSUE THREAD

**Issue by chen-rn** [Yidadaa/ChatGPT-Next-Web#2025]
See [video](https://imgur.com/a/gIch3jQ) here.

When you are close to the bottom of the scroll, there is a mechanism that makes the scrollbar snap to the bottom. I assume this is an intended behavior but it makes it difficult to read longer texts.

**Comment by reece00** [comment]
我没有出现这个功能，但说起来我手机上浏览出现出文字时聊天框一直重复定位到某个位置，重新进入对话后才停止。我感觉这更像是bug
