### ISSUE TITLE
无法下载到本地呢？

### ISSUE THREAD

**Issue by andyjxli** [Yidadaa/ChatGPT-Next-Web#203]
最新部署的无法安装到本地呀？

**Comment by AprilNEA** [comment]
能否提供消息报错信息

**Comment by andyjxli** [comment]
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/19701675/228848417-c4a7ad14-75cc-4063-8bc5-ff6cdd23c69a.png">
只有这一行错误，目测不是这个问题。我打开其他人之前部署的网站是可以的下载的。我今天部署的就无法下载～

**Comment by andyjxli** [comment]
> 

是的，无法使用 pwa 程序
