### ISSUE TITLE
关于代理的问题

### ISSUE THREAD

**Issue by hlcen66** [Yidadaa/ChatGPT-Next-Web#2036]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我在centos系统中启动了项目，访问提示如下：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/81564338/7131ae2e-d0ed-427e-82f7-2a7dbe5f9f8b)

我的启动命令如下：
docker run -d --name chatgpt-next-web -p 3000:3000 -e OPENAI_API_KEY="sk-X********GOc3zMail2UBeb6W1qw" -e CODE="666666" -e PROXY_URL="http://127.0.0.1:7890" -e HOSTNAME=127.0.0.1 yidadaa/chatgpt-next-web

我的代理开启截图如下：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/81564338/8883babe-4e18-4ede-989e-aed50573d317)

请问如何解决，请大佬支招

**Comment by Yidadaa** [comment]
你截图里里面显示，你的代理端口是 7891，而不是 7890。

**Comment by hlcen66** [comment]
> In order to improve communication efficiency, we have set up official QQ groups and QQ channels. If you encounter any problems during use or construction, please join the group or channel for consultation and solve them as soon as possible, unless it is a bug that can be reproduced stably or More creative feature suggestions, otherwise please do not send low-quality meaningless posts to the Issue area.

7890和7891都试过了，结果是一样的

**Comment by hlcen66** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> Your screenshot shows that your proxy port is 7891, not 7890.

i tryed 7890 and 7891 ,the result is same

**Comment by hlcen66** [comment]
> 你截图里面显示，你的代理端口是 7891，而不是 7890。

2个都试过了，结果是一样的。

**Comment by lxk955** [comment]
Add the --network host argument to use the host's network.
