### ISSUE TITLE
[Bug] {"error":true,"msg":"you are not allowed to request v1/completions"}

### ISSUE THREAD

**Issue by skzhengkai** [Yidadaa/ChatGPT-Next-Web#2037]
**Describe the bug**
When trying to access v1/completions, I'm presented with the error: `{"error":true,"msg":"you are not allowed to request v1/completions"}`

How do I fix this?

**Comment by Yidadaa** [comment]
For security reasons (there is a major vulnerability in OpenAI's authentication mechanism, which I previously reported to them but was not taken seriously), I have set up a whitelist mechanism in the project to ensure that others cannot steal your account permissions. You can manually add the path you want to access here: 

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/89717c9b1513357dac066963320589ff93891fd1/app/constant.ts#L50
