### ISSUE TITLE
docker24依然无法拉取[Bug] 

### ISSUE THREAD

**Issue by TenXLL** [Yidadaa/ChatGPT-Next-Web#2039]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/131734492/2f32bb58-3a36-44b9-b871-aa7b78204467)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/131734492/85076acf-0ebe-427a-af56-f74598d5a639)

**Comment by Bisstocuz** [comment]
你的问题

**Comment by Yidadaa** [comment]
换个 docker 镜像源。
