### ISSUE TITLE
[Feature]  write multiple files from prompt

### ISSUE THREAD

**Issue by Jarrodsz** [Yidadaa/ChatGPT-Next-Web#2041]
Nobody had thought of this idea before, so I'm posting it here. Either I must be a genius, or the rest of the people haven't thought of it yet.

Here's the proposal: within the plugin's features, add an option to write multiple files to the disk. This feature would be particularly useful when running locally on a development machine.

Here's an example prompt:
"Write me a 1-page React todo app in TypeScript. Write all components to /components."

When the plugin is enhanced, it should generate files with filenames as descriptions and save them to disk based on instructions or plugin settings that are relevant to the conversation. For instance, you could choose a specific output path from the browser or define a string variable with the output path, such as /my.nextjs.app.path/. The plugin should then write all the output files accordingly.

If this feature doesn't exist yet, I highly believe it is needed not just by me, but also by other developers. Let's work together to make this happen quickly!

I also have some additional improvement ideas for the plugin:

1. Ask to store files after they have been written and reviewed, or provide an option for "auto store" to save the generated files directly.

2. Allow users to set paths for output files, giving them more flexibility in organizing their codebase.

3. Add modes for generating or refactoring codebases. The plugin could load an existing application file tree, such as a Next.js, Remix, or PHP project, and read and refactor the files. As a bonus, consider implementing a drag-and-drop functionality in the plugin's UI to facilitate code refactoring.

4. Implement a conversion mode, where code can be converted from one language (X) to another (Y) based on the provided prompt.

Let's collaborate and make this brilliant addition to the open-source project a reality!

**Comment by Yidadaa** [comment]
Great idea, but it seems more suitable to be developed as a new project, as file manipulation capabilities are not within the scope of this project.
