### ISSUE TITLE
[Feature] please add settings page with on/off for features

### ISSUE THREAD

**Issue by Jarrodsz** [Yidadaa/ChatGPT-Next-Web#2043]
In settings allow toggle on / off for features

like disable default templates
Prompts
Etc

show ui element x

To make it more customizable
Allow store of these in config file so dev can set custom config for ui🙏

**Comment by Yidadaa** [comment]
Not in plan, you can fork this project and implement it by your self.

**Comment by kisamoto** [comment]
@Yidadaa 

I would be interested in adding some environment variables to customize based on language.

Example use case: I am only an english speaker so I would like to disable the CN masks and prompts to clean up the UI as I will never need them.

If I was to implement this and open a pull request, would you merge it in?

Thank you.
