### ISSUE TITLE
[Bug] [OpenAI] [TypeError: fetch failed] { cause: [Error: AggregateError] }

### ISSUE THREAD

**Issue by sglxh** [Yidadaa/ChatGPT-Next-Web#2047]
ubuntu20 win10 edge浏览器访问 服务器部署 
页面打开后想使用chatgpt报错了
root@coal-pasi1cmp:/www/wwwroot/ChatGPT-Next-Web# PORT=3000 yarn start
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ next start
[Next] build mode standalone
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
[Next] build mode standalone
- warn "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
[Next] build mode standalone
- warn "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
[OpenAI Route] params  { path: [ 'v1', 'chat', 'completions' ] }
[Auth] allowed hashed codes:  []
[Auth] got access code: 
[Auth] hashed access code: d41d8cd98f00b204e9800998ecf8427e
[User IP]  112.xx.xx.xx
[Time]  6/19/2023, 3:50:32 AM
[Auth] use user api key
[Proxy]  v1/chat/completions?path=v1&path=chat&path=completions
[Base Url] https://api.openai.com
**[OpenAI]  [TypeError: fetch failed] { cause: [Error: AggregateError] }**

**Comment by Yidadaa** [comment]
服务器能直连 openai 吗？

**Comment by sglxh** [comment]
可以

**Comment by Yidadaa** [comment]
直连的意思是服务器本身在国外，确认？

另外把你的环境变量发一下，可以自行把敏感信息用星号打码。

**Comment by sglxh** [comment]
nodejs版本太高了，我改成18就好了
