### ISSUE TITLE
[Feature] I recommend that ChatGPT-Next_web supply more masks and a user interface that is more user-friendly, categorizing the various masks for easier navigation

### ISSUE THREAD

**Issue by heavenkiller2018** [Yidadaa/ChatGPT-Next-Web#2059]
I recommend that ChatGPT-Next_web supply more masks and a user interface that is more user-friendly, categorizing the various masks for easier navigation. For instance, there is a reference that offers up to 2915 prompts and groups them into a dozen categories.

[[AI 提示语 (tishi.top)](https://tishi.top/)](https://tishi.top/)

![2222 Screenshot 2023-06-20 081109](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45555611/f4075bda-9dde-431f-9989-f73110d0f485)

**Comment by yeenbean** [comment]
ChatGPT Next Web appears to be geared towards developers. It seems that the provided masks serve as examples to demonstrate the utilization of the ChatGPT API. If this is the case, is it necessary to include them?

If the future plan is to include more masks, then it would be appropriate to consider organizing them effectively. Having a large number of masks without proper organization can be overwhelming to scroll through. It could be implemented as a filter, similar to the existing language selection feature.

<img width="939" alt="Screenshot 2023-06-19 at 8 04 42 PM" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/7747985/a2160295-80a4-45a4-b328-af65d6ab74dd">
