### ISSUE TITLE
[Bug] 202306219版本 TypeError: RequestInit: duplex option is required when sending a body. 

### ISSUE THREAD

**Issue by Mydong** [Yidadaa/ChatGPT-Next-Web#2061]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
TypeError: RequestInit: duplex option is required when sending a body.

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/2a945b20-d4de-4bd4-85eb-2c072ea42e28)

**如何复现**
构建拉取20230619版本镜像后

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/4cf6901e-412d-47fb-bd99-9ccf1c8a5db5)

**一些必要的信息**
 - 系统：windows 11
 - 浏览器：chrome
 - 版本： 
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/838c4902-1dae-4b87-9e5c-fdebff0af72d)
 - 部署方式：Docker

**Comment by Mydong** [comment]
**相关信息：**
docker 安装，系统 Debian，node js版本v18.16.0
![6K$1MN1 4FNMVXF2YU8U_WC](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/6c32c668-bbd2-48c3-b7e4-fa942a2cc1df)


已经尝试解决的方法：
1. 重新拉取镜像
2. 删除仓库，重新fork仓库，构建镜像。
3. 去掉反代域名，使用ip:3000 方式访问尝试

均是上述错误

**Comment by Yidadaa** [comment]
我即将开始休端午假，如果有人有时间，可以帮忙修一下这个 bug，在下方代码处尝试增加 `duplex: half,` 即可：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/daeb8a67a38eca25565a387242eb1bf980aed88e/app/api/common.ts#L45
