### ISSUE TITLE
[Bug] 清除聊天失效了？我看点了清除聊天，还是会把历史消息一起发送过去。

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#2062]

**Comment by Yidadaa** [comment]
哪个清除聊天，清除上下文？

**Comment by vual** [comment]
> 哪个清除聊天，清除上下文？

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/dcc7f1e6-e545-4194-85ad-444bafc1dfad)
