### ISSUE TITLE
[Bug] [OpenAI]  [TypeError: Response body object should not be disturbed or locked]

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#2063]
这种打印报错是什么问题导致的？我用自己的代理地址。我用postman调用是没问题。

**Comment by vual** [comment]
直连openai的环境，聊天的时候也报这个错了

**Comment by vual** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/b675fa26-4adf-4284-9b64-b9d8307bccf9)

**Comment by vual** [comment]
nextjs上也有这个问题的讨论：https://github.com/vercel/next.js/discussions/49524

**Comment by vual** [comment]
问到一个解决方法，帮忙看看是否可行？

**Comment by Yidadaa** [comment]
自己改过代码？

**Comment by vual** [comment]
> 自己改过代码？

增加了请求打印日志，使用了 await req.text()；坑爹了，去掉了就好了，我的错。
