### ISSUE TITLE
gpt-3.5-turbo-16k 模型无法发送超过4k的长文本

### ISSUE THREAD

**Issue by jasontips** [Yidadaa/ChatGPT-Next-Web#2066]
我选择16k 模型，ui上也设置tokens为15.5K:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/130386594/b59877a4-42d4-448d-86b4-27bc66d87d65)

但是我发送长文本还是提示超限了：
{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, your messages resulted in 7603 tokens. Please reduce the length of the messages.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

如何才能正常发送16k的长文本？

**Comment by yushuaige** [comment]
确实，gpt-3.5-turbo-16k和gpt-3.5-turbo-0613-16k模型，输入3000个汉字就提示超了，换了别人的网站却可以正常发送。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11461928/08f4653d-f982-4c12-9842-b115293d483c)

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/d8a61d01-d3db-4919-bed6-3185da639deb)

**Comment by Yidadaa** [comment]
无法复现该问题。

**Comment by yushuaige** [comment]
> 确实，gpt-3.5-turbo-16k和gpt-3.5-turbo-0613-16k模型，输入3000个汉字就提示超了，换了别人的网站却可以正常发送。 ![image](https://user-images.githubusercontent.com/11461928/247128157-08f4653d-f982-4c12-9842-b115293d483c.png)

找到原因了，无意中发现的。

设置里面模型选择gpt-3.5-turbo-16k，
使用面具之后，聊天界面的模型会默认变成gpt-3.5-turbo，需要再手动修改一下。
不使用面具，点击“直接开始”没有这个问题。

使用面具：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11461928/da19c924-1b31-4ca4-8e71-460109557a6d)
直接开始：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11461928/f7274382-ee20-4975-b6da-2eb03837fa03)
