### ISSUE TITLE
[Bug] 选了模型，但是没有效果，我打印了请求内容

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#2068]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/b0f7a296-ea3a-493f-acd2-721d59ad6c70)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/ffed92c6-a53c-4fb1-a546-167c424e21a1)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/5a010a20-c778-491b-8a48-359260ce5f08)

**Comment by Yidadaa** [comment]
截图请求是自动总结标题的，用的固定模型。
