### ISSUE TITLE
[Bug] Setting `BASE_URL` does not work

### ISSUE THREAD

**Issue by Nauxscript** [Yidadaa/ChatGPT-Next-Web#2071]
**Describe the bug**
vercel 环境变量中设置了 `BASE_URL` `OPENAI_API_KEY` `CODE` 三个环境变量，但是，其中，`BASE_URL` 设置为 `https://api.chatanywhere.com.cn` 或 `https://api.chatanywhere.com.cn/v1` 均无法在部署后的页面正常使用；和这个类似 #1938 。

而若在设置页面中填入部署的页面的设置中设置 `接口地址` 为 `https://api.chatanywhere.com.cn`，并且再设置 `API Key`, 则可以使用；如果没有在设置页面再次设置 `API Key` 只设置 `接口地址`，也是无法使用（此时设置的 `API Key` 与环境变量的 `OPENAI_API_KEY` 是相同值）。

**To Reproduce**
1. 部署新的 vercel 项目
2. 设置 `BASE_URL` `OPENAI_API_KEY` `CODE` 三个环境变量

**Expected behavior**
正常使用

**Screenshots**
只设置 `BASE_URL` `OPENAI_API_KEY` `CODE` 三个环境变量的情况下：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/13010589/c84b8484-137d-4c38-bb89-5bd76854cad3)

设置了设置页面中的 `接口地址` 和 `API Key` 的情况下
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/13010589/8d8ba470-885f-4241-a083-fc76ee7704dd)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: MacOS 13.1
 - Browser chrome
 - Version 113.0.5672.63 (arm64)

大概在5月的时候还是正常的正常使用的（只设置`BASE_URL` `OPENAI_API_KEY` `CODE` 这三个环境变量），后续更新了版本后就无法使用了（大概两周前），今天突然想起重新又更新了最新代码部署，还是不行；

以及想请问一下设置页面的 `接口地址` 这一项是用于设置什么？以前好像没有注意到这个选项；默认的 `/api/openai/` 值又是代表什么呢？没有在文档中看到这个配置的描述。

最后感谢大佬的项目🎉

**Comment by Yidadaa** [comment]
/api/openai 是项目自带代理，将请求在 vercel 服务器上转发一次，并且可以通过访问码将 api key 隔离。

默认情况下，chatgpt 请求会访问 api/openai 到 vercel 服务器，然后校验访问码之后，注入 OPENAI_API_KEY，然后将请求发往 BASE_URL。

你修改了接口地址之后，所有请求会在浏览器测直接发往你设置的地址，不会经过服务器中转。

你的报错看起来是无法在 vercel 服务器上访问设定的 BASE_URL，正确格式是不加 v1，建议你咨询你的 api 中转服务商，确认服务能否在 vercel 服务器上使用。

**Comment by Nauxscript** [comment]
> /api/openai 是项目自带代理，将请求在 vercel 服务器上转发一次，并且可以通过访问码将 api key 隔离。
> 
> 默认情况下，chatgpt 请求会访问 api/openai 到 vercel 服务器，然后校验访问码之后，注入 OPENAI_API_KEY，然后将请求发往 BASE_URL。
> 
> 你修改了接口地址之后，所有请求会在浏览器测直接发往你设置的地址，不会经过服务器中转。
> 
> 你的报错看起来是无法在 vercel 服务器上访问设定的 BASE_URL，正确格式是不加 v1，建议你咨询你的 api 中转服务商，确认服务能否在 vercel 服务器上使用。

明白了，那个服务商的地址是在国内的，估计是 vercel 的代理发送请求到国内的服务上，可能是服务商做了什么限制；换成国外的服务地址能正常使用了，感谢回复！

**Comment by ludy520** [comment]
> > /api/openai 是项目自带代理，将请求在 vercel 服务器上转发一次，并且可以通过访问码将 api key 隔离。
> > 默认情况下，chatgpt 请求会访问 api/openai 到 vercel 服务器，然后校验访问码之后，注入 OPENAI_API_KEY，然后将请求发往 BASE_URL。
> > 你修改了接口地址之后，所有请求会在浏览器测直接发往你设置的地址，不会经过服务器中转。
> > 你的报错看起来是无法在 vercel 服务器上访问设定的 BASE_URL，正确格式是不加 v1，建议你咨询你的 api 中转服务商，确认服务能否在 vercel 服务器上使用。
> 
> 明白了，那个服务商的地址是在国内的，估计是 vercel 的代理发送请求到国内的服务上，可能是服务商做了什么限制；换成国外的服务地址能正常使用了，感谢回复！

那服务商是国内的，怎么处理的？

**Comment by Nauxscript** [comment]
> > > /api/openai 是项目自带代理，将请求在 vercel 服务器上转发一次，并且可以通过访问码将 api key 隔离。
> > > 默认情况下，chatgpt 请求会访问 api/openai 到 vercel 服务器，然后校验访问码之后，注入 OPENAI_API_KEY，然后将请求发往 BASE_URL。
> > > 你修改了接口地址之后，所有请求会在浏览器测直接发往你设置的地址，不会经过服务器中转。
> > > 你的报错看起来是无法在 vercel 服务器上访问设定的 BASE_URL，正确格式是不加 v1，建议你咨询你的 api 中转服务商，确认服务能否在 vercel 服务器上使用。
> > 
> > 
> > 明白了，那个服务商的地址是在国内的，估计是 vercel 的代理发送请求到国内的服务上，可能是服务商做了什么限制；换成国外的服务地址能正常使用了，感谢回复！
> 
> 那服务商是国内的，怎么处理的？

这个就不清楚了，最好咨询服务商国外访问方面的限制和支持；比如[我现在购买的服务](https://github.com/chatanywhere/GPT_API_free)，是有提供对应的国内访问和国外访问的接口地址的。
