### ISSUE TITLE
[Bug] 在Linux环境下docker无法拉取镜像，并且docker的版本号是>20

### ISSUE THREAD

**Issue by ArmyMedalMei** [Yidadaa/ChatGPT-Next-Web#2072]
**描述问题**
在Linux环境下docker无法拉取镜像，并且docker的版本号是>20
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19337530/c67f77b7-b2d1-4671-8f21-7a228a136516)

**如何复现**
使用docker pull 命令一直提示timeout
**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19337530/9f4be495-bf08-403d-97e7-99405f474408)

**Comment by ArmyMedalMei** [comment]
我换了很多网络，都拉取不下来哦 不可能是网路问题哦

**Comment by fullee** [comment]
> 

解决了吗
