### ISSUE TITLE
[Bug] “发现新版本：19700101”

### ISSUE THREAD

**Issue by HJWqa** [Yidadaa/ChatGPT-Next-Web#2084]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
小问题，“发现新版本：19700101”，这是网络问题吗？偶尔出现。

**如何复现**
不知道

**截图**
![IMG_20230621_092526.jpg](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/56158081/6ba98b7d-0357-4cb1-a174-5a11e69534f2)
![Screenshot_20230621_093050.jpg](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/56158081/96080d0f-e50c-49fa-b267-a5ad0c6db3cf)

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： QQX5，Chrome，Edge
 - 版本： 20230620
 - 部署方式：Vercel

**Comment by Yidadaa** [comment]
版本号是从 github 拉取的，众所周知 github 的访问很不稳定，所以凑合用吧。
