### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jbrnb** [Yidadaa/ChatGPT-Next-Web#2085]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
网上部署next-web，然后问问题回复TypeError: RequestInit: duplex option is required when sending a body.

**如何复现**
说什么内容都报错
**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/137160971/417ea078-c53e-4d78-9fef-3bfdf090eb6e)

**一些必要的信息**
 - 系统： windows 10
 - 浏览器：edge
 - 版本： 20230619
 - 部署方式：zeabru

**Comment by jbrnb** [comment]
发送正文时需要双工选项。

**Comment by jbrnb** [comment]
翻译：发送正文时需要双工选项。

**Comment by jbrnb** [comment]
对的

**Comment by Yidadaa** [comment]
docker 版本有这个 bug，最新代码已经修复了，等发版吧
