### ISSUE TITLE
docker部署的版本，用ngnix走https后GPT不会逐字回答

### ISSUE THREAD

**Issue by AreChen** [Yidadaa/ChatGPT-Next-Web#209]
如题，现在我是用ngnix将3000端口映射到100端口绑定域名，并开启ssl，但是GPT回答不是正常一个字一个字出，而是等一会直接出完，并且说两句后会报错
![image](https://user-images.githubusercontent.com/20765464/228749892-9f6cebfb-2d53-4eb0-87f2-9b5494a9d61d.png)
但是如果直接通过IP或者域名访问3000端口就是正常的，问问大佬们，我该怎么解决，感谢！

**Comment by AreChen** [comment]
> [参考](https://github.com/Chanzhaoyu/chatgpt-web#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 试试

感谢我会尝试一下！

**Comment by AreChen** [comment]
已解决，就是proxy_buffering off;的问题，取消缓存现在https反代正常使用!

**Comment by PuddingJoker** [comment]
大哥，你是用docker部署的吗？为什么我部署会失败啊，就是代理问题，本地使用那个代理没问题，但是用docker部署的话就会报错
