### ISSUE TITLE
[Bug] 根据”增加Key池多Key轮询“这个付费教程操作会报错

### ISSUE THREAD

**Issue by ilolita945** [Yidadaa/ChatGPT-Next-Web#2094]
**描述问题**
根据”增加Key池多Key轮询“这个付费教程进行操作，在群辉7.1docker环境中修改了/app/config/server.ts文件，但是我设置了两个key会报错（key1,key2）

**如何复现**
docker用的映射方式来修改，设置了两个key会报错（key1,key2），单个key没问题，见下图

**截图**
![QQ截图20230622015027](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49525838/8730d513-4ed6-4305-8e48-6e508dee86a4)

**一些必要的信息**
 - 系统：[DSM7.1]
 - 浏览器： [chrome,]
 - 版本： [2.8.3]
 - 部署方式：[docker]

**Comment by Yidadaa** [comment]
1. 代码抄错了
2. key 填错了

**Comment by ilolita945** [comment]
> 

看着教程来的  这里我可以发图吗？

**Comment by ilolita945** [comment]
> 1. 代码抄错了
> 2. key 填错了

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49525838/7d90cbff-1a44-4995-b4cd-2395cda5c98b)
没错吧？ key也没错

**Comment by Yidadaa** [comment]
1. 39 行逗号确认一下是不是英文逗号
2. 改完之后在 vercel 上重新部署一次才会生效

**Comment by ilolita945** [comment]
> 

  const apiKeys = (process.env.OPENAI_API_KEY ?? '').split(',')
  const apiKey = apiKeys.at(Math.floor(Math.random() * apiKeys.length)) ?? ''

写的是这样
然后在Docker 内修改好了  单个key可以，2个就报错了

**Comment by ilolita945** [comment]
> 1. 39 行逗号确认一下是不是英文逗号
> 2. 改完之后在 vercel 上重新部署一次才会生效

> 

  const apiKeys = (process.env.OPENAI_API_KEY ?? '').split(',')
  const apiKey = apiKeys.at(Math.floor(Math.random() * apiKeys.length)) ?? ''

写的是这样
然后在Docker 内修改好了  单个key可以，2个就报错了

**Comment by ilolita945** [comment]
> 1. 39 行逗号确认一下是不是英文逗号
> 2. 改完之后在 vercel 上重新部署一次才会生效

![2](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49525838/71a913eb-b5d8-44a0-8327-10b5f0e07747)
![UUO{0G(W2U~YLM9V9@M@6R5](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49525838/54b5f8a1-ba11-4d62-82cb-4fc04f1eacb8)

这里我一共填了两个key，一个账号一个key单独一个key就正常

**Comment by ilolita945** [comment]
![QQ截图20230622114750](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49525838/a79272c8-436a-4c66-b21b-d086d5119aad)


一个key时正常

**Comment by Yidadaa** [comment]
你可以在那两行代码后面加一个 log，把 api key 打印出来，多发几次消息，看看是否轮询成功。

**Comment by Yidadaa** [comment]
@evan-xie 公众号：《我的代码会好吗》

**Comment by Payne-Wang** [comment]
@Yidadaa  大佬，我也在使用付费教程，感觉这个代码只是随机挑选多个key中的一个，然后使用，如果遇到限制之后并不会自动切换key（我是在vercel上部署的）。下面是我的代码：
const apiKeys = (process.env.OPENAI_API_KEY ?? '').split(',')
  const apiKey = apiKeys.at(Math.floor(Math.random() * apiKeys.length)) ?? ''

  return {
    apiKey,
    code: process.env.CODE,
    codes: ACCESS_CODES,
    needCode: ACCESS_CODES.size > 0,
    proxyUrl: process.env.PROXY_URL,
    isVercel: !!process.env.VERCEL,
  };
};
