### ISSUE TITLE
问大家一下，面具角色进入聊天后，聊天记录好像没有保存。下次打开时没有聊天历史

### ISSUE THREAD

**Issue by xkungxfu** [Yidadaa/ChatGPT-Next-Web#2100]
问大家一下，面具角色进入聊天后，聊天记录好像没有保存。下次打开时没有聊天历史

请问大家都是这样么？

如何让面具角色聊天记录自动保存，下次打开时在聊天窗口自动显示历史消息？

**Comment by nidbCN** [comment]
我这里使用一切正常，需要注意的是历史记录是存储在浏览器中的，也就是不会跨设备同步。

检查下浏览器设置，有没有开启无痕模式或自动清理缓存。

如果还有问题建议去官方的 QQ 群提问反馈。
