### ISSUE TITLE
[Question]Does OPENAI_API_KEY supports multi tokens?

### ISSUE THREAD

**Issue by mxrk314** [Yidadaa/ChatGPT-Next-Web#2114]
Does the OPENAI_API_KEY variable supports multiple tokens? like can I put more than one token separated by commas?

**Comment by Yidadaa** [comment]
If you are in China, see this http://mp.weixin.qq.com/s?__biz=MzU0OTY2ODMzNg==&mid=2247483785&idx=1&sn=a65c1306a5bc01ae3c988df1d20a67c7&chksm=fbad1516ccda9c008201bfa15f3702e9985923c8ebea05e6804f26a51179f9b55eefd3f15d41&cur_album_id=2914396475705819137&scene=189#wechat_redirect

**Comment by mxrk314** [comment]
sorry, I dont understand chinese..
