### ISSUE TITLE
[Feature] 现在gpt3.5也支持联网功能了，希望可以加入

### ISSUE THREAD

**Issue by ckcoding** [Yidadaa/ChatGPT-Next-Web#2121]
> 例如官方提供的示例，今天北京天气怎么样，gpt觉得需要你联网的时候会告知你调用函数，可以优先考虑介入微软搜索功能。

参考地址：https://openai.com/blog/function-calling-and-other-api-updates

**Comment by Yidadaa** [comment]
#165
