### ISSUE TITLE
[Feature] 希望支持 serverless CSRF 防护

### ISSUE THREAD

**Issue by jerryokk** [Yidadaa/ChatGPT-Next-Web#2123]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
和现有问题无关。

**你想要什么功能或者有什么建议？**
希望支持 serverless CSRF（跨站请求伪造）防护。我只想我的网站访问 serverless 函数，不想其他网站访问。这应该是个普遍需求。

**有没有可以参考的同类竞品？**
无。这是一种安全方式。

**其他信息**
无。

**Comment by Yidadaa** [comment]
把这几行删了，或者你自己加个环境变量去控制：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/8f66da112837b11890fd60c1ed9ccb22e1c7a534/next.config.mjs#L21

**Comment by jerryokk** [comment]
> 把这几行删了，或者你自己加个环境变量去控制：
> 
> https://github.com/Yidadaa/ChatGPT-Next-Web/blob/8f66da112837b11890fd60c1ed9ccb22e1c7a534/next.config.mjs#L21

改这几行只能限制 CORS，不能 CSRF 啊。
删掉这几行，用后端访问 api 还是防不住。

**Comment by Yidadaa** [comment]
你需要先构造出一系列可能的攻击方式，再谈如何防范，不妨先在此处列举一下你能想到的针对性攻击方式。

**Comment by jerryokk** [comment]
> 你需要先构造出一系列可能的攻击方式，再谈如何防范，不妨先在此处列举一下你能想到的针对性攻击方式。

场景：我想别人免费使用web网站，所以我可以不设密码，或者分享密码。但是不想别人直接使用我的 api 接口。
现在的问题：别人只要能用web网站，就能通过浏览器检查知道该网站的接口，然后构造接口内容，就能绕过 ChatGPT-Next-Web 直接访问接口了，这是我们不希望看到的；

CORS 只能限制浏览器客户端的请求，有些请求可以通过后端发起，Referer 等头部字段都能伪造。
可以通过 https://apifox.com/ 模拟请求您的网站的接口，发现是可以直接绕过 web 网页访问接口的。

所以我才想通过 CSRF 的方式进行防护。 @Yidadaa

**Comment by Yidadaa** [comment]
@jerryokk 这个行为是 by-design 的，因为此项目设立的初衷是绕过 openai 和 gfw 的诸多限制，项目本身的 api 不仅仅为前端页面而服务，实际上访问码加上 `ak-xxxx` 前缀之后，配合项目的域名 `https://xxx/api/openai`，是可以完整替代 `api.openai.com` 和 `sk-xxx` 的功能的，这是我在开发项目之初就确定的特性，只不过我并没有时间把这些特性补充到文档里。

至于你说的绕过前端直接请求接口，即便是加了 CSRF 也无法杜绝，只要你没有加任何限制措施，别人总能想办法突破你的封锁，openai 的 accessToken 以及 poe 的各种验证基本都是形同虚设，所以在这上面花时间防范，收益不大。

针对你的场景，增加 rate-limit 以及使用 cf zero trust 服务，可以在一定程度上缓解该问题。

如果你执意想增加 csrf 防护，可以研究一下 nextjs 中增加 csrf 的最佳实践，自行在 fork 的下游项目中增加此功能。
