### ISSUE TITLE
[Feature] 不支持账号共享功能吗？

### ISSUE THREAD

**Issue by tlerbao** [Yidadaa/ChatGPT-Next-Web#2128]
隔壁另一个开源项目比咱这个丑多了

但是支持账号共享

就是一个人的Plus账号可以在这个平台下给N个朋友一起用GTP4，咱们还不支持是吗

**Comment by tlerbao** [comment]
我说的是这个项目
https://github.com/moeakwak/chatgpt-web-share

**Comment by Yidadaa** [comment]
1. 不支持 accessToken；
2. 如果你有 api 权限，部署之后设定访问码，就能达到你所谓的账号共享。
