### ISSUE TITLE
[Feature] Retry with by editing original prompt

### ISSUE THREAD

**Issue by chen-rn** [Yidadaa/ChatGPT-Next-Web#2136]
Often times, I want to retry but modify my prompt slightly. The current retry will simply retry with the same prompt. Delete will delete the prompt and the response.

**The current way of doing prompt retry is:**
1. copying original prompt
2. delete response(which will delete prompt as well)
3. paste my prompt in chatbox
4. edit

Instead, when I click retry, ideally something similar to [yakgpt](https://yakgpt.vercel.app/) happens. Where I can directly edit my original prompt.

**Comment by Yidadaa** [comment]
Now you can click avatar to edit a message:

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/375a559e-3e5c-41cb-b885-6381d393c564)
