### ISSUE TITLE
请问标题与OpenAI官网不同步是怎么回事

### ISSUE THREAD

**Issue by dengchangdong** [Yidadaa/ChatGPT-Next-Web#2139]
请教各位大佬，能正确获得聊天对话标题，但是OpenAI官网的标题全部显示为“New Chat”，是我哪里配置错误了吗？

使用的 linweiyuan/go-chatgpt-api 和 acheong08/ChatGPT-to-API 反代 OpenAI API，配置 accessToken

**Comment by Yidadaa** [comment]
两者的标题生成没有任何关系。

**Comment by dengchangdong** [comment]
谢谢大佬
