### ISSUE TITLE
移动端设置界面里的小小问题

### ISSUE THREAD

**Issue by TactfulBean** [Yidadaa/ChatGPT-Next-Web#214]
移动端的紧凑边框选项使用display: none;进行隐藏
但是有条线还在这里🙃🙃
![L{LNU)6Q){R%JPOXY99 96](https://user-images.githubusercontent.com/90669825/228767388-0ff1f7ef-e800-4d64-9df9-777dd6738753.png)

**Comment by AprilNEA** [comment]
列文虎克

**Comment by TactfulBean** [comment]
调换后在PC端显示少一根线

**Comment by TactfulBean** [comment]
和这个样式有关
```
.list .list-item:last-child {
  border: 0;
}
```

**Comment by Yidadaa** [comment]
#254
