### ISSUE TITLE
[Feature] "Clear All Data" and "Reset All Settings" buttons should be in a less visible place

### ISSUE THREAD

**Issue by johan456789** [Yidadaa/ChatGPT-Next-Web#2142]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2023-06-25 at 23 49 46](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14802181/cdd000f5-a0f9-4026-a2b3-387d95bef72d)

The "Clear All Data" and "Reset All Settings" buttons are both destructive actions and should not be placed in such a visible place and especially not next to a relatively benign button "Close (Window)".

Here's more explanation of the UX considerations:
- https://www.nngroup.com/articles/proximity-consequential-options/
- https://uxmovement.com/buttons/how-to-design-destructive-actions-that-prevent-data-loss/

**Describe the solution you'd like**
IMO the ideal location is at the end of the settings list, and the text (the section as well, at least the text) should be marked red like what GitHub does here:

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14802181/cd855905-b75a-4273-9077-cd23280de11a)

**Describe alternatives you've considered**
I haven't tried clicking either of the buttons to avoid risking data loss. Maybe there are warnings that show up after clicking them but my point is the location is less than ideal. They are infrequent actions and should be placed in a less visible place.

**Comment by Yidadaa** [comment]
Good suggestion, a better solution is to place them to the bottom of the settings page, i will do it later.

**Comment by Yidadaa** [comment]
done
