### ISSUE TITLE
[Feature] 增加一个配置，可以传入js代码

### ISSUE THREAD

**Issue by V1V1rus** [Yidadaa/ChatGPT-Next-Web#2148]
希望在设置中添加一个输入框，可以用户自定义插入js代码。

方便在web端放入类似Umami的探针，记录网络请求数据。

**Comment by Yidadaa** [comment]
自己改代码就行了，就一行，还不影响你自动同步。

**Comment by Kiuber** [comment]
You can also implement it in gateway. e.g. Nginx `sub_filter_types` `sub_filter` directive.

**Comment by V1V1rus** [comment]
> You can also implement it in gateway. e.g. Nginx `sub_filter_types` `sub_filter` directive.

I try to use a sub_filter.

           sub_filter '</body>' '<script>alert("Hello World!");</script></body>';
           sub_filter_once off;
           sub_filter_types text/html;

But it didn't work.

**Comment by V1V1rus** [comment]
> You can also implement it in gateway. e.g. Nginx `sub_filter_types` `sub_filter` directive.

This method is OK!!! Thanks
