### ISSUE TITLE
[Bug] 页面按钮显示异常

### ISSUE THREAD

**Issue by gwoweiming** [Yidadaa/ChatGPT-Next-Web#2149]
**Describe the bug**
iOS上打开页面时输入框上面一排按钮显示异常。

**To Reproduce**
1. 打开新的聊天

**Expected behavior**

**Screenshots**
![2ab3d508de9c27c2e7731a9006b30b90](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46470282/81524b7b-78d6-46a9-ae80-fddbe0deeb2f)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS:  iOS16.5.1
 - Browser： Safari

**Comment by gwoweiming** [comment]
额，刚刚更新了，还是有问题

**Comment by Yidadaa** [comment]
只有在 vercel 上部署才会出现这个问题，本地部署无法复现，挺离谱的。

**Comment by Yidadaa** [comment]
已彻底解决该问题
