### ISSUE TITLE
The Safari browser on iOS system opens and loads very slowly, and the styles also become distorted.

### ISSUE THREAD

**Issue by akl7777777** [Yidadaa/ChatGPT-Next-Web#2160]
**Describe the bug**
iPhone12,iPhone11都试过,流量和WiFi也都试过,同样网络环境下,安卓手机可以很快加载出来,但是IOS不行,需要等待很久,在等待的时候直接点击新建聊天,会出现一片白屏,但是在白屏上好像可以点击弹出键盘;同样的网络条件下,用另一台安卓的vivo手机测试自带浏览器打开是很快的,而且没有样式乱掉的问题;我用Chrome浏览器的手机模式试过无法复现,麻烦大佬帮看下

截图我后面用手机发出来

**Comment by akl7777777** [comment]
![IMG_3014](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/84266551/891d6970-e3e1-4429-8097-185ca77f448f)

![IMG_3015](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/84266551/111e09e9-9891-4c36-8f93-00467bf47c26)

**Comment by Yidadaa** [comment]
检查你的 safari 是不是装了什么插件。
