### ISSUE TITLE
/api/config，这个请求地址，后端代码是在哪里？

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#2162]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25891219/22605e56-8b4a-42f3-af6b-0bd9ba20a4ad)
我对react和nextjs不太熟。
还有个疑问就是，我看有些代码是在服务端运行的，有些代码是在浏览器端运行，这个是如何进行区分的？有没有相关资料链接，我可以自己学习。

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/api/config/route.ts

**Comment by vual** [comment]
> https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/api/config/route.ts

他是如何捕获 /api/config 这个请求的？

**Comment by Yidadaa** [comment]
https://nextjs.org/docs/app/building-your-application/routing/router-handlers
