### ISSUE TITLE
[Bug] The router mode can not be change to history, and can not get path params by useParams()

### ISSUE THREAD

**Issue by TiannaXin** [Yidadaa/ChatGPT-Next-Web#2164]
1 、When I changed the 'HashRouter' to 'BrowserRouter, it did not work, it was still the hash mode(/#/chat) .
2、I defined the route like /chat/:id， but i can't get the id param by useParams(), when the router is /chat/123.

So how can I get it works, thanks.

**Comment by Yidadaa** [comment]
https://colinhacks.com/essays/building-a-spa-with-nextjs

**Comment by Yidadaa** [comment]
Next.js has poor compatibility with the browser router, so it is not recommended to use it.
