### ISSUE TITLE
[Bug] macOS客户端点击聊天右上角的编辑按钮没反应

### ISSUE THREAD

**Issue by ZacharyJia** [Yidadaa/ChatGPT-Next-Web#2165]
**Describe the bug**
macOS客户端点击聊天右上角的编辑聊天名称按钮没反应。或许是tauri不支持alert?

**To Reproduce**
1. 打开任意聊天窗口
2. 点击右上角编辑聊天名称，无反应

**Expected behavior**
网页版应该弹出alert要求输入新的名称

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [20230625]

**Comment by Yidadaa** [comment]
#1994
