### ISSUE TITLE
[Bug] 最近更新后奇慢无比... ...

### ISSUE THREAD

**Issue by yuejunzhang** [Yidadaa/ChatGPT-Next-Web#2166]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
和 openai 服务有关。

**Comment by yuejunzhang** [comment]
慢的离谱，好像旧版本更正常。
