### ISSUE TITLE
[Feature] 配置OPENAI_API_KEY和PROXY_URL在初始配置无效

### ISSUE THREAD

**Issue by tanjingdong** [Yidadaa/ChatGPT-Next-Web#2167]
我使用fast docker方式进行部署，我发现配置结束后每一台新进入服务的设备，都需要单独配置OPENAI_API_KEY和PROXY_URL，我不太清楚这是我创建容器配置错误，还是项目的特性如此。而我希望的是，能够创建一个服务，使得我在我的不同设备、或者我和我的朋友们，都可以直接使用这个服务，而不是每一台设备都要配置。在README文档中似乎也没有提及该特性。

另外文档中也没有提到配置文件config所在的位置，我花了很长时间没有找到。

我感觉我的配置是对的，因为CODE参数起效了。

**Comment by Yidadaa** [comment]
docker 部署命令和环境变量提供一下

**Comment by tanjingdong** [comment]
> docker 部署命令和环境变量提供一下
![网页捕获_27-6-2023_172657_42 193 23 238](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/131412657/e7a0f28a-12f1-46b1-8787-ec0fcb975224)

**Comment by Yidadaa** [comment]
当你设置了 CODE 之后，你的朋友们只需要在设置里填写访问码就能使用你部署的网页了。

此外，我不太懂你说的“创建一个服务”是指什么的服务，是指你的朋友们直接通过你部署的链接访问这个项目？还是通过你提供的 docker 服务部署他们自己的项目？

**Comment by tanjingdong** [comment]
> 当你设置了 CODE 之后，你的朋友们只需要在设置里填写访问码就能使用你部署的网页了。
> 
> 此外，我不太懂你说的“创建一个服务”是指什么的服务，是指你的朋友们直接通过你部署的链接访问这个项目？还是通过你提供的 docker 服务部署他们自己的项目？

是的。我部署后CODE参数生效了，每一台设备都需要输入密码，但是OPENAI_API_KEY和PROXY_URL参数没有生效，每一台设备都得单独填入之后才能使用。我希望的是，每一台设备只要输入了密码，就能使用我预先配置的OPENAI_API_KEY和PROXY_URL参数进行使用。目前这种，每一台设备都需要单独填写OPENAI_API_KEY和PROXY_URL的情况，我不清楚是我配置错误了，还是这个项目就是这样的特性。

**Comment by Yidadaa** [comment]
@tanjingdong 显然是你的环境变量填错了，PROXY_URL 是本地 http 代理的地址，如果你的服务器本身就在国外，就无需设置，只需要设置 API_KEY 就行了；如果你需要使用自建的 openai 代理，你需要改的环境变量是 BASE_URL。

**Comment by xushier** [comment]
我也遇到这个问题，新的访问需要填入访问密码、API key、BaseUrl才能使用，而不是使用后端配置好的 Key 和 Url，docker run 和 docker compose 都试过，是一样的结果，docker-compose 文件也去除了引号，容器内查看变量是有的。

环境：docker

docker-compose：
`version: 3.3
services:
    chatgpt-next-web:
        container_name: ChatGPT-Next
        network_mode: bridge
        environment:
            - OPENAI-API-KEY=sk-xxxx
            - CODE=xxxpassword
            - BASE_URL=xxxbaseurl
        ports:
            - 4037:3000/tcp
        image: yidadaa/chatgpt-next-web`

**Comment by Yidadaa** [comment]
@xushier 如果不填，前端访问会报什么错？

**Comment by xushier** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> @xushier If you leave it blank, what error will the front-end access report?

会提示：
访问密码不正确或为空，请前往[登录]页输入正确的访问密码，或者在[设置]页填入你自己的 OpenAI API Key。

发送问题显示：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/31540107/60c71c8f-0fdf-4c75-9d6e-fb5b75ab9641)
