### ISSUE TITLE
[Bug] Markdown 显示异常

### ISSUE THREAD

**Issue by gwoweiming** [Yidadaa/ChatGPT-Next-Web#2172]
Describe the bug
机器人回复markdown时格式有点错乱，打开一下设置界面就会正常了

To Reproduce
触发机器人回复markdown格式

Expected behavior

Screenshots
![Snipaste_2023-06-27_23-42-53](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46470282/85bf37a5-fdb8-4e51-9f13-cd7cc3847af1)

Deployment
 Vercel

Smartphone (please complete the following information):
Device: iPhone13
OS: iOS16.5.1
Browser： Safari

**Comment by Yidadaa** [comment]
iOS 的兼容性问题，此问题无法排查也不好处理，不影响使用。
