### ISSUE TITLE
[Bug] Invalid URL (POST /v1/chat/completions)

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2175]
latest commit show me this issue:

![SNAG-0129](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/6913ea49-2ff4-4c70-b289-67a3dcabda91)

latest one of that is OK:

![SNAG-0130](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/9f7c1ffc-927d-468e-aeea-d5546e352455)

**Comment by Yidadaa** [comment]
have you set `Endpoint`?

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/d506ffe7-ff98-4df8-ae62-c0d9bb92ded9)

**Comment by johnfelipe** [comment]
What need to put in that field?

**Comment by Yidadaa** [comment]
If you have direct access to api.openai.com, please set it as https://api.openai.com.
If you do not have direct access to api.openai.com, please keep the option as /api/openai. This will utilize Vercel to proxy all your requests.

**Comment by Yidadaa** [comment]
Later, I will add a default logic to the code, so if the user forgets to set this option, the default `endpoint` will be automatically used.

**Comment by QAQQL** [comment]
当我使用  https://github.com/THUDM/ChatGLM2-6B  时,官方有推荐使用该项目
`
感谢 [@hiyouga](https://github.com/THUDM/ChatGLM2-6B/blob/main) 实现了 OpenAI 格式的流式 API 部署，可以作为任意基于 ChatGPT 的应用的后端，比如 [ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)。可以通过运行仓库中的[openai_api.py](https://github.com/THUDM/ChatGLM2-6B/blob/main/openai_api.py) 进行部署：
`

我进行了如下配置
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/51136763/38ce5b58-bf7a-4388-9be5-1d566acaa0d0)
发现下拉模型列表并不能触发`/v1/models`接口,且接口访问全为跨域
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/51136763/af08786b-8031-4ec9-9948-d2edabc72273)

#1179

**Comment by QAQQL** [comment]
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/51136763/d8adbc36-9147-4c7c-80ca-ba4ed8f7ded3)
下面的模型无法选择

**Comment by Yidadaa** [comment]
@QAQQL 兼容接口无需选中 chatglm 模型，使用默认的 gpt-3.5-turbo 即可。

**Comment by QAQQL** [comment]
但是他接口访问失败

**Comment by Yidadaa** [comment]
@QAQQL 这是浏览器的默认策略，你可以给他们提个 PR 来解决这个问题，只需要允许所有的 OPTIONS 请求，并返回 200 即可。

**Comment by Yidadaa** [comment]
@QAQQL 你可以参考 fastapi 的 api 文档，为它添加 cors 支持：https://fastapi.tiangolo.com/tutorial/cors/#steps

只需要在：

https://github.com/THUDM/ChatGLM2-6B/blob/ba60190296e3451c0e7e6a0f26c60a8ba7720dfe/openai_api.py#L26

处，加几行代码：

```python
from fastapi.middleware.cors import CORSMiddleware

origins = [
    "http://localhost.tiangolo.com",
    "https://localhost.tiangolo.com",
    "http://localhost",
    "http://localhost:8080",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```

**Comment by Yidadaa** [comment]
等待此 PR 合入：https://github.com/THUDM/ChatGLM2-6B/pull/102

**Comment by QAQQL** [comment]
好的,谢谢您

**Comment by KAIYI-HSU** [comment]
@Yidadaa 
您好:

我也是透過ChatGLM2-6B 的openai_api.py進行部署後端。
我只修改文件中的model路徑跟改對外端口如下:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73111412/3360b069-40f2-4f3b-b87e-1aa9ffbab9e5)
我有確定成功開啟端口並且能成功從 <我的固定IP>:19745/docs造訪說明書，也能用POST測試成功，GLM2可以生成回應。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73111412/a46e0f77-96ce-4bb4-979e-f02e8ec0f207)
=====
請問我使用您的前端網頁: https://chatgpt1.nextweb.fun/
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73111412/4efac604-5c8a-4ee9-a9a9-9b5d9645872f)
Endpoint填寫我的<我的固定IP>:19745 or https://<我的固定IP>:19745
對話時會出現以下錯誤:
{
  "error": true,
  "message": "Failed to fetch"
}
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73111412/c4575bbc-6700-4ce0-ae27-d251d2fd1feb)

=====
希望能尋求幫助，
為何我後端部署好，任何前端網頁都無法跟 我的<我的固定IP>:19745 or https://<我的固定IP>:19745
進行互動?
