### ISSUE TITLE
[Feature] 建议曾加一个将用户信息同步到IPFS的功能

### ISSUE THREAD

**Issue by Endlessworld** [Yidadaa/ChatGPT-Next-Web#2176]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
[Feature] Cloud Sync via WebDAV #920 (https://github.com/Yidadaa/ChatGPT-Next-Web/issues/920)

**你想要什么功能或者有什么建议？**
建议曾加一个将用户信息同步到IPFS的功能
 1、用户可自行决定是否开启聊天记录同步。
 2、开启聊天记录同步后 可填写自定义IPNS同步地址。
 3、上传和下载时可以是使用客户端用户自定key简单加密内容。
 4、开启后将当前聊天记录以目录形式同步到IPFS ，然后将根目录的CID发布到IPNS
 5、用户将获取一个固定的IPNS访问链接，此链接可用于聊天记录多端同步，但内容需要用户密码解密

**有没有可以参考的同类竞品？**
暂时没有

**其他信息**
![分布式文件系统](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/33451309/89bc9c19-5777-47c4-8ae2-15db9a63dc56)

![IPFS目录固定 (1)](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/33451309/6fbdca9c-a237-4ebf-8777-7a857bc4dd1b)

**Comment by Yidadaa** [comment]
ipfs 节点要自己部署？那为什么不用 web dav？大多数用户根本不会花时间维护自己的服务器，web dav 跨域问题只需要在 vercel 上加个反代就能解决了。

**Comment by Endlessworld** [comment]
可以使用公共网关 https://ipfs.github.io/public-gateway-checker/
例如cloudflare的 cloudflare-ipfs.com
cloudflare 提供免费计划、开发者配置好默认网关之后 用户无需关心 服务器问题
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/33451309/52cb6845-86ce-4d5a-aca9-9008f3dc76c0)

**Comment by Yidadaa** [comment]
我不准备把这个功能复杂化，web dav 对于大多数用户都是一个易于理解的概念，至少理解成本要比 ipfs 要低很多，尤其是国内用户，可以非常方便地使用坚果云提供的 web dav 服务，完全不需要自己再去部署一个新的用于存储的服务。

**Comment by daiaji** [comment]
> 我不准备把这个功能复杂化，web dav 对于大多数用户都是一个易于理解的概念，至少理解成本要比 ipfs 要低很多，尤其是国内用户，可以非常方便地使用坚果云提供的 web dav 服务，完全不需要自己再去部署一个新的用于存储的服务。

要说的话，如果ipfs现在可靠度足够的话，去中心的方案应该更靠谱，毕竟不用担心运营跑路，但ipfs基于区块链，我都不知道有没有靠谱的应用案例。
老实说webdav如果不太行的话，怕不是还是要用网盘的api。

**Comment by Yidadaa** [comment]
@daiaji webdav 在 vercel 上套个代理就行，跨域问题好解决。ipfs 认知成本太高，这项目还是以易用性为主。

**Comment by daiaji** [comment]
> @daiaji webdav 在 vercel 上套个代理就行，跨域问题好解决。ipfs 认知成本太高，这项目还是以易用性为主。

> 大多数 webdav 服务均没有开启 cors，无法在网页中直接使用，此特性开发暂时搁置。

这个还有的抢救吗？
实在不行就网盘api吧。

**Comment by daiaji** [comment]
> @daiaji webdav 在 vercel 上套个代理就行，跨域问题好解决。ipfs 认知成本太高，这项目还是以易用性为主。

我在cloudflare部署，貌似没法用next运行时，upstash又特别小气。

四舍五入根本没法用云同步。

感觉还真不如用IPFS.

起码配额够用，而且cloudflare也大方。

要不然就是各大云盘了。
