### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by a494413872** [Yidadaa/ChatGPT-Next-Web#2177]
收到这个邮件，新模型降价了，还有支持长token的，麻烦加一下：
GPT-3.5 TurboThis model has been updated with a new version: gpt-3.5-turbo-0613 which is more steerable with the system message and includes a new capability: function calling. By describing functions in your prompts, the model can intelligently output a JSON object containing arguments to call these functions based on user input — perfect for integrating with other tools or APIs. Learn more in our function calling documentation.
GPT-3.5 Turbo
This model has been updated with a new version: gpt-3.5-turbo-0613 which is more steerable with the system message and includes a new capability: function calling. By describing functions in your prompts, the model can intelligently output a JSON object containing arguments to call these functions based on user input — perfect for integrating with other tools or APIs.
Plus enjoy a 25% cost reduction for input tokens on GPT-3.5 Turbo (now $0.0015 per 1K input tokens), effective immediately.
Longer Context
We're also introducing gpt-3.5-turbo-16k. This model offers four times the context length of the 4k base model and is priced at $0.003 per 1K input tokens and $0.004 per 1K output tokens.
Model Transitioning
You can begin using the new gpt-3.5-turbo-0613 model today. On June 27th, the stable gpt-3.5-turbo will be automatically upgraded to this new version. If you need more time to transition, you can specify gpt-3.5-turbo-0301 to keep using the older version, which will remain available until September 13th as part of our upgrade and deprecation process

**Comment by Yidadaa** [comment]
升级代码

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/c99e09f9-8b15-4917-932d-d3cd4bbdf050)
