### ISSUE TITLE
2.84 桌面版本，安装后无法启动

### ISSUE THREAD

**Issue by onlyhuman028** [Yidadaa/ChatGPT-Next-Web#2179]
**Describe the bug**
2.84 桌面版本，安装后无法启动

win10操作系统

关闭杀毒软件，应用管理员权限安装

始终无法启动

有图标，但无法运行，在图标上点右键 也出不来显示

**Comment by Yidadaa** [comment]
我在 win11 下无法复现，可以正常安装使用。

可以尝试卸载后重装，如果还是无法使用，请优先使用项目提供的演示站点，国内可直连。

目前客户端仍是测试版本，不保证可用。

最后有个问题，2.8.3 版本或者更老的版本可用吗？
