### ISSUE TITLE
[Bug] 响应式动画导致复制时文字会移动，复制起来太难受了

### ISSUE THREAD

**Issue by xzxz520cs** [Yidadaa/ChatGPT-Next-Web#2180]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
响应式动画导致复制时文字会移动。能否对这一部分的UI进行优化。

**如何复现**

**截图**

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/22582356/22567b4e-cc0e-4c90-92f6-9f4ac2c560bc

**一些必要的信息**

**Comment by Yidadaa** [comment]
有几种方法可以缓解：
1. 复制消息时，稍微将消息列表向上滚动一点，这样最后一条消息长度变化不会导致整体位移；
2. 复制消息时，控制鼠标不要离开消息体；
3. 在设置里面调大文字，方便精准操作；
4. 右键单击消息，自动填充消息内容到对话框，在对话框内编辑文本。
