### ISSUE TITLE
[Feature] 能否提供禁用自动生成标题的设置

### ISSUE THREAD

**Issue by Ryan-yang125** [Yidadaa/ChatGPT-Next-Web#2181]
**Is your feature request related to a problem? Please describe.**
聊天的时候让chatgpt生成几个字的标题用来管理对话是很棒的。但是当我用来让他分析一些文章时会消耗大量token，而自动生成标题会额外消耗一倍多一点的token。
**Describe the solution you'd like**
希望能够让我自己选择关掉这个功能。
**Describe alternatives you've considered**

**Additional context**

**Comment by Yidadaa** [comment]
你可以单独创建一个面具，给面具随便设定一个名字，其他保持不变，当你要分析长文章时，就用这个面具新建对话，这样它就不会自动生成标题了。
