### ISSUE TITLE
[Feature] 可以修改系统默认的提示词

### ISSUE THREAD

**Issue by dltc** [Yidadaa/ChatGPT-Next-Web#2183]
对接的是Azure OpenAI 但是每次会话之前，都有一段
You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: 2021-09
Current model: gpt-3.5-turbo
Current time: 2023/6/28 15:43:04
导致 Azure OpenAI 认为自己是ChatGPT.

**Comment by llllllllllx** [comment]
这是你开了预设提示词吧，关掉 或者修订一下就可以了

**Comment by Yidadaa** [comment]
这段提示词是 openai 网页版的预制提示词，openai 针对其做了优化，加了之后可以提升使用体验，如果你手动指定了预设提示词，这段系统提示词将不会被发送。

**Comment by imldy** [comment]
#2344
