### ISSUE TITLE
[Bug] 本地无法运行

### ISSUE THREAD

**Issue by BuildSoft** [Yidadaa/ChatGPT-Next-Web#2184]
node版本为18.16.0，yarn版本为1.22.19，使用命令行yarn dev时无法运行项目，提示Using wasm build of next-swc

**Comment by BuildSoft** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/5466222/cc09996a-5002-4789-a717-7f0490fe352e)
执行yarn dev

**Comment by Yidadaa** [comment]
1. 尝试 https://stackoverflow.com/questions/76043724/create-next-app-npm-run-dev-error-command-failed-with-exit-code-1
2. 尝试删除 node_modules，然后重新 `yarn install && yarn dev`

**Comment by BuildSoft** [comment]
删除过很多次了，还是不生效。除了node_modules还有别的因素会导致这个问题嘛？如果没有别的原因的话实在找不到别的原因了。

**Comment by Yidadaa** [comment]
你的 nodejs 能正常运行吗？可以安装 nodejs 20 试一下。
