### ISSUE TITLE
[Feature] Improve Chat Actions UX

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#2187]
- auto-grow height caused by hovering message is annoying
- fix hover styles for more stable visual transition
- maybe should use absolute position for it?

**Comment by ClarenceDan** [comment]
A fixed position is more eye-catching. Maybe we could try putting the Chat Actions on top of the latest message and hide them for the rest.
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48417261/98a611ea-0488-4c3c-bb49-6300f64a9077)

**Comment by onepy** [comment]
同意上一个版本的消息操作方式，现在的操作经常性的误触，且界面来回跳动，体验很差
