### ISSUE TITLE
[Feature] 希望左侧的菜单栏可以展开或折叠

### ISSUE THREAD

**Issue by freedomspiritJohn** [Yidadaa/ChatGPT-Next-Web#2188]
有时候会查询比较隐私的问题，不希望被别人看到，所以希望添加一个折叠起来左侧历史记录的面板的功能

**Comment by ClarenceDan** [comment]
尝试将鼠标放在聊天框和列表中间的横线上往左侧拖动即可。
不过确实可以考虑加个更明确的方向小按钮表明列表可以折叠🤔

**Comment by freedomspiritJohn** [comment]
> 尝试将鼠标放在聊天框和列表中间的横线上往左侧拖动即可。 不过确实可以考虑加个更明确的方向小按钮表明列表可以折叠🤔

如果您考虑的话，希望折叠起来后，可以可以设置聊天内容距离左右边界的距离。如图所示
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/129288685/2fd21677-5880-4a35-b318-22dc4f98248f)
