### ISSUE TITLE
[Bug]macOS 启动失败 

### ISSUE THREAD

**Issue by flyMDW** [Yidadaa/ChatGPT-Next-Web#2189]
macOS 版本：10.14.6 (18G103)
应用版本：Version 2.8.4 (20230625.174604)
试了下 2.8.5也有同样的问题

<img width="746" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17376202/fa47d5e5-240c-4e95-8146-69e1a22fabe6">

**Comment by Yidadaa** [comment]
1. Safari 版本？
2. 检查自己的浏览器版本是否在：https://nextjs.org/docs/architecture/supported-browsers 中
3. 访问本项目的演示站点，确认是否会出现该问题。

初步猜测是老版本 safari 不兼容导致的。

**Comment by Yidadaa** [comment]
请下载安装 v2.8.6 版本，应该已经解决了该问题。
