### ISSUE TITLE
[Bug] MacOS上的app图标过大不符合规范

### ISSUE THREAD

**Issue by lc11235** [Yidadaa/ChatGPT-Next-Web#2195]
app在MacOS上的图标尺寸过大，如下图所示。

![20230630-095307](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/12327096/9c02264b-3db5-4734-9ef3-940845c5eac3)

**Comment by Yidadaa** [comment]
一些有用的信息：
- https://www.reddit.com/r/PWA/comments/rm2v38/macos_dock_icon_sizing/
- https://github.com/Yidadaa/ChatGPT-Next-Web/issues/156
- https://stackoverflow.com/questions/71118094/why-is-my-app-icon-bigger-than-the-others-in-the-macos-dock
- https://github.com/photopea/photopea/issues/2644
