### ISSUE TITLE
[Bug] 网页版总是显示更新

### ISSUE THREAD

**Issue by gwoweiming** [Yidadaa/ChatGPT-Next-Web#2196]
**Describe the bug**
网页版总是显示更新

**Expected behavior**
最新版不应该显示前往更新

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46470282/1cebab28-2476-4ee5-8d8b-bd3e60d57901)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by Yidadaa** [comment]
预期内行为，明天就好了。
