### ISSUE TITLE
 Will it support Unofficial API using OpenAI tokens?

### ISSUE THREAD

**Issue by tristone13th** [Yidadaa/ChatGPT-Next-Web#22]

**Comment by Yidadaa** [comment]
Most likely not, the main goal of this project is to deploy the ChatGPT web application quickly and conveniently. Using unofficial APIs may complicate the deployment process. If you have better ideas, you are welcome to submit a PR to contribute code.

**Comment by tristone13th** [comment]
> Most likely not, the main goal of this project is to deploy the ChatGPT web application quickly and conveniently. Using unofficial APIs may complicate the deployment process. If you have better ideas, you are welcome to submit a PR to contribute code.

Got it, thanks for the great work!
