### ISSUE TITLE
[Feature] 左侧聊天列表关闭时，希望 有个弹窗二次确认

### ISSUE THREAD

**Issue by flyMDW** [Yidadaa/ChatGPT-Next-Web#2200]
<img width="299" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17376202/7751d3a5-032e-45f7-973f-00768d4bf15f">

**Comment by Yidadaa** [comment]
非易误触按钮，没必要加，有时需要快速删除大量对话，加了反而用着不舒服。如果误触了，会弹出提示撤回的。
