### ISSUE TITLE
[Bug] 回复会被清空，且返回network error

### ISSUE THREAD

**Issue by Easteriv** [Yidadaa/ChatGPT-Next-Web#2203]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我在使用GPT4 API 模型时，提问了长段问题，它在回复到一半的时候直接返回：network error，并会清空之前的回答(我认为这对我并不友好，因为部分回答可能对我也有帮助)
**如何复现**
1. 提问了预计100行的两段代码，并询问Gpt如何重构
2. 在出现network error后曾多次点击重试按钮
3. 升级新版本后曾清空之前历史数据，并重设openAI key等参数
4. 短问题没有发生此类问题
PS：不确定是否是版本问题还是API稳定性，2.8.6之前的版本并未发生此类问题

**截图**
<img width="479" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/40998471/ed8f7a24-2c33-47d1-bed3-b61cb2d000cd">

**一些必要的信息**
 - 系统： linux 
 - 浏览器： chrome
 - 版本： 2.8.6
 - 部署方式：docker + cloudFlare + Nginx

**Comment by Yidadaa** [comment]
基本都是网络问题导致，docker + cf 并不稳，首先 cf 在国内访问的稳定性就很堪忧，其次 docker 上如果你用了 PROXY_URL，你自己的本地代理的质量也会影响连接稳定性。目前最稳的方法还是 vercel + 自定义域名。

网络问题无法解决，除非你更改部署方式。

**Comment by Easteriv** [comment]
好吧，我用的是vultr国外服务器搭建部署，配合梯子使用，按道理说访问速度和稳定性不应该是一个问题的。

**Comment by Easteriv** [comment]
> 基本都是网络问题导致，docker + cf 并不稳定，首先 cf 在内部访问的稳定性就很堪忧，其次 docker 上如果你用了 PROXY_URL，你自己本地代理的质量也会影响连接稳定性。最稳定的方法还是vercel + 自定义域名。
> 
> 网络问题无法解决，除非您更改部署方式。
国外服务器部署也存在这个稳定性问题吗？没有走代理。。

**Comment by LPtrichor** [comment]
我也是nginx转发和套了cloudflare，时不时就会出现一直加载的情况，重发就又可以了，直接访问ip+port没啥问题

**Comment by zgpnuaa** [comment]
我也遇到了这个问题，是在微信中打开网页使用会出现这种情况，用手机上的浏览器打开使用没有出现这个问题，不知道是不是微信内嵌的浏览器有什么影响。
