### ISSUE TITLE
[Bug] 全局设置按钮无法勾选或取消，点击后无效

### ISSUE THREAD

**Issue by reece00** [Yidadaa/ChatGPT-Next-Web#2208]
**Describe the bug**
按钮点击后无效。

还有版本号是不是不太对
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/37351410/8fabaf01-4833-4711-8ee4-cb5cda68bc73)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chromei]

**Comment by Yidadaa** [comment]
全局设置按钮是指什么

**Comment by reece00** [comment]
对话设置里的全局设置继承按钮
