### ISSUE TITLE
Can't resolve 'child_process'

### ISSUE THREAD

**Issue by hhtower** [Yidadaa/ChatGPT-Next-Web#2214]
win11 vs使用 yarn run dev
然后
- warn ./app/config/build.ts
Module not found: Can't resolve 'child_process' in 'D:\Hobby\H5Code\ChatGPT-Next\app\config'

Import trace for requested module:
./app/config/build.ts
./app/config/client.ts
./app/components/home.tsx

目前来看是不影响运行，但是打包的wins客户端默认打开不是全屏。

**Comment by Yidadaa** [comment]
nextjs 的 warning，没找到关掉的方法，不影响使用。

你用啥方法打包的？不全屏和这个一点关系都没有，打包的时候必须用 BUILD_APP=1 环境变量。

**Comment by hhtower** [comment]
thanks。
