### ISSUE TITLE
[Feature] 每添加新的面具请应用默认设置

### ISSUE THREAD

**Issue by Iitianci** [Yidadaa/ChatGPT-Next-Web#2218]
请添加上如下功能:
每添加新的面具请应用默认设置
目前后台设置的模型,相关性的设置,只有新建一个空白聊天才会应用,当选择一个新的面具,却使用了内置的设置,需要自己重新修改,请在后台设置添加一个功能:每次新增新的面具应用当前设置的默认设置,而不是内设设置

**Comment by Yidadaa** [comment]
你对面具的理解有偏差，面具就是用来让你存储不同的设置的，如果你想让面具用全局设置，编辑当前对话设置，然后勾选下面的选项：

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/33d6fcc8-40ce-4f35-9de5-39404b00a79c)
