### ISSUE TITLE
[Feature] 支持多key轮询

### ISSUE THREAD

**Issue by Iitianci** [Yidadaa/ChatGPT-Next-Web#2219]
后台设置可以提供多个key,系统轮询进行使用key进行调用

**Comment by Yidadaa** [comment]
公众号：《我的代码会好吗》

**Comment by Yidadaa** [comment]
公众号：《我的代码会好吗》

**Comment by ilolita945** [comment]
实测并不可用

**Comment by Yidadaa** [comment]
@ilolita945 已经有 200 多人付费了，教程是不会有问题的

**Comment by ilolita945** [comment]
> @ilolita945 已经有 200 多人付费了，教程是不会有问题的

我自己也付费了，照着做都不行，而且新版的也不适用

**Comment by ilolita945** [comment]
> @ilolita945 已经有 200 多人付费了，教程是不会有问题的

不是说付费就代表没问题，不付费能看吗？

**Comment by Yidadaa** [comment]
把报错截图贴一下，不然我不知道你哪里弄错了。

**Comment by zhangbinhui** [comment]
教程可以用，我唯一担心的只是多key轮询ip被openai封掉

>
