### ISSUE TITLE
请教本地部署的问题，如何设置才能本地开发，按照文档部署提示超时

### ISSUE THREAD

**Issue by PartnerDAO** [Yidadaa/ChatGPT-Next-Web#2220]
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在本地开发中 始终提示超时，错误信息如下。已经配置代理，并设置了环境变量，添加了 KEY 。已经部署了代理，并设置了环境变量，并且增加到了代理中。使用项目提供的 base_url 地址可以。 使用官方的不行。请指点一二 ，谢谢。

 cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
**如何复现**
在对话框中输入既可以复现。
**截图**
<img width="624" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16472262/f9dba172-e779-4f78-9b59-16427dcdfbc8">

**Comment by PartnerDAO** [comment]
并且不明原因，输入密码项的表单总丢失，看不见！

**Comment by Yidadaa** [comment]
openai 服务国内无法直连，你用官方的当然会超时。
