### ISSUE TITLE
[增加“快捷指令”排序] 

### ISSUE THREAD

**Issue by HotelEnglish** [Yidadaa/ChatGPT-Next-Web#2221]
内置的提示词，有部分与个人的专业相去甚远，所以自己新建了一些，当在聊天界面使用“快捷指令”时，默认显示的是提示词的最后一条，而新建的提示词却在最上面，不是太方便，希望可以将新建的提示词默认放在最后面，或者将聊天界面的“快捷指令”打开的默认位置跟随新建的提示词的位置。或者增加所有的提示词按首字母排序，方便选择。再次感谢作者提供如此优秀的开源项目！

**Comment by Yidadaa** [comment]
最新代码已经调整显示逻辑，优先展示用户添加的自定义提示词。
