### ISSUE TITLE
Windows安装打开闪退

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [Yidadaa/ChatGPT-Next-Web#2223]
ChatGPT.Next.Web_2.8.6_x64-setup.exe
打开闪退

**Comment by Yidadaa** [comment]
windows 版本？

**Comment by LiWeiQiangAndroid** [comment]
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎5/‎22
操作系统版本	22631.1830
体验	Windows Feature Experience Pack 1000.22642.1000.0

**Comment by LiWeiQiangAndroid** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17853766/e26ed396-a092-4d99-ad50-a6f08c642ebd)

**Comment by LiWeiQiangAndroid** [comment]
没效果

**Comment by Yidadaa** [comment]
@LiWeiQiangAndroid 那先用网页版吧，网页版功能会更全一点

**Comment by LiWeiQiangAndroid** [comment]
好的
