### ISSUE TITLE
无论发什么都提示You exceeded your current quota, please check your plan and billing details[Bug] 昨天还能用，我不是个例吧

### ISSUE THREAD

**Issue by zbin-x** [Yidadaa/ChatGPT-Next-Web#2229]
无论发什么都提示You exceeded your current quota, please check your plan and billing details[Bug] 昨天还能用，我不是个例吧

**Comment by fyl080801** [comment]
盲猜免费的5刀过期了

**Comment by zbin-x** [comment]
好吧，是API的5美刀过期了

**Comment by zbin-x** [comment]
这个有效期到期了![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/50869296/9b6dd2a6-c63c-4686-bccd-3a51426a33b8)
