### ISSUE TITLE
现在是未授权状态，请在设置页填写授权码。

### ISSUE THREAD

**Issue by zwingser** [Yidadaa/ChatGPT-Next-Web#223]
每次对话都提示这个,我确保项目配置已经包含的对应变量,但是每次打开对话,还是要重新点设置,输入api和授权码,请问这个是什么问题呢.
![image](https://user-images.githubusercontent.com/126068653/228793364-6b33462e-81a7-49ab-823a-c23b438b7c0c.png)
![image](https://user-images.githubusercontent.com/126068653/228793477-28be3aa3-c3ce-4466-85af-f92c09c69a63.png)

**Comment by zwingser** [comment]
我知道了, 原来不是在对话的时候，直接输入code就能继续使用了，是要到设置里面单独设置一下。不过每次启动个新界面，都需要设置一下，稍微有点麻烦了。最好聊天提示没有code，直接输入一下就能继续用。交互上会有好很多。既然不是bug，我先关闭issue了。

**Comment by huwan** [comment]
> 我知道了, 原来不是在对话的时候，直接输入code就能继续使用了，是要到设置里面单独设置一下。不过每次启动个新界面，都需要设置一下，稍微有点麻烦了。最好聊天提示没有code，直接输入一下就能继续用。交互上会有好很多。既然不是bug，我先关闭issue了。

支持，能直接对话框直接输入code就可以自动填写到设置里面或者提示的句子里能够直接跳转设置项就好了。
