### ISSUE TITLE
[Feature] markdown无法正常渲染

### ISSUE THREAD

**Issue by freedomspiritJohn** [Yidadaa/ChatGPT-Next-Web#2231]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/129288685/d7899401-696a-4638-8e71-65df67f643a2)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/129288685/844bd9b5-ba96-4ddf-a36c-9f257e9c32af)

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
希望可以像官网一样可以正常渲染
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/129288685/500058a8-3901-470d-947f-895840ac8543)

**Comment by Yidadaa** [comment]
检查一下自己是不是装了什么 latex 渲染插件，检查一下是不是装了翻译插件。

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/2f36d489-1322-4c1e-b068-a0654839ed3f)
