### ISSUE TITLE
[Bug] 本地部署测试安装其他包后启动报错

### ISSUE THREAD

**Issue by aforwardz** [Yidadaa/ChatGPT-Next-Web#2232]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我npm install redis，安装了一个node的redis客户端，链接：https://www.npmjs.com/package/redis ，按照示例来引用和初始化。但是yarn dev之后，server端出现‘fs’、‘os’、‘path’、‘stream‘等基础包module not found的问题，引用代码为：
```
import { createClient } from 'redis';

const client = createClient();

client.on('error', err => console.log('Redis Client Error', err));
```

研究很久没研究明白，有人说在package.json里增加
```
  "browser": {
    "fs": false,
    "os": false,
    "path": false,
    "stream": false,
    "string_decoder": false,
    "net": false,
    "tls": false,
    "crypto": false
  }
```
但仍有报错，我在macos和ubuntu上同样操作测试，都有这种问题，求解答

**如何复现**
npm install redis
yarn dev

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19967761/7f03e684-80c8-4355-84c8-14cdeffe0492)

**一些必要的信息**
 - 系统：macos 12/ linux
 - 浏览器： chrome
 - 版本： 20230625
 - 部署方式：本地部署测试

**Comment by Yidadaa** [comment]
nextjs edge function 不支持大多数数据库客户端，如果你要用，就改 runtime 成 nodejs：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/ad2bc7da9618957fb728e13873865d1f055e1c43/app/api/openai/%5B...path%5D/route.ts#L52

**Comment by aforwardz** [comment]
好的，谢谢！
