### ISSUE TITLE
对话记录是否可以缓存到本地数据库

### ISSUE THREAD

**Issue by catchfishday** [Yidadaa/ChatGPT-Next-Web#224]
大佬可否将聊天记录保存到本地或者远程数据库，根据提问关键字做一个类似热搜功能

**Comment by Darrenzzy** [comment]
建议别这么干，你无法知道人们有多能问，\捂脸

最简单的是给用户保存cookie到本地就行，这样用户每次打开都能看到历史，和你期望的效果一样。

**Comment by Yidadaa** [comment]
不准备加数据库，可能存在法律风险。
