### ISSUE TITLE
[Bug] BASE_URL change has no impact...

### ISSUE THREAD

**Issue by DaniEnsi** [Yidadaa/ChatGPT-Next-Web#2243]
**Describe the bug**
Uses localhost:3000 as `BASE_URL` even though I defined it differently...

**To Reproduce**
1. `BASE_URL = https://example-url.com`
2. Deploy or run local server
3. completion requests go to `https://localhost:3000/api`... or when deployed to `https://deployed_domain.com/api`...

**Expected behavior**
Should use https://example-url.com/api/...

**Deployment**
- Local Dev and Vercel

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc
 - Version: 16.2

**Comment by Yidadaa** [comment]
1. check your settings page, make sure this value is `/api/openai`:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/3a99d077-30d8-45da-9730-4e6fff45274d)

2. change your `.env.local` locally, and run `yarn dev`, and check the running log, it should print the `BASE_URL` on every request.
3. if you are deploying on vercel, each time you changed the env vars, you have to redeploy the project to make it take effects.
