### ISSUE TITLE
[Feature] 在聊天界面直接修改预设

### ISSUE THREAD

**Issue by daiaji** [Yidadaa/ChatGPT-Next-Web#2248]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
面临的问题是无法直接在聊天界面修改预设内容，而必须前往设置菜单进行修改，这样的设计显得有些违背直觉。在聊天界面内修改预设内容，不仅可以提高编辑效率，还能更快捷地进行预设编辑。
此外，我认为现有的提示气泡只有在预设内容被隐藏时才发挥作用。相比之下，使用可点击的分割线来标示预设内容会更为直观清晰，让用户明确分辨出分割线上方的内容即为预设内容。
实例图片
![img](https://user-images.githubusercontent.com/25875791/246640368-32299c46-bb6b-472e-b6c6-3d42502a24d3.png) 
**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
点击分割线跳转到设置实际引导也没太必要做，因为在聊天界面直接修改预设肯定比设置里调整更好用。

**Comment by Yidadaa** [comment]
1. 已经添加的预设消息，直接点击头像是可以直接编辑的；
2. 点击固定按钮，可以将对应的消息固定到预设对话；
3. 你的代码太老了，没有我说的这几个功能，升级代码。

**Comment by daiaji** [comment]
> 1. 已经添加的预设消息，直接点击头像是可以直接编辑的；
> 
>     2. 点击固定按钮，可以将对应的消息固定到预设对话；
> 
>     3. 你的代码太老了，没有我说的这几个功能，升级代码。

我试试。

**Comment by daiaji** [comment]
> 1. 已经添加的预设消息，直接点击头像是可以直接编辑的；
> 
>     2. 点击固定按钮，可以将对应的消息固定到预设对话；
> 
>     3. 你的代码太老了，没有我说的这几个功能，升级代码。

新建对话从面具继承的预设消息在聊天流里是无法通过点击头像编辑的。
[Imgur](https://i.imgur.com/mgtyqWA.mp4)
我在你部署的网站里测试，除了预设都能编辑。
