### ISSUE TITLE
[Bug] when change the apikey, 

### ISSUE THREAD

**Issue by DavidZhiXing** [Yidadaa/ChatGPT-Next-Web#2250]
Bug Description:
The bug I encountered is related to an invalid OpenAI key. I have updated the environment with a new key, but it only works on the client side and not on the server side.

Steps to Reproduce:
1. Change the key in Vercel '...'
2. Redeploy '....'
3. Test using your deployment URL '....'
4. Observe any errors that occur.

Expected Behavior:
Should get the response message

Screenshots:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11553856/c2be4048-214b-496d-8992-603c022b8e4a)

Deployment Details:

- Docker
- [x] Vercel
- Server

Desktop Information:
Chrome

**Comment by Yidadaa** [comment]
You must redeploy your vercel service to take effects.

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2
