### ISSUE TITLE
[Bug] Unordered numbered list rendered incorrectly

### ISSUE THREAD

**Issue by johan456789** [Yidadaa/ChatGPT-Next-Web#2254]
**Describe the bug**
Unordered numbered list rendered with incorrect numbering.

**To Reproduce**
Enter an unordered numbered list and it will be rendered with different numbers. I guess it's because it's rendered as a markdown.

**Expected behavior**
The numbering should be the same. 

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14802181/0e8c28b1-e8c7-4dbd-bd99-18cf8cc85a27)

**Deployment**
Vercel

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1 (22F82)
 - Browser: Google Chrome v114.0.5735.198 (5735.198)
 - Version: V2.8.7

**Comment by Yidadaa** [comment]
This is the standard behavior of markdown. You can try entering the text below in the comment section on GitHub, and you will see that it will be rendered as an ordered list:

```
12321. a
12. b
13132. c 
```

we got:

12321. a
12. b
13132. c
