### ISSUE TITLE
[Feature] 关于max_tokens在代码中的作用

### ISSUE THREAD

**Issue by youqiang95** [Yidadaa/ChatGPT-Next-Web#2258]
qq群满了加不了，issue也查了，一点小困惑： 我查看代码发现，max_tokens除了会传给后端之外，还有作为限制上下文长度的阈值的作用（app/store/chat.ts: getMessagesWithMemory）, 我的理解是这个max_tokens是告诉API接口回复tokens的限制，不是上下文的限制，UI设置页面展示的也是单次回复的最大限制tokens, 但是我从代码中看，也会用这个数去限制上下文的tokens数，我的理解是这俩是两个东西，比如我可以让回复短一些，同时让上下文长一些，以便更详细描述信息，但我看代码这一个值会同时限制上下文长度和回复长度，是我理解错了吗？

**Comment by Yidadaa** [comment]
max_tokens 其实并不会被发送到服务端：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/38f2495cf6ed24f8d5202a251281e14b066c1ecf/app/client/platforms/openai.ts#L58-L66

原因是很多人不会用这个参数，然后导致 openai 报错，所以后来干脆去掉了，但确实会用来约束历史消息的长度，不会约束回复长度。

**Comment by reece00** [comment]
选项描述应该修改一下，标题和描述冲突，和实际功能也不一致

**Comment by Yidadaa** [comment]
@reece00 你用这个字段是用来干啥的？我感觉实际使用的时候，没什么用

**Comment by youqiang95** [comment]
@Yidadaa 感谢答疑，查看了最新代码，确实不会发到后端，不过这个参数对我限制上下文长度仍然有点用，比如对于上下文相关不大的情况（非多轮对话），我会调小这个值，减少token费用

**Comment by reece00** [comment]
> @reece00 你用这个字段是用来干啥的？我感觉实际使用的时候，没什么用

就是按照字面意思设置个一万防止无限输出花钱（没去了解回复上限）。要这么说的话现在这个选项可以改名为上下文长度上限。的确是没啥用，聊天环境对话截断了基本就不能用了，真api用户才用截断

**Comment by Yidadaa** [comment]
@reece00 不用担心无限输出，openai 最长的模型输入就是 gpt4-32k，也就是 32k token 长度，大部分人都没有这个权限。普通人能用到的最长上下文 api 是 gpt3.5-16k，想输出更多都没辙。

**Comment by QinWinner** [comment]
> @reece00 不用担心无限输出，openai 最长的模型限制就是 gpt4-32k，也就是 32k token 长度，大部分人都没有这个权限。普通人能用到的最长上下文 api 是 gpt3.5-16k，想输出更多都没辙。

请求添加max_token 参数，目前新本的的gpt4.0 token上限实在是太高了。

**Comment by QinWinner** [comment]
@Yidadaa  目前新版的gpt-4-vision-preview，max_token非常的巨大。所以请求使得max_token 参数能够起作用。
