### ISSUE TITLE
[Bug] 隐藏边框白线

### ISSUE THREAD

**Issue by techkoala** [Yidadaa/ChatGPT-Next-Web#2265]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
边框的白线在暗色模式下比较明显，不太好看，希望可以在放大模式下隐藏边框白线

**如何复现**
必现，选择放大页面

**截图**
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/67769327/d162a60f-fe8e-4f88-b277-488fd29a0f82)

**一些必要的信息**
 - 系统：比如 windows 11
 - 浏览器： chrome, edge firefox
 - 版本： 2.8.7
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
把你的 dark reader 关了：

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/5dfaf304-6e2f-49fc-9a7f-663fce7c813e)

**Comment by Yidadaa** [comment]
已经确认这个白框是 dark reader 给你加的：

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/d16f2dd6-2772-4646-8e65-0658d182205d)
