### ISSUE TITLE
[Feature] User Question Suggestions 自动生成追问建议

### ISSUE THREAD

**Issue by mushan0x0** [Yidadaa/ChatGPT-Next-Web#2270]
**你想要什么功能或者有什么建议？**
类似于 NewBing 的相关搜索，有些时候可以省去自己输入提问的步骤

**有没有可以参考的同类竞品？**
<img width="694" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/29084441/887205ed-c621-4640-9051-d3634c0a094d">

**Comment by Yidadaa** [comment]
尝试做了一下，效果不是很好，暂时搁置。

https://github.com/Yidadaa/ChatGPT-Next-Web/tree/suggestion
