### ISSUE TITLE
[Bug] 本地部署后版本号不更新

### ISSUE THREAD

**Issue by Cyrker** [Yidadaa/ChatGPT-Next-Web#2274]
**描述问题**
尝试直接拉取或者fork到自己的仓库后拉取
运行 yarn install && yarn build && yarn start 后 
版本号仍然显示
当前版本：v2.8.6
发现新版本：v2.8.8

尝试过使用无痕模式流览和清除本地缓存 没有效果

**如何复现**
本地部署web

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/38664017/fd00495c-e563-4e08-b244-00ef9bc237f9)

warning package.json: License should be a valid SPDX license expression
$ cross-env BUILD_MODE=standalone next build
[Next] build mode standalone
[Next] build with chunk:  true
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
- warn Compiled with warnings

**一些必要的信息**
 - 系统：Ubuntu 22.04.2
 - 浏览器：chrome
 - 版本： v2.8.6
 - 部署方式：服务器部署

**Comment by Yidadaa** [comment]
检查一下你代码里的这个文件：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/300d1a24-1045-44f7-9950-306dbab3ab95)

看看版本号是否是对的。

**Comment by Cyrker** [comment]
> 检查一下你代码里的这个文件： ![image](https://user-images.githubusercontent.com/16968934/251475240-300d1a24-1045-44f7-9950-306dbab3ab95.png)
> 
> 看看版本号是否是对的。

是正确的 2.8.8
https://github.com/Cyrker/ChatGPT-Next-Web/blob/main/src-tauri/tauri.conf.json

**Comment by Yidadaa** [comment]
你可以 f12 打开浏览器控制台，看看你前端拿到的版本号：

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/ab0398bb-0fc7-4e01-a259-f6e781fd59ba)

**Comment by Cyrker** [comment]
> 你可以 f12 打开浏览器控制台，看看你前端拿到的版本号：
> 
> ![image](https://user-images.githubusercontent.com/16968934/251623883-ab0398bb-0fc7-4e01-a259-f6e781fd59ba.png)

前端拿到的还是2.8.6...
请问您一下
这应该怎么解决呢？
