### ISSUE TITLE
[Feature] 怎样打包客户端？

### ISSUE THREAD

**Issue by henryhu712** [Yidadaa/ChatGPT-Next-Web#2278]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
需要有怎样打包客户端的文档，用户才可以开发自己的客户端。

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by Yidadaa** [comment]
`yarn app:build`

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/42561d04de53dd9d2f1a8ef75ab2746b17aa43e7/package.json#L13
