### ISSUE TITLE
[Bug] DISABLE_GPT4 设置为1还是能选

### ISSUE THREAD

**Issue by EchoShoot** [Yidadaa/ChatGPT-Next-Web#2280]
**Describe the bug**
我是用 docker 部署的 Version:    24.0.2

**To Reproduce**
  chatgpt-next-web:
    container_name: chatgpt-next-web
    image: yidadaa/chatgpt-next-web:latest
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - HIDE_USER_API_KEY=1
      - DISABLE_GPT4=1
      ...

在设置里面能看到 gpt4相关模型不是禁用状态

**Comment by Yidadaa** [comment]
现在会自动使用 /list/models 检测可用模型，如果 `/list/models` 接口不可用，就会默认启用所有模型。

你用的是中转接口？可以问一下接口服务商是否支持 `/list/models`。

**Comment by starzhoume** [comment]
OpenAI open API4.0 interface for ChatGPT Plus,  My chatgpt web next version is 20230623.
How to switch to  API4.0 interface?

**Comment by kaifeng0502** [comment]
如上所说，模型选择都是灰色 代表都可用，但如何指定GPT4呢

**Comment by LYnnazo** [comment]
> 如上所说，模型选择都是灰色 代表都可用，但如何指定GPT4呢

我也在纠结这个问题，本地下载安装的，也有gpt4的API，也可以选，但是输入后就弹出“model-not-found”。
要如何调整到gpt4以上版本呢？

**Comment by LYnnazo** [comment]
> 现在会自动使用 /list/models 检测可用模型，如果 `/list/models` 接口不可用，就会默认启用所有模型。
> 
> 你用的是中转接口？可以问一下接口服务商是否支持 `/list/models`。

> 
您好，我的接口地址是 https://chatgpt1.nextweb.fun/api/proxy
请问是这个接口的问题才导致无法选择gpt4以上版本吗？如果是接口服务商的问题？有解决方法吗？
非常感谢！
