### ISSUE TITLE
[Bug] DISABLE_GPT4 曾设置为1 现在设置为0无效

### ISSUE THREAD

**Issue by Erimus-Koo** [Yidadaa/ChatGPT-Next-Web#2281]
- 曾把 DISABLE_GPT4 设置为 1，有效。
- 现在把 DISABLE_GPT4 设置为 0，希望启用 GPT4。修改完参数并 Redeploy 之后，模型中 3.5 以外的仍旧为灰色。
- KEY 和 ORG_ID 均已设置，是否查询可用 Model 还未生效？如何自行确认可用 models？

**Comment by devyujie** [comment]
直接把环境变量删了，重新部署不就行了

**Comment by Yidadaa** [comment]
f12 打开控制台，可以看到通过接口查询到的支持的接口：

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/6e728826-6013-4428-9137-8d8ae9c99ff4)

**Comment by Yidadaa** [comment]
同时关注 #2280

**Comment by Yidadaa** [comment]
DISABLE_GPT4 如果不想启用，直接删掉，这个环境变量只要有东西，就会被判定为 true，所以直接删掉就行了。

**Comment by Erimus-Koo** [comment]
删掉再redeploy生效了

顺便提个小建议，切换模型建议从点击轮询，变成select/options，因为内容太多了，要点很多下才能切换。
或者能在设置里指定几个，比如选中 3.5turbo / 3.5-16k / 4，那前端点击轮询在三个中切换，就稍好一些。
