### ISSUE TITLE
[Feature] 设置DISABLE_GPT4仅对使用访问密码的用户生效

### ISSUE THREAD

**Issue by dale0525** [Yidadaa/ChatGPT-Next-Web#2283]
搭了服务给其他人使用，用的自己的API KEY，给其他人的是访问密码。
今天拿到了GPT4的API权限，希望可以只有自己能使用（毕竟贵），但发现没有这个功能。
从我个人理解，如果其他人用他自己的API KEY的话，也没有必要对其限制使用GPT4？

**Comment by Yidadaa** [comment]
vercel 可以从 github 仓库部署两个版本，你可以通过环境变量来控制，一个有 gpt4，一个没有。
