### ISSUE TITLE
[本地启动ChatGPT-Next-Web服务正常，待打开界面后，输入消息时，报错] 

### ISSUE THREAD

**Issue by lewis-ing** [Yidadaa/ChatGPT-Next-Web#2286]
1、已经申请openai的KEY
2、本地启动ChatGPT-Next-Web服务正常，待打开界面后，输入消息时，报错，信息如下：

[Base Url] https://
[OpenAI]   [TypeError: fetch failed] {
  cause:  [Error: getaddrinfo ENOTFOUND v1] {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'v1'
}

**Comment by Yidadaa** [comment]
国内不能直连 openai api 服务。

**Comment by dutny** [comment]
> 国内不能直连 openai api 服务。

貌似不是代理的问题，我启了clash也一样，用postman能通，但是进页面就是3008
