### ISSUE TITLE
openai开放gpt4接口，模型直接选gpt-4不可用

### ISSUE THREAD

**Issue by liuzhaowei1** [Yidadaa/ChatGPT-Next-Web#2287]
openai开放gpt4接口，模型直接选gpt-4不可用，是还要改什么东西吗

**Comment by xming521** [comment]
我也是 ，自己搭了openai的接口代理

**Comment by Yidadaa** [comment]
报错截图呢？

**Comment by arslan2012** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8698442/2aa2cc90-ae9e-44a9-a3cb-e6de896a9127)
@Yidadaa

**Comment by arslan2012** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8698442/6d6ea5d1-cc64-40a1-8527-ab86cbb4ee48)

**Comment by xming521** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/32786500/e9c5c2d0-ecb0-4aff-a82f-f8df1e92396d)
只能选中GPT3 2.8.8版本

**Comment by liuzhaowei1** [comment]
> 我也是 ，自己搭了openai的接口代理

然后，能用嘛？

**Comment by liuzhaowei1** [comment]
> 报错截图呢？

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/86914882/3ed4e1ef-2c91-452d-b959-738af574ad39)
