### ISSUE TITLE
[Bug] 使用gpt4面具时，会切换到被禁用的gpt4模型

### ISSUE THREAD

**Issue by Pnut-GGG** [Yidadaa/ChatGPT-Next-Web#2290]
**Describe the bug**
使用gpt4面具时，会切换到被禁用的gpt4模型
禁止gpt4模型的同时禁用gpt4模型的面具

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
此时服务端会拒绝服务。

**Comment by Pnut-GGG** [comment]
为什么不在前端就进行限制呢，前端显示可用会误导用户。
