### ISSUE TITLE
https://github.com/Yidadaa/ChatGPT-Next-Web/edit/main/app/components/chat.tsx 第195行： 这里的：移除事件监听器为什么使用onCompositionStart和onCompositionEnd，应该是bug吧！！！

### ISSUE THREAD

**Issue by Friedrich-hue** [Yidadaa/ChatGPT-Next-Web#2291]
https://github.com/Yidadaa/ChatGPT-Next-Web/edit/main/app/components/chat.tsx 第195行：
这里的：移除事件监听器为什么使用onCompositionStart和onCompositionEnd，应该是bug吧！！！

window.removeEventListener("compositionstart", onCompositionStart); window.removeEventListener("compositionend", onCompositionEnd);

**Comment by Yidadaa** [comment]
#2252
