### ISSUE TITLE
[Bug] GPT-PLUS & API 付费不能使用GPT4 The paying user can not use GPT4

### ISSUE THREAD

**Issue by erfect2020** [Yidadaa/ChatGPT-Next-Web#2293]
**Describe the bug**
我是付费的用户，plus+api付费，但是不能gpt4是灰色按钮，不可选的状态。

我确定DISABLE_GPT4没有打开

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="216" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/94505384/5f696dd9-2153-4401-8688-7d6b7f655208">

<img width="1036" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/94505384/12ed92f3-f536-42c5-8e0f-290aad520ce2">

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [ mac ]
 - Browser [chrome]
 - Version [the latest]

**Additional Logs**
想调查一下有人有类似的情况嘛

**Comment by ProgrammerHuang** [comment]
我的也是, GPT4的选项都是禁用的,
不过我的是docker的, 晚上还特意更新了.
是不是模型名称有变化, 还没有支持?

**Comment by erfect2020** [comment]
原因可能是openai没开放

**Comment by Yidadaa** [comment]
plus 用户和 api 用户是独立的，openai 这波只对 api 付费用户开放，plus 用户不在开放范围内。

**Comment by ProgrammerHuang** [comment]
> plus 用户和 api 用户是独立的，openai 这波只对 api 付费用户开放，plus 用户不在开放范围内。

我的是api付费的

**Comment by erfect2020** [comment]
I am the API paying user.

**Comment by erfect2020** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> Plus users and api users are independent. This wave of openai is only open to paid api users, and plus users are not included.

我是API 付费用户
