### ISSUE TITLE
[Bug] 迁移配置时会丢失以往配置

### ISSUE THREAD

**Issue by imldy** [Yidadaa/ChatGPT-Next-Web#2295]
**Describe the bug**

貌似每次获取配置时，会执行迁移`migrate`函数，判断配置的版本，而代码中`StoreKey.Config`的`version`更新后，造成代码与LocalStorage版本不一致，会执行以下代码：
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/3432d4df29d3c289b4f8e1cbcdf41cda9f43d6ba/app/store/config.ts#L144-L152

这里的代码并没有获取之前用户自定义的配置，也没有使用默认配置：
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/3432d4df29d3c289b4f8e1cbcdf41cda9f43d6ba/app/store/config.ts#L23-L51

而是使用魔法值（可能用词不太准确）给变量赋值。

请考虑迁移配置时获取用户已有配置

**Expected behavior**

更新代码后丢配置。

**Comment by Yidadaa** [comment]
真实原因是这里的版本号用法错了。

**Comment by imldy** [comment]
> 真实原因是这里的版本号用法错了。

是的，我认为应该是判断旧版本号，然后给新版本的新配置项赋值。

但因为我不确定每个版本配置项的区别，所以我的PR当前仅仅是解决了这个BUG，并没有正确使用版本号。
