### ISSUE TITLE
[Bug] You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by ZhangMin1998** [Yidadaa/ChatGPT-Next-Web#2304]
You exceeded your current quota, please check your plan and billing details.
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/66857222/257c73e0-17e6-4307-9875-7e1b09d9f98c)
这个怎么解决呀
what should i do ???

**Comment by Yidadaa** [comment]
在提 issue 之前，你应该先在 issue 区搜索一下，或者去看看项目的 faq。
