### ISSUE TITLE
[help me求助] You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by ZhangMin1998** [Yidadaa/ChatGPT-Next-Web#2305]
You exceeded your current quota, please check your plan and billing details.
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/66857222/31ada393-a14e-4325-8bf8-593bd27a2fc0)
请问怎么解决
what should i do ??

**Comment by erfect2020** [comment]
充钱

**Comment by zlfzy** [comment]
字面意思
