### ISSUE TITLE
[Bug] 一个小问题

### ISSUE THREAD

**Issue by ourcss** [Yidadaa/ChatGPT-Next-Web#2307]
重现过程
无痕浏览器下，当我使用自己的key，在设置中输入的时候，然后选择模型模型都为不可选，必须强制刷新一下页面才能检测到那些模型可用

**Comment by ourcss** [comment]
截止到现在我拉取的最新的代码，在本地部署，发现还是一样的问题，在对话页面点击机器人图标也会有相同bug出现

**Comment by itcodes** [comment]
对。。我的也是

**Comment by Yidadaa** [comment]
关注 #2280
