### ISSUE TITLE
快捷指令

### ISSUE THREAD

**Issue by scyslz** [Yidadaa/ChatGPT-Next-Web#231]
能出个快捷指令的教程吗？
1. code不知道是怎么传参
2. 每次对话请求都带了上下文的信息，可不可不用携带

**Comment by GOWxx** [comment]
## 问题1
 点击`deploy` 一键部署时，链接中可以去掉参数
目前的链接是`https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2FYidadaa%2FChatGPT-Next-Web&env=OPENAI_API_KEY&env=CODE&project-name=chatgpt-next-web&repository-name=ChatGPT-Next-Web`
可以去掉其中的 `env=CODE` 变成
`https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2FYidadaa%2FChatGPT-Next-Web&env=OPENAI_API_KEY&project-name=chatgpt-next-web&repository-name=ChatGPT-Next-Web`

## 问题2

设置面板理 附带历史消息数 可以设置成 0 应该就可以了
