### ISSUE TITLE
[Bug] 模型无法手动切换, 选项置灰

### ISSUE THREAD

**Issue by zuilintan** [Yidadaa/ChatGPT-Next-Web#2311]
**Describe the bug**

**To Reproduce**
设置页模型无法切换, 可选项置灰, 无法点击

**Expected behavior**
可以手动切换

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34953840/9950cfd7-5ff1-46a4-b164-a6b2b660d98f)

**Deployment**
- [ ] Vercel

**Desktop (please complete the following information):**
 - OS: Android, Windows

**Smartphone (please complete the following information):**
 - Browser Chrome

**Comment by zuilintan** [comment]
已输入管理员密码, 可正常查询到余额, 说明API是生效的

**Comment by Yidadaa** [comment]
1. 刷新页面
2. 关注 #2280
