### ISSUE TITLE
[Bug] 自定义模型后，在选择模型下拉框中不可选中

### ISSUE THREAD

**Issue by ourcss** [Yidadaa/ChatGPT-Next-Web#2313]
当我使用第三方中转api时，添加了api地址和他们自己的秘钥，如果添加模型的话，是不可选中的状态

**Comment by Yidadaa** [comment]
升级到最新的代码

**Comment by ourcss** [comment]
刚刚测试了，还是不能选中的状态，比如我租用的api有poe逆向 的模型，填写他们给我的模型名字，在选择模型时还是不能选自定义的模型

**Comment by Yidadaa** [comment]
> 

设置项新增了自定义模型名，把自定义名字加进去

**Comment by Yidadaa** [comment]
#2303
