### ISSUE TITLE
在桌面端选择prompt时容易出现选中后不显示的问题

### ISSUE THREAD

**Issue by ClarenceDan** [Yidadaa/ChatGPT-Next-Web#232]
桌面端点击prompt 可能并不会加载到对话框，有时候双击点击后能加载。
移动端暂时没有发现问题

https://user-images.githubusercontent.com/48417261/228807284-8a6a954b-416f-4b5d-acb7-60c2aa805af8.mp4

**Comment by wyonghao** [comment]
这个桌面的应该是bug，和下面的report内容类似：
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/182

**Comment by Yidadaa** [comment]
重复 #182
