### ISSUE TITLE
[Bug] 清空接口地址后，如果输入密码访问就报错，必须改回/api/openai/才能使用

### ISSUE THREAD

**Issue by ourcss** [Yidadaa/ChatGPT-Next-Web#2321]
<img width="642" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/105355582/464af59c-aa3e-43c7-bc72-35edae1a587a">

**Comment by Yidadaa** [comment]
确实，你不填就会使用 openai 的接口，这样有什么问题吗？

**Comment by imldy** [comment]
我猜楼主的意思是访问密码应该在固定的后端中使用，而不是自定义的接口地址/后端/base_url。

即：使用访问密码时，不允许自定义后端地址。使用api_key时，使用此处定义的接口地址/后端地址/base_url。此地址只与api_key绑定。

而目前实现是feature还是bug？
