### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Huang-JunDong** [Yidadaa/ChatGPT-Next-Web#2322]
大佬您好，请问在gpt回答过程中可不可以实现官网那种打字机效果，目前版本回答是隔几秒输出一大段内容，感觉体验不是特别好，如果能一个个字输出，这样用户等待时间会明显感觉减少，当然这只是一个建议

**Comment by Yidadaa** [comment]
cf 的 cdn 会影响流式传输的效果，你用演示站试一下对比一下你自己的就知道了。
