### ISSUE TITLE
[Bug] You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by bestchinacoder** [Yidadaa/ChatGPT-Next-Web#2323]
我是个人免费账户.为什么配置了自己的 key 之后,会有配额上的限制? 而且我查看了配额的使用,并没有超出限制.
报错信息如下

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

我在 gpt 的官方聊天窗口中提问,就没有这个问题.

**Comment by bestchinacoder** [comment]
> 我是个人免费账户.为什么配置了自己的 key 之后,会有配额上的限制? 而且我查看了配额的使用,并没有超出限制. 报错信息如下
> 
> { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": "insufficient_quota" } }
> 
> 我在 gpt 的官方聊天窗口中提问,就没有这个问题.

The English translation is as follows
-----
I have a free personal account. Why is there a quota limit after I configure my own key? And I have checked the quota usage and it is not exceeded.
The error message is as follows:

`{
"error": {
"message": "You exceeded your current quota, please check your plan and billing details.",
"type": "insufficient_quota",
"param": null,
"code": "insufficient_quota"
}
}`

I asked the question in the official chat window of gpt, and I didn't have this problem.

**Comment by Yidadaa** [comment]
余额过期。

**Comment by lmx01** [comment]
请问博主，这个问题解决了吗？谢谢

**Comment by woshichenghaibo** [comment]
> 余额过期。

也就是说这个openai账号没用了吗
