### ISSUE TITLE
[Bug] 为什么gpt4模型无法被选中

### ISSUE THREAD

**Issue by sysy007uuu** [Yidadaa/ChatGPT-Next-Web#2325]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34132715/dfdece82-4707-4aaf-9b41-0dcfb30f4af4)
gpt4是灰色的，我的api支持gpt4，但是用不了

**Comment by Yidadaa** [comment]
同步你的代码到最新。
