### ISSUE TITLE
设置界面中的数值显示问题

### ISSUE THREAD

**Issue by wyonghao** [Yidadaa/ChatGPT-Next-Web#233]
设置界面中的数值显示，在README.md的截图中，是有显示的，例如下图highlight的
“附带历史消息数”  - 4
”随机性“ - 1
<img width="784" alt="image" src="https://user-images.githubusercontent.com/4404209/228809505-949c6a15-d41d-4431-8fdb-5d484c607930.png">

但是在运行的server和demo中，这个数值没有显示，不知道到底设置的是啥，不知道是不是和浏览器有关？测试mac上的firefox和chrome都没有显示，如图下：
<img width="575" alt="image" src="https://user-images.githubusercontent.com/4404209/228810631-a6aad66b-d45f-445c-b664-daa3d8bdc015.png">

**Comment by Yidadaa** [comment]
firefox 上确实不会显示，确认为 bug

**Comment by AprilNEA** [comment]
可能是字体问题
