### ISSUE TITLE
[Bug] gpt4无法使用

### ISSUE THREAD

**Issue by sysy007uuu** [Yidadaa/ChatGPT-Next-Web#2330]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34132715/c38d42aa-2263-4531-bc57-61ff4b9ca815)
我的apikey是走镜像base_url的，验证的时候会显示不支持4.0，实际上是能用的，能不能把验证的过程去掉，不然还是用不了，之前我f12强制把disable去掉选gpt4是能用的，更新到2.8.9用不了了

**Comment by sysy007uuu** [comment]
现在3.5好像也用不了了
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34132715/e305df9e-b88f-4749-beb1-b8431775e8bd)

**Comment by sysy007uuu** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34132715/faddebc8-6312-4c19-94e4-095a5da0510d)
其他镜像站里我的key能使用，nextweb更新到2.8.9以后，所有模型都无法使用了

**Comment by sysy007uuu** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34132715/08ac97e8-396b-4207-bab2-51886211210e)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34132715/f3b0c2d7-8651-46d2-aeb0-040c53c5607f)

找到问题了，手动设置url和api可以跑，但是用环境变量就不行，这是什么原因，项目已经重新部署3次了，用环境变量确实没法用了。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34132715/3f6dc3f8-a611-49bd-a734-57ebd57f7bea)

**Comment by Yidadaa** [comment]
你的 BASE_URL 用的啥？

**Comment by sysy007uuu** [comment]
刚才2.8.8是能用的，更新到2.8.9就不行了

**Comment by ktangel** [comment]
我是一直用不了GPT4，正好我看7月6号之后官方发布说全部付费用户都可以使用了，然后我更新到了2.9.0，看我的GPT4那些还是选不了。不知道是不是BUG

**Comment by ourcss** [comment]
@ktangel  那你得登上openai看看你有没有4.0权限，现在是开放了一部分付费用户，并不是你付费就自动开通了

**Comment by Yidadaa** [comment]
检查你的 vercel 环境变量是不是加了 DISABLE_GPT4
