### ISSUE TITLE
[Bug] iOS 端报错，不能使用

### ISSUE THREAD

**Issue by qinxs** [Yidadaa/ChatGPT-Next-Web#2332]
**Describe the bug**
iOS 端报错，不能使用。提示某个js文件丢失

**Screenshots**
![1-报错截图](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/13647698/7c26df6d-cce1-4b17-bb04-137c6eac753d)

![2-控制台](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/13647698/3e8cb8fa-b853-46fd-9458-e0940b1ef0fd)

![3-系统环境](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/13647698/4920642f-77a1-4dfc-a6d3-ee1f8f9bb3fd)

**Deployment**
- [x] Vercel

**Smartphone (please complete the following information):**
 - Device:  iPhone8
 - OS: iOS12.4.1
 - Browser: Alook（safari上也是一样的错误）
 - Version: 18.2

> 可能低版本safari不支持ES6的[可选链](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Optional_chaining)语法 `?`（如何是，建议将bable转换的兼容性设置高一些）

> User Agent: 
> Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1

**Additional Logs**
> Oops, something went wrong!
>
> ChunkLoadError: Loading chunk 6172 failed.
(missing: https://chatgpt.7bxing.com/_next/static/chunks/fb2b3725.c750bcec60bef8ea.js)
Lazy
Suspense
LoadableComponent
div
div
R@https://chatgpt.7bxing.com/_next/static/chunks/app/page-ed93453a31db1ffb.js:1:30279
div
Q@https://chatgpt.7bxing.com/_next/static/chunks/app/page-ed93453a31db1ffb.js:1:36066
L@https://chatgpt.7bxing.com/_next/static/chunks/4241-4c5ef87c2cbefeb1.js:27:20544
p@https://chatgpt.7bxing.com/_next/static/chunks/4241-4c5ef87c2cbefeb1.js:27:986
m@https://chatgpt.7bxing.com/_next/static/chunks/app/page-ed93453a31db1ffb.js:1:23772
ee@https://chatgpt.7bxing.com/_next/static/chunks/app/page-ed93453a31db1ffb.js:1:37027
O@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:19675
i@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:29326
c@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:29414
l@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:27442
P@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:21311
c@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:15929
m@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:18485
g@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:19369
a@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:31132
E@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:21508
body
html
i@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:29326
c@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:29414
a@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:27284
l@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:27442
T@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:9644
l@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:15277
c@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:15929
M@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:13430
C@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:4283
N
x@https://chatgpt.7bxing.com/_next/static/chunks/5769-7dc3eca27733ae19.js:1:4667

> [Config] got config from build time 
Object {version: "v2.8.8", commitDate: "1688912623000", commitHash: "300f023d2a3e52511b3caf981c09fd4e56b02beb", buildMode: "standalone", isApp: false}
[Config] got config from server 
Object {needCode: true, hideUserApiKey: false, disableGPT4: true, hideBalanceQuery: false}
[Models] undefined
Unexpected token '.'
Loading chunk 6172 failed.
(missing: https://chatgpt.7bxing.com/_next/static/chunks/fb2b3725.c750bcec60bef8ea.js)

**Comment by qinxs** [comment]
补充说明：
https://chatgpt.7bxing.com/_next/static/chunks/fb2b3725.c750bcec60bef8ea.js 这个js文件在手机上是可以正常访问的

**Comment by Yidadaa** [comment]
如果你是用 vercel 部署或者自行从源码编译部署，环境变量里增加 DISABLE_CHUNK=1 ，可以避免此错误。

Docker 不支持此用法。

**Comment by itcthienkhiem** [comment]
i have add DISABLE_CHUNK=1 but now not loading to page???

**Comment by itcthienkhiem** [comment]
loading forever ??
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/2140355/65df6c68-4bff-41a0-bcf1-674726dc9c2c)

**Comment by qinxs** [comment]
> loading forever ?? ![image](https://user-images.githubusercontent.com/2140355/252370925-65df6c68-4bff-41a0-bcf1-674726dc9c2c.png)

一样的情况！

**Comment by lehhair** [comment]
我用电脑上的edge浏览器也是这样
