### ISSUE TITLE
[Feature] 关于消息的操作按钮

### ISSUE THREAD

**Issue by Cyrker** [Yidadaa/ChatGPT-Next-Web#2334]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

<img width="347" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/38664017/753150a0-5924-40da-b1d8-7b3ce6bafc99">

**你想要什么功能或者有什么建议？**
之前有一个版本这个按钮是在消息框底部的，更新到2.8.9后被移动到顶部了，对长的回复不太友好，需要滑动到消息顶部再操作

**Comment by Yidadaa** [comment]
目前来看没有收到太多负面反馈，如果一周之内没有更多反馈，此交互将不会修改。

**Comment by reece00** [comment]
上下都显示不得了，二选一总有问题

**Comment by Anfernee17** [comment]
赞同将消息改到底部，对于长消息或者上班摸鱼开非全屏的时候比较方便，不用特地往上拉找功能按钮

**Comment by Cyrker** [comment]
另外重试按钮会把我这边的发言再一次发送出去，而不是直接回复对话，能否添加一个开关，让重新生成的对话覆盖之前生成的？

**Comment by Yidadaa** [comment]
@Cyrker 升级代码
