### ISSUE TITLE
[Feature] 新版本的重试没有覆盖之前的记录

### ISSUE THREAD

**Issue by mushan0x0** [Yidadaa/ChatGPT-Next-Web#2336]
**你想要什么功能或者有什么建议？**
新版本的重试没有覆盖之前的记录，这样会导致重试后的回复跟之前的没有太大差别，因为gpt会参考上一次的回复结果，建议重试的时候跟之前一样覆盖掉之前的记录

**Comment by Yidadaa** [comment]
已知问题，今晚修复。
