### ISSUE TITLE
[Feature] enabled / disabled in contextual and memory prompts

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2347]
![SNAG-0205](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/b648d0f1-c94a-44c0-9f26-d62d343b9a9d)

that will be great feature

**Comment by Yidadaa** [comment]
why not just delete unused prompts?

**Comment by johnfelipe** [comment]
Because sometimes Is needed and sometimes not
Then enabled/disabled is a good choice

**Comment by Mydong** [comment]
> 为什么不直接删除未使用的提示呢？

借楼表达下：
【希望这里可以能拖动排序】
需求场景：
使用PIN之后，想要按照顺利联系上下午，就需要自上而下的依次去pin。
如果某一个PIN错了，就需要删除掉重新pin，或者全部删除；
因此，可能有一个可拖动的功能比较好。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14023137/144dde4c-5435-47eb-8596-ab5cbe75d923)

**Comment by johnfelipe** [comment]
drag and drop is already feature, tnks
only remains this feature enable / disable from context

**Comment by Yidadaa** [comment]
Adding this feature will make the data structure of the mask inconsistent, increase maintenance costs, and provide limited benefits. Therefore, we do not plan to add this functionality
