### ISSUE TITLE
[Bug] The model: `gpt-4-32k-0613` does not exist

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2349]
pls view this video:

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/5eaea62c-541e-4add-9e24-befa23da964e

how can solve this?

**Comment by Yidadaa** [comment]
Nobody have access to this model.

**Comment by johnfelipe** [comment]
But then, how can solve it?

**Comment by Yidadaa** [comment]
32k is only available for specific individuals and companies.

**Comment by johnfelipe** [comment]
bro i buy gpt4 apikey, and i have used for 1 hour, but something happend, because i do ask question with 26 contextual prompts and show me that error warning

**Comment by Yidadaa** [comment]
try to switch to `gpt-4` model.

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/fb2f0816-5b07-4d17-9c9b-14ac13a82bc3)

**Comment by johnfelipe** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/d7bb1a6d-6506-4e4e-a9d4-9296dab42531


```json
{
  "error": {
    "message": "The model: `gpt-4` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}
```

**Comment by Yidadaa** [comment]
you can check your available models here: https://platform.openai.com/account/rate-limits

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/535b9f47-0636-4123-88eb-e76291ccfd7a)

**Comment by johnfelipe** [comment]
![SNAG-0206](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/7c3f4a5e-ae57-41d6-bbe2-ec9948c33747)

is not there

is avaible only for few days?

**Comment by johnfelipe** [comment]
@Yidadaa then gpt4 is avaible few days in month, even i buy personal account not free?

**Comment by johnfelipe** [comment]
> @Yidadaa then gpt4 is avaible few days in month, even i buy personal account not free?

sorry for repeat request, but why i havent that model if i have payed account?
