### ISSUE TITLE
移动端UI显示问题

### ISSUE THREAD

**Issue by youngoris** [Yidadaa/ChatGPT-Next-Web#235]
输入框和设置菜单在Chrome和Safari均没有在浏览器窗口范围内，需要滚动才能显示，十分让人困惑。
另外能帮忙出个docker build 的教程吗？docker pull 更新有点慢。
谢谢！

**Comment by Yidadaa** [comment]
iOS 的 bug

**Comment by Yidadaa** [comment]
尝试多种方法无法解决。

**Comment by AprilNEA** [comment]
貌似和 Docker 构建无关

**Comment by youngoris** [comment]
> 

谢谢反馈，已更改Issue标题

**Comment by youngoris** [comment]
> 尝试多种方法无法解决。

谢谢你的努力，辛苦了

**Comment by yorunning** [comment]
这个项目是支持pwa的，添加到主屏幕使用就没这个问题了

**Comment by youngoris** [comment]
> 这个项目是支持pwa的，添加到主屏幕使用就没这个问题了
不错的主意，但PWA使用场景比较少，大多时候用浏览器。

**Comment by DemonRR** [comment]
这个问题在Safari将网页添加到桌面就行了，打开后就是一个独立的一个应用，或者你使用webclip工具

**Comment by youngoris** [comment]
> 这个问题在Safari将网页添加到桌面就行了，打开后就是一个独立的一个应用，或者你使用webclip工具

我们解决是浏览器使用的问题，包括Chrome。楼上已经给出相同的答复，为何还要重复？
