### ISSUE TITLE
[Bug] 安卓手机，钉钉端打开页面一直是加载中

### ISSUE THREAD

**Issue by csfrez** [Yidadaa/ChatGPT-Next-Web#2350]
**Describe the bug**
小米手机，自带的浏览器、谷歌浏览器、微信内都可正常打开，只有钉钉客户端无法打开

**To Reproduce**
钉钉端打开链接

**Expected behavior**
无法正常进入页面

**Screenshots**
![截图内容](https://raw.githubusercontent.com/csfrez/csfreztest/master/images/Weixin%20Image_20230711092604.jpg)

**Deployment**
- [x] Docker

**Smartphone (please complete the following information):**
 - Device: 小米12X
 - OS: Android13（MIUI 14.0.9）
 - Browser : Dingtalk
 - Version : v2.8.9

**Comment by Yidadaa** [comment]
钉钉 webview 太老，不兼容。
