### ISSUE TITLE
[Bug] 无法使用GPT4

### ISSUE THREAD

**Issue by BoneGatherer** [Yidadaa/ChatGPT-Next-Web#2351]
**Describe the bug**
在设置界面切换到GPT4后无法使用

**To Reproduce**
1、在设置界面将模型改为gpt-4
2、在对话界面发送任意字句

**Expected behavior**
调用gpt4模型

**Screenshots**
![图片](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8413877/f1c5e91a-c158-444d-9864-1d0f672a55b6)

**Deployment**
- [ ] Docker
- [ *] Vercel
- [ ] Server

{
  "error": {
    "message": "The model: `gpt-4-0314` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}

**Comment by fyl080801** [comment]
目测没有获得4的调用许可，在openai的账号界面查看use limit查看是否有许可

**Comment by johnfelipe** [comment]
how can review that in my portal?

**Comment by yinxulai** [comment]
About the url of open gpt4
https://openai.com/blog/gpt-4-api-general-availability
