### ISSUE TITLE
[Bug] 话题自动生成的小标题的相关问题

### ISSUE THREAD

**Issue by Cyrus-Reed** [Yidadaa/ChatGPT-Next-Web#2361]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
每个话题自动生成的小标题，gpt-3.5-turbo能够正常生成，gpt-4不能够生成，只是显示新的聊天。

**如何复现**
切换模型新建对话即可。

**截图**
<img width="950" alt="a" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/134946188/c822605a-e73a-4ecd-b6ea-d7024dd192c3">
<img width="951" alt="b" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/134946188/d88e925a-8a7f-47a5-b29b-8a89f28254f5">

**一些必要的信息**
 - 系统：windows 11
 - 浏览器： Edge
 - 版本： v2.8.9
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
小于 50 字的对话不会生成标题，多聊几句。
