### ISSUE TITLE
[Bug] 模型选项中多出了账号中没有的gpt-4-32k系列模型

### ISSUE THREAD

**Issue by gwoweiming** [Yidadaa/ChatGPT-Next-Web#2363]
**Describe the bug**
账号中没有gpt-4-32k模型，但是选项列表中列出来了
![Snipaste_2023-07-12_00-26-04](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46470282/0d22313d-cdda-494e-a6af-273227c7302e)
希望能够不显示这些没有的模型

**Comment by Yidadaa** [comment]
自动检测模型功能会让很多人困扰，所以不会开启此功能。

**Comment by gwoweiming** [comment]
我有办法自己开启吗？

**Comment by daiaji** [comment]
目前似乎站点支持的模型似乎又处于灰色的模式了。
旧的自动检测似乎更好用。
