### ISSUE TITLE
[Bug] 在Safari设备中 分享到ShareGPT时 提示复制成功 实际并没有复制到粘贴板

### ISSUE THREAD

**Issue by jiahao2333** [Yidadaa/ChatGPT-Next-Web#2367]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在Safari中 
分享到ShareGPT时 提示复制成功 实际并没有复制到粘贴板

环境：IOS16.1 iPhone14pm Safari版本未知
           macOS13.2.1 MacbookAir 2022 Safari/605.1.15 AppleWebKit/605.1.15
           iPad OS 16.5 iPadPro M2 Safari版本未知

**如何复现**
「先决条件 使用Safari设备（至少目前测试是这样）」
新建一个聊天👉简单聊两句👉右上角分享👉分享到ShareGPT

**截图**
![IMG_0369](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/53189564/d333044d-bbb7-4cee-ae95-b0b3eb392996)

**一些必要的信息**
 - 系统：macOS13.2.1
 - 浏览器： Safari/605.1.1
 - 版本： 2.8.9
 - 部署方式：Docker 以及官方网页

**Comment by jiahao2333** [comment]
目前来看复制其他内容都是正常的 只有复制ShareGPT链接时不成功

**Comment by daiaji** [comment]
其他地方复制有时候也不成功。

**Comment by Yidadaa** [comment]
web 里面的复制、下载，一直都是玄学触发，所有 web 应用都是这样，习惯就好。

**Comment by jiahao2333** [comment]
> web 里面的复制、下载，一直都是玄学触发，所有 web 应用都是这样，习惯就好。

但目前的情况是分享到ShareGPT Safari设备100%不成功🤔

**Comment by daiaji** [comment]
> web 里面的复制、下载，一直都是玄学触发，所有 web 应用都是这样，习惯就好。

难绷

**Comment by Yidadaa** [comment]
找到原因了，Share To ShareGPT 会发送一个请求，然后在异步回调中复制文本，Safari 默认禁止在异步回调中复制文本 😅，苹果可真牛逼，这逼项目就 Safari 里面一堆 bug，什么现代 IE。

解决方法：
https://wolfgangrittner.dev/how-to-use-clipboard-api-in-safari/
https://wolfgangrittner.dev/how-to-use-clipboard-api-in-firefox/

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/2912937e-517d-4f51-a77d-4225985a9bbf)

**Comment by daiaji** [comment]
> 找到原因了，Share To ShareGPT 会发送一个请求，然后在异步回调中复制文本，Safari 默认禁止在异步回调中复制文本 😅，苹果可真牛逼，这逼项目就 Safari 里面一堆 bug，什么现代 IE。
> 
> 解决方法： https://wolfgangrittner.dev/how-to-use-clipboard-api-in-safari/ https://wolfgangrittner.dev/how-to-use-clipboard-api-in-firefox/
> 
> ![image](https://user-images.githubusercontent.com/16968934/253741754-2912937e-517d-4f51-a77d-4225985a9bbf.png)

>> Hooray
>>
>> At last, copying text fetched from a URL works across Chrome, Safari and Firefox. And all it took was an if statement like it's 2004.

哈哈
firefox要改`about:config`吗？

**Comment by jiahao2333** [comment]
> 找到原因了，Share To ShareGPT 会发送一个请求，然后在异步回调中复制文本，Safari 默认禁止在异步回调中复制文本 😅，苹果可真牛逼，这逼项目就 Safari 里面一堆 bug，什么现代 IE。
> 
> 
> 
> 解决方法：
> 
> https://wolfgangrittner.dev/how-to-use-clipboard-api-in-safari/
> 
> https://wolfgangrittner.dev/how-to-use-clipboard-api-in-firefox/
> 
> 
> 
> ![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/2912937e-517d-4f51-a77d-4225985a9bbf)
> 
> 

🤣原来是这样吗 我修了半天没搞明白 本来都打算放弃了 牛批的😋👍

**Comment by Yidadaa** [comment]
主线代码已经修复，修改了复制链接的方式。
