### ISSUE TITLE
[Feature] steps for add my own prompts

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2371]
I want to add this prompts in templates, i want to see it when build application

this is an examples:

	¿Cuáles son los desarrolladores full stack del proyecto OFP?

	Crear las posibles actividades y tareas de un líder técnico, con también 90 horas por sprint

	Requiero una descripción detallada de que se busca construir en las historias del sprint 2, que se busca implementar y agrega los pasos a seguir luego de la descripción detallada

	Requiero una descripción detallada de que se busca construir en la historia de usuario de Azure DevOPS "Construcción de componentes de Mapeo de Datos", (Sprint N), que se busca implementar y agrega los pasos a seguir luego de la descripción detallada

	Crea los criterios de aceptación de la historia "Construcción de componentes de Mapeo de Datos", (Sprint N), la tabla debe tener:
	* Criterio
	* Contexto
	* Evento

**Comment by Yidadaa** [comment]
edit `public/prompts.json`
