### ISSUE TITLE
[Bug] 一个有关 replaceAll 的兼容性的bug：

### ISSUE THREAD

**Issue by sbetamaster** [Yidadaa/ChatGPT-Next-Web#2376]
**Describe the bug**
一个有关 replaceAll 兼容性的 bug 。

**To Reproduce**
我在手机上用 via 浏览器时，会出现一个奇怪的现象，输入文字并且点击按钮发送请求后，列表中并没有象正常那样把用户输入的文字显示在列表框中，而是消失不见，并且一直无法收到响应。然而用Chrome或者Edge浏览器并没有这种问题。

通过调试发现问题出在 app/store/chat.ts 文件中的以下代码处:
  Object.entries(vars).forEach(([name, value]) => {
    output = output.replaceAll(`{{${name}}}`, value);
  });

以上代码产生了异常，从而导致后续的代码都没有正常执行，于是出现了上述描述的现象。

其中 output.replaceAll 这一行代码编译后，在 via 浏览器运行时会出现异常，提示 o.replaceAll not is a function。
通过询问 chatgpt ，提示问题出现的原因为：”而您可能使用的是不支持该方法的JavaScript引擎“。因此这可能是个兼容性的问题。

chatgpt 提供了以下解决方案，即修改代码为：
  Object.entries(vars).forEach(([name, value]) => {
    output = output.replace(new RegExp(`{{${name}}}`, 'g'), value);
  });

经过测试后可行。

**Comment by Yidadaa** [comment]
手机系统版本？

**Comment by imzhoukunqiang** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/26564844/9a827ced-4817-4b6c-9934-6b7690670470)
这个函数版本要求确实比较高， @sbetamaster 可以升级webview试一下

**Comment by Yidadaa** [comment]
我加一个 polyfill 吧。

**Comment by Yidadaa** [comment]
ref: https://vanillajstoolkit.com/polyfills/stringreplaceall/

**Comment by Yidadaa** [comment]
I am going to introduce `babel/preset-env` to solve the polyfill issues: https://babeljs.io/docs/babel-preset-env

**Comment by Yidadaa** [comment]
@sbetamaster 已经尝试在主线增加 babel 转译，请使用演示站点测试此 bug 是否依然存在：https://chatgpt1.nextweb.fun/
