### ISSUE TITLE
[Feature] Have a link with specific chatbot only for interact (No full perms and env variables)

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2377]
Is possible have a link with:

- Chatbot
- without settings options
- without mask options
- without model of gpt

![SNAG-0226](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/ef78b8e1-df5a-4b2b-94b7-005b6139f2df)

that is for send link to testers with 32 contextual prompts

**Comment by Yidadaa** [comment]
You need to modify the code to meet your requirements.

**Comment by johnfelipe** [comment]
Pls share me paths and files for research....

**Comment by johnfelipe** [comment]
![Screenshot_2023-07-13-13-14-20-57_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/e90adf73-f2b6-4d8a-9432-a27178137303)

Will be a good feature
