### ISSUE TITLE
我看到claude已经整合进来了，请问如休让其正常工作？

### ISSUE THREAD

**Issue by ecco2005** [Yidadaa/ChatGPT-Next-Web#2379]
{
  "error": {
    "message": "The model `claude-100k` does not exist",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}

**Comment by Yidadaa** [comment]
没有整合，只是一个“自定义模型”的示例。如果你想用，请搭配 claude-to-gpt 这类项目使用。
