### ISSUE TITLE
code高亮显示似乎有点问题

### ISSUE THREAD

**Issue by Pandoxie** [Yidadaa/ChatGPT-Next-Web#238]
![image](https://user-images.githubusercontent.com/4418547/228829751-f34bb903-4c9f-491f-ba38-2bf16a75def4.png)
只有我这样么？还是css js什么挂了

**Comment by tisfeng** [comment]
好像出问题了，所有的代码块都无法高亮显示，代码语言类型也无了 😢

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/25194972/228850106-ac1890ad-498d-4058-804b-7c6310943508.png">

**Comment by Yidadaa** [comment]
gpt 返回的语言不指定类型就会这样，这是 gpt 的问题，你可以换个问法
