### ISSUE TITLE
[Bug] 编译打包部署后，env配置文件的参数不载入

### ISSUE THREAD

**Issue by Fnckerpoi** [Yidadaa/ChatGPT-Next-Web#2381]
**描述问题**
在本地开发实验时，env.local配置文件的参数能成功读取加载。
但当使用build、和tauri打包桌面端后，env配置文件参数并不会加载。
不清楚是从哪一次的版本合并后就失效了。
先前作者刚推出桌面端app编译后，是可以成功配置好env变量，编译打包后直接使用程序访问；

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/38403438/3b05e90d-547b-45e2-9ea6-0692a3faa93a)
现在就会一直提示没有通过权限验证

**一些必要的信息**
 - 系统：macos
 - 浏览器： chrome
 - 版本：2.8.9
 - 部署方式：服务器部署、tauri编译打包

**Comment by Yidadaa** [comment]
客户端打包是纯静态文件打包，不带任何服务端代码，`.env` 文件只会在服务端生效，客户端完全不会用到，所以本来就不应该能被打包。
