### ISSUE TITLE
[请教] 关于API Key

### ISSUE THREAD

**Issue by toyo2333** [Yidadaa/ChatGPT-Next-Web#2382]
我是个小白，打算试一试这个项目。

这里有疑问，

1，API key 本身会有所谓的 “对话历史记录” 等隐私元素么？

2，比如我去某个地方买了个120刀的Key（来路不明），那么通过这个key在产生的各种数据（如api请求记录，提问内容），会存在这个key原属于的openai账户里或者某个地方么？

主要是没法给自己的账户绑定信用卡用自己的key，只能考虑这种黑key了。就想知道上面的疑问，以及使用起来有没有其他的坑。

谢谢

**Comment by Yidadaa** [comment]
不会，apikey 不会存储你的任何信息
