### ISSUE TITLE
[请教] 请问部署后不同设备，用户使用的会话是隔离的么？

### ISSUE THREAD

**Issue by toyo2333** [Yidadaa/ChatGPT-Next-Web#2385]
部署后给朋友用用。设置是
服务端配置好OpenAI API KEY（不允许用户在客户端配置key）
并开启访问密码CODE
然后设置好自己的域名

这种情况下，不同设备访问服务得到的对话记录，是隔离的么？
这种情况下，某一个设备的对话记录全靠客户端的浏览器缓存保存么？

**Comment by Yidadaa** [comment]
是的，完全隔离，会话全部存储在本地。
