### ISSUE TITLE
新特性请求：支持Cloudflare一键部署

### ISSUE THREAD

**Issue by latorc** [Yidadaa/ChatGPT-Next-Web#239]
作为前端小白，希望能在cloudflare pages部署这个项目。似乎需要把vercel的serverless function改成Cloudflare版本的function，是否有方法可以判断平台？

**Comment by AprilNEA** [comment]
首先判断平台是可以的，Edge Runtime 改成 Cloudflare Function 也没有多少工作量。
但是目前 Cloudflare Pages 还不支持 Next.js13 的实验性功能也就是本项目使用的`appDir`，故本特性不太可能在短期内被支持。

**Comment by latorc** [comment]
> 首先判断平台是可以的，Edge Runtime 改成 Cloudflare Function 也没有多少工作量。 ~但是目前 Cloudflare Pages 还不支持 Next.js13 的实验性功能也就是本项目使用的`appDir`，故本特性不太可能在短期内被支持。~
> 
> 可以尝试: https://github.com/cloudflare/next-on-pages
试了在CF选择next.js编译，有错误说：
<html>
<body>


02:18:01.989 | ⚡️ Completed 'npx vercel build'.
-- | --
02:18:01.989 | ⚡️
02:18:02.622 | ⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
02:18:02.622 | ⚡️ The following functions were not configured to run with the Edge Runtime:
02:18:02.622 | ⚡️
02:18:02.622 | ⚡️  - index
02:18:02.622 | ⚡️  - index.rsc


</body>
</html>

不知道怎么解决 = =；

**Comment by latorc** [comment]
![image](https://user-images.githubusercontent.com/65785354/229373204-3af3f0f9-8130-446c-b09c-5f81d467b00e.png)
CF的编译设置
NODE_VERSION 是16 似乎CF不支持18

**Comment by Yidadaa** [comment]
cf 貌似尚未支持 nextjs13，可能需要降级一下 nextjs 版本

**Comment by AprilNEA** [comment]
> ![image](https://user-images.githubusercontent.com/65785354/229373204-3af3f0f9-8130-446c-b09c-5f81d467b00e.png) CF的编译设置 NODE_VERSION 是16 似乎CF不支持18

目前手动指定 NODE_VERSION 最高仅能支持到 17

**Comment by darth-pika-hu** [comment]
@AprilNEA NODE_VERSION要手动设置为18，你设20.1都行。
