### ISSUE TITLE
[Bug] Massive lag on UI updates 消息增多时卡顿严重

### ISSUE THREAD

**Issue by Happiness777** [Yidadaa/ChatGPT-Next-Web#2393]
**Describe the bug**
The app is lagging, whenever a bot types a message, or any UI changes, basically.

**To Reproduce**
1. Accumulate big amount of chats with long message history.
2. Create a new chat.
3. Send a message.
4. Lag :(

**Expected behavior**
No lag?

**Screenshots**
I'll add a [video](https://drive.google.com/file/d/1s62nLK2v3x-n68sLhDqGae8OaPXUGsM_/view?usp=sharing)

**Deployment**
- [ ] Docker
- [ ] Vercel
- [x] Server (termux on the phone)

**Smartphone:**
 - Device: Poco F3 (8/256)
 - OS: Android 12, MIUI V13.0.7.0.SKHRUXM
 - Browser: Soul Browser (based on chrome, afaik)
 - Version 1.3.56 (chrome version 110)

I'm on latest commit (c98df33), at the moment. 
And no, so many tabs don't make my browser lag :D

**Comment by Happiness777** [comment]
I tried to manually recreate the massive amount of chats with long messages history via masks (to profile things, on kiwi browser), but now it's just giving me an error, lol.

```
Unhandled Runtime Error
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'chat-next-web-store' exceeded the quota.
```

```javascript
  196 | }
  197 | 
> 198 | set((state) => ({
      |        ^
  199 |   currentSessionIndex: 0,
  200 |   sessions: [session].concat(state.sessions),
  201 | }));
```

![Screenshot_2023-07-16-08-26-11-812_com kiwibrowser browser](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35190676/3abcb1f6-f750-4f9f-8e39-113bb2c9f942)
![Screenshot_2023-07-16-08-26-05-496_com kiwibrowser browser](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35190676/a7468a62-178e-41c4-ade6-f80b39b13592)



The good thing is that I've managed to get enough chats to make things lag already.
28 chats are already enough. This is not even a fraction of the amount what I have on my main browser 👀

**Comment by Happiness777** [comment]
Omg it lags so hard. Yeah, it's certainly enough. It crashed both my browser and termux where I host the server, LMAO.

I don't even know how I would profile this thing with that amount of lag, honestly...

**Comment by Happiness777** [comment]
![Screenshot_2023-07-16-08-46-28-685_com kiwibrowser browser](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35190676/98f9f82a-2561-4ffb-9c34-b8c2cd3cffbe)
![Screenshot_2023-07-16-08-46-07-218_com kiwibrowser browser](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35190676/02028e01-9c25-4f88-bed1-2936dfe581de)


And this much lag was caused by a short message:
"Hello! I'm ChatGPT, a language model developed by OpenAI. I'm here to help answer your questions and engage in conversation on a wide range of topics. How can I assist you today?"

I may be blind, but this doesn't seem to explain why even closing the settings and dragging sliders is causing lag though.

**Comment by Happiness777** [comment]
I was just dragging message limit slider:
![Screenshot_2023-07-16-08-57-54-768_com kiwibrowser browser](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35190676/53229635-b9ef-4a60-8892-676bbc4c85af)
![Screenshot_2023-07-16-08-59-48-856_com kiwibrowser browser](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35190676/ab01ae7a-c6a1-4b88-a13a-652c97b57659)

**Comment by Happiness777** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.

🤣

**Comment by Happiness777** [comment]
I've profiled this also with react profiler.
Idk if this is helpful, but I'll leave these exported profiler results here, just in case.
[react-profiler-results.zip](https://github.com/Yidadaa/ChatGPT-Next-Web/files/12063443/react-profiler-results.zip)

Also, here's a screenshot of chat lag:
![Screenshot_2023-07-16-09-56-17-240_com kiwibrowser browser](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35190676/f9f1f6b6-6813-439a-a4f1-b7cb27762e79)

I won't send a screenshot of slider lag, because I'm confused about what exactly causes it to lag. You better look into it yourself.

P.S.
Yeah, I just realised that I could export profiler results...
Well, it's my first time profiling things ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by Yidadaa** [comment]
It doesn't seem to be caused by React, but rather by frequent reading and writing to `localStorage`, leading to the lag.

**Comment by Yidadaa** [comment]
This also explains why simply dragging the slider will cause lag.

**Comment by Happiness777** [comment]
I also had suspicion about similar thing, honestly, but didn't voice my thoughts, because I'm not really experienced in JavaScript

**Comment by Yidadaa** [comment]
@Happiness777 

I wrote a micro benchmark, would you please run it on your phone?

https://codepen.io/yda_da/pen/rNQdrgB

**Comment by Happiness777** [comment]
> would you please run it on your phone?

```
Benchmark log:


setting an array[10000] 10000 times
item length = 20001

Done in 1753ms
```

**Comment by Yidadaa** [comment]
On my phone:

```
Benchmark log:


setting an array[10000] 10000 times
item length = 20001

Done in 1137ms
```

It doesn't seem like the problem originated from here.

**Comment by Happiness777** [comment]
> It doesn't seem like the problem originated from here.

Hmm, but my browser lagged (basically frozen) in exactly the same way it lags in the app, whenever the bot types.

**Comment by Yidadaa** [comment]
I have to go back to work now. If this bug affects your usage, please try manually checking out an older version tag and redeploying once to temporarily avoid the issue.

**Comment by Happiness777** [comment]
Ok then, good luck. I'll probably keep trying to fix this thing, or at least find the cause of lag.

**Comment by Yidadaa** [comment]
If you can find another device, maybe you can try to reproduce the bug on it?

**Comment by Happiness777** [comment]
> If you can find another device

I have only Poco F1 and Redmi Note 3 Pro(somewhere in my drawer, powered off).

I can send you the exported mask, which you can apply to a ton of chats and try reproduce the lag, if you want.

**Comment by Yidadaa** [comment]
Sure, you can post the json here, i will test on my phone.

**Comment by Happiness777** [comment]
Had to zip the thing to be able to send it, lol
[masks.zip](https://github.com/Yidadaa/ChatGPT-Next-Web/files/12067270/masks.zip)

**Comment by Yidadaa** [comment]
Um... I don't have any issues on my phone. It runs very smoothly...

**Comment by Happiness777** [comment]
> It runs very smoothly...

How many chats have you created?

**Comment by Yidadaa** [comment]
I imported your mask, and type some text & scroll the screen, it works perfectly.

Furthermore, my daily conversations have accumulated 86 chats without encountering any performance issues. I also asked my friends, who have had numerous conversations consisting of hundreds of chats, and they haven't experienced this issue either.

![c9e445fc5591f4bffe8c451639539bc](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/4918507e-dcba-4240-8d05-fd22f6878b73)

**Comment by Yidadaa** [comment]
Perhaps you can try borrowing your friend's phone to see if they have this issue?

**Comment by Happiness777** [comment]
> I imported your mask, and type some text & scroll the screen, it works perfectly.

I had to use my mask 28 times to notice the lag. 1-5 chats just aren't enough.

And by chats, I mean not message (as you've shown on the screenshot. 86 messages.), I mean the conversations/chats specifically.

**Comment by Yidadaa** [comment]
I understand. This is a known issue. The chat list does not have lazy loading implemented, so long lists can experience lag.

**Comment by Yidadaa** [comment]
Let me confirm again, when you say "10-15 chats," are you referring to the number of items in the homepage list, rather than the number of messages within a single chat, right?

**Comment by Happiness777** [comment]
> Let me confirm again, when you say "10-15 chats," are you referring to the number of items in the homepage list, rather than the number of messages within a single chat, right?

Yes

**Comment by Happiness777** [comment]
> The chat list does not have lazy loading implemented

Btw, do you have plans to implement it any time soon?

**Comment by Yidadaa** [comment]
Tried to fix it, would your please try to verify it on demo site?

**Comment by Happiness777** [comment]
> verify it on demo site

Of you mean the https://chatgpt1.nextweb.fun/, then it's not fixed there. It still lags as before.

**Comment by Yidadaa** [comment]
Hi bro, i made some new fixes, would you please check it out again?

**Comment by Happiness777** [comment]
Sure. Is it on the main website already?

**Comment by Yidadaa** [comment]
yes


---Original---
From: ***@***.***&gt;
Date: Fri, Aug 4, 2023 03:07 AM
To: ***@***.***&gt;;
Cc: &quot;Yifei ***@***.***&gt;;&quot;State ***@***.***&gt;;
Subject: Re: [Yidadaa/ChatGPT-Next-Web] [Bug] Massive lag on UI updates (Issue#2393)




 
Sure. Is it on the main website already?
 
&mdash;

**Comment by Happiness777** [comment]
I noticed that even deleting messages takes some time and causes lag (around 0.3~0.5 seconds from my perception)

**Comment by Happiness777** [comment]
I've updated the sources I had on my local server and ran it myself, to see how it performs.
To be fair, it lags a lot less with my main list of chats right now.
Although there's some jittering when just scrolling, both list of chats and list of messages sometimes.

**Comment by Yidadaa** [comment]
Bro, can you provide a screen recording video? If it doesn't affect usability anymore, I think the problem is considered solved.

**Comment by Happiness777** [comment]
> If it doesn't affect usability anymore

It does, unfortunately.
I mean, the browser doesn't crash and freeze for 10 seconds straight (or even crash) anymore, it just lags a lot. Still freezing, but basically for 0.5 seconds every time the bot types

**Comment by Happiness777** [comment]
> screen recording video

It's the same kind of lag I provided in the video in my first message here. When I have time, I'll try to record it again, if you want

**Comment by Yidadaa** [comment]
Merge into #2433

**Comment by Happiness777** [comment]
Are there any updates on the problem? 
I'm still lagging horrendously, to the point I'm actually starting to think about switching to other web UI's.
