### ISSUE TITLE
[Feature] Allow editing of history message for any roles & Provide an option to customize model name for backend

### ISSUE THREAD

**Issue by hycxnas** [Yidadaa/ChatGPT-Next-Web#2397]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to two main problems I have encountered while using ChatGPT-Next-Web:

1. The inability to edit sent messages, which can lead to difficulties in correcting errors and ensuring a smooth conversation flow.
2. The lack of flexibility in deploying the project with different models, as the list of model names cannot currently be passed as an environment variable when deploying via Docker.

**Describe the solution you'd like**
I propose two main solutions to address these issues:

1. Implement a feature that allows users to edit their sent messages. This would make conversations smoother and more user-friendly, as users could easily correct any mistakes they make.
2. Allow the list of model names to be passed as an environment variable when deploying the project via Docker. This would make it easier to deploy the project with different models, increasing its flexibility and adaptability.

**Describe alternatives you've considered**
An alternative to the first solution could be to implement a confirmation step before sending a message, which would give users a chance to review and correct their message before it is sent. However, this could potentially disrupt the flow of conversation and make the interface less user-friendly.

For the second solution, an alternative could be to include a step in the deployment process where the user can manually select the model they want to use. However, this would not be as efficient or flexible as passing the model names as an environment variable.

**Additional context**
These suggestions are based on my personal experience using ChatGPT-Next-Web over the past few weeks. I believe that implementing these features would greatly improve the user-friendliness and adaptability of the project, making it even more powerful and useful for its users. I hope you will consider these suggestions and I look forward to seeing the continued development of this great project.

**Comment by Yidadaa** [comment]
Hi @hycxnas,

Make sure that you have made your code base synced with upstream.

1. Of course you can edit sent messages, just click avatar:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/12cc4494-cf46-46ae-b99a-5ebc3ed15c80)
2. You can add custom model names here: 
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/64cd92df-ecf4-4f8a-bfbf-3946591d7a37)
