### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by tiandankanfeng** [Yidadaa/ChatGPT-Next-Web#2398]
目前版本迭代的周期是怎样的，大版本以及小版本，比如3.0版本大概那个时间段会出来

**Comment by Yidadaa** [comment]
主数字是大版本号，大概一到两个月更新一次，一般会涉及到重要功能性更新；
其次是小数点后一位，更新频率一到两周一次；
最后是第二个小数点后一位，更新频率一周一到两次。

不过并不会严格按照这个频率来，随缘。
