### ISSUE TITLE
出错了，稍后重试吧

### ISSUE THREAD

**Issue by wilsonsky18** [Yidadaa/ChatGPT-Next-Web#24]
![image](https://user-images.githubusercontent.com/12883204/227705107-81b19135-95b2-46ea-bd44-b5deb5b9f246.png)
从openai的官网生成的key，应该不是这个问题，一只报错

**Comment by wilsonsky18** [comment]
还有想请问下作者，是不是运行这个app也需要挂美国或者英国的vpn？谢谢

**Comment by Cp0204** [comment]
> 还有想请问下作者，是不是运行这个app也需要挂美国或者英国的vpn？谢谢

看你在哪里运行，如果墙内，是的。

**Comment by Yidadaa** [comment]
如果你是用 vercel 部署，并且没有绑定自定义域名，那就需要翻墙才能访问。

如果你是自己服务器部署，需要你的服务器在国外。

**Comment by damengmeng** [comment]
你好，如何去除github 标识，还有二次开发，加入使用限制。

**Comment by BingyuanXie** [comment]
我部署到了vercel，然后也是一直这种报错，我查了vercel上的日志，http代码是504，截图如下，请问下作者，这种一般是什么错误？

![Snipaste_2023-03-25_21-18-51](https://user-images.githubusercontent.com/46948396/227719516-289727d0-c8bc-4b7b-9809-bc1c5b4be4df.png)
