### ISSUE TITLE
[Feature] discord channel for solve rookies questions before create issues here 

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2401]
Pls share discord channel again

**Comment by Yidadaa** [comment]
I previously established a Discord channel, but due to the inconvenience of using Discord in my country, I find it challenging to effectively manage the discussions on Discord. Perhaps I should consider setting up a new Discord or Telegram group chat now?

**Comment by Yidadaa** [comment]
Join discord: https://discord.gg/YCkeafCafC

**Comment by johnfelipe** [comment]
When you build telegram channel pls share it too
