### ISSUE TITLE
[Feature] 对话列表批量清理功能

### ISSUE THREAD

**Issue by NNGTHB** [Yidadaa/ChatGPT-Next-Web#2402]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

目前对话无法批量选中删除

**你想要什么功能或者有什么建议？**
尽管告诉我们。
选中多个列表后一键删除，或者加一个类似“清除前50条对话”的功能

**Comment by Yidadaa** [comment]
你说的是左侧边栏列表，还是单个对话的消息列表？

**Comment by Yidadaa** [comment]
1. 善用清除聊天
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/fb848adc-8cbb-4a37-90e0-80bd4002a08f)

2. 狂点这个叉号：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/2d621042-6e65-40f5-bbe0-cd495d672e6c)

**Comment by NNGTHB** [comment]
> 你说的是左侧边栏列表，还是单个对话的消息列表？

左边侧边栏列表
