### ISSUE TITLE
[Feature] nextjs 框架不熟悉，请问如何给项目增加一个统一静态前缀

### ISSUE THREAD

**Issue by chenmins** [Yidadaa/ChatGPT-Next-Web#2408]
如题目，如果我只有一个域名。www.chenmin.com.cn。
我希望以www.chenmin.com.cn/ai/chatgpt方式使用，请问编译导出如何增加“/ai/chatgpt”

谢谢

**Comment by Yidadaa** [comment]
不好加，见 #720

**Comment by pkuphy** [comment]
I think using a subdomain would be more appropriate.
