### ISSUE TITLE
[咨询] 关于system预设提示词两种做法的区别

### ISSUE THREAD

**Issue by toyo2333** [Yidadaa/ChatGPT-Next-Web#2414]
1、在一个新的聊天对话里，选”对话设置“ 新增角色为”system“的”预设提示词“，然后回到对话，开始用户提问”具体问题“；

2、直接在新聊天的对话的用户提问里包含”预设提示词+具体问题“，直接提问

请问这两种方式在：回答效果、成本(Token计价）、效率方面有什么不同？

**Comment by toyo2333** [comment]
> 没有任何区别，无非就是一个手动档，一个自动档。

谢谢。还有个补充问题，就是新开一个对话，然后直接对话左上角那个”有什么可以帮你的吗“ 这个预设词的编辑按钮（那个🖊），里面修改点保存，没有变化，这是bug么？

**Comment by Yidadaa** [comment]
@toyo2333 算是 bug，欢迎词不应该被编辑，但是无伤大雅，不影响使用。

**Comment by toyo2333** [comment]
> @toyo2333 算是 bug，欢迎词不应该被编辑，但是无伤大雅，不影响使用。

关于这个问题的最后一个提问：

你说这两种方式在成本上没有区别，意思是不是：

无论那种方式，在后续的**每一轮**对话中，都会发送完整”提示词“么？


比如提示词是
1、system：你是一个儿童心理咨询师，用5岁儿童可以理解的方式、幽默、有趣的回答我提出的问题

2、你是一个儿童心理咨询师，请用5岁儿童可以理解的方式、幽默、有趣的回答这个问题：XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

这两种情况，2的提示词里包含了内容问题，字数Token可能多很多哦，这不就会有差异了么？

**Comment by Yidadaa** [comment]
方法 1 同样也需要把 system prompt 每次都和问题一起发过去，并不是设置一次就一劳永逸了，api 没有记忆能力，所以两者没什么区别。

**Comment by toyo2333** [comment]
> 方法 1 同样也需要把 system prompt 每次都和问题一起发过去，并不是设置一次就一劳永逸了，api 没有记忆能力，所以两者没什么区别。

请作者别笑话我，我不是程序员，最近刚刚才用起来GTP，所以问题比较多，也可能比较没有水平。

按我的理解：比如后续进行了5轮对话后，提了第6个问题Q6

方法1里：发送的就是 system prompt +Q6 

方法2：发送的就是 user prompt （里面包含了Q1）+Q6

这还是不保留历史消息的设置情况西啊，如果保留了4条历史消息 ，方法2 还要带上上两轮的提问+回答 ：
 (user prompt （里面包含了Q1）+Q4)+A4
 (user prompt （里面包含了Q1）+Q5)+A5

如果Q1是个很长的问题，那方法2相比方法1就多发了很多重复内容啊。

（所以如果在意成本的话，是不是合理的做法，应该是方法2应该把user prompt 和Q1 拆成2条消息对话发给GTP完成提问？）
