### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xinyu162** [Yidadaa/ChatGPT-Next-Web#2415]
https://chatgpt1.nextweb.fun/#/chat  网址使用，用firefox  浏览器配置了地址以后，出现如下错误：
{
  "error": true,
  "message": "Failed to fetch"
}

控制台如下的错误：
Firefox 提示已阻止载入混合活动内容,
参考如下可以解决：
打开新标签页，在地址栏输入 about:config，进入配置页面。
搜索 security.mixed_content.block_active_content，将 true 改为 false。

但是 用 mac  v2.8.9 客户端，mac os 14 ,配置了相同的地址， 出现如下的错误：
{
  "error": true,
  "message": "Load failed"
}

<img width="321" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/12483834/9d7fdf90-9186-411c-985c-212d5f146d18">

**Comment by Yidadaa** [comment]
客户端的网络问题我无法解决，请自行排查。

**Comment by xinyu162** [comment]
not support  http  proxy  ?  must https  ?
