### ISSUE TITLE
[Feature] Add embeeding to this wonderful UI

### ISSUE THREAD

**Issue by realnoob007** [Yidadaa/ChatGPT-Next-Web#2427]
The UI provides wonderful user experience, however, it lacks the function of uploading files including pdf, docx, ppt, excel and etc. The openai embedding model is easy to be applied. The embedding data can be storaged locally, which enabled the program to recall it again when someone upload the same file.
**Describe the solution you'd like**

**Describe alternatives you've considered**
Openai embedding model
local storage

**Additional context**
ChuanhuChatGPT(https://github.com/GaiZhenbiao/ChuanhuChatGPT) provides 2 solutions:
1. openai embedding
2. local embedding (require high memory)
faiss cpu

**Comment by Yidadaa** [comment]
In plan #960
