### ISSUE TITLE
[Feature] 新增回复字生成速度控制

### ISSUE THREAD

**Issue by yohaneowo** [Yidadaa/ChatGPT-Next-Web#2429]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
字生成的速度过慢,实际上已经生成完毕 只是回复生成的字很慢

**你想要什么功能或者有什么建议？**
可以调整回复速度,

**Comment by Yidadaa** [comment]
你的疑问别人也提出过，但事实上并不是如此，你多虑了。
