### ISSUE TITLE
[Feature] Can you add an explanation of some vague settings?

### ISSUE THREAD

**Issue by aalyousfi** [Yidadaa/ChatGPT-Next-Web#2430]
There are some settings that I don't understand in the app. I tried searching the repo for explanations but couldn't find anything useful, at least in English.

The settings are:

**1. History Compression Threshold**: Will compress if uncompressed messages length exceeds the value. 

What does compression mean here? And the threshold value is the number of tokens or what? I assume this is talking about the previous messages in the conversation that get sent to the Chat API, right?

**2. Memory Prompt**: Send Memory.

What does memory prompt mean? How does it work with the compression mentioned above for example?

**3. Attached Messages Count**: Number of sent messages attached per request.

I think this is the number of previous messages in the conversation that get sent to the Chat API, right? Like if I set it to 4 for example, then what happens to older messages (older than 4)? Will they be ignored?

If you can please provide explanations about these settings in particular or guide me to a place where I can learn about them. Thanks.

**Comment by Yidadaa** [comment]
Indeed, it can be challenging to fully comprehend the complexity of a situation in just a few words. I will keep this issue in mind and await further clarification when you have the time. Nonetheless, your initial understanding aligns with the majority of the intended meaning. Feel free to rely on your instincts for interpretation.

**Comment by aalyousfi** [comment]
Thank you but even with my initial understanding, I feel I don't understand what's going on. So please when you have time provide us with a guide to understand these settings so we can use the app effectively. Thanks in advance.

**Comment by cahya-wirawan** [comment]
Can I disable this automatic compression? because it seems the web browser send following message automatically to the api: "Please generate a four to five word title summarizing our conversation without any lead-in, punctuation, quotation marks, periods, symbols, or additional text. Remove enclosing quotation marks.". I use a local LM which is not trained to answer those message, so such a message is not desirable. Thanks.

**Comment by Yidadaa** [comment]
Please read this:

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/user-manual-cn.md

Currently, only the Chinese version is available. Please use ChatGPT or any translation tool to read it

**Comment by shaggy2626** [comment]
> generate a four to five word title summarizing our conversation without any lead-in, punctuation, quotation marks, periods, symbols, or additional text. Remove enclosi

Is there anyway to see how many tokens the chat is at so far, kind of something like this

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/120447538/fd90fe9b-bce5-4bf6-bf85-778c4f9a109f)
