### ISSUE TITLE
[Bug] ChatGLM2-6B 的openai_api.py進行部署後端，可以成功在  <我的固定IP>:19745/docs造訪說明書，前端網頁對話出現"error": true,"message": "Failed to fetch"

### ISSUE THREAD

**Issue by KAIYI-HSU** [Yidadaa/ChatGPT-Next-Web#2435]
@Yidadaa 
您好:

我也是透過ChatGLM2-6B 的openai_api.py進行部署後端。
我只修改文件中的model路徑跟改對外端口如下:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73111412/3360b069-40f2-4f3b-b87e-1aa9ffbab9e5)
我有確定成功開啟端口並且能成功從 <我的固定IP>:19745/docs造訪說明書，也能用POST測試成功，GLM2可以生成回應。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73111412/a46e0f77-96ce-4bb4-979e-f02e8ec0f207)
=====
請問我使用您的前端網頁: https://chatgpt1.nextweb.fun/
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73111412/4efac604-5c8a-4ee9-a9a9-9b5d9645872f)
Endpoint填寫我的<我的固定IP>:19745 or https://<我的固定IP>:19745
對話時會出現以下錯誤:
{
  "error": true,
  "message": "Failed to fetch"
}
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73111412/c4575bbc-6700-4ce0-ae27-d251d2fd1feb)

=====
希望能尋求幫助，
為何我後端部署好，任何前端網頁都無法跟 我的<我的固定IP>:19745 or https://<我的固定IP>:19745
進行互動?

**Comment by Yidadaa** [comment]
请确认你的 openai_api.py 中解除了跨域限制，检查代码中是否有 `CORSMiddleware`。
