### ISSUE TITLE
[Feature] 为面具设置独特的api与key

### ISSUE THREAD

**Issue by inanb** [Yidadaa/ChatGPT-Next-Web#2439]
现在有一些不同的模型，一些项目使其都提供openai范式的api，如果可以为每个面具设置不同的api，那么通过切换面具就可以做到在一个应用中方便地切换到不同模型，这会很有趣~

**Comment by Yidadaa** [comment]
面具的维度是模型，而不是 api 设置，所以此需求不会考虑，不过最近我会加入其他模型的支持，你只需要在模型中设定好对应的模型即可。
