### ISSUE TITLE
修改BASE_URL未生效

### ISSUE THREAD

**Issue by yidasanqian** [Yidadaa/ChatGPT-Next-Web#2441]
在vercel修改了BASE_URL，重新部署，但是接口未生效
请求的是如下地址：
https://chatgpt1.nextweb.fun/api/proxy/v1/chat/completions

**Comment by Yidadaa** [comment]
https://flowus.cn/23341c3d-7c3d-4f73-9a8d-570075ae7d5f#21679613-3d42-4e01-b139-a5d4ac91aaf4
