### ISSUE TITLE
[Bug] 问一两个问题就出现 ECONNRESET报错

### ISSUE THREAD

**Issue by ntbzx** [Yidadaa/ChatGPT-Next-Web#2442]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
docker run --name chatgpt -d -p 3000:3000 -e OPENAI_API_KEY="xxxxxx" -e CODE="xxxx" yidadaa/chatgpt-next-web
使用这个命令在威联通nas上部署的，路由器用clash，选择的日本的Amazon节点，openai官网，api都能正常访问，但是使用你们的工具偶尔会出现以下报错
```json
{
  "cause": {
    "errno": -104,
    "code": "ECONNRESET",
    "syscall": "read"
  }
}
```
问个一两个问题就会出现一次，但是如果我在我win11电脑上使用chatbox访问一直是正常的（也是连的openai api，项目地址https://github.com/Bin-Huang/chatbox）
然后我去clash yacd里面看了连接，发现我每问一次问题，就会建立一个新的连接，回复完之后连接又会断开。如果我使用win11客户端chatbox访问的话，我每次问一个问题，连接是长期活动的，不会出现断开的情况

**如何复现**
问一两句就会出现一次，重试几次又能正常使用

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/27877221/ff375a2c-2ddc-49b8-9561-5e0e169e818b)

**一些必要的信息**
 - 系统：win11，威联通nas
 - 浏览器：chrome
 - 版本： 2.8.9
 - 部署方式：docker

**Comment by Yidadaa** [comment]
梯子不稳定就会这样，建议使用项目自带的 proxy 地址使用：https://chatgpt1.nextweb.fun/api/proxy，配合官方 key 即可开始使用。
