### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by dislazy** [Yidadaa/ChatGPT-Next-Web#2446]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
无关

**你想要什么功能或者有什么建议？**
是否可以有个简单的api接口对外暴露，同样是使用和web端一样的密码，然后给外部提供api接口

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
地址：https://你的域名/api/openai
key：ak-你的CODE
