### ISSUE TITLE
[Feature] Read Settings from URL params

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#2447]
I will add this feature:

```
https://chatgpt.nextweb.fun/#/chat?code=xxxxxx
https://chatgpt.nextweb.fun/#/chat?settings=[base64encoded settings]
```

It will read settings from url after loading, and auto-fill the settings fields.

**Comment by imldy** [comment]
Note: 'settings' accepts JSON characters instead of base64encoded settings

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/e5f6133127894b68498de0a4d38741bccdba68f1/app/components/chat.tsx#L895-L898
