### ISSUE TITLE
[Feature] Insert messages

### ISSUE THREAD

**Issue by Algorithm5838** [Yidadaa/ChatGPT-Next-Web#2449]
**Is your feature request related to a problem? Please describe.**
I cannot insert messages at specific points in the chat.

**Describe the solution you'd like**
Ability to insert messages anywhere in the chat for better customization and guidance.

**Describe alternatives you've considered**
I have to write a random message so I can edit it and its response.

**Additional context**
An idea is to add a plus sign (+) before and after every message to insert one or multiple messages.

Thank you. Really appreciate your work.

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/135d20f1-d617-4ce5-83bb-e11d9c6f62ca)
