### ISSUE TITLE
访问码和API正确,仍访问受限,重新部署无效

### ISSUE THREAD

**Issue by tyu6201** [Yidadaa/ChatGPT-Next-Web#245]
![Snipaste_2023-03-30_22-14-48](https://user-images.githubusercontent.com/85124793/228866123-8a391d59-227b-4726-a3e7-7f55091ecfff.png)
![Snipaste_2023-03-30_22-15-27](https://user-images.githubusercontent.com/85124793/228866141-bf3a7a97-ea06-4b0c-9678-54c77525cdbc.png)
![Snipaste_2023-03-30_22-18-45](https://user-images.githubusercontent.com/85124793/228866147-5cc799cc-24f6-473a-add4-76f0c4b348a4.png)

**Comment by hugoyue** [comment]
> ![Snipaste_2023-03-30_22-14-48](https://user-images.githubusercontent.com/85124793/228866123-8a391d59-227b-4726-a3e7-7f55091ecfff.png) ![Snipaste_2023-03-30_22-15-27](https://user-images.githubusercontent.com/85124793/228866141-bf3a7a97-ea06-4b0c-9678-54c77525cdbc.png) ![Snipaste_2023-03-30_22-18-45](https://user-images.githubusercontent.com/85124793/228866147-5cc799cc-24f6-473a-add4-76f0c4b348a4.png)

部署完，进入设置内，在访问码正确填入设定好的 CODE 值，才可以正常使用。填一个，而不是填三个，例如环境中设定CODE值为 A,B,C 那么设置里面访问码填 A、B、C 任意一个。

**Comment by tyu6201** [comment]
> > ![Snipaste_2023-03-30_22-14-48](https://user-images.githubusercontent.com/85124793/228866123-8a391d59-227b-4726-a3e7-7f55091ecfff.png) ![Snipaste_2023-03-30_22-15-27](https://user-images.githubusercontent.com/85124793/228866141-bf3a7a97-ea06-4b0c-9678-54c77525cdbc.png) ![Snipaste_2023-03-30_22-18-45](https://user-images.githubusercontent.com/85124793/228866147-5cc799cc-24f6-473a-add4-76f0c4b348a4.png)
> 
> 部署完，进入设置内，在访问码正确填入设定好的 CODE 值，才可以正常使用。填一个，而不是填三个，例如环境中设定CODE值为 A,B,C 那么设置里面访问码填 A、B、C 任意一个。

![123](https://user-images.githubusercontent.com/85124793/228867935-56fe99e8-d1ac-4df5-bc88-7278ed1f8198.png)
![1234](https://user-images.githubusercontent.com/85124793/228868058-5d7214f8-da77-4cba-a366-ebd550d51cc8.png)
已尝试,但仍然无法解决,很奇怪

**Comment by hugoyue** [comment]
> > > ![Snipaste_2023-03-30_22-14-48](https://user-images.githubusercontent.com/85124793/228866123-8a391d59-227b-4726-a3e7-7f55091ecfff.png) ![Snipaste_2023-03-30_22-15-27](https://user-images.githubusercontent.com/85124793/228866141-bf3a7a97-ea06-4b0c-9678-54c77525cdbc.png) ![Snipaste_2023-03-30_22-18-45](https://user-images.githubusercontent.com/85124793/228866147-5cc799cc-24f6-473a-add4-76f0c4b348a4.png)
> > 
> > 
> > 部署完，进入设置内，在访问码正确填入设定好的 CODE 值，才可以正常使用。填一个，而不是填三个，例如环境中设定CODE值为 A,B,C 那么设置里面访问码填 A、B、C 任意一个。
> 
> ![123](https://user-images.githubusercontent.com/85124793/228867935-56fe99e8-d1ac-4df5-bc88-7278ed1f8198.png) ![1234](https://user-images.githubusercontent.com/85124793/228868058-5d7214f8-da77-4cba-a366-ebd550d51cc8.png) 已尝试,但仍然无法解决,很奇怪

如果变量环境是在部署完成后再次修改过的，需要 redeploy 才会生效。

**Comment by tyu6201** [comment]
> > > > ![Snipaste_2023-03-30_22-14-48](https://user-images.githubusercontent.com/85124793/228866123-8a391d59-227b-4726-a3e7-7f55091ecfff.png) ![Snipaste_2023-03-30_22-15-27](https://user-images.githubusercontent.com/85124793/228866141-bf3a7a97-ea06-4b0c-9678-54c77525cdbc.png) ![Snipaste_2023-03-30_22-18-45](https://user-images.githubusercontent.com/85124793/228866147-5cc799cc-24f6-473a-add4-76f0c4b348a4.png)
> > > 
> > > 
> > > 部署完，进入设置内，在访问码正确填入设定好的 CODE 值，才可以正常使用。填一个，而不是填三个，例如环境中设定CODE值为 A,B,C 那么设置里面访问码填 A、B、C 任意一个。
> > 
> > 
> > ![123](https://user-images.githubusercontent.com/85124793/228867935-56fe99e8-d1ac-4df5-bc88-7278ed1f8198.png) ![1234](https://user-images.githubusercontent.com/85124793/228868058-5d7214f8-da77-4cba-a366-ebd550d51cc8.png) 已尝试,但仍然无法解决,很奇怪
> 
> 如果变量环境是在部署完成后再次修改过的，需要 redeploy 才会生效。

未修改过,尝试过redeploy,也无法解决

**Comment by hugoyue** [comment]
> > > > > ![Snipaste_2023-03-30_22-14-48](https://user-images.githubusercontent.com/85124793/228866123-8a391d59-227b-4726-a3e7-7f55091ecfff.png) ![Snipaste_2023-03-30_22-15-27](https://user-images.githubusercontent.com/85124793/228866141-bf3a7a97-ea06-4b0c-9678-54c77525cdbc.png) ![Snipaste_2023-03-30_22-18-45](https://user-images.githubusercontent.com/85124793/228866147-5cc799cc-24f6-473a-add4-76f0c4b348a4.png)
> > > > 
> > > > 
> > > > 部署完，进入设置内，在访问码正确填入设定好的 CODE 值，才可以正常使用。填一个，而不是填三个，例如环境中设定CODE值为 A,B,C 那么设置里面访问码填 A、B、C 任意一个。
> > > 
> > > 
> > > ![123](https://user-images.githubusercontent.com/85124793/228867935-56fe99e8-d1ac-4df5-bc88-7278ed1f8198.png) ![1234](https://user-images.githubusercontent.com/85124793/228868058-5d7214f8-da77-4cba-a366-ebd550d51cc8.png) 已尝试,但仍然无法解决,很奇怪
> > 
> > 
> > 如果变量环境是在部署完成后再次修改过的，需要 redeploy 才会生效。
> 
> 未修改过,尝试过redeploy,也无法解决

那你删掉实例，重新部署，code设置一个值例如就设置 56789 这种简单的值，再试试看吧。

**Comment by tyu6201** [comment]
> > > > > > ![Snipaste_2023-03-30_22-14-48](https://user-images.githubusercontent.com/85124793/228866123-8a391d59-227b-4726-a3e7-7f55091ecfff.png) ![Snipaste_2023-03-30_22-15-27](https://user-images.githubusercontent.com/85124793/228866141-bf3a7a97-ea06-4b0c-9678-54c77525cdbc.png) ![Snipaste_2023-03-30_22-18-45](https://user-images.githubusercontent.com/85124793/228866147-5cc799cc-24f6-473a-add4-76f0c4b348a4.png)
> > > > > 
> > > > > 
> > > > > 部署完，进入设置内，在访问码正确填入设定好的 CODE 值，才可以正常使用。填一个，而不是填三个，例如环境中设定CODE值为 A,B,C 那么设置里面访问码填 A、B、C 任意一个。
> > > > 
> > > > 
> > > > ![123](https://user-images.githubusercontent.com/85124793/228867935-56fe99e8-d1ac-4df5-bc88-7278ed1f8198.png) ![1234](https://user-images.githubusercontent.com/85124793/228868058-5d7214f8-da77-4cba-a366-ebd550d51cc8.png) 已尝试,但仍然无法解决,很奇怪
> > > 
> > > 
> > > 如果变量环境是在部署完成后再次修改过的，需要 redeploy 才会生效。
> > 
> > 
> > 未修改过,尝试过redeploy,也无法解决
> 
> 那你删掉实例，重新部署，code设置一个值例如就设置 56789 这种简单的值，再试试看吧。
![123](https://user-images.githubusercontent.com/85124793/228872175-e6c04f75-6bdf-404b-9adb-279ec6ded4df.png)
![1234](https://user-images.githubusercontent.com/85124793/228872194-89d7e8df-187a-49af-9c3a-3eb885a533c2.png)
删后重新添加CODE,重新部署后在设置中输入新的CODE,但仍提示受控

**Comment by tyu6201** [comment]
> 

![1](https://user-images.githubusercontent.com/85124793/228874705-1c130dd3-96b6-4866-8ccf-61094b598f5e.png)
![2](https://user-images.githubusercontent.com/85124793/228874743-fcf16317-8501-4463-a4dd-e4c79a326dbe.png)
已提供

**Comment by hugoyue** [comment]
> Yidadaa

演示页面没有设置code，说明真的是你的token有问题

**Comment by Yidadaa** [comment]
可能是你的 token 被封了，你可以试试用其他的开源项目，比如 https://github.com/Chanzhaoyu/chatgpt-web
