### ISSUE TITLE
在存在 IPV6 的网络环境下无法访问

### ISSUE THREAD

**Issue by snycloud** [Yidadaa/ChatGPT-Next-Web#2451]
在存在 IPV6 的网络环境下无法访问

访问时日志报错如下
Error: connect ECONNREFUSED 2408:820c:7517:b2d0::697:46566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '2408:820c:7517:b2d0::697',
  port: 46566
}
Error: connect ECONNREFUSED 2408:820c:7517:b2d0::697:46566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '2408:820c:7517:b2d0::697',
  port: 46566
}

**Comment by Yidadaa** [comment]
网络问题请自行排查。

**Comment by JianleiZhang** [comment]
<img width="528" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/7637056/58189ec2-fe30-4de7-a55e-571e45927844">
试试在容器启动时，禁用IPv6协议栈。

**Comment by Vigilans** [comment]
> 网络问题请自行排查。

@Yidadaa 这是因为chatgpt-next-web只监听了ipv4 0.0.0.0:
```
$ sudo ss -nap | grep 34515                                                                                                                                                                                                        ​
tcp   LISTEN     0      511   0.0.0.0:34515  0.0.0.0:*        users:(("node",pid=1275121,fd=26))
```
然后chatgpt-next-web的某段代码尝试访问ipv6地址::1，于是就出错了。

**Comment by ujfjhz** [comment]
请问为什么不同时监听 ipv6?  @Yidadaa
