### ISSUE TITLE
[Feature] “禁止自动滚动到底部”的功能

### ISSUE THREAD

**Issue by AjianYo** [Yidadaa/ChatGPT-Next-Web#2461]
使用场景：非全屏下输出长文本

描述：在工作环境下一般设置为窄窗，由于默认是随着文本的生成自动滚动到最低部，所以在输出长文本时，不断地向下滚动比较影响效率。否则需要把窗口放大很多。

预期效果：
① 未触发鼠标滚动时，生成文本过程，自动滚动到底部
② 触发鼠标滚动时，即使正在生成文本，也停留在触发鼠标的位置

最后，真的非常感谢这个项目，Mac平台上综合体验几乎是数一数二的👍，respect

**Comment by Yidadaa** [comment]
你只需要往上滚动一下消息，就会停止自动滚动。

**Comment by Yidadaa** [comment]
大多数聊天软件的滚动逻辑都是这样。

**Comment by Yidadaa** [comment]
如果你发现向上滚动之后，没有自动停止滚动，请在此附上操作系统、客户端版本号、浏览器版本号，我会核查后考虑是否开启此 issue。
