### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by zjzjzjzj1874** [Yidadaa/ChatGPT-Next-Web#2466]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
暂无

**你想要什么功能或者有什么建议？**
考虑到很多用户会把服务部署到公网访问，内容审核其实还是比较关键，尤其在国内访问。
建议可以添加一个配置的内容审核过滤服务，这里有一个免费使用的内容审核服务，[ScanA](http://scana-docs.yunaq.com/)；
如果有需要的话，可以对这个issue提PR。
欢迎沟通交流。

**有没有可以参考的同类竞品？**
同类竞品：
https://www.chatgpu.net/
![851690167885_ pic](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/47138343/7499f8ee-3790-41eb-9292-7c22dbf4af7b)

**其他信息**
可以达到这种效果的

**Comment by Yidadaa** [comment]
请自行在接口层面实现。
