### ISSUE TITLE
[Feature] Search chat item

### ISSUE THREAD

**Issue by 0x9be00ff1** [Yidadaa/ChatGPT-Next-Web#2467]
**Is your feature request related to a problem? Please describe.**
feature request: simple local search chat item by title and chat history, make it easy to find history items

**Comment by RennCheung** [comment]
<img width="1326" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/50518861/e8262797-7593-4a7e-9698-ee088f33e2ef">

I have tried to implement this function, which supports searching topic and message, but does not support viewing specific message for the time being. If possible, I will submit this pr
@Yidadaa

**Comment by nkbai** [comment]
期待pr的合并

**Comment by Yidadaa** [comment]
#2158
