### ISSUE TITLE
本地Docker部署 怎样让API通过代理访问OPENAI网站呢？

### ISSUE THREAD

**Issue by joshinewon** [Yidadaa/ChatGPT-Next-Web#248]

**Comment by Yidadaa** [comment]
重复 #120

**Comment by hqzh** [comment]
> Docker 需要定义变量 `BASE_URL`和 `PROTOCOL`，其中 `BASE_URL` 配置为代理接口地址，[可自行部署代理接口](https://github.com/imyuanx/chatgpt-proxy) 或者 使用别人用 [CF Worker](https://github.com/x-dr/chatgptProxyAPI) 提供的代理接口地址，请自行选择。

使用腾讯云函数已处理，但是OPENAI_API_KEY没设置上
