### ISSUE TITLE
[Bug] 余额查询异常

### ISSUE THREAD

**Issue by gopcn** [Yidadaa/ChatGPT-Next-Web#2480]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [√] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
余额查询异常（没有对查询余额的接口使用代理）
**如何复现**
请告诉我们你是通过什么操作触发的该问题。
自己vercel部署余额查询异常，在https://chatgpt1.nextweb.fun输入自己的OpenAI API Key也是查询异常，能正常对话,不影响使用
**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/121377609/f591c4ee-8ede-40d2-b09c-1687eabbefaf)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/121377609/1415a509-b83c-430d-a49b-75c4c69f764c)
**一些必要的信息**
 - 系统：[windows 11/ android 10]
 - 浏览器： [edge,夸克浏览器]
 - 版本： [v2.9.1]
 - 部署方式：[vercel]

**Comment by IlluminateDarkheat** [comment]
官方查余额接口目前只能用登录网页端产生的 cookie `sess-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` 来查询，无法通过 API Key 查询。
