### ISSUE TITLE
能否增添架构在replit上面的功能

### ISSUE THREAD

**Issue by KayCHENvip** [Yidadaa/ChatGPT-Next-Web#2481]
vercel被墙了，国内正常访问需要绑定域名，学生党买不起，能不能增添架构在replit的功能

**Comment by Yidadaa** [comment]
10 块钱的域名都买不起？

https://buy.cloud.tencent.com/domain

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/75b16718-31e2-4006-9f15-8e230d614629)

**Comment by Yidadaa** [comment]
10 块钱一年还要啥自行车。
