### ISSUE TITLE
[Bug] 我不开防火墙能正常使用 我开了防火墙就不能正常使用 报这个错误"message": "Post \"https://api.openai.com/v1/chat/

### ISSUE THREAD

**Issue by danggerenba** [Yidadaa/ChatGPT-Next-Web#2482]
{
  "error": {
    "message": "Post \"https://api.openai.com/v1/chat/completions\": dial tcp: lookup api.openai.com on 8.8.4.4:53: read udp 172.17.0.2:37286->8.8.4.4:53: read: no route to host",
    "type": "one_api_error",
    "param": "",
    "code": "do_request_failed"
  }
}

**Comment by Yidadaa** [comment]
这是 one api 的报错。
