### ISSUE TITLE
[Bug] 请求报错

### ISSUE THREAD

**Issue by Pa5sw0rd** [Yidadaa/ChatGPT-Next-Web#2485]
昨天还好好地，今天就不行了，我测试了接口是没问题的
TypeError: A request with a one-time-use body (it was initialized from a stream, not a buffer) encountered a redirect requiring the body to be retransmitted. To avoid this error in the future, construct this request from a buffer-like body initializer.

**Comment by Yidadaa** [comment]
升级代码。

**Comment by Pa5sw0rd** [comment]
> 升级代码。

升级重新部署后仍存在改问题，使用vercel部署

**Comment by Yidadaa** [comment]
收到了几例报告，看来升级代码不能解决问题，尝试：https://stackoverflow.com/questions/55920957/cloudflare-worker-typeerror-one-time-use-body
