### ISSUE TITLE
[Feature] 仅特定域名有效以支持 Cloudflare Access

### ISSUE THREAD

**Issue by vicevolf** [Yidadaa/ChatGPT-Next-Web#2492]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**

- 网页只用密码保护，存在一定的爆破风险；安全的密码却记忆困难，Access 可以免密登录。
- 推荐 Vercel 部署，但 Vercel 访问管理属于高级功能需要额外支出；Cloudflare 直接部署兼容性差，Access 却是免费的。

**你想要什么功能或者有什么建议？**

如果能用 Cloudflare Access 将这种网页应用保护起来，安全性和便捷性可以大幅提升。不直接在 Cloudflare 部署，可以给 Vercel 的项目自定义域名到 Cloudflare，启用 Access。**但是 Vercel 会在部署时同时生成 xxxxx.vercel.app 的网址**，这些网页也是可以用 API key 的，等于给 Access 开了一个后门，无法起到应有的保护作用。

是否可以在 Vercel 的环境变量中，配置一个“有效域名”，配置后仅在自定义的特定域名提供服务，其他域名的访问全都拒绝，这样就可以安全的使用的 Access 免登录进行身份验证了。不配置依然所有域名均可访问，也不会影响到现有的用户。

**有没有可以参考的同类竞品？**
抱歉打扰了🙇，我不太确定能否实现，但应该能提高产品的安全性。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
Vercel 默认分配的域名可以手动删掉，你删了就行了：

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/c98b5be5-b947-42dc-a26b-4f5d58fb7ad0)

**Comment by vicevolf** [comment]
> Vercel 默认分配的域名可以手动删掉，你删了就行了：
> 
> ![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/c98b5be5-b947-42dc-a26b-4f5d58fb7ad0)
> 

不是这个自定义域名，是在部署页面会按仓库名称等生成预览的域名，也是可以用环境里配置的 API key 的。如果vercel直接默认部署，很容易按公开的仓库信息，找到这个网址，还望您再考虑下这个安全风险。
![Screenshot_2023-07-27-10-31-05-902_com.kiwibrowser.browser.jpg](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/47265026/ca704676-485e-4a94-ba7a-5e0cd102a400)

![IMG_20230727_103259.jpg](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/47265026/08d0a824-9295-4a5f-b3c6-379a86aab4bd)
