### ISSUE TITLE
宝塔面板容器部署，更新版本后出现错误码-111

### ISSUE THREAD

**Issue by adamliu926** [Yidadaa/ChatGPT-Next-Web#2494]
{   "cause": {     "errno": -111,     "code": "ECONNREFUSED",     "syscall": "connect",     "address": "224.0.0.1",     "port": 443   } }[Bug]

**Comment by Yidadaa** [comment]
国内不能直连。

**Comment by bingbaicai** [comment]
> 国内不能直连。

大佬。我现在知晓是要走代理，我菜鸟不知道如何弄，我OP上开了科学的，我要如何设置才能让我这个容器走代理呢，我是照搬的你的代码安装的，

**Comment by ersaijun** [comment]
> > 国内不能直连。
> 
> 大佬。我现在知晓是要走代理，我菜鸟不知道如何弄，我OP上开了科学的，我要如何设置才能让我这个容器走代理呢，我是照搬的你的代码安装的，

我服务器也是国内的，现在在考虑要不要买个国外的服务器……

**Comment by bingbaicai** [comment]
> > > 国内不能直连。
> > 
> > 
> > 大佬。我现在知晓是要走代理，我菜鸟不知道如何弄，我OP上开了科学的，我要如何设置才能让我这个容器走代理呢，我是照搬的你的代码安装的，
> 
> 我服务器也是国内的，现在在考虑要不要买个国外的服务器……

后面 搞定了。不过我发现这种还是要账户有钱才行的

**Comment by bahuzh** [comment]
代理用了127.0.0.1吧，改成非lo地址就可以了

**Comment by yellow13441** [comment]
注意：如果你的代理是在本地启动，而不是在Docker容器内启动。
Notice: If your proxy is launched locally instead of within a Docker container.

docker: Add --net=host in your command.
docker-compose: Add network_mode: "host" in your docker-compose.yml.
