### ISSUE TITLE
[Feature] Quick model switcher

### ISSUE THREAD

**Issue by JKamsker** [Yidadaa/ChatGPT-Next-Web#2498]
**Is your feature request related to a problem? Please describe.**
The need to navigate to settings to switch models during an ongoing chat is inconvenient.

**Describe the solution you'd like**
Add a feature to change models directly from the chat interface, enhancing efficiency and flexibility. There should be a default selection (for e.g: GPT-3, GPT-4) but the user should be able to change the available options from the settings menu.

**Describe alternatives you've considered**
Switching models from the settings menu.

**Additional context**
This request is inspired by ChatGPT's model-switching feature. It'll offer more control over the conversation to users, allowing for better, context-specific interaction.

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/00d7d9f5-b8a7-43a0-a7b1-e42b732e7c33)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/d4183ecf-138d-4ad7-9ea7-5b44e1074ca5)

**Comment by Yidadaa** [comment]
If your site doesn't show this icon, sync your code: https://github.com/Yidadaa/ChatGPT-Next-Web#keep-updated

**Comment by JKamsker** [comment]
Oh thank you 😅

**Comment by JKamsker** [comment]
@Yidadaa Could you add settings to disable not needed models? Like i only need Gpt3.5 16k turbo and gpt4
