### ISSUE TITLE
关于想部署在自己的海外服务器上面快速访问的问题

### ISSUE THREAD

**Issue by Jasion552** [Yidadaa/ChatGPT-Next-Web#25]
我是小白，不太懂代码，请问如果要部署在自己服务器上的话，需要什么环境和依赖

**Comment by Yidadaa** [comment]
你好，可以问问 chatgpt，使用下面的 prompt：

如何使用 pm2 和 yarn 部署 nextjs 到 ubuntu 服务器上，项目启动命令为 yarn start，端口为 3000，使用 ngnix 做反向代理，环境变量为 OPENAI\_API\_KEY

**Comment by Jasion552** [comment]
好的太谢谢了！


| |
lucky2582023
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Yifei ***@***.***> |
| 发送日期 | 2023年3月25日 21:17 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Yidadaa/ChatGPT-Next-Web] 关于想部署在自己的海外服务器上面快速访问的问题 (Issue #25) |

你好，可以问问 chatgpt，使用下面的 prompt：

如何使用 pm2 和 yarn 部署 nextjs 到 ubuntu 服务器上，项目启动命令为 yarn start，端口为 3000，使用 ngnix 做反向代理，环境变量为 OPENAI_API_KEY

**Comment by Jasion552** [comment]
UI设计得很棒，但我使用得时候，在网页版要翻阅聊天记录得时候，就算我没有发送任何信息也会自动回跳到最新的聊天来，不知道是BUG还是我自己使用的问题，


| |
lucky2582023
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Yifei ***@***.***> |
| 发送日期 | 2023年3月25日 21:17 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Yidadaa/ChatGPT-Next-Web] 关于想部署在自己的海外服务器上面快速访问的问题 (Issue #25) |

Closed #25 as completed.
