### ISSUE TITLE
最新版本，随机性调成2不崩溃了，但是，回复会乱码

### ISSUE THREAD

**Issue by ruixing1001** [Yidadaa/ChatGPT-Next-Web#250]
![image](https://user-images.githubusercontent.com/128834242/228894212-c7d13e68-9e89-4374-af7e-968a9fbda79a.png)
![image](https://user-images.githubusercontent.com/128834242/228894265-8bdec782-e27c-42d5-9c9f-5bc52ec6aba9.png)

**Comment by Yidadaa** [comment]
openai 的问题
