### ISSUE TITLE
[Feature] 可以为面具或者单个对话设置不同的api地址

### ISSUE THREAD

**Issue by mushan0x0** [Yidadaa/ChatGPT-Next-Web#2506]
**Describe the solution you'd like**
这样就可以为一个对话设置gpt接口，另一个对话设置claude接口

**Comment by damonyang007** [comment]
请问作者，为每个面具配置单独的key和url，在功能开发的清单中吗？

**Comment by Yidadaa** [comment]
面具是可以二次分发，把 key 和 url 放进去不现实。
