### ISSUE TITLE
[Feature] 希望可以支持公式显示

### ISSUE THREAD

**Issue by paststrange** [Yidadaa/ChatGPT-Next-Web#2507]
chat版已经支持latex公式了，希望能支持latex公式。

**Comment by Yidadaa** [comment]
?

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/816e1bd4-2402-4b12-9536-bad74bcf9022)

**Comment by remann2** [comment]
其实$...$、$$...$$还不能代表latex公示，\(...\) 和 \[...\] 分别在latex中代表inline和display math。如上图所示，
```
(x） 和(y) 是两个待比较的图像。
(mu_x)和(mu_y)分别表示（x）和(y) 的亮度平均值。
```
这里其实gpt返回了 \\(x\\) 和 \\(y\\)，转义的 \ 又被隐藏了，所以没有被正确地显示。由于经常和公示打交道，希望这部分可以特殊处理一下，比如将 \\(...\\)替换为$...$, 将\\[...\\]替换为$$...$$.
