### ISSUE TITLE
[Bug] 无法输入code

### ISSUE THREAD

**Issue by Ezgx** [Yidadaa/ChatGPT-Next-Web#2508]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/110729988/eb06cbe0-5d9c-4a67-ad21-4ab4c5690432)
设置里没有输入授权码的选项

**Comment by Yidadaa** [comment]
环境变量不填 CODE，就不会有填写选项：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#code-%E5%8F%AF%E9%80%89
