### ISSUE TITLE
[Bug] GPT遗忘对话历史

### ISSUE THREAD

**Issue by ProgramFan** [Yidadaa/ChatGPT-Next-Web#2509]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
GPT在对话中不记得上一条消息是什么，导致下一个问题无法关联当前上下文。

**如何复现**
连续问三个问题：
1. 简单解释霍尔效应。
2. 它的数学公式是什么？
3. 我给你发了几条消息？

**截图**
<img width="1167" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/32396/3ca9e3a9-0498-4f75-aa1a-aee01b22a74a">

**一些必要的信息**
 - 系统：macos latest
 - 部署方式：desktop app

**Comment by ProgramFan** [comment]
After several experiments,  I discovered that this happens only when I set `max_tokens` to 0. Is this still a bug? Please close this if max_tokens can not be set to 0.

**Comment by Yidadaa** [comment]
Certainly, don't set `max_tokens` to 0, indicating that you do not wish for ChatGPT to provide any response.
