### ISSUE TITLE
配置环境变量无效

### ISSUE THREAD

**Issue by LingweiMeng** [Yidadaa/ChatGPT-Next-Web#251]
deploy后，仍需要在设置页面填写api_key
且更换设备后无法记住

**Comment by hugoyue** [comment]
> 

配置存储在浏览器而不是存储在数据库。

**Comment by hugoyue** [comment]
> > > 
> > 
> > 
> > 配置存储在浏览器而不是存储在数据库。
> 
> 这不应该是一个bug吗？

这个项目不涉及数据库，你想多个设备都能直接用，就把API Key在变量中配置好就可以了。

**Comment by LingweiMeng** [comment]
是的 但是目前dea3d26 配置环境变量无效
