### ISSUE TITLE
[Feature] 在环境变量中设置 CustomModel 以及 自定义隐藏的Model

### ISSUE THREAD

**Issue by Sam5440** [Yidadaa/ChatGPT-Next-Web#2511]
因为人在国内，
直接在openai上来付费不是很方便，
所以只能购买第三方转发的api，
但是第三方转发的api可能会有些不同的模型名字来对应不同的价格，
例如Azure自部署模型和poe这些，
在每个设备上手动设置这些模型名字就很麻烦，
希望可以被支持，感谢

**Comment by iamsad3508** [comment]
Is there still no plan for this? The model list is getting very long now, and some models seem not to be that popular since the introduction of GPT-3.5-1106 and GPT-4-turbo-preview.

**Comment by Yidadaa** [comment]
@iamsad3508 In plan, you wont wait too long.
