### ISSUE TITLE
关于那行代理怎么弄

### ISSUE THREAD

**Issue by bingbaicai** [Yidadaa/ChatGPT-Next-Web#2512]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我按教程
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/66243694/0aa4e984-3314-4962-9bfb-5e502bae6023)
这样部署了登录进去提问吗反应，我知道肯定是网络代理问题，我家的OP有科学，请问要如何给这个进行代理呢，我是直接照搬安装的。

**如何复现**
部署成功提问AI无反应。

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/66243694/de7f9e8f-9843-4e04-b8d7-2e0252534420)。

**一些必要的信息**
 - 系统：nas 7.2
 - 浏览器：edge
 - 版本： V2.9.1
 - 部署方式：docker

**Comment by JessySnow** [comment]
> > 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。
> 
> > [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)
> 
> **反馈须知**
> 
> ⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。
> 
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
> 
> * [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
> * [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
> * [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。
> 
> **描述问题** 我按教程 ![image](https://user-images.githubusercontent.com/66243694/257082756-0aa4e984-3314-4962-9bfb-5e502bae6023.png) 这样部署了登录进去提问吗反应，我知道肯定是网络代理问题，我家的OP有科学，请问要如何给这个进行代理呢，我是直接照搬安装的。
> 
> **如何复现** 部署成功提问AI无反应。
> 
> **截图** ![image](https://user-images.githubusercontent.com/66243694/257082870-de7f9e8f-9843-4e04-b8d7-2e0252534420.png)。
> 
> **一些必要的信息**
> 
> * 系统：nas 7.2
> * 浏览器：edge
> * 版本： V2.9.1
> * 部署方式：docker

把代理的地址换成局域网代理网关的地址

**Comment by bingbaicai** [comment]
> > > 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。
> > 
> > 
> > > [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)
> > 
> > 
> > **反馈须知**
> > ⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。
> > 请在下方中括号内输入 x 来表示你已经知晓相关内容。
> > 
> > * [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
> > * [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
> > * [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。
> > 
> > **描述问题** 我按教程 ![image](https://user-images.githubusercontent.com/66243694/257082756-0aa4e984-3314-4962-9bfb-5e502bae6023.png) 这样部署了登录进去提问吗反应，我知道肯定是网络代理问题，我家的OP有科学，请问要如何给这个进行代理呢，我是直接照搬安装的。
> > **如何复现** 部署成功提问AI无反应。
> > **截图** ![image](https://user-images.githubusercontent.com/66243694/257082870-de7f9e8f-9843-4e04-b8d7-2e0252534420.png)。
> > **一些必要的信息**
> > 
> > * 系统：nas 7.2
> > * 浏览器：edge
> > * 版本： V2.9.1
> > * 部署方式：docker
> 
> 把代理的地址换成局域网代理网关的地址

谢谢解答，后面解决了 不过我发现这样的也要账户里面有💰才行 😄
