### ISSUE TITLE
快速接入langchain开发的应用接口[Feature] 

### ISSUE THREAD

**Issue by wuheyi** [Yidadaa/ChatGPT-Next-Web#2513]
在开发大模型应用时，绝大多数场景下都需要用到langchain等python进行二次开发。
是否能将这类二次开发的功能快速接入到本系统内。
比如：我用langchain开发了个知识库，并提供了一个类似openai的流式API接口
是否可以在系统上配置下环境变量就能快速接入这个功能。
我看到插件功能正在开发中，未来插件功能是否能覆盖上面的需求。

**Comment by wuheyi** [comment]
目前chainlit是能实现上面的需求，无缝对接langchain，各位大佬可以参考下那个项目

**Comment by Yidadaa** [comment]
chainlit 和这个项目完全不同，没有可借鉴的地方，请关注插件功能的开发 #763
