### ISSUE TITLE
[bug]连接不上

### ISSUE THREAD

**Issue by Hack-XK** [Yidadaa/ChatGPT-Next-Web#2530]
打开链接不上，输入问题报错不显示。

你的api打开是404，是不是自带的api没了

这个：https://chatgpt1.nextweb.fun/api/proxy

提示报错：

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

**Comment by ersaijun** [comment]
> 打开链接不上，输入问题报错不显示。
> 
> 你的api打开是404，是不是自带的api没了
> 
> 这个：https://chatgpt1.nextweb.fun/api/proxy
> 
> 提示报错：
> 
> { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": "insufficient_quota" } }

mark，遇到同样问题

**Comment by Hack-XK** [comment]
没人回答一下吗？

**Comment by ersaijun** [comment]
> 没人回答一下吗？

我感觉是不是过期了呀，openai里看看

**Comment by Yidadaa** [comment]
是你 api key 过期了。

**Comment by Hack-XK** [comment]
>api没有过期，我已经测试了官方的，没有问题

**Comment by Hack-XK** [comment]
没人回答一下吗

**Comment by Hack-XK** [comment]
api都是对的，可用，我自己测试了官方的，为什么不能用，没人回答吗？
