### ISSUE TITLE
[Bug] Max tokens issue

### ISSUE THREAD

**Issue by yswlww** [Yidadaa/ChatGPT-Next-Web#2532]
Hi there,

When i used the models claude-2, the max tokens limits that only can set 32k , so we cannot used all 100k tokens, please help

**Comment by Yidadaa** [comment]
`max_tokens` will not be sent to server, so this number wont's actually affect the specific model.

**Comment by 113998274** [comment]
我也有相同情况，claude2的回答越来越少，不能显示全，修改max_tokens 没作用，不知道为何
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/15992600/502b6f65-e72e-4e28-8270-a171a993c1f3)

**Comment by redtier100x** [comment]
> I can understand this reason to remove the `max_tokens ` parameter. But it is necessary when I use customize models. For example, when I use vllm to serve a llama2 model, the default `max_tokens = 16` which is really unacceptable. So I really need a way to make the parameter works again.
> 
> Right now I just do a little patch like this:
> 
> ```diff
> diff --git a/app/client/api.ts b/app/client/api.ts
> index b04dd88..f6ab3bc 100644
> --- a/app/client/api.ts
> +++ b/app/client/api.ts
> @@ -19,6 +19,7 @@ export interface LLMConfig {
>    temperature?: number;
>    top_p?: number;
>    stream?: boolean;
> +  max_tokens?: number;
>    presence_penalty?: number;
>    frequency_penalty?: number;
>  }
> diff --git a/app/client/platforms/openai.ts b/app/client/platforms/openai.ts
> index fd4eb59..7ca8a1d 100644
> --- a/app/client/platforms/openai.ts
> +++ b/app/client/platforms/openai.ts
> @@ -70,6 +70,7 @@ export class ChatGPTApi implements LLMApi {
>        presence_penalty: modelConfig.presence_penalty,
>        frequency_penalty: modelConfig.frequency_penalty,
>        top_p: modelConfig.top_p,
> +      max_tokens: modelConfig.max_tokens,
>      };
> 
>      console.log("[Request] openai payload: ", requestPayload);
> ```

Is this still the best workaround for the low default max_token count? I"m running into this problem with llama-cpp-python server due to its openapi implementation defaulting to 16.
