### ISSUE TITLE
[Question] 有办法刷新所有用户的配置么? 

### ISSUE THREAD

**Issue by Kuri-su** [Yidadaa/ChatGPT-Next-Web#2533]
有办法刷新所有用户的配置么?  比方说 我想禁用 GPT4 的选项, 但由于之前用户浏览器上的GPT4 配置已经缓存到浏览器里, 所以即便我在服务端改了也没用

**Comment by Yidadaa** [comment]
服务端禁用了 gpt-4 之后，用户虽然选项还是 gpt-4，但是在发送消息之后服务器会提示拒绝提供服务。
