### ISSUE TITLE
[Feature] 能否出一个部署RWKV-runner模型的教程

### ISSUE THREAD

**Issue by itdsgithub** [Yidadaa/ChatGPT-Next-Web#2539]
chatgpt的额度到期了，
Vercel上能部署RWKV-runner之类的模型吗，能不能辛苦作者出一个相关的教程。

**Comment by Yidadaa** [comment]
不能，vercel 不是大模型推理平台，目前只能本地运行 rwkv-runner，然后修改接口地址为本地端口。

**Comment by Yidadaa** [comment]
大模型的部署成本，普通人根本负担不起。

**Comment by itdsgithub** [comment]
> 大模型的部署成本，普通人根本负担不起。

好吧，因为chatgpt额度到期了，我想好多人也遇到这种情况，我也在找一种能在线部署或者直接在线用接口调用程序的方式

**Comment by Yidadaa** [comment]
我的中转站内测了一段时间，目前已经稳定了，官方原价，有需要可以试试：https://api.nextweb.fun

**Comment by Lvjinhong** [comment]
I’m sorry, but I’m not sure what you are referring to. Could you please provide more context or information about the project and the interface you are referring to? I’ll try my best to help you.
