### ISSUE TITLE
[Bug] Mac 客户端使用自定义api 校验不通过

### ISSUE THREAD

**Issue by jh235** [Yidadaa/ChatGPT-Next-Web#2540]
**Describe the bug**
Mac 客户端使用自定义api 校验不通过，比如我的web访问地址是 https://xxxx.com, 网页输入密码能正常使用。使用mac 客户端，api地址设置的是 https://xxxx.com/api/openai/ 输入 密码之后还是提示 invalid_request_error，输入api-key 可以正常使用

**To Reproduce**
1. Mac 客户端输入自定义API
2. 登录输入密码
3. 发送聊天
4. 报错

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [✅] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 Macos 13.4 (22F66)
 2.9.1

**Additional Logs**
Add any logs about the problem here.

{
  "error": {
    "message": "This key is associated with a deactivated account. If you feel this is an error, contact us through our help center at help.openai.com.",
    "type": "invalid_request_error",
    "param": null,
    "code": "account_deactivated"
  }
}
是不是 校验有问题？

**Comment by Yidadaa** [comment]
你这个报错信息，表明你用的 api key 被封了。

**Comment by jh235** [comment]
但是这个网页版可以直接用，api key 没有问题
