### ISSUE TITLE
[Feature] 请问如何快速导入和导出面具？

### ISSUE THREAD

**Issue by sanbuphy** [Yidadaa/ChatGPT-Next-Web#2544]
你好，我有多个内置prompt，请问是否有什么快速的导入导出方法？（比如一个json） 谢谢

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/5db5dbb8-8e0c-4723-8ad8-3562e829b752)
