### ISSUE TITLE
求助：今天调用openai的3.5接口提示超出账号的配额？请问是什么原因？我登陆到openai的网站上查好像还没超额啊

### ISSUE THREAD

**Issue by xy-qimu** [Yidadaa/ChatGPT-Next-Web#2548]
{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

![微信截图_20230803120609](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/46561657/cf8b445c-8380-49b5-9ca6-4f5a8f6c8bd3)

**Comment by Yidadaa** [comment]
红色：Expired - 已失效。
