### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by 94zuocom** [Yidadaa/ChatGPT-Next-Web#2549]
> 希望可以存储到数据库，mysql sqlite pg都行（pg性能好点），并从结果中搜索回答，如果没有满意的答案再请求gpt

>

**Comment by CKylinMC** [comment]
看上去有点类似这个第三方服务文档提到的结果缓存 https://api2d.com/wiki/doc#api-cache

**Comment by Yidadaa** [comment]
接口缓存请自行实现。
