### ISSUE TITLE
能否增加对话页面的搜索功能

### ISSUE THREAD

**Issue by nkbai** [Yidadaa/ChatGPT-Next-Web#2550]
对话框能否支持搜索？
同一主题下面，累计对话时间久了以后，这时候想找一下以前问的问题，就比较麻烦。
而在web页面中可以使用浏览器的搜索功能，就没这个问题。

**Comment by ClarenceDan** [comment]
之前的一个关掉的pr里加了这个功能，可以去搜一下

**Comment by Yidadaa** [comment]
#2467

**Comment by Yidadaa** [comment]
#2467
