### ISSUE TITLE
浏览器上渲染性能问题

### ISSUE THREAD

**Issue by slinar** [Yidadaa/ChatGPT-Next-Web#2554]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
当对话记录过多时，点击最大化的时候响应变慢，大概消耗了0.5秒。下图第三个按钮
使用chrome性能分析看到重新计算样式使用了437ms, 受影响的元素4万多

**如何复现**
对话记录上百条(>500)时, 点击最大化按钮，清除对话记录后，新的对话恢复正常

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/41759351/6f2058cb-2043-4f68-b281-c9d6e9b993f9)

chrome性能分析如下图
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/41759351/fcc0a448-2bce-4111-82e6-0c8b3e385440)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器：chrome 114.0.5735.119
 - 版本：v2.9.2
 - 部署方式：服务器部署

**Comment by Yidadaa** [comment]
此问题已经被修复：#2545
