### ISSUE TITLE
[Bug] 余额查询是不是失效了

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#2559]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
余额查询不能用了

**如何复现**
、

**截图**
、

**一些必要的信息**
 - 系统： windows 10
 - 浏览器： chrome
 - 版本： v 2.9.2
 - 部署方式：vercel

**Comment by xlongshu** [comment]
好像是 求解决办法
- /api/openai/dashboard/billing/usage
- /api/openai/dashboard/billing/subscription

> 403 Forbidden


```json
{
  "error": {
    "message": "Your request to GET /dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
```

**Comment by Zer0CooL4ek** [comment]
2.9.0 was exactly everything worked.
since version 2.9.1 and in subsequent versions the problem is still present

**Comment by Yidadaa** [comment]
OpenAI 更改了这个接口的权限，现在所有人都用不了。

现在只有一个不完整的接口，无法直接查询密钥总用量，只能查询某天用量，可以在这里尝试使用：https://api.nextweb.fun/check
