### ISSUE TITLE
Attached Messages 数量超过 0 时无响应

### ISSUE THREAD

**Issue by l3ony2k** [Yidadaa/ChatGPT-Next-Web#256]
Vercel 搭建之后只要设置中 Attached Message 数量大于零，发送消息后会加载然后提示 something went wrong，尝试更换了 base url 问题依旧。一旦将 attached 设为零便没有问题。

**Comment by l3ony2k** [comment]
![Screenshot_20230331_022317_mark via](https://user-images.githubusercontent.com/58762081/228929566-8d357503-55bc-4b4d-a251-3f3099223c0b.jpg)

在其他设备上也有一样的问题，按照最新的 fork 构建的

**Comment by Yidadaa** [comment]
请在本项目的演示网址测试一下是否依然存在该问题。

**Comment by l3ony2k** [comment]
更新到最新版本的时候似乎问题解决了，应该是上次同步上游的时候更新到了一次不完整的更新。
