### ISSUE TITLE
[Bug] How to use ChimeraGPT

### ISSUE THREAD

**Issue by Joackk** [Yidadaa/ChatGPT-Next-Web#2560]
I used docker to build, which is the content of my configuration file.
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45162558/607fa753-05dd-4d20-ade3-983990c92351)
After I ran it, I sent a message, and he asked me to enter key.
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45162558/6f7c6fdf-13b3-454a-b0e6-074f98973758)
Then I set key and api in the settings
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45162558/797697af-254d-4a5e-84a0-035eb00aa21d)
At this time, I encountered a new problem.
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45162558/3dcc429c-1270-4ba5-ae2f-ca6a3fd5f3ba)

**Comment by Yidadaa** [comment]
删除链接里的 `/v1`

**Comment by Joackk** [comment]
> 删除链接里的 `/v1`

删掉环境变量里的v1就行了吗？其他的还有需要改动的吗？
