### ISSUE TITLE
[Feature] ChatGLM2-6B 模型的支持

### ISSUE THREAD

**Issue by pepsigold** [Yidadaa/ChatGPT-Next-Web#2567]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
https://github.com/THUDM/ChatGLM2-6B 
已经实现了 OpenAI 格式的流式 API 部署，可以作为任意基于 ChatGPT 的应用的后端，
官方推荐 比如 [ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)。可以通过运行仓库中的[openai_api.py](https://github.com/THUDM/ChatGLM2-6B/blob/main/openai_api.py) 进行部署。
具体为：

```
import openai
if __name__ == "__main__":
    openai.api_base = "http://localhost:8000/v1"
    openai.api_key = "none"
    for chunk in openai.ChatCompletion.create(
        model="chatglm2-6b",
        messages=[
            {"role": "user", "content": "你好"}
        ],
        stream=True
    ):
        if hasattr(chunk.choices[0].delta, "content"):
            print(chunk.choices[0].delta.content, end="", flush=True)
```
**你想要什么功能或者有什么建议？**
我在接口地址输入chatglm本地接口 http://192.168.1.111:8000/v1 
Chatgpt Next提示：

```json
{
  "error": true,
  "message": "NetworkError when attempting to fetch resource."
}
```

**其他信息**
希望up，接入chatglm本地模型，谢谢！

**Comment by onlinedear** [comment]
是时候考虑增加更多的模型了，chatgpt太不稳定了
