### ISSUE TITLE
[Bug] 设置中的接口地址是做什么用的？会导致token泄露么？

### ISSUE THREAD

**Issue by nkbai** [Yidadaa/ChatGPT-Next-Web#2581]
**描述问题**
默认值是https://chatgpt1.nextweb.fun/api/proxy，这个地址是用来做科学上网的代理么？ 
我用的是客户端，没有搭建任何网站。

**如何复现**
无法复现，30,31号两天的账单激增，平时只有一天几美分的账单，突然激增到一天十美元。 通过插件客户端使用记录发现一天只询问了十几个问题。

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/10471399/f915f426-dd2b-429d-9d89-4c92a540de4e)
**一些必要的信息**
 - 系统： macos 12 
 - 浏览器：客户端，非浏览器
 - 版本： 2.9.2
 - 部署方式：客户端运行

**我的问题**
这个接口地址如果是代理上网用，是否可能会导致token泄露。
我能用自己的代理么？我测试用我自己的http://127.0.0.1:8087，浏览器可以正常上网，但是无法使用。

**Comment by Yidadaa** [comment]
客户端默认使用项目自带的 openai 代理，源码：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/c41c498a9c42717d6ff77ba3fcfd3a5d67b5615a/next.config.mjs#L66

不会记录任何 api key 数据，如果你发现 api key 用量激增，请排查是否在其他渠道泄露，并第一时间在 openai 官方删除旧密钥，重新生成。

**Comment by nkbai** [comment]
> 

如果我想用自己的代理，http://127.0.0.1:8087，该怎么写呢？
