### ISSUE TITLE
这个目前不能实现插件联网这样的吗？

### ISSUE THREAD

**Issue by yangchen158158** [Yidadaa/ChatGPT-Next-Web#2587]
这个目前不能实现插件联网这样的吗？或者有别的方式联网吗 https://chrome.google.com/webstore/detail/sider-chatgpt-sidebar-gpt/difoiogjjojoaoomphldepapgpbgkhkb
这个谷歌插件，好像都是利用插件，直接实现联网的！

**Comment by Yidadaa** [comment]
计划中 #763
