### ISSUE TITLE
[Bug] -3007 这里时出现了什么问题 

### ISSUE THREAD

**Issue by Xiaofeng05** [Yidadaa/ChatGPT-Next-Web#2591]
**Describe the bug**
-3007 这里时出现了什么问题 
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/84329269/154708ae-e293-4a6d-bd72-3151ae2b6e49)

**Comment by taozi2001** [comment]
你好，请问问题解决了吗
