### ISSUE TITLE
[Bug] 客户端不能用自己的代理

### ISSUE THREAD

**Issue by nkbai** [Yidadaa/ChatGPT-Next-Web#2599]
一些必要的信息

系统： macos 12
浏览器：客户端，非浏览器
版本： 2.9.2
部署方式：客户端运行

## 问题描述

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/10471399/76c5b1f7-0f83-47eb-b89d-6742f5cf2302)
配置代理为自定义的后，出现错误
```
{
  "error": true,
  "message": "Load failed"
}
```

该代理可以正常在浏览器中通过代理上网

**Comment by Yidadaa** [comment]
你先区分清楚接口地址和本地代理，这是接口地址，不是代理地址，客户端不支持设置本地代理。

**Comment by nkbai** [comment]
客户端没有直接访问chatgpt的api？只能通过接口地址，由接口地址代理来访问的openai的api？
如果是这样，那如果接口地址所在的服务器被劫持了，岂不是所有的api_token都会泄露？

**Comment by Yidadaa** [comment]
我在客户端里提供了一个代理，你不放心就自己搭一个。

**Comment by nkbai** [comment]
如何替换这个代理呢？
