### ISSUE TITLE
我部署后一直无法使用，界面提示是【出错了，稍后重试吧】，vercel日志显示504报错

### ISSUE THREAD

**Issue by BingyuanXie** [Yidadaa/ChatGPT-Next-Web#26]
## 首先是出错截图
![Snipaste_2023-03-25_21-27-46](https://user-images.githubusercontent.com/46948396/227720019-bb7e1cd4-00f6-4da0-888c-75fd9bba432a.png)

## 在vercel的日志里面，有如下提示：
![Snipaste_2023-03-25_21-28-32](https://user-images.githubusercontent.com/46948396/227720089-e04b80b0-0ecf-4cf0-b4e0-2565c70549b6.png)

## 在openAI里面查看，显示我的key重来没用过，我检查下来发现key没有问题，在vercel里面，设置是这样的
![Snipaste_2023-03-25_21-30-39](https://user-images.githubusercontent.com/46948396/227720178-ff2fcd8f-8228-4b72-8a68-82e5ea7ca4ec.png)

请问作者大大，出现这个错误的最大可能是什么？

**Comment by Yidadaa** [comment]
看起来是 vercel edge function 无法访问到 openai 服务器了，可以试试修改 edge function 的服务器位置，按照下方设置操作，确保它是在美国的服务器上运行的：

<img width="760" alt="image" src="https://user-images.githubusercontent.com/16968934/227721639-1434d065-0064-4625-af1b-5ce620773aff.png">

**Comment by yuanlizhanshi** [comment]
同样是这样，服务器是美国的也不行

**Comment by Yidadaa** [comment]
那你需要确认 api key 能否使用了，可以使用另外的开源项目交叉验证下，比如这个：https://github.com/Chanzhaoyu/chatgpt-web

**Comment by yuanlizhanshi** [comment]
> 那你需要确认 api key 能否使用了，可以使用另外的开源项目交叉验证下，比如这个：https://github.com/Chanzhaoyu/chatgpt-web

不太清楚为啥？https://platform.openai.com/account/api-keys
这里面显示是已使用的

**Comment by Yidadaa** [comment]
确实不太好确认原因，目前只收到了你一个人的反馈遇到了这个问题，要不然你删除 vercel 的 project ，然后重新按步骤部署下？

**Comment by duolawag** [comment]
解决了嘛，我的也是【出错了，稍后重试吧】

**Comment by BingyuanXie** [comment]
> 解决了嘛，我的也是【出错了，稍后重试吧】

解决了，我重部署后解决，我猜测应该是把秘钥更正后没有重新部署的原因

**Comment by BingyuanXie** [comment]
> 确实不太好确认原因，目前只收到了你一个人的反馈遇到了这个问题，要不然你删除 vercel 的 project ，然后重新按步骤部署下？

感谢！我的问题解决了，大概率是我自己一开始秘钥弄错，重新修改后没有部署的原因

**Comment by BingyuanXie** [comment]
> 确实不太好确认原因，目前只收到了你一个人的反馈遇到了这个问题，要不然你删除 vercel 的 project ，然后重新按步骤部署下？

我自己没找到关闭的办法，麻烦大佬方便的时候处理一下

**Comment by aglent** [comment]
这个问题我也遇到了，deploy后，环境变量里设置了API-KEY，但是网页里报错，只有在网页里设置API-Key才能用，请指点哪里操作错了。

**Comment by gooker** [comment]
刚部署完了,同样错误

**Comment by aglent** [comment]
> 这个问题我也遇到了，deploy后，环境变量里设置了API-KEY，但是网页里报错，只有在网页里设置API-Key才能用，请指点哪里操作错了。

我又重新部署了一次，现在看起来可以用了。
