### ISSUE TITLE
[Feature] mirror website used is not/v1/chat/completions

### ISSUE THREAD

**Issue by qingdog** [Yidadaa/ChatGPT-Next-Web#2600]
The API of the mirror website used is not/v1/chat/completions, but chat/completions. Can I modify the code to change the request path?

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/69775024/cf0db657-2f0a-4b13-bf84-ccebb886012a)

I attempted to modify the following code but failed.

```js
export const OpenaiPath = {
  ChatPath: "v1/chat/completions",
  UsagePath: "dashboard/billing/usage",
  SubsPath: "dashboard/billing/subscription",
  ListModelPath: "v1/models",
};
```

**Comment by Yidadaa** [comment]
OpenaiPath.ChatPath
