### ISSUE TITLE
[Bug] 持续滚动存在跳跃现象

### ISSUE THREAD

**Issue by AjianYo** [Yidadaa/ChatGPT-Next-Web#2609]
**Describe the bug**
鼠标功能正常，使用鼠标持续滚动时会触发跳跃现象。

**Expected behavior**
比如：从底部开始，持续向上滚动界面，有时会导致跳跃过好几条消息，甚至半屏。

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: macOS 12
 - 桌面客户端
 - Version: v2.9.3

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
这是正常现象，为了聊天性能，做了分页懒加载，向上滑动过程中会不断自动加载过去的消息内容，滑动过快就会感受到跳跃，滑慢点就没事了。
