### ISSUE TITLE
[Feature] 增加生成标题功能选项：关闭、用户首次输入的Prompt、AI总结

### ISSUE THREAD

**Issue by imldy** [Yidadaa/ChatGPT-Next-Web#2613]
**你想要什么功能或者有什么建议？**

让用户控制生成标题功能的开关/生成逻辑。

暂可提供三个选项：

1. 不改变默认标题(关闭)
2. 用户Prompt文本(用户输入的前几个Prompt字符)
3. AI总结对话(目前方案)

**有没有可以参考的同类竞品？**

[Chanzhaoyu/chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web) 使用的是第二种方案，但没有限制字符长度。（它的实现，具体来说是不限于是首次输入，每次输入都会判断是否是默认标题，如果是则修改标题）。代码: https://github.com/Chanzhaoyu/chatgpt-web/blob/2b2efe2f1505653c34da7ad51a8e29e4a8c3ea66/src/store/modules/chat/index.ts#L121-L135

**其他信息**

目前使用的第三种方案，即 对话文本长度超过一个阈值 且 标题为默认标题 时，使用`gpt-3.5-turbo`生成标题。

代码：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/61852b4021448240d14af2178369da3ef5fd4f32/app/store/chat.ts#L487-L512

标题生成prompt（简体中文）：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/61852b4021448240d14af2178369da3ef5fd4f32/app/locales/cn.ts#L265-L266

但这存在几个问题: 

1. 浪费tokens。需要将最少1轮对话的tokens重复传入api。（如果第1轮对话后文本长度大于`SUMMARIZE_MIN_LEN`，将传第1轮，否则第2、3……轮）
2. 效果差强人意，难以找到合适的标题生成prompt。比如用户`prompt`为`翻译“从前，有兄弟两个人到郊外去打猎。正在这时，哥哥望见天上飞来了一只大雁，就准备拉弓把它射下来。”`，`gpt-3.5-turbo-16k`模型`completions`为`Once upon a time, there were two brothers who went hunting in the countryside. Just then, the older brother saw a large goose flying in the sky and prepared to shoot it down with his bow.`，但标题生成结果是`打猎`，偏重于prompt中的宾语`从前……射下来。`，而非谓语`翻译`。按照习惯来说，总结为`翻译一个关于打猎的故事`可能更为合适。原因可能是用户输入prompt中含有指令(谓语)+数据(宾语)，而数据占比大于指令，生成标题时模型就会混淆，因此效果较差。我试过其他的标题生成prompt，即便强调指令，效果也比较差。

目前通过修改标题为非默认标题，可关闭AI生成标题功能，但总归不算非常合理的开关。已见过多名网友对此表示疑惑。

因此，提供一个方便的选项尤为重要。

个人见解，欢迎讨论。

本人可认领此功能的开发，开发并测试后提交PR。

**Comment by imldy** [comment]
已完成用户选择部分，未实现具体控制代码。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/53949747/7b794c5c-a340-43a6-858d-cdbb3b7e94d5)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/53949747/a3c71f60-4487-462b-9897-2d2187d6594a)

可讨论选项位置是否合适。

**Comment by Yidadaa** [comment]
@imldy 提供布尔值，控制是否需要 auto generate title 就行，没必要整成下拉框。

**Comment by imldy** [comment]
> @imldy 提供布尔值，控制是否需要 auto generate title 就行，没必要整成下拉框。

刚看到，布尔值控制我早就实现了，我再PR一个。
