### ISSUE TITLE
[Bug] RTL character causes text direction issue

### ISSUE THREAD

**Issue by Algorithm5838** [Yidadaa/ChatGPT-Next-Web#2614]
___
**Describe the bug**
When an RTL (Right-to-Left) character is introduced in the text, the entire text becomes RTL, even in paragraphs that do not have an RTL character. This issue occurs when the text is not in editing mode.

**Expected behavior**
Each paragraph should follow the direction of its first character. If the first character is LTR (Left-to-Right), the whole paragraph should be LTR. If the first character is RTL, the whole paragraph should be RTL.

**Screenshots**
![Screenshot 2023-08-13 at 22 32 06](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/108630393/931abb19-401a-4536-9e4b-6e9035a87f60)
This is how the first question should look:
![Screenshot 2023-08-13 at 01 53 50](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/108630393/c116d79a-86ed-4c72-bdae-1762dc91a412)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome and Firefox]
 - Version [Latest]

**Smartphone (please complete the following information):**
 - OS: [Android]
 - Browser [Chrome and Firefox]
 - Version [Latest]

**Comment by leadscloud** [comment]
这不是算是bug吧，应该是正常的行为。
阿语是从右往左看的，在中东一些国家他们的网页都是从右往左布局的，对我们来说，看起来非常难受。

所以有阿语一般都会自动从右往左书写。在css中通过 direction可以控制。

```
style={{
        fontSize: `${props.fontSize ?? 14}px`,
        direction: /[\u0600-\u06FF]/.test(props.content) ? "rtl" : "ltr",
      }}
```

`direction: /[\u0600-\u06FF]/.test(props.content) ? "rtl" : "ltr",` 判断如果有阿语，就自动切换为rtl布局。

所以这是正常行为。如果非要从左往右，修改`app\components\markdown.tsx`中的代码。

**Comment by Algorithm5838** [comment]
Hey leadscloud,

Thanks for your response! I really appreciate you explaining the right-to-left behavior in relation to the Arabic language. Since I'm an Arabic speaker, I wanted to suggest a couple of solutions to fix the garbled text issue:

One solution could be to force a left-to-right (LTR) layout for all paragraphs, regardless of whether there are RTL characters or not. This would make it much easier for Arabic speakers like me to read the text.

Another idea, which I've seen implemented in Google Keep, is to check the first letter of each paragraph. If it's an LTR character, the paragraph should be displayed in LTR, and if it's an RTL character, the paragraph should be displayed in RTL. This way, each paragraph follows its natural direction and provides a better user experience.

An example from Google Keep:
![SmartSelect_20230813_224946_Keep Notes](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/108630393/27def30a-dd37-4136-9a52-d2bfc83fafdf)

I know I'm not a developer, but I think these suggestions could really improve the readability for Arabic speakers who struggle with the garbled text issue.

Thanks for considering these ideas!

**Comment by Algorithm5838** [comment]
I just wanted to drop a quick thank you note to express my gratitude for your assistance. I just used ChatGPT and followed your hints to write some code, and guess what? It worked like a charm! I'm really thrilled with the outcome, especially with the second solution I suggested.

I also want to give a shoutout to Yidadaa for developing such an amazing UI.

Here is a screenshot after the new edits:
![Screenshot 2023-08-14 at 02 35 07](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/108630393/b8ae0c3d-8510-44ab-a981-d28407dfbe50)

And another screenshot of the edited code:
![Screenshot 2023-08-14 at 02 35 41](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/108630393/1bcdc9d6-c1f8-414f-a783-26fb28d681bd)

Here is the code, it might need some edits, but I believe you have a better understanding of implementation, so I'll leave it to your expertise:
```
    <>
      {paragraphs.map((paragraph, index) => (
        <p
          key={index}
          style={{
            direction: /\p{Script=Latin}/u.test(paragraph.trim().charAt(0))
              ? "ltr"
              : "rtl",
          }}
        >
          {paragraph}
        </p>
      ))}
    </>
```
I'm not entirely sure about the code that ChatGPT removed.

**Comment by Algorithm5838** [comment]
Sorry, big mistake for non-Latin or RTL scripts.
Here is the correct one:
```
    <>
      {paragraphs.map((paragraph, index) => (
        <p
          key={index}
          style={{
            direction: /\p{Script=Arabic}/u.test(paragraph.trim().charAt(0))
              ? "rtl"
              : "ltr",
          }}
        >
          {paragraph}
        </p>
      ))}
    </>
```

**Comment by leadscloud** [comment]
这看起来是个简单的问题，处理起来可能是比较复杂的，需要考虑的情况很多，[比如希伯来语(he)，阿拉伯语(ar)](https://developer.mozilla.org/zh-CN/docs/Glossary/RTL)

[阿拉伯语](https://en.wikipedia.org/wiki/Arabic)、[希伯来语](https://en.wikipedia.org/wiki/Hebrew_language)、[波斯语](https://en.wikipedia.org/wiki/Persian_language)、[乌尔都语](https://en.wikipedia.org/wiki/Urdu)、[克什米尔](https://en.wikipedia.org/wiki/Kashmiri_language)语、[普什图语](https://en.wikipedia.org/wiki/Pashto)、[维吾尔](https://en.wikipedia.org/wiki/Uyghur_language)语、[索拉尼库尔德语](https://en.wikipedia.org/wiki/Sorani_Kurdish)、[旁遮普](https://en.wikipedia.org/wiki/Punjabi_language)语和[信德语](https://en.wikipedia.org/wiki/Sindhi_language)是现代最广泛使用的 RTL 书写系统 
https://en.wikipedia.org/wiki/Right-to-left_script

如果全部处理需要一个单独的库比如react-intl 来判断语言，对于混合内容 又需要特别处理，也许可以在界面上方有一个提示按钮，让用户选择LTR还是RTL。

当然，最简单的判断就是当前的写法，

content contains arabric 
```
direction: /[\u0600-\u06FF]/.test(props.content) ? "rtl" : "ltr",
```

content start with arabric
```
direction: /^[\u0600-\u06FF]/.test(props.content) ? "rtl" : "ltr",
```

这是一个比较小众的需求，有需求的可以直接修改以上代码。

今天学到一个新知识： `/\p{Script=Arabic}/u`是阿语的正则匹配，是一种 Unicode 正则表达式属性，用于匹配所有阿拉伯语字符

**Comment by Yidadaa** [comment]
Just use `dir="auto"`.

https://github.com/remarkjs/react-markdown/issues/197#issuecomment-1000627807

**Comment by Yidadaa** [comment]
Fixed:

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/bcdceee3-f464-4173-8b98-6f9453ace93d)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/6c788bf8-2f58-4882-a104-75e46139b7fa)
