### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by TonyGeez** [Yidadaa/ChatGPT-Next-Web#2616]
Hello, first thing firt, i should say that is probably the most sharp and nice webapp related to openai api.
Thanks to all contributor.

I would like to know if there a setting that should be configured/updated and where it should be, to be able to upload file and send to gpt4 model.

If i can remmeber correctly, the chatpt-midjourney project had this option, i would like to know if there a way to add it etc or if it related to option in some file that need to be activated.

 (Im talking about the true file send to gpt4 api model, and not the file to text.)
 
 thanks alot.

**Comment by Yidadaa** [comment]
OpenAI's gpt-4 API still does not support receiving files, only the official web UI: chat.openai.com supports direct file uploads.
