### ISSUE TITLE
模型不能正确地切换

### ISSUE THREAD

**Issue by gallifreyCar** [Yidadaa/ChatGPT-Next-Web#263]
设置中选择model好像并不能正确的切换
我去openapi后台查了一下，只有默认的模型：gpt-3.5-turbo ,正确发起了请求
选择其他model：gpt4，gpt4-32k...都不能正确发起请求,[openapi后台](https://platform.openai.com/account/usage) 都没有请求记录

**Comment by Yidadaa** [comment]
请确认自己账号有 gpt4 api 权限，chatgpt plus 不能保证你有 gpt4 api 权限。

**Comment by gallifreyCar** [comment]
我刚刚发现了这个问题，原来plus 用户并没有 gpt4 api权限，只有网页端的使用权
我已经在https://openai.com/waitlist/gpt-4-api申请gpt4 api的权限了，谢谢你的回答
