### ISSUE TITLE
Extreme Lag after a recent update[Bug] 

### ISSUE THREAD

**Issue by chen-rn** [Yidadaa/ChatGPT-Next-Web#2635]
**Describe the bug**
Recently ChatGPT Next Web has became incredibly laggy when using.

**To Reproduce**
Try using gpt-3.5-turbo(so the output writes fast) and ask ChatGPT for a long answer.
Ie. please write me a 500 word privacy policy for a generic mobile game.

For me, it gets really slow then crashes.

**Comment by Yidadaa** [comment]
Please provide the code version number and the operating system version

**Comment by Yidadaa** [comment]
#2393
