### ISSUE TITLE
有方法可以在不同的设备上保存聊天历史吗

### ISSUE THREAD

**Issue by Alpha2J** [Yidadaa/ChatGPT-Next-Web#264]
现在应该是本地保存的？因为切换设备后记录就消失了，怎么才能持久化呢

**Comment by lidedongsn** [comment]
是同样的问题

**Comment by Yidadaa** [comment]
不会增加任何云同步功能。

**Comment by LiangYang666** [comment]
因为vercel是云函数，不能含有状态信息，做不了云同步聊天记录，如果想同步记录可以看看这个仓库https://github.com/LiangYang666/ChatGPT-Web

**Comment by yuntian123456** [comment]
我想应该是为了安全性考虑，所以不增加云同步功能。这个我赞同。
如果真的有需求，也许作者可以考虑增加导入聊天记录功能。

**Comment by LiangYang666** [comment]
如果是个人部署在自己的云容器上，云同步应该不存在你说的安全问题吧，这个云地址只有自己知道，也只有自己能访问

**Comment by yuntian123456** [comment]
> 如果是个人部署在自己的云容器上，云同步应该不存在你说的安全问题吧，这个云地址只有自己知道，也只有自己能访问

假如说code被盗或一不小心泄露了，别人一登录看到了之前的聊天记录。。。

**Comment by LiangYang666** [comment]
> > 如果是个人部署在自己的云容器上，云同步应该不存在你说的安全问题吧，这个云地址只有自己知道，也只有自己能访问
> 
> 假如说code被盗或一不小心泄露了，别人一登录看到了之前的聊天记录。。。

关键是CODE（访问密码）应该不会轻易泄露吧，这是部署服务的时候自己设的环境变量，且仓库也是private的，网址也是只有自己知道，既然一般我们在其它网站的账号密码都不会泄露，这个code应该也不会轻易泄露吧

**Comment by Yniije** [comment]
想问问这个的数据是存在游览器的哪个数据本地文件夹里面？我想进去把聊天记录一次性拿出来备份
