### ISSUE TITLE
[Bug] Docker PROXY_URL参数问题

### ISSUE THREAD

**Issue by iWangza** [Yidadaa/ChatGPT-Next-Web#2642]
**Describe the bug**
开启docker实例的时候，代理地址按教程给的PROXY_URL参数进行设置的话，docker实例会无法正常启动。
改成BASE_URL解决，所以这个教程是不是有问题。
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/110147552/f4d4259b-1c99-4393-9ab5-bb4162d9380b)

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by zuosc** [comment]
是这样的 这是一个bug.  应该使用 BASE_URL
