### ISSUE TITLE
[Bug] 根据 CloudFlare 文档配置报错

### ISSUE THREAD

**Issue by xJoyLu** [Yidadaa/ChatGPT-Next-Web#2643]
根据此文档指引进行配置。
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/cloudflare-pages-cn.md
报错日志：

22:47:08.055 | [4/4] Building fresh packages...
-- | --
22:47:08.081 | $ husky install
22:47:08.210 | husky - Git hooks installed
22:47:08.220 | Done in 50.56s.
22:47:08.269 | Executing user command: npx https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/4930842298/npm-package-next-on-pages-230 --experimental-minify
22:47:11.062 | npm ERR! code E404
22:47:11.064 | npm ERR! 404 Not Found - GET https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/4930842298/npm-package-next-on-pages-230
22:47:11.064 | npm ERR! 404
22:47:11.064 | npm ERR! 404  'https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/4930842298/npm-package-next-on-pages-230' is not in this registry.
22:47:11.065 | npm ERR! 404 This package name is not valid, because
22:47:11.065 | npm ERR! 404  1. name can only contain URL-friendly characters
22:47:11.065 | npm ERR! 404
22:47:11.065 | npm ERR! 404 Note that you can also install from a
22:47:11.065 | npm ERR! 404 tarball, folder, http url, or git url.
22:47:11.066 |  
22:47:11.067 | npm ERR! A complete log of this run can be found in: /opt/buildhome/.npm/_logs/2023-08-16T14_47_09_746Z-debug-0.log
22:47:11.077 | Failed: Error while executing user command. Exited with error code: 1
22:47:11.092 | Failed: build command exited with code: 1
22:47:13.817 | Failed: error occurred while running build command

**Comment by Yidadaa** [comment]
cf 并非是首要支持平台，出了问题无人维护，你可以尝试使用 yarn export 命令导出静态产物部署。

**Comment by zhaosound** [comment]
我也遇到了，看了下应该是next-on-pages近期更新的问题，参照这里 [https://github.com/cloudflare/next-on-pages/issues/433](https://github.com/cloudflare/next-on-pages/issues/433)，试试`npx @cloudflare/next-on-pages@1.5.0`，这样我部署成功了。
