### ISSUE TITLE
[Bug] 访问被拦截

### ISSUE THREAD

**Issue by hazoop** [Yidadaa/ChatGPT-Next-Web#2644]
**Describe the bug**
偶发的现象，问代码相关的就会出错，看图吧

**Expected behavior**

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/25174977/45b5c161-b4df-47d7-9b4f-eb55c6143303)
**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - Browser [chrome,]
 - Version [e.g. 90]

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
去找你的服务提供商反馈问题。
