### ISSUE TITLE
Dock image is not available.

### ISSUE THREAD

**Issue by PackFan2019** [Yidadaa/ChatGPT-Next-Web#2650]
I tried to pull this dock image from docker, docker pull yidadaa/chatgpt-next-web  （8/17/2023 12：15 PM US CST,  in US)

but I always face error saying that 

Dock image is not available.

I do not know if there is something wrong with Docker website or it might be just related to my network.  just FYI if other people has this same problem.

**Comment by Yidadaa** [comment]
Require Docker version >= 20
