### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HuylensHu** [Yidadaa/ChatGPT-Next-Web#2656]
fork代码在vercel部署，添加了BASE_URL环境变量，发现并没有用，打开控制台发现log[Request] openai payload下面是一行报错POST https://我的访问地址/api/openai/v1/chat/completions 403，在页面的设置里的endpoint输入之后可以正常使用。把代码在本地跑却可以使用，BASE_URL生效了。是不是vercel把BASE_URL设置成了访问地址了

**Comment by Yidadaa** [comment]
去看 vercel 侧的 log，看看 BASE_URL 生效没。

**Comment by HuylensHu** [comment]
没有生效，我把代码改了，只是把BASE_URL换了个名字之后就正常了，可能BASE_URL是vercel的保留字段
