### ISSUE TITLE
[Bug] 报错error

### ISSUE THREAD

**Issue by grayoranges** [Yidadaa/ChatGPT-Next-Web#2658]
部署完后gpt回答问题经常会回复这种异常怎么解决:

```json
{
  "cause": {
    "code": "ECONNRESET",
    "host": "api.openai.com",
    "port": 443,
    "localAddress": null
  }
}
```

{
  "cause": {
    "name": "ConnectTimeoutError",
    "code": "UND_ERR_CONNECT_TIMEOUT",
    "message": "Connect Timeout Error"
  }
}

**Comment by Yidadaa** [comment]
确保你的服务器能直连 openai 服务。

**Comment by woshichenghaibo** [comment]
> 确保你的服务器能直连 openai 服务。

啊？国内的服务器没戏了呗？
