### ISSUE TITLE
[Bug] 提示缺少许可内容No license field，测试时候编译时间很久

### ISSUE THREAD

**Issue by DFDzaidu** [Yidadaa/ChatGPT-Next-Web#2662]
[root@RainYun-yWl9bu0c ChatGPT-Next-Web]# yarn dev
yarn run v1.22.19
warning ../package.json: No license field
$ next dev
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /www/wwwroot/v.zaidu.in/ChatGPT-Next-Web/.env
[Next] build mode standalone
[Next] build with chunk:  true
- warn You have enabled experimental feature (forceSwcTransforms) in next.config.mjs.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

warning ../package.json: No license field
- event compiled client and server successfully in 4.5s (20 modules)
- wait compiling...
- event compiled client and server successfully in 1469 ms (20 modules)
[Next] build mode standalone
[Next] build with chunk:  true
- wait compiling /page (client and server)...

**Comment by Yidadaa** [comment]
Not a bug.
