### ISSUE TITLE
增加对latex公式语法的兼容

### ISSUE THREAD

**Issue by remann2** [Yidadaa/ChatGPT-Next-Web#2664]
其实$...$、$$...$$还不能代表latex公示，\(...\) 和 \[...\] 分别在latex中代表inline和display math。gpt返回公示的典型输出：
```
(x） 和(y) 是两个待比较的图像。
(mu_x)和(mu_y)分别表示（x）和(y) 的亮度平均值。
```
这里其实gpt返回了 \\(x\\) 和 \\(y\\)，转义的 \ 又被隐藏了，所以没有被正确地显示。由于经常和公示打交道，希望这部分可以特殊处理一下，比如将 \\(...\\)替换为$...$, 将\\[...\\]替换为$$...$$.

_Originally posted by @remann2 in https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2507#issuecomment-1685081750_

**Comment by Yidadaa** [comment]
这里用的是 markdown 语法，在 markdown 里，latex 公式就是被 $ 和 $$ 裹起来的。

**Comment by Yidadaa** [comment]
你应该在 prompt 里让 gpt 帮你自动转换为 markdown 格式的公式。
