### ISSUE TITLE
希望增加一个撤回前一条消息的动能

### ISSUE THREAD

**Issue by cheng6563** [Yidadaa/ChatGPT-Next-Web#267]
感激不尽

**Comment by hugoyue** [comment]
正在回复的答案不及预期，我觉得提前取消回复会比这个更满足实际需求一些。如果你觉得是个需求，好像已经有人提过了。

**Comment by cheng6563** [comment]
> 正在回复的答案不及预期，我觉得提前取消回复会比这个更满足实际需求一些。如果你觉得是个需求，好像已经有人提过了。

有时候是自己的提问方式错了，这样还是直接把这个提问删掉好一些，其实隔壁的ChuanhuChatGPT就有这功能的，无奈他们那个项目不知道是不是python的原因内存占用实在有点大。。。

**Comment by GOWxx** [comment]
可以考虑的功能是 [对话可删除]

**Comment by Cp0204** [comment]
还有个场景，我输入了一段代码，结果太长超过toekn了。没法删除，后面提交还会带上历史的这段代码输入和error输出。尴尬。。。

![QQ截图20230403092143](https://user-images.githubusercontent.com/5239753/229391326-f781994d-ada9-4515-a2d5-539c11f37fee.png)

**Comment by Yidadaa** [comment]
#510
