### ISSUE TITLE
希望可以增加修改对话标题的功能

### ISSUE THREAD

**Issue by afresh** [Yidadaa/ChatGPT-Next-Web#268]
官网是可以编辑对话标题的，因为自动生成标题无法准确描述对话的内容，下次打开时，不方便查找以前的对话。

**Comment by hugoyue** [comment]
> 官网是可以编辑对话标题的，因为自动生成标题无法准确描述对话的内容，下次打开时，不方便查找以前的对话。

最新版本，点击标题就可以修改。

**Comment by afresh** [comment]
@hugoyue 用`docker pull yidadaa/chatgpt-next-web`拉取的镜像不是最新的版本么？为什么我的点击不了？

**Comment by hugoyue** [comment]
> @hugoyue 用`docker pull yidadaa/chatgpt-next-web`拉取的镜像不是最新的版本么？为什么我的点击不了？

你试试加上latest的tag再拉取一遍
