### ISSUE TITLE
[Problem]  Malware Detection on VirusTotal 6/71

### ISSUE THREAD

**Issue by boromyr** [Yidadaa/ChatGPT-Next-Web#2680]
**Describe the issue**
The executable [exe](https://github.com/Yidadaa/ChatGPT-Next-Web/releases/download/v2.9.4/ChatGPT.Next.Web_2.9.4_x64-setup.exe) tests positive for scanning on [VirusTotal](https://www.virustotal.com/gui/file/0405e6b62e4660f5e9f16ef2860336424dd39c5a0ed9b55c5e59152409895bb2)

The executable [msi](https://github.com/Yidadaa/ChatGPT-Next-Web/releases/download/v2.9.4/ChatGPT.Next.Web_2.9.4_x64_en-US.msi) results clean, but the [exe](https://www.virustotal.com/gui/file/1836c74e4191282189efc39ce3af36e0126dbb21df934da2cf65a659d93541b1) installed from the msi package results positive with 3/69 detections

**Some necessary information**
 - System: Windows 11
 - Version: 2.9.4
 - Deployment method: releases on GitHub

**Comment by Yidadaa** [comment]
二进制文件使用 tauri actions 自动构建，你可以尝试自行构建并重新测试，我相信这应该是误报。

workflow: https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/.github/workflows/app.yml
logs: https://github.com/Yidadaa/ChatGPT-Next-Web/actions/runs/5901771382
