### ISSUE TITLE
[Questions] Which model is used for GPT-4?

### ISSUE THREAD

**Issue by galendai** [Yidadaa/ChatGPT-Next-Web#2681]
I have chosen `gpt-4` under the model dropdown list, however when I check the usage under my OpenAI billing it indicates I have made calls using `gpt-4-0613`.

Is it a bug or expected?

Thx for the magnificent work.

**Comment by reece00** [comment]
using GPT-3.5-Turbo also shows GPT-3.5-Turbo-0613

**Comment by Yidadaa** [comment]
This is the default behavior of OpenAI
