### ISSUE TITLE
[Feature] 为何这个项目的接口返回的很快？

### ISSUE THREAD

**Issue by RookieGz** [Yidadaa/ChatGPT-Next-Web#2682]
**Is your feature request related to a problem? Please describe.**
为什么这个项目的接口返回的很快，我项目的方案是使用云函数做的代理部署在硅谷，但是openai api的返回特别的慢，有时能达到3分钟左右，但是这个项目的接口返回的很快，我们使用的models都是gpt-3.5-turbo，

我想向作者请教一下这个问题。谢谢

**Comment by Yidadaa** [comment]
不要用美国本土的代理，把你的代理函数放到东亚地区，比如新加坡、香港、日本这些地方。
