### ISSUE TITLE
[Problem] BUILTIN_CONFIG_URL 环境变量无法使用

### ISSUE THREAD

**Issue by singledoggy** [Yidadaa/ChatGPT-Next-Web#2686]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
#1302 中提到的功能性环境变量BUILTIN_CONFIG_URL在docker和源码编译下均无法启用，搜索[源码](https://github.com/search?q=repo%3AYidadaa%2FChatGPT-Next-Web+process.env&type=code#:~:text=app/config/server.ts)也无法找到BUILTIN_CONFIG_URL这一变量位置，这一功能是尚未merge还是改名了？

**Comment by Yidadaa** [comment]
此功能尚未实现。
