### ISSUE TITLE
这个项目是不是不需要自己搞反向代理

### ISSUE THREAD

**Issue by riba2534** [Yidadaa/ChatGPT-Next-Web#269]
看起来请求 openai 接口的这一步是在 vercel 服务器中进行的，相当于已经自带反代了？应该不需要填自己的反向代理地址

**Comment by afresh** [comment]
需要，最好稳定的代理，不然很容易超时报错。

**Comment by riba2534** [comment]
> 

对，我意思是 vercel 部署，是相当于白嫖了他们当反代？

**Comment by AprilNEA** [comment]
issue 无关，请不要在此处讨论
