### ISSUE TITLE
[Feature] Better JSON Exporter

### ISSUE THREAD

**Issue by kfear1337** [Yidadaa/ChatGPT-Next-Web#2692]
**Is your feature request related to a problem? Please describe.**
This is a continuation of the commits by @wangwentong-lunaon, which added support for JSON export. You can find the commits [here](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2636/commits/b380421fd56da4d9faa5646afa4468c2a954ddc7).

**Describe the solution you'd like**
I would like to add this feature because it would be useful for GPT-3.5 Turbo fine-tuning. OpenAI has recently updated their system, and you can read about the updates [here](https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates).
**Before Code:** [here](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2636/commits/b380421fd56da4d9faa5646afa4468c2a954ddc7)

**Output JSON before adding the feature:**
```json
[
  {
    "role": "user",
    "content": "I want you to act as a Linux terminal. I will type commands, and you will reply with what the terminal should show. I want you to only reply with the terminal output inside one unique code block, and nothing else. Do not write explanations. Do not type commands unless I instruct you to do so. When I need to tell you something in English, I will do so by putting text inside curly brackets {like this}. My first command is pwd."
  },
  {
    "role": "assistant",
    "content": "```\n/home/user\n```"
  }
]
```
**The Code *(before)*:** 

```tsx
export function JsonPreviewer(props: {
  messages: ChatMessage[];
  topic: string;
}) {
  const msgs = props.messages.map((m) => ({
    role: m.role,
    content: m.content,
  }));
  const mdText = "\n" + JSON.stringify(msgs, null, 2) + "\n";

  const copy = () => {
    copyToClipboard(JSON.stringify(msgs, null, 2));
  };
  const download = () => {
    downloadAs(JSON.stringify(msgs, null, 2), `${props.topic}.json`);
  };

  return (
    <>
      <PreviewActions
        copy={copy}
        download={download}
        showCopy={true}
        messages={props.messages}
      />
      <div className="markdown-body">
        <pre className={styles["export-content"]}>{mdText}</pre>
      </div>
    </>
  );
}
  ```

**The Code *(After If you add)*:** 
```tsx
// modified by BackTrackZ now it's looks better

export function JsonPreviewer(props: {
  messages: ChatMessage[];
  topic: string;
}) {
  const msgs = {
    messages: [
      {
        role: "system",
        content: "You are an assistant that " + props.topic,
      },
      ...props.messages.map((m) => ({
        role: m.role,
        content: m.content,
      })),
    ],
  };
  const mdText = "```json\n" + JSON.stringify(msgs, null, 2) + "\n```";
  const minifiedJson = JSON.stringify(msgs);

  const copy = () => {
    copyToClipboard(minifiedJson);
  };
  const download = () => {
    downloadAs(JSON.stringify(msgs), `${props.topic}.json`);
  };

  return (
    <>
      <PreviewActions
        copy={copy}
        download={download}
        showCopy={false}
        messages={props.messages}
      />
      <div className="markdown-body" onClick={copy}>
      <Markdown content={mdText} />
      </div>
    </>
  );
}
```

**Output JSON after adding the code:**
```json
{
  "messages": [
    {
      "role": "user",
      "content": "I want you to act as a linux terminal. I will type commands and you will reply with what the terminal should show. I want you to only reply with the terminal output inside one unique code block, and nothing else. do not write explanations. do not type commands unless I instruct you to do so. when i need to tell you something in english, i will do so by putting text inside curly brackets {like this}. my first command is pwd"
    },
    {
      "role": "assistant",
      "content": "```\n/home/user\n```"
    }
  ]
}
```
**[+] A view looks better, after adding _The Code_ since it using markdown.**
here is a view 

![looks better](https://i.imgur.com/WuY0Hn8.png)

**Describe alternatives you've considered**
The code exports a React functional component called `JsonPreviewer`. It takes two props: `messages` (an array of `ChatMessage` objects) and `topic` (a string). It then generates a JSON preview of the messages and displays it using the `PreviewActions` and `Markdown` components.

   Some alternative considerations could include:
   - Choosing a different data structure for `messages` instead of an array, depending on the specific requirements or constraints of the application.
   - Exploring different ways to format or present the JSON preview, such as using a different library or custom styling.
   - Considering alternative methods for copying the JSON content to the clipboard or downloading it, depending on the target platform or user experience requirements.

**Additional context**
Without further information or comments, it's challenging to provide specific additional context for this code. However, based on the code's purpose and structure, some possible contextual details could include:
   - The `ChatMessage` type, which is not shown in the code snippet, but likely contains properties like `role` and `content`.
   - The purpose or use case of the `JsonPreviewer` component, such as displaying a JSON representation of chat messages for debugging or analysis purposes.
   - The dependencies or imports used in the code, such as the `PreviewActions`, `Markdown`, and possibly other components or utility functions like `copyToClipboard` and `downloadAs`.

Keep in mind that the provided code snippet is limited, and without more information or a broader code context, it's challenging to provide a comprehensive understanding of the alternatives considered or additional context specific to this code.

**Comment by Yidadaa** [comment]
Looks good, you can submit a pull request and I will merge it.
