### ISSUE TITLE
[Bug] escape dollar sign when referring money

### ISSUE THREAD

**Issue by johan456789** [Yidadaa/ChatGPT-Next-Web#2693]
**Describe the bug**
Dollar signs are incorrectly treated as math.

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14802181/f0a44b65-890e-4b01-aaaf-cb637a338ec9)

**To Reproduce**

Ask any question that gets an answer with multiple dollar signs. My prompt:

```
"An ATM option has a delta of ±0.50, positive if it is a call, negative for a put."

why 0.5?
```

**Expected behavior**
Dollar signs escaped when used as money not math.

ChatGPT:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14802181/42528c64-5086-48bc-adb0-8a2de26fc57d)

**Deployment**
Vercel

**Desktop (please complete the following information):**
 - Browser Arc v1.4.1 (40966)

**Comment by kfear1337** [comment]
not a bug that's output, are from openai api.

**Comment by johan456789** [comment]
Did you check if the output you got contains dollar signs? Here's my raw text of the output I get:

```
The delta of an option represents the sensitivity of its price to changes in the price of the underlying asset. A delta of ±0.50 for an at-the-money (ATM) option means that the option's price will change by approximately half the amount of the change in the price of the underlying asset.

For a call option, a delta of +0.50 means that if the price of the underlying asset increases by $1, the price of the call option will increase by approximately $0.50. On the other hand, for a put option, a delta of -0.50 means that if the price of the underlying asset decreases by $1, the price of the put option will increase by approximately $0.50.

The delta of an option is influenced by several factors, including the price of the underlying asset, the strike price of the option, the time to expiration, and the volatility of the underlying asset. An ATM option, where the strike price is equal to the current price of the underlying asset, typically has a delta of around ±
```

**Comment by kfear1337** [comment]
yeah the raw output its legit from openai
about text show like this
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/71199b11-852a-43e4-84cd-db70eb05df6b)
its issue from a package `mermaid` or `react-markdown` maybe

**Comment by Yidadaa** [comment]
The $ symbol is used in markdown to display mathematical formulas, so if there are $ symbols in the output, this project will attempt to parse them as mathematical formulas, which is why you see them in italics. If you want to avoid this behavior, you can add "escape all $ symbols as \$" in the system prompt.
