### ISSUE TITLE
[疑问] 关于自定义对话里的system角色

### ISSUE THREAD

**Issue by toyo2333** [Yidadaa/ChatGPT-Next-Web#2695]
问题1：我想看到你设置的通用面具中，自定义的预设都使用的是user这个角色。我想问问 system这个角色的作用，以及通常在场景和情况下使用呢？

问题2：现在官方GTP客户端支持了‘自定义指令’，我想问问，它设置的自定义指令里的两段内容，如果要在ChatGTP-next-web中实现，那么应该对应的是哪个（些）角色，以及怎么设定？

盼望解答，谢谢！

**Comment by Yidadaa** [comment]
1. 一般用于系统设定，和 user 其实差别并不大；
2. system
