### ISSUE TITLE
Will a Docker version be released?

### ISSUE THREAD

**Issue by Voldeemort** [Yidadaa/ChatGPT-Next-Web#27]
Will a Docker version be released?

**Comment by Yidadaa** [comment]
I am not familiar with Docker, but you can ask ChatGPT: [https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README.md#docker-deployment](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README.md#docker-deployment)

If you make it, PR is welcomed.

**Comment by Voldeemort** [comment]
> I am not familiar with Docker, but you can ask ChatGPT: https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README.md#docker-deployment
> 
> If you make it, PR is welcomed.

ok, thanks

**Comment by AprilNEA** [comment]
I think it would be difficult to implement this, Nextjs 13, which started the experimental functionality of appDir, is not suitable for local deployment, it requires Edge Runtime support, and secondly the current knowledge of ChatGPT only goes up to around 2021, when Nextjs is not yet released.
