### ISSUE TITLE
[Bug] 配置了BASE_URL 但是设置自定义密码就报错 直接填写 官方key 就正常

### ISSUE THREAD

**Issue by cnucky** [Yidadaa/ChatGPT-Next-Web#2701]
接口和 key 都是没问题的 但是不知道哪里的出的问题
报错信息
 `
{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}
`

难道设置过了BASE_URL 还有去页面里面也改下么？

**Comment by Yidadaa** [comment]
重新设置之后需要重新部署才能生效。
