### ISSUE TITLE
[Bug] A small bug of chatgpt icon when exporting message as image

### ISSUE THREAD

**Issue by kfear1337** [Yidadaa/ChatGPT-Next-Web#2702]
**Describe the bug**
The bug is related to the `ChatGptIcon` in the text "chatgpt next web" glitching when taking a screenshot in the `ImagePreviewer` component. The `ChatGptIcon` sometimes appears distorted or does not appear at all in the captured screenshot.

**To Reproduce**
To reproduce the bug, follow these steps:
1. Open the application and navigate to the `ImagePreviewer` component.
2. Ensure that the `ChatGptIcon` is visible in the preview area.
3. Take a screenshot of the `ImagePreviewer` component using the provided functionality.
4. Review the captured screenshot and observe the appearance of the `ChatGptIcon`.

**Expected behavior**
The `ChatGptIcon` should appear correctly in the captured screenshot without any distortion or glitches. It should maintain its original appearance as displayed in the `ImagePreviewer` component.

**Screenshots**
![Screenshot_75](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/2dc6ac7f-621e-4848-9055-e8fd2aa0af42)
**Deployment**
- [x] All
- [ ] All
- [ ] All

**Desktop (please complete the following information):**
 - OS: All Device Sometimes
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All Device Sometimes
 - OS: All
 - Browser All
 - Version All

**Additional Logs**
If you merge my commits a bug will be fixed  here is a screenshot
![Screenshot_76](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/e3c061db-dd32-4ec3-a093-c1980e1f05fb)

**Comment by Yidadaa** [comment]
I don't think it's because the image hasn't finished loading. This could be a flaw in `html-to-image`. Can you provide more information about the pr?

**Comment by kfear1337** [comment]
its happen sometimes 
other proof in pc version (this was old arround almost 1 month, when first time I figure out)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/4ba16bce-ff6a-4aa9-b6b9-6f8738a09524)
![ChatGPT API vs chat openai com (1)](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/3a7b521f-a48f-40f4-a332-1716b2e83f54)

**Comment by kfear1337** [comment]
here is my website with this commit https://github.com/kfear1337/ChatGPT-Next-Web/commit/bda2f109a2c8de2c197e4631d6d2584968bc6fe0
https://chatgpt.btz.pm/

**Comment by Yidadaa** [comment]
看起来并不是这个原因，即便是在你的网站上，我也能复现这个 bug。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/3c6279af-fecf-4c27-9bd3-de7346c7caa4)

**Comment by kfear1337** [comment]
wait what its so weird
it work for me
and this in yours site 
![心灵导师](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/699315db-7671-4a96-81d6-41d2fad770e7)

**Comment by kfear1337** [comment]
@Yidadaa can you try again on my website ?
I change a logic of the code
and was rename of icon name `ChatGptIcon.src` -> `ChatGptIconTest.src`
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/ec4d2741-781d-47e5-81d9-ea8a20227b2d)

**Comment by kfear1337** [comment]
@Yidadaa its bug glitching cause  `DEFAULT_MASK_AVATAR`
Instead of using `NextImage` in the `ExportAvatar` function for `DEFAULT_MASK_AVATAR`, it would be better to use `img`. 
because when `NextImage` is used for `DEFAULT_MASK_AVATAR`, it causes a bug where the `ChatGPTicon.src` 
glitches and breaks then it switch to a `BotIcon.src`, when exporting the image for the second time without refreshing the page.
Here is a problem I sent video 

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/dfc45971-c08b-48b7-ab15-cdc433d5f7b1

**Source :**
```tsx
function ExportAvatar(props: { avatar: string }) {
  if (props.avatar === DEFAULT_MASK_AVATAR) {
    return (
      <NextImage
        src={BotIcon.src}
        width={30}
        height={30}
        alt="bot"
        className="user-avatar"
      />
    );
  }

  return <Avatar avatar={props.avatar}></Avatar>;
}
```
**If you modify that code with this** 
```tsx
function ExportAvatar(props: { avatar: string }) {
  if (props.avatar === DEFAULT_MASK_AVATAR) {
    return (
      <img
        src={BotIcon.src}
        width={30}
        height={30}
        alt="bot"
        className="user-avatar"
      />
    );
  }

  return <Avatar avatar={props.avatar} />;
}
```
**and this for dom safety**
```tsx
export function ImagePreviewer(props: {
  messages: ChatMessage[];
  topic: string;
}) {
  const chatStore = useChatStore();
  const session = chatStore.currentSession();
  const mask = session.mask;
  const config = useAppConfig();

  const previewRef = useRef<HTMLDivElement>(null);

  const copy = () => {
    showToast(Locale.Export.Image.Toast);
    const dom = previewRef.current;
    if (!dom) return;
    toBlob(dom).then((blob) => {
      if (!blob) return;
      try {
        navigator.clipboard
          .write([
            new ClipboardItem({
              "image/png": blob,
            }),
          ])
          .then(() => {
            showToast(Locale.Copy.Success);
            refreshPreview();
          });
      } catch (e) {
        console.error("[Copy Image] ", e);
        showToast(Locale.Copy.Failed);
      }
    });
  };

  const isMobile = useMobileScreen();

  const download = () => {
    showToast(Locale.Export.Image.Toast);
    const dom = previewRef.current;
    if (!dom) return;
    toPng(dom)
      .then((blob) => {
        refreshPreview();
        if (!blob) return;

        if (isMobile || getClientConfig()?.isApp) {
          showImageModal(blob);
        } else {
          const link = document.createElement("a");
          link.download = `${props.topic}.png`;
          link.href = blob;
          link.click();
        }
      })
      .catch((e) => console.log("[Export Image] ", e));
  };

  const refreshPreview = () => {
    const dom = previewRef.current;
    if (dom) {
      dom.innerHTML = dom.innerHTML; // Refresh the content of the preview by resetting its HTML
    }
  };
  ```
  **it will be fixed**

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/158490d3-38a1-4e0a-ad90-6e437e3c484a

**Comment by Yidadaa** [comment]
@kfear1337 Thank you, this sounds reasonable. Could you open a new pull request to address this issue? Please also create a separate pull request for the new language translation. Thank you very much!

**Comment by kfear1337** [comment]
Done all already separate
