### ISSUE TITLE
[Bug] 为什么要把api路由暴露出来？

### ISSUE THREAD

**Issue by crazyming9528** [Yidadaa/ChatGPT-Next-Web#2714]
**描述问题**
将项目部署到公网，发现被盗刷，排查日志发现，有人在 通过工具请求  项目地址.com/api/xxx 的接口，api接口会直接转发到openai，请问为什么这么设计？也没有关闭的地方

**如何复现**
例如请求 项目地址/api/openai/v1/chat/completions

看到之前的 issues ，想必是接口被盗刷造成的：https://github.com/Yidadaa/ChatGPT-Next-Web/issues/518

**Comment by reece00** [comment]
你也太jb聪明了，建议你换个软件吧

**Comment by Yidadaa** [comment]
请使用项目 README 中介绍的密码功能防护你的 api 接口。
