### ISSUE TITLE
[Bug] Docker 容器Nginx反向代理问题

### ISSUE THREAD

**Issue by jiaxudonggit** [Yidadaa/ChatGPT-Next-Web#2718]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
1、nextJs 更新为13.4.19后，docker容器无法通过nginx反向代理。
2、初步原因是HOSTNAME为127.0.0.1，所以无法正常通过0.0.0.0:3000连接。
3、后将HOSTNAME修改为0.0.0.0，又报错如下：
<img width="821" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/41093243/7177e8a5-1272-4c31-9f57-46108bff750b">
4、发现当前版本nextJs启动方式有区别：
新（13.4.19）：
<img width="358" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/41093243/029a8e16-263a-484b-bb99-cc67d76b1e38">
旧（13.4.9）：
<img width="683" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/41093243/e8ff37a0-2a64-470c-850a-7b72ca207485">

疑似该问题导致：https://github.com/vercel/next.js/pull/54203

**如何复现**
构建最新版本的docker镜像后即可复现该问题。

**截图**
<img width="821" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/41093243/7177e8a5-1272-4c31-9f57-46108bff750b">
<img width="358" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/41093243/029a8e16-263a-484b-bb99-cc67d76b1e38">
<img width="683" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/41093243/e8ff37a0-2a64-470c-850a-7b72ca207485">

**一些必要的信息**
 - 系统：macos 13.4.1/ linux 
 - 浏览器：chrome
 - 版本：2.9.5
 - 部署方式：docker

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2721

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/actions/runs/5995150083/job/16257748308

**Comment by Yidadaa** [comment]
以及回退到旧版本 nextjs 并重新构建了 docker 镜像，请重新拉取 latest 版本 docker 镜像后重试。

**Comment by kevinriver** [comment]
我在nginx里把127.0.0.1改为0.0.0.0后可以了

**Comment by luandro** [comment]
I'm having similar issue:
```
{
  "cause": {
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "172.21.0.18",
    "port": 443
  }
}
```

Tried adding `DEFAULT_HOST=0.0.0.0` to `nginxproxy/nginx-proxy` but didn't make any difference. Any tips on how to solve @kevinriver?
