### ISSUE TITLE
[Bug] 无法余额查询，出现？

### ISSUE THREAD

**Issue by Oject** [Yidadaa/ChatGPT-Next-Web#2719]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
无法余额查询，出现？

**如何复现**
每次必现

**截图**
![01e6a1d9fd06bbbf888ca7dfaba2fc08](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/13999771/61da6b87-3fa2-4a2a-85eb-18b82253dfbc)

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [chrome]
 - 版本： [v.2.9.5]
 - 部署方式：[https://chatgpt1.nextweb.fun/]

**Comment by jiaxudonggit** [comment]
+1

**Comment by jiaxudonggit** [comment]
好像是查询余额的接口参数需要携带一个session key
响应的msg：Your request to GET /dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.

**Comment by Yidadaa** [comment]
openai 不让查了
