### ISSUE TITLE
希望取得联系，并支持 InternLM

### ISSUE THREAD

**Issue by JimmyMa99** [Yidadaa/ChatGPT-Next-Web#2723]
尊敬的 ChatGPT-Next-Web 应用开发者，我是 InternLM 社区开发者&志愿者尖米, 大佬开源的工作对我的启发很大，希望可以探讨使用 InternLM 实现 ChatGPT-Next-Web 的可能性和实现路径，我的微信是 mzm312，希望可以取得联系进行更深度的交流；

**Comment by Yidadaa** [comment]
只需要像 ChatGLM2-6B 这样提供一个 openai 兼容脚本即可：

https://github.com/THUDM/ChatGLM2-6B/blob/main/openai_api.py
