### ISSUE TITLE
[Feature] 能支持一下微软 Azure 的open ai开出来的接口地址吗

### ISSUE THREAD

**Issue by slx618** [Yidadaa/ChatGPT-Next-Web#2738]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by slx618** [comment]
https://cloud.dify.ai/ 有类似的的功能

<img width="841" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14901275/63fb8faa-086b-434d-af53-0311d6c4243f">

**Comment by Yidadaa** [comment]
#371

**Comment by dadaoerv** [comment]
自己搭建完全免费的平台，one api
