### ISSUE TITLE
https 如何实现 证书要放在哪里

### ISSUE THREAD

**Issue by JhonCageWang** [Yidadaa/ChatGPT-Next-Web#274]
我有个问题想问下 我用nginx 代理https 到docker 部署的这个项目 但是 感觉体验方式就不一样了 它的对话就是一下出来不是strem流的方式
如果不用nginx 如何实现https 麻烦回复一下哈谢谢

**Comment by Yidadaa** [comment]
加群问。

**Comment by rainyLeo** [comment]
我也遇到用 nginx 代理到 https 后 event-stream 不生效的问题，nginx 配置里加下解决了
proxy_buffering off;
proxy_cache off;
