### ISSUE TITLE
如何使用微调后的模型

### ISSUE THREAD

**Issue by oldunclez** [Yidadaa/ChatGPT-Next-Web#2740]
请问如何使用微调后的模型？
我有一个微调后的模型，训练了一些私人数据，名称是ft:gpt-3.5-turbo-0613:personal:yyyy:xxxx
若要使用这个模型，如何设置 ? 如下图？
但是设置后，似乎不生效，因为我问了关于私人数据问题，没有得到正确的回复。

按照https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates 这个方法
我使用curl能获取到正确的回复

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/6986430/00ed14d7-5e18-4d0a-918f-deb1c6b767b5)

**Comment by Yidadaa** [comment]
你需要在下方的模型选择下拉列表中手动选中刚刚添加的自定义模型名。

**Comment by oldunclez** [comment]
我使用以下数据训练的。

```json
{"messages": [{"role": "system", "content": "You are a helpful assistant of xxxxx company."}, {"role": "user", "content": "离职流程是如何?"}, {"role": "assistant", "content": "先找到张三，然后xxx，再去那里，再提交证书，再签名."}]}
```
curl 可以获取到预期答案

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/6986430/1afa2c3b-97ce-4342-86f8-8291ea94faaa)
 
web中没有得到预期答案

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/6986430/4a1af22a-7b27-48fb-b96d-9e99bc0739dc)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/6986430/6fc47923-ffa2-45cb-93eb-0849fdc7abfe)
