### ISSUE TITLE
[Feature] Hide User Key之后，聊天界面预置语句没有变化

### ISSUE THREAD

**Issue by noteshs** [Yidadaa/ChatGPT-Next-Web#2743]
就是说，我禁止用户输入自己的Key后，设置页面这块是关掉了，但刚打开网页时那句话里，后半句（去设置页填写自己的Key这句话）还是存在。

**Comment by Yidadaa** [comment]
提示词仅作引导作用，你可以通过修改源代码自行修改此提示词。
