### ISSUE TITLE
[Feature] 增加自定义Web访问上下文的配置功能

### ISSUE THREAD

**Issue by LLLBlue** [Yidadaa/ChatGPT-Next-Web#2745]
**这个功能与现有的问题有关吗？**
无关，属个人建议

**你想要什么功能或者有什么建议？**
您好：
我是一个个人用户，这边使用的是Docker的方式部署的该项目，并且希望将其通过Nginx代理出去，我的配置如下：
location /abc {
 proxy_pass http://chatgpt_backend_server;
...;
}
但是我发现该项目中的静态资源使用了若干以"/"开头的绝对路径，这样会导致他们的请求会直接访问到host的"/"，进而产生404。
所以我这边希望可以增加一个自定义应用访问上下文的功能，使得代理的转发配置更加灵活。

顺祝商祺。

**其他信息**
部署环境：群晖DSM 7.2

**Comment by Yidadaa** [comment]
不准备支持子路径模式，建议分配一个单独的子域名。
