### ISSUE TITLE
现在是未授权状态，请在设置页填写授权码

### ISSUE THREAD

**Issue by lit2430** [Yidadaa/ChatGPT-Next-Web#275]
![image](https://user-images.githubusercontent.com/91309604/229068792-aaa9c022-dce2-4565-9b71-c302d74bc6b7.png)
这个怎么回事？

**Comment by wupgyu** [comment]
设置了code ? 要在这里输入设置的code 才能使用.
![image](https://user-images.githubusercontent.com/17608432/229071049-3ab2c0e3-4678-4a4c-9660-66608a08641a.png)

**Comment by hujingting** [comment]
我设置了code，还是用不了

**Comment by zenghx** [comment]
> 我设置了code，还是用不了

我这里也是，填了访问码依然不行，甚至自行设置了key也提示这个

**Comment by hujingting** [comment]
我这现在可以了，可以刷新下新建个聊天窗口试试

zenghx ***@***.***> 于 2023年4月1日周六 13:08写道：

**Comment by xiangchun3** [comment]
设置了还是一直提示这个，有谁成功了吗？

**Comment by xuanxuan321** [comment]
我也是不行
