### ISSUE TITLE
[Feature] 网络搜索

### ISSUE THREAD

**Issue by catmeowjiao** [Yidadaa/ChatGPT-Next-Web#2750]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
网络搜索

**有没有可以参考的同类竞品？**
1.https://github.com/akl7777777/ShellGPT, 应该是这个项目改的
2.https://github.com/binjie09/chatgpt-web

**其他信息**
无

**Comment by Yidadaa** [comment]
#165
