### ISSUE TITLE
[Feature] Chinese input method supports.

### ISSUE THREAD

**Issue by hongyi-zhao** [Yidadaa/ChatGPT-Next-Web#2751]
I've tested the latest desktop version of this tool but found that the Chinese input method cannot be activated in its input window. The OS is as follows:

```bash
werner@X10DAi:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
Any tips for this problem will be helpful.

Regards,
Zhao

**Comment by Yidadaa** [comment]
I don't have an Ubuntu environment here, so I can't verify the issue. It is most likely a compatibility problem with Tauri. Please prioritize using the web version to ensure the best compatibility.

**Comment by hongyi-zhao** [comment]
I confirm that this issue only occurs when using the AppImage version, while the version installed with the deb package does not have this problem, as shown below:

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11155854/e2d592ec-eac0-4a7d-b121-dfca4ea31f43)
