### ISSUE TITLE
[Feature] Chats Export and Import as Backup

### ISSUE THREAD

**Issue by Algorithm5838** [Yidadaa/ChatGPT-Next-Web#2754]
**Is your feature request related to a problem? Please describe.**
I often need to backup and restore my chats. Currently, there is no built-in functionality to export and import all chats data.

**Describe the solution you'd like**
I would like to have the ability to export all chats as a backup file, which can be later imported to restore the conversations, similar to Masks. This feature would provide peace of mind and enable easy migration between instances or recovery from accidental data loss.

**Describe alternatives you've considered**
One alternative could be manually copying and pasting the chat content, but this is time-consuming and prone to errors.

**Comment by kfear1337** [comment]
Also I added this 
[[+] Added global settings & Minor improvement](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2773/commits/3ea7c77f89c04dbdb838545c835b839586919454)
so @Yidadaa how about this issue ?

**Comment by Algorithm5838** [comment]
I have provided you with my thoughts in the PR.
