### ISSUE TITLE
[Feature] 密码功能提议

### ISSUE THREAD

**Issue by OldDream666** [Yidadaa/ChatGPT-Next-Web#2756]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
CODE密码支持不同密码限制使用不同模型，例如code1，code2，code3.....
code1限制使用3.5，4.0....模型，code2限制使用4.0,,,模型，code3限制使用Claude...模型等等

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by JJTools** [comment]
建议你参考商用项目。。不要用这个。这个密码设置的最初目的是用来防止爆破的，不是用来做多用户管理的。

**Comment by OldDream666** [comment]
> 建议你参考商用项目。。不要用这个。这个密码设置的最初目的是用来防止爆破的，不是用来做多用户管理的。

主要是想把管理员和其他普通用户的权限分隔开，主要就是GPT-4的权限划分，GPT-4的费用太高了，不愿给普通用户使用，我自己用。而不是为了收费商用化
