### ISSUE TITLE
[quwation]i'm Very anxious. What if I forgot my access code? how to resolve this question.

### ISSUE THREAD

**Issue by MackDing** [Yidadaa/ChatGPT-Next-Web#2765]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
Unauthorized access, please enter access code in [auth](https://tauri.localhost/#/auth) page.

{
  "error": {
    "message": "Incorrect API key provided: sk-AvsP9*********************************HePf. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}
**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/19878893/0b7d63a4-1861-45ee-8d9f-26b3f2be75c4)

**一些必要的信息**
 - 系统：[比如 windows 10 exe
 - 版本： v2.9.3

**Comment by Yidadaa** [comment]
Your API key has expired, please check if the API key is still valid.
