### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Fyg369** [Yidadaa/ChatGPT-Next-Web#2767]
Keep the code updated. There is a problem here. According to the name of the tutorial, this step is always difficult.
![11](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/142138034/a682dcea-097c-49d6-8925-e4c02043a377)
![12](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/142138034/d2f7cded-1a76-421c-b252-9e79c923e3b3)

**Comment by Yidadaa** [comment]
key: OPENAI_API_KEY
value: sk-xxxxxx
