### ISSUE TITLE
[Bug] docker 部署后无法访问

### ISSUE THREAD

**Issue by yinbug** [Yidadaa/ChatGPT-Next-Web#2769]
docker 部署后只能用curl 127.0.0.1:3000访问，输入其他ip访问无效，nginx反向代理也无效
即使加了 --net=host 也只能用127.0.0.1 的ip访问，其他ip无效；

docker命令如下：
`
docker run -d --name chatgpt-web --restart=always -p 3000:3000 
  --net=host 
  -v /home/www/chatgpt-web/.env.production:/app/.env.production 
  -e PROXY_URL="http://127.0.0.1:7890" 
  chatgpt-next-web
`

**Comment by ivanberry** [comment]
图片有隐私信息

**Comment by rabin-HE** [comment]
这个问题解决了吗?
最近发布的v2.12.4 和 3 我部署后都有这个问题, 只能用127.0.0.1:3000, 局域网内其他的设备无法通过ip地址访问
