### ISSUE TITLE
[Bug] 相同的配置从2.9.4升级到2.9.5之后，页面badgateway

### ISSUE THREAD

**Issue by Monsterlin2018** [Yidadaa/ChatGPT-Next-Web#2775]
我使用以下命令启动项目
docker pull yidadaa/chatgpt-next-web:v2.9.5

docker run -d -p 3000:3000 -e OPENAI_API_KEY=sk-xxxx  -e CODE=1234  -e PROXY_URL=http://localhost:7890  yidadaa/chatgpt-next-web:v2.9.5

浏览器中访问 http://localhost:3000/
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/36352219/cedf083f-bd2a-4d72-8ce0-21a22d6e0030)
日志：
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/36352219/f189cf0e-8594-4b38-8a9f-001c1fea17dc)

如果将为2.9.4 便可正常访问

**Comment by Yidadaa** [comment]
请尝试删除 PROXY_URL 后重试。
