### ISSUE TITLE
[Bug] Docker从v.2.8.9升级到v2.9.5后异常，回退后正常。

### ISSUE THREAD

**Issue by hiroi-sora** [Yidadaa/ChatGPT-Next-Web#2784]
原先在docker中使用v2.8.9版。进行下列步骤更换到v2.9.5：

```
docker stop 原来容器
docker rm 原来容器
docker image rm 原来镜像
docker pull yidadaa/chatgpt-next-web:latest

docker run -d -p 3002:3000 \
   -e OPENAI_API_KEY="sk-密钥" \
   -e CODE="访问密码" \
   yidadaa/chatgpt-next-web
```

完成上述操作后，出现以下情况：

访问密码不正确或为空，请前往登录页输入正确的访问密码，或者在设置页填入你自己的 OpenAI API Key。
```json
  "error": {
    "message": "Incorrect API key provided: ak-访问密码. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
```
（值得注意的是，上述message中的“访问密码”是我设置的访问密码。即这个容器将访问密码当成了API密钥？）

同时，页面设置的版本号仍为 v2.8.9 ，而不是 v2.9.5 。

### 我尝试了以下操作：
- 不加换行和双引号，如下。问题依旧。
`docker run -d -p 3002:3000 -e OPENAI_API_KEY=sk-xxxx -e CODE=页面访问密码 yidadaa/chatgpt-next-web`
- 不设置访问密码，如下。可以正常使用了GPT，但版本号仍为 v2.8.9 。
`docker run -d -p 3002:3000 -e OPENAI_API_KEY=sk-xxxx -e yidadaa/chatgpt-next-web`
- 切换至 v2.9.4 ，问题依旧。
- 切换回 v2.8.9 ，问题解决，可以正常设置访问密码。

**Comment by Yidadaa** [comment]
2.9.5 之后，访问密码的前缀从 ak-xxx 变为了 nk-xxx，请检查。

**Comment by ccq18** [comment]
所以是怎么解决的？访问密码要加前缀？

**Comment by hiroi-sora** [comment]
> 所以是怎么解决的？访问密码要加前缀？

不是，多半是缓存的问题。升级新版本后，还使用旧版本的缓存，就会出bug。服务器将缓存文件一删就药到病除。
