### ISSUE TITLE
如何设置访问密码？

### ISSUE THREAD

**Issue by Evolution-detector** [Yidadaa/ChatGPT-Next-Web#279]
很感谢作者提供这么好的作品，用起来比官方的更便捷。

我尝试了：
1. 先部署页面，然后在【设置 - 环境变量】中增加名为 CODE 的环境变量。
2. 在首次部署前，把 OPENAI KEY 和 CODE 一同添加，然后部署。
最终打开自己部署的页面，都是一样的，没有需要输入密码的地方。

因为网址很容易暴露，我不希望陌生人使用我的页面，因而准备设置密码保护。但上述方法都没有成功，能否告知要如何操作？

**Comment by Yidadaa** [comment]
请提供打码后的 Vercel 环境变量页截图，以及部署后的应用设置页截图。

**Comment by Evolution-detector** [comment]
![image](https://user-images.githubusercontent.com/64944480/229087611-438384ae-4658-4f50-8a40-35738587a8d1.png)

**Comment by Evolution-detector** [comment]
![image](https://user-images.githubusercontent.com/64944480/229088998-8a2dbaf7-0644-4d2d-b1a9-67f37d6ca8d8.png)

**Comment by Yidadaa** [comment]
@Evolution-detector 你发一条消息就知道了。

**Comment by NBBruceeli** [comment]
为什么我已经设置了code 但是输入后还是提示访问密码不对

**Comment by Liink6868** [comment]
我也是输入密码，明明就是设置的密码，但是输入之后说是wrong access code
