### ISSUE TITLE
[Bug] windows端一直在报Failed to fetch呀

### ISSUE THREAD

**Issue by lifetin** [Yidadaa/ChatGPT-Next-Web#2790]
{
  "error": true,
  "message": "Failed to fetch"
}
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/10474968/1dc9c167-997a-4a8e-9735-942887b2a897)
有时可以,有时不行. 时好时坏.这是什么原因

**Comment by ciyjbo** [comment]
我也遇到了这个问题,可以确定和ip限制无关,因为我本地部署的另外一个gpt应用程序使用同样的apikey能正常使用

**Comment by lifetin** [comment]
是域名问题. 我在设置中把接口地址换成另外的就可以用了.

It's a domain name issue I can use it by changing the interface address to another one in the settings

**Comment by ameryzhu** [comment]
有大佬知道怎么搞吗？我也碰到了

**Comment by lifetin** [comment]
> 有大佬知道怎么搞吗？我也碰到了

原因就是他默认的这个域名可能被墙了, 或是服务器连不上了.   要换一个域名.自己布署的那种.

**Comment by Yidadaa** [comment]
1. 挂全局梯子
2. 接口地址换成 `https://chatgpt2.nextweb.fun/api/proxy`

**Comment by YeFei572** [comment]
> 1. 挂全局梯子
> 2. 接口地址换成 `https://chatgpt2.nextweb.fun/api/proxy`

有没有办法不挂全局梯子，挂全局不方便。

**Comment by tangsipeng** [comment]
> 2\. https://chatgpt2.nextweb.fun/api/proxy

如果这样的话不如直接填openai的地址就好了

**Comment by lrz0916** [comment]
我换了域名也不行，怎么办呀

**Comment by caicai000** [comment]
清除浏览器数据后重试。这个好用
