### ISSUE TITLE
补充一个提示词，可以通过markdown的链接的能力获取网络图片

### ISSUE THREAD

**Issue by ohownew** [Yidadaa/ChatGPT-Next-Web#280]
/找图片
我需要你找一张网络图片。使用Unsplash API(https://source.unsplash.com/960x640/?<英语关键词>)获取图片URL，然后请使用Markdown格式封装，并且不要有反斜线，不要用代码块。现在，请按以下描述给我发送图片：

**Comment by HenMie** [comment]
似乎作者正在开发自定义prompts了，这个功能开发出来后自定义就可以了

**Comment by Cp0204** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/138

**Comment by Yidadaa** [comment]
可以补充到：https://github.com/PlexPt/awesome-chatgpt-prompts-zh

之后会自动同步到本项目。
