### ISSUE TITLE
[Feature] New browser tab should open a new chat.

### ISSUE THREAD

**Issue by JKamsker** [Yidadaa/ChatGPT-Next-Web#2802]
**Is your feature request related to a problem? Please describe.**
When you start a new tab (and then navigate to chatgpt.nextweb.fun of course), the app should begin a new chat, not show the old one. This is what users usually expect. The current way can be quite a bit confusing to some people.

**Comment by kfear1337** [comment]
you mean start a new tab in browser not a chat ?

**Comment by Yidadaa** [comment]
You should consider it as an app rather than a webpage. Please use the built-in sidebar in the app to manage multiple sessions.
