### ISSUE TITLE
演示的demo大家能访问吗？

### ISSUE THREAD

**Issue by myysophia** [Yidadaa/ChatGPT-Next-Web#281]
演示的demo大家能访问吗？
自己搭建的也无法访问
看状态也是ready的
![image](https://user-images.githubusercontent.com/25994521/229090104-15b79988-18a2-4cd4-a23b-41c0dc94d43e.png)

**Comment by hugoyue** [comment]
演示地址可在墙内访问是 https://chat.simplenaive.cn/ 这个，自部署你需要用你自己的域名，自动生成的vercel地址已被污染。
