### ISSUE TITLE
[Bug] 接口地址填写IP格式报错

### ISSUE THREAD

**Issue by yuexiaoliang** [Yidadaa/ChatGPT-Next-Web#2810]
接口地址填写 `http://xx.xx.xx.xx:3870/` 这种格式后报错 `{"error": true,"message": "Failed to fetch"}`，用抓包工具看了一下，也没发请求。

**Comment by Alsohao** [comment]
同样的问题,如何解决啊?

**Comment by xupeng19881010** [comment]
bug, 未发送请求

**Comment by TlgYuri** [comment]
我也遇到这个问题了，填http://ip:xxxx会failed，但是改成http://127.0.0.1:xxxx就能正常请求

**Comment by wjfu99** [comment]
同样遇到了这个问题
