### ISSUE TITLE
Plesae fix portreat orientation[Bug] 

### ISSUE THREAD

**Issue by almaziphone** [Yidadaa/ChatGPT-Next-Web#2812]
![portreat](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/38611294/3f955649-6afd-4509-90f4-65a1966aa5ed)

**Comment by Yidadaa** [comment]
移动端横屏操作不在考虑范围之内，请尝试下列做法：
- 调整页面缩放比例到 80% 或更低
- 使用竖屏模式
