### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by FreeVonn** [Yidadaa/ChatGPT-Next-Web#2815]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果我想给多个人使用并设置了不同的CODE，不同的CODE能否看到其他人的聊天记录呢？

**Comment by Yidadaa** [comment]
不能。
