### ISSUE TITLE
[Bug]  Landscape orientation

### ISSUE THREAD

**Issue by almaziphone** [Yidadaa/ChatGPT-Next-Web#2817]
Problems with iOS landscape orientation on mobile devices
![Screenshot_2](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/38611294/986b7b77-29da-49e8-9113-a569dc9b2bbe)

**Comment by kfear1337** [comment]
fixed
![Screenshot_143](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/c029fe66-e09e-4e22-89b7-c2a0fcdb9669)

**Comment by kfear1337** [comment]
tested on real mobile device : 

![mm](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48602426/b76d374f-e61d-4a49-ab2a-375254869ee3)

can scroll up/down looks like desktop
