### ISSUE TITLE
响应数据被截断怎么解决，没法一次性全部返回吗 

### ISSUE THREAD

**Issue by dothin** [Yidadaa/ChatGPT-Next-Web#282]
比如：需要一次性返回完整的代码结构

**Comment by Yidadaa** [comment]
全部返回会超出 vercel edge function 运行时间，vercel 限制了 10s 的最大运行时间。

**Comment by qingweiSun** [comment]
确实是，要么升级vercel.要么换后台，我是用astro写了api也可以部署在vercel.他就没有10s的限制
