### ISSUE TITLE
[Bug] WebDAV Cloud Sync return 520 status code / WebDAV 不可用

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#2820]
After deploying WebDAV cors to Vercel, a 520 error code occurs, which prevents normal usage. The specific reason needs further investigation.

**Comment by H0llyW00dzZ** [comment]
this might server issue I think not from a client-side
if on vercel try use region singapore
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/6a5e2b25-973f-45b4-8d39-0e1cc1d174f5)

**Comment by Clarkkkk** [comment]
Change the runtime from 'edge' to 'nodejs' works for me. Still weird though.

**Comment by Yidadaa** [comment]
Seems like a vercel's bug, still working on it.

**Comment by H0llyW00dzZ** [comment]
other issue I've been tryna fix in my pull req
its so bad webdav unlike github gist
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/7edfc33d-eb23-4f0c-9fc6-3e3fdac9c8d2)

**Comment by daiaji** [comment]
cloudflare上部署也一样，我用坚果云。
