### ISSUE TITLE
[Bug] WebDav sync creates a 0-byte backup.json

### ISSUE THREAD

**Issue by Philantrop** [Yidadaa/ChatGPT-Next-Web#2823]
The new WebDav functionality only ever creates a 0-byte backup.json in the target location which resides on a [Nextcloud Hub 5 (27.0.2).

**To Reproduce**
1. Configure WebDAV
2. Click on the (untranslated, "examine"?) left button and confirm.
3. Click sync 
4. ChatGPT-NExt-Web reports success but the backup.json is empty

**Expected behavior**
Both pre-existing data as well as data created after the initial sync is successfully transferred.

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 116.0.5845.179

**Comment by Yidadaa** [comment]
Can you attach your console log?

**Comment by H0llyW00dzZ** [comment]
fixed in #2854

**Comment by Philantrop** [comment]
Sorry for the late reply: There's only this one line:

`Sep 18 06:34:43 turing.mailstation.de chatgpt-next-web[1477523]: [Any Proxy] https://nextcloud.mailstation.de/remote.php/dav/files/xxx/chatgpt-next-web/backup.json`

**Comment by Yidadaa** [comment]
Attempted fixed, please re-validate

You can also try using the new synchronization feature based on Upstash Redis:

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/62809ca5-f8cc-4f85-9f1f-06eee783a0cb)

**Comment by Philantrop** [comment]
The fix hasn't made it to the Docker image yet, it seems. (An external provider is not an option.)

**Comment by Yidadaa** [comment]
v2.9.7 docker image will be released soon (30 mins after this message).

**Comment by Philantrop** [comment]
Sadly, it still generates an empty file:

```
Sep 19 06:41:37 turing.mailstation.de chatgpt-next-web[2126691]: [Any Proxy] https://nextcloud.mailstation.de/remote.php/dav/files/xxx/chatgpt-next-web/backup.json { status: 200, statusText: 'OK' }
Sep 19 06:41:37 turing.mailstation.de chatgpt-next-web[2126691]: [Any Proxy] https://nextcloud.mailstation.de/remote.php/dav/files/xxx/chatgpt-next-web/backup.json { status: 204, statusText: 'No Content' }
```

**Comment by Philantrop** [comment]
Any news about this? And maybe reopen it since it's not fixed?

**Comment by Philantrop** [comment]
Still broken: { status: 204, statusText: 'No Content' }
