### ISSUE TITLE
[Feature] 获取用户微调模型

### ISSUE THREAD

**Issue by Microwave-WYB** [Yidadaa/ChatGPT-Next-Web#2824]
**你想要什么功能或者有什么建议？**
通过API获取可用的模型列表以获得用户微调的模型

**有没有可以参考的同类竞品？**
[ChuanhuChatGPT](https://github.com/GaiZhenbiao/ChuanhuChatGPT) 已经实现了类似功能，可以调用微调API进行训练，并获取微调模型

**Comment by Yidadaa** [comment]
请使用自定义模型名手动添加微调模型名。
