### ISSUE TITLE
[Feature] Single Chat Export and Import

### ISSUE THREAD

**Issue by SnowCharmQ** [Yidadaa/ChatGPT-Next-Web#2827]
**Is your feature request related to a problem? Please describe.**
I tried out the new sync function in **2.9.6** and found it to be excellent. But the function can only store all conversations now, which will be troublesome when I only want to back up a single conversation from a large number of conversations.

**Describe the solution you'd like**
I recommend adding a sync function for a single conversation to save a JSON file as the overall sync function acts now.

**Comment by H0llyW00dzZ** [comment]
I've been add this before but my github got temporary suspended

**Comment by H0llyW00dzZ** [comment]
how about this ?
UI Page Load & Save [Chat Commands] #2955

**Comment by Yidadaa** [comment]
#3006
