### ISSUE TITLE
[Bug] 坚果云的webdav不可用

### ISSUE THREAD

**Issue by snoopytl** [Yidadaa/ChatGPT-Next-Web#2831]
坚果云的webdav，已经正常配置，但测试连接连接不上，开不开代理都无法连接上
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/29892766/bb57dce0-292c-4c09-af6f-ad1bd900f5be)

**Comment by TS1989ED** [comment]
同样的问题

**Comment by Yidadaa** [comment]
已知问题，请关注 #2820

**Comment by dadaoerv** [comment]
刚刚设置了，没有任何问题。我的项目在海外服务器。

**Comment by snoopytl** [comment]
> 刚刚设置了，没有任何问题。我的项目在海外服务器。

你用的哪家的webdav，能否把截图共享一下看看

**Comment by dadaoerv** [comment]
坚果啊，这个问题不就是坚果吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月15日 18:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Yidadaa/ChatGPT-Next-Web] [Bug] 坚果云的webdav不可用 (Issue #2831) |

刚刚设置了，没有任何问题。我的项目在海外服务器。

你用的哪家的webdav，能否把截图共享一下看看

**Comment by snoopytl** [comment]
> 坚果啊，这个问题不就是坚果吗
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年09月15日 18:21 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [Yidadaa/ChatGPT-Next-Web] [Bug] 坚果云的webdav不可用 (Issue #2831) | 刚刚设置了，没有任何问题。我的项目在海外服务器。 你用的哪家的webdav，能否把截图共享一下看看 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我也是啊，就是按照坚果云提供的信息，填进去，不管开不开代理都无法联通，你是开代理还是不开代理

**Comment by myriad2** [comment]
webdav地址直接用 https://dav.jianguoyun.com/dav/ 不行，要在根目录新建一个文件夹，比如 chatgpt_next_web，填入https://dav.jianguoyun.com/dav/chatgpt_next_web
不需要启用代理

**Comment by maboloshi** [comment]
> webdav地址直接用 https://dav.jianguoyun.com/dav/ 不行，要在根目录新建一个文件夹，比如 chatgpt_next_web，填入https://dav.jianguoyun.com/dav/chatgpt_next_web 不需要启用代理

我这边无效🤣

**Comment by Etleventt** [comment]
我run docker的时候的代理给关掉就可以了，不关不行
