### ISSUE TITLE
[Feature] 请考虑为Markdown添加TikZ支持，以便于渲染图形和数学函数图像

### ISSUE THREAD

**Issue by Dx-hualuo** [Yidadaa/ChatGPT-Next-Web#2833]
**这个功能与现有的问题有关吗？**
现在程序内的Markdown可以渲染LaTeX数学公式和Mermaid流程图，但想让GPT可以使用更丰富的方式展示内容，GPT可以支持回答对应语法的内容（TikZ），但程序缺少渲染方式

**你想要什么功能或者有什么建议？**
请添加TikZ语法支持，使GPT回答的数学图像等更丰富的图形内容可以展示

**有没有可以参考的同类竞品？**
[知乎TikZ简介](https://zhuanlan.zhihu.com/p/48300815)

**其他信息**
支持PGFPlots，渲染2D/3D函数图

**Comment by Yidadaa** [comment]
TikZ 是一个体积不小的二进制程序，目前有人将他导出为了 wasm，来让它在浏览器里执行，但是增加此依赖库会增加 ~2MB 的额外体积，会显著拖慢加载速度，考虑到这是一个小众需求，所以并不准备引入此依赖库。

ref: https://github.com/kisonecat/tikzjax

**Comment by Dx-hualuo** [comment]
@Yidadaa 可以考虑使用插件导入吗
