### ISSUE TITLE
[Bug] Each keystroke would cause a new Emoji fetched

### ISSUE THREAD

**Issue by a6z6** [Yidadaa/ChatGPT-Next-Web#2838]
**Describe the bug**
Chrome's DevTools, as I am typing, each keystroke would cause a new GET request to `https://cdn.staticfile.org/emoji-datasource-apple/14.0.0/img/apple/64/1f603.png`

Since I am not familiar with every detail of this super repo, anyone would like to tell me where the problem is, I'd like to create a PR.

**To Reproduce**
1. `yarn install && yarn dev`
2. Setup API key
3. Typing message talking to ChatGPT
4. In Chrome DevTools

**Expected behavior**
Should not fetch one emoji after each keystroke.

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/132665015/cc1613f0-c0ca-4777-90e2-daf861e55302)

**Deployment**
N/A

**Desktop (please complete the following information):**
 - Chrome

**Smartphone (please complete the following information):**
N/A

**Additional Logs**
N/A

**Comment by Yidadaa** [comment]
Should `React.memo` this:

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/e03db9c2d53cbc2aa2b9ea344b13c933e871659a/app/components/emoji.tsx#L51

**Comment by a6z6** [comment]
@Yidadaa, Thank you for pointing out this line. But I tried to change it to:

```js
export const EmojiAvatar = React.memo(function EmojiAvatar(props: { avatar: string; size?: number }) {
  return (
    <Emoji
      unified={props.avatar}
      size={props.size ?? 18}
      getEmojiUrl={getEmojiUrl}
    />
  );
});
```
then run `yarn dev`, the problem still exists

**Comment by H0llyW00dzZ** [comment]
I fixed this already
if anyone wanted I can open pull request

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/a418a6c3-a108-43e2-9192-449c4f0143d8)


only first time like this then it will caching

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/73a6763f-4989-4c19-9e23-e5e51e0b01b7)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/73c118e3-0e77-44ae-a8a7-831c241b0b70)

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/3de1c0c1-15a1-4dcc-8a54-f769c5ec289e)

Do not disable cache.
