### ISSUE TITLE
[Feature] 手机上无法调整侧边栏的大小

### ISSUE THREAD

**Issue by Aincvy** [Yidadaa/ChatGPT-Next-Web#2848]
**Is your feature request related to a problem? Please describe.**
手机上无法调整侧边栏的大小

**Describe the solution you'd like**
- 按住 中间几个点左右拖动 调节侧边栏大小
- 或者在设置里面切换

**Comment by Yidadaa** [comment]
现在可以通过点击手柄来切换侧边栏了。
