### ISSUE TITLE
[Bug] 云同步不勾选“启用代理”依然使用了代理

### ISSUE THREAD

**Issue by zengbo** [Yidadaa/ChatGPT-Next-Web#2855]
配置云同步里面，取消 “启用代理” 的勾选，请求的时候依然请求了代理的地址，我是使用静态页面的方式部署的，就没有代理功能，请求的时候报 405 错误

**Comment by Yidadaa** [comment]
你必须要使用代理，webdav 默认禁止了跨域，代理的作用就是为了解除这个限制，否则你用不了这个功能。

**Comment by zengbo** [comment]
> 你必须要使用代理，webdav 默认禁止了跨域，代理的作用就是为了解除这个限制，否则你用不了这个功能。

我用的自建的 Alist 提供的 webdav 功能，是开启跨域了的。我自己修改了一下代码，直接使用 webdav 的 endpoint 请求，是成功的。
