### ISSUE TITLE
希望增加arm版本的docker镜像

### ISSUE THREAD

**Issue by ouyanglong721** [Yidadaa/ChatGPT-Next-Web#286]
希望增加arm版本的docker镜像

**Comment by hugoyue** [comment]
1.7.2 的版本支持 arm，拉取镜像的时候 tag 标记一下
```
docker pull yidadaa/chatgpt-next-web:1.7.2
````
最新的需要自己 build 

![iShot_2023-03-31_20 42 05](https://user-images.githubusercontent.com/36737373/229122980-cda5bdc7-8f8c-4fea-9a38-f0be7a0254e9.jpg)

**Comment by Yidadaa** [comment]
arm docker 镜像没有找到比较好的部署方法，之前太慢了，全部编译部署要花 30min，所以暂时去掉了

**Comment by ouyanglong721** [comment]
ok了解了
