### ISSUE TITLE
[Feature] 请求接入GPT-3.5-Turbo-Instruct模型

### ISSUE THREAD

**Issue by lainbo** [Yidadaa/ChatGPT-Next-Web#2870]
**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
希望可以在模型选项中新增`gpt-3.5-turbo-instruct`，这是Open AI近期新推出的模型，详见[官方介绍](https://openai.com/research/instruction-following)

**有没有可以参考的同类竞品？**
无

**其他信息**
无

**Comment by H0llyW00dzZ** [comment]
not really good as 16k models
was trying already in the morning

**Comment by Yidadaa** [comment]
非聊天模型，不适用于聊天场景。
