### ISSUE TITLE
[Bug] 插件可以使用了吗？本地部署还是一直提示正在开发中

### ISSUE THREAD

**Issue by Joackk** [Yidadaa/ChatGPT-Next-Web#2871]
**一些必要的信息**
 - 系统：[linux]
 - 浏览器： [chrome]
 - 版本： [2.9.7]
 - 部署方式：[docker]
使用的docker部署的，拉的2.9.7的版本，检查更新也没有更新的了，之前遇到一个别人部署的next-web已经把插件装里了，试了下自己部署的，点插件提示还在开发中，是还需要什么配置吗？

**Comment by Yidadaa** [comment]
没有开发，那是别人的版本。
