### ISSUE TITLE
[Bug] Docker部署添加多个密码时，密码不能出现标点符号，不然会识别为没有设置密码

### ISSUE THREAD

**Issue by hubeibei** [Yidadaa/ChatGPT-Next-Web#2875]
比如使用 ! . 中间用英文,隔开，但部署后发现密码为空了

**Comment by Yidadaa** [comment]
英文逗号是分隔符，用来切割密码的

**Comment by hubeibei** [comment]
我明白，比如我环境变量设置的三个密码是：abc.123,abc.456,abc.789 或者 abc!123,abc!456,abc!789
部署后密码都是空的，也就是不需要密码，去掉密码中的特殊字符，只使用字母和数字就没问题
