### ISSUE TITLE
[Bug] "Regenerate" Button Reorders Messages

### ISSUE THREAD

**Issue by Algorithm5838** [Yidadaa/ChatGPT-Next-Web#2879]
**Describe the bug**
When clicking "regenerate" on either the user or bot previous messages, if there were following messages, those messages become the latest ones. This behavior is not intuitive and can lead to confusion and loss of context in the conversation.

**To Reproduce**
1. Click on 'regenerate' for any user or bot message that has following messages.
2. Observe that the following messages become the latest messages.

**Expected behavior**
The expected behavior could be one of the following two options:
1. An acceptable solution: Clicking regenerate, while there are messages following the message that the user wants to be regenerated, should warn the user that following messages would be cleared, and they should confirm or cancel.
2. A better solution: Clicking regenerate, while there are messages following the message that the user wants to be regenerated, should let the user choose between three options:
    - "Clear and Regenerate" which would clear the following messages and regenerate the message.
    - "Regenerate Message" which would only regenerate the message and keeps every other message in order. Note: the following messages should not be sent through the API.
    - "Cancel" which aborts the regeneration process and keeps the existing messages unchanged.

**Screenshots**
Before clicking regenerate:
![Screenshot 2023-09-20 at 14 42 09](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/108630393/a38f2359-a18f-4f29-b8b1-7ab82a692df8)

After clicking regenerate:
![Screenshot 2023-09-20 at 14 42 56](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/108630393/65a397ce-5985-4614-a97b-ff89ab0213ad)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by Yidadaa** [comment]
This is not a bug, this is by design.

**Comment by Algorithm5838** [comment]
Thank you for explaining the current behavior. Could you please provide more insight into the reasoning behind this design decision? This will help me understand the intended functionality and provide any feedback or suggestions accordingly.

**Comment by Algorithm5838** [comment]
I have implemented the first solution in my fork. Feel free to check it out if you are interested.

**Comment by Yidadaa** [comment]
I am going to release a big refactor of the project, which will introduce multi-models support (azure, claude, etc.), this behavior will be refactor too.f
