### ISSUE TITLE
[Feature] Differentiating System Messages with a Unique Avatar

### ISSUE THREAD

**Issue by Algorithm5838** [Yidadaa/ChatGPT-Next-Web#2880]
**Is your feature request related to a problem? Please describe.**
No, the avatar for the system messages is the same as the avatar for the "assistant".

**Describe the solution you'd like**
I would suggest using a different avatar, such as the gear emoji ⚙️, for system messages. This would make it easier to distinguish between "system" messages and "assistant" messages.

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/23eb7732d7011ce9476ab6309c92509e094fca81/app/components/chat.tsx#L1155C25-L1155C25

**Comment by H0llyW00dzZ** [comment]
@Yidadaa Thanks for pointing out the code snippet. This requested feature is really beneficial.

**Comment by H0llyW00dzZ** [comment]
@Algorithm5838 code snippet
```tsx
</div>
{isUser ? (
<Avatar avatar={config.avatar} />
 ) : isContext ? (
<Avatar avatar="2699-fe0f" /> // Add this line for system messages
) : (
<MaskAvatar mask={session.mask} />
)}
</div>
```

**Comment by Algorithm5838** [comment]
Thank you, both.
@H0llyW00dzZ, I tried it and it works, but only for contextual prompts. It does not work on prompts added through "Edit All Messages".
___
Additionally, something I have noticed, although it is not a priority for me, is that when exporting a single chat and selecting either text or image, there is no differentiation between the messages from the "system" and those from the "assistant".
Furthermore, if you choose JSON as the export format, you will encounter the following at the beginning:
```
"role":"system",
"content":"You are an assistant that New Conversation"
```
Even though I didn't write this system message, and "New Conversation" is the title of the chat. This means that if it generated a title, you would see this, for example:
```
"role":"system",
"content":"You are an assistant that Ideas for a picknic"
```
I believe these two might be related, but I think they should be reported as separate issues.

**Comment by Yidadaa** [comment]
@Algorithm5838 It's a bug, i will fix it.

**Comment by Algorithm5838** [comment]
Got the original feature working, check the PR.

**Comment by H0llyW00dzZ** [comment]
@Algorithm5838 check my fork I made something cool from your refrence
[UI Page [Chat] [Contributor] #13](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/pull/13)

**Comment by Algorithm5838** [comment]
@H0llyW00dzZ I gave it a try, and it worked exactly as intended.
