### ISSUE TITLE
[Bug] 'export' button does not work

### ISSUE THREAD

**Issue by Pear-sudo** [Yidadaa/ChatGPT-Next-Web#2884]
**Describe the bug**
'export' button does not have any effect.

**To Reproduce**
1. Go to 'settings'
2. Click on 'export'

**Expected behavior**
It should prompt the user to choose a location to save the file.

**Desktop (please complete the following information):**
 - OS: [macOS Ventura]
 - Version [v2.9.7]
 - ( ChatGPT.Next.Web_2.9.7_x64.dmg )

**Comment by H0llyW00dzZ** [comment]
might this bug issue its because of `filename`
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/23eb7732d7011ce9476ab6309c92509e094fca81/app/utils.ts#L34
this is wrong
```ts
export function downloadAs(text: string, filename: string) {
  const element = document.createElement("a");
  element.setAttribute(
    "href",
    "data:text/plain;charset=utf-8," + encodeURIComponent(text),
  );
  element.setAttribute("download", filename);

  element.style.display = "none";
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}
```

**Comment by Yidadaa** [comment]
should refactor `downloadAs` to https://tauri.app/v1/api/js/fs/#writebinaryfile

**Comment by H0llyW00dzZ** [comment]
@Yidadaa what how its json btw you mean refactor by adding parameter ?
also object its already enought for json

**Comment by Yashh221** [comment]
is this issue opened ? Can i work on it? @Pear-sudo

**Comment by Yidadaa** [comment]
@Yashh221 

Sure, you can refactor `downloadAs` with tauri api, just like this:

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/23eb7732d7011ce9476ab6309c92509e094fca81/app/utils.ts#L9-L17

**Comment by H0llyW00dzZ** [comment]
this issue must be add package for tauri I think
because the default there is no package for tauri
only default `window.__TAURI__`

**Comment by H0llyW00dzZ** [comment]
@Yidadaa not only that
this one aswell
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/23eb7732d7011ce9476ab6309c92509e094fca81/app/global.d.ts#L13C1-L14C1
example :
```ts
declare module "*.jpg";
declare module "*.png";
declare module "*.woff2";
declare module "*.woff";
declare module "*.ttf";
declare module "*.scss" {
  const content: Record<string, string>;
  export default content;
}

declare module "*.svg";

declare interface Window {
  __TAURI__?: {
    [x: string]: any; // customize tauri-api
    writeText(text: string): Promise<void>;
  };
}
```

**Comment by H0llyW00dzZ** [comment]
let's continue this issue
@Yidadaa 
invoke / writebinary file not possible

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/55462e31-651b-487a-a78f-a2c5c5aea22c)

**Comment by H0llyW00dzZ** [comment]
> **Note**
  > This issue has been fixed on my fork's

https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/commit/2e948b4920833536394c3f2f4a6f67cbfc86524f
