### ISSUE TITLE
部署在 vercel，是否每一次聊天请求都会经过 vercel 服务器？

### ISSUE THREAD

**Issue by jaydong2016** [Yidadaa/ChatGPT-Next-Web#2885]
纯小白问题，我是部署在 vercel，变量填写有 key 和 api 代理接口地址， 我在国内是否每一次聊天请求都还要经过 vercel 服务器再请求到接口地址再到 OpenAI ？
能不能就像本地客户端一样使用呢？

**Comment by qiudcs** [comment]
有桌面版

**Comment by jaydong2016** [comment]
我要给多人使用的，桌面版要下载还要每个人自己填入 api，很麻烦

**Comment by Yidadaa** [comment]
设置里面的接口地址控制了请求是否经过 vercel 转发，只要值为空或者 `/api/openai` 的时候才会由服务器转发。
