### ISSUE TITLE
【bug】界面代码无高亮显示

### ISSUE THREAD

**Issue by substitute5** [Yidadaa/ChatGPT-Next-Web#289]
拷贝回答内容至*.md文件中，可以看到，代码区域是明确了编程语言的，但界面的代码没有高亮显示。
![image](https://user-images.githubusercontent.com/56405486/229127151-f2bf7e5e-a625-4fb8-8d63-7bc4b2da991b.png)

**Comment by Yidadaa** [comment]
用的 markdown 插件比较蠢，只能识别 cpp 标识，设置为 c++ 就不认识了

**Comment by substitute5** [comment]
额 接口返回的数据应该就是带了`c++`字样的，那看起来短时间内还无法解决这个bug哇？交互查看代码时，影响挺大的。

**Comment by yanglyu902** [comment]
可不可以每次用regex之类的把返回的"\`\`\`c++"转成"\`\`\`cpp"？
