### ISSUE TITLE
[Feature] 清空聊天记录建议加个弹窗，目前不小心点到聊天记录就全没了

### ISSUE THREAD

**Issue by tyzero** [Yidadaa/ChatGPT-Next-Web#2891]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

 
清空聊天记录建议加个弹窗，目前不小心点到聊天记录就全没了

500多条聊历史聊天，不小心点到，清空了。（有没有办法恢复，求告知）

**Comment by Yidadaa** [comment]
无法恢复，除非有云备份。
