### ISSUE TITLE
[Bug] 一些第三方的gpt无法使用被提示：Failed to fetch

### ISSUE THREAD

**Issue by Joackk** [Yidadaa/ChatGPT-Next-Web#2893]
**描述问题**
在我使用naga和wave的api时得到了Failed to fetch错误，但是我在其他程序中是可以正常使用他们的，版本为2.9.7

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45162558/ee98ebeb-4af0-45ee-b99f-ad6a1c456a5c)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/45162558/4f726118-8e34-4bbf-a1c8-2d7f58aa5ad2)

**Comment by jaydong2016** [comment]
确实我也遇到类似问题

**Comment by Yidadaa** [comment]
不要加 v1 后缀

**Comment by Joackk** [comment]
> 不要加 v1 后缀

大佬nb，感谢

**Comment by HumanMus1c** [comment]
> 不要加 v1 后缀

可以把这个写进文档嘛
