### ISSUE TITLE
[Feature] Make the mask selection more streamlined

### ISSUE THREAD

**Issue by debitCredit** [Yidadaa/ChatGPT-Next-Web#2895]
**Is your feature request related to a problem? Please describe.**
Selecting the correct mask is not streamlined and requires too many clicks. The default Mask page displays repeated buttons for the same masks and only limited number of characters from the name. For the masks that share the same beginning it's not possible to select the correct one from this screen.

**Describe the solution you'd like**
Add a feature to for the user to go directly to the "Prompt Template" page when clicking on the "Mask" button on the main page instead of having to click on "Find More" first.

**Describe alternatives you've considered**

**Additional context**

**Comment by H0llyW00dzZ** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blame/23eb7732d7011ce9476ab6309c92509e094fca81/app/components/sidebar.tsx#L160
replace with this :
```tsx
        <IconButton
          icon={<MaskIcon />}
          text={shouldNarrow ? undefined : Locale.Mask.Name}
          className={styles["sidebar-bar-button"]}
          onClick={() => {
            if (config.dontShowMaskSplashScreen !== true) {
              navigate(Path.NewChat, { state: { fromHome: true } });
            } else {
              navigate(Path.Masks, { state: { fromHome: true } });
            }
          }}
          shadow
        />
 ```

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2905
