### ISSUE TITLE
[Feature] Android app

### ISSUE THREAD

**Issue by oifj34f34f** [Yidadaa/ChatGPT-Next-Web#2896]
This could be an alternative to the proprietary [ChatGPT app](https://play.google.com/store/apps/details?id=com.openai.chatgpt), which [doesn't work](https://www.toscl.com/chatgpt_android/#%E5%BC%BA%E7%BB%91%E5%AE%9Agoogle-play) on devices without Google Play and/or in [certain](https://help.openai.com/en/articles/7947663-chatgpt-supported-countries) countries. We can use a webview wrapper (as on desktop).

I know ChatGPT Next Web works in the browser, but having an app with its own icon would be better.

**Comment by Yidadaa** [comment]
Just use PWA on your Android/IOS phone, try to use 'send to desktop' button in your mobile's browser.
