### ISSUE TITLE
为何最近几次聊天回复,都是一次性把所有回答抛出来.

### ISSUE THREAD

**Issue by hceasy** [Yidadaa/ChatGPT-Next-Web#290]
之前我记得是一句一句的说出来的,现在变成把所有答案组装完整之后,一次性吐回来.
这个跟我哪项设置有关?cloudflaer?还是模型选择?SSL加密?

**Comment by hceasy** [comment]
测试了一下,nginx代理之后就会出现这个问题.

**Comment by GOWxx** [comment]
[#209 docker部署的版本，用ngnix走https后GPT不会逐字回答](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/209)

**Comment by hceasy** [comment]
![图片](https://user-images.githubusercontent.com/4436382/229136229-7a88a801-6e32-417e-8fd2-d94ab1a5bac6.png)
nginx启用了压缩...
