### ISSUE TITLE
[Feature] Cloud backup adds Redis connectivity to the local environment

### ISSUE THREAD

**Issue by cfwl1111** [Yidadaa/ChatGPT-Next-Web#2909]
Do you have any plans to synchronize external Redis connections? For example, I have deployed ChatGPT-Next-Web on the docker and hope to connect to my own Redis environment or external Redis servers

**Comment by H0llyW00dzZ** [comment]
I'll try

**Comment by H0llyW00dzZ** [comment]
Cloudsync redist #2929
only package need to fix it
