### ISSUE TITLE
功能建议：回复的模型类型显示。Feature: Show the model type of the reply

### ISSUE THREAD

**Issue by HenMie** [Yidadaa/ChatGPT-Next-Web#291]
有时候会根据实际需要切换模型，加上模型显示的功能可以更清晰地知道该回答是用哪个模型生成的。
可参考样式如图，在回复框下面加上模型类型的显示。
Sometimes the model needs to be switched according to actual needs. Adding the display of the model can make it clearer which model generated the answer. 
You can refer to the style in the picture.

![image.png](https://s2.loli.net/2023/03/31/V9CZzrxEW25Rpql.png)

**Comment by AprilNEA** [comment]
是否也可以加上本次消耗的 Token ?

**Comment by yanglyu902** [comment]
+1，不过显示token可不可以作为可选项，不然容易token焦虑：）

**Comment by tuliren** [comment]
已在这个 PR 中实现了此功能：#379
