### ISSUE TITLE
[Bug] 使用upstash同步后，出现以下问题

### ISSUE THREAD

**Issue by blue6659** [Yidadaa/ChatGPT-Next-Web#2910]
使用upstash同步后，出现以下问题：
1、发送按钮自动变成enter键，但在输入聊天内容的时候，Enter键还是换行的作用！！！
2、默认gpt选择变成gpt-3.5-turo，会覆盖已选择使用模型：gpt4.0-0613。
3、左边聊天框自动会乱序

**Comment by Yidadaa** [comment]
同步功能仅用户聊天记录同步，设置会混乱，关注 https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2892
