### ISSUE TITLE
[Bug] chatglm_pro附带历史消息数为奇数的时候，到达轮数，报[1214][prompt参数非法。请检查文档。]

### ISSUE THREAD

**Issue by qingju32** [Yidadaa/ChatGPT-Next-Web#2916]
**Describe the bug**
选择chatglm_pro模型，使用oneapi部署的
附带历史消息数为奇数的时候，到达轮数，报[1214][prompt参数非法。请检查文档。]
比如历史消息数设置为3，到达第三轮就报错

另外一个问题EXE版本的图标和快捷方式上有黑影，建议换一个
启动时会在桌面跳来跳去，没有记忆位置？
[ico.zip](https://github.com/Yidadaa/ChatGPT-Next-Web/files/12734200/a0f42-ynp8q-001.zip)

**Expected behavior**
可以继续对话

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/40858189/bf148a5d-e97f-40e9-97da-89609c081fd7)

**Deployment**
- [+] Docker
- [+] Vercel

**Desktop:**
 - OS: [Windows]
 - Browser [Chrome, Edge]

**Comment by Yidadaa** [comment]
请附上服务端 log，否则无法排查。
