### ISSUE TITLE
我的3000端口已被占用，请问如何修改此项目的端口？[Bug] 

### ISSUE THREAD

**Issue by yufengqinli** [Yidadaa/ChatGPT-Next-Web#2920]
我的3000端口已被占用，在布置此项目过程中，已将3000改为其他端口，但运行时发现日志中此项目还是运行在3000端口上，请问如何正确修改端口？

**Comment by 2284730142** [comment]
参考next配置
` scripts: {
    "dev": "PORT=10000 next dev"
  }`

**Comment by happly-plane** [comment]
我都试了，为什么还是不可以呢包括使用-p 3002
