### ISSUE TITLE
[Feature] Toggle/swifth between GPT4 and GPT3.5

### ISSUE THREAD

**Issue by arndeash** [Yidadaa/ChatGPT-Next-Web#2926]
Lot of people juggle between GPT3.5 and GPT4 multiple times during a day. Different questions, require different models. A simple toggle on the top would solve it. 
<img width="439" alt="Screenshot 2023-09-28 at 13 28 42" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/919360/ac9802fb-03d6-4c92-93b1-0f12bc210a2b">

**Comment by aaxyat** [comment]
What about this? 
![toggle](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/108934987/0df4bb24-5f88-4d99-9788-46eb859eb30a)

**Comment by arndeash** [comment]
I just like a big one click toggle on the top better.

**Comment by Yidadaa** [comment]
Just use the bot icon.
