### ISSUE TITLE
[Feature] Hide or delete prompt templates in #/masks link

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2930]
![SNAG-0020](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/d25161d8-8554-4732-9f7c-d25109773852)

how can hide or delete all prompts?

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/85320660-7495-430e-b072-c9048000f6c2)
