### ISSUE TITLE
[Feature] share public link with a prompt or mask

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2931]
a good feature is share a public link with a chat or mask or template, because all prompt configured can we used by other if i share code for login into page

**Comment by Yidadaa** [comment]
Mask:

Masks -> Edit Mask -> Share This Mask

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/e908f2bc-61ae-40b0-abd5-746b6406d6ee)

**Comment by Yidadaa** [comment]
Prompts:

https://chatgpt.nextweb.fun/#/chat?fill=sometexthere

**Comment by H0llyW00dzZ** [comment]
wait what I don't know this worked
`https://chatgpt.nextweb.fun/#/chat?fill=sometexthere`
`https://chatgpt.nextweb.fun/#/chat?submit=sometexthere`
might gonna used as ref for a feature about `sharing chat id`

**Comment by johnfelipe** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/ab11dea1-e240-436b-b360-0d64bec7facb

not working

https://chat-gpt-next-web-1-1l5v29k4k-johnfelipe.vercel.app/#/new-chat?mask=NW54zCE62cbuPV1AU58aT

havent prompts

**Comment by johnfelipe** [comment]
Is normal that behavior?
Not share prompts in mask sharing?
