### ISSUE TITLE
Checkout this out if you are looking for a different APP😘

### ISSUE THREAD

**Issue by proxfly** [Yidadaa/ChatGPT-Next-Web#2932]
Hello everyone! 😇

Introducing our project, [Talk](https://github.com/proxoar/talk)—an app that shares similarities with ChatGPT-Next-Web. With [Talk](https://github.com/proxoar/talk), you can engage in voice-based conversations with ChatGPT. The app is built with a refreshing user interface and allows you to customize the parameters of ChatGPT, Elevenlabs, and Google Text-to-Speech.

We hold deep respect for ChatGPT-Next-Web, as it served as a significant source of inspiration for us. Just for those seeking a different experience, we invite you to give [Talk](https://github.com/proxoar/talk) a try: [DEMO](https://talk.proxoar.com/)

If you're interested in deploying your own instance, you can access all the necessary resources at: https://github.com/proxoar/talk. Setting up your server using Docker is a pretty easy.

<img width="917" alt="0" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/27894831/46843a58-eba9-4667-9b74-4407bb87babd">

![1](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/27894831/04802307-cc6c-48ae-a942-42c98a505458)

![2](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/27894831/5bfe3dcd-2f6a-4613-86b6-771d0316a268)

![3](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/27894831/2d5c8dd6-0935-4321-b854-1c07ad744899)

**Comment by H0llyW00dzZ** [comment]
Audio models seems interesting
