### ISSUE TITLE
[Bug] share link mask haven't prompts

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2938]
When share link mask with 4 prompts like user or assistant is not possible reuse with share link public because that 4 prompts not there

Copy and paste share link mask and try to view if prompts is there ...

Share link have original prompts

VERCEL DEPLOY

**Comment by Yidadaa** [comment]
That is not possible, because we dont have a database to store prompts, you have to add the mask to the code base, so that you can share it as a link.
