### ISSUE TITLE
[Feature] 增加使用Access key使用GPT

### ISSUE THREAD

**Issue by 3856887** [Yidadaa/ChatGPT-Next-Web#2952]
建议增加通过Access key免费访问GPT3.5点功能
Access key可以通过json的方式在
https://chat.openai.com/api/auth/session
获得
**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。
以下是有这个功能的示例
https://github.com/Chanzhaoyu/chatgpt-web
**其他信息**
可以说说你的其他考虑。

**Comment by 3856887** [comment]
好像Access key可以当api key使用，🤡

**Comment by H0llyW00dzZ** [comment]
Tutorial: Obtaining a Session Key for OpenAI Platform #2936
