### ISSUE TITLE
[Feature] 我想每次对话的结果能够放到我的笔记本或者本地缓存，

### ISSUE THREAD

**Issue by sakurafly123** [Yidadaa/ChatGPT-Next-Web#2953]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
将每次对话记录保存到笔记本上或者本地磁盘中，方便以后查看，因为有的问题可能不止问一遍，后面还会再需要
希望能够快速定位上次问题，如果能从本地找到，就不会再消耗token，还有就是能够结构化，关联化，有这个想法，但是还不知道则呢么去做这个

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by H0llyW00dzZ** [comment]
This one better 
https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2955

**Comment by Yidadaa** [comment]
搜索功能请等待 #2158 
知识库功能请等待 #960
