### ISSUE TITLE
[Feature] 历史摘要提供复制粘贴的功能

### ISSUE THREAD

**Issue by JiaxiangBU** [Yidadaa/ChatGPT-Next-Web#2954]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

“历史摘要”是否可以提供复制粘贴的功能。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

类似于对话的标题，对话的历史摘要是比较好的总结，可以直接复制，作为总结。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

暂无。

**其他信息**
可以说说你的其他考虑。

目前我是F12提取出来复制的。

**Comment by H0llyW00dzZ** [comment]
you mean memory prompt ?
if memory prompt I already made 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/bf00f75b-df0e-4ae8-80d6-8e0d08c40901)

the stuff I used for creating masks for github action workflows generator hahahaha

![Github Action Workflow Generator](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/1cc311ce-bb0c-489f-8e40-bd9ec6bf92e0)

**Comment by GOWxx** [comment]
> I don't understand can you provide a screenshot, which is history abstract located in the bottom of the dialogue setting ?

这里就是历史摘要区域。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/12870715/befb8a0f-3e35-4e10-b803-e60bb27809ba)

**Comment by H0llyW00dzZ** [comment]
oh yeah that's memory prompt ai
i've made that already
commits logs :
https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/commit/39dd41895a467d9bd90673ec0ef30ad983ee244d
if you wanted I can pull req to @Yidadaa main branch

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/3dcdff22-240e-4dde-93f6-f85f23a67079)

other for a masks : 
https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/commit/dc9694e1705868cd46281a249b21d00974860577
