### ISSUE TITLE
[Bug] 2.9.8 Trojan:Win32/Wacatac.B!ml Virus

### ISSUE THREAD

**Issue by Mist-Hunter** [Yidadaa/ChatGPT-Next-Web#2961]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

Downloaded recent package for 2.9.8 on windows and all are flagged as viruses by Window Defender

**Comment by H0llyW00dzZ** [comment]
works fine for me 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/c721d816-84cc-4deb-af16-f1d0bac9b8d5)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/d59b511d-576b-42a7-b761-d5437c7566a0)

try "[ChatGPT.Next.Web_2.9.8_x64_en-US.msi](https://github.com/Yidadaa/ChatGPT-Next-Web/releases/download/v2.9.8/ChatGPT.Next.Web_2.9.8_x64_en-US.msi)"

**Comment by Mist-Hunter** [comment]
I'll give it a shot, ty

**Comment by Mist-Hunter** [comment]
Not sure why I got a hit on my machine but in case anyone looks through the conversation and gets nervous, I did direct pulls of the packages talked about here to VirusTotal and as @H0llyW00dzZ said, they are clean.

[v2.9.8/ChatGPT.Next.Web_2.9.8_x64-setup.nsis.zip](https://www.virustotal.com/gui/url/18da244c5b554a8ddab28c387b329049a2a43455f763c36a394072667a5c575c?nocache=1)
[
v2.9.8/ChatGPT.Next.Web_2.9.8_x64-setup.exe](https://www.virustotal.com/gui/url/07f26d94a6f02599a11f39f8aa8b55ed575155e18762bc007f28f1ef72b8cba1?nocache=1)

[v2.9.8/ChatGPT.Next.Web_2.9.8_x64_en-US.msi](https://www.virustotal.com/gui/url/5ac10ae300cedacba5c7eee8d8293f6710997844ab7217faa2c839a34c627af1?nocache=1)
