### ISSUE TITLE
[Bug] webdav提示同步成功但是磁盘上无数据

### ISSUE THREAD

**Issue by jaychoubaby** [Yidadaa/ChatGPT-Next-Web#2962]
配置了`webdav`，检测可用性为`通过`，点击同步提示`同步成功`，但是磁盘上无任何数据，对其是否成功心存疑虑

**Comment by Yidadaa** [comment]
F12 开控制台看 log

**Comment by jaychoubaby** [comment]
> F12 打开控制台看日志


You need to enable JavaScript to run this app.

**Comment by jaychoubaby** [comment]
> F12 开控制台看 log

我是用的alist搭建的webdav服务，目前找不到任何地方设置是否开启JavaScript的配置

**Comment by jaychoubaby** [comment]
配置问题解决了，但是`检测是否`可用提示` Method Not Allowed` ，同步却可以同步成功

**Comment by Yidadaa** [comment]
可用性检测只是辅助，webdav 配置环境复杂，不可能面面俱到，能同步就行。

**Comment by GriMu** [comment]
> 配置问题解决了，但是`检测是否`可用提示` Method Not Allowed` ，同步却可以同步成功
你好，想问下怎么解决的吗，我是用xiaoya alist的webdav，不知道哪里配置这个

**Comment by 2bstronger** [comment]
> 配置问题解决了，但是`检测是否`可用提示` Method Not Allowed` ，同步却可以同步成功

方便说一下在哪里配置解决的吗？我也是alist，我chrome 也开启了js（我不清楚”You need to enable JavaScript to run this app“说的是不是这个），但是还是没有同步成功。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/51631197/3b934cc0-fa7d-44a4-8a61-eea1f601c8db)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/51631197/93d4cb95-60c3-44c1-a382-04d3ca43edb1)
