### ISSUE TITLE
[Feature] Request put `latest.json` in somewhere

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Yidadaa/ChatGPT-Next-Web#2965]
**Is your feature request related to a problem? Please describe.**
Request put `latest.json` in somewhere not only in github assets (release) because I can't made this https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/pull/45 Work Perfectly in client app [tauri] (keep getting blocked when tryna fetch in github assets)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/e30125ae-a1d0-4661-85f6-060badb58a6e)

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/releases/latest/download/latest.json

**Comment by H0llyW00dzZ** [comment]
It work now wanted to pull req this soon:tm:
this a wild 

![Screenshot_244](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/459c47bc-2d38-4628-b577-d38f6149fe39)
![Screenshot_245](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/4b838da4-714b-4276-8639-0554d2557e6e)
