### ISSUE TITLE
关于token和attached message的困惑

### ISSUE THREAD

**Issue by yanglyu902** [Yidadaa/ChatGPT-Next-Web#297]
目前有三个关于每次对话给chatgpt多少信息的设置：
1. attached messages count
2. history compression threshold
3. max tokens

每次发消息时，这三者的关系究竟是怎样的？可不可以给一个流程图？

我目前的困惑是
1. `attached messages count`设置里24这个上限是如何决定的？为什么要设置上限？
2. 什么时候进行`history compression`? 是先基于`attached message count`选出最近`n`个message然后进行压缩，还是全部的历史信息都被压缩？是用户每发一次信息都压缩一次吗？并且压缩的时候相当于给chatgpt一个query让它来压缩?
3. `max token`的信息有被用到吗？我试了`max token=10`但仍然能返回有效信息。
4. `max token`大于3500左右的时候就偶尔有不响应的情况，即使message很短。
5. 聊天界面的`memory prompt`有什么用途？和`history compression`有关吗？

总之感觉需要一个清晰的流程图来让用户知道每一步究竟是什么信息被发送给了chatgpt。和官方chatgpt相比，目前这个chatgpt会somehow漏掉一些历史信息，不知道是不是我以上三个参数没有设置好。

我最终想解决的问题是，如果我想让chatgpt最大程度记住历史信息（不介意多花token），该如何设置这三个参数？比如`max token=3000`, `history compression threshold=3000`, `attached messages count=24` 是一个好的组合吗？

**Comment by Yidadaa** [comment]
全部拉最大可以最大程度保留信息。至于它们带关系，你是的八九不离十了，不过机制要稍微绕一点，拉大之后很容易碰到 4000 的官方上限，所以做了历史压缩。

调用 api 本来就很难记录所有的历史信息，有些历史上下文被遗弃很正常。
