### ISSUE TITLE
[Bug] 使用upstash同步会丢失API KEY 和 token吗？

### ISSUE THREAD

**Issue by llity** [Yidadaa/ChatGPT-Next-Web#2970]
配置好upstash后，点击同步，API和TOKEN都被重置了。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11771112/5dbc59bb-c4f2-4fe8-8916-440ba69a8b75)

同步可以自动运行吗？谢谢
谢谢

**Comment by Yidadaa** [comment]
一般来说不会，现在同步功能还有待改进。
