### ISSUE TITLE
[Feature] 支持语音输入

### ISSUE THREAD

**Issue by deartb** [Yidadaa/ChatGPT-Next-Web#2972]
作者方便加一个语音输入吗，就像这个网站 https://github.com/xqdoo00o/chatgpt-web，用起来更加方便。

Would you mind adding voice input functionality, similar to this website https://github.com/xqdoo00o/chatgpt-web? It would make it more convenient to use.

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/65097367/d1524102-587a-406a-8824-96dec6d1df48)

**Comment by Yidadaa** [comment]
暂时不会考虑，可以看这个 pr：https://github.com/Yidadaa/ChatGPT-Next-Web/pull/1298
