### ISSUE TITLE
新版本V2.9.8打开后UI变丑了

### ISSUE THREAD

**Issue by lulu-sk** [Yidadaa/ChatGPT-Next-Web#2974]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/58587930/8eb6837c-11e9-480d-9368-8132d7228349)

**Comment by luckykong** [comment]
'app/components/home.tsx' 文件里，132行的 `    config.tightBorder && !isMobileScreen && !getClientConfig()?.isApp;` ，改成‘    config.tightBorder && !isMobileScreen && getClientConfig()?.isApp;’可能就可以了

**Comment by Yidadaa** [comment]
感谢反馈，这是一个 bug，我会尽快修复。
