### ISSUE TITLE
[Bug] v2.9.9更新后Docker部署无法全屏

### ISSUE THREAD

**Issue by Kosette** [Yidadaa/ChatGPT-Next-Web#2981]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
2.9.9更新导致Docker部署的网页端无法全屏，没有测试过直接部署的结果，猜测应该是一样的。

不懂ts，猜测可能是2.9.9更新中的`config.tightBorder && !isMobileScreen && getClientConfig()?.isApp;`部分导致`getClientConfig()`返回`null`或者`undefined`的时候无法全屏。如果我猜测的逻辑正确的话，可能改成`getClientConfig()?.isApp || (config.tightBorder && !isMobileScreen);`这样可以解决。

测试后，Docker部署可以正常全屏，但没有测试app是否显示正确布局。

**Comment by H0llyW00dzZ** [comment]
this a bug not only in docker this affected to web version aswell
https://chatgpt.btz.sh/#/chat

**Comment by BunnySakura** [comment]
碰到了同样的问题
Encountered the same problem

**Comment by KevenLi8888** [comment]
Same problem here, cannot go fullscreen with version v2.9.8

**Comment by Yidadaa** [comment]
我会尽快修复。

**Comment by Yidadaa** [comment]
等待半小时后 CI 完成，重新拉取一遍 2.9.9 版本镜像即可：https://github.com/Yidadaa/ChatGPT-Next-Web/actions/runs/6464545494
