### ISSUE TITLE
[Feature] [Request] Render Based of GPU for client app

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Yidadaa/ChatGPT-Next-Web#2982]
**Is your feature request related to a problem? Please describe.**
Might if it possible it would be greatest ChatGPT Project as Open Source in The World if used GPU for rendering instead of CPU/Ram Memory  in client app

**Comment by Yidadaa** [comment]
It uses tauri: https://tauri.app/ , and renders with webview.

**Comment by H0llyW00dzZ** [comment]
yeah I know I've been checking it and tryna use a gpu for a rendering
