### ISSUE TITLE
[Bug] 客户端接口

### ISSUE THREAD

**Issue by CPwd520** [Yidadaa/ChatGPT-Next-Web#2984]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
客户端调用接口总是失败

**如何复现**
向客户端提交问题就提示failed to fetch。

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/39092582/f9d383e5-7608-4c77-96c0-07486a5df875)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器： [比如 chrome, safari]
 - 版本：2.9.9
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by H0llyW00dzZ** [comment]
I am pretty sure it's runtime issue (nodejs)

**Comment by CPwd520** [comment]
> 我很确定这是运行时问题（nodejs） 尝试重新启动客户端（通过在任务管理器上杀死它）或通过更改 ip 使用 VPN
thanks

**Comment by CPwd520** [comment]
> 我很确定这是运行时问题（nodejs） 尝试重新启动客户端（通过在任务管理器上杀死它）或通过更改 ip 使用 VPN

我用了你说的的方法，但是有时接口请求成功，有时还是失败是扫码原因额
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/39092582/447cf254-0018-445d-9687-a5ddeb34fcca)

**Comment by CPwd520** [comment]
> I am pretty sure it's runtime issue (nodejs) try restart client (by kill it on task manager) or use vpn by changing ip

我知道了，好像是你的接口不稳定，所以数据请求有问题

**Comment by Yidadaa** [comment]
网络问题请自行解决。

**Comment by hisaige** [comment]
我也遇到了这个问题，通过重新部署解决，重启没用
