### ISSUE TITLE
[Bug] dcoker部署 添加的环境变量没有生效

### ISSUE THREAD

**Issue by cloud-nine-GitHub** [Yidadaa/ChatGPT-Next-Web#2987]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用dcoker部署 添加的环境变量 并没有替换配置

**截图**
![企业微信截图_16969336047569](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/92359509/7fa283ae-55cd-4b75-9deb-efe69b8df4d2)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/92359509/3657841c-f727-4502-90a8-c81860185e72)

**如何复现**
docker镜像
yidadaa/chatgpt-next-web                                  latest              d6e716d6b8ba        6 hours ago         244MB
容器命令
docker run -d -p 8400:3000 --name chatgptWeb   -e OPENAI_API_KEY="sk-X2GW**************************n3jPh1dfy9G"  -e BASE_URL="https://chatgpt.xxxxxxxx.cn/api/openai"  yidadaa/chatgpt-next-web

**一些必要的信息**
 - 系统： windows 10
 - 浏览器：edge
 - 版本：2.9.9
 - 部署方式：docker

**Comment by cloud-nine-GitHub** [comment]
> env 中的配置和前端设置页的配置显然是分离的，难不成你想让你的用户直接看到你的 sk？

那个接口地址呢，也不能修改默认值吗

**Comment by Nolovenodie** [comment]
同样遇到此问题，环境变量设置接口地址后，前端无法直接使用。依旧是默认的OpenAI地址。。
