### ISSUE TITLE
[Bug] error Command failed with signal "SIGHUP"

### ISSUE THREAD

**Issue by pendy99** [Yidadaa/ChatGPT-Next-Web#2989]
[Time]  10/10/2023, 12:19:33 AM
[Auth] use system api key
[Proxy]  v1/chat/completions?path=v1&path=chat&path=completions
[Base Url] https://api.openai.com
error Command failed with signal "SIGHUP".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

每次运行后都会一段时间自动退出
是在ubuntu22.04上直接部署

**Comment by Yidadaa** [comment]
nextjs 本身存在内存泄漏，定时做好自动重启，多实例保活等机制。
