### ISSUE TITLE
[Feature] Show the consumed token of each message

### ISSUE THREAD

**Issue by JigaoLuo** [Yidadaa/ChatGPT-Next-Web#2991]
I have a feature request regarding the token consumption in the future release. It would greatly benefit me if there was a way to see the exact number of tokens used for each question and answer. 

By having this information readily available, I would be able to estimate the cost more accurately and make informed decisions about my usage. This feature would provide transparency and help me manage my usage effectively, ensuring that I stay within my desired budget. 

I believe that incorporating this feature into the future  release would greatly enhance the user experience and make this project even more user-friendly. Thank you for considering my suggestion.

**Comment by Yidadaa** [comment]
The library for calculating tokens will significantly increase the size of the application, which is very uneconomical, so we are not planning to add this function.
