### ISSUE TITLE
[问题] docker方式运行后，只要访问应用程序，容器就会一直进行写入操作，导致系统卡顿

### ISSUE THREAD

**Issue by yimuyangshu** [Yidadaa/ChatGPT-Next-Web#2995]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用的是0.5GB内存的服务器,单独使用docker运行该程序,但是通过3000端口访问后，容器docker stats显示 BLOCK I/O ，一直在进行写操作,导致服务器卡顿。但是在2GB服务器运行正常，有没有大佬能够帮忙解决一下的

访问是直接通过IP+Port访问
香港服务器

**如何复现**
根据文档的docker运行方式启动的容器

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/57276968/c75e3197-e081-4d30-ad6a-b8f374f3d2fd)

**一些必要的信息**
 - 系统：Centos7
 - 浏览器：chrome
 - 版本： 2.9.6
 - 部署方式：docker

**Comment by BunnySakura** [comment]
你看看是不是内存满了然后往交换分区写导致IO卡顿
