### ISSUE TITLE
你好老板，我想在部署到vercel之前自定义一些默认配置，请问在哪改

### ISSUE THREAD

**Issue by JeazW** [Yidadaa/ChatGPT-Next-Web#3]
比如紧凑边框、enter模式、记忆历史信息数量等，这些可以通过变量定义吗，或者需要在部署之前修改某些文件内容。

**Comment by Yidadaa** [comment]
目前要改默认配置的话，需要改动代码文件，修改 `store.ts` 里面的 `DEFAULT_CONFIG` 变量即可，具体位置在这里：

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/store.ts#L111
