### ISSUE TITLE
[Bug] macos下左边栏点选容易出现拖拽顺序的情况

### ISSUE THREAD

**Issue by llity** [Yidadaa/ChatGPT-Next-Web#3002]
选择后似乎没选上，移动鼠标就是拖拽。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11771112/758aae91-4024-4497-910e-02a5bb93832d)

选择tab后，触发拖动顺序。

谢谢

**Comment by Yidadaa** [comment]
无法复现。

**Comment by chenenyu** [comment]
这个是必现的问题啊，我用最新版本还是有的，很难受

**Comment by H0llyW00dzZ** [comment]
on windows/linux works fine, macos it's weird
