### ISSUE TITLE
https://nb.nextweb.fun/ 可能存在泄露用户token的风险

### ISSUE THREAD

**Issue by windanchaos** [Yidadaa/ChatGPT-Next-Web#3007]
### 问题描述
反馈当日的前一天，我在贵网站https://nb.nextweb.fun/，输入了我的token，结果昨天token的消耗量远超我的日常使用量。
我仅在该网站上上报过我的token。日常单日token正常使用量最大10dollar，昨天一天就消耗掉了65dollar。

![image](https://user-images.githubusercontent.com/15338996/274768223-dd124035-52eb-4872-97b7-88a2d445cd9d.png)

我是单线程操作，不存在并发消费情况，本地记录的自己消耗tonken数量为 21800039，按最贵的0.002/k dollar，整个消耗最多就40 dollar。而昨天一天就消耗了65dollar。对贵网站可能泄露了token持怀疑态度。

**Comment by Yidadaa** [comment]
如果你信不过，自己部署一个就行了，vercel 部署一遍要不了几分钟。
