### ISSUE TITLE
[Feature] Vercel auto-detect env variables

### ISSUE THREAD

**Issue by ImBIOS** [Yidadaa/ChatGPT-Next-Web#3008]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to check README to write the env variable in Vercel.

**Describe the solution you'd like**
Use `.env.example` instead of `.env.template`

**Comment by H0llyW00dzZ** [comment]
check this pr
https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2994

**Comment by Yidadaa** [comment]
Too many configuration options will confuse users. If you need advanced configuration options, please carefully refer to the documentation to set environment variables.
