### ISSUE TITLE
[Bug] WebDav non-responsive/failed sync

### ISSUE THREAD

**Issue by m0rg5** [Yidadaa/ChatGPT-Next-Web#3011]
**Describe the bug**
Triple checked WebDav settings, reset, re-added password, 'check connection' shows nothing, on attempt to sync get a perpetual "sync fail" message. 

I would expect to enter SSL/port, which is likely why it is failing. 

**To Reproduce**
Configure WebDav
Click Sync

**Expected behavior**
Sync is successful

**Versions (please complete the following information):**
 - OS: Mac Ventura 13.6.
 - CGPTNW: 2.9.9

**Comment by Yidadaa** [comment]
Please follow the steps below to troubleshoot the issue:
1. Please provide the webdav provider you are using.
2. Check if a new folder has been created in the webdav cloud drive.
3. Use the demonstration webpage of the project to retry the synchronization process.
4. In the demonstration webpage, if an error occurs, press the F12 key to open the console, check the detailed error message, and take a screenshot here.

**Comment by m0rg5** [comment]
1. Webhosting - Cpanel, 'web disk'.
2. Yes, with new password.
3. Noone should put their webdav details into a public demo page.

EDIT: Figured it - Cpanel is giving WRONG 'web disk' (webdav) authentication details.
I disabled CORS, and used full URL with port: https://domain.url:2078/ - this worked. 
Might be worth adding this to Wiki.

**Comment by Yidadaa** [comment]
By default, most webdav service providers disable CORS, which is why I provided the proxy URL option. Furthermore, based on your description, I cannot determine the specific cause of the error. 

Webdav configurations vary greatly, from authentication methods to network settings, and I do not have the resources to fully adapt to all of them. Therefore, I have only handled the commonly used methods.

**Comment by myriad2** [comment]
> webdav地址直接用 https://dav.jianguoyun.com/dav/ 不行，要在根目录新建一个文件夹，比如 chatgpt_next_web，填入https://dav.jianguoyun.com/dav/chatgpt_next_web
app版，国内没翻墙，没有启用app自带的代理
