### ISSUE TITLE
[Bug] Cannot deploy with cloudflare pages

### ISSUE THREAD

**Issue by Dorapower** [Yidadaa/ChatGPT-Next-Web#3015]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**

Cannot deploy on Cloudflare successfully following the [instruction](docs/cloudflare-pages-en.md)

**如何复现**

Following docs/cloudflare-pages-en.md

Error when deploying (after creating the compatible flags)

**截图**

who needs screenshots when you can have a [gist](https://gist.github.com/Dorapower/b3fd74da50f32adbc9fde0f8c17cb9e0)

**一些必要的信息**
 - 系统：windows 11
 - 浏览器：chrome
 - 版本：[today's main](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/06e043d3f1979c92d9fb0bd8068a78ffaaa9f108)
 - 部署方式：Cloudflare Pages

There are similar issues like #2161 describing failure while using Cloudflare pages to deploy, but there isn't much discussion or any pr related to that issue, so i am not sure if it's fixed. Our logs don't look the same though.

**Comment by Dorapower** [comment]
It seems like it failed when running the custom user command, but I am not familiar with js so I'm not sure what is happening

**Comment by Yidadaa** [comment]
Cloudflare deployment is not the preferred recommended method. I don't have enough energy to maintain the documentation for these platforms, so either you try to solve the problem yourself or consider using the Vercel platform for deployment.

**Comment by Dorapower** [comment]
fine, I will try vercel
