### ISSUE TITLE
[Feature] 移动端需要选项关闭对话页面的过度效果

### ISSUE THREAD

**Issue by reece00** [Yidadaa/ChatGPT-Next-Web#3016]
Safari浏览器右滑返回有自己的过度效果，网页再次过度效果不好看

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/37351410/26e75bba-10b5-4d1a-a890-33fe2fdfa32a

**Comment by reece00** [comment]
What are you two doing, don’t connect this repositories    @H0llyW00dzZ  @chenzeyu

**Comment by H0llyW00dzZ** [comment]
@reece00 it's Autolinked references github

**Comment by H0llyW00dzZ** [comment]
it won't connect, only linked a references
