### ISSUE TITLE
[Bug] Auto scroll the conversation to the bottom after leaving the current page and returning

### ISSUE THREAD

**Issue by SnowCharmQ** [Yidadaa/ChatGPT-Next-Web#3017]
**Describe the bug**
Sometimes, I scroll up to find previous messages, and then if I switch to another page or application and return, the conversation will automatically jump to the bottom. This is troublesome because I change pages frequently to check other info, but I have to scroll up again and again after returning.

**Expected behavior**
I think it will be better to have a setting to set a preferred pattern, whether the conversation should maintain its current location or jump to the bottom after leaving the page.

**Comment by Yidadaa** [comment]
When you have similar needs, please open a new tab to search for past messages.

**Comment by SnowCharmQ** [comment]
> When you have similar needs, please open a new tab to search for past messages.

Yeah, I used to do it, but switching a tab or page again would still jump to the bottom after returning. I think it is a poor user experience. Can you try to fix it or have a setting to make it more flexible?
