### ISSUE TITLE
[Feature] Wanted to pull req this Models DALL-E-2 [Beta]

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Yidadaa/ChatGPT-Next-Web#3018]
Show case :
![Exploring the Milky Way Galaxy](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/99ffc219-b4b1-4f46-bad9-034cbd1a66bd)
![Captivating Image_ Andromeda Galaxy](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/b0e50f28-f7d0-4d60-b416-cf17e7baaed0)
![Captivating Picture_ Milky Way](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/1b779e5b-4147-4d85-8057-3e1d9f5b0069)

![Exploring the Milky Way galaxy (1)](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/727240f1-9356-45e0-90d8-258c005879aa)

![Exploring Andromeda Galaxy](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/eecf0e34-270d-44fa-9c8b-67c21e852a14)

This based of communication AI
example how it work :
DALL-E-2 & gpt-3.5-turbo-0613 (tbh this model can read object such as image)
they are communication each other then gpt-3.5-turbo-0613 explaining to us

The best Machine Learning
Also, thanks to OpenAI for providing me with the maximum rate limits.

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/67a6f433-a5ec-42df-91e0-9d96d6d298f3)

**Comment by H0llyW00dzZ** [comment]
Additional Note for DALL-E-2 [Beta] [Experimental] Not Ready Yet : 
- [Network Search](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/165)

![JL2pezb](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/3bbc54ec-6fde-479c-afaa-c52356c0ca4b)

**Comment by H0llyW00dzZ** [comment]
Live Test : https://preview.chatgpt.btz.sh/

![Exploring Pinwheel Galaxy_ Facts   Beauty](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/59e7b098-f0fd-46ed-a634-7e1ab9a5eca0)

**Comment by Yidadaa** [comment]
#2904
