### ISSUE TITLE
上下文过多时卡顿问题

### ISSUE THREAD

**Issue by Cranberrycrisp** [Yidadaa/ChatGPT-Next-Web#302]
使用中发现一个聊天中对话数量过多时（几十句对话），聊天框键入或删除文本会有明显卡顿。调整过附带历史消息数没有改善。
当然不影响使用，也只对这一个话题对话有影响，只是交互体验感不好。

**Comment by Yidadaa** [comment]
这是因为 UI 没做长列表优化，需要做懒加载
