### ISSUE TITLE
[Feature] Add Persian language

### ISSUE THREAD

**Issue by mimsadAlef** [Yidadaa/ChatGPT-Next-Web#3024]
hi!
Please add persian language🤷‍♂️

**Comment by H0llyW00dzZ** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/translation.md

**Comment by mimsadAlef** [comment]
Farsi is RTL, what should I do to convert it to RTL?

**Comment by Yidadaa** [comment]
RTL is supported, just try https://github.com/Yidadaa/ChatGPT-Next-Web/blob/06e043d3f1979c92d9fb0bd8068a78ffaaa9f108/app/components/home.tsx#L142
