### ISSUE TITLE
[Feature] Ability to delete prompts and masks - (drop 'masks', and inc in prompts?)

### ISSUE THREAD

**Issue by m0rg5** [Yidadaa/ChatGPT-Next-Web#3030]
**Is your feature request related to a problem? Please describe.**
There are many prompts, and masks I do not need, and many more I cannot read.

_I've disabled the 'masks splash screen' as it serves no clear function. It makes more UX sense IMHO to include 'masks' in the comment box '/' prompts search (as 'masks' are functionally prompts too - I'm not clear as to how they're sufficiently different to warrant a disinction between them)._

**Describe the solution you'd like**
To be able to edit, delete both prompts and masks, and add new ones as needed (a duplicate option wld be handy too).

**Comment by Yidadaa** [comment]
Read this with google translate or chatgpt: https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/user-manual-cn.md

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/31d31c05-e170-41a8-8304-53e71332b1cc)

**Comment by m0rg5** [comment]
I **can't** delete any prompts in that list, which was my point.

I have, as I said, disabled masks.

Masks vs prompts make little sense.
