### ISSUE TITLE
[Bug]  Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by myluzh** [Yidadaa/ChatGPT-Next-Web#3032]
Application error: a client-side exception has occurred (see the browser console for more information). 
Request URL:
https://xxxx.com/_next/static/chunks/app/page-4c1887700c5770c6.js
Request Method:
GET
Status Code:
404 Not Found

这个资源一直404加载不了

**Comment by Yidadaa** [comment]
部署方式？

**Comment by myluzh** [comment]
docker run -d  -p 3000:3000 -e BASE_URL=https://api.openai.com -e OPENAI_API_KEY=xxxxx -e CODE=naimo123  yidadaa/chatgpt-next-web:latest
用docker跑起来 然后使用nginx反向代理到本地的3000

**Comment by myluzh** [comment]
docker run -d -p 3000:3000 -e BASE_URL=https://api.openai.com/ -e OPENAI_API_KEY=xxxxx -e CODE=xxxxxx 
 yidadaa/chatgpt-next-web:latest
用docker跑起来 然后使用nginx反向代理到本地的3000
