### ISSUE TITLE
如何配置ssl

### ISSUE THREAD

**Issue by seagullz4** [Yidadaa/ChatGPT-Next-Web#3034]
如何配置ssl证书

**Comment by Yidadaa** [comment]
自行搜索 ngnix 教程。

**Comment by Tasselmi** [comment]
看我的教程，老哥哥们： [免费自动续期签发的证书服务手把手教您](https://scalapie.com/2024/08/31/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF%E4%B9%8B7/)

**记得在底部评论给个好评额。**

**Comment by Tasselmi** [comment]
@seagullz4
