### ISSUE TITLE
[Feature] 建议增加一个通过Access Token实现对话的功能

### ISSUE THREAD

**Issue by K1vinL** [Yidadaa/ChatGPT-Next-Web#3036]
**你想要什么功能或者有什么建议？**
建议增加一个通过Access Token实现对话的功能，多一种可用的选择

**Comment by Pahkho** [comment]
goods suggestion

**Comment by gilgamsh** [comment]
https://github.com/xueandyue/ChatGPT-AccessToken-Web/tree/main
You can refer this repo @K1vinL
