### ISSUE TITLE
[Feature] Support default model change

### ISSUE THREAD

**Issue by wyhysj** [Yidadaa/ChatGPT-Next-Web#3043]
Looking at the envs, I can not find a proper way to set gpt-4 as default modelConfig, I think by default this will consume more tokens, but I think it can be an option for user to override.

**Comment by H0llyW00dzZ** [comment]
remove this `DISABLE_GPT4` in Environment Variables (eg vercel)
and edit this one 
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/78bddbc0-baef-43c8-8c04-a854854c7f7d)
`gpt-3.5-turbo` -> `gpt-4`

it will set `gpt-4` as default modelconfig

**Comment by wyhysj** [comment]
> remove this `DISABLE_GPT4` in Environment Variables (eg vercel) and edit this one ![image](https://user-images.githubusercontent.com/17626300/275728355-78bddbc0-baef-43c8-8c04-a854854c7f7d.png) `gpt-3.5-turbo` -> `gpt-4`
> 
> it will set `gpt-4` as default modelconfig

Hi @H0llyW00dzZ , my case is to deploy this app to Kubernetes cluster, so I prefer to use latest image you guys built in docker hub, change `config.ts` works, but I need to build my own image, which is not very good. If this setting can be exposed by `environment variables`, it's more flexible.

Hence, seems update this one in `config.ts`, the settings in other masks are still `model-3.5-turbo`.

**Comment by H0llyW00dzZ** [comment]
masks is different if its from Builtin Mask 
default masks for a default models (`modelConfig: ModelConfig;`) should be depends of that I've been tell you
also try clear all data / use different browser
```ts
export type Mask = {
  id: string;
  createdAt: number;
  avatar: string;
  name: string;
  hideContext?: boolean;
  context: ChatMessage[];
  syncGlobalConfig?: boolean;
  modelConfig: ModelConfig;
  lang: Lang;
  builtin: boolean;
};
```
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/d7afe2a6-6cb3-4f46-bc39-5ede233607f0)

**Comment by wyhysj** [comment]
Thanks @H0llyW00dzZ , clear all data works on masks, now I can build my own image to have gpt-4 model as default, if this modelConfig can be overridden from environment variable, it's even better, cheers.

**Comment by H0llyW00dzZ** [comment]
@wyhysj currently is not available for overridden rn, unless adding new `state` object.
