### ISSUE TITLE
[Bug] 注册的api key 在注册平台都能正常使用的，但是在自己部署的nextweb上内置了还是一直报错key无效，这是什么原因呢

### ISSUE THREAD

**Issue by sying-7** [Yidadaa/ChatGPT-Next-Web#3044]
{
  "error": {
    "message": "Incorrect API key provided: sk-wzFCE***************************************C93c. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}

**Comment by Yidadaa** [comment]
key 已失效。

**Comment by KallyYang** [comment]
同样的问题，后来有何发现吗
