### ISSUE TITLE
[Feature] 是否考虑支持阿里云的通义千问

### ISSUE THREAD

**Issue by xiyuvi** [Yidadaa/ChatGPT-Next-Web#3048]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。
国产的ai模型，可能没有openai的强大，但是付费还算方便一点https://help.aliyun.com/zh/dashscope/developer-reference/quick-start?spm=a2c4g.11186623.0.0.28c616e9aFuATO
**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by H0llyW00dzZ** [comment]
I can add this because a reference seems same like openai but I don't have access to that ai service

**Comment by Yidadaa** [comment]
等待 #2063
