### ISSUE TITLE
[Feature] upstash and vercel

### ISSUE THREAD

**Issue by Duan-rax** [Yidadaa/ChatGPT-Next-Web#3055]
情景说明；使用vercel部署，添加upstash数据库作为备份
1，备份是手动点击才可以，能否设置自动备份会话
2，能否将stash数据库两个值做成可选的environment variables从而使得新设备使用时不用手动输入

**Comment by Yidadaa** [comment]
备份功能尚不完善，目前的策略是能用就行。
