### ISSUE TITLE
[Feature] 在发送按钮旁边添加一个清空再发送按钮

### ISSUE THREAD

**Issue by lynn-yt** [Yidadaa/ChatGPT-Next-Web#3062]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/24616583/80ae6224-4f1a-4d10-b4e0-708d21d16f7d)

很多时候的对话的是问一些比较独立的问题，不需要历史聊天记录。点击清楚聊天再点发送，要点击两次，有时候还会忘记点击。
增加token费用。在发送按钮旁边添加一个清空再发送按钮，可以少点击一次。

**Comment by H0llyW00dzZ** [comment]
this one might can made a layout looks bad in mobile, maybe @Yidadaa can made looks it better
