### ISSUE TITLE
[Feature] Bard的优先适配，感觉超过市面上超GPT4外的AI

### ISSUE THREAD

**Issue by fangyuan99** [Yidadaa/ChatGPT-Next-Web#3068]
**你想要什么功能或者有什么建议？**
[Bard](https://bard.google.com/)的优先适配
试用了一段时间之后，发现Bard现在真的很强，他可以联网，甚至知道网络梗

**有没有可以参考的同类竞品？**
实现方式好像用`cookie`就行，隔壁的[chatgpt-mirai-qq-bot](https://github.com/lss233/chatgpt-mirai-qq-bot)是用`cookie`
[Bard Cookie 获取方法 · lss233/chatgpt-mirai-qq-bot Wiki](https://github.com/lss233/chatgpt-mirai-qq-bot/wiki/Bard-Cookie-%E8%8E%B7%E5%8F%96%E6%96%B9%E6%B3%95)
> 你需要通过电脑浏览器来获得 Bard Cookie ，如果你有别的手段能获得 cookie 的话也是可以的。
打开 Bard 官网：https://bard.google.com/
按下 F12，打开开发者工具（DevTools）
找到 网络（或 Network）
在页面上随便点击一个对话窗口，或者给 AI 发送消息 接下来，你可以在这里找到 Cookie：
复制 Cookie: 后面的所有文本，他们就是你的 Cookie。
<img src="https://user-images.githubusercontent.com/8984680/235232437-3bb57cea-bf70-4d3d-8496-f37abc82ba85.png" />

**其他信息**

以下是Bard的部分回答：

> 问：原神，启动！
> 
> 答：
> 原神启动！
> 
> 这句话是来自于一位名为“门酱”的博主在启动原神游戏时的视频。视频中，门酱一边喝着可乐，一边喊着“原神启动”，表情夸张，十分搞笑。这段视频很快在网络上走红，成为了原神玩家们常用的梗。
> 
> “原神启动”可以用来表达对原神的热爱，也可以用来调侃原神玩家。在原神玩家的眼中，“原神启动”是一段充满激情和欢乐的音符，是他们进入提瓦特世界的通行证。
> 
> 以下是一些“原神启动”的使用场景：
> 
> * 在原神直播或视频中，玩家们经常会在开始游戏时喊出“原神启动”，来表达对原神的热爱。
> * 在原神玩家的群聊中，玩家们经常会发送“原神启动”的表情包，来调侃其他玩家。
> * 在原神相关的文章或评论中，玩家们经常会使用“原神启动”来表达对原神的喜爱或吐槽。
> 
> “原神启动”已经成为了原神文化中的重要组成部分，它代表了原神玩家们对这款游戏的热爱和喜悦。
> 
> 问：原来，你也玩原神？
> 答：
> 是的，我玩原神。我喜欢原神的开放世界、丰富的剧情和精美的画面。我最喜欢的角色是魈，他的故事很感人，战斗也很强力。
> 
> 我还在原神中探索世界，还有很多东西没有体验到。我很期待未来原神还会推出什么新内容。
> 
> 你喜欢原神吗？你最喜欢的角色是谁？
> 
> 问：鸡你太美
> 答：
> 鸡你太美，是一句网络流行语，为歌曲《只因你太美》的空耳音译。出自明星“蔡徐坤”在节目《偶像练习生》中的自我介绍表演。
> 
> 在蔡徐坤的自我介绍表演中，他演唱了歌曲《只因你太美》。在歌曲中，原歌词是“只因你太美”，但蔡徐坤的口音导致“只因”被听成了“鸡你”。因此，这句话就成了“鸡你太美”。
> 
> “鸡你太美”这句话在当时迅速走红，成为了网络流行语。它被用来表达各种各样的意思，比如赞美、调侃、嘲讽等。
> 
> 以下是“鸡你太美”的几个常见用法：
> 
> * 用来赞美某人或某物的美丽。例如：这朵花真鸡你太美！
> * 用来调侃某人或某物。例如：你的新发型鸡你太美了！
> * 用来嘲讽某人或某物。例如：你的演技鸡你太美了！
> 
> “鸡你太美”这句话虽然是空耳，但它已经成为了网络文化的一部分。它代表着一种幽默感和调侃精神。

**Comment by H0llyW00dzZ** [comment]
Cookies can sometimes change due to expiration. 
It would be better to wait for the official API release of Google Bard AI, which can be easily configured.

**Comment by Yidadaa** [comment]
#2603
