### ISSUE TITLE
v2.9.9不能将聊天记录分享为图片[Bug] 

### ISSUE THREAD

**Issue by Riku1998** [Yidadaa/ChatGPT-Next-Web#3074]
**Describe the bug**
v2.9.9不能将聊天记录分享为图片，在windows chrome浏览器、edge浏览器，安卓chrome浏览器都不能导出图片，v2.9.8则是正常。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
its cors issue
you have to enabled this one in latest push commit about serviceworker
commits : 
cc565cf57ebedc6d59483e37b7633349426ff510

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/a02a9063-da54-4944-ae18-bedccf0a9b30)
