### ISSUE TITLE
[Feature]  增加 cloudflare ai gateway 地址支持

### ISSUE THREAD

**Issue by ibrother** [Yidadaa/ChatGPT-Next-Web#3079]
**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
增加 cloudflare ai gateway 地址支持
https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai
替换 openai 官方 api https://api.openai.com/v1 地址

**有没有可以参考的同类竞品？**
无

**其他信息**
https://developers.cloudflare.com/ai-gateway/get-started/connecting-applications/#openai

**Comment by ibrother** [comment]
> you don't have to setup it in cloudflare if already deploying on vercel just for proxying
> 
> ![Exploring Vercel's Edge Functions](https://user-images.githubusercontent.com/17626300/277270540-e54569ec-d901-44e1-bf18-873d069cd534.png)
> 
> also this repositories already had proxying like that cloudflare for other deployments

Hi, This is not only for proxying, but also for accessing features from the Cloudflare AI Gateway.

**Comment by H0llyW00dzZ** [comment]
@ibrother a feature only this one 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/2edb645a-c643-4df1-aa30-df2582bb704f)

and look the setup 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/71ae8259-7fb4-4a37-8001-47e3c6095397)

a client LLMAPI by @Yidadaa its better than that cloudflare

link : https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts

**Comment by H0llyW00dzZ** [comment]
another example a client LLMApi by @Yidadaa which is better than that cloudflare

I can add text-moderation & models dalle (image AI)
https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/blob/3.0.0/app/client/platforms/openai.ts

however in scenario if we planning for adding that cloudflare there is nothing much we can do as developer

**Comment by ibrother** [comment]
Okay, I understood. Thank you for your reply.
