### ISSUE TITLE
账户余额显示为0

### ISSUE THREAD

**Issue by huwan** [Yidadaa/ChatGPT-Next-Web#308]
使用18美元额度的试用的API时可以正常显示余额，总共$XX，已使用$YY。
![IMG_0744](https://user-images.githubusercontent.com/1451009/229264153-25a6f365-04cd-4611-8020-13d9c93f1a72.JPG)
但是切换为绑定支付方式，可以正常使用的付费API Key（每个月有$120使用额度上限）的时候，显示的内容均为$0。
![Jietu20230401-113549 2](https://user-images.githubusercontent.com/1451009/229264163-093f57bd-7cae-4006-a5e2-a6ed47305715.jpg)

**Comment by Yidadaa** [comment]
这个 api 返回数据比较迷，我的账户一直都是已用 18 美元，仅供参考就行了
