### ISSUE TITLE
[Bug] Wrong loading while scrolling 

### ISSUE THREAD

**Issue by weykon** [Yidadaa/ChatGPT-Next-Web#3088]
**Describe the bug**
 
at now, the dialog have 44 chatting records, scroll the page to bottom then scroll to up slowly, when it arrived the critical value of scroll bar percent,  it will suddenly jump to the top into the first message, therefore, I never can review the intermediate fragment.

**Expected behavior**
to in right loading behavior while scrolling 

**Deployment**
Vercel

**Desktop (please complete the following information):**
 Safair

now my build is in latest version.

**Comment by Yidadaa** [comment]
Please provide screen recording.

**Comment by weykon** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/assets/36456814/ab491de1-b0d2-4af8-9666-92f504283b48

!!! please note the right side scroll bar !!!       forget my chat, plz 
Here when I go from the top to the bottom of the bar, that jumps right to the end, and when I go from the latest roll to the top and almost to the top, he jumps right to the first one and never sees the middle part.

**Comment by weykon** [comment]
I made an app at macos used native code.  [the source code](https://github.com/weykon/new-man)

and I just set a webview in it , I do not think much relationship about on this code build.

**Comment by Yidadaa** [comment]
@weykon 将你的聊天记录导出为 json，然后导入到本项目的演示站，尝试复现该问题。注意保持窗体高度与你自己的应用相同。

**Comment by weykon** [comment]
Please re-open this issue.  @Yidadaa 

The scroll and window height inside, when using the PWA of ios or the webview of MAC OS safari, will trigger renderings to the top and bottom.

This may be caused by the way scroll events are handled differently in PWA on iOS or Safari WebView on MacOS than in other environments. 

1. Maybe the updates between requestAnimationFrame and react are at different paces?

2. Or is it caused by the native sliding optimization of mac and ios?

3. Try adding Debounce to control it.

**Comment by weykon** [comment]
> @weykon Export your chat history to json, and then import it into the demo site of this project to try to reproduce the problem. Be careful to keep the form height the same as your own application.

I have the same problem in my ios page as a PWA

**Comment by weykon** [comment]
I need to create a new issue to remind the author
