### ISSUE TITLE
不支持gpt4模型聊天

### ISSUE THREAD

**Issue by KingPlusOs** [Yidadaa/ChatGPT-Next-Web#309]
我的帐号是支持gpt4的，在open ai 官网可以聊天，在项目里一直提示 出错误，请重试

**Comment by IAMONLYERIC** [comment]
这里说的gpt4应该是指的api的gpt4，不是开通了chatplus之后的chatgpt-4

**Comment by KingPlusOs** [comment]
是的 我是开通了chatPlus  ，那我要如何操作呢。才能在项目里使用chat 4 呢

**Comment by IAMONLYERIC** [comment]
https://openai.com/waitlist/gpt-4-api
