### ISSUE TITLE
使用cnpm安装完依赖，运行npm run dev报错

### ISSUE THREAD

**Issue by hrz191128** [Yidadaa/ChatGPT-Next-Web#3093]
使用cnpm安装完依赖，运行npm run dev报错

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/142761838/e02df3e3-1da3-4d37-8f24-d59568f7c6fd)

**Comment by H0llyW00dzZ** [comment]
whats your node version ?

**Comment by Yidadaa** [comment]
1. 用 yarn
2. 确保 nodejs version >= 18
