### ISSUE TITLE
[Feature] Upstash提示redis两周不适用就要删除，建议增加自动备份功能

### ISSUE THREAD

**Issue by jaychoubaby** [Yidadaa/ChatGPT-Next-Web#3098]
已经部署好了Upstash的redis进行备份，今天早上收到邮件提示2周内不适用则会被删除，建议增加定时备份功能保证Upstash活跃状态

**Comment by H0llyW00dzZ** [comment]
starting made own syncing smiliar like this on golang
its possible and golang redis support json

**Comment by daiaji** [comment]
两周不用就删数据，这也太逆天了。
