### ISSUE TITLE
有两点建议

### ISSUE THREAD

**Issue by HanyangLin** [Yidadaa/ChatGPT-Next-Web#31]
1. 代码复制功能
2. 文本消息转语音

另外内容复制功能好像不能用。

**Comment by Yidadaa** [comment]
内容复制功能需要授权剪切板权限，如果你首次拒绝或者忽略了授权，那么复制功能就会不可用，你可以问问 chatgpt 如何你所用的操作系统、浏览器版本的权限如何重新授权。

代码块复制功能正在开发中，下个版本就会有，请保持关注。

**Comment by Yidadaa** [comment]
内容转语音功能暂时不在计划内，请搭配浏览器插件解决。
