### ISSUE TITLE
[Bug] Not using GPT-4

### ISSUE THREAD

**Issue by m0rg5** [Yidadaa/ChatGPT-Next-Web#3101]
**Describe the bug**
I'm using API, it's succdesfully showing models and using 3.5 Turbo most of the time.
When I select GPT-4 above the comment box it does not use the GPT-4 model.
I confirmed this, after suspecting, by specifically asking:

what gpt model are u?
_I am based on OpenAI's GPT-3 model. As of my last training data in September 2021, GPT-4 or any subsequent models have not been released by OpenAI._

**To Reproduce**
As above

**Screenshots**
<img width="862" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8669538/a79e5e78-a6e2-4efb-801c-12834b6a225b">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.6.1
 - CGPTN v2.9.9

**Comment by Yidadaa** [comment]
Common sense: When you ask GPT about its version, it doesn't know who it is.

**Comment by m0rg5** [comment]
How is that "common sense"? Maybe you mean "common knowledge", and given I didn't, well 🤷‍♂️.

So, it's still showing
<img width="856" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8669538/e127e03b-93eb-44c2-bf1c-daea2249e4be">

Shouldn't it be at least Jan 2022, if not later - for GPT4?

See: https://www.reddit.com/r/OpenAI/comments/17h5hbc/chatgpt_is_now_updated_to_january_2022/

**Comment by H0llyW00dzZ** [comment]
@m0rg5 
api and https://chat.openai.com/ are different 
do test here :  https://platform.openai.com/playground

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/2bcfbfe8-2e6d-4348-af07-4205b17d7ac5)

**Comment by m0rg5** [comment]
> @m0rg5 api and https://chat.openai.com/ are different do test here : https://platform.openai.com/playground
> 
> ![image](https://user-images.githubusercontent.com/17626300/278666779-2bcfbfe8-2e6d-4348-af07-4205b17d7ac5.png)

So all API clients cutoff **is Sept 2021** - is yr point?

At https://chat.openai.com/ 👍 
<img width="436" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8669538/ccd23b44-1796-4070-847f-1962758c89e0">

Still asking how to confirm/verify in CGPTN app use of whatever model.

**Comment by H0llyW00dzZ** [comment]
So all API clients cutoff is Sept 2021 - is yr point?
yes
also read here about privacy for api https://openai.com/enterprise-privacy

**Comment by m0rg5** [comment]
> Still asking how to confirm/verify in CGPTN app that we are using whatever model.

Bump?

How can we confirm/test this is working correctly?
