### ISSUE TITLE
[Bug] 绑定了自定义域名,但是仍然会被墙，如何在不开梯子的情况下使用

### ISSUE THREAD

**Issue by xiangnanscu** [Yidadaa/ChatGPT-Next-Web#3102]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
绑定了自定义域名, 比如我绑定在chat.foo.com, 但是仍然会向vitals.vercel-insights.com发起请求, 导致ERR_CONNECTION_RESET

**如何复现**
直接访问首页

**截图**
控制台截图
```
Failed to load resource: net::ERR_TIMED_OUT
7698-eba6250449e9934b.js:1  [Chat] failed  TypeError: Failed to fetch
    at R (224-37b3f5328a8474e3.js:52:2192)
    at 224-37b3f5328a8474e3.js:52:3263
    at new Promise (<anonymous>)
    at l (224-37b3f5328a8474e3.js:52:1691)
    at c.chat (page-41b0e79c7a0c84af.js:1:22446)
    at Object.onUserInput (page-41b0e79c7a0c84af.js:1:179519)
    at O (3547.0ba41f989e50d982.js:1:46383)
    at onClick (3547.0ba41f989e50d982.js:1:54596)
    at Object.l5 (bce60fc1-76a57db123ee8dbb.js:9:67335)

```
**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by Yidadaa** [comment]
请确定你使用 cname 的方法绑定域名。
