### ISSUE TITLE
可以支持通过子目录的方式来访问页面吗？例如：https://ai.example.com/chatUI

### ISSUE THREAD

**Issue by yankevin** [Yidadaa/ChatGPT-Next-Web#3104]
我用Docker在服务器上部署了多个实例，分别使用了不同的端口：192.168.1.1:3000、192.168.1.1:3001、192.168.1.1:3002

我想通过同一个域名的子文件夹来访问它们，如：

http://ai.example.com/chatUI-one  --> 192.168.1.1:3000
http://ai.example.com/chatUI-two  --> 192.168.1.1:3001
http://ai.example.com/chatUI-three  --> 192.168.1.1:3002

**Comment by yankevin** [comment]
类似于这个项目中提到的 CMD_URL_PATH=codimd 参数样式，有开发计划提供吗？
https://github.com/hackmdio/codimd/issues/1440

**Comment by Yidadaa** [comment]
请通过 ngnix 配置解决此问题。

**Comment by Immortalyzy** [comment]
楼主找到解决办法了吗？我测试了好多办法都没法正常运行，要么就是一直显示加载的三个点要么是主界面显示出来之后点任何东西都报错。感觉这个程序需要知道他是在子目录下运行才能正常跑。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/13324199/ca1f4978-5bd2-4ef7-b991-5cbeaad3d66b)

**Comment by Immortalyzy** [comment]
> http://ai.example.com/chatUI-one --> 192.168.1.1:3000
> http://ai.example.com/chatUI-two --> 192.168.1.1:3001
> http://ai.example.com/chatUI-three --> 192.168.1.1:3002
这样有些难，不过这样很简单

http://chatUI-one.example.com/ --> 192.168.1.1:3000
http://chatUI-two.example.com/ --> 192.168.1.1:3001
http://chatUI-three.example.com/--> 192.168.1.1:3002
