### ISSUE TITLE
[Bug] MacOS Application hangs when fonts.google.com domain is blocked

### ISSUE THREAD

**Issue by jedi-admin** [Yidadaa/ChatGPT-Next-Web#3107]
**Describe the bug**

**To Reproduce**
1. block domain `fonts.google.com` 
2. Open the APP
3. it will take about a minute before the application proceeds to load (I suppose the retries to load the remote fonts)

**Expected behavior**

There should be NO DEPENDENCY on google fonts or any 3rd party services while running a desktop application. also fonts loading should not block the loading of the app.

**Comment by jedi-admin** [comment]
all google domains/ services are blocked on the network due to the security policy in place.

**Comment by H0llyW00dzZ** [comment]
are you using client from this https://github.com/Yidadaa/ChatGPT-Next-Web/releases/tag/v2.9.9 ?

**Comment by Yidadaa** [comment]
The latest version of the desktop application, loading Google Fonts does not block the app startup, please upgrade.
