### ISSUE TITLE
为什么我问两三个问题后便会报错，提示：出错了，稍后重试吧

### ISSUE THREAD

**Issue by zzQ894416361** [Yidadaa/ChatGPT-Next-Web#311]
新起聊天窗口便又可以问两三个问题，我添加了OPENAI_API_KEY和BASE_URL变量

**Comment by Yidadaa** [comment]
请提供网页控制台截图和 vercel 或者你自己部署的后端运行 log。

**Comment by jazzbon** [comment]
我也是。对话不超过5次，“出错了，稍后重试吧”

**Comment by jazzbon** [comment]
> 请提供网页控制台截图和 vercel 或者你自己部署的后端运行 log。

log里的eror=504

[POST] /api/chat-stream reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true

**Comment by Yidadaa** [comment]
openai 的问题。

**Comment by AreChen** [comment]
我今天是所有聊天窗口只能回答一次，然后就错误了，小白想问下，我是在docker 中部署的，去哪里看log呢？
