### ISSUE TITLE
[Bug] /_vercel/insights/script.js 404 not found

### ISSUE THREAD

**Issue by fising** [Yidadaa/ChatGPT-Next-Web#3111]
**Describe the bug**
部署到 vercel 后，发现无法正常加载 https://自定义域名/_vercel/insights/script.js

**To Reproduce**
1. 打开部署的站点
2. 打开chrome开发者工具
3. 切换到 Network 标签，查看资源加载情况

**Expected behavior**
正常加载 https://自定义域名/_vercel/insights/script.js

**Screenshots**
![20231030100542](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1930658/8c5a28fb-8581-4aa3-83c0-a70a0607a578)

**Deployment**
- ✅ Vercel

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome 
 - Version: 118.0.5993.88

**Comment by Yidadaa** [comment]
这是 vercel 的分析服务，默认情况下不会启动：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/b90dfb48ee0446fdcb567dae2b77220508f62f0d/app/page.tsx#L13
