### ISSUE TITLE
[Bug] Suspicious API Usage?

### ISSUE THREAD

**Issue by Helmasko** [Yidadaa/ChatGPT-Next-Web#3117]
**Describe the bug**
The website https://ab.nextweb.fun/ seems to be using high amounts of API usage ($0.10+ in 30 minutes for gpt-4 with only a single message) even when it is currently unused.

**To Reproduce**
1. Go to https://ab.nextweb.fun/
2. enter OpenAI API key
3. use the gpt-4 bot once
4. wait about 10-30 minutes

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: v2.9.9

**Comment by Yidadaa** [comment]
Have you seen multiple usage records in the quantity log?

**Comment by Helmasko** [comment]
What do you mean by that? For testing purposes I only used the API token on the website and I am certain that it's this app that is using it.

**Comment by DaniEnsi** [comment]
@Helmasko 
You can use Postman for example to get the api key usage for a certain time period...
1. Get Request to: `https://api.openai.com/v1/usage?date=2023-10-31` where the `date` is in YYYY-MM-DD format
2. This will return you a usage list for your Api Key like this:

```JSON
{
    "object": "list",
    "data": [
        {
            "organization_id": "org-IrEnPBQSfaDHEMLzjCOw9r0w",
            "aggregation_timestamp": 1698663600,
            "n_requests": 2,
            "operation": "completion",
            "snapshot_id": "gpt-4-0613",
            "n_context": 2,
            "n_context_tokens_total": 811,
            "n_generated": 2,
            "n_generated_tokens_total": 41,
            "user_id": null
        },
        {
           ...
        },
        {
            "organization_id": "org-IrEnPBQSfaDHEMLzjCOw9r0w",
            "aggregation_timestamp": 1698704400,
            "n_requests": 1,
            "operation": "completion",
            "snapshot_id": "gpt-4-0613",
            "n_context": 1,
            "n_context_tokens_total": 59,
            "n_generated": 1,
            "n_generated_tokens_total": 100,
            "user_id": null
        }
    ],
    "ft_data": [],
    "dalle_api_data": [
        {
            "timestamp": 1698663660,
            "num_images": 1,
            "num_requests": 1,
            "image_size": "1024x1024",
            "operation": "generations",
            "user_id": null,
            "organization_id": "org-IrEnPBQSfaDHEMLzjCOw9r0w"
        }
    ],
    "whisper_api_data": []
}
```

Also dont forget to add your Api Key as a Bearer Token to your request...

**Comment by Yidadaa** [comment]
@Helmasko My point is that you need to check the usage of your key on platform.openai.com. If you find any unauthorized usage in the usage records, please consider revoking the generated API key and generating a new one.

**Comment by Helmasko** [comment]
@DaniEnsi thank you for your reply, I will look into that.
@Yidadaa refer to my previous comment

**Comment by Helmasko** [comment]
using https://api.openai.com/v1/usage ive found out about a few things.
- chat hitsory gets sent for every consecutive response in the same chat window.
- even though i only use gpt4, i see gpt3.5 usage as well is this the history compressor?

**Comment by reece00** [comment]
1. Go to search how GPT is used
2. Set yourself and turn off the Auto Generate Title

**Comment by Helmasko** [comment]
1. how do you think I found out about it... would've been a lot easier if this 'how GPT is used' article was linked on the repo somewhere to reduce confusion. As I see many people on the internet have also wondered why API usage is high, I can see this benefitting a lot of people.
