### ISSUE TITLE
优化输入框高度

### ISSUE THREAD

**Issue by tisfeng** [Yidadaa/ChatGPT-Next-Web#312]
目前输入框的高度是固定，即使输入一行文本，高度也很大，用户体验不佳，也太占用屏幕空间。

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/25194972/229269889-d796afd6-7d15-4a48-aa4f-43487edc8c5e.png">

建议参考 ChatGPT 官方 UI，默认显示一行文本高度，再设置一个最大高度，在此区间范围内输入框的高度可根据输入文本自适应调整

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/25194972/229270007-752542be-f3a0-4f1c-afaa-3838aa9ccc1f.png">

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/25194972/229269852-562b7bf0-2d9c-49d8-b05a-9a05e3c0b8f9.png">

**Comment by douglas-lee** [comment]
还有就是发送代码的时候，被自动格式化了。

**Comment by Yidadaa** [comment]
#118
