### ISSUE TITLE
cannot get response using anyscale api[Bug] 

### ISSUE THREAD

**Issue by OTA-Tech-AI** [Yidadaa/ChatGPT-Next-Web#3124]
**Describe the bug**
I put my anyscale api endpoint and supplied my api key, but the result keep printing

{
  "detail": "Not Found"
}

**To Reproduce**
use this end point https://api.endpoints.anyscale.com/v1
use this model meta-llama/Llama-2-70b-chat-hf

**Expected behavior**
{
  "detail": "Not Found"
}

**Deployment**
local

**Desktop (please complete the following information):**
windows

**Comment by Yidadaa** [comment]
remove trailing `/v1`
