### ISSUE TITLE
[Feature] Multi-Backend API Configuration

### ISSUE THREAD

**Issue by SamirSaidani** [Yidadaa/ChatGPT-Next-Web#3125]
I would love the ability to configure multiple chat backends and seamlessly switch between them in conversations. Supporting models like llama2 / mistral / Claude etc. via openai-compatible APIs would add versatility for various use cases. Currently, it seems limited to one backend configuration per conversation, instead of being able to switch between several api backends per conversation. This enhancement would greatly enhance the user experience.

**Comment by Yidadaa** [comment]
wip: #2603
