### ISSUE TITLE
Font is too small in prompt edit (✏️) view

### ISSUE THREAD

**Issue by m0rg5** [Yidadaa/ChatGPT-Next-Web#3126]
**Is your feature request related to a problem? Please describe.**
When I click edit on a prompt I've written the font is too small for me to easily read (I wear 👓).

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8669538/4f4231e1-dbea-46a8-baf0-d39c42c3ff9e)

**Describe the solution you'd like**
An option in settings to define the font size (or short term - what text file to edit).

**Comment by Yidadaa** [comment]
You can use the following methods to zoom in on the text on the screen:
- Press and hold the Ctrl key while scrolling the mouse wheel
- Use `Ctrl =` and `Ctrl -` to zoom page

**Comment by m0rg5** [comment]
> * Press and hold the Ctrl key while scrolling the mouse wheel
> * Use `Ctrl =` and `Ctrl -` to zoom page

This doesn't work on Mac OR in the EDIT window. 

Neither does this resolve the issue of there being no option for changing **EDIT WINDOW** font size.

**Comment by m0rg5** [comment]
@Yidadaa Can you pls review this? 

I literally cannot read what's in the **edit** window: I need new glasses, my eyesight is worse on some days than others, and today I literally cannot read the text in the **edit** window.
