### ISSUE TITLE
[Feature] 可以添stop_token_ids 字段设置么。。。

### ISSUE THREAD

**Issue by YingchaoX** [Yidadaa/ChatGPT-Next-Web#3128]
使用Qwen-14B-Chat作为backend，没有触发stop_token会一直输出文字。。。

**Comment by H0llyW00dzZ** [comment]
not available at this moment because it will break client openai LLMApi which is the best already

**Comment by Yidadaa** [comment]
你在服务端设置好默认值就可以了，自建模型的优点不就是这样吗

**Comment by CoderCore** [comment]
在使用 python -m vllm.entrypoints.openai.api_server 启动API服务器时，若你想为模型推理添加 sample_params（采样参数），通常这些参数不是直接通过命令行传递给API服务器的。相反，sample_params 是在API请求中作为参数传递给模型的。

**Comment by kevinzhao2233** [comment]
> 在使用 python -m vllm.entrypoints.openai.api_server 启动API服务器时，若你想为模型推理添加 sample_params（采样参数），通常这些参数不是直接通过命令行传递给API服务器的。相反，sample_params 是在API请求中作为参数传递给模型的。

请问你现在是怎么解决这个问题的
