### ISSUE TITLE
目前更新到什么程度了，支持图片了嘛，我应该怎么更新，更快捷的更新方法有嘛？

### ISSUE THREAD

**Issue by mozhu-too** [Yidadaa/ChatGPT-Next-Web#3129]
目前更新到什么程度了，支持图片了嘛，我应该怎么更新，更快捷的更新方法有嘛？

**Comment by H0llyW00dzZ** [comment]
owner been refactoring this https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3072

**Comment by mozhu-too** [comment]
> 业主一直在重建这个#3072

明白了，好的感谢
