### ISSUE TITLE
允许设置 System Prompt？

### ISSUE THREAD

**Issue by l3ony2k** [Yidadaa/ChatGPT-Next-Web#314]
有时候希望一个对话专门用来解决一个问题（例如翻译、润色），但是经过几次来回后就会忘记最早 Prompt 的要求，就要再重新输入一次 prompt。希望可以允许设置一个对话的 system prompt，这样使用更方便一些。

或许还有其他实现这个需求的方法但我不知道的吗？

**Comment by Yidadaa** [comment]
#138

**Comment by ImAmelie** [comment]
问下 `system prompt` 和 `assistant prompt` 有什么区别吗？好像都是 AI 的回复。
