### ISSUE TITLE
[Feature] Add a version selection on the screen to use 3.5 or 4

### ISSUE THREAD

**Issue by cvanderhaar** [Yidadaa/ChatGPT-Next-Web#3142]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I just want to see how I can use version 3.5 and 4 in the app and point to the right model in the config

**Describe alternatives you've considered**
In the requestOpenApi I added my endpoints and created a version slider component to handle this but I just cannot get it to work

**Additional context**
PLEASE HELP

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/af89533a-c552-46a9-930b-25c2ba263337)

**Comment by cvanderhaar** [comment]
Is it done already
