### ISSUE TITLE
[Feature] New Model is Actived , Please add them

### ISSUE THREAD

**Issue by sinfee** [Yidadaa/ChatGPT-Next-Web#3146]
Thanks for your job ! 
There are some new openai models , Please add them :
gpt-3.5-turbo-1106
gpt-4-1106-preview
...

**Comment by H0llyW00dzZ** [comment]
Feat Models [GPT-4] [GPT-3.5] [128K context] #3143

**Comment by wadang** [comment]
可以先用自定义模型功能，自己添加进去。https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3147

**Comment by Yidadaa** [comment]
Merged.

**Comment by qwe325207** [comment]
Add dall-e-3 to the custom model. When using it, it shows that I don’t have permission.

{
"error": {
"message": "You are not allowed to sample from this model",
"type": "invalid_request_error",
"param": null,
"code": null
}
}
