### ISSUE TITLE
[Bug] 自定义的模型不起作用，如 gpt-4-1106-preview

### ISSUE THREAD

**Issue by wadang** [Yidadaa/ChatGPT-Next-Web#3147]
在后端设置 最新版 gpt-4-1106-preview
![WX20231107-100832@2x](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1182832/7b079258-12b7-4026-a909-277dd11af4d2)

结果收到的还是 GPT4
![WX20231107-100846@2x](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1182832/a301213d-e545-4757-8810-440a589b8365)

**Comment by H0llyW00dzZ** [comment]
Feat Models [GPT-4] [GPT-3.5] [128K context] #3143

**Comment by wadang** [comment]
After taking a closer look at the settings, it seems to be a problem prompted by the system's default settings. So close this issue

![Uploading WX20231107-101838@2x.png…]()

**Comment by wadang** [comment]
![WX20231107-101838@2x](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1182832/6badcd7f-d056-4b77-96ba-c35782012900)

**Comment by wadang** [comment]
其实用自定义模型功能就可以了 ，是生效的。
![WX20231107-102140@2x](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1182832/4d9b5bc9-d5f3-4848-b4ad-50cd3e72f384)

**Comment by ilxqx** [comment]
是怎么操作的？我设置自定义模型死活不生效，也不知道哪里配置有问题，我都检查了一遍，也没发现哪里不对

**Comment by H0llyW00dzZ** [comment]
it will set as default like other models , no need to configure in custom models

**Comment by notdp** [comment]
可以设置默认模型为gpt-3.5-turbo-1106吗
这个模型快了很多 而且还便宜

**Comment by ahhxyz** [comment]
我设置并使用了gpt-4-1106-preview，代码已经更新到了最新并已重新部署了，但还是不生效。

**Comment by ilxqx** [comment]
@ahhxyz 我来告诉你，在设置界面最下面重置一下设置就好了，具体原理我也不懂，好了就行，不用深究
<img width="1094" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/18739624/6fc4cfa5-d54a-4864-96b1-bdcd354a2e3a">

**Comment by ahhxyz** [comment]
@ilxqx 我刚试了，还是不行唉

**Comment by ilxqx** [comment]
@ahhxyz 你卸载了重新安装试试，我当时也是不生效，升级了也不生效，我就重置了一下设置就好了

**Comment by ahhxyz** [comment]
@ilxqx 我是用vercel部署的，删了重新部署就好了，谢了
