### ISSUE TITLE
[Bug] 自定义模型不生效

### ISSUE THREAD

**Issue by ilxqx** [Yidadaa/ChatGPT-Next-Web#3148]
**Describe the bug**
OpenAI刚刚发布新模型：gpt-4-1106-preview，工具没有内置，添加了自定义模型，聊天的时候用的依旧是以前设置的模型

**To Reproduce**
1. 选择自定义模型
<img width="1379" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/18739624/13dd1578-2498-40fb-bbc1-2f5d32c4b4ec">

2. 聊天测试
<img width="1379" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/18739624/9c7dde43-153b-4ef4-992f-9784212f6a55">

发现日期不对，肯定没有使用到自定义的这个模型，我通过命令测试新模型如下：
```shell
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-xxx" \
  -d '{
     "model": "gpt-4-1106-preview",
     "messages": [{"role": "user", "content": "请问你的训练日期截止什么时间？"}],
     "temperature": 0.2
   }'
```
得到结果：
```json
{
  "id": "chatcmpl-8I61KXkfxvfe4Q9qYFU8rXdCR5OhX",
  "object": "chat.completion",
  "created": 1699323738,
  "model": "gpt-4-1106-preview",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "我的知识截止日期是2023年4月，这意味着我所了解的信息和数据都是在这个时间点之前的。如果你有任何问题，我会尽力根据我所了解的信息来回答。如果你需要最新的信息，我建议查阅最新的资料或者使用实时的在线资源。"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 24,
    "completion_tokens": 94,
    "total_tokens": 118
  },
  "system_fingerprint": "fp_a24b4d720c"
}
```
可以看到2023年4月就合适了，说明用到了这个模型 `gpt-4-1106-preview`

**Expected behavior**
可以按预期使用到模型 `gpt-4-1106-preview`

**Screenshots**
<img width="1379" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/18739624/a8328119-6207-43a8-bcd1-de7eae274b8c">

**Comment by H0llyW00dzZ** [comment]
Feat Models [GPT-4] [GPT-3.5] [128K context] #3143

**Comment by Yidadaa** [comment]
不是 bug，默认注入的提示词有问题罢了。

**Comment by Yidadaa** [comment]
等 #3143 合入。
