### ISSUE TITLE
max_tokens填写4000会报错

### ISSUE THREAD

**Issue by AreChen** [Yidadaa/ChatGPT-Next-Web#315]
在测试中发现，若将max_tokens参数设置为4000，系统会抛出错误。因为之前使用过其他项目的开发者可能会将此参数值设置为4000。本人也进行了测试，将该参数从2000改为4000后，发现每个对话GPT只能回答一次后就会报错。改回2000后，回答正常。需注意调整此参数时，要避免超过系统可承受的最大值。

**Comment by Yidadaa** [comment]
官方文档：https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens

>max_tokens
integer
Optional
Defaults to inf
The maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the chat completion.
The total length of input tokens and generated tokens is limited by the model's context length.

看起来设置成无穷都没事，我自己测试了几个值，并没有触发该 bug，请重新确认一下。

**Comment by AreChen** [comment]
设置4000
![image](https://user-images.githubusercontent.com/20765464/229302193-d634d542-3b2d-42f4-bef7-2b95cee210bf.png)
![image](https://user-images.githubusercontent.com/20765464/229302232-267ee220-a8b8-408d-80df-1ae528510fe9.png)
设置2000
![image](https://user-images.githubusercontent.com/20765464/229302288-db1818f2-a83d-4374-b799-7a57351eff17.png)
![image](https://user-images.githubusercontent.com/20765464/229302315-11c04833-d434-415e-8f54-b16659e23d77.png)
版本1.8
DOCKER部署
nginx反代走https，配置文件[参考](https://github.com/Chanzhaoyu/chatgpt-web/issues/402)
`server {
                listen      100 ssl;
                ssl_certificate /etc/nginx/certificate.crt;
                ssl_certificate_key /etc/nginx/private.key;
                ssl_ciphers     ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4; 
                ssl_protocols   TLSv1 TLSv1.1 TLSv1.2; 
                server_name  chat.mydomain.com;域名
        location / {
                default_type octet-stream;
                chunked_transfer_encoding on;
                tcp_nopush on;
                tcp_nodelay on;
                keepalive_timeout 65;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header REMOTE-HOST $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_buffering off;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_pass  http://127.0.0.1:3000;

        }
}`
会不会跟NGINX有关系？

**Comment by AreChen** [comment]
在4000情况下，如果GPT回答答案较短可以多次回答一旦长串回答就会出错
![image](https://user-images.githubusercontent.com/20765464/229303353-bcf12b70-f110-456f-92bd-d475c5516107.png)
![image](https://user-images.githubusercontent.com/20765464/229303375-3386b500-6193-4e23-82ac-e8d804348778.png)

**Comment by AreChen** [comment]
3800效果
![image](https://user-images.githubusercontent.com/20765464/229303559-d41b64ee-72d3-4646-bdea-409803c9aa21.png)

**Comment by AreChen** [comment]
最新发现，当我以这些文字去分别测试tokens数值，GPT不在第一轮回答就挂掉的最大值在3176，但是还是对话2论就挂了。
测试了一些数值后，对我来说2000-3000是个很稳定的值，不太清楚这个值到底跟什么有关系。
`现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”`
![image](https://user-images.githubusercontent.com/20765464/229304520-5e192b69-cda2-42a8-a2b3-71bc71422f6b.png)

**Comment by AreChen** [comment]
> 官方文档：https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens
> 
> > max_tokens
> > integer
> > Optional
> > Defaults to inf
> > The maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the chat completion.
> > The total length of input tokens and generated tokens is limited by the model's context length.
> 
> 看起来设置成无穷都没事，我自己测试了几个值，并没有触发该 bug，请重新确认一下。

令人震惊的是当我设置成1000000000000000000值，居然很稳定，而且可以发送以下的超长文字

`现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”现在我在测试，你只需要回答我“现在我在测试，你只需要回答我”`

**Comment by AreChen** [comment]
另外一段测试文案2000写不出来，1000000000000000000值随便写阿，震惊了
```
允贞诱拐案
2000年7月29日一个女孩儿拿着羽毛球拍安静的坐在学校台阶上，同学们都在玩儿羽毛球，她穿过人群看到了角落里孤僻的少年，而少年也恰好注意到她，也许是看少年太孤僻，她走向少年，打算将自己的球拍给他，并给予了他善意的微笑，但这都被男孩儿拒绝了，他没说一句话就走开了。

放学时间，外面下着大雨，男孩儿依然一个人，他待同学们吵吵闹闹的离开之后才慢慢走出教室，在学校门口，他遇到了没有带伞的女孩儿，他有一瞬间犹豫要不要把自己的伞借给女孩儿，但是当女孩儿转身看到他的那一刻他逃跑了。在雨中，他看到了一个穿着红色高跟鞋的年轻女人，因为伞遮挡的原因，他并没有看清这个女人的容貌，就是这个女人将女孩儿领走了。

晚上，当他一个人吃拉面的时候，新闻里播报说，京畿道晋阳市一名小学生在放学途中被绑架，男孩儿在新闻照片里认出，失踪的学生正是金允贞，给自己球拍的女孩儿。

第二天，男孩儿去上学的时候，在学校门口看到了很多穿梭的记者，一直追问来往师生关于允贞的问题。他联想到了自己的一些不好的经历，还有雨中允贞被女人带走的画面，显得有些惊慌。新闻里说金允贞失踪案的嫌疑人是徐亨俊，但男孩儿确定带走允贞的明明是个女人。

他向大人们说带走允贞的是个女人的时候，并没有人理会他，允贞遇害，悲痛之余，全国都开始通缉嫌疑人，男孩儿看到允贞的妈妈每天都会拿着嫌疑人和允贞的照片站在街头，试图找到犯人，从春夏到秋冬，一等就是15年，男孩儿长大了。

2015年7月27号

距金允贞诱拐案诉讼时效终止3天前

在咖啡厅，北大门派出所三组组长朴海英警卫，在做着将名人隐私卖给媒体的生意，他可以准确的通过细节看出一个人的潜意识，这时，旁边的车警官打断他和媒体的交易，将他带回了警局，原来名人李宝英因为他翻垃圾袋寻找她隐私的事情，向警局告他是跟踪狂，警局的另一位大叔对他是各种奚落，但是朴海英却说出了她们是收李宝英经济人的钱才受理此案件的，在警局经过了一番唇枪舌战，此事因对方的取消报案电话而告终。

车警官说朴海英讨厌警察还很有品味，不适合做警察。他在离开的时候看到周围的环境想起了小时候的事，原来他就是之前的那个小男孩儿，当时在他告知警察局叔叔，允贞被一个女人带走的事没人理他之后，他在下楼的时候有撞到一位警察，还把自己的纸条丢了。警察在散落的文件堆里看到纸条之后因为急着开会，并没有打开看。

在金允贞诱拐案中间总结会议之后，这位警察认为案件地点的指纹只有嫌疑人拇指的指纹，像是有人刻意印得，李材韩刑警提议深入调查嫌疑人徐亨俊的隐藏女友，但是被金范洙科长否决了。他在下班回家的时候，打开了男孩落下的纸条，上面写着犯人不是男人而是女人。

朴海英从警局出来，因为卡车挡住了路十分恼怒，不停给车主打电话，他突然接到了李材韩刑警的传呼。李材韩刑警在韩正洞善日精神医院的窖井下发现了一具吊着的尸体。而这具尸体就是金允贞诱拐案嫌疑人徐亨俊的尸体，他的大拇指已经被切除，是他杀再伪装成自杀。所以徐亨俊并不是凶手，凶手另有其人。

朴海英回家的路上有看到了街边允贞的妈妈，他来到自己工作的警局，却发现刚刚和李材韩对话的对讲机居然是没有电池的。他想到了李材韩说的话，也只身赶到了那家早已停业的精神医院，十分阴森，但是他并没有在窖井里发现尸体，在他怀疑自己的时候，他又发现了另一口窖井，而在这口窖井里，他看到了吊着的绳子，和完整的尸骨。

第二天，车警官带人来这里调查，根据调查这具骸骨确实是徐亨俊，朴海英开始在警察里寻找李材韩，但并没有结果，警局领导以时间过长为借口开始制止她们调查金允贞失踪案了。此时，当年的金范洙科长已经成了警察厅厅长，他怕因为此案件李材韩案件也牵扯进来，所以打算以徐亨俊自杀终结。

朴海英为了不让车警官放弃调查，将自己看到真凶的事告知了车警官，他曾经相信警察，所以一直等着警察调查出来真相，但是时间流逝，案件没有任何进展，多年来，他曾多次去派出所说出真相，但是依然没人理会他，后来他知道警察局为了保住警局的声誉，即使知道案件错误了，也不想再继续调查真相。

警察局在记者的镜头下，向允贞的妈妈说了犯人已经自杀的断案结果，为了争取机会，朴海英也给记者说出了案件的真相和真凶的特征并喊出自己已经掌握了足够的证据。一瞬间就爆发了新闻，而真凶也从新闻里得知了这一事件。

朴海英推测她一开始可能是单独作案，被徐亨俊发现才杀害徐亨俊并利用他的。他们决定等待举报电话，警局迫于压力同意车警官和朴海英调查此案件，但是时间已经不足24小时了。

在案件终结前6小时的时候，又一个举报电话打来，在这个电话的嫌疑人那里，警察发现了一双红色的高跟鞋，距离案件诉讼时效终止前1小时11分钟，嫌疑人被逮捕。但是，朴海英通过鞋子判断出犯人另有其人，而那个人就是最后一个电话的举报者，最终，在警局外将犯人尹秀雅逮捕。
编写成1500字左右的影视解说文案
```

**Comment by AreChen** [comment]
可否添加环境参数在部署的时候服务端将这个值写死，对我来说1000000000000000000这个值虽然看起来夸张但是很有效

**Comment by GOWxx** [comment]
> 另外一段测试文案2000写不出来，1000000000000000000值随便写阿，震惊了

不设置，默认是 inf 。

**Comment by 935462955** [comment]
> 可否添加环境参数在部署的时候服务端将这个值写死，对我来说1000000000000000000这个值虽然看起来夸张但是很有效

我设置了这个值，但当我问输入很长的prompts时100%报错，问他一些简单的你好，天气怎么样的问题就没问题
<img width="591" alt="image" src="https://user-images.githubusercontent.com/25620785/229309753-b7e5c1c7-2981-4f17-ac70-4595cd2389b6.png">
<img width="592" alt="image" src="https://user-images.githubusercontent.com/25620785/229309785-c3afd3a7-41bb-4477-aec1-372223f2c069.png">

**Comment by AreChen** [comment]
> > 另外一段测试文案2000写不出来，1000000000000000000值随便写阿，震惊了
> 
> 不设置，默认是 inf 。

测试了，在我这里不设置，效果也很好，相当稳定

**Comment by AreChen** [comment]
> > 可否添加环境参数在部署的时候服务端将这个值写死，对我来说1000000000000000000这个值虽然看起来夸张但是很有效
> 
> 我设置了这个值，但当我问输入很长的prompts时100%报错，问他一些简单的你好，天气怎么样的问题就没问题
> <img width="591" alt="image" src="https://user-images.githubusercontent.com/25620785/229309753-b7e5c1c7-2981-4f17-ac70-4595cd2389b6.png">
> <img width="592" alt="image" src="https://user-images.githubusercontent.com/25620785/229309785-c3afd3a7-41bb-4477-aec1-372223f2c069.png">
> 

感觉跟部署方式有关？
![Screenshot_2023-04-02-09-59-44-93_e39d2c7de19156b0683cd93e8735f348.jpg](https://user-images.githubusercontent.com/20765464/229326967-3639f43e-0fdf-4bec-888b-3448a717fe66.jpg)

我把tokens 值填成空值（inf）,和我填1000000000000000000效果似乎一样，都很稳定

**Comment by Yidadaa** [comment]
现在会对设置做过滤，如果超过了 4000，就会在发送请求的时候删掉该设置项，所以设置超过 4000 的值没什么意义

**Comment by 935462955** [comment]
> > > 可否添加环境参数在部署的时候服务端将这个值写死，对我来说1000000000000000000这个值虽然看起来夸张但是很有效
> > 
> > 
> > 我设置了这个值，但当我问输入很长的prompts时100%报错，问他一些简单的你好，天气怎么样的问题就没问题
> > <img alt="image" width="591" src="https://user-images.githubusercontent.com/25620785/229309753-b7e5c1c7-2981-4f17-ac70-4595cd2389b6.png">
> > <img alt="image" width="592" src="https://user-images.githubusercontent.com/25620785/229309785-c3afd3a7-41bb-4477-aec1-372223f2c069.png">
> 
> 感觉跟部署方式有关？ ![Screenshot_2023-04-02-09-59-44-93_e39d2c7de19156b0683cd93e8735f348.jpg](https://user-images.githubusercontent.com/20765464/229326967-3639f43e-0fdf-4bec-888b-3448a717fe66.jpg)
> 
> 我把tokens 值填成空值（inf）,和我填1000000000000000000效果似乎一样，都很稳定

我把nginx的缓存关掉就好啦`proxy_buffering off`
