### ISSUE TITLE
[Bug] systemPrompts not effective

### ISSUE THREAD

**Issue by lvguanjun** [Yidadaa/ChatGPT-Next-Web#3152]
**Describe the bug**
systemPrompts not effective, even if my enableInjectSystemPrompts is true

**To Reproduce**
1. F12 open console
2. Create new chat
3. Send message
4. Check network

**Expected behavior**
messages should have system prompt

**Screenshots**
messages not have system prompt, only user's message

**Deployment**
- [ ] Docker
- [ ] Vercel
- [x] Server

**Additional Logs**
maybe is this commit's bug, https://github.com/Yidadaa/ChatGPT-Next-Web/commit/d2d615c84a6a30879488528c4537e5a3ecaebca5, line 416 ` const systemPrompt = createMessage` use systemPrompt but not inject

**Comment by lvguanjun** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/58430934/f82ffe22-81f8-41ed-8ee7-2d5d81ad3085)

Changing the system prompt in this way has taken effect, but I'm not sure if this is the correct change. I don't know TypeScript, it's just the correction plan that copilot-chat taught me.

**Comment by H0llyW00dzZ** [comment]
latest commits : 1096fe55e12ee32aa3f575fcda593d2d3b701905
its correct

**Comment by H0llyW00dzZ** [comment]
here is another showcase of knowledge  :
![List of iPhone models discussed](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/96a0ed6e-9456-4adc-8617-e3e30db07157)


![List of iPhone models discussed (1)](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/95e2b4f8-3260-4f2f-a8f1-ea0f0586ba7c)

**Comment by lvguanjun** [comment]
> here is another showcase of knowledge : ![List of iPhone models discussed](https://user-images.githubusercontent.com/17626300/280976119-96a0ed6e-9456-4adc-8617-e3e30db07157.png)
> 
> ![List of iPhone models discussed (1)](https://user-images.githubusercontent.com/17626300/280976156-95e2b4f8-3260-4f2f-a8f1-ea0f0586ba7c.png)

Maybe there is something wrong with my expression. The problem I pointed out is that the system prompt information is not injected into the messages. You can open the console network to view the body.

What I expected was：
```json
messages = [{
"role": "system",
"content": "You are an AI"
},
{
"role": "user",
"content": "hello"
}
]
```

But what is actually sent is
```json
messages = [
{
"role": "user",
"content": "hello"
}
]
```

**Comment by H0llyW00dzZ** [comment]
if you want to use a custom injection system, you can create your own masks and untick this feature for disabled which is enabled by default : 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/9301971b-d63a-44c5-9465-4adea6dd09f0)

**Comment by lvguanjun** [comment]
Can you try creat new chat and not use mask, enble `Inject System Prompts`, then check your sent body
excepted bosy shoule like:
```json
messages = [
  {
    "role": "system",
    "content": "You are ChatGPT, a large language model trained by OpenAI.
Carefully heed the user's instructions.
Respond using Markdown.
Knowledge cutoff: {{knowledgeCutoff}}
Current model: {{model}}
Current time: {{time}}"
  },
  {
    "role": "user",
    "content": "hello"
  }
]
```

**Comment by lvguanjun** [comment]
I'm not sure if the **system prompt** is sent when I use mask, but your test is incorrect, in this case you should be asking `who are you` or other instead of asking it with something close to the prompt word, Even if you don't provide any **system prompt**, your current question may still get the expected answer.

**Comment by H0llyW00dzZ** [comment]
lmao how is it incorrect ? you can see in console its legit changing date for a specific model such as newer models

![Screenshot_359](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/f526474c-d5c0-4eb0-ab22-f32b217e6732)
![Screenshot_360](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/c6f0c847-e09f-44cf-855e-d87650fa42f4)

**Comment by lvguanjun** [comment]
not console.log, you log it, but network is not send, and i will give you photo

**Comment by lvguanjun** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/58430934/00994fb6-a5c4-4aef-a0a2-dd604ce8194a)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/58430934/24ab7c1c-16ce-49a3-aa2f-6c6938d72b2c)

**Comment by lvguanjun** [comment]
If you check the submitted code, you can clearly see that `systemPrompt` is not used, instead `systemPrompts` (more one s) is used, of course I'm not sure if there is any other way to use it, I don't know TypeScrpit

**Comment by H0llyW00dzZ** [comment]
its used but not put in that (clearly hidden)

**Comment by H0llyW00dzZ** [comment]
here is another showcase 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/5e231f47-26b2-4078-81d0-dea93bf5a45b)

**Comment by lvguanjun** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/58430934/f9301e10-3c3a-4ea2-93e1-d475e53fbfb7)

**Comment by H0llyW00dzZ** [comment]
if you ask to ai like that it will be hallucination

**Comment by lvguanjun** [comment]
not, your sent body lost system prompt, so why you init system prompt, and add Knowledge cutoff, current model, current time, if this just console log but not send?

**Comment by H0llyW00dzZ** [comment]
its send but it's not showing in that history network because clearly hidden

**Comment by lvguanjun** [comment]
this is correct? `enableInjectSystemPrompts` Does this option make sense? and in terms of network requests, the actual request body sent does not have a system prompt, and is not hidden as you may think.

**Comment by H0llyW00dzZ** [comment]
to make sure that you still not believe 
you can put a logger in server-side then see how it goes in the wilds

**Comment by lvguanjun** [comment]
Assume that the system prompt built into our code is something else such as github copilot chat. Do you think this system prompt will take effect when it has not been sent?

ok, i will change the system prompt built into our code, and give you photo

**Comment by H0llyW00dzZ** [comment]
how about this ? I am interpreting without github copilot or anything hahaha

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/f044d3e0-463e-4378-8b37-ffde4709c2b9)

**Comment by lvguanjun** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/58430934/52101250-1d74-4833-a344-ea045f82f157)

i can answer any question even if my global system prompt is github copilot chat's prompt

**Comment by lvguanjun** [comment]
my mead is your global system prompt not take effect, not mask or other

**Comment by H0llyW00dzZ** [comment]
its does take effect like what I said if you still not believe 
try put a logger in server-side mode then see how it goes in the wilds

**Comment by lvguanjun** [comment]
ok, you are right, I don't want to argue with you anymore, you just did the test according to your idea, or asked me to do the test. Even if I did it, you didn't interpret it. I hope that when this issue is fixed, this issue will be linked.

**Comment by H0llyW00dzZ** [comment]
also how it work in this code if you are not understand that typescript

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/b9e6916b-b919-48fe-ae81-761d6a1564f1)


the code is only changing date of time for a new models otherwise it keep like old/default by @Yidadaa

**Comment by lvguanjun** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/58430934/78127ea8-251c-49a2-875f-5d6674115bda)
if you check your files change, you can find you set `systemPrompts` (have s) is `[]`, and set `systemPrompt` (not have s) message;
but last code, when `enableInjectSystemPrompts` is true, the `systemPrompts` (have s) set message

**Comment by lvguanjun** [comment]
> ![image](https://user-images.githubusercontent.com/58430934/280957623-f82ffe22-81f8-41ed-8ee7-2d5d81ad3085.png)
> 
> Changing the system prompt in this way has taken effect, but I'm not sure if this is the correct change. I don't know TypeScript, it's just the correction plan that copilot-chat taught me.

Why not take a look at other people’s code tips?

**Comment by H0llyW00dzZ** [comment]
wait hold on

**Comment by H0llyW00dzZ** [comment]
check tbh a response its still same 
https://github.com/Yidadaa/ChatGPT-Next-Web/pull/3157

**Comment by lvguanjun** [comment]
> check tbh a response its still same

I'm not sure if this is the correct change. I don't know TypeScript

**Comment by H0llyW00dzZ** [comment]
@lvguanjun its correct
from your code/commits it just stored a system inject system prompts
latest models :
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/54692bc5-8239-4522-8127-37ff96d020f2)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/ca24cb01-3564-4846-9ac9-897f014f5de4)

**Comment by H0llyW00dzZ** [comment]
additional note
its still same even without inject system prompt "nothing about bug effective or not"

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/d7e567bd-d0ef-4e44-8a8f-90ce08b69a5c)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/c6cb7e42-ac9c-4717-8f0c-f0a32752b2e3)
