### ISSUE TITLE
gpt-4-vision-preview这个模式下，请增加上传图片的功能

### ISSUE THREAD

**Issue by afredzhou** [Yidadaa/ChatGPT-Next-Web#3153]
GPT-4 with Vision, sometimes referred to as [GPT-4V](https://openai.com/research/gpt-4v-system-card) or gpt-4-vision-preview in the API, allows the model to take in images and answer questions about them. Historically, language model systems have been limited by taking in a single input modality, text. For many use cases, this constrained the areas where models like GPT-4 could be used。

选择了这个模型，无法上传图片

**Comment by luoxiaofeng1029** [comment]
附议

**Comment by LJunius** [comment]
顶一顶

**Comment by coffee-guy** [comment]
顶一手

**Comment by ag471782517** [comment]
顶一顶，该更新了，大佬！

**Comment by leslie2046** [comment]
+1

**Comment by 7738373** [comment]
顶顶

**Comment by sudusuperman** [comment]
This project is so neat, I believe the developer will add this function very soon.
Looking forward!!!

**Comment by xingstarx** [comment]
hhh, 这是要把开发者累坏的节奏呀😂

**Comment by Yidadaa** [comment]
#3110

**Comment by vual** [comment]
我这边实现了gpt4-vision-preview识图功能，可以了解下。
https://github.com/vual/ChatGPT-Next-Web-Pro
