### ISSUE TITLE
[Bug] 当代理地址具有端口号的时候，不能正确解析 

### ISSUE THREAD

**Issue by licesun** [Yidadaa/ChatGPT-Next-Web#3159]
**Describe the bug**
当代理地址具有端口号的时候，不能正确解析 

**To Reproduce**
设定BASE_URL 为 www.sample.com:3000
进行对话，提示501.
改成 www.sample.com。 就可以进行对话了

**Expected behavior**
正确进行对话

**Deployment**
- [ ] Docker
- [ √] Vercel
- [ ] Server

**Comment by zdaiot** [comment]
@Yidadaa 您好，仍然存在这个问题？这个已经解决了么？

**Comment by Fog3719** [comment]
still have this problem
