### ISSUE TITLE
[Bug] max_token 无效

### ISSUE THREAD

**Issue by d0j1a1701** [Yidadaa/ChatGPT-Next-Web#3164]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我的代理商（https://aiproxy.io）会在发送请求时冻结积分（代理商账号的余额），若传入 max_token，则按照 max_token 冻结，否则按照模型最大上下文长度冻结。然而发现始终按照最大长度冻结，查询日志发现 ChatGPT-Next-Web 没有传入 max_token。

**如何复现**
设置 max_token，查看 api 日志

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：Windows 11
 - 浏览器： Edge
 - 版本： 2.9.9
 - 部署方式：Vercel

**Comment by Yidadaa** [comment]
传入 `max_token` 会引起不必要的报错，大多数情况下都没有必要传入。

**Comment by d0j1a1701** [comment]
> 传入 `max_token` 会引起不必要的报错，大多数情况下都没有必要传入。

我注意到设置里是有这个选项的。如果我确实需要传入，应该如何修改代码？
