### ISSUE TITLE
[Bug] gpt-4-vision-preview无法显示完整对话

### ISSUE THREAD

**Issue by lcjhcc** [Yidadaa/ChatGPT-Next-Web#3168]
版本：v2.9.10（使用Docker运行，直接暴露端口访问） 
问题：如图，使用gpt-4-vision-preview模型无法正常显示完整的对话，gpt-4-1106-preview模型显示正常
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/39474554/f875afd1-3268-4ad8-bcf2-cfc1bbe4eba2)

**Comment by leslie2046** [comment]
我是也这样

**Comment by wkunzhi** [comment]
me too

**Comment by Soonze** [comment]
+1

**Comment by unliu** [comment]
+1

**Comment by batch-norm** [comment]
+1

**Comment by H0llyW00dzZ** [comment]
I know this issue
this models required max_tokens which it might break a system client LLM API in latest version

**Comment by l0veshe** [comment]
+1

**Comment by Yidadaa** [comment]
#3110
