### ISSUE TITLE
修改BASE_URL后账户余额显示问号

### ISSUE THREAD

**Issue by huwan** [Yidadaa/ChatGPT-Next-Web#317]
如图所示，使用Vercel部署的，修改了BASE_URL后账户余额显示问号。对话功能都正常。去掉BASE_URL设置后重新部署又会“正常”显示（指显示为0）。 
<img width="657" alt="Jietu20230401-170531" src="https://user-images.githubusercontent.com/1451009/229277346-a82bc388-dbb9-4559-90fd-bf8cb0870798.png">

**Comment by Yidadaa** [comment]
请确认是否对查询余额的接口做了代理。
