### ISSUE TITLE
手动设置代理

### ISSUE THREAD

**Issue by changzhongxinxin** [Yidadaa/ChatGPT-Next-Web#3173]
用这个项目要翻墙，但是电脑上翻墙软件会在后台一直运行，但不一定打开系统代理，希望加入手动设置代理的开关
![de67bf3389c4be5fd419402289897d40](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/68383493/aad020d9-4331-4259-89ae-e56c0f8b8af1)

**Comment by Yidadaa** [comment]
不支持设置传统的代理。
