### ISSUE TITLE
[Bug] 移动端，点击删除聊天，不会弹窗，需要切换到其它页面才会弹窗提示是否删除。

### ISSUE THREAD

**Issue by vual** [Yidadaa/ChatGPT-Next-Web#3174]
[Bug] 移动端，点击删除聊天，不会弹窗，需要切换到其它页面才会弹窗提示是否删除。

**Comment by 327078466** [comment]
微信小程序版的有啦 搜GF聊天

**Comment by vual** [comment]
@Yidadaa 我更新了，没修复啊。

**Comment by Yidadaa** [comment]
提供一下录屏，版本号，部署方式。

**Comment by vual** [comment]
> 提供一下录屏，版本号，部署方式。
是我改了个z-index问题。现在好了。

**Comment by vual** [comment]
> 提供一下录屏，版本号，部署方式。

是我改了个z-index问题。现在好了。
