### ISSUE TITLE
[Feature] 关于上传图片和文件的 UI 建议

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#3176]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
、

**你想要什么功能或者有什么建议？**
关于 GPT-4 V 的图片上传，可以在这里设置一排显示 UI（可以增加一个展开/折叠按钮，这样不遮挡对话区域），对话内上传过的图片都在这里显示缩略图，支持点击每张缩略图放大查看，且在查看大图片的时候：①：可以定位到此图片的位置（类似 Telegram 中的消息定位）②：有左右按钮可以直接切换图片（类似 Telegram 中的左右图片切换）。当定位到某一张历史图片时，可以通过操作按钮重新对此图片进行询问。对话内只支持针对单张历史图片进行分析，如果携带过多历史图片的话，实在太费钱了。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48620527/cec671d4-794c-416d-88cf-7f26d7ed5c5e)
助理 API 的上传文件也可以这样，但是文件就可以支持多文件分析，毕竟有这样的实际需求。

仅提供一个思路，哈哈

**有没有可以参考的同类竞品？**
、

**其他信息**
、

**Comment by Yidadaa** [comment]
好的，我还在构思。
