### ISSUE TITLE
[Bug] the Latex format mathematical formulas cannot be displayed properly.

### ISSUE THREAD

**Issue by DouiKo** [Yidadaa/ChatGPT-Next-Web#3178]
**Describe the bug**
Since a certain version update, the Latex format mathematical formulas cannot be displayed properly.

**To Reproduce**
For example: Please output the probability density function of the Gaussian distribution in Latex format.
Respond: [ f(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \cdot e^{-\frac{(x-\mu)^2}{2\sigma^2}} ]

....
**Screenshots**
<img width="916" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/36651688/f00a8d66-a9bb-48e9-86c4-b219aed82e28">

**Deployment**
- [x] Vercel

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [safari]

**Comment by Yidadaa** [comment]
加上提示词：用 $ 包裹所有数学符号。

**Comment by DouiKo** [comment]
测试方法可行。但是大约3天前，我在交流中还不需要提示使用$包裹数学符号。请问这是否是某次NextWeb项目更新的特性？

**Comment by Yidadaa** [comment]
@DouiKo openai 模型更新导致的性能降级。
