### ISSUE TITLE
 [Bug] GPT一直回复 [object Object]

### ISSUE THREAD

**Issue by RyanLookchard** [Yidadaa/ChatGPT-Next-Web#3179]
今天问了几个问题之后，GPT回复一直是[object Object]

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/34979814/9f43f24f-53cd-4235-8f58-5e2d005e4172)

**Comment by louyongjiu** [comment]
+1

**Comment by bahuzh** [comment]
不是2.9.10吗？

**Comment by lqdflying** [comment]
2.9.10 +1

**Comment by RyanLookchard** [comment]
> 不是2.9.10吗？

我拉docker的latest镜像是2.9.9

**Comment by ventusff** [comment]
2.9.10 +1

**Comment by lrannn** [comment]
Me too

**Comment by moondie** [comment]
我也是

**Comment by vbskycn** [comment]
2.9.10 +1

**Comment by bahuzh** [comment]
我换到2.9.8一样，切换了不同终端

**Comment by wuyuw** [comment]
一样的问题

**Comment by xmrmt** [comment]
+1

**Comment by Spellzzy** [comment]
Same problem +1

**Comment by 7738373** [comment]
+1

**Comment by chen2438** [comment]
+1

**Comment by fdgdssds** [comment]
+1BUG

**Comment by TwoOnefour** [comment]
Same problem :(

**Comment by Tarryhao** [comment]
我也是

**Comment by Tarryhao** [comment]
早上是可以的，大约11点过后就出错了

**Comment by ventusff** [comment]
The service status of OpenAI's API is abnormal now. Let's wait for the official team to fix this.

https://status.openai.com/incidents/462433f2fk2j

**Comment by covered0000** [comment]
+1

**Comment by ZZz433** [comment]
+1

**Comment by z499738316** [comment]
+1

**Comment by richard-fu-1007** [comment]
+1

**Comment by SpencerLaw** [comment]
+1

**Comment by muzi-admin** [comment]
我刚才试着可以啦

**Comment by SpencerLaw** [comment]
> 我刚才试着可以啦

还是不行啊

**Comment by Tarryhao** [comment]
<img width="975" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11739828/1f53d9b9-4f96-479b-b6c2-d77a72d96250">
openAI的服务还是没有恢复完全

**Comment by l1angfeng** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/33654458/2912f5b4-b31b-45a8-bd75-638cd8efbf6f)
修复了，各位可以了吗

**Comment by RyanLookchard** [comment]
> ![image](https://user-images.githubusercontent.com/33654458/281284428-2912f5b4-b31b-45a8-bd75-638cd8efbf6f.png) 修复了，各位可以了吗

刚试了 还是不行

**Comment by ZZz433** [comment]
我更新了也还是不行

**Comment by ClarenceDan** [comment]
可能是因为直连反代挂了，因为今天早些时候 api.openai.com 套了一层cf，导致反代会出现 429或者418错误，返回结果为 {}，在Next-Web上就会变成Object，目前暂时的解决方案是在设置中替换 /api/openai/ 为: https://api.openai.com/

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48417261/f5929512-ea1e-4615-a3d6-e06fb78f8ea8)

**Comment by PEKEW** [comment]
> 可能是因为直连反代挂了，因为今天早些时候 api.openai.com 套了一层cf，导致反代会出现 429或者418错误，返回结果为 {}，在Next-Web上就会变成Object，目前暂时的解决方案是在设置中替换 /api/openai/ 为: https://api.openai.com/
> 
> ![image](https://user-images.githubusercontent.com/48417261/281285448-f5929512-ea1e-4615-a3d6-e06fb78f8ea8.png)

替换https://api.openai.com/后提示密码或者apikey不正确，已确认没有填错

**Comment by Tarryhao** [comment]
我这就是默认的https://api.openai.com/ 也是报429错误
<img width="1118" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11739828/8e47d835-175d-46c0-94ec-a6e0669dff67">

**Comment by RyanLookchard** [comment]
> > 可能是因为直连反代挂了，因为今天早些时候 api.openai.com 套了一层cf，导致反代会出现 429或者418错误，返回结果为 {}，在Next-Web上就会变成Object，目前暂时的解决方案是在设置中替换 /api/openai/ 为: https://api.openai.com/
> > ![image](https://user-images.githubusercontent.com/48417261/281285448-f5929512-ea1e-4615-a3d6-e06fb78f8ea8.png)
> 
> 替换https://api.openai.com/ 后提示密码或者apikey不正确，已确认没有填错

替换了之后, 登陆密码就不能用了，必须要输入api key

**Comment by ZZz433** [comment]
换了https://api.openai.com/，还得把api复制进去才能用，不能用那个密码

**Comment by linwentao-hexin** [comment]
+1

**Comment by gaboolic** [comment]
+1

**Comment by SpencerLaw** [comment]
> 换了[https://api.openai.com/，还得把api复制进去才能用，不能用那个密码](https://api.openai.com/%EF%BC%8C%E8%BF%98%E5%BE%97%E6%8A%8Aapi%E5%A4%8D%E5%88%B6%E8%BF%9B%E5%8E%BB%E6%89%8D%E8%83%BD%E7%94%A8%EF%BC%8C%E4%B8%8D%E8%83%BD%E7%94%A8%E9%82%A3%E4%B8%AA%E5%AF%86%E7%A0%81)

是的 求解决方式

**Comment by ClarenceDan** [comment]
这是最难崩的，catgpt上线：
![c2eb6f05e308853db9f2984496f1782](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48417261/4089b839-af08-42d6-9a2f-03891f30984e)

**Comment by gusizhu** [comment]
Meow,I am a Teapot

**Comment by s3xysteak** [comment]
Meow, I am a Teapot

**Comment by starsead** [comment]
help，I have the same issue as well，I use cf as reverse proxy

**Comment by suoaao** [comment]
https://github.com/suoaao/affordable-openai

可以尝试自己反向代理一次，目前还可以用

**Comment by blkot** [comment]
> 换了[https://api.openai.com/，还得把api复制进去才能用，不能用那个密码](https://api.openai.com/%EF%BC%8C%E8%BF%98%E5%BE%97%E6%8A%8Aapi%E5%A4%8D%E5%88%B6%E8%BF%9B%E5%8E%BB%E6%89%8D%E8%83%BD%E7%94%A8%EF%BC%8C%E4%B8%8D%E8%83%BD%E7%94%A8%E9%82%A3%E4%B8%AA%E5%AF%86%E7%A0%81)

this works even for 2.9.5

**Comment by fdgdssds** [comment]
> https://github.com/suoaao/affordable-openai
> 
> 可以尝试自己一次反向代理，目前还可以用

具体怎么用呢？

**Comment by 327078466** [comment]
微信小程序版的有啦 搜GF聊天

**Comment by TwoOnefour** [comment]
> 微信小程序版的有啦 搜GF聊天

谁问你了

**Comment by cnchef** [comment]
+1 好了没

**Comment by CA-GPT** [comment]
+1

**Comment by Bazinga-Wang** [comment]
+1

**Comment by Tarryhao** [comment]
主分支有bug，会显示[object Object]，log里的请求报429错误。但是[remark-breaks]分支生成的程序是正常的：
<img width="914" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/11739828/7c264e38-ce55-468e-9000-1e69587d20ef">

**Comment by bahuzh** [comment]
恢复了，清理下浏览器缓存，再试试

**Comment by Tarryhao** [comment]
已恢复

**Comment by cnchef** [comment]
Suddenly it's getting better again, it's strange! 2.9.3版本一值正常的

**Comment by WangShuo2000** [comment]
Restored

**Comment by Tan35** [comment]
已恢复！

**Comment by H0llyW00dzZ** [comment]
works fine

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/db4b8a69-b169-4fdf-ae99-c8f59a3abd28)

**Comment by Yidadaa** [comment]
OpenAI 接口侧的问题，目前已经恢复。
