### ISSUE TITLE
[Feature] 在对话页内增加月api用量展示 和会话内token使用统计

### ISSUE THREAD

**Issue by burpheart** [Yidadaa/ChatGPT-Next-Web#3184]
使用GPT4时很容易造成高额账单。为了帮助用户控制使用量和了解单次会话的价格，建议在客户端内添加以下功能

用量展示：在对话页内增加一个显示月度API用量的功能，让用户可以随时了解他们已经使用的API用量。
会话统计：在会话中统计双向token的使用情况，让用户可以清楚地了解每个会话的用量情况。
使用量预测：在点击发送按钮之前，通过token分词器计算token数量 提示用户当前使用模型的用量和预计价格。
这些功能将帮助用户更好地管理他们的API用量，避免产生意外的高额账单。

**有没有可以参考的同类竞品？**
https://platform.openai.com/tokenizer
https://github.com/openai/tiktoken
https://www.npmjs.com/package/tiktoken
**其他信息**
请考虑将这些功能添加到gpt4客户端中，以提高用户体验和控制成本的能力。

**Comment by Yidadaa** [comment]
没必要，官方都不让你查了，加它干啥。

**Comment by burpheart** [comment]
但是单次对话使用的token还是可以统计的

**Comment by burpheart** [comment]
> 没必要，官方都不让你查了，加它干啥。

但是单次对话内使用的token还是可以统计的 也可以统计出月使用量
