### ISSUE TITLE
如何手动修改代码添加更多的预置模型？

### ISSUE THREAD

**Issue by itq5** [Yidadaa/ChatGPT-Next-Web#3187]
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
如何手动修改代码添加更多的预置模型？

**截图**

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/42521985/3e38981c-b21c-4306-886d-8f322573c985)

**Comment by H0llyW00dzZ** [comment]
models :
[`constant.ts`](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/constant.ts)
payload : 
[`openai.ts`](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts)

**Comment by itq5** [comment]
n

> models : [`constant.ts`](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/constant.ts) payload : [`openai.ts`](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts)

能具体点吗？感谢！

**Comment by H0llyW00dzZ** [comment]
Here is a quick tutorial

example like this 

[`constant.ts`](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/constant.ts) : 
```ts
export const DEFAULT_MODELS = [
  {
    name: "gpt-4",
    available: true,
  },
  {
    name: "gpt-4-0314",
    available: true,
  },
  {
    name: "gpt-4-0613",
    available: true,
  },
  {
    name: "gpt-4-32k",
    available: true,
  },
  {
    name: "gpt-4-32k-0314",
    available: true,
  },
  {
    name: "gpt-4-32k-0613",
    available: true,
  },
  {
    name: "gpt-4-1106-preview",
    available: true,
  },
  {
    name: "gpt-4-vision-preview",
    available: true,
  },
  {
    name: "gpt-3.5-turbo",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-0301",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-0613",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-1106",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-16k",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-16k-0613",
    available: true,
  },
] as const;
```
if you want add other models 
replace a [`constant.ts`](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/constant.ts) like this : 
```ts
export const DEFAULT_MODELS = [
  {
    name: "gpt-4",
    available: true,
  },
  {
    name: "gpt-4-0314",
    available: true,
  },
  {
    name: "gpt-4-0613",
    available: true,
  },
  {
    name: "gpt-4-32k",
    available: true,
  },
  {
    name: "gpt-4-32k-0314",
    available: true,
  },
  {
    name: "gpt-4-32k-0613",
    available: true,
  },
  {
    name: "gpt-4-1106-preview",
    available: true,
  },
  {
    name: "gpt-4-vision-preview",
    available: true,
  },
  {
    name: "gpt-3.5-turbo",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-0301",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-0613",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-1106",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-16k",
    available: true,
  },
  {
    name: "gpt-3.5-turbo-16k-0613",
    available: true,
  },
// add models
  {
    name: "H0llyW00dzZ-1337-turbo-1337k-1337",
    available: true,
  },
] as const;
```

then in [`openai.ts`](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts) if the models required `max_tokens`

[`openai.ts`](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts) : 
```ts
    const requestPayload = {
      messages,
      stream: options.config.stream,
      model: modelConfig.model,
      temperature: modelConfig.temperature,
      presence_penalty: modelConfig.presence_penalty,
      frequency_penalty: modelConfig.frequency_penalty,
      top_p: modelConfig.top_p,
    };
```
replace by this the payloads : 
```ts
    const requestPayload = {
       messages,
       stream: options.config.stream,
       model: modelConfig.model,
       temperature: modelConfig.temperature,
       presence_penalty: modelConfig.presence_penalty,
       frequency_penalty: modelConfig.frequency_penalty,
       top_p: modelConfig.top_p,
       // new models is insane
       // model "H0llyW00dzZ-1337-turbo-1337k-1337" required this max_tokens and max is 1337
       max_tokens: modelConfig.model.includes("H0llyW00dzZ-1337-turbo-1337k-1337") ? modelConfig.max_tokens : undefined,
   };
   ```

**Comment by Yidadaa** [comment]
[CUSTOM_MODELS （可选）](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#custom_models-%E5%8F%AF%E9%80%89)
示例：+qwen-7b-chat,+glm-6b,-gpt-3.5-turbo 表示增加 qwen-7b-chat 和 glm-6b 到模型列表，而从列表中删除 gpt-3.5-turbo。

用来控制模型列表，使用 + 增加一个模型，使用 - 来隐藏一个模型，用英文逗号隔开。

**Comment by EchoShoot** [comment]
> [CUSTOM_MODELS （可选）](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#custom_models-%E5%8F%AF%E9%80%89) 示例：+qwen-7b-chat,+glm-6b,-gpt-3.5-turbo 表示增加 qwen-7b-chat 和 glm-6b 到模型列表，而从列表中删除 gpt-3.5-turbo。
> 
> 用来控制模型列表，使用 + 增加一个模型，使用 - 来隐藏一个模型，用英文逗号隔开。

docker 版好像用不了？是没更新的缘故吗？

**Comment by xmokay** [comment]
> > [CUSTOM_MODELS （可选）](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#custom_models-%E5%8F%AF%E9%80%89) 示例：+qwen-7b-chat,+glm-6b,-gpt-3.5-turbo 表示增加 qwen-7b-chat 和 glm-6b 到模型列表，而从列表中删除 gpt-3.5-turbo。
> > 用来控制模型列表，使用 + 增加一个模型，使用 - 来隐藏一个模型，用英文逗号隔开。
> 
> docker 版好像用不了？是没更新的缘故吗？

能用，效果不是从列表删除。而是相关选项被disable掉，不能选
