### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nnvvff** [Yidadaa/ChatGPT-Next-Web#3188]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
vercel 换了一个api之后进行redeploy失败，如图片所示

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**

![Uploading 20231108215752.png…]()
![20231108215757](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/135152323/85732e28-2570-4770-b7f3-07db9fae028f)
![20231108215801](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/135152323/c8c7ba1b-7e52-4678-97c1-c173804413a6)

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by nnvvff** [comment]
![20231108215752](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/135152323/20461c55-f06d-418d-8832-dc7af58ccab6)
![20231108215757](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/135152323/3e7fc359-70c9-4bf2-bf93-f81f40a5e176)
![20231108215801](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/135152323/3abfd9da-66d7-4da1-8b15-4c17d30a4d52)

**Comment by H0llyW00dzZ** [comment]
don't upgrade package

**Comment by Yidadaa** [comment]
删除 vercel 项目重新部署。
