### ISSUE TITLE
[Bug] 导出图片渲染时文字符号不对

### ISSUE THREAD

**Issue by bonuschild** [Yidadaa/ChatGPT-Next-Web#3189]
目前发现是数学公式，比如x^3，在对话窗口时正常看到上标3的，但是导出为图片时只能看到x，上标3没有，一度以为是输出错了，结果发现是渲染问题。个人感觉是否是可以优先bugfix？主要是容易造成误解，前后不一致，谢谢！

**Comment by H0llyW00dzZ** [comment]
are you exporting it as picture in web ver or client app ver ?

**Comment by bonuschild** [comment]
@H0llyW00dzZ I encounter this problem when I export it as picture in WEB v2.9.9 😄

**Comment by bonuschild** [comment]
@H0llyW00dzZ Is that fixed on newer version? I save 2.9.10 and 2.9.11 has been released

**Comment by H0llyW00dzZ** [comment]
@bonuschild [change logs](https://github.com/Yidadaa/ChatGPT-Next-Web/compare/v2.9.10...v2.9.11)
