### ISSUE TITLE
Error failed to get cargo metadata: Bad CPU type in executable (os error 86)

### ISSUE THREAD

**Issue by DaniEnsi** [Yidadaa/ChatGPT-Next-Web#3194]
When running `yarn app:build` it always returns `Error failed to get cargo metadata: Bad CPU type in executable (os error 86)`

I have rosetta installed and tried force launching terminal with rosetta, but it still returned the same error... I am running M2 Max and cant find a solution anywhere. They all say to install rosetta and that fixes the issue...

**Comment by DaniEnsi** [comment]
<img width="905" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/74594229/ef9cf66e-0b6d-48ce-a291-060952c4ed79">

**Comment by DaniEnsi** [comment]
<img width="949" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/74594229/a9e06587-5abb-4787-bdce-7ff650492fe2">

**Comment by Yidadaa** [comment]
https://stackoverflow.com/questions/68570065/cause-error-86-bad-cpu-type-in-executable-m1-macbook-android-studio

**Comment by DaniEnsi** [comment]
@Yidadaa I already looked at that article, I have installed rosetta restarted, and everything mentioned in that article... It still doesnt work...
