### ISSUE TITLE
[Bug] max_token is too large

### ISSUE THREAD

**Issue by Algorithm5838** [Yidadaa/ChatGPT-Next-Web#3195]
**Describe the bug**
When I used the new `gpt-3.5-turbo-1106` model with the updated default max_token value of `8192`, I just sent "Hello", I encountered the following error:
```
{
  "error": {
    "message": "max_tokens is too large: 8192. This model supports at most 4096 completion tokens, whereas you provided 8192.",
    "type": "invalid_request_error",
    "param": "max_tokens",
    "code": null
  }
}
```
Which is strange because the new model should support 16k. The same thing happens with `gpt-4-1106-preview`. However, when I use the older version `gpt-3.5-turbo-16k`, it works flawlessly without any errors. But when I use `gpt-4`, I just sent "Hello", I get this error:
```
{
  "error": {
    "message": "This model's maximum context length is 8192 tokens. However, you requested 8256 tokens (64 in the messages, 8192 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
```

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by cutejun** [comment]
+1

**Comment by xiangmingwu** [comment]
+1

**Comment by pmao-guess** [comment]
same problem ， any one can help

**Comment by Yidadaa** [comment]
fixed

**Comment by Algorithm5838** [comment]
Please check the discussion https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/3208.
