### ISSUE TITLE
想请教一下项目的入口是哪个文件

### ISSUE THREAD

**Issue by bigshezhang** [Yidadaa/ChatGPT-Next-Web#32]
本人才疏学浅，看您写的代码框架应该是基于 React，但是我找不到它的入口文件（index.js之类的），烦请作者指教。
另附：作者您画的界面真的好看！请问您是 UI 设计师吗，请问您一般在什么地方浏览最新的视觉设计，还有我应该如何描述您当前构建的页面风格，是否有一个可以概括的词呢？
辛苦您！

**Comment by Yidadaa** [comment]
框架是 nextjs，主入口是 layout.tsx，页面入口是 page.tsx，整个 app 的主要功能都在 home.tsx 里。

我自己不是 UI 设计师，通常会在 dribble 上找灵感，页面风格没有固定的描述词，看灵感吧，核心思路就是圆角和阴影一把梭，其他的交给直觉。
