### ISSUE TITLE
出错了，稍后重试吧

### ISSUE THREAD

**Issue by dengnaitian** [Yidadaa/ChatGPT-Next-Web#320]
后台日志提示 [POST] /api/chat-stream reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true

**Comment by dengnaitian** [comment]
原因是key无余额了

**Comment by danzhewuju** [comment]
> 后台日志提示 [POST] /api/chat-stream reason=EDGE_FUNCTION_INVOCATION_TIMEOUT, status=504, user_error=true

这个日志在哪看呢？

**Comment by dengnaitian** [comment]
在部署的服务器log日志区
