### ISSUE TITLE
[Bug] max_tokens not working as expected 

### ISSUE THREAD

**Issue by yasu1209** [Yidadaa/ChatGPT-Next-Web#3202]
**Describe the bug**
In the recent code, max_tokens is added into the request payload.
The original value is 8192, and if i use this value, only if i just send "hello", i would get a response like 
```
{"messages":[{"role":"system","content":"你是一个助手 新的聊天"},{"role":"user","content":"hello"},{"role":"assistant","content":"\n\n```json\n{\n  \"error\": {\n    \"message\": \"This model's maximum context length is 4097 tokens. However, you requested 8259 tokens (67 in the messages, 8192 in the completion). Please reduce the length of the messages or completion.\",\n    \"type\": \"invalid_request_error\",\n    \"param\": \"messages\",\n    \"code\": \"context_length_exceeded\"\n  }\n}\n```"}]}
```

request payload is like
```
{
  "messages": [
    {
      "role": "system",
      "content": "\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2023/11/9 16:36:26\n\n"
    },
    {
      "role": "user",
      "content": "hello"
    }
  ],
  "stream": true,
  "model": "gpt-3.5-turbo",
  "temperature": 0.5,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "top_p": 1,
  "max_tokens": 8192
}
```

It seems that max_tokens is not used as a limitation check, but treated as the current length of completion.

It works when i set max_tokens to a smaller value, but it would occupy part of the actual length of completion.
If I set it to 4000, and openai api has a limitation of 8000 tokens, then i can only send 4000 tokens for my completion.

**Expected behavior**
I think max_tokens is only a limitation for checking the length of completion, not used for calculation.
Or does openai api use it for the wrong behavior?

**Deployment**
- [ ] Docker
- [Y] Vercel
- [ ] Server

**Comment by Yidadaa** [comment]
This is the default behavior of OpenAI

**Comment by yasu1209** [comment]
@Yidadaa 
Thank you for your reply.
I checked the document.
but i cannot understand what it means.
[The token count of your prompt **plus** max_tokens]
It seemt to be an extra part of the prompt. so what does it really mean?
And why shouldn't we just keep the default value as 16?

```
max_tokens
integer or null
Optional
Defaults to 16
The maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the completion.

The token count of your prompt plus max_tokens cannot exceed the model's context length. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens.
```
