### ISSUE TITLE
优化建议（停止按钮&自动滚动）

### ISSUE THREAD

**Issue by Dogtiti** [Yidadaa/ChatGPT-Next-Web#321]
* 停止按钮的位置可以考虑换个位置，现在跟着文本框移动，有时想立即停止点不到，可以参考chatgpt官网放到最下面
* 输出内容时支持主动打断自动滚动，有时想让他静默输出并翻看上方内容，现在体验很不好，只能等他输出完或者主动停止输出

**Comment by Dogtiti** [comment]
@Yidadaa 可以讨论一下

**Comment by yuntian123456** [comment]
是的，表示赞同。

**Comment by yanglyu902** [comment]
+1, echo一下 https://github.com/Yidadaa/ChatGPT-Next-Web/issues/118#issue-1644834717
