### ISSUE TITLE
[Bug] An error is reported after clicking Settings

### ISSUE THREAD

**Issue by by123456by** [Yidadaa/ChatGPT-Next-Web#3211]
**Describe the bug**
Error reported after clicking on settings

**Expected behavior**
Open Settings
**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/15666692/5045981d-5f18-42d8-b5bc-42a25dabd6a0)

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - win7
 - edge
 - 

**Additional Logs**
Add any logs about the problem here.

**Comment by MCheping8108** [comment]
Please update your browser to the latest version

**Comment by MCheping8108** [comment]
> Please update your browser to the latest version

Also, Windows 7 is a gradually outdated operating system, chrome may not be upgraded to the latest version, it is recommended that you update your operating system.

**Comment by by123456by** [comment]
> Please update your browser to the latest version



> Please update your browser to the latest version
I also reported an error using the latest version of the browser on other computers

**Comment by by123456by** [comment]
> > Please update your browser to the latest version
> 
> Also, Windows 7 is a gradually outdated operating system, chrome may not be upgraded to the latest version, it is recommended that you update your operating system.

I don't think this is a browser issue. I use the latest version of Edge on both Win10 and Android systems, and the same error is reported

**Comment by MCheping8108** [comment]
I think it should be a network problem, if you don't have any problem with your network, please re-download the project and redeploy it again

**Comment by Yidadaa** [comment]
It's usually a network problem. Check your Docker network. You can search for this error in the issue area to see how others deal with it.

**Comment by by123456by** [comment]
> It's usually a network problem. Check your Docker network. You can search for this error in the issue area to see how others deal with it.

I don't know what keywords to use for searching
