### ISSUE TITLE
[Bug] 删除部分输入内容导致崩溃

### ISSUE THREAD

**Issue by ling142857** [Yidadaa/ChatGPT-Next-Web#3212]
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

重现：
输入： 严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E1086........
选中E1086前面部分（包括空格）按下backspace会导致页面崩溃

**Comment by Yidadaa** [comment]
1. 保证你是最新的代码；
2. 关闭浏览器的翻译功能。
