### ISSUE TITLE
[Feature] Image upload support might be added

### ISSUE THREAD

**Issue by tolgakurtuluss** [Yidadaa/ChatGPT-Next-Web#3216]
I deployed and tried the features of this repo and noticed that new vision feature is not accessible. To implement this, I have a recommended repository below to add this feature.

Feature might look like this:
![](https://raw.githubusercontent.com/Licoy/ChatGPT-Midjourney/master/docs/images/mj-5.png)

Repo:
https://github.com/Licoy/ChatGPT-Midjourney

**Comment by H0llyW00dzZ** [comment]
must be on runtime edge i think hahaha

**Comment by Yidadaa** [comment]
#3110

**Comment by Avey777** [comment]
https://demo6.goamzai.com/draw
