### ISSUE TITLE
[Bug] 最新mac桌面版聊天栏功能图标错位

### ISSUE THREAD

**Issue by Ganzhe2028** [Yidadaa/ChatGPT-Next-Web#3218]
如题，mac桌面版在光标放在聊天栏的功能图标上面时会有框、文字和icon错位的情况

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/129269449/b4af42b3-6552-44b7-b2bb-aa262a2cfbaa

**Comment by Yidadaa** [comment]
这是 Safari 的 bug，修不了。
