### ISSUE TITLE
[Bug] No API Key setting is present

### ISSUE THREAD

**Issue by andenixa** [Yidadaa/ChatGPT-Next-Web#3223]
No setting message is asking to fill in API key which field is not present in settings.

1. Start the program
2. Go to Settings

No input API key field is present

**Desktop (please complete the following information):**
 - OS: Windows 11 64-bit
 - N/A

**Comment by Yidadaa** [comment]
Click `Use Custom Endpoint`: 
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/2c270dbb-2c90-4a84-9f7a-58b70fe064ea)
