### ISSUE TITLE
[Feature] Define the Model in an .env file

### ISSUE THREAD

**Issue by PaulWoitaschek** [Yidadaa/ChatGPT-Next-Web#3224]
In my family, everyone uses our self hosted instance.
Right now on every new login, we need to set the model to `gpt-4-1106-preview` for every single instance.

I'd like to have an option where an env controls the model in use and where users can not configure which model to use.

**Comment by Yidadaa** [comment]
You can use `CUSTOM_MODELS` env var to control available models now:
https://github.com/Yidadaa/ChatGPT-Next-Web#custom_models-optional

you can disable all `gpt-3.5-` models, and it will switch to first available `gpt-4` model.

Only available in main stream, Docker version will be released in next version.

**Comment by PaulWoitaschek** [comment]
Thanks! That's a little hard to maintain though because on every updated model we'd need to manually disable models. Could you add an option to clear all models and then add the ones we want?
