### ISSUE TITLE
[Bug] 老版本怎样导出json格式数据，2.9.1 -> 2.9.11 迁移，发现原来的配置和对话记录都没法转移过去了

### ISSUE THREAD

**Issue by jiangying000** [Yidadaa/ChatGPT-Next-Web#3225]
如果老版本可以输出个json，在2.9.11 import 这个json就可以了

是否有类似的方案

**Comment by H0llyW00dzZ** [comment]
you have to modify it manually for export and import if cannot be transferred
and tools you need

viewer : 
https://jsonviewer.stack.hu/
https://unminify.com/

**Comment by Yidadaa** [comment]
1. 如果你是自行部署的网页，升级你的代码到最新版本即可；
2. 如果你是安装的客户端，下载安装新版本客户端即可。
