### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 1501575808** [Yidadaa/ChatGPT-Next-Web#323]
昨天使用还好好的，今天怎么提示这个了：
出错了，稍后重试吧

**Comment by flyme6** [comment]
api应该是到期了

**Comment by 1501575808** [comment]
过期之后怎么搞呢，文档没看明白



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 1, 2023 19:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Yidadaa/ChatGPT-Next-Web] error (Issue #323)




 
api应该是到期了
