### ISSUE TITLE
[Bug] Azure 模型输出时会不断重复一个词

### ISSUE THREAD

**Issue by Zhenxi-yang** [Yidadaa/ChatGPT-Next-Web#3234]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
使用Azure OpenAI 提问时，模型回答有概率不断重复的一个字或字符如不断输出,,,,,,,
**如何复现**
请告诉我们你是通过什么操作触发的该问题。
询问“你现在是一名电影推荐員”,已使用以下模型测试:az gpt-4 az gpt 3 az gpt 4 32k
**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![Screenshot_20231112-134734_Chrome](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/119769659/ddf826a5-2ad1-4b5e-9e13-7b72ca43016d)
![Screenshot_20231112-134500_Chrome](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/119769659/61a40467-61f4-466a-85b1-f655de283909)
![Screenshot_20231112-134450_Chrome](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/119769659/380b84f7-5eb2-4708-bf8b-e297ff774c50)
![Screenshot_20231112-134430_Chrome](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/119769659/d215820f-d7de-4a8c-92d1-56261dc0e94e)
![Screenshot_20231112-134029_Chrome](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/119769659/53631c28-16ad-4f82-b76c-cfcb4c225ee0)

**一些必要的信息**
 - 系统： A13
 - 浏览器： chrome
 - 版本： 最新版
 - 部署方式： vercel

**Comment by H0llyW00dzZ** [comment]
I can't fix that bug for Azure because I don't have access to it.
should wait @Yidadaa for fix it

**Comment by Yidadaa** [comment]
聊天参数不要乱调，话题新鲜度和频率惩罚度建议设置回原值。
