### ISSUE TITLE
[Bug] windows PC is working good, but it is not working  on ios

### ISSUE THREAD

**Issue by ZuesTao** [Yidadaa/ChatGPT-Next-Web#3238]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
     部署vercel上的next web使用Mandrill AI的API key，调用openai的gpt-4-1106-preview模型，在 PC Chrome 浏览器上用可以正常工作，但相同的参数设置和相同网址，相同的API KEY，在手机端(ios14.4和ios15.6) 的chorme浏览器和 safari浏览器 中均无法正常工作。

所有参数都已反复检查数遍确认相同，也试过清理了cookies，但故障依旧，无法找到原因。

 ios手机 chrome和safari报错信息均如下：

访问密码不正确或为空，请前往登录页输入正确的访问密码，或者在设置页填入你自己的 OpenAI API Key。

{
  "error": {
    "message": "Invalid API key"
  }
}

**如何复现**
请使用以下我的配置信息进行确认:
模型服务商：
openai

接口地址:
https://api.mandrillai.tech

API key(24小时后我会重置它请尽快验证):
md-kcRDJYoIAkWqFYhKaAlayEGrYiboTCrtpmLUjVdrNZSplBlO

模型:
gpt-4-1106-preview

**截图**
描述非常详细，这里就不符图了

**一些必要的信息**
 - 系统：PC端：windows 10   手机端： ios 14.4和ios15.6
 - 浏览器：chrome,和safari
 - 版本： v2.9.11
 - 部署方式：vercel

**Comment by ZuesTao** [comment]
已收到您的邮件!

**Comment by Yidadaa** [comment]
你 key 输错了：https://a.nextweb.fun/#/?settings=%7B%22key%22:%22md-kcRDJYoIAkWqFYhKaAlayEGrYiboTCrtpmLUjVdrNZSplBlO%22,%22url%22:%22https://api.mandrillai.tech%22%7D

**Comment by ZuesTao** [comment]
> 你 key 输错了：https://a.nextweb.fun/#/?settings=%7B%22key%22:%22md-kcRDJYoIAkWqFYhKaAlayEGrYiboTCrtpmLUjVdrNZSplBlO%22,%22url%22:%22https://api.mandrillai.tech%22%7D

Windows pc端Chrome上的确是能正常使用的
但是经确认密码并没有输错，而且ios手机通过您邮件里的链接自动填参数和密码，故障也依旧，如下图所示：
![微信图片_20231112232226](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/73762224/c64d47e3-0ae7-43b2-9af8-3fb971a22b69)
