### ISSUE TITLE
我可以使用，但是我点击新对话它提示我无效API KEY

### ISSUE THREAD

**Issue by lulu-sk** [Yidadaa/ChatGPT-Next-Web#3241]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/58587930/903b7587-2b9b-48c1-844b-3ee809361215)

**Comment by Yidadaa** [comment]
客户端还是网页？

**Comment by lulu-sk** [comment]
最新的客户端





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yidadaa/ChatGPT-Next-Web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yidadaa/ChatGPT-Next-Web] 我可以使用，但是我点击新对话它提示我无效API KEY (Issue #3241)





 
客户端还是网页？

**Comment by lulu-sk** [comment]
最新的客户端，只填写APIKey，不填写网址接口，就会有这个提示，
但是不填写其实就是OpenAI的官方地址
