### ISSUE TITLE
[Feature] OpenAI的ChatCompletion API支持自定义seed参数设置

### ISSUE THREAD

**Issue by amazingchow** [Yidadaa/ChatGPT-Next-Web#3242]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
无关

**你想要什么功能或者有什么建议？**
一致性得评估不同版本prompt的优劣

**有没有可以参考的同类竞品？**
无

**其他信息**
参考资料：https://cookbook.openai.com/examples/deterministic_outputs_with_the_seed_parameter

**Comment by tsinghua202** [comment]
已收到您的信息，目前我不在线，无法给您回复！

**Comment by H0llyW00dzZ** [comment]
#3180

**Comment by H0llyW00dzZ** [comment]
also `seed` / `system_fingerprint` its still confusing for LLM Api which is already best & stable

**Comment by Yidadaa** [comment]
看起来对于大多数用户来说，这个参数都没有实际用处，这个参数适用于基于 api 二次开发功能的场景。
