### ISSUE TITLE
[Bug] 为何在www.aium.cc充值购买的key，模型为gpt-3，切换模型也无效

### ISSUE THREAD

**Issue by czhang223** [Yidadaa/ChatGPT-Next-Web#3243]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在aium.cc上购买了key，在chat.i4store.net上配置完毕后使用，问答显示为gpt-3模型，切换模型也无效

**如何复现**
如上

**截图**
<img width="869" alt="截屏2023-11-13 15 09 06" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/24970977/0b1ada39-684c-4987-8068-08f849c88f1f">

**一些必要的信息**
 - 系统：[macos 13.6]
 - 浏览器： [chrome]
 - 版本： [2.9.9]
 - 部署方式：[chat.i4store.net]

**Comment by Yidadaa** [comment]
别问我，谁卖你的去问谁

**Comment by yann0917** [comment]
因为gpt-4 是基于gpt-3 微调的，并不具备联网功能，所以你换一个gpt-4 能回答正确但是gpt-3.5回答不出来的问题严重一下就知道了。
