### ISSUE TITLE
[Feature] 添加一个开关用来关闭 [正在输入...] 功能

### ISSUE THREAD

**Issue by HADB** [Yidadaa/ChatGPT-Next-Web#3253]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
在文本框输入内容时，上面会显示一个正在输入的内容，和文本框的内容是一样的，感觉有点多余，并且在输入一段文字后再全部删除的时候，上面的对话会有抖动，期望加个开关，可以关闭正在输入的这个气泡的功能，这样可以和一般的聊天界面的行为保持一致。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Unintendedz** [comment]
这个设置可能是你正在找的，它可以关掉预览气泡
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/64687143/db87551c-8158-4e89-9723-a3f46344a9e2)

**Comment by HADB** [comment]
Cool!
