### ISSUE TITLE
[Bug] 输入了访问密码之后 , 还是会提示错误

### ISSUE THREAD

**Issue by Pahkho** [Yidadaa/ChatGPT-Next-Web#3256]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/52782346/341d433c-07cc-462f-8411-9cfe82bf667d)
我能肯定我输入的密码是正确的 , 但是输入密码确认之后 , 回到聊天页面还是会提示错误
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/52782346/da3f17b6-9a93-4983-8cd7-37ad302096b6)

**Comment by Yidadaa** [comment]
你自己部署的，还是用的别人的？
