### ISSUE TITLE
[Feature] 请求集成直接登录openai功能

### ISSUE THREAD

**Issue by itdsgithub** [Yidadaa/ChatGPT-Next-Web#3259]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
无关
**你想要什么功能或者有什么建议？**
是否可以集成一个直接登录openai官网的功能，集成进去一个网页版，毕竟chatgpt在能翻墙情况下，网页版还是免费用的，可以直接用；

**有没有可以参考的同类竞品？**
[可以给出参考产品的链接或者截图。
](https://github.com/lencx/ChatGPT)

**其他信息**
如果不好弄就当我没说

**Comment by QAbot-zh** [comment]
next web主要面向api，估计作者不会往网页版搞，吃力不讨好 (除了要提供代理服务，还要跟官方各种人机验证斗争，然后用户还要怀疑你账号密码登录会不会被偷账号，最后也不利于大家自己部署）。
免翻登录openai，你可以去找pandora项目(https://chat1.zhile.io)
