### ISSUE TITLE
感觉可以加个联网功能（github有个ChuanhuChatGPT好像就能联网，不知道是怎么逻辑）

### ISSUE THREAD

**Issue by knigth95** [Yidadaa/ChatGPT-Next-Web#326]

**Comment by knigth95** [comment]
链接联网的参考https://github.com/GaiZhenbiao/ChuanhuChatGPT

**Comment by hayoial** [comment]
> 链接联网的参考https://github.com/GaiZhenbiao/ChuanhuChatGPT

测试了一下，怎么感觉它这个回答风格像是new bing。

**Comment by Yidadaa** [comment]
重复 #165

**Comment by knigth95** [comment]
> > 链接联网的参考https://github.com/GaiZhenbiao/ChuanhuChatGPT
> 
> 测试了一下，怎么感觉它这个回答风格像是new bing。

dian点了联网后的回复确实像new bing
