### ISSUE TITLE
最新版本支持Azure，但OpenAI Key仍然是必选参数，也就是仍然需要部署azure-openai-proxy才能让Docker正常工作。

### ISSUE THREAD

**Issue by yankevin** [Yidadaa/ChatGPT-Next-Web#3264]
//gpt-35-turbo-16k

docker run -d -p 3080:3000 --name=chatgpt-azure \
   -e OPENAI_API_KEY=here-is-my-azure-key \
   -e BASE_URL=http://10.90.0.47:8080 \
   -e AZURE_URL=https://my-azure-openai.openai.azure.com/openai/deployments/gpt-35-turbo-16k \
   -e AZURE_API_KEY=here-is-my-azure-key \
   -e AZURE_API_VERSION=2023-09-01-preview \
   -e HIDE_USER_API_KEY=1 \
   -e DISABLE_GPT4=1 \
   -e HIDE_BALANCE_QUERY=1 \
   yidadaa/chatgpt-next-web:latest

如何才能不使用BASE_URL参数来支持Azure的OpenAI?

**Comment by Yidadaa** [comment]
不填 BASE_URL 会报什么错？

**Comment by yankevin** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/6825207/e383ecbf-76b5-4b38-80c4-b16bdc5a60c6)
Un[auth](http://10.90.0.47:3090/#/auth)orized access, please enter access code in auth page, or enter your OpenAI API Key.

**Comment by yankevin** [comment]
> 不填 BASE_URL 会报什么错？

我上了个图，在这个图中，即使输入了OpenAPI的Key，也仍然没有作用。

**Comment by yzkwkw** [comment]
我也碰到这样问题，好像仍然没有解决的方法？

**Comment by oicoderr** [comment]
在不更改chatgpt-next-web项目前提，可以采用代理转发，希望可以帮助到你https://github.com/oicoderr/azure-openai-proxy
