### ISSUE TITLE
[Bug] 现在是被墙了吗

### ISSUE THREAD

**Issue by KrystalandBarry** [Yidadaa/ChatGPT-Next-Web#3279]
![Uploading image.png…]()

**Comment by KrystalandBarry** [comment]
<div class="cf-section cf-highlight">
    <div class="cf-wrapper">
      <div class="cf-screenshot-container cf-screenshot-full">
        
          <span class="cf-no-screenshot error"></span>
        
      </div>
    </div>
  </div>

  <div class="cf-section cf-wrapper">
    <div class="cf-columns two">
      <div class="cf-column">
        <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

        <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
      </div>

      <div class="cf-column">
        <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

        <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
      </div>
    </div>
  </div>

  <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">

**Comment by dodobird2077** [comment]
"Sorry, you have been blocked"

**Comment by vangie** [comment]
Why have I been blocked? 碰到一样的问题

**Comment by cakiihana** [comment]
Same question here. It seems Cloudflare's CDN is getting attack and BLOCK some link automatically. Maybe wait?

**Comment by WilsonWow** [comment]
Facing the same problem with Vercel deployment.

**Comment by CaptainRuby** [comment]
++++++1
