### ISSUE TITLE
[Bug] docker部署设置代理不支持域名代理

### ISSUE THREAD

**Issue by jaychoubaby** [Yidadaa/ChatGPT-Next-Web#3281]
docker部署的时候，由于服务器无法直连openai，故设置代理，但是目前不支持域名代理，希望可以给予支持

设置：
-e PROXY_URL=http://openai-proxy.cf

报错提示：
error: invalid item in proxylist section: http openai-proxy.cf

**Comment by Yidadaa** [comment]
你应该是使用 BASE_URL 而不是 PROXY_URL，好好读文档。
