### ISSUE TITLE
[Feature] 增加每日统计功能吗？

### ISSUE THREAD

**Issue by DoiiarX** [Yidadaa/ChatGPT-Next-Web#3282]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
我的chatgpt next web 每天凌晨2点到3点有大量使用记录，但是无法知道原因。

**你想要什么功能或者有什么建议？**
增加每日统计功能

**有没有可以参考的同类竞品？**
增加每日统计功能

**其他信息**
我的chatgpt next web 每天凌晨2点到3点有大量使用记录，但是无法知道原因。

**Comment by Yidadaa** [comment]
没有数据库，无法记录用量。

如果你发现有不明使用记录，请修改 CODE，并使用复杂 CODE。
