### ISSUE TITLE
[Bug] Ctrl + F won't work in long conversation

### ISSUE THREAD

**Issue by AelecTi** [Yidadaa/ChatGPT-Next-Web#3283]
Some features automatically hide message items that are too far away from current scrolling position, and the message within those items won't show up when using Ctrl+F. My workflow requires constantly searching history backwardly and this feature of auto hiding has become a pain in the ass.

I'v notice you have created a constant named 'MAX_RENDER_MSG_COUNT' but are no referrenced anywhere else.

Please consider adding an option to stop or change this behaviour. Or could you please tell me where to change the code to temporarily solve the problem?

**Comment by Yidadaa** [comment]
For performance issues, we must hide old messages, otherwise lag will cause the entire UI to be unavailable, you can wait #2158
