### ISSUE TITLE
[Bug] 本地部署使用阿里云的香港服务器，"You are unable to access"，有什么解决办法吗，换了好几个ip了

### ISSUE THREAD

**Issue by MengYingjie** [Yidadaa/ChatGPT-Next-Web#3289]
**Describe the bug**
本地部署使用阿里云的香港服务器，"You are unable to access"，有什么解决办法吗，换了好几个ip了

**Deployment**
- [ ] Docker
- [ ] Vercel
- [·] Server

**Comment by nonewind** [comment]
香港的服务器用不了，下一个
