### ISSUE TITLE
[Bug]  docker 部署 出现错误  

### ISSUE THREAD

**Issue by shrimpma** [Yidadaa/ChatGPT-Next-Web#3293]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/1514413/3ab74f61-86c3-4de0-8467-84a12a7d2be9)

**Comment by Yidadaa** [comment]
网络问题，请自行解决。
