### ISSUE TITLE
BASE_URL 定义htts 出现的问题

### ISSUE THREAD

**Issue by qichuangguo** [Yidadaa/ChatGPT-Next-Web#3297]
我docker 启动的时候指定 BASE_URL=https://xxx  这样就提示 
{
  "cause": {
    "code": "ECONNRESET",
    "host": "api.ngapi.top",
    "port": 443,
    "localAddress": null
  }
}

如果我在前端设置自定义域名 并且填写key 却可以正常访问，这是什么原因？

**Comment by Yidadaa** [comment]
BASE_URL=https://api.ngapi.top

**Comment by qichuangguo** [comment]
docker run -d -p 3000:3000 \
   -e OPENAI_API_KEY=sk-xxxxxxxxxxxxxx \
   -e CODE=xxxxxxx \
   -e BASE_URL=https://api.ngapi.top \
   yidadaa/chatgpt-next-web
我这样启动是对的吗
