### ISSUE TITLE
[Bug] Mac UI暗色界面下对话删除键不可见

### ISSUE THREAD

**Issue by A2Sumie** [Yidadaa/ChatGPT-Next-Web#3299]
**Describe the bug**
如题，如图。
<img width="1130" alt="图片" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/89308692/6c50d0dc-20c1-42de-ad19-62002dc441e7">
<img width="1130" alt="图片" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/89308692/bb0464b3-ba7e-42fa-b187-48e3d7725242">

但是Vercel上我部署的同版本号的这个 https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain 在firefox上并无此问题。
**To Reproduce**
将界面设置成暗色，或者auto时系统在暗色。
鼠标悬停在对话卡片上，暗色时删除按钮不可见。
鼠标找寻到对应位置鼠标光标会有变化，也可以点击生效，仅是视觉上不可见。

**Expected behavior**
一个可见可用的删除键。

**Screenshots**
放在描述里了。

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server
本地。

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.0
 - Browser 不适用

**Comment by H0llyW00dzZ** [comment]
something wrong in rendering while compiling to a binary


on windows/linux works fine


![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/e93bb65a-5b24-4f4d-bbae-fad0000b733b)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/8d0e6c70-bc48-42ca-bc51-156b8f6e28ca)

**Comment by A2Sumie** [comment]
Updating MacOS to 14.1.1 seems to resolve the problem. Closing.
