### ISSUE TITLE
作者有捐赠入口吗？

### ISSUE THREAD

**Issue by mushan0x0** [Yidadaa/ChatGPT-Next-Web#33]
我愿意捐赠作者的这个项目

**Comment by ruixing1001** [comment]
支持支持

**Comment by Yidadaa** [comment]
感谢支持，相关款项会用于支充值演示网址的 openai 账户，你可以在备注中提供自己的 github 名用于鸣谢。

![mm_facetoface_collect_qrcode_1679817556760](https://user-images.githubusercontent.com/16968934/227763084-2b5e51b8-52e3-42f3-8501-33ca7563b212.png)

**Comment by mushan0x0** [comment]
已捐赠，好项目值得支持

**Comment by Yidadaa** [comment]
@mushan0x0 大手笔

**Comment by ClarenceDan** [comment]
我也来支持一波，感谢大佬！

**Comment by hoochanlon** [comment]
哈哈，我已经向项目捐赠爱心软妹币，以及个人API，记得看邮箱哦。

**Comment by benjaminv** [comment]
Count my five cents. this is great.

**Comment by benjaminv** [comment]
当前版本其实可以这样分享给家人朋友：
部署的时候不填写OPENAI_API_KEY, although it is required. - seems a bug but indeed a great feature.
然后私下分发API Key给朋友使用。

**Comment by JohnsenZhou** [comment]
请问下作者是怎么充值openai 账户的，目前绑定不了信用卡

**Comment by HenMie** [comment]
> 请问下作者是怎么充值openai 账户的，目前绑定不了信用卡

用支持地区发行的银行卡，中国发行的不行。没有实体卡可以用虚拟卡，depay之类的。

**Comment by lingnanlu** [comment]
发现这个项目, 真不错, 请作者喝了一杯奶茶
另外, 发现chat.simplenaive.cn这个域名真有内含啊

**Comment by NoMoney2022** [comment]
支持，已经捐赠

**Comment by shunz** [comment]
做的确实很棒、很用心、很好用，实在忍不住，一定要上来捐赠一点碎银子。

**Comment by HuChundong** [comment]
支持作者，捐赠一波。

**Comment by YyJyyy** [comment]
支持作者

**Comment by NBchitu** [comment]
支持作者，加油！

**Comment by anobodycan** [comment]
太棒了，已支持！

**Comment by Corwin006** [comment]
谢谢辛劳！感谢开源！已支持 :)

**Comment by ypwhs** [comment]
支持一个：

<img width="332" alt="image" src="https://user-images.githubusercontent.com/10473170/231674759-765d5686-5de9-4a96-b1d0-05d27a472294.png">

**Comment by OnClickListener2048** [comment]
这个代码写的真漂亮

**Comment by xuzhougeng** [comment]
支持一波作者，学习下代码！

**Comment by poweredbyai** [comment]
很棒，大神愿意接定制化开发的项目吗？

**Comment by aidisheng101** [comment]
> 
你是要买api是嘛

**Comment by firmitfeng** [comment]
支持作者

**Comment by mgttt** [comment]
刚捐了101，但是忘记备注了，无所谓，希望早点支持官方插件哈

**Comment by GUOhk36** [comment]
谢谢。

**Comment by djkko** [comment]
已捐助，大佬请喝茶

**Comment by zhaoxitao** [comment]
> 我愿意捐赠作者的这个项目

咦，你不是AI 0x0那个项目的作者吗？哈哈哈哈哈，居然在这里碰到你还在其他项目捐款，梦幻联动了属于是

**Comment by fangyuan99** [comment]
> > 我愿意捐赠作者的这个项目
> 
> 咦，你不是AI 0x0那个项目的作者吗？哈哈哈哈哈，居然在这里碰到你还在其他项目捐款，梦幻联动了属于是

他的项目参考了这个项目

**Comment by ZhangMin1998** [comment]
> 感谢支持，可以在备注中提供自己的 github 账户名用于鸣谢。
> 
> > 由于小额打赏较多，目前仅金额 >= 100RMB 的用户会被列入鸣谢名单。
> 
> <img alt="" width="260px" src="https://user-images.githubusercontent.com/16968934/227763084-2b5e51b8-52e3-42f3-8501-33ca7563b212.png">

你好 请问可以拉我进群吗   请问这个问题怎么解决呀 什么意思 超限  You exceeded your current quota, please check your plan and billing details.

**Comment by lucasmen9527** [comment]
支持支持

**Comment by OwenPro1233** [comment]
Support👍

**Comment by lzt7920** [comment]
> 刚刚捐了100.发现个小问题，就是搭建好的网址到手机上的浏览器访问报错。 ![图像](https://user-images.githubusercontent.com/5416234/245461595-d99ec87c-bde5-4194-9fa3-a9b78c717af4.png)

我的朋友也出现过这样的报错，ios15系统，其他系统设备没遇到过

**Comment by rayzhl25** [comment]
我在9月12号也捐助了，忘了备注了git账号了，

**Comment by wenjiavv** [comment]
单号：10000499012023111300411615459113
支持大佬！

**Comment by LeXwDeX** [comment]
> 感谢支持，可以在备注中提供自己的 github 账户名用于鸣谢。
> 
> > 由于小额打赏较多，目前仅金额 >= 100RMB 的用户会被列入鸣谢名单。
> 
> <img alt="" width="260px" src="https://user-images.githubusercontent.com/16968934/227763084-2b5e51b8-52e3-42f3-8501-33ca7563b212.png">

但我没在名单上呀。😂

**Comment by LuRenJiasWorld** [comment]
支持原创，支持开源，加油！

**Comment by shangmin2009** [comment]
支持一下，好项目，期待更多好用的功能
