### ISSUE TITLE
Add an option to clear CUSTOM_MODELS

### ISSUE THREAD

**Issue by PaulWoitaschek** [Yidadaa/ChatGPT-Next-Web#3301]
I use CUSTOM_MODELS in order to specify the model which all of our users make use of.

In my use case I want only `gpt-4-1106-preview` be available and selected as a default.

With the new `CUSTOM_MODELS` I can archive that by excluding all models.
This is a very long block of code and also error prone because it would need to be adjusted whenever there are new models available.

```.env
CUSTOM_MODELS=-gpt-4-0314,-gpt-4-0613,-gpt-4-32k,-gpt-4-32k-0314,-gpt-4-32k-0613,-gpt-4-vision-preview,-gpt-3.5-turbo-0301,-gpt-3.5-turbo-0613,-gpt-3.5-turbo-1106,-gpt-3.5-turbo-16k,-gpt-3.5-turbo-16k-0613,-gpt-4,-gpt-3.5-turbo
```

One solution could be to add an `-all` (and `+all`) shortcut.

Then what I'm achieving could be done as
```.env
CUSTOM_MODELS=-all,+gpt-4-1106-preview
```

**Comment by dq7532183** [comment]
默认模型bug
设置为 CUSTOM_MODELS=-all,+gpt-4-1106-preview
虽然模型列表只剩下了gpt-4-1106-preview,但是打开新聊天,默认的模型还是gpt-3.5-trubo,必须再选择一下模型才能修改
