### ISSUE TITLE
[Bug] 2.9.12 自定义模型添加微调模型失败

### ISSUE THREAD

**Issue by wzqmaui** [Yidadaa/ChatGPT-Next-Web#3304]
**Describe the bug**
设置里添加自定义模型失败  微调模型 格式ft:gpt-3.5-turbo-1106:personal::XXXXXX
**To Reproduce**
1. 设置里
2. 自定义模型框填入微调模型名称
3. 模型选择框看不到, 出现两个 gpt-3.5-turbo-1106 选择 最下边, 聊天 结果返回  json 提示 model id 'ft' 找不到
4.随便填写 XX:111:@@@,下边模型框里只会看到111, 不是完整名称

**Desktop (please complete the following information):**
 - OS: [mac]
 - Version [2.9.12]

**Comment by H0llyW00dzZ** [comment]
I know where is problem

in this one
```ts
export function collectModelTable(
  models: readonly LLMModel[],
  customModels: string,
) {
  const modelTable: Record<
    string,
    { available: boolean; name: string; displayName: string }
  > = {};

  // default models
  models.forEach(
    (m) =>
      (modelTable[m.name] = {
        ...m,
        displayName: m.name,
      }),
  );

  // server custom models
  customModels
    .split(",")
    .filter((v) => !!v && v.length > 0)
    .map((m) => {
      const available = !m.startsWith("-");
      const nameConfig =
        m.startsWith("+") || m.startsWith("-") ? m.slice(1) : m;
      const [name, displayName] = nameConfig.split(":");
      modelTable[name] = {
        name,
        displayName: displayName || name,
        available,
      };
    });
  return modelTable;
}
```


`const [name, displayName] = nameConfig.split(":");` should be `const [name, displayName] = nameConfig.split(":") && nameConfig.split("|");`

`|` is for aliases fine tuning model eg : `ft:gpt-3.5-turbo-0613:github-developer-program::88ufxjNg|Fine-Tunning`

it will showing a Fine-Tunning

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/a0c0aa7d-ba7e-4363-8dcd-89b39c43fe70)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/f2dfbc1d-c7da-4d18-8334-df0938aaf9d5)

**Comment by H0llyW00dzZ** [comment]
also by adding aliases support multipe fine-tunning

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/712f2d54-3e17-49f0-9e5b-044d6f7d1055)

**Comment by Yidadaa** [comment]
模型映射和微调模型冲突了，我需要找一个其他的映射符号

**Comment by H0llyW00dzZ** [comment]
By adding aliases, you can resolve the conflict, and it's recommended to use it so because the names of fine-tuned models, its idk how I call `ft:gpt-3.5-turbo-0613:github-developer-program::88ufxjNg` (example) too broad.

**Comment by H0llyW00dzZ** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/eab606c3-b750-42ae-ae27-388d19d78298)

**Comment by Yidadaa** [comment]
已经修改为使用 `=` 映射模型名。
