### ISSUE TITLE
[Bug] 使用国内服务器DOCK部署并安装Clash,Curl api.openai.com成功，但是ChatGPT-Next-Web无法链接openai

### ISSUE THREAD

**Issue by berryyan** [Yidadaa/ChatGPT-Next-Web#3306]
请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [X] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [X] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [X] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用国内服务器DOCK部署并安装Clash,Curl api.openai.com成功，但是ChatGPT-Next-Web无法链接openai。

**如何复现**
反复重新启动和安装，检查所有config，确认Clash和ChatGPT-Next-Web启动配置了-e PROXY_URL=http://127.0.0.1:7890 \

**截图**
![chatgpt next001](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/24866151/b77b157e-a97a-4a0e-9d01-b40d700a3642)
![chatgpt next002](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/24866151/e11da244-b2ec-43bf-a50a-11e3879a016c)

**一些必要的信息**
 - 系统：腾讯云上海
 - 部署方式：docker服务器部署]

**Comment by Yidadaa** [comment]
请提供 docker 内的 log。

**Comment by berryyan** [comment]
-- Logs begin at Tue 2021-07-20 11:11:18 CST, end at Sat 2023-11-18 22:26:24 CST. --
Nov 18 17:05:26 VM-16-15-centos systemd[1]: Starting Docker Application Container Engine...
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.916401179+08:00" level=info msg="Starting up"
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.917517357+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.917541806+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.917588861+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grp
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.917611103+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.925157154+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.925184248+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.925209456+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grp
Nov 18 17:05:26 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:26.925226185+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 18 17:05:27 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:27.163090026+08:00" level=info msg="Loading containers: start."
Nov 18 17:05:27 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:27.638824108+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP
Nov 18 17:05:27 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:27.742602436+08:00" level=info msg="Loading containers: done."
Nov 18 17:05:27 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:27.853083347+08:00" level=info msg="Docker daemon" commit=363e9a8 graphdriver(s)=overlay2 version=20.10.5
Nov 18 17:05:27 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:27.853210178+08:00" level=info msg="Daemon has completed initialization"
Nov 18 17:05:28 VM-16-15-centos systemd[1]: Started Docker Application Container Engine.
Nov 18 17:05:28 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:05:28.066832904+08:00" level=info msg="API listen on /var/run/docker.sock"
Nov 18 17:37:12 VM-16-15-centos dockerd[1566]: time="2023-11-18T17:37:12.463134636+08:00" level=info msg="ignoring event" container=ca1f9d8359ec8e6a7f30bea71d0f38eaeceee3c13eaa6047edb33075e4753946 module=libcontainerd namespace=mo
Nov 18 19:04:34 VM-16-15-centos dockerd[1566]: time="2023-11-18T19:04:34.817361669+08:00" level=info msg="ignoring event" container=1b6338570bd7c39ffacb9ca43562c552b1760612eb47368b35b662e6d94ec519 module=libcontainerd namespace=mo
Nov 18 19:33:29 VM-16-15-centos dockerd[1566]: time="2023-11-18T19:33:29.698446636+08:00" level=info msg="ignoring event" container=1b6338570bd7c39ffacb9ca43562c552b1760612eb47368b35b662e6d94ec519 module=libcontainerd namespace=mo
Nov 18 19:34:15 VM-16-15-centos dockerd[1566]: time="2023-11-18T19:34:15.737997967+08:00" level=info msg="Processing signal 'terminated'"
Nov 18 19:34:15 VM-16-15-centos systemd[1]: Stopping Docker Application Container Engine...
Nov 18 19:34:15 VM-16-15-centos dockerd[1566]: time="2023-11-18T19:34:15.887395636+08:00" level=info msg="ignoring event" container=1b6338570bd7c39ffacb9ca43562c552b1760612eb47368b35b662e6d94ec519 module=libcontainerd namespace=mo
Nov 18 19:34:16 VM-16-15-centos dockerd[1566]: time="2023-11-18T19:34:16.016742871+08:00" level=info msg="Daemon shutdown complete"
Nov 18 19:34:16 VM-16-15-centos systemd[1]: Stopped Docker Application Container Engine.
-- Reboot --
Nov 18 19:34:36 VM-16-15-centos systemd[1]: Starting Docker Application Container Engine...
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.727399128+08:00" level=info msg="Starting up"
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.743802606+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.743827646+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.743870300+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grp
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.743893601+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.764584171+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.764618608+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.764643127+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grp
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.764659472+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 18 19:34:36 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:36.879758637+08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Nov 18 19:34:37 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:37.271380047+08:00" level=info msg="Loading containers: start."
Nov 18 19:34:37 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:37.719103750+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP
Nov 18 19:34:37 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:37.795867306+08:00" level=info msg="Loading containers: done."
Nov 18 19:34:37 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:37.902920700+08:00" level=info msg="Docker daemon" commit=363e9a8 graphdriver(s)=overlay2 version=20.10.5
Nov 18 19:34:37 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:37.903630975+08:00" level=info msg="Daemon has completed initialization"
Nov 18 19:34:37 VM-16-15-centos systemd[1]: Started Docker Application Container Engine.
Nov 18 19:34:37 VM-16-15-centos dockerd[1561]: time="2023-11-18T19:34:37.972668313+08:00" level=info msg="API listen on /var/run/docker.sock"
Nov 18 20:10:28 VM-16-15-centos dockerd[1561]: time="2023-11-18T20:10:28.864347642+08:00" level=info msg="ignoring event" container=1b6338570bd7c39ffacb9ca43562c552b1760612eb47368b35b662e6d94ec519 module=libcontainerd namespace=mo
Nov 18 20:15:00 VM-16-15-centos dockerd[1561]: time="2023-11-18T20:15:00.467598556+08:00" level=info msg="ignoring event" container=1b6338570bd7c39ffacb9ca43562c552b1760612eb47368b35b662e6d94ec519 module=libcontainerd namespace=mo
Nov 18 20:27:20 VM-16-15-centos dockerd[1561]: time="2023-11-18T20:27:20.654905500+08:00" level=info msg="ignoring event" container=3a2b80a7c7226b3d5fe892aa80cf009d310f04c812cc9a64e58956993a63c558 module=libcontainerd namespace=mo
Nov 18 20:31:17 VM-16-15-centos dockerd[1561]: time="2023-11-18T20:31:17.730299293+08:00" level=info msg="ignoring event" container=7717c6b587141d4ec00a6b2b66aede4689f8201377a52e8af3f49acc4f1027c0 module=libcontainerd namespace=mo
Nov 18 20:41:05 VM-16-15-centos dockerd[1561]: time="2023-11-18T20:41:05.003144342+08:00" level=info msg="Processing signal 'terminated'"
Nov 18 20:41:05 VM-16-15-centos systemd[1]: Stopping Docker Application Container Engine...
Nov 18 20:41:05 VM-16-15-centos dockerd[1561]: time="2023-11-18T20:41:05.155370939+08:00" level=info msg="ignoring event" container=7717c6b587141d4ec00a6b2b66aede4689f8201377a52e8af3f49acc4f1027c0 module=libcontainerd namespace=mo
Nov 18 20:41:05 VM-16-15-centos dockerd[1561]: time="2023-11-18T20:41:05.284836662+08:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Nov 18 20:41:05 VM-16-15-centos dockerd[1561]: time="2023-11-18T20:41:05.285035630+08:00" level=info msg="Daemon shutdown complete"
Nov 18 20:41:05 VM-16-15-centos systemd[1]: Stopped Docker Application Container Engine.
-- Reboot --
Nov 18 20:41:23 VM-16-15-centos systemd[1]: Starting Docker Application Container Engine...
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.283486308+08:00" level=info msg="Starting up"
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.300610657+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.300649038+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.300682235+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grp
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.300703341+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.312085519+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.312106331+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.312126684+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grp
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.312140494+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.397389210+08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.493735276+08:00" level=info msg="Loading containers: start."
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.856296688+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP
Nov 18 20:41:25 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:25.915435438+08:00" level=info msg="Loading containers: done."
Nov 18 20:41:26 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:26.011831320+08:00" level=info msg="Docker daemon" commit=363e9a8 graphdriver(s)=overlay2 version=20.10.5
Nov 18 20:41:26 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:26.014489167+08:00" level=info msg="Daemon has completed initialization"
Nov 18 20:41:26 VM-16-15-centos systemd[1]: Started Docker Application Container Engine.
Nov 18 20:41:26 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:41:26.118906995+08:00" level=info msg="API listen on /var/run/docker.sock"
Nov 18 20:49:49 VM-16-15-centos dockerd[1524]: time="2023-11-18T20:49:49.529150103+08:00" level=info msg="ignoring event" container=7717c6b587141d4ec00a6b2b66aede4689f8201377a52e8af3f49acc4f1027c0 module=libcontainerd namespace=mo
Nov 18 21:05:01 VM-16-15-centos dockerd[1524]: time="2023-11-18T21:05:01.840322276+08:00" level=info msg="ignoring event" container=403cee4f0373aa5ad3ef71c7fa3358d8966af699d4665e957441b870478b1ba8 module=libcontainerd namespace=mo
Nov 18 21:38:45 VM-16-15-centos dockerd[1524]: time="2023-11-18T21:38:45.530718351+08:00" level=info msg="ignoring event" container=403cee4f0373aa5ad3ef71c7fa3358d8966af699d4665e957441b870478b1ba8 module=libcontainerd namespace=mo
lines 51-77/77 (END)

**Comment by berryyan** [comment]
您好，然后就没有然后了吗？.....哭
