### ISSUE TITLE
[Bug] 重定向丢失Authorization

### ISSUE THREAD

**Issue by steven52880** [Yidadaa/ChatGPT-Next-Web#3309]
**Describe the bug**
使用Docker在反代后面搭建好了OneAPI+ChatGPT-Next，一直用的好好的，前几天忽然开始报错：
```
{
  "error": {
    "message": "未提供令牌 (request id: 20231119042250651265372CmEHqLZb)",
    "type": "one_api_error"
  }
}
```
电脑上chrome和edge均出现此问题，手机上可以正常使用
F12的Network里面显示，先访问`https://chatgpt-next-web/api/openai/v1/chat/completions`，此时POST请求Request Header包含Authorization
<img width="658" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/31466039/6619681c-4652-49f9-94b0-6d5207847b37">
跳转到`https://one-api/v1/chat/completions?path=v1&path=chat&path=completions`，此时POST请求Request Header没有Authorization
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/31466039/623bb3bb-6c8c-49b7-b196-f6b1c1c8b9cb)

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 119.0.6045.159

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android
 - Browser: Chrome
 - Version: 112.0.5615.136

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
没看懂，你好好检查一下请求在各个流程上的 log。
