### ISSUE TITLE
[Feature] Azure OpenAI 和OpenAI快速切换

### ISSUE THREAD

**Issue by aaro-n** [Yidadaa/ChatGPT-Next-Web#3312]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
我更新ChatGPT-Next-Web并正常使用Azure OpenAI ，我无法分辨ChatGPT-Next-Web当前到底使用的是那个API，只能通过vercel后台查看。我想要ChatGPT-Next-Web 可以快速切换不同api并且web界面显示这种变化。

**有没有可以参考的同类竞品？**
无

**其他信息**
无

**Comment by Yidadaa** [comment]
这个做不到，没有数据库。
