### ISSUE TITLE
Windows10+IDEA+nodejs20开发环境中报错：ConnectTimeoutError

### ISSUE THREAD

**Issue by jihaonan** [Yidadaa/ChatGPT-Next-Web#3313]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在本地Windows10+IDEA+nodejs20开发环境中运行，.env里面配置了代理URL，但是访问报错ConnectTimeoutError

**截图**
**本地PC通过浏览器直接访问openai的结果**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14744832/78cb9c9d-9d80-4938-8dc6-a4d9b01b4329)
**本地启动应用后浏览器访问聊天窗口返回结果**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14744832/01073bf5-8b71-444c-8950-f26ff4e4c11e)
**控制台日志**
[OpenAI Route] params  { path: [ 'v1', 'chat', 'completions' ] }
[User IP]  8.8.8.8
[Time]  2023/11/19 20:36:21
[Auth] use system api key
[Proxy]  v1/chat/completions?path=v1&path=chat&path=completions
[Base Url] https://api.openai.com
[Org ID]
[OpenAI]   [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
**.env配置**
PROXY_URL=http://127.0.0.1:10088

**一些必要的信息**
 - 系统： Windows 10、nodejs 20
 - 部署方式：在本地IDEA开发环境中运行

**Comment by Yidadaa** [comment]
nodejs 代理不好架，仔细读中文 readme
