### ISSUE TITLE
[Bug] HTTP请求头里面会泄露访问密码

### ISSUE THREAD

**Issue by jihaonan** [Yidadaa/ChatGPT-Next-Web#3315]
**Describe the bug**
HTTP请求头里面会泄露访问密码
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14744832/6c04f27c-42c8-48d2-83d4-e4c33ff943bf)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
The issue you're experiencing is not a bug, it occurs by default when using an access code.
