### ISSUE TITLE
URL is not valid or contains user credentials

### ISSUE THREAD

**Issue by stainboy** [Yidadaa/ChatGPT-Next-Web#3317]
**Describe the bug**
Configuration with Azure on Desktop version of Next-web shows me error of "URL is not valid or contains user credentials"

**To Reproduce**
1. Say 'hi'
2. See error

**Expected behavior**
Response with normal chat results.

Detail of configuration shows below, which is tested in my dev environment
- Azure endpoint: https://aaaa.openai.azure.com/openai/deployments/bbbb (where aaaa and bbbb are my own resource names)
- Azure api version: 2023-07-01-preview
- Model: gpt-4-1106-preview

**Screenshots**
<img width="976" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/474101/b33a0d53-d710-4c2c-bea0-38badfd8bae2">
<img width="978" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/474101/6cfda71e-3737-4cd4-a072-7eb6e56c7769">

**Deployment**
- [x] Desktop

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.1 (23B81) (M1 Pro)
 - Browser: Desktop version
 - Version: v2.9.12

**Additional Logs**
Not aware of how to check logs

**Comment by H0llyW00dzZ** [comment]
you need to put like this 
`https://xxxx.openai.azure.com/openai/deployments/your-deployment`
and azure api version try set `2023-08-01-preview`

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/8c50fb3a-9174-4936-ac3c-65324f05879d)

**Comment by Yidadaa** [comment]
F12, and show me the console logs

**Comment by Yidadaa** [comment]
https://www.reddit.com/r/WebKit/comments/oqog3u/why_am_i_getting_this_error_in_webkit/

**Comment by stainboy** [comment]
I eventually figured out what's wrong with my setup.

I accidentally put an extra leading space to the URL..... When the space got trimmed, everything works like a charm!

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/474101/809f4a82-b9b8-456b-87ae-da23c30d8ac0)

BTW, great work! Yidadaa. You rock!
