### ISSUE TITLE
[Bug] in desktop app no place to enter api key?

### ISSUE THREAD

**Issue by clarity99** [Yidadaa/ChatGPT-Next-Web#3323]
**Describe the bug**
when starting desktop app on macos it says:
Invalid API Key, please check it in [Settings](tauri://localhost/#/settings) page.

however, there is nothing in the setting where to set the api key.

**To Reproduce**
1. run app
2. select Settings
3. 

**Screenshots**

**Deployment**
mac app

**Desktop (please complete the following information):**
 - OS: macos sonoma 14.1.1
 - Browser - app
 - Version 2.9.12
 - 

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
enabled this 
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/49d8b97d-0c69-4fdb-858b-5cbb63bfc52d)
