### ISSUE TITLE
[Bug] App crashed

### ISSUE THREAD

**Issue by SteelBallSuck** [Yidadaa/ChatGPT-Next-Web#3332]
After that I looked at /var/log/syslog:
`kernel: [75058.875322] traps: chat-gpt-next-w[148248] trap int3 ip:7fa730e42167 sp:7fff8f5de9f0 error:0 in libglib-2.0.so.0[7fa730dfe000+8f000]`
Errors started with Appimage v2.9.11and continue to appear in v2.9.12, preventing the application launching. In this case, version v2.9.10 started ok.
That's what I did:
`sudo apt install --reinstall libglib2.0-0`
`sudo apt install --reinstall libglib2.0-dev`
It didn't help.
Ubuntu Studio 22.04.3 KDE

**Comment by Yidadaa** [comment]
I don't have an Ubuntu environment to reproduce this error. Please try installing the deb version. If the issue persists, please prioritize using the PWA web version. I don't want to spend more time fixing compatibility issues like this. Thank you for your understanding.
