### ISSUE TITLE
[Feature] 自定义限制部署系统使用gpt4.0 api

### ISSUE THREAD

**Issue by wangxiaodong1021** [Yidadaa/ChatGPT-Next-Web#3336]
**Is your feature request related to a problem? Please describe.**
给多人分享部署平台，存在4.0被滥用风险

**Describe the solution you'd like**
限定只有某些密码可以使用4.0 api，或者4.0 api只能在输入key使用，密码不能使用

避免被滥用后，只能改密码

**Comment by Yidadaa** [comment]
请用 one api 实现这些高级功能。
