### ISSUE TITLE
DEFAULT_SYSTEM_TEMPLATE  是不能在环境变量中定义吗需要自己改源码?

### ISSUE THREAD

**Issue by duolabmeng6** [Yidadaa/ChatGPT-Next-Web#3339]
```
{
    "messages":[
        {
            "role":"system",
            "content":"\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2023/11/21 22:05:51\n\n"
        },
        {
            "role":"user",
            "content":"我想做饭"
        }
    ],
    "stream":true,
    "model":"gpt-3.5-turbo",
    "temperature":0.5,
    "presence_penalty":0,
    "frequency_penalty":0,
    "top_p":1
}
```
```
export const DEFAULT_SYSTEM_TEMPLATE = `
You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: {{cutoff}}
Current model: {{model}}
Current time: {{time}}
Latex inline: $x^2$ 
Latex block: $$e=mc^2$$
`;
````

我想问一下 因为我不想要这个 system

**Comment by H0llyW00dzZ** [comment]
> ```
> {
>     "messages":[
>         {
>             "role":"system",
>             "content":"\nYou are ChatGPT, a large language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2023/11/21 22:05:51\n\n"
>         },
>         {
>             "role":"user",
>             "content":"我想做饭"
>         }
>     ],
>     "stream":true,
>     "model":"gpt-3.5-turbo",
>     "temperature":0.5,
>     "presence_penalty":0,
>     "frequency_penalty":0,
>     "top_p":1
> }
> ```
> 
> ```
> export const DEFAULT_SYSTEM_TEMPLATE = `
> You are ChatGPT, a large language model trained by OpenAI.
> Knowledge cutoff: {{cutoff}}
> Current model: {{model}}
> Current time: {{time}}
> Latex inline: $x^2$ 
> Latex block: $$e=mc^2$$
> `;
> ```
> 
> 我想问一下 因为我不想要这个 system

you need to change it for yourself, but its not recommended 
better use `masks` if want customize because `DEFAULT_SYSTEM_TEMPLATE` is system prompts for prevent bad hallucination AI (e.g its become weird)
this one : 
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/d5709186-181d-4ecd-9aff-76923b87905c)

**Comment by duolabmeng6** [comment]
谢谢
