### ISSUE TITLE
[Bug] 仅启用一种模型的情况下，默认会选择gpt-3.5-turbo

### ISSUE THREAD

**Issue by itcodes** [Yidadaa/ChatGPT-Next-Web#3341]
**我在使用环境变量CUSTOM_MODELS的时候遇到一个问题，-all,+gpt-4-1106-preview这条指令应该是仅启用 gpt-4-1106-preview。
实际部署好发现默认会用gpt-3.5-turbo。**
### 复现步骤
**图 1，这是我后台设置可选模型**
<img width="912" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8282645/b82e1954-151e-4fbf-977e-667f162115da">
**图 2，我在输入测试的时候还是提示you are not allowed to use gpt-3.5-turbo model**
<img width="932" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8282645/ce6037f8-12f2-4d76-8fa8-f8c715bebb9a">
**图 3，我在下方重新选一下模型再测试就是正常，应该是默认给了gpt-3.5-turbo**
<img width="962" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8282645/81596425-f3ad-4308-abee-b7a42587cb01">
<img width="718" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8282645/db6b698b-4e8a-46ec-8135-ad2914e5816b">
**图 4，我重新选择一下模型，就会恢复正常。**
<img width="701" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/8282645/ff7c6316-4e1f-4d2a-ab5c-8f4417367eba">
### 部署方式
Vercel

**Comment by Yidadaa** [comment]
最新版本代码会自动选中第一个可用模型。

**Comment by itcodes** [comment]
> 最新版本代码会自动选中第一个可用模型。

是最新的 2.9.12 版本吗？我看我的还是这个问题。

**Comment by Towski0804** [comment]
我也出现了和  @itcodes  一模一样的问题，我来增加一些细节。当我创建新对话的时候会有短暂的弹窗，显示的确实是我的第一个可用模型，如下图
![1](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49519644/3d4564e9-0618-43d3-b1a9-e6a9e046d73f)
但当我什么操作都不做，直接开始对话的时候，就会发现实际在发送请求的时候还是会默认会用gpt-3.5-turbo，之后就是和 @itcodes 所经历的一模一样了。
![2](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49519644/1369f44d-1ddf-4b55-ba7a-c70d1c4a991d)
这时候在这里手动选择后就可以正常使用了。

**Comment by NPC-JIN** [comment]
遇到同样的问题，在环境变量中设置默认模型，的确可以使得打开web的第一次对话试用模型为默认模型，但打开新的对话，又变成3.5-turbo模型
