### ISSUE TITLE
[Feature] 头部高度建议缩小点

### ISSUE THREAD

**Issue by Jesn** [Yidadaa/ChatGPT-Next-Web#3346]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

感觉对话框上面的这个头部高度太高了，是否可以降低点高度，或者让其自动折叠起来？
在笔记本上头部和下面的输入框感觉占用了很大一部分空间，内容部分显示受限
<img width="1506" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/5728274/4c6040fd-da78-4eeb-83ea-aa2da0c14b0e">

**Comment by Yidadaa** [comment]
你可以自行 fork 一份定制自己的 UI。
