### ISSUE TITLE
[Bug] CUSTOM_MODELS使用问题

### ISSUE THREAD

**Issue by itcodes** [Yidadaa/ChatGPT-Next-Web#3349]
环境变量哪里配置了-all,+gpt-3.5-turbo-1106
实际上默认指定模型还是gpt-3.5-turbo，每次新建聊天时候，都必须要勾选一下模型，个是我部署的问题吗？
还是说至少部署 2 个模型。
部署方式：vercel 当前版本：2.9.12

**Comment by dq7532183** [comment]
确实是这个bug,原因是默认模型就是gpt-3.5-turbo
希望作者加一个环境变量,能够设置默认模型.    需求是,只使用gpt4-1106
