### ISSUE TITLE
不止有填写api_key,还需要填写一个访问码是什么意思？

### ISSUE THREAD

**Issue by 18033083746** [Yidadaa/ChatGPT-Next-Web#335]

**Comment by crow4586** [comment]
访问码是这个程序精髓，但好像有BUG，API KEY只需一个，添加访问码相当于给他开了多用户，如此分享给别人时只需要分享不同的访问码，避免API KEY泄露问题。
但我根据说明 CODE 添加多组密码后只有第一个密码可以登录，目前不明原因。

**Comment by crow4586** [comment]
> 访问码是这个程序，bug，api键，只只需一个，添加只一一，添加添加相当于给给给给他了了了多多，如此了多，如此开了了了了如此如此如此如此分享分享给别人别人时时时只时需要需要分享 分享我根据说明码添加多组密码后只有第一个密码可以登录，目前不明原因。

重新部署 解决上边多密码问题。
