### ISSUE TITLE
[Feature] Google AI [PaLM]

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Yidadaa/ChatGPT-Next-Web#3353]
this ai have chat system which is supported

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/f24abaa4-08ae-4cdd-91c4-64e0d51a1763)

Docs : https://ai.google/discover/palm2/

**Comment by Yidadaa** [comment]
我不准备兼容任何 OpenAI 之外的模型，如果用户需要，他们应该去使用 https://github.com/songquanpeng/one-api

**Comment by H0llyW00dzZ** [comment]
well it's kinda boring while only openai

**Comment by Yidadaa** [comment]
You must admit that the usability of models other than OpenAI is very poor, there is no need to waste time on them, and many models are missing advanced capabilities such as function calling and image understanding. If we support these models, we will spend a lot of energy to Address these compatibility issues.

**Comment by H0llyW00dzZ** [comment]
> You must admit that the usability of models other than OpenAI is very poor, there is no need to waste time on them, and many models are missing advanced capabilities such as function calling and image understanding. If we support these models, we will spend a lot of energy to Address these compatibility issues.

it's better wait then

**Comment by Algorithm5838** [comment]
Check this: https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/3361
