### ISSUE TITLE
🌟【功能请求】 📑  引入标签页式布局 &  🌈 使用彩色卡片区分说话者角色，以提升ChatGPT-Next-Web交互体验

### ISSUE THREAD

**Issue by hycxnas** [Yidadaa/ChatGPT-Next-Web#3358]
**这个功能与现有的问题有关吗？**
目前在使用ChatGPT-Next-Web与大型语言模型（LLM）交互时，存在两个问题：一是在要求LLM对同一问题提供多版本回答时，管理和比较这些回答的方式不够直观与有效；二是在对话页面上，不同说话者的区分不够明显。

**你想要什么功能或者有什么建议？**
1. 我建议开发一种类似于浏览器标签页的布局，可以将对于同一个问题的不同版本的回答折叠起来，方便比较和选取。用户可以通过点击不同的标签来查看不同的回答草稿，并选取其中一个采纳到到对话上下文中，而未被选中的草稿则不会被纳入后续对话中，这可以减少LLM对用户意图的误解和节省API的成本开销。
2. 另外，我建议为不同的说话者分配不同的色卡，并将对应颜色渲染到其对话中，以增强用户识别不同角色言语的能力，快速定位对话中的信息。颜色标签可通过颜色和透明度不同来区分，例如系统信息为浅红色、用户为浅蓝色、机器人回答为淡紫色等，并允许用户自定义不同角色所使用的标志色。这将极大提升用户在快速锁定特定角色的发言和信息追踪上的效率，优化用户体验。

**有没有可以参考的同类竞品？**
对于第一个功能，Google Bard的网页版提供了类似的布局，在每个独立的回答轮次中有多个版本时，用户能够选择一个进行展示与互动。
对于第二个功能，一些即时通讯应用，如Slack，允许用户自定义消息主题颜色，以便更容易地区分不同的参与者。

**其他信息**
实施这些功能的话，不仅可以改善用户在使用ChatGPT-Next-Web时的体验，还有助于将项目与其他竞品区分开来，提升竞争力。希望开发团队能考虑到这些建议，并期待看到这些功能的实际落地。谢谢！

**Comment by devyujie** [comment]
太烧token了

**Comment by hycxnas** [comment]
> 太烧token了

事实上Token的消耗并不会因为这个改进而异常增加，因为所有的增量成本只来自用户手动触发的Re-generate操作。

只有被选中的Draft会被纳入后续的交互上下文中，其余部分只会在本地显示和存储，不会产生Token Input的成本。

**Comment by Yidadaa** [comment]
你是否在找：https://chromewebstore.google.com/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma

**Comment by kitaev-chen** [comment]
其实就是类似 ChatHub 这种功能，但 ChatHub 费用太高比较扯蛋。平时大家在 NextChat 的操作一般是建立多个标签，分别选择不同的模型，然后不停地复制粘贴，得到不同模型对同一个问题的回复，频繁切换标签来对比回复内容。

建议引入tab group的概念，一个group中的tab，可以像 ChatHub 一样的布局，或者块状随意拖动布局，集体响应同一个输入。
