### ISSUE TITLE
[Bug] 内存泄露

### ISSUE THREAD

**Issue by ShinChven** [Yidadaa/ChatGPT-Next-Web#3360]
**描述错误**
在使用 ChatGPT Next v2.9.12 版本时，如果聊天记录很多（大约800+条消息），会出现严重的内存泄露问题。一个浏览器标签页的内存占用可能超过9GB。这个问题似乎在从旧版本软件迁移数据时发生。

**复现步骤**
复现行为的步骤：
1. 在 Chrome 浏览器中打开 ChatGPT Next v2.9.12。
2. 进行对话以积累大量聊天记录（在我的案例中，超过800条消息）。
3. 监控运行 ChatGPT Next 的浏览器标签页的内存使用情况。
4. 观察到内存消耗增加到9GB以上。

**预期行为**
预期的行为应该是应用程序能够高效管理内存，不论聊天记录的条数多少。内存使用应保持在合理的限制范围内，并且随着消息积累不会不成比例地增加。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**部署**
- [x] Docker
- [ ] Vercel
- [ ] 服务器

**桌面端（请完成以下信息）：**
 - 操作系统：macOS 11.7.10
 - 浏览器：Chrome
 - 版本：119.0.6045.123（正式版本）(x86_64)

**智能手机（请完成以下信息）：**
 - 设备：[不适用 - 问题出现在桌面端]
 - 操作系统：[不适用 - 问题出现在桌面端]
 - 浏览器：[不适用 - 问题出现在桌面端]
 - 版本：[不适用 - 问题出现在桌面端]

**附加日志**
在这里添加任何与问题有关的日志，比如浏览器开发者工具中的控制台输出、内存快照等。

**Comment by H0llyW00dzZ** [comment]
I'm aware of this issue. 
Related to [Feature] Syncing Feature: Archive Old Chats #2832

> [!TIP]
> In desktop app still can handle (was reached 400+ messages in 1 chats)

**Comment by H0llyW00dzZ** [comment]
Also the main problem is `a serious memory leak problem will occur.` its in render

**Comment by Yidadaa** [comment]
#2433
