### ISSUE TITLE
[Bug] 容器部署，通过内网穿透访问只有我自己的设备能使用，其他人无法范围跟

### ISSUE THREAD

**Issue by lemon5227** [Yidadaa/ChatGPT-Next-Web#3362]
**Describe the bug**
docker
`docker run -d -p 3000:3000 \
-e OPENAI_API_KEY="https://chat.xxx" \
-e CODE="lemon" \
-e HIDE_USER_API_KEY=1 \
-e PROXY_URL=http://127.0.0.1:7890 \
yidadaa/chatgpt-next-web`

除了我自己的设备访问全都报错，
`{
  "cause": {
    "name": "ConnectTimeoutError",
    "code": "UND_ERR_CONNECT_TIMEOUT",
    "message": "Connect Timeout Error"
  }
}`
在issue上看了一遍以为是代理问题，我跑docker的服务器上已经有clash，所以改变docker
`docker run -d -p 3000:3000 \
-e OPENAI_API_KEY="https://chat.xxx" \
-e CODE="lemon" \
-e HIDE_USER_API_KEY=1 \
-e PROXY_URL=http://127.0.0.1:7890 \
yidadaa/chatgpt-next-web`
然后还是只有我一个人的设备能访问，其他人的报错发生变化
`{
  "cause": {
    "errno": -111,
    "code": "ECONNREFUSED",
    "syscall": "connect",
    "address": "224.0.0.1",
    "port": 443
  }
}`

**Comment by Yidadaa** [comment]
这和项目无关，自行排查。

**Comment by yellow13441** [comment]
@lemon5227 https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/issues/1014#issuecomment-1856344942
