### ISSUE TITLE
[Feature] 我在本地部署了清华大模型，我希望使用docker是能直接把api地址填上去

### ISSUE THREAD

**Issue by lemon5227** [Yidadaa/ChatGPT-Next-Web#3363]
我测试了 
docker run -d -p 3000:3000 \
-e BASE_URL="https://chat.10111.xyz" \
yidadaa/chatgpt-next-web

docker run -d -p 3000:3000 \
-e OPENAI_API_KEY="https://chat.10111.xyz" \
yidadaa/chatgpt-next-web
都不能实现这个功能
只能打开页面然后手动勾选自定义接口
然后填入我自己部署的大模型api地址
这样就可以分享给他人使用的时候做到，打开就能使用

**Comment by iamsad3508** [comment]
i think you can share your link like this format
https://example.com/#/?settings={"key":"sk-xxxxxxx","url":"api.example.com"}

**Comment by radishyell** [comment]
这个问题好像没解决，我只要在不同浏览器打开  都要手动填写一次自定义接口和密码

**Comment by radishyell** [comment]
已经收到您的邮件，我会尽快给您回复。O(∩_∩)O~
