### ISSUE TITLE
setting "max_tokens" should be separated into "max_accumulated_tokens" and "max_tokens_to_generate"

### ISSUE THREAD

**Issue by Pear-sudo** [Yidadaa/ChatGPT-Next-Web#3366]
**Is your feature request related to a problem? Please describe.**

“单次回复限制”的设置名不副实，代码的实际的逻辑是：
比较累计的词数，如果累计词数大于该限制，就终止将前一个历史消息附加到新的request中；
但openai api里的"max_tokens"是限定即将生成的消息的长度，如果超出就终止生成，来限定开支，但可能会影响使用体验。

这两个设定都有各自的作用，所以建议一分为二，把现在的“单次回复限制”更名为”历史词数限制“，另外新增”生成词数限制“，直接对应openai官网的"max_tokens"。

Currently, there is only one setting named "max_tokens", this is quite misleading. I looked at the source code, this "max_tokens" is used to decide the number of accumulated tokens to ATTACH:
<img width="538" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/82039974/b70fcf78-fdfd-477d-ad6a-445ec509cd02">

This is different from the "max_tokens" in openai's official API [document:](https://platform.openai.com/docs/api-reference/chat/create)
<img width="618" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/82039974/773299b7-899d-4e46-92c1-6b1de336e5e3">
Here, ""max_tokens" is limiting the number of tokens the model is GOING TO generate.
So, if it is very small, the response would be interrupted abruptly (This is the feature I need! The cost needs to be controlled!):
<img width="830" alt="Screenshot 2023-11-24 at 21 30 02" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/82039974/79df8a0c-9e7a-48d9-bf45-678319eabef2">

These are two very different concepts, so its better to have two separate settings.

**Describe the solution you'd like**
option "max_tokens" should be separated into "max_accumulated_tokens" and "max_tokens_to_generate";
"max_accumulated_tokens" has already been implemented in the current app logic.
"max_tokens_to_generate" has not yet been implemented.

**Comment by H0llyW00dzZ** [comment]
openai was changed that confusing feature before it used to be max_tokens in old UI playground

anyways its bad max_tokens or whatever that confusing feature always break LLMs

**Comment by H0llyW00dzZ** [comment]
here is example how that max_tokens or whatever its so bad in latest models gpt-4 preview


![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/29f536c6-f503-4aa2-bacc-e333ed7c5381)


old models (gpt-3.5-turbo-16k-0613): 


![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/b2cb6da6-e175-44ee-b5f1-ba0f4ccd6f8b)

**Comment by H0llyW00dzZ** [comment]
> Thanks for your reply,
> 
> Yes, OpenAI's setting "breaks" the LLM because the response is terminated before finishing. I bet most users don't need OpenAI's version of max_tokens but prefer your personal implementation of max_tokens. And separating it into two does confuse more users. However, I do believe a small handful advanced users do need a separate setting that sets OpenAI's "max_tokens" in request to control cost, knowing this would "break" the response.
> 
> Maybe consider adopt the methodology of "progressive disclosure", that is, hide this advanced setting in a deep menu, such as in "advanced" section of settings. Thus to strike a balance between most users' need and some advanced users' need.
> 
> Anyway, I am happy to hear this is a thoughtful design rather than a bug. Keep it if you like :)

well tbh it's still bad I was figure out how it work so many times about that confusing max_tokens

and in the example I show, that max tokens it's already 4K I tryna set, then I leave it because waste credit balance just for figure out how that work bad feature.

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/1965655e-a1fb-4ed8-bad9-1bea73c8a01f)


so for OpenAI if they forcing max_tokens for all models then don't bring name about LLM's  (aka large language models)
