### ISSUE TITLE
[Bug] 云端数据同步错误

### ISSUE THREAD

**Issue by goxigo** [Yidadaa/ChatGPT-Next-Web#3373]
修改了本地配置，同步之后总用云端的配置覆盖本地配置

**Comment by jkjoker** [comment]
我也遇到这个问题了，具体是：
我使用的是最新的windows桌面端
我配置了webdav，输入了api地址和key，能正常使用
但是，一但点击同步，输入的api地址和key就失效了，需要重新输入才可使用
谢谢

**Comment by Yidadaa** [comment]
#3001 #3006
