### ISSUE TITLE
BASE_URL=https://chatgpt1.nextweb.fun/api/proxy 和BASE_URL=https://open.aiproxy.xyz都不能使用了，请问您知道如何解决吗？

### ISSUE THREAD

**Issue by zhaoyuan020** [Yidadaa/ChatGPT-Next-Web#3377]
#BASE_URL=https://chatgpt1.nextweb.fun/api/proxy
#BASE_URL=https://open.aiproxy.xyz
这些代理都不能用了，有哪位知道如何解决吗？

**Comment by Yidadaa** [comment]
`a.nextweb.fun/api/proxy`
