### ISSUE TITLE
微信打开链接设置会报错：Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by thinkersOne** [Yidadaa/ChatGPT-Next-Web#338]
从微信打开链接，然后点击"设置"会出现一下报错：Application error: a client-side exception has occurred (see the browser console for more information)
![image](https://user-images.githubusercontent.com/19427384/229324853-626284e4-c56d-4fcb-a6e5-fffd7f24085f.png)

**Comment by AprilNEA** [comment]
#322

**Comment by thinkersOne** [comment]
问题依然存在
