### ISSUE TITLE
[Bug] cf部署报错ERROR: Failed to produce a Cloudflare Pages build from the project.

### ISSUE THREAD

**Issue by xzygreen** [Yidadaa/ChatGPT-Next-Web#3380]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
使用cf部署3‘28时报错
**如何复现**
请告诉我们你是通过什么操作触发的该问题。
正常操作到3’28是出现
**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
<img width="1424" alt="截屏2023-11-26 16 01 25" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/125412114/be4720fb-ee87-4a5b-9ad9-1074a38d7ec5">
<img width="1122" alt="截屏2023-11-26 16 01 51" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/12541211
<img width="901" alt="截屏2023-11-26 16 02 17" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/125412114/8afeb047-8a47-4e17-a10a-9f4cf780024e">
4/6dfb3635-f35f-43df-88a7-e194840ff552">
[gpt-3-5.9c0cfc1c-62f9-417f-a8f0-08bc3a11ce03.log](https://github.com/Yidadaa/ChatGPT-Next-Web/files/13466225/gpt-3-5.9c0cfc1c-62f9-417f-a8f0-08bc3a11ce03.log)

**一些必要的信息**
 - 系统：macos14
 - 浏览器：chrome, safari
 - 版本：120.0.6099.28（正式版本）beta (arm64)
 - 部署方式：clouldflare部署

**Comment by H0llyW00dzZ** [comment]
replace this to edge 
```ts
export const runtime = "nodejs";
```
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/b21931c667abf2825eca43d59f794471420c1db0/app/api/cors/%5B...path%5D/route.ts#L43C1-L43C33

**Comment by xzygreen** [comment]
请问如何替换，谢谢
