### ISSUE TITLE
[Bug] 是不是自动生辰标题都不起作用了？

### ISSUE THREAD

**Issue by iamsad3508** [Yidadaa/ChatGPT-Next-Web#3381]
**Describe the bug**
至少v2.9.12没有自动生成标题

**To Reproduce**
1. 就说话
**Expected behavior**
生成标题.

**Screenshots**

**Deployment**
- [ *] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [pixel5]
 - OS: [android14]
 - Browser [chrome]
 - Version [2.9.12]

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
> **Describe the bug** 至少v2.9.12没有自动生成标题
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. 就说话
>    **Expected behavior**
>    生成标题.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Deployment**
> 
> * [ *] Docker
> * [ ]  Vercel
> * [ ]  Server
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [pixel5]
> * OS: [android14]
> * Browser [chrome]
> * Version [2.9.12]
> 
> **Additional Logs** Add any logs about the problem here.

you mean this ? make sure its enabled, and its enabled by default

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/99e2a225-271a-4c06-aef0-770236b093d4)

**Comment by H0llyW00dzZ** [comment]
> > > **Describe the bug** 至少v2.9.12没有自动生成标题
> > > **To Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. 就说话
> > >    **Expected behavior**
> > >    生成标题.
> > > 
> > > **Screenshots** If applicable, add screenshots to help explain your problem.
> > > **Deployment**
> > > 
> > > * [ *] Docker
> > > * [ ]    Vercel
> > > * [ ]    Server
> > > 
> > > **Desktop (please complete the following information):**
> > > 
> > > * OS: [e.g. iOS]
> > > * Browser [e.g. chrome, safari]
> > > * Version [e.g. 22]
> > > 
> > > **Smartphone (please complete the following information):**
> > > 
> > > * Device: [pixel5]
> > > * OS: [android14]
> > > * Browser [chrome]
> > > * Version [2.9.12]
> > > 
> > > **Additional Logs** Add any logs about the problem here.
> > 
> > 
> > you mean this ? make sure its enabled, and its enabled by default
> > ![image](https://private-user-images.githubusercontent.com/17626300/285698970-99e2a225-271a-4c06-aef0-770236b093d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTU3MjYsIm5iZiI6MTcwMTA1NTQyNiwicGF0aCI6Ii8xNzYyNjMwMC8yODU2OTg5NzAtOTllMmEyMjUtMjcxYS00YzA2LWFlZjAtNzcwMjM2YjA5M2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAzMjM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOTJmOGQ3N2E1MDZjMzQxYjY3MDgxOWYxYzIxNWQ3ZTY1MDA5YmYxODAzNDY4NDBiMmU0MGVhMWM5YWUzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7-R2CZdBOdCSWmyU8ni_ADy75lyA-3xB7R_SJTcxHc)
> 
> 这个我开了，现在我认为应该是one-api的问题，因为我换成openai的地址和key是可以的

you may need to put `stream: true,` in `chat.ts`

in this one 

```ts
          api.llm.chat({
            messages: topicMessages,
            config: {
              model: getSummarizeModel(session.mask.modelConfig.model),
            },
```

by replacing like this

```ts
          api.llm.chat({
            messages: topicMessages,
            config: {
              model: getSummarizeModel(session.mask.modelConfig.model),
              stream: true,
            },
```

Link: https://github.com/Yidadaa/ChatGPT-Next-Web/blob/b21931c667abf2825eca43d59f794471420c1db0/app/store/chat.ts#L493C1-L497C15

**Comment by H0llyW00dzZ** [comment]
> [!NOTE]  
> by replacing putting that stream as `true`, it made response as text-stream in openai/azure
