### ISSUE TITLE
功能咨询-是否支持设置默认的gpt模型

### ISSUE THREAD

**Issue by shangmin2009** [Yidadaa/ChatGPT-Next-Web#3384]
请问一下目前支持指定默认的model吗？
我想指定默认的模型为MODEL_NAME=gpt-4-1106-preview，也成功加到docker的env里面了，但是打开新的网页，模型还是3.5-turbo，是目前不支持更改这个吗？
xxx@ps0:/data/chatgpt$ sudo docker exec chatgpt env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MODEL_NAME=gpt-4-1106-preview

**Comment by H0llyW00dzZ** [comment]
cek this pull req fix(CUSTOM_MODELS):#3349 Dependency chatStore otherwise the session a… #3356

**Comment by shangmin2009** [comment]
> cek this pull req fix(CUSTOM_MODELS):#3349 Dependency chatStore otherwise the session a… #3356

OK，I understand. At this moment, if I want to set the default model, I have to edit the source code(just one line), right?

**Comment by H0llyW00dzZ** [comment]
> > cek this pull req fix(CUSTOM_MODELS):#3349 Dependency chatStore otherwise the session a… #3356
> 
> OK，I understand. At this moment, if I want to set the default model to gpt-4-1106-preview, I have to edit the source code(just one line), right?

yes

**Comment by shangmin2009** [comment]
There is an image have fix this:
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3335#issuecomment-1824298639

**Comment by H0llyW00dzZ** [comment]
> There is an image which has fixed this bug: [#3335 (comment)](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3335#issuecomment-1824298639)

you can use that image if it's already fixed a bug

**Comment by shangmin2009** [comment]
> > There is an image which has fixed this bug: [#3335 (comment)](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3335#issuecomment-1824298639)
> 
> you can use that image if it's already fixed a bug

Thank you, My problem has fixed

**Comment by duolabmeng6** [comment]
How to solve it...ah?
