### ISSUE TITLE
功能咨询-预览气泡有没有全局的设置开关？

### ISSUE THREAD

**Issue by shangmin2009** [Yidadaa/ChatGPT-Next-Web#3386]
请问预览气泡有没有全局的设置开关，想把这个都关了。

<img width="655" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/86669146/2ca3c9cb-f7cb-46e8-a8aa-a92ae53e7958">

**Comment by shangmin2009** [comment]
> > 请问预览气泡有没有全局的设置开关，想把这个都关了。
> > <img alt="image" width="655" src="https://private-user-images.githubusercontent.com/86669146/285743732-2ca3c9cb-f7cb-46e8-a8aa-a92ae53e7958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjgyNTEsIm5iZiI6MTcwMTA2Nzk1MSwicGF0aCI6Ii84NjY2OTE0Ni8yODU3NDM3MzItMmNhM2M5Y2ItZjdjYi00NmU4LWE4YWEtYTkyYWU1M2U3OTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA2NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMGVjMDhiMjZjYTEwYmFkY2Q2ODlmNzJmMjkxYTZkZWM0M2ZmNjZiOGUxZTZiMTU3ZDY1OWI2YTE0MWNhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Mus7ixSl-1w9nj0yJtSamb_vZzvb1_M6cgyBKDcEd8">
> 
> yes that one

But when I open a new window in another browser, it is still open. How can I close it for all?

**Comment by shangmin2009** [comment]
> > > > 请问预览气泡有没有全局的设置开关，想把这个都关了。
> > > > <img alt="image" width="655" src="https://private-user-images.githubusercontent.com/86669146/285743732-2ca3c9cb-f7cb-46e8-a8aa-a92ae53e7958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjgyNTEsIm5iZiI6MTcwMTA2Nzk1MSwicGF0aCI6Ii84NjY2OTE0Ni8yODU3NDM3MzItMmNhM2M5Y2ItZjdjYi00NmU4LWE4YWEtYTkyYWU1M2U3OTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA2NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMGVjMDhiMjZjYTEwYmFkY2Q2ODlmNzJmMjkxYTZkZWM0M2ZmNjZiOGUxZTZiMTU3ZDY1OWI2YTE0MWNhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Mus7ixSl-1w9nj0yJtSamb_vZzvb1_M6cgyBKDcEd8">
> > > 
> > > 
> > > yes that one
> > 
> > 
> > But when I open a new window in another browser, it is still open. How can I close it for all?
> 
> if you are open a new window in another browser, its because different local storage and default is enabled you have to disabled it by untick

I know, I just want to ask if there is param to close it for all when I start chatgpt-next-web

**Comment by H0llyW00dzZ** [comment]
> > > > > 请问预览气泡有没有全局的设置开关，想把这个都关了。
> > > > > <img alt="image" width="655" src="https://private-user-images.githubusercontent.com/86669146/285743732-2ca3c9cb-f7cb-46e8-a8aa-a92ae53e7958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjgyNTEsIm5iZiI6MTcwMTA2Nzk1MSwicGF0aCI6Ii84NjY2OTE0Ni8yODU3NDM3MzItMmNhM2M5Y2ItZjdjYi00NmU4LWE4YWEtYTkyYWU1M2U3OTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA2NTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMGVjMDhiMjZjYTEwYmFkY2Q2ODlmNzJmMjkxYTZkZWM0M2ZmNjZiOGUxZTZiMTU3ZDY1OWI2YTE0MWNhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Mus7ixSl-1w9nj0yJtSamb_vZzvb1_M6cgyBKDcEd8">
> > > > 
> > > > 
> > > > yes that one
> > > 
> > > 
> > > But when I open a new window in another browser, it is still open. How can I close it for all?
> > 
> > 
> > if you are open a new window in another browser, its because different local storage and default is enabled you have to disabled it by untick
> 
> I know, I just want to ask if there is param to close it for all when I start chatgpt-next-web

I don't know about that but it's seem this

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/9cbf899c-a3b8-4f1d-8e38-a8e664b24af2)

**Comment by shangmin2009** [comment]
OK, thank you, I will try this
