### ISSUE TITLE
手机UI建议

### ISSUE THREAD

**Issue by yvyan** [Yidadaa/ChatGPT-Next-Web#34]
在手机浏览器使用时，输入字符后输入框会刷新到最下方，被输入法遮挡，导致无法看到之前输入的内容。
复现环境：安卓版Edge 110  百度输入法  MIUI14。

另外，建议输入页面展示使用类似于聊天软件的形式，只在发送信息后展示对话框，而不是对话框随着输入框实时更新，视觉上感觉有一点点儿怪。

**Comment by Yidadaa** [comment]
移动端适配一直是比较难搞的问题，现在秉承的思路是能用就行，不会花费太多精力在上面，毕竟还有很多高优先级的事情要处理。

关于对话框的形式，这是因为输入框支持 markdown 输入，右侧用户气泡是为了能够实时预览用户输入的 markdown 内容，这个不会改动，后期可能会加个开关。

**Comment by yvyan** [comment]
好的，大致了解了，增加一个开关是可行的，文本输入中md的比例应该还是偏小的，希望可以自由选择

**Comment by Cp0204** [comment]
即使没有输入，电脑端总是会自动滚屏。

实测是：手动翻到上面内容后，只要鼠标焦点离开对话列表，一会又自动滚到底端了。

我的使用场景是让GPT修改代码，在IDE和浏览器之间来回切换。浏览开头代码时，总是跳到末尾，不是很方便。

**Comment by Yidadaa** [comment]
已经修改为当且仅当输入框聚焦时才会开启自动滚动，请等待下个版本更新。
