### ISSUE TITLE
[Bug] 不填写接口地址, 触发azure内容审核时, 直接出现404, 无法正常报错

### ISSUE THREAD

**Issue by KamiPasi** [Yidadaa/ChatGPT-Next-Web#3401]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
如果不填写接口地址, 只填写key, 触发azure内容审核时, 会直接出现404, 不会接着重试

**如何复现**
1. 使用oneapi里部署的azure渠道, 部署next-web, 环境变量填上接口地址
2. 尝试使用违禁词触发报错
3. 自行填入接口地址时正常报错
4. 删掉接口地址, 只保留key时, 直接404

**截图**
- 填写接口地址时能够正常重试报错
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/92498495/bde03cdd-44c3-42ad-b6d8-38437ca3fb98)
- 删掉接口地址,只填写key, 直接404
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/92498495/9c780f8d-810e-4cec-a6c1-10b717982d0b)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器： chrome, Edge
 - 版本： 最新版本
 - 部署方式：vercel、docker

**Comment by H0llyW00dzZ** [comment]
> > 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。
> 
> > [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)
> 
> **反馈须知**
> 
> ⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。
> 
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
> 
> * [x]  我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
> * [x]  我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
> * [x]  我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。
> 
> **描述问题** 如果不填写接口地址, 只填写key, 触发azure内容审核时, 会直接出现404, 不会接着重试
> 
> **如何复现**
> 
> 1. 使用oneapi里部署的azure渠道, 部署next-web, 环境变量填上接口地址
> 2. 尝试使用违禁词触发报错
> 3. 自行填入接口地址时正常报错
> 4. 删掉接口地址, 只保留key时, 直接404
> 
> **截图**
> 
> * 填写接口地址时能够正常重试报错
>   ![image](https://private-user-images.githubusercontent.com/92498495/286341815-bde03cdd-44c3-42ad-b6d8-38437ca3fb98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTIyMTgsIm5iZiI6MTcwMTE5MTkxOCwicGF0aCI6Ii85MjQ5ODQ5NS8yODYzNDE4MTUtYmRlMDNjZGQtNDRjMy00MmFkLWI2ZDgtMzg0MzdjYTNmYjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE3MTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDJmNmNkMjFhNzA4ZDJiMzZjNTA4ODQ5YTJhMTQ5MWE1NTk0MjkwZjdlNDg1NGQ1MDRiZmExMWRkNTJiZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pM-rtEDNnKl80NJgDxTg6U11R6zvlzQZCiS1HXxTY-k)
> * 删掉接口地址,只填写key, 直接404
>   ![image](https://private-user-images.githubusercontent.com/92498495/286342184-9c780f8d-810e-4cec-a6c1-10b717982d0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTIyMTgsIm5iZiI6MTcwMTE5MTkxOCwicGF0aCI6Ii85MjQ5ODQ5NS8yODYzNDIxODQtOWM3ODBmOGQtODEwZS00Y2VjLWE2YzEtMTBiNzE3OTgyZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE3MTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NmM5MmM0YjMyMmM3NDVlZmExMGQyZWQzNzg3ODQ0MmNjYzgzN2U3MTIwZjZhMTZmYzZiZTM1YTNkNjJlNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LY3CG2TSux6NGXj1ZzaqsZiqKJlVVpAYgOaMrJoySg4)
> 
> **一些必要的信息**
> 
> * 系统：windows 10
> * 浏览器： chrome, Edge
> * 版本： 最新版本
> * 部署方式：vercel、docker

can you give me a example prompt for test triggering azure openai content policy (I haven't try and figure out how it work) ?

**Comment by Yidadaa** [comment]
one api 的问题去 one api 仓库里反馈。
