### ISSUE TITLE
设置授权码后，仍一直显示 现在是未授权状态，请在设置页填写授权码。

### ISSUE THREAD

**Issue by minicloudsky** [Yidadaa/ChatGPT-Next-Web#341]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/32286819/229329884-24042a44-9146-49fc-9295-82b66b6b1127.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/32286819/229329889-b07ff331-2830-4046-a812-9cc2cdba3bc3.png">

**Comment by AprilNEA** [comment]
请问是何种部署方式，以及是否方便打开给出一些日志记录（Vercel Console，浏览器Console）

**Comment by AprilNEA** [comment]
Docker 可参考 #265

**Comment by minicloudsky** [comment]
> 请告知是何种部署方式，并给出一些日志记录（Vercel Console，浏览器Console）

vercel fork项目后部署，配置环境变量重新部署后解决了，感谢大佬
