### ISSUE TITLE
拼音中带有英文单词时，回车会发送消息

### ISSUE THREAD

**Issue by leadream** [Yidadaa/ChatGPT-Next-Web#342]
如下面的视频，在设置中设置了 Enter 即发送，输入拼音时回车预期的是在输入框中输入 js 但不发送，实际上被发送出去。

https://user-images.githubusercontent.com/12868055/229329875-6b21bc13-d888-492f-9655-68ff0b54cdcb.mov

BTW，我在部署时填写了 API_KEY，部署成功后打开页面还是要在设置中填写 API_KEY。

**Comment by AprilNEA** [comment]
1. 重复 issue #331 
2. 如果是Vercel，在确认`api key`无误后，可以尝试重新部署
