### ISSUE TITLE
[Bug] Configure the API key in settings initially. Upon enabling HIDE_USER_API_KEY, a 401 response is received.

### ISSUE THREAD

**Issue by Seize-cf** [Yidadaa/ChatGPT-Next-Web#3422]
**Describe the bug**
1. configure API key in the settings
2. add env variable in Vercel
3. rebuild project
4. 401 received

**To Reproduce**
1. configure API key in the settings
2. add env variable in Vercel
3. rebuild project
4. start a new conversion
5. 401 received

**Expected behavior**
use server-side API key, instead of API key in local storage

**Screenshots**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/39005402/b0611640-8489-44c9-9a96-d7f465726fc3)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 119

**Comment by H0llyW00dzZ** [comment]
work's fine 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/08950db6-1ee0-4980-a07b-055fd1f4c04e)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/151ebbbb-6a77-4e23-a6da-5e5e277cc367)




![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/b60e90c2-b39e-4fb2-b140-cf2305744f50)

**Comment by Yidadaa** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/89d58ed3-b975-4bc9-97d7-ee5b8382ce63)

**Comment by Yidadaa** [comment]
你可以通过清空浏览器数据的方式让你最新的设置生效。
