### ISSUE TITLE
[Bug] webdav同步问题

### ISSUE THREAD

**Issue by jkjoker** [Yidadaa/ChatGPT-Next-Web#3423]
windows端目前关于使用webdav同步数据遇到的问题如下：
1、虽然使用的是坚果云webdav，但网络连接不稳定，很多时候都同步不上；
2、windows导出到本地的json文件为乱码，无法正常查看，也无法正常导入；
3、Windows通过webdav同步的json文件，是正常的，能正常查看。

综上：目前可能没法及时通过webdav同步，数据存在丢失风险（无法同步到云端，本地导出有故障）。

然后有个问题是，坚果云webdav是在国内，这个线路不应该有问题才对，这是我疑惑的地方。也许网络连接线路需要优化。谢谢

**Comment by reece00** [comment]
你买的谁网站你找他去啊你来UI论坛这里干嘛？

**Comment by jkjoker** [comment]
> 1、网络问题你买的谁网站你找他去啊你来UI论坛这里干嘛？

我是在正常反馈问题，坚果云dav在国内是可以正常访问的。什么叫来论坛干嘛？

**Comment by Yidadaa** [comment]
坚果云的 webdav 不支持 cors 跨域，我提供了内置代理来解决这个问题，但不保证可用性。导出 json 乱码仅仅是因为是编码问题，这是 windows 平台老生常谈的问题，你可以自己去检索一下解决方法。

**Comment by jkjoker** [comment]
> 坚果云的 webdav 不支持 cors 跨域，我提供了内置代理来解决这个问题，但不保证可用性。导出 json 乱码仅仅是因为是编码问题，这是 windows 平台老生常谈的问题，你可以自己去检索一下解决方法。

我做了些测试，希望有帮助：
经测试，Windows2.9.7、2.9.6都没问题，能正常导出、正常查看、正常导入，但之后的版本都有问题。

其中有个细节是，通过2.9.7导出的json文件，大小为1727kb，能正常打开，能正常导入；而通过2.9.8、2.9.9、2.9.10导出时，大小分别为1102kb、1331kb、1079kb，文件明显偏小，且大小不一致。

**Comment by kitaev-chen** [comment]
今天更新2.10后发现坚果云同步失败才知道有这个问题，持续关注。

**Comment by Robinson28years** [comment]
> 今天更新2.10后发现坚果云同步失败才知道有这个问题，持续关注。

我也是

**Comment by PinkPanther-ny** [comment]
> > 坚果云的 webdav 不支持 cors 跨域，我提供了内置代理来解决这个问题，但不保证可用性。导出 json 乱码仅仅是因为是编码问题，这是 windows 平台老生常谈的问题，你可以自己去检索一下解决方法。
> 
> 我做了些测试，希望有帮助： 经测试，Windows2.9.7、2.9.6都没问题，能正常导出、正常查看、正常导入，但之后的版本都有问题。
> 
> 其中有个细节是，通过2.9.7导出的json文件，大小为1727kb，能正常打开，能正常导入；而通过2.9.8、2.9.9、2.9.10导出时，大小分别为1102kb、1331kb、1079kb，文件明显偏小，且大小不一致。

非常感谢，是这样的，我重新下载了2.9.7版本 成功的导出了数据后，下载安装了2.10.3版本，（也测试了后面多个版本）可以将2.9.7导出的数据成功导入，但是用后面的版本导出的数据仍热是乱码且无法重新导入。
尝试修改了系统语言等，都不行。
用notepad打开可以看到，完好的导出json文件为CRLF结尾，以及UTF-8编码，而其他版本导出的乱码皆为LF结尾以及ANSI编码（修改为CRLF以及UTF-8仍是乱码），看起来并不是您所说的“老生常谈的问题” @Yidadaa

**Comment by kitaev-chen** [comment]
感觉“同步”这块还有很大优化空间，一不小心就会得到不想要的结果。最好还是分成“上传”和“下载”备份两个按钮。

**Comment by TCOTC** [comment]
我在 v2.11.3 终于可以连通坚果云 WebDAV 了（感觉可能跟 #3972 的修复有关），但不知道为什么无法上传文件到坚果云
