### ISSUE TITLE
如何支持非OPENAI官方的API和KEY

### ISSUE THREAD

**Issue by Lvjinhong** [Yidadaa/ChatGPT-Next-Web#3427]
您好！您的项目非常出色！我想知道您是怎么支持 类OPENAI的api和key的，
可以麻烦告知一下对应的代码位置吗？ 我想参考一下

代码文件我看了好久，但是更进一步的 我想知道您是如何 设计请求结构的 ，
以至于 改变url地址后依旧可以正常对接。 这对我非常重要，如果您方便，可以麻烦帮助我一下吗？ 非常感谢

**Comment by Yidadaa** [comment]
为什么不读文档？BASE_URL 和 API_KEY 就是为了兼容 openai 类型的接口而生的。

**Comment by FranzKafkaYu** [comment]
首先要非常感谢作者的项目，在部署过程中我也有类似的问题，我的API 地址基于Pandora生成,使用BASE_URL环境变量指定时发现Post请求会额外添加路径参数，导致无法正常使用；但是如果我直接在Web中设置URL地址却是可用的，请问该问题该如何解决呢

**Comment by zhangwengyu999** [comment]
Same problem, looking forward to the solution.

**Comment by zhangwengyu999** [comment]
I get the solution, change [the line 15 of the ./app/api/common.ts](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/blob/main/app/api/common.ts#L15) from 

```ts
let path = `${req.nextUrl.pathname}${req.nextUrl.search}`.replaceAll(
```
 to 

```ts
let path = `${req.nextUrl.pathname}`.replaceAll(
```
where the `${req.nextUrl.search}` is removed, so Proxy path will become `v1/chat/completions` only.

It works for me.

**Comment by rookis1** [comment]
> I get the solution, change [the line 15 of the ./app/api/common.ts](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/blob/main/app/api/common.ts#L15) from
> 
> ```ts
> let path = `${req.nextUrl.pathname}${req.nextUrl.search}`.replaceAll(
> ```
> 
> to
> 
> ```ts
> let path = `${req.nextUrl.pathname}`.replaceAll(
> ```
> 
> where the `${req.nextUrl.search}` is removed, so Proxy path will become `v1/chat/completions` only.
> 
> It works for me.

it works !

**Comment by 429383298** [comment]
> 我得到了解决方案，将 .[/app/api/common.ts 的第 15 行](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/blob/main/app/api/common.ts#L15)从
> 
> ```ts
> let path = `${req.nextUrl.pathname}${req.nextUrl.search}`.replaceAll(
> ```
> 
> 自
> 
> ```ts
> let path = `${req.nextUrl.pathname}`.replaceAll(
> ```
> 
> 其中，则代理路径将变为 only。`${req.nextUrl.search}``v1/chat/completions`
> 
> 它对我有用。

你好，请问在群晖的Docker 中如何修改？我并没有找到这个文件。
