### ISSUE TITLE
登录，注意错别字

### ISSUE THREAD

**Issue by SadPencil** [Yidadaa/ChatGPT-Next-Web#343]
`直接使用 Github 账号登陆即可` -> `直接使用 Github 账号登录即可`
`用户登陆`->`用户登录`

**Comment by AprilNEA** [comment]
参考
>在中文中，"登录"和"登陆"这两个词语在日常生活和网络术语中经常被使用，它们都表示通过输入用户名和密码等信息，进入一个系统或网站的过程。在实际使用中，这两个词语几乎是可以互换的，没有太大的区别。
>
>然而，在严格意义上，这两个词语在中文书面语中的用法略有不同。
>
>登录：更常用于计算机、网络和技术领域，表示用户通过输入用户名、密码等信息进入一个系统、平台或网站。例如：登录电脑、登录网站等。
>
>登陆：在书面语中，通常用于描述船只、飞行器或人员抵达一个地方，例如：登陆岛屿、登陆火星等。
>
>但在现实使用中，这两个词的区别已经变得模糊，它们通常可以互换使用。在网络用语中，"登录"的使用频率更高，因此如果要选择一个词用于网络环境，"登录"会是更好的选择。

**Comment by SadPencil** [comment]
此段话不包含来源。

这是最开始拼音打字偷懒的人给的坏习惯。“登录”是通过输入用户名和密码等信息进入网站或系统，“登陆”是舰船靠岸。没有可互换的意思。可参考《当代汉语词典》《新华字典》等。

不要让这个词步入“荨麻疹”“呆板”的后尘。

**Comment by Kosette** [comment]
类似的"阈值"和"阀值"😄

**Comment by Yidadaa** [comment]
@SadPencil 

语言是人类沟通的媒介，可以追求严谨，但是陷入教条主义就有点钻牛角尖了，没必要追求茴字的几种写法，已经合入你的 PR。

**Comment by SadPencil** [comment]
> @SadPencil
> 
> 语言是人类沟通的媒介，可以追求严谨，但是陷入教条主义就有点钻牛角尖了，没必要追求茴字的几种写法，已经合入你的 PR。

@Yidadaa 这不是教条主义，前面有人举了一个很好的例子，"阈值"和"阀值"。"阀值"是错误的拼写，不应出现在任何场合下。"登陆"也是一样。争议内容坚持某个观点，可以算教条主义，而"登陆"是单纯的错别字。

**Comment by Yidadaa** [comment]
@SadPencil 

你想听我的诡辩吗？

自古以来就有通假字的说法，大多说通假字都是由形近或音近的词语因为错用而流传开来，随着人们交流的大规模使用，这些通假字逐渐变成了近义字或者同义字。

语言从来不是一个静态系统，尤其是互联网出现之后，随着人类交流效率的提升，类似的错字 / 错词导致的现代通假现象只会层出不穷，事实上每隔一段时间，现代汉语词典都会根据当代人们的用语习惯对内容[进行修订](https://china.huanqiu.com/article/9CaKrnKicPZ)，我在义务教育阶段花了大力气记下的“说 shui 服”、“铁骑 ji” 早就被扫进了历史的垃圾堆。

而时下网络用语也在深刻地影响人们对文字的使用习惯，“首当其冲”“差强人意”等成语已经或者正在被各种社交平台上的人们错误地使用着，我相信这些词汇目前的“错误用法”，也将很快在不久的将来转正成为现代汉语词典的正式内容，我认为这恰恰是语言学内在的生长规律，我们当然可以日复一日地在各个平台上纠正人们关于这些词汇的正确用法，但是那些符合直觉的、易于记忆和传播的用法，始终不会消亡，所以我认为现在再纠结某个习语是否是“正确”的，没有什么太大的价值。

**Comment by SadPencil** [comment]
@Yidadaa 按照你的观点，凡是对拼写、语法做任何修正的，都是教条主义，不应该纠结任何错别字或语法错误，因为错误的写法“符合直觉、易于记忆和传播”。如此，我们可以直接扔掉字典了。例句：“这个东西要花四千米，好多Q呀，累S我才能挣到这么多Q，xswl。”

不对语言发展做限制，就会回到秦始皇实行书同文之前的年代，语言会在不同圈子内独立发展，方言化。

**Comment by Yidadaa** [comment]
@SadPencil 

请不要曲解我的意思，你举例的“四千米”“好多Q”等例子是由于国内畸形审查文化导致的语言变体，这些文字的出现完全出于用户规避平台审查的交流需要，而非用户在语义层面上进行的扩展。

如果非要举例子，大可以用互联网脏话或者烂梗的发展来反驳，比如脏话在传播中出现的语义弱化现象，让人们逐渐给正常词汇赋予脏话的引申义，这些本来属于亚文化圈子的小众用法正在逐渐侵蚀大众视野，我认为这是一个比较恰当的类比。

语言的变迁是一个需要时间检验的过程，你所举的例子以及大多数互联网烂梗的生命周期都不会超过 5 年（不严谨的说法），而类似“登陆/登录”、“差强人意”等用法，其本身在语义层面就有较强的易混性，我个人认为他们的“错误用法”转正只是时间问题。

**Comment by SadPencil** [comment]
@Yidadaa 为什么非要指出是因为审查？不管由于什么原因导致的所谓语言变体，只要其持续时间以年为单位计算，都会造成侵蚀。例如，有多少人能写出“逼”“卧槽”的原始写法？

你主张的是，凡是流行几年的用法，就不再纠正，因为流行几年之后一定会成为语言的一部分。而我主张的是，正因为语言变种会随流行时间而变得根深蒂固，所以我们需要手动干预不正确的写法，不认为凡是能流行的写法都是我们应该接受的。

**Comment by Yidadaa** [comment]
我认同你“不认为凡是能流行的写法都是我们应该接受的”的观点，我认为这件事本身不是二元的，毕竟并不是所有的用法都一视同仁，我单纯地认为“登陆/登录”已经可以等价为同义词了，但我同时认为“稍后/稍候”的混用是完全错误的用法。

**Comment by SadPencil** [comment]
@Yidadaa 如果“登录”和“登陆”可以同义了，那么类似的“阈值”和“阀值”，“密钥”和“秘钥”，是否也可以用后面的错误用法代替前面的正确用法？在大数据和智能推送时代，不能只靠一个人的信息茧房去判断什么表达可以通用，什么不可以。

我认为的标准是这样：1. 在专业领域有主流（例如权威书籍、论文等场合）用法，例如，密钥（安全领域），登录（从 Windows 开始，各种操作系统、主流软件的提示文字等，不包括比如明显缺乏维护UI都画不好的软件） 2. 该主流用法相比其他用法更能从词源的方式去解释。例如登录与日志，航海，原木的关系。满足以上两点标准的，应该予以坚持。按我这个标准，“荨麻疹”亦是如此。但可惜这个词已经被改了，我不希望有更多这种词出现。如果不符合这两条标准，改了也就改了。

**Comment by jagerzhang** [comment]
找相关issue看到这条，回复一下，无意冒犯。
issue本意挺好的，就是语气略显生硬，建议可以柔和一点，不要带有指责和批判。作者无偿开源又不欠谁，别搞得跟boss指导工作一样就不好了。

**Comment by Yidadaa** [comment]
@SadPencil 关于语言的讹变现象我觉得没有太多的讨论价值了，如果想深入了解可以找相关文献进行阅读。
