### ISSUE TITLE
[Bug] 矩阵显示错误

### ISSUE THREAD

**Issue by coffee-guy** [Yidadaa/ChatGPT-Next-Web#3436]
**Describe the bug**
gpr4-1106-preview
latex语法显示出错

gpt回复内容：
一个三阶酉矩阵的例子可以是以下矩阵：

\[ U = \begin{bmatrix}
\frac{1}{\sqrt{2}} & 0 & \frac{1}{\sqrt{2}} \\
0 & 1 & 0 \\
\frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix} \]

为了验证这个矩阵确实是酉的，我们需要检查它是否满足 \( U^{\dagger}U = UU^{\dagger} = I \)，其中 \( I \) 是三阶单位矩阵。

首先，计算 \( U^{\dagger} \)（U 的共轭转置）：

\[ U^{\dagger} = \begin{bmatrix}
\frac{1}{\sqrt{2}} & 0 & \frac{1}{\sqrt{2}} \\
0 & 1 & 0 \\
\frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix}^{\dagger} = \begin{bmatrix}
\frac{1}{\sqrt{2}} & 0 & \frac{1}{\sqrt{2}} \\
0 & 1 & 0 \\
\frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix} \]

（注意：在这个特殊的例子中，矩阵 U 的元素都是实数，所以共轭转置只涉及转置。）

接下来，计算 \( U^{\dagger}U \) 和 \( UU^{\dagger} \)：

\[ U^{\dagger}U = \begin{bmatrix}
\frac{1}{\sqrt{2}} & 0 & \frac{1}{\sqrt{2}} \\
0 & 1 & 0 \\
\frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix} \begin{bmatrix}
\frac{1}{\sqrt{2}} & 0 & \frac{1}{\sqrt{2}} \\
0 & 1 & 0 \\
\frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix} = I \]

\[ UU^{\dagger} = \begin{bmatrix}
\frac{1}{\sqrt{2}} & 0 & \frac{1}{\sqrt{2}} \\
0 & 1 & 0 \\
\frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix} \begin{bmatrix}
\frac{1}{\sqrt{2}} & 0 & \frac{1}{\sqrt{2}} \\
0 & 1 & 0 \\
\frac{1}{\sqrt{2}} & 0 & -\frac{1}{\sqrt{2}}
\end{bmatrix} = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix} = I \]

由于 \( U^{\dagger}U \) 和 \( UU^{\dagger} \) 都等于单位矩阵 I，我们可以确认这个矩阵 U 是酉的。

**To Reproduce**
1. 提问gpt4 turbo
2. 给我一个三阶酉矩阵的例子
3. 矩阵latex显示出错

**Expected behavior**

**Screenshots**

![bug](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16222087/e0e9ec63-f3a9-4f0b-b68a-d9e139bb24c9)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
it's model issue related https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/3351

**Comment by coffee-guy** [comment]
> it's model issue related #3351

i use gpt4-1106-preview

**Comment by Yidadaa** [comment]
OpenAI 为了避免 LaTex 的公式符合与美元 $ 符号冲突，使用 [] 作为公式语法，所以会出现这种情况，虽然现在可以通过调整 prompts 来解决，但未来需要提交代码，来彻底解决这个问题。

#3239
