### ISSUE TITLE
[Bug] Can't handle so long response (128k Context Tokens) while using gpt-4-1106-preview

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Yidadaa/ChatGPT-Next-Web#3437]
**Describe the bug**
Can't handle so long response (128k Context Tokens) while using gpt-4-1106-preview

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/af8a03e4-355f-4897-adf4-3fb8bb42d9e3)

token input:

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/85a25c13-c1a2-4757-aea0-fe45ec78f015)

**Comment by H0llyW00dzZ** [comment]
> [!NOTE]  
> Not sure yet if the bug are related to this repo (might openai issue), because while "continue" after stuck it continuing

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/fc0f4799-e8e2-4bc2-8c3a-4c15fddd758e)

**Comment by ProblemFactory** [comment]
I remembered it was mentioned that the output is limited to 4096 tokens even for 128k model.
