### ISSUE TITLE
DISABLE_GPT4=0未生效 v2.9.12[Bug] 

### ISSUE THREAD

**Issue by wanqi98** [Yidadaa/ChatGPT-Next-Web#3441]
vercel上
设置DISABLE_GPT4=0，在自定义模型名中输入-all，gpt-4，模型下拉框变为空
阿里云服务器docker容器中docker run时设置-e DISABLE_GPT4=0，模型列表中的gpt-4仍然不显示

**Comment by wanqi98** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/49070358/08420114-b039-4f29-ad7d-356e7192637c)

**Comment by NixerSo5** [comment]
设置了  code  和 apikey 以后 依然让输入 apikey  没有输入  密码的地方

**Comment by Yidadaa** [comment]
不要设置为 0，直接删掉这个环境变量，然后重新部署。
