### ISSUE TITLE
请问怎么本地部署  复制本地部署命令行后到本地终端执行，重定向符号报错

### ISSUE THREAD

**Issue by xuexigpt** [Yidadaa/ChatGPT-Next-Web#345]
![微信图片_20230402132432](https://user-images.githubusercontent.com/129637884/229333226-e828f120-3499-4707-995a-9eeeb7dd4fce.jpg)

**Comment by AprilNEA** [comment]
请前往QQ群询问

**Comment by xuexigpt** [comment]
> 请前往QQ群尝试获得帮助

请问qq群号是多少呢
