### ISSUE TITLE
[Feature] Different auth codes support different optional models.

### ISSUE THREAD

**Issue by PeterChen1997** [Yidadaa/ChatGPT-Next-Web#3467]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I want to use different auth code to select different model, for example, I share code 1 just for chatGPT 3.5

But I want use code 2 for chatGPT 4 model

**Describe alternatives you've considered**

no

**Additional context**

just for fee control

**Comment by H0llyW00dzZ** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> No
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> I want to use different auth code to select different model, for example, I share code 1 just for chatGPT 3.5
> 
> But I want use code 2 for chatGPT 4 model
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> no
> 
> **Additional context** Add any other context or screenshots about the feature request here.
> 
> just for fee control

it's too complex

**Comment by PeterChen1997** [comment]
> > **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > No
> > **Describe the solution you'd like** A clear and concise description of what you want to happen.
> > I want to use different auth code to select different model, for example, I share code 1 just for chatGPT 3.5
> > But I want use code 2 for chatGPT 4 model
> > **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> > no
> > **Additional context** Add any other context or screenshots about the feature request here.
> > just for fee control
> 
> it's too complex

or can I limit each code request per day?

**Comment by H0llyW00dzZ** [comment]
> > > **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > > No
> > > **Describe the solution you'd like** A clear and concise description of what you want to happen.
> > > I want to use different auth code to select different model, for example, I share code 1 just for chatGPT 3.5
> > > But I want use code 2 for chatGPT 4 model
> > > **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> > > no
> > > **Additional context** Add any other context or screenshots about the feature request here.
> > > just for fee control
> > 
> > 
> > it's too complex
> 
> or can I limit each code request per day?

limit each code request per day its possible and actually not really complex, but the things is access code are setup in Environment Variables, I don't think so it's recommended to add in Environment Variables as well for limiting, unless made own admin/server panel for it

**Comment by H0llyW00dzZ** [comment]
> Try this: https://github.com/songquanpeng/one-api

I think i am gonna try this, because lazy to made admin panel

**Comment by PeterChen1997** [comment]
> Try this: https://github.com/songquanpeng/one-api

Thx bro ！！
