### ISSUE TITLE
[Feature] Markdown不支持渲染\\text{det}(A) = \\sum_{j=1}^{n} a_{ij} C_{ij} \\公式

### ISSUE THREAD

**Issue by youdianfan** [Yidadaa/ChatGPT-Next-Web#3479]
Markdown不支持渲染\\text{det}(A) = \\sum_{j=1}^{n} a_{ij} C_{ij} \\公式

**Comment by H0llyW00dzZ** [comment]
Try using gpt-4 preview

**Comment by youdianfan** [comment]
Above is the data returned by gpt, placed on top of Markdown in the project, he will not render the formula

**Comment by H0llyW00dzZ** [comment]
> ![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/27018910/fd2a3ece-063c-4369-a4f0-a568cab2525f)
> 
> 
> 
> 
> 
> I don't think so. gpt supports it
> 
> 
> 
> 

Its model issue, being bad hallucinated.
you have to prompt it perfectly because sometimes its not returning ('$...$') or ('$$...$$') which is syntax's latex in text/markdown

**Comment by youdianfan** [comment]
GPT officially does not use $, it can still be identified

**Comment by youdianfan** [comment]
This is the answer data returned by the chatgpt web page


[
"拉普拉斯展开（拉普拉斯展开）是一种用于计算行列式的方法。给定一个阶方阵，其行列式的拉普拉斯展开公式如下：\n\n\[ \det (A) = \sum_{i=1}^{n} (-1)^{i+j} \cdot a_{ij} \cdot \det(M_{ij}) \]\n\n其中，\ ( a_{ij} \) 是矩阵A的第i行第j列的元素，\( \det(M_{ij}) \) 是剩余矩阵，即去掉第i行和第j列后得到的（n -1）阶方阵的行列式。展开的求和是针对矩阵A的任意一行或一列进行的。\n\n这个公式的主要思想是行列式的计算架构，为每个元素乘习得代数余子式的求和。这种展开方法在计算增量阶数的行列式时可能会比直接计算更加方便。"
]

**Comment by youdianfan** [comment]
The Markdown component of the current project does not support the rendering of mathematical formulas in text format

**Comment by H0llyW00dzZ** [comment]
> The Markdown component of the current project does not support the rendering of mathematical formulas in text format
> 
> 
> 
> 

It's supported the syntax its $...$ and $$...$$

**Comment by youdianfan** [comment]
It is not supported, you can write this data to the Markdown component to test

**Comment by youdianfan** [comment]
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/27018910/bb7c967b-16b0-4fc5-a657-319dc4a927f4)

**Comment by youdianfan** [comment]
I don't know how to render mathematical formulas in latext format

**Comment by H0llyW00dzZ** [comment]
> I don't know how to render mathematical formulas in latext format

it's same (`$..$`) (`$$...$$`)

**Comment by H0llyW00dzZ** [comment]
> I'm talking about latext, of course I know that the $$format is recognized, so I'm saying that the Markdown component of the current project is not supported

yeah I know format like that are bad, even (`$..$`) (`$$...$$`) still returning that format btw in models

**Comment by H0llyW00dzZ** [comment]
try like this 
```
$$
\text{det}(A) = \\\sum_{j=1}^{n} a_{ij} C_{ij}
$$
```

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/b261ca72-d95d-47e6-b527-e58dd58e35d3)

**Comment by youdianfan** [comment]
Thank you for your answer, but I need to solve that it supports Latext format instead of adding $$, adding $$can be identified, this function I know

**Comment by Yidadaa** [comment]
之后会改。
