### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by mivinci** [Yidadaa/ChatGPT-Next-Web#348]
Is anybody having the same problem? Looks like Vercel failed to access OpenAI. 

![P@ M9LGOBZ8Y15F%1IKR$GO](https://user-images.githubusercontent.com/33592375/229335932-0be4bfac-46d6-4452-8b2b-1a017c56f007.png)

**Comment by Yuitsuki** [comment]
the same problem i just meet but I have no idea

**Comment by walala** [comment]
me too

**Comment by tangzixuan** [comment]
me too

**Comment by xeon76** [comment]
i also meet this problem

**Comment by mingjianqaq** [comment]
me to

**Comment by Yidadaa** [comment]
Please check if your API key is valid.

**Comment by mivinci** [comment]
> It maybe because your your free trial usage has expired. Refer: [here](https://www.bopblab.live/2023/04/reasons-why-your-hosting-platform.html)

Yea I just found out that my free trial usage has expired. It is only available within 3 months. 

Thank you guys!
