### ISSUE TITLE
[Bug]  EDGE_FUNCTION_INVOCATION_TIMEOUT

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#3481]
An error occurred with your deployment

EDGE_FUNCTION_INVOCATION_TIMEOUT

![SNAG-0322](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/66386500-6f0f-4b3c-bf2c-4557325889f1)

i refresh and works

**Comment by H0llyW00dzZ** [comment]
it's connection issue between client and server
and that `EDGE_FUNCTION_INVOCATION_TIMEOUT` timeout are server side issue
