### ISSUE TITLE
No place to enter API key

### ISSUE THREAD

**Issue by sm18lr88** [Yidadaa/ChatGPT-Next-Web#3487]
My system: Windows 11
Version of app: ChatGPT.Next.Web_2.9.12_x64-setup.exe

Bug: the Settings page doesn't have anywhere to enter the API key.

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/64564447/f540c305-ec29-4394-9575-32b72ba32728)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/64564447/ea572b82-7f70-4143-9a9e-386ac1a9f95c)

**Comment by Yidadaa** [comment]
custom endpoint
