### ISSUE TITLE
[Feature] 希望能支持 DALL·E 相关功能

### ISSUE THREAD

**Issue by zhangminggeek** [Yidadaa/ChatGPT-Next-Web#3498]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vual** [comment]
我的项目有支持这些，可以了解下：https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by Yidadaa** [comment]
#3110
