### ISSUE TITLE
[Bug] Upstash syncs bypass the user authentication

### ISSUE THREAD

**Issue by yosh3289** [Yidadaa/ChatGPT-Next-Web#3500]
**Describe the bug**
Syncing with upstash (probably with WebDAV too, but I haven't check) before entering passcodes OR API keys, **can bypass the authentication.**
There's only me using the ChatGPT-Next-Web vercel service, so I don't know how this may affect people with multiple passcodes.
Do you suggest people create multiple upstash/WebDAV databases for multiple passcodes OR is there a way to tell upstash only synchronize the chat history?
I understand if you think upstash/WebDAV should remember not only all the chat histories but also the settings (including passcodes or API keys of course). Then maybe it's a good idea to update your README, just a heads-up for everyone :)

**To Reproduce**
1. Go to 'Settings' before login
2. Sync with Upstash/WebDAV
3. All chat histories are there and settings are synchronized too (Automatically logged in)

**Deployment**
- [Y] Vercel
- [Y] Server

**Comment by reece00** [comment]
Can't you set a synchronous password?

**Comment by yosh3289** [comment]
I did set up the token and the Redis REST URL. It's just unexpected that there is an alternative way to log in (using the REST URL & REST TOKEN combination), apart from using a passcode or an API key.

**Comment by H0llyW00dzZ** [comment]
I know this can leading that bug, it's because "AccessControl" are overwriting by a default

on my fork's I had to set like this

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/f49a5d92-bca9-4c47-be80-09238ca292f9)

and default are false so its depend's of users

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/d327262e-cc91-4715-8b2c-3ea2b306cba9)

**Comment by yosh3289** [comment]
> I know this can leading that bug, it's because "AccessControl" are overwriting by a default
> 
> on my fork's I had to set like this
> 
> ![image](https://private-user-images.githubusercontent.com/17626300/289672632-f49a5d92-bca9-4c47-be80-09238ca292f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTAwMTIsIm5iZiI6MTcwMjM0OTcxMiwicGF0aCI6Ii8xNzYyNjMwMC8yODk2NzI2MzItZjQ5YTVkOTItYmNhOS00YzQ3LWJlODAtMDkyMzhjYTI5MmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZmFhMjhlZmQ4Yzc4Mjc0M2YxNGMxNTgxMDhhMDVkYTc4ZjQzNmQ3NjdjY2JlMDk1NGMzY2NhMDQ0ZjVjMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d-9_uEKM43gYFwk6ZwbgdJMePuRQQ-51PIr8Fbsn3F4)
> 
> and default are false so its depend's of users
> 
> ![image](https://private-user-images.githubusercontent.com/17626300/289672705-d327262e-cc91-4715-8b2c-3ea2b306cba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTAwMTIsIm5iZiI6MTcwMjM0OTcxMiwicGF0aCI6Ii8xNzYyNjMwMC8yODk2NzI3MDUtZDMyNzI2MmUtY2M5MS00NzE1LThiMmMtM2VhMmIzMDZjYmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOWIyNDI4M2Q1YWQ4MDllNDMwYjEwNzQyMjhjMDkwNDdmMWNjNzlkMDZhZDNhNzE0MzFiYTEzNjY2ZTYyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OvndC0pgR-Bzcu6W7gI3NGOw9X2figi39BNWluQleu0)

Good catch, that should give additional controls to the users
