### ISSUE TITLE
关于vercel自动部署的一个问题

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#351]
vercel是自动部署吗，还是每次需要手动重新部署。我看github里已经可以自动同步上游仓库代码了 [sync.yaml](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/.github/workflows/sync.yml)

**Comment by realskyrin** [comment]
第一次要手动部署，参考这里保证你在 vercel 部署的版本是你的 fork 版本：https://github.com/Yidadaa/ChatGPT-Next-Web#%E4%BF%9D%E6%8C%81%E6%9B%B4%E6%96%B0-keep-updated

之后 sync.yaml 脚本每天 0 点自动触发 sync，vercel 会自动部署
