### ISSUE TITLE
[Bug] The second password cannot be logged in

### ISSUE THREAD

**Issue by 2059353675** [Yidadaa/ChatGPT-Next-Web#3514]
**Describe the bug**
I set multiple passwords in the environment variable, but only the first password can log in, while the others can not.

thx! :)

**Comment by GOWxx** [comment]
> The value should be passwords separated by comma（https://github.com/Yidadaa/ChatGPT-Next-Web#access-password）

Please verify the comma used, ensuring it is the English comma rather than the Chinese comma.

**Comment by 2059353675** [comment]
> > The value should be passwords separated by comma（[https://github.com/Yidadaa/ChatGPT-Next-Web#access-password）](https://github.com/Yidadaa/ChatGPT-Next-Web#access-password%EF%BC%89)
> 
> Please verify the comma used, ensuring it is the English comma rather than the Chinese comma.

I'm sorry I exactly used the English comma but I was forgot to update the environment variables. Thank you!
