### ISSUE TITLE
根据自己的喜好改了一下CSS样式

### ISSUE THREAD

**Issue by MrShellad** [Yidadaa/ChatGPT-Next-Web#354]
喜欢的可以自取
body {
  background-image: url("https://www.bing.com/th?id=OHR.MWDolomites_EN-US2413806289_1920x1080.jpg"); /* 链接自行替换 */

  background-size: cover;  /* 图片将会被拉伸或压缩以适应屏幕大小 */
  background-repeat: no-repeat;  /* 禁止重复背景图片 */
  background-position: center;  /* 将背景图像始终垂直和水平居中 */

}
* {
  font-family: "等距更纱黑体 SC", sans-serif !important;/* 填入自己喜欢的字库，前提是本地已经安装 */
}
}
.home_container__Myqoy {
    border: var(--border-in-light);
    border-radius: 20px;
    box-shadow: var(--shadow);
    color: var(--black);
    background-color: var(--white);
    min-width: 600px;
    min-height: 480px;
    max-width: 1920px; /* 根据自己的屏幕分辨率或者自己的喜好调节 */
    display: flex;
    overflow: hidden;
    box-sizing: border-box;
    width: var(--window-width);
    height: var(--window-height);
}
![Snipaste_2023-04-02_18-20-42](https://user-images.githubusercontent.com/27322551/229347178-d501b933-abd9-4165-8ac0-e289dee9b9b0.png)

**Comment by Yidadaa** [comment]
加载第三方字体会严重拖慢页面加载速度，目前采取的方案是使用 google fonts 按需加载，不会考虑使用其他第三方字体。

**Comment by MrShellad** [comment]
> 加载第三方字体会严重拖慢页面加载速度，目前采取的方案是使用 google fonts 按需加载，不会考虑使用其他第三方字体。

这个是stylish浏览器插件

**Comment by tuqingwen** [comment]
> 喜欢的可以自取 body { background-image: url("https://www.bing.com/th?id=OHR.MWDolomites_EN-US2413806289_1920x1080.jpg"); /* 链接自行替换 */
> 
> background-size: cover; /* 图片将会被拉伸或压缩以适应屏幕大小 _/ background-repeat: no-repeat; /_ 禁止重复背景图片 _/ background-position: center; /_ 将背景图像始终垂直和水平居中 */
> 
> }
> 
> * {
>   font-family: "等距更纱黑体 SC", sans-serif !important;/* 填入自己喜欢的字库，前提是本地已经安装 _/
>   }
>   }
>   .home_container__Myqoy {
>   border: var(--border-in-light);
>   border-radius: 20px;
>   box-shadow: var(--shadow);
>   color: var(--black);
>   background-color: var(--white);
>   min-width: 600px;
>   min-height: 480px;
>   max-width: 1920px; /_ 根据自己的屏幕分辨率或者自己的喜好调节 */
>   display: flex;
>   overflow: hidden;
>   box-sizing: border-box;
>   width: var(--window-width);
>   height: var(--window-height);
>   }
>   ![Snipaste_2023-04-02_18-20-42](https://user-images.githubusercontent.com/27322551/229347178-d501b933-abd9-4165-8ac0-e289dee9b9b0.png)

请问这个背景图片在脚本中哪个位置改动呢？
