### ISSUE TITLE
vercel 部署错误

### ISSUE THREAD

**Issue by old-chow** [Yidadaa/ChatGPT-Next-Web#357]
Type error: Property 'SendPreviewBubble' is missing in type '{ Title: string; SubTitle: string; Actions: { ClearAll: string; ResetAll: string; Close: string; }; Lang: { Name: string; Options: { cn: string; en: string; tw: string; es: string; }; }; Avatar: string; FontSize: { ...; }; ... 13 more ...; PresencePenlty: { ...; }; }' but required in type '{ Title: string; SubTitle: string; Actions: { ClearAll: string; ResetAll: string; Close: string; }; Lang: { Name: string; Options: { cn: string; en: string; tw: string; es: string; }; }; Avatar: string; FontSize: { ...; }; ... 14 more ...; PresencePenlty: { ...; }; }'.

**Comment by mengqi92** [comment]
Regressed by #271. A fix is underway:  #360 .
