### ISSUE TITLE
Vercel 部署失败

### ISSUE THREAD

**Issue by ithou** [Yidadaa/ChatGPT-Next-Web#359]
vercel登录github，import此项目，添加CODE和OPENAI_API_KEY，部署失败。
<img width="1440" alt="CleanShot 2023-04-02 at 20 31 03@2x" src="https://user-images.githubusercontent.com/39048771/229352954-2071c467-a85c-47a4-bc58-8a36892fb5b3.png">

**Comment by ithou** [comment]
> +1

很突然～😂

**Comment by zytw** [comment]
+1

**Comment by AMXOOO** [comment]
+1

**Comment by aaBaO** [comment]
多语言里少了es.ts的配置:rofl:

**Comment by Boiled-Chicken-Slices** [comment]
+1

**Comment by longzexd** [comment]
+1

**Comment by xeon76** [comment]
+1

**Comment by yaoyaoio** [comment]
+1

**Comment by Boiled-Chicken-Slices** [comment]
有知道这玩意怎么处理嘛

**Comment by neuer** [comment]
+1

**Comment by leoshcn** [comment]
> 

期待
