### ISSUE TITLE
关于随机性选项的问题

### ISSUE THREAD

**Issue by TactfulBean** [Yidadaa/ChatGPT-Next-Web#361]
在选项中有随机性的选项，初始值为1.0，我将其调整为2.0（拉满）后提问与1.0设置相同的问题，高随机值给出的回复很奇怪，就是乱码，这是什么问题呢。
上2.0，下1.0
![BFLAP1WLM$_NI~UL6{WW`}P](https://user-images.githubusercontent.com/90669825/229354639-b02e2951-b40a-4cac-8349-b21073955ad7.png)
![N4((Y}@) QPH_Y W}~UV@VG](https://user-images.githubusercontent.com/90669825/229354643-1b4d7b8e-bd81-401a-9923-8529bfd29be0.png)

**Comment by Yidadaa** [comment]
openai 的设置就是这样
