### ISSUE TITLE
可以支持导出静态网站部署吗？

### ISSUE THREAD

**Issue by wubonetcn** [Yidadaa/ChatGPT-Next-Web#362]
可以支持导出静态网站部署吗？

**Comment by Yidadaa** [comment]
那你让用户直连 openai 服务器？

**Comment by wubonetcn** [comment]
> 那你让用户直连 openai 服务器？

是的，如果是面向国外用户，他本身的网络就是通的。国内的话可以填他自己的代理服务器。

**Comment by wubonetcn** [comment]
因为有的人比较关注隐私不想通过服务器中转，所以能静态还是比较有价值

**Comment by Yidadaa** [comment]
之后做个客户端打包出来，或许就支持了，耐心等待吧，现在还有更重要的事要做。
