### ISSUE TITLE
deploy到vercel上，需要翻墙才可以访问，是为啥

### ISSUE THREAD

**Issue by jie123123** [Yidadaa/ChatGPT-Next-Web#364]
deploy到vercel上，需要翻墙才可以访问，是为啥，https://chat-gpt-next-web-beryl-iota-45.vercel.app/
![image](https://user-images.githubusercontent.com/34887703/229355766-4bf44031-5c32-4afb-ae3a-78876af24e40.png)

**Comment by Yidadaa** [comment]
确实，我也挺纳闷的，国家怎么就把 vercel 给封了呢。

**Comment by jie123123** [comment]
> 确实，我也挺纳闷的，国家怎么就把vercel给封了呢。

https://gpt-4.lovesi.tech/

**Comment by jie123123** [comment]
https://gpt-4.lovesi.tech/ 这个是自己国内的备案域名吗

**Comment by jie123123** [comment]
@Yidadaa https://gpt-4.lovesi.tech/ 大佬，你这个怎么部署的，不用翻墙，，，，，这个是自己国内的备案域名吗

**Comment by zealotCE** [comment]
> @Yidadaa https://gpt-4.lovesi.tech/ 大佬，你这个怎么部署的，不用翻墙，，，，，这个是自己国内的备案域名吗

一般可以利用找个已备案的域名，然后服务器ip能被国内访问到就可以了

例如说，我有一台新加坡的服务器部署服务，然后再利用cloudflare 的DNS能力，把域名和服务器的公网ip绑好。就可以了

**Comment by zealotCE** [comment]
> > @Yidadaa https://gpt-4.lovesi.tech/ 大佬，你这个怎么部署的，不用翻墙，，，，，这个是自己国内的备案域名吗
> 
> 一般可以利用找个已备案的域名，然后服务器ip能被国内访问到就可以了
> 
> 例如说，我有一台新加坡的服务器部署服务，然后再利用cloudflare 的DNS能力，把域名和服务器的公网ip绑好。就可以了

当然，DNS 解析可以不只是CloudFlare ，阿里云也有类似能力。

但是，你首先得有一个能被国内访问的服务器
