### ISSUE TITLE
最近的版本，复制功能无效

### ISSUE THREAD

**Issue by chaoticjoy** [Yidadaa/ChatGPT-Next-Web#366]
不论对话复制，还是对话里的markdown文本复制，都是复制无效，chrome浏览器

**Comment by Yidadaa** [comment]
请确认是否授权了剪切板访问。

**Comment by Yidadaa** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/16968934/229357500-e4bac05c-e5a0-4631-8774-60725f07b513.png">

点进去看看。

**Comment by chaoticjoy** [comment]
> <img alt="image" width="380" src="https://user-images.githubusercontent.com/16968934/229357500-e4bac05c-e5a0-4631-8774-60725f07b513.png">
> 
> 点进去看看。

可能是因为我用的http没有ssl证书，显示不安全，默认没有剪贴板权限，单独设置后还是有问题。能否换一种复制实现方式，单纯的js实现，我在这个网站上搭的chatgpt-web，以及其他的都没有剪贴板权限，但是可以复制。

**Comment by Yidadaa** [comment]
最新代码已经增加了 fallback，再试试

**Comment by chaoticjoy** [comment]
> 最新代码已经增加了 fallback，再试试

已经没有问题了，谢谢。
