### ISSUE TITLE
最近无法正常使用，求助下

### ISSUE THREAD

**Issue by tangzixuan** [Yidadaa/ChatGPT-Next-Web#369]
* 在我翻墙后，是可以正常使用官方网站https://chat.openai.com/chat；
* 但是这个战队最近无法正常使用了，https://chat-gpt-next-web.vercel.app/，我是用v2ray翻墙的，之前几天是可以的。
看这个报错，似乎是超时了嘛，我在我服务器上用docker部署也有这样的问题
![截屏2023-04-02 22 15 16](https://user-images.githubusercontent.com/51657124/229358505-7e1d135b-efcf-4de4-9c63-9072c87b180e.png)

**Comment by Yidadaa** [comment]
用演示站，测试一下你的 api key 是否可用。

**Comment by simonbean** [comment]
出现了相同问题，泪目

**Comment by JohnWangggg** [comment]
同样的问题

**Comment by yusixian** [comment]
遇到了同样的问题，可能是api key过期了，可以在这里检查一下：https://platform.openai.com/account/usage

**Comment by XixiangWu** [comment]
ChatGPT送的18USD四月一号就过期了，想用的话得连一张银行卡

**Comment by occamrazor1492** [comment]
不翻墙是不是用不了
