### ISSUE TITLE
I am a novice front-end developer. What's wrong with compiling and deploying server 404? Can you give me a local deployment tutorial?

### ISSUE THREAD

**Issue by kevins0116** [Yidadaa/ChatGPT-Next-Web#37]
I am a novice front-end developer. What's wrong with compiling and deploying server 404? Can you give me a local deployment tutorial?

**Comment by AprilNEA** [comment]
If you mean deployment and not development.
then obviously the experimental feature `appDir` in `Next13` is not suitable for local deployment.

**Comment by AprilNEA** [comment]
You can get more information in this document [Next.js Beta Docs](https://beta.nextjs.org/docs)
