### ISSUE TITLE
微信打开链接设置会报错：Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by thinkersOne** [Yidadaa/ChatGPT-Next-Web#373]
这个问题依然存在

**Comment by lipanpan-hub** [comment]
同样的问题 依然存在 桌面端和手机浏览器都能正常打开 就是微信一打开就报错

**Comment by lipanpan-hub** [comment]
> 同样的问题 依然存在 桌面端和手机浏览器都能正常打开 就是微信一打开就报错

安卓版本微信正常打开  苹果版本微信打开就报错

**Comment by lipanpan-hub** [comment]
有没有大佬有X5内核的微信 看看啥报错  
有的微信能打开 有的微信打不开
之前 没有打开过的微信 一般情况下 可以打开不会报错 如果之前打开过 则会报这个错误
我还以为是缓存问题  清除了微信缓存 还是不行

**Comment by douyinyu** [comment]
同样的问题 真的有点玄学

**Comment by douyinyu** [comment]
我也是测试了各种手机浏览器(安卓原生 safari qq uc 百度 edge都能打开) 就是微信 bing手机端 微博内打不开
