### ISSUE TITLE
希望添加隐藏侧边栏支持

### ISSUE THREAD

**Issue by lingnanlu** [Yidadaa/ChatGPT-Next-Web#380]
<img width="1600" alt="CleanShot 2023-04-03 at 07 46 24@2x" src="https://user-images.githubusercontent.com/2167947/229385594-f4d76935-fc4b-400b-a331-fb9d6f9f600d.png">

如图所示, 在并排两个窗口时, 如果不能隐藏侧边栏, 则占用面积过多.

**Comment by bkjyyy** [comment]
赞同，希望添加隐藏侧边栏支持

**Comment by HenMie** [comment]
或者做成动态宽度，可调节，拉到最左边就消失。不过这种处理可能会降低响应速度。

**Comment by ZJYCP** [comment]
#336 有人写了，希望能尽快合并进去

**Comment by devyujie** [comment]
+1
