### ISSUE TITLE
是否能支持echarts画图

### ISSUE THREAD

**Issue by 143heyan** [Yidadaa/ChatGPT-Next-Web#3803]
我试了可以通过Mermaid的代码直接生成图片
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/143150794/1ab2d291-39cc-4c29-9c00-a55c9fd62ad2)
是否也能加上对echarts的支持

**Comment by Yidadaa** [comment]
抱歉，这个功能我曾经尝试过，非常不稳定，所以决定不引入。如果未来发现了更好的解决方案，会考虑引入此功能，请保持关注！
