### ISSUE TITLE
部署完成后 一直显示错误，chatgpt没有回应

### ISSUE THREAD

**Issue by white586** [Yidadaa/ChatGPT-Next-Web#381]
![Screenshot_20230403_075756.jpg](https://user-images.githubusercontent.com/378109/229386023-a45f22c6-1025-40dc-aadf-7eba2b268179.jpg)

**Comment by btbox** [comment]
感觉是 openai 官方的问题？我上个星期用的时候没问题，这两天用的时候发现也是这样

**Comment by mx2013713828** [comment]
+1，今天刚发现的，一直这样，应该是vercel访问不了openai api了吧，但是我自己连代理是能访问的，奇怪

**Comment by Neu070224** [comment]
用vercel部署的能访问，本地部署的不行，报上面这个错误。

**Comment by btbox** [comment]
@Neu070224 我刚用netlify部署的还是不行。

**Comment by Neu070224** [comment]
> @Neu070224 我刚用netlify部署的还是不行。

我刚才试了一下，可以的。

**Comment by Neu070224** [comment]
本地部署后，访问http://localhost:3001/  界面显示都没问题 打开vpn 提问老是提示错误

**Comment by Neu070224** [comment]
> 本地部署后，访问http://localhost:3001/ 界面显示都没问题 打开vpn 提问老是提示错误

提示错误如下：
[Proxy] openaiPath: v1/chat/completions
[Proxy] contentType: application/json
[Proxy] method: POST
[Proxy] body: <ref *1> ReadableStream {
  _state: 'readable',
  _reader: undefined,
  _storedError: undefined,
  _disturbed: false,
  _readableStreamController: ReadableStreamDefaultController {
  _controlledReadableStream: [Circular *1],
  _queue: S {
  _cursor: 0,
  _size: 0,
  _front: { _elements: [], _next: undefined },
  _back: { _elements: [], _next: undefined }
},
  _queueTotalSize: 0,
  _started: false,
  _closeRequested: false,
  _pullAgain: false,
  _pulling: false,
  _strategySizeAlgorithm: [Function],
  _strategyHWM: 1,
  _pullAlgorithm: [Function],
  _cancelAlgorithm: [Function]
}
}
[Proxy] url: https://api.openai.com/v1/chat/completions
fatal: not a git repository (or any of the parent directories): .git
No git or not from git repo.
[Chat Stream]  [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
}

**Comment by Yidadaa** [comment]
@Neu070224 请仔细阅读文档：

https://github.com/Yidadaa/ChatGPT-Next-Web#%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91-local-development

**Comment by jiyuay** [comment]
@Neu070224 我也遇到了这个问题，请问你解决了吗？
