### ISSUE TITLE
超过 4097 tokens 错误提示，似乎是个bug

### ISSUE THREAD

**Issue by Cp0204** [Yidadaa/ChatGPT-Next-Web#385]
操作步骤：新建对话，输入以下内容，前置上下文、历史记录均为空。

```
<?php
function aes_encrypt($plaintext, $key, $iv) {
    $cipher = openssl_encrypt($plaintext, 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);
    return base64_encode($cipher);
}

function aes_decrypt($ciphertext, $key, $iv) {
    $cipher = base64_decode($ciphertext);
    return openssl_decrypt($cipher, 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);
}

评价这段代码，给出优化建议；
```

按理说不会超tokens，在 ChatGPT-Next-Web 都会提示超限。（当前版本：5843303）

开始怀疑是返回内容太长的问题，后来反复试了很多次，而在 ChatGPT-Web 中是正常返回的。

ChatGPT-Next-Web：
![QQ截图20230403095016](https://user-images.githubusercontent.com/5239753/229393890-9ccfa49e-1af5-4ab3-8434-545a2e8dbefa.png)

ChatGPT-Web：
![QQ截图20230403095000](https://user-images.githubusercontent.com/5239753/229393913-fc7ae519-b8ae-4abe-9284-a892361fedba.png)

**Comment by Yidadaa** [comment]
更新了代码，重新 sync 部署一下试试。

**Comment by NoMoney2022** [comment]
相同问题，更新代码，清除浏览器缓存后完美解决
