### ISSUE TITLE
有计划支持流式响应吗

### ISSUE THREAD

**Issue by selfboot** [Yidadaa/ChatGPT-Next-Web#386]
目前docker部署后，用nginx做了反向代理，但是没有流式响应。是因为现在还没支持，还是我的nginx配置有问题呢

**Comment by Cp0204** [comment]
一直支持的，你配置的问题，加上这几句

```
        # 不缓存，支持流式输出
        proxy_cache off;  # 关闭缓存
        proxy_buffering off;  # 关闭代理缓冲
        chunked_transfer_encoding on;  # 开启分块传输编码
        tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
        tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
        keepalive_timeout 300;  # 设定keep-alive超时时间为65秒
```

**Comment by roboger** [comment]
vercel等一键部署平台，没法设置环境，该怎么做能流式输出？

**Comment by Cp0204** [comment]
> 

一键部署没用反向代理，原本就是流式输出

**Comment by roboger** [comment]
采用 netlify 一键部署的，不支持流式输出，希望后期能对这块 调整，或者增加一个开关。

**Comment by openaddr** [comment]
docker run -d -p 1111:3000 \
   -e OPENAI_API_KEY="我的秘钥" \
   -e CODE="我的密码" \
   -e PROXY_URL="我的代理地址" \
   yidadaa/chatgpt-next-web
   
   我的docker是这样启动的,
   访问时是:  域名:1111 这样访问的

**Comment by LiberatorHg** [comment]
> 这个配置文件是写在哪的呢，我直接docker部署了，也没有使用过nginx， 直接使用端口号访问的页面，也没有流响应

老哥你解决了吗，我现在也是遇到和你一样的问题。。直接docker部署的，没有打字机效果

**Comment by openaddr** [comment]
> 

我最后检查出来的问题是浏览器兼容性,我使用火狐浏览器是不行的, 切换谷歌浏览器就行了

**Comment by LiberatorHg** [comment]
> > 
> 
> 我最后检查出来的问题是浏览器兼容性,我使用火狐浏览器是不行的, 切换谷歌浏览器就行了

我本地docker跑用edge有打字机效果，但是放到服务器中的docker上，打字机效果就没了  纳闷了  也没做nginx

**Comment by openaddr** [comment]
我也没做什么,这是我的启动命令:
docker run -d -p 1111:3000 \
   -e OPENAI_API_KEY="APIKEY" \
   -e CODE="PassCode" \
   -e PROXY_URL="proxy" \
   yidadaa/chatgpt-next-web

> > > 
> > 
> > 
> > 我最后检查出来的问题是浏览器兼容性,我使用火狐浏览器是不行的, 切换谷歌浏览器就行了
> 
> 我本地docker跑用edge有打字机效果，但是放到服务器中的docker上，打字机效果就没了 纳闷了 也没做nginx

**Comment by LiberatorHg** [comment]
> 我也没做什么,这是我的启动命令: docker run -d -p 1111:3000 -e OPENAI_API_KEY="APIKEY" -e CODE="PassCode" -e PROXY_URL="proxy" yidadaa/chatgpt-next-web
> 
> > > > 
> > > 
> > > 
> > > 我最后检查出来的问题是浏览器兼容性,我使用火狐浏览器是不行的, 切换谷歌浏览器就行了
> > 
> > 
> > 我本地docker跑用edge有打字机效果，但是放到服务器中的docker上，打字机效果就没了 纳闷了 也没做nginx

是的，我也是和你一模一样的启动命令，

**Comment by luciouskami** [comment]
用traefik替代nginx就能解决了
