### ISSUE TITLE
关于授权码

### ISSUE THREAD

**Issue by prinzchao** [Yidadaa/ChatGPT-Next-Web#387]
授权码是否可以设置，打开网页自动弹出要求填写，不然页面呈现锁死状态
不然部署给公司内部用，我还一个一个告诉他们去哪里填

**Comment by ywgx** [comment]
内部使用,完全可以放开,不需要授权码

**Comment by prinzchao** [comment]
域名是公开的，网址容易外泄的。

**Comment by Yidadaa** [comment]
你在内网部署不就行了。

**Comment by CKylinMC** [comment]
给一个建议，可以考虑HTTP的BasicAuth或者用Cloudflare的ZeroTrust
