### ISSUE TITLE
优化前端ui显示间距问题

### ISSUE THREAD

**Issue by leochen12-rgb** [Yidadaa/ChatGPT-Next-Web#390]
部署完成后，前端ui界面只占用屏幕中间的1/3部分，两边空旷，出现代码框时，代码长度过长会导致代码溢出代码框，希望能调整前端ui间距问题或在设置里让用户自定义，类似wixin web大小比较美观。然后我又尝试在设置里设置紧凑边框显示又太大了，目前我的屏幕有2K和4K的，并且都有这种问题。

**Comment by Yidadaa** [comment]
你可以安装成 pwa 应用，可以随意调整大小

**Comment by leochen12-rgb** [comment]
这对于新手来说还是有点难度的，哈哈

**Comment by Yidadaa** [comment]
问下 chatgpt 就知道了。

**Comment by picklefan** [comment]
> 部署完成后，前端ui界面只占用屏幕中间的1/3部分，两边空旷，出现代码框时，代码长度过长会导致代码溢出代码框，希望能调整前端ui间距问题或在设置里让用户自定义，类似wixin web大小比较美观。然后我又尝试在设置里设置紧凑边框显示又太大了，目前我的屏幕有2K和4K的，并且都有这种问题。

我也这么觉得, 然后我fork 改了, 他有个message 什么的是80% 你搜一下改成100% 就行了, 或者你看看我的fork 改了什么, 找到那个80% 的地方, 还有一个左边框默认是300px, 我改成了260px
@leochen12-rgb
