### ISSUE TITLE
鼠标移出对话框后输入框会丢失焦点

### ISSUE THREAD

**Issue by WJZhen** [Yidadaa/ChatGPT-Next-Web#391]
略微有点影响使用，是否能够优化

**Comment by Yidadaa** [comment]
有意为之，你的使用场景是啥，会出现什么问题

**Comment by WJZhen** [comment]
有意为之就算了,个人使用问题.在输入的时候碰到鼠标后,鼠标移出对话框导致无法继续输入,并且输入法预选区的拼音也会变为普通字母
