### ISSUE TITLE
建议添加自定义对话功能

### ISSUE THREAD

**Issue by fangyuan99** [Yidadaa/ChatGPT-Next-Web#396]
有时候想给对话自定义一个标题，用来区分不同的用途

**Comment by Yidadaa** [comment]
在聊天界面点击标题自定义。

**Comment by fangyuan99** [comment]
> 

![image](https://user-images.githubusercontent.com/62874116/229405672-d3c9a878-4193-46b9-a5c1-ce55f0da33f5.png)
我点击这里似乎没有反应

**Comment by fangyuan99** [comment]
能否和官网一样在这个位置添加一个修改按钮
![image](https://user-images.githubusercontent.com/62874116/229405836-661435ef-1724-46c4-b55f-7917a000306f.png)

**Comment by Yidadaa** [comment]
你这是二改之后的代码，请找二改作者修改。
