### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by ifyour** [Yidadaa/ChatGPT-Next-Web#397]
Hello, thank you for your open-source contribution. I encountered the following error when deploying the latest version on mobile:

### Error

```text
Application error: a client-side exception has occurred (see the browser console for more information)
```

 

### Env

```text
iOS: 14.2
Chrome: 111.0.5563.101
Safari: 14.0.1 
 ```

**Comment by lipanpan-hub** [comment]
#373

**Comment by lipanpan-hub** [comment]
[6e6d2a](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/6e6d2a3310604dcb3e6aa1ba78ea05b02ac60c57) 确实会有这个问题  等待大佬修复
