### ISSUE TITLE
部署 Vercel 设置 OPENAI_API_KEY 环境变量无效

### ISSUE THREAD

**Issue by leonfancy** [Yidadaa/ChatGPT-Next-Web#398]
部署 Vercel 设置 OPENAI_API_KEY 环境变量无效。只能在前端设置 API KEY，但是这样的话 KEY 只有保存在本地。难道这个项目不支持在服务端设置 API KEY？

**Comment by Yidadaa** [comment]
请提供 vercel 控制台 log 截图。

**Comment by leonfancy** [comment]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/4530475/229421316-d7e4f653-348d-4c6a-b6ea-508c406dfb20.png">
看不出什么有用的东西

**Comment by Yidadaa** [comment]
修改完环境变量重新部署 vercel 了没？

**Comment by leonfancy** [comment]
重新部署试过，删了项目重新部署也试过。都不行

**Comment by Yidadaa** [comment]
1. 提供一下环境变量页的截图
2. 确认 api key 可用？

**Comment by leonfancy** [comment]
确认可用哦，因为我在前端填 API KEY 就可以用

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/4530475/229422064-457607c9-0a75-4598-9a23-8e57eec9cdf1.png">

**Comment by leonfancy** [comment]
我试过 fork 部署，以及直接点你这个项目deploy 按钮部署都不行

**Comment by Yidadaa** [comment]
是否在设置页填写了你自己设置的 CODE？

**Comment by leonfancy** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/4530475/229423039-5cb54a62-142a-4b06-bc33-8cac9f6f4364.png">

**Comment by Yidadaa** [comment]
把你的 CODE 填到 Access Code 上去。

**Comment by leonfancy** [comment]
啊？Code 原来是这个意思？若然可以了。
我以为设置了 CODE的话，前端会弹出一个什么输入密码的框框。

**Comment by sswws** [comment]
这个code值是什么？在哪里获取

**Comment by liuzhoucheng** [comment]
我设置了CODE，在前台也重新输入CODE，但依然不行，必须在前台输入API KEY才可以。唉，不知道为什么vercel已经设置了环境变量，前台还要输入一次KEY，好麻烦。

**Comment by 2001016** [comment]
{
  "error": {
    "message": "Incorrect API key provided: Incorrec**************ided. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}
这个报错是为啥啊

**Comment by 2001016** [comment]
我的api可以在其他地方使用但是这里使用就显示这个问题

**Comment by 2001016** [comment]
不知道为啥api在这里用不了
