### ISSUE TITLE
新版在手机的浏览会报错，还有在macos的webview的点击冒泡问题

### ISSUE THREAD

**Issue by weykon** [Yidadaa/ChatGPT-Next-Web#399]
1. 新版进入页面就有错误: Application error: a client-side exception has occurred ~~~~~
2. chatItem 的 delete svg button 点击， 会触发底部 div 的 onClick, 而且detele函数没起效。
我用 e.stopPropagation 无济于事。

**Comment by Yidadaa** [comment]
提供操作系统类型，版本，并尝试使用本项目演示站进入，确认问题是否依然存在

**Comment by weykon** [comment]
第一个问题： 用https://chat-gpt-next-web.vercel.app在我手机能使用，可能是我域名解析问题

第二个问题： https://chat-gpt-next-web.vercel.app 问题存在。 
macos Ventura 13.0, Xcode Version 14.1

**Comment by weykon** [comment]
![IMG_A50372638E02-1](https://user-images.githubusercontent.com/36456814/229427091-bbe5ad19-56a4-4611-8271-91c02ab52b25.jpeg)
我不太会怎么设置，我用自己域名解析，我fork你的新代码后，我的域名需要操作什么吗

**Comment by Yidadaa** [comment]
不用操作，等 Vercel 自动部署完成就行。

**Comment by weykon** [comment]
> 不用操作，等 Vercel 自动部署完成就行。

[chat.weykon.com](chat.weykon.com)
我电脑chrome 没问题, 但是手机 Safari 进不去，如上图

**Comment by weykon** [comment]
我又拉了你一次新代码，等待中

**Comment by weykon** [comment]
新代码手机可以用了！！！！！！ @Yidadaa 

但是 xcode 的 WKWebView 问题还存在，导致没法清除对话，我找点办法自己清除吧
