### ISSUE TITLE
ui好看

### ISSUE THREAD

**Issue by tszamy** [Yidadaa/ChatGPT-Next-Web#4]
ui和排版挺好看的，用的是什么ui库呢

**Comment by tszamy** [comment]
> 感谢肯定，为了保证首屏加载速度，没有使用第三方 UI 库，用 css 自己写的。

哇，那么快回复。感谢。
还有个问题，我如果二开可以不用gitpod吗，就用node把项目运行起来就行了吧

**Comment by Yidadaa** [comment]
可以不用 gitpod，本地直接 `yarn install && yarn dev` 就行了，不过 openai 的 api 在国内是被墙的状态，你需要花时间解决本地开发时翻墙的问题，我最开始的时候就是在本地开发，虽然用 proxychains 可以解决，但还是挺难受的，总会有些小问题，现在这个项目所有的开发都是在 gitpod 上完成。

**Comment by tszamy** [comment]
好的 十分感谢 !
