### ISSUE TITLE
将 README.md 中的中英文分离

### ISSUE THREAD

**Issue by AprilNEA** [Yidadaa/ChatGPT-Next-Web#40]
同时放置中英文是一件好事，但是如果在将其掺杂在一起我认为会降低阅读体验。

ChatGPT 给出的解决方案 (prompt: 在 Github 的 README.md 中中英文版本是否应该分开):
>**在同一个README文件中包含中英文内容：**
>
>如果你的项目受众包括中英文用户，你可以在同一个README文件中提供中英文两个版本的内容。通常情况下，可以按顺序放置各个语言版本，例如先放英文版本，然后是中文版本。这样，读者可以根据自己的需求选择合适的语言阅读。
>
>缺点是，如果README文件内容较多，这会使得文件变得很长，可能导致阅读体验不佳。
>
>**将中英文版本分开到不同的文件：**
>
>另一种选择是将中英文版本的README内容分开到不同的文件。例如，你可以将英文版放在名为README.md的文件中，将中文版放
>在名为README.zh.md的文件中。在每个文件开头，添加指向其他语言版本的链接，方便用户切换。
>
>这种做法的优点是，每个文件都更容易阅读和维护。然而，缺点是你需要确保在更新文档时，所有语言版本的内容保持一致。
>
>综上所述，是否将中英文版本分开取决于你的实际需求。如果你认为在同一个文件中提供多语言内容可能会导致阅读体验不佳，那么将它们分开到不同的文件可能是更好的选择。相反，如果你认为维护多个单独的文件可能会导致内容不一致，那么将它们放在同一个文件中可能更合适。

**Comment by Yidadaa** [comment]
分开存放确实可以让 readme 更整洁，但是用起来体验会差一些，用户很可能会懒得跳转，包括后续更新文档的时候也会更麻烦，暂时还是中英混合吧。

**Comment by Yidadaa** [comment]
#510
