### ISSUE TITLE
chat-gpt4使用问题

### ISSUE THREAD

**Issue by 52devops** [Yidadaa/ChatGPT-Next-Web#402]
openai的api key无法使用chat-gpt 4模型
![LHIe9u4McH](https://user-images.githubusercontent.com/40234908/229434855-829bd2d1-9179-4f62-b2d3-cfb535a2b891.jpg)

**Comment by zealotCE** [comment]
首先得让openai给你账号gpt4.0的API权限

**Comment by zealotCE** [comment]
> 我已经开通，还要在哪里申请API吗？
[GPT-4 API waitlist](https://openai.com/waitlist/gpt-4-api)
