### ISSUE TITLE
请问本项目支持长回复吗？也就是长代码，不需要说“继续”，能自动接着输出

### ISSUE THREAD

**Issue by oasis168** [Yidadaa/ChatGPT-Next-Web#405]
请问本项目支持长回复吗？也就是长代码，不需要说“继续”，能自动接着输出

**Comment by Cp0204** [comment]
不支持，我在我微信应用php对接的时候是这样处理的：
```php
// 如因 maxtokens 限制截断，自动续写
function chatgpt($text, $chatID){
  //...
  $return = trim($response_arr['choices'][0]['message']['content']);
  if($response_arr['choices'][0]['finish_reason']=="length"){
      $return = $return.chatgpt("continue", $chatID);
  }
  return $return;
}
```
如果finish_reason=length，就自动发 "continue" ，直至写完，拼合后返回给用户。这个过程用户是无感的，唯一感觉是多个请求会返回得慢一些。

局限于不会 nodejs ，供参考。 有前端界面还可以提供自动续写开关，把判断放到前端。

**Comment by oasis168** [comment]
> 不支持，我在我微信应用php对接的时候是这样处理的：
> 
> ```
> // 如因 maxtokens 限制截断，自动续写
> function chatgpt($text, $chatID){
>   //...
>   $return = trim($response_arr['choices'][0]['message']['content']);
>   if($response_arr['choices'][0]['finish_reason']=="length"){
>       $return = $return.chatgpt("continue", $chatID);
>   }
>   return $return;
> }
> ```
> 
> 如果finish_reason=length，就自动发 "continue" ，直至写完，拼合后返回给用户。这个过程用户是无感的，唯一感觉是多个请求会返回得慢一些。
> 
> 局限于不会 nodejs ，供参考。 有前端界面还可以提供自动续写开关，把判断放到前端。

在正常使用的时候，有时输入“continue”，GPT会从头开始反馈消息，您后台这么处理，有遇到不接着写，而是从头开始写的情况吗？

**Comment by Cp0204** [comment]
> > 不支持，我在我微信应用php对接的时候是这样处理的：
> > ```
> > // 如因 maxtokens 限制截断，自动续写
> > function chatgpt($text, $chatID){
> >   //...
> >   $return = trim($response_arr['choices'][0]['message']['content']);
> >   if($response_arr['choices'][0]['finish_reason']=="length"){
> >       $return = $return.chatgpt("continue", $chatID);
> >   }
> >   return $return;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果finish_reason=length，就自动发 "continue" ，直至写完，拼合后返回给用户。这个过程用户是无感的，唯一感觉是多个请求会返回得慢一些。
> > 局限于不会 nodejs ，供参考。 有前端界面还可以提供自动续写开关，把判断放到前端。
> 
> 在正常使用的时候，有时输入“continue”，GPT会从头开始反馈消息，您后台这么处理，有遇到不接着写，而是从头开始写的情况吗？

没有，但是用官方和会有这种情况，很迷惑

**Comment by oasis168** [comment]
可以将这代码融到此项目中吗？

**Comment by Cp0204** [comment]
> 可以将这代码融到此项目中吗？

不会node.js，you can you up, 欢迎PR

**Comment by oasis168** [comment]
俺也不会，不然早出手了

**Comment by yhyu13** [comment]
问cursor js怎么写
