### ISSUE TITLE
昨天还能用，今天发送任何信息都是报错“出错了，稍后重试吧”

### ISSUE THREAD

**Issue by 844104310** [Yidadaa/ChatGPT-Next-Web#408]

**Comment by zealotCE** [comment]
先检查一下你账号又没有被ban，以及上你服务器上测试能不能正常访问。
最近openai疯狂ban账号

**Comment by 844104310** [comment]
账号没有被ban，官网还能正常使用

**Comment by Yidadaa** [comment]
请提供 vercel 控制台截图

**Comment by 844104310** [comment]
![image](https://user-images.githubusercontent.com/56929224/229449622-065a50d6-bf45-4359-bddd-35e8d5a4a630.png)

**Comment by Yidadaa** [comment]
View Runtime Logs 的截图

**Comment by 844104310** [comment]
![image](https://user-images.githubusercontent.com/56929224/229450690-e8ebfab0-0367-4ac2-8bf5-fdeedbd6db6e.png)

**Comment by 844104310** [comment]
这个报错怎么说 ？

**Comment by Yidadaa** [comment]
应该是你 key 过期了，用演示站测试一下。

**Comment by 844104310** [comment]
请问需要如何操作？

**Comment by 844104310** [comment]
指的是API KEY么，这个我早上换过，没有用；如果不是 方便截图看下是改哪里
![image](https://user-images.githubusercontent.com/56929224/229455390-35a913eb-d901-4ed1-b8b2-0cc150b0ea9e.png)

**Comment by Yidadaa** [comment]
在你截图的网页里填入你自己的 api key，然后发几条消息，看看能不能用。

**Comment by Yidadaa** [comment]
把 openai 余额页面截图发来看看。

**Comment by 844104310** [comment]
![image](https://user-images.githubusercontent.com/56929224/229457132-8e5e4d06-986c-4b92-99e9-22238440165d.png)
yue余额也显示不出了，之前是有的17🔪

**Comment by Yidadaa** [comment]
我的意思是你 openai 官网的余额截图。

**Comment by 844104310** [comment]
![image](https://user-images.githubusercontent.com/56929224/229458376-6776fa23-1320-4c18-bcb6-b278267fcb37.png)
是这个吧

**Comment by Yidadaa** [comment]
你的余额已经过期了，绑个美国信用卡或者换新账号吧。

**Comment by 844104310** [comment]
使用额度用完了是这个意思？

**Comment by coffeepepsi** [comment]
和上面情况一样
但是 chat.openai.com 页面访问还是可以使用
