### ISSUE TITLE
功能优化：显示余额功能优化

### ISSUE THREAD

**Issue by ZyXianzi** [Yidadaa/ChatGPT-Next-Web#409]
考虑如下场景：我在部署后，设置了一个密码，我将其分享给身边好友使用，但我并不希望他能看到我的使用份额。因此是否能对显示余额功能进行如下优化：仅当在设置页面输入Api Key后才可以查看余额，仅输入访问码时无法查看余额。同时希望访问码与Api Key的输入框能使用密码格式，不要直接显示明文。
若作者采纳，我可以进行开发。

**Comment by Yidadaa** [comment]
期待 PR，开发时注意：
- 提供查看密码选项，用户点击后查看密码原始文本

**Comment by ZyXianzi** [comment]
> 期待 PR，开发时注意：
> 
> - 提供查看密码选项，用户点击后查看密码原始文本

已PR~
