### ISSUE TITLE
最新 commit 版本出现 React 错误

### ISSUE THREAD

**Issue by bohanyang** [Yidadaa/ChatGPT-Next-Web#41]
以及设置中没有显示访问码的地方（确认过`CODE`环境变量已经配置并生效）

<img width="772" alt="image" src="https://user-images.githubusercontent.com/8384161/227766093-1d289995-bd08-4b25-bb04-08ee2b14990d.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/8384161/227766108-9204978a-ebc2-400e-8482-8c7fddd27e8a.png">

**Comment by Yidadaa** [comment]
这是 dev 环境的错误，请使用 `yarn build && yarn start` 部署你的项目。

**Comment by bohanyang** [comment]
你好，yarn start（即build后的生产模式中）也有同样的错误，出现在console中。

主要问题是设置中没有出现填写访问码的地方。
不知道和这个错误是否有关。

**Comment by Yidadaa** [comment]
请确认产物的 head > meta 字段的 access 值是否为 enabled：

![](https://user-images.githubusercontent.com/16968934/227766439-822b6b28-e87d-4e8b-aae0-80a8fc21b313.png)

**Comment by bohanyang** [comment]
是 disabled （与您的截图一致）。
但是 API 访问限制是生效了的。
<img width="754" alt="image" src="https://user-images.githubusercontent.com/8384161/227766671-3017428d-907e-46c2-a5ae-18cbe1148cc0.png">

**Comment by Yidadaa** [comment]
我们到 discord 中详聊吧：https://discord.gg/zrhvHCr79N

**Comment by Yidadaa** [comment]
已确定为自定义部署时未在编译时传入环境变量导致的问题。
