### ISSUE TITLE
Code 设置不生效

### ISSUE THREAD

**Issue by helloChenLei** [Yidadaa/ChatGPT-Next-Web#413]
我在部署的时候添加的 CODE ，部署成功后并没有设置 CODE，项目依旧可以访问。

<img width="1005" alt="Xnip2023-04-03_17-24-22" src="https://user-images.githubusercontent.com/94668118/229470051-384a40fd-413a-4f94-8253-8b55c4e7cfd8.png">

我的 code 是空的。
<img width="1037" alt="Xnip2023-04-03_17-24-34" src="https://user-images.githubusercontent.com/94668118/229470079-5bb5b8ac-6f7f-46f8-aaf7-3534790faa3f.png">
但是依旧可以发消息？
<img width="656" alt="Xnip2023-04-03_17-24-40" src="https://user-images.githubusercontent.com/94668118/229470110-6eb31888-cf31-4ce5-b4ec-91cf7d1d85b8.png">
请问是哪里没有设置正确吗

**Comment by Yidadaa** [comment]
你提供了 api key 啊

**Comment by Yidadaa** [comment]
我寻思你红圈不是已经圈出来了？

**Comment by helloChenLei** [comment]
噢，我懂了。Code 和 key 任选一个就行。。
