### ISSUE TITLE
RT: 未判断输入值合法性

### ISSUE THREAD

**Issue by hulog** [Yidadaa/ChatGPT-Next-Web#418]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/a4743034a9965873de6d639f496f749827bf8bd3/app/components/settings.tsx#L457-L469

在设置组件中，未判断输入值 `e.currentTarget.valueAsNumber` 的合法性，导致配置数据错误。

类似问题该组件中还有几处存在，麻烦开启表单验证 🙏🏻

**Comment by Yidadaa** [comment]
发请求的时候会过滤掉不合法数据，这个会导致什么问题吗？按理来说 input type 设置为 number 之后，应该输入不了其他内容？
