### ISSUE TITLE
非常喜欢这个项目，请问可以付费定制功能吗？

### ISSUE THREAD

**Issue by ClarenceDan** [Yidadaa/ChatGPT-Next-Web#42]
希望能在前端加上输入ApiKey的功能，以及后台key轮询，重新提问等细节功能

**Comment by Yidadaa** [comment]
*   前端输入 api key 会增加封号风险，应该确认是不会加该功能，不过你可以自己 fork 一个分支自行开发。
*   不太清楚你说的后台 key 轮询是指什么，可以指定多个 api key，然后挨个分配使用？这样也有可能会触发 openai 风控，建议慎用。
*   重新提问的功能正在开发中，后续版本会更新。

**Comment by ClarenceDan** [comment]
好的感谢，我自己试试！轮询可以在网站负载较高的时候提高回复效率，之前在vercel部署过类似的网站还没有遇到封号的情况
