### ISSUE TITLE
[error response]:You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by xkdvSrPD** [Yidadaa/ChatGPT-Next-Web#421]
自己部署之后发送消息显示
![image](https://user-images.githubusercontent.com/85148161/229509956-b7e92e9b-dfae-46b6-9b00-d30005ac39df.png)
```json
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```
官方Demo是同样的错误
![image](https://user-images.githubusercontent.com/85148161/229510164-177ee15a-ced7-41f6-bab8-e52a32174dc0.png)
官网可以正常使用，并且没有超出
![image](https://user-images.githubusercontent.com/85148161/229510704-d88687b1-38ee-4a58-972e-f49b69d7b4db.png)

**Comment by SiShiBa48** [comment]
请问是怎么解决这个问题的？

**Comment by convers39** [comment]
同問怎麼解決的？

**Comment by convers39** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/428
