### ISSUE TITLE
重新fork部署后访问提示404

### ISSUE THREAD

**Issue by simpletrain** [Yidadaa/ChatGPT-Next-Web#422]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/12999581/229515576-c02f350e-405c-4c72-b459-ccf33f04cec9.png">

**Comment by Yidadaa** [comment]
请确认 vercel 是否部署就绪。

**Comment by jeremy-feng** [comment]
一样的问题，请问你解决了吗

**Comment by jeremy-feng** [comment]
> 一样的问题，请问你解决了吗

解决了。注意 `BASE_URL` 不要加 https 即可。
