### ISSUE TITLE
希望可以加入一个功能开关，“尽力上传历史会话消息”，而不是局限于目前的固定条数

### ISSUE THREAD

**Issue by Scenx** [Yidadaa/ChatGPT-Next-Web#425]
使用一个工具（python有）可以计算出token，按接口能接受的token的max去上传最多的上下文，体验更佳

**Comment by Cp0204** [comment]
这个没有十全十美的方案，因为你不确定回复的token数，就算精确计算上传多少上下文，预留回复多少token给回复呢？都是个玄学。
