### ISSUE TITLE
如何把openai接口改成自己代理的接口呢？

### ISSUE THREAD

**Issue by chenhuohuo23** [Yidadaa/ChatGPT-Next-Web#426]
怎么修改或者自定义接口api.openai.com?
![api](https://user-images.githubusercontent.com/127205118/229531227-dd8e7f5d-14e5-4f9e-aba1-9e070bfa57aa.png)

**Comment by Yidadaa** [comment]
README 里有写，环境变量里增加 BASE_URL 就行。

**Comment by chenhuohuo23** [comment]
> README 里有写，环境变量里增加 BASE_URL 就行。

具体要怎么操作呢?
我看页面只有两个选项
![api2](https://user-images.githubusercontent.com/127205118/229550223-0f8c1667-5fd7-456e-9783-bfa64f62ce9c.png)

**Comment by Yidadaa** [comment]
你需要部署之后手动去环境变量页增加对应的值。
