### ISSUE TITLE
添加指定 Organization Requesting 的设置

### ISSUE THREAD

**Issue by sotvokun** [Yidadaa/ChatGPT-Next-Web#427]
需求：可以通过设置页面或是环境变量指定用于消费的 Organization
动机：同一个账号加入多个 Organization，需要为每一个 Organization 各自部署时，需要实现每一个 org 单独统计各自的使用情况。

相关文档：
https://platform.openai.com/docs/api-reference/requesting-organization

**Comment by Yidadaa** [comment]
想问一下一般哪种用户会归属于多个 org，企业用户？想知道目前企业调用 openai api 是如何突破 request limit rate 的，如果能分享一下，十分感谢。

**Comment by sotvokun** [comment]
我这边的项目是为用户提供和部署私有的 ChatGPT 服务，我是作为开发者身份加入的 org。所以有需求区分各个 request 的 org。

rate limit 这个问题我也考虑过，但还没有进行实践。它的 limit 是和 org 关联的，所以理论上如果有多个 org 的话可以做“负载均衡”（反正都需要自己携带上下文）：

https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

> If you are sharing your organization with other users, note that limits are applied per organization and not per user.

**Comment by Yidadaa** [comment]
了解了，感谢分享。

**Comment by yinm0591** [comment]
@sotvokun 试试这个项目，可以加OrgID。部署在cloudflare workers上，免费版支持10万次访问/天，不用绑卡。

https://github.com/yinm0591/cf-openai-with-sub-account-proxy/blob/main/workers.js

**Comment by imyuanx** [comment]
有计划支持这个功能吗？

**Comment by yinm0591** [comment]
@imyuanx   支持orgid有2种方式，第1种是在cloudflare workers上部署 https://github.com/yinm0591/cf-openai-with-sub-account-proxy/ ，然后将base_url改到worker的地址。 第2种方式是修改 /app/api/common.ts，加入orgid支持，然后重新build镜像。

**Comment by imyuanx** [comment]
> @imyuanx 支持orgid有2种方式，第1种是在cloudflare workers上部署 https://github.com/yinm0591/cf-openai-with-sub-account-proxy/ ，然后将base_url改到worker的地址。 第2种方式是修改 /app/api/common.ts，加入orgid支持，然后重新build镜像。

你项目的思路很不错，但是增加一层中转会导致请求链路变长

用户是不用关心 orgid 的，所以在设置中增加这个配置项不太合适，我希望是能够通过环境变量配置 orgid

**Comment by yinm0591** [comment]
@imyuanx /app/api/common.ts文件21~28行改成下面的代码，配置环境变量OPENAI_ORGID

```javasript
  let header={
    "Content-Type": "application/json",
    Authorization: `Bearer ${apiKey}`,
  };

  if(process.env.OPENAI_ORGID){
    header["OpenAI-Organization"] = process.env.OPENAI_ORGID;
    console.log("[ORGID]", process.env.OPENAI_ORGID);
  }

  return fetch(`${baseUrl}/${openaiPath}`, {
    headers: header,
    method: req.method,
    body: req.body,
  });
```

**Comment by Yidadaa** [comment]
@yinm0591 提个 PR？我合进去，环境变量建议改为 `OPENAI_ORG_ID`。

**Comment by yinm0591** [comment]
@Yidadaa PR递交有点问题， /app/api/common.ts的代码我已经测试过了，应该OK，供参考：

```javascript
import { NextRequest } from "next/server";

const OPENAI_URL = "api.openai.com";
const DEFAULT_PROTOCOL = "https";
const PROTOCOL = process.env.PROTOCOL ?? DEFAULT_PROTOCOL;
const BASE_URL = process.env.BASE_URL ?? OPENAI_URL;

export async function requestOpenai(req: NextRequest) {
  const apiKey = req.headers.get("token");
  const openaiPath = req.headers.get("path");

  let baseUrl = BASE_URL;

  if (!baseUrl.startsWith("http")) {
    baseUrl = `${PROTOCOL}://${baseUrl}`;
  }

  console.log("[Proxy] ", openaiPath);
  console.log("[Base Url]", baseUrl);

  if (process.env.OPENAI_ORG_ID) {
    console.log("[Org ID]", process.env.OPENAI_ORG_ID);
  }

  return fetch(`${baseUrl}/${openaiPath}`, {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
      ...(process.env.OPENAI_ORG_ID && { "OpenAI-Organization": process.env.OPENAI_ORG_ID }),
    },
    method: req.method,
    body: req.body,
  });
}
```

**Comment by yinm0591** [comment]
@Yidadaa 已PR
