### ISSUE TITLE
部署后一直显示错误

### ISSUE THREAD

**Issue by dannyc97230** [Yidadaa/ChatGPT-Next-Web#428]
问问题时一直显示：
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by yankunsong** [comment]
注册时免费的额度用完了或者过期（好多是4.1号过期）了。需要绑定支付方式，以后得花钱才能用。

**Comment by Yidadaa** [comment]
账号过期了

**Comment by jinwendaiya** [comment]
> 
同样的问题，但是如果是账户过期了 ，为什么我再官方的页面登录后还能正常对话

**Comment by yankunsong** [comment]
官网不用api的额度

**Comment by zyh08808** [comment]
一样的报错,请问该如何解决？
