### ISSUE TITLE
访问控制逻辑的优化建议

### ISSUE THREAD

**Issue by ruixing1001** [Yidadaa/ChatGPT-Next-Web#43]
马上更新体验了访问控制功能。
为了用户的良好体验，可否前10个提问不限制，谁都可以提。
超过10个提问就开启访问控制，必须输授权码才能继续

**Comment by ruixing1001** [comment]
如果能把提问限制数量加到环境变量中可以随时改那最好了

**Comment by iSource** [comment]
个人感觉这个需求有点业务化，这不是一个商业项目，在其中添加类似于商业试用的功能点太不合适。

**Comment by Yidadaa** [comment]
可以去找人付费定制这个功能，我就不在这个需求上花时间了哈。
