### ISSUE TITLE
无法显示图片

### ISSUE THREAD

**Issue by yuntian123456** [Yidadaa/ChatGPT-Next-Web#431]
如图，图片都显示不了。每次请求图片，似乎都是**随机使用不同的图床？**
![image](https://user-images.githubusercontent.com/19453085/229558411-847ff6bb-9ffa-4f2d-ab9c-d5c511e7b316.png)
直接复制给出的链接到浏览器，显示没有权限
![image](https://user-images.githubusercontent.com/19453085/229558952-94812ff7-7139-4e4e-be64-cd7e9825087d.png)

当然偶尔也有正常显示图片的时候，但绝大多时候都是显示不了图片的（图床权限问题？）
![image](https://user-images.githubusercontent.com/19453085/229559821-eadcbf7a-de52-4877-97d6-357968a5bec7.png)

**Comment by AprilNEA** [comment]
图床本身会限制外链

**Comment by yuntian123456** [comment]
那咋整？图床是随机选择的吗？
