### ISSUE TITLE
自动同步仓库好像不起作用了

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#432]
看了sync改为每6小时一次，但是不起作用，并没有同步

**Comment by yorunning** [comment]
到仓库设置里把action功能打开

**Comment by ZyXianzi** [comment]
默认Fork仓库会禁止action自动运行，需要在仓库设置里手动打开～

**Comment by viquu** [comment]
我的也一直在报错。
错误信息：
The process '/usr/bin/sh' failed with exit code 128

**Comment by yorunning** [comment]
> 我的也一直在报错。 错误信息： The process '/usr/bin/sh' failed with exit code 128

已经加了contents: write的权限，但你的仓库还是[read权限](https://github.com/viquu/ChatGPT-Next-Web/actions/runs/4602923800/jobs/8132418151#step:1:19)，奇怪

**Comment by viquu** [comment]
> > 我的也一直在报错。 错误信息： The process '/usr/bin/sh' failed with exit code 128
> 
> 已经加了contents: write的权限，但你的仓库还是[read权限](https://github.com/viquu/ChatGPT-Next-Web/actions/runs/4602923800/jobs/8132418151#step:1:19)，奇怪

感谢，我刚才的权限没有加上。
原来是要在Workflow permissions：下选中read and wirte permissions，现在可以了。

**Comment by yorunning** [comment]
> > > 我的也一直在报错。 错误信息： The process '/usr/bin/sh' failed with exit code 128
> > 
> > 
> > 已经加了contents: write的权限，但你的仓库还是[read权限](https://github.com/viquu/ChatGPT-Next-Web/actions/runs/4602923800/jobs/8132418151#step:1:19)，奇怪
> 
> 感谢，我刚才的权限没有加上。 原来是要在Workflow permissions：下选中read and wirte permissions，现在可以了。

帮忙测一下，把Workflow permissions的权限调回原来的状态，在运行一次，因为我的仓库没设置这个也是能正常运行的。

**Comment by viquu** [comment]
> > > > 我的也一直在报错。 错误信息： The process '/usr/bin/sh' failed with exit code 128
> > > 
> > > 
> > > 已经加了contents: write的权限，但你的仓库还是[read权限](https://github.com/viquu/ChatGPT-Next-Web/actions/runs/4602923800/jobs/8132418151#step:1:19)，奇怪
> > 
> > 
> > 感谢，我刚才的权限没有加上。 原来是要在Workflow permissions：下选中read and wirte permissions，现在可以了。
> 
> 帮忙测一下，把Workflow permissions的权限调回原来的状态，在运行一次，因为我的仓库没设置这个也是能正常运行的。

奇怪，改回去也成功了。会不会是代码是最新的，没有新更新的代码导致的。

**Comment by yorunning** [comment]
> > > > > 我的也一直在报错。 错误信息： The process '/usr/bin/sh' failed with exit code 128
> > > > 
> > > > 
> > > > 已经加了contents: write的权限，但你的仓库还是[read权限](https://github.com/viquu/ChatGPT-Next-Web/actions/runs/4602923800/jobs/8132418151#step:1:19)，奇怪
> > > 
> > > 
> > > 感谢，我刚才的权限没有加上。 原来是要在Workflow permissions：下选中read and wirte permissions，现在可以了。
> > 
> > 
> > 帮忙测一下，把Workflow permissions的权限调回原来的状态，在运行一次，因为我的仓库没设置这个也是能正常运行的。
> 
> 奇怪，改回去也成功了。会不会是代码是最新的，没有新更新的代码导致的。

OK，我大概知道原因了，GITHUB_TOKEN缓存了sync.yaml文件没修改权限之前的状态。

**Comment by smallyunet** [comment]
我试了一下，前几天的自动运行一直是失败的，刚才手动触发是成功的

**Comment by Jessire** [comment]
> > > > > > 我的也一直在报错。 错误信息： The process '/usr/bin/sh' failed with exit code 128
> > > > > 
> > > > > 
> > > > > 已经加了contents: write的权限，但你的仓库还是[read权限](https://github.com/viquu/ChatGPT-Next-Web/actions/runs/4602923800/jobs/8132418151#step:1:19)，奇怪
> > > > 
> > > > 
> > > > 感谢，我刚才的权限没有加上。 原来是要在Workflow permissions：下选中read and wirte permissions，现在可以了。
> > > 
> > > 
> > > 帮忙测一下，把Workflow permissions的权限调回原来的状态，在运行一次，因为我的仓库没设置这个也是能正常运行的。
> > 
> > 
> > 奇怪，改回去也成功了。会不会是代码是最新的，没有新更新的代码导致的。
> 
> OK，我大概知道原因了，GITHUB_TOKEN缓存了sync.yaml文件没修改权限之前的状态。改权限是最近的一次提交，你前面也运行过缓存了

<img width="853" alt="image" src="https://user-images.githubusercontent.com/61305123/231474549-223e39a9-7db8-4fa3-a110-c844db0619bb.png">
大佬看看，改了权限手动自动都失败了

**Comment by Jessire** [comment]
> 

已成功，感谢大佬回复
