### ISSUE TITLE
升级到1.9.1之后，部分浏览器无法运行了。

### ISSUE THREAD

**Issue by chenliang720** [Yidadaa/ChatGPT-Next-Web#437]
昨天从1.6升级到了1.9.1，发现360极速浏览器打开APP时，抛出：Application error: ...... 如图所示。另外，在手机微信中打开也提示该错误。
![app_err](https://user-images.githubusercontent.com/31513922/229665429-11d60fe1-8d4e-4657-b92a-32bcd3d11515.png)

**Comment by awwl** [comment]
的确是这样

**Comment by Yidadaa** [comment]
等待 v1.9.2 发布：https://github.com/Yidadaa/ChatGPT-Next-Web/releases/tag/v1.9.2
