### ISSUE TITLE
libpng warning: iCCP: cHRM chunk does not match sRGB

### ISSUE THREAD

**Issue by kevins0116** [Yidadaa/ChatGPT-Next-Web#44]
libpng warning: iCCP: cHRM chunk does not match sRGB
[Chat Stream]  [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}

**Comment by Yidadaa** [comment]
你是在本地部署？

请加入 discord 群聊：https://discord.gg/zrhvHCr79N

**Comment by Yidadaa** [comment]
Might be network problems, please make sure that you can access openai service at your country.
