### ISSUE TITLE
Mac下允许Cmd-Enter提交

### ISSUE THREAD

**Issue by h4x3rotab** [Yidadaa/ChatGPT-Next-Web#442]
目前可以配置几种提交快捷键，在非Mac环境下Ctrl-Enter很合适，但Mac下还是Cmd-Enter比较好。希望可以改进，增加Ctrl/Cmd-Enter提交快捷键的选项。

**Comment by Yidadaa** [comment]
Meta + Enter 就是 Cmd + Enter

**Comment by h4x3rotab** [comment]
感谢快速回复。的确解决了问题，但如果在看到回复以前是想不到的，相信可能有很多用户也是这样。在前端上说明一下如何？
