### ISSUE TITLE
可否增加poe api支持

### ISSUE THREAD

**Issue by terrytwomail** [Yidadaa/ChatGPT-Next-Web#443]
当时订了年费的poe，目前可以透过poe api项目获得自己的api。可以也增加poe的支持吗～

**Comment by Yidadaa** [comment]
请尝试通过设置 BASE_URL 环境变量的方式使用其他平台 api

**Comment by xiandan-erizo** [comment]
请问怎么解决的呢？

**Comment by qq821181867** [comment]
[poe proxy](https://github.com/juzeon/poe-openai-proxy)

return [object Object]
