### ISSUE TITLE
允许更改系统默认model

### ISSUE THREAD

**Issue by h4x3rotab** [Yidadaa/ChatGPT-Next-Web#444]
目前部署的项目默认请求 gpt3.5-turbo，虽然每个用户都可以独立在设置里修改，但每次换一个浏览器都需要重新设置，有的时候会忘记。如果能在部署的时候（比如docker部署），或者是提供一个全局修改默认值的功能，就会非常方便。

**Comment by Scenx** [comment]
确实 我也需要

**Comment by leochen12-rgb** [comment]
确实，变量里没有

**Comment by suyaoyong** [comment]
我连在哪里修改都不知道，哪位大神多指点一下。我想改过默认值再部署后，给办公室的兄弟们也可以用上。

**Comment by RogerProSelf** [comment]
+1

**Comment by ywgx** [comment]
> 我连在哪里修改都不知道，哪位大神多指点一下。我想改过默认值再部署后，给办公室的兄弟们也可以用上。

app/store/app.ts

**Comment by wss-sosen** [comment]
修改代码中（app/store/app.ts）大概第134-153行：以下是加入注释的内容，自己看情况修改即可。
// 默认的聊天配置
const DEFAULT_CONFIG: ChatConfig = {
// 历史消息数量
historyMessageCount: 4,
// 消息长度大于此阈值时自动压缩
compressMessageLengthThreshold: 1000,
// 是否发送机器人消息
sendBotMessages: true as boolean,
// 提交消息的默认按键
submitKey: SubmitKey.Enter as SubmitKey,
// 默认头像样式
avatar: "1f603",
// 默认字体大小
fontSize: 14,
// 默认主题
theme: Theme.Light as Theme,
// 默认开启或关闭紧凑边框
tightBorder: false,
// 发送消息时是否显示预览气泡
sendPreviewBubble: false,
// 是否禁用提示信息
disablePromptHint: false,
// 模型相关配置
modelConfig: {
// 模型名称
model: "gpt-3.5-turbo",
// 默认随机数
temperature: 1,
// 生成消息的最大token数
max_tokens: 2000,
// 默认的话题新鲜数
presence_penalty: 0,
},
};

部署chatgpt不如先好好学习怎么用，不会的就问chatgpt啊。大佬哪儿有功夫给你当客服，本身开源就已经够意思了

**Comment by rookie-LiMr** [comment]
请问大佬一下，为啥我默认3.5，但是我提问它却说自己是gpt2，我在官方chatgpt中同样问题，它却回答是3.5

**Comment by shelken** [comment]
> 修改代码中（app/store/app.ts）大概第134-153行：以下是加入注释的内容，自己看情况修改即可。 // 默认的聊天配置 const DEFAULT_CONFIG: ChatConfig = { // 历史消息数量 historyMessageCount: 4, // 消息长度大于此阈值时自动压缩 compressMessageLengthThreshold: 1000, // 是否发送机器人消息 sendBotMessages: true as boolean, // 提交消息的默认按键 submitKey: SubmitKey.Enter as SubmitKey, // 默认头像样式 avatar: "1f603", // 默认字体大小 fontSize: 14, // 默认主题 theme: Theme.Light as Theme, // 默认开启或关闭紧凑边框 tightBorder: false, // 发送消息时是否显示预览气泡 sendPreviewBubble: false, // 是否禁用提示信息 disablePromptHint: false, // 模型相关配置 modelConfig: { // 模型名称 model: "gpt-3.5-turbo", // 默认随机数 temperature: 1, // 生成消息的最大token数 max_tokens: 2000, // 默认的话题新鲜数 presence_penalty: 0, }, };
> 
> 部署chatgpt不如先好好学习怎么用，不会的就问chatgpt啊。大佬哪儿有功夫给你当客服，本身开源就已经够意思了

首先，你指出可以在哪可以修改源代码这是非常respect的，但我不同意后面的说法，首先部署的人未必一定要操作源代码，了解源代码。而且这是一个需求，开源项目被人提需求我觉得是正常且能够理解的，至于需求的重要性高低以及是否有必要这可以由开发者来决定。但是，从这个需求出发，我认为有必要把这些环境变量开放出去，这增加了程序的灵活性。再次感谢开发者的努力

**Comment by mengxianbin** [comment]
我用 gpt-4 请求, 总是提示 模型不存在, 请问如何解决？
2个 gpt-3.5 选项 都可用, 4个 gpt-4 选项 都不可用

{
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by rookie-LiMr** [comment]
> 我用 gpt-4 请求, 总是提示 模型不存在, 请问如何解决？ 2个 gpt-3.5 选项 都可用, 4个 gpt-4 选项 都不可用
> 
> ```json
> {
>     "error": {
>         "message": "The model: `gpt-4` does not exist",
>         "type": "invalid_request_error",
>         "param": null,
>         "code": "model_not_found"
>     }
> }
> ```

你没有4的使用权限，可以去openai官方申请。

**Comment by mengxianbin** [comment]
> > 我用 gpt-4 请求, 总是提示 模型不存在, 请问如何解决？ 2个 gpt-3.5 选项 都可用, 4个 gpt-4 选项 都不可用
> > ```json
> > {
> >     "error": {
> >         "message": "The model: `gpt-4` does not exist",
> >         "type": "invalid_request_error",
> >         "param": null,
> >         "code": "model_not_found"
> >     }
> > }
> > ```
> 
> 你没有4的使用权限，可以去openai官方申请。

我有 plus, 在官方 web 端是可以正常使用 gpt-4 的, 通过 API 访问 gpt-4 还需要单独申请吗？

**Comment by mengxianbin** [comment]
> > 我用 gpt-4 请求, 总是提示 模型不存在, 请问如何解决？ 2个 gpt-3.5 选项 都可用, 4个 gpt-4 选项 都不可用
> > ```json
> > {
> >     "error": {
> >         "message": "The model: `gpt-4` does not exist",
> >         "type": "invalid_request_error",
> >         "param": null,
> >         "code": "model_not_found"
> >     }
> > }
> > ```
> 
> 你没有4的使用权限，可以去openai官方申请。

明白了, plus 只提供 preview, 而 gpt-4 api 访问 需要继续等 waitlist.

**Comment by aczls** [comment]
为什么我用的3.5模型问他是基于gpt哪一代开发的他跟我说是gpt2

**Comment by aczls** [comment]
> 请问大佬一下，为啥我默认3.5，但是我提问它却说自己是gpt2，我在官方chatgpt中同样问题，它却回答是3.5
我也出现这样的情况 他回答我他是三有1700亿参数 官方回答说是3.5有2万亿参数

**Comment by Knight174** [comment]
> > 请问大佬一下，为啥我默认3.5，但是我提问它却说自己是gpt2，我在官方chatgpt中同样问题，它却回答是3.5
> > 我也出现这样的情况 他回答我他是三有1700亿参数 官方回答说是3.5有2万亿参数

我问的结果，它说是 3

**Comment by doveppp** [comment]
现在好像只能通过环境变量禁用gpt4，还不能通过环境变量设置默认模型？ 用docker的话改代码不太方便

**Comment by caiguanhao** [comment]
如果是用 nginx 的话，可以参照这个配置直接修改 js 代码的默认值：
```
location ~ ^/_next/static/chunks/app/page-[a-z0-9]+\.js$ {
  proxy_pass http://127.0.0.1:3000;
  proxy_set_header Accept-Encoding "";
  sub_filter 'models:d.Fv,modelConfig:{model:"gpt-3.5-turbo"' 'models:d.Fv,modelConfig:{model:"gpt-4"';
  sub_filter_types *;
}
```

**Comment by doveppp** [comment]
> 如果是用 nginx 的话，可以参照这个配置直接修改 js 代码的默认值：
> 
> ```
> location ~ ^/_next/static/chunks/app/page-[a-z0-9]+\.js$ {
>   proxy_pass http://127.0.0.1:3000;
>   proxy_set_header Accept-Encoding "";
>   sub_filter 'models:d.Fv,modelConfig:{model:"gpt-3.5-turbo"' 'models:d.Fv,modelConfig:{model:"gpt-4"';
>   sub_filter_types *;
> }
> ```

好的谢谢老哥
