### ISSUE TITLE
docker 部署 latest 还提示有更新

### ISSUE THREAD

**Issue by selfboot** [Yidadaa/ChatGPT-Next-Web#446]
```
docker pull yidadaa/chatgpt-next-web:latest

docker run -d -p 3000:3000 -e OPENAI_API_KEY="***" -e CODE="***" --name chatgpt-container yidadaa/chatgpt-next-web:latest
```

部署后，还提示有版本更新：

<img width="535" alt="image" src="https://user-images.githubusercontent.com/2769831/229695074-81289047-dbeb-4536-b2e7-5a2326066fb8.png">

**Comment by Yidadaa** [comment]
正常，docker 版本会落后一到两天

**Comment by selfboot** [comment]
https://hub.docker.com/r/yidadaa/chatgpt-next-web/tags
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/2769831/229704179-b1b4501c-07d8-4ce4-96e2-14b42d48002a.png">

我看上面 latest的镜像也是1.9.2，实际安装拉到的镜像，版本是1.8 的
