### ISSUE TITLE
更改model為gpt-4後，仍然是以gpt-3.5-turbo回答

### ISSUE THREAD

**Issue by jtung4** [Yidadaa/ChatGPT-Next-Web#451]
確認API已經獲准使用gpt-4，但在設定中選擇model為gpt-4後，在OpenAI後台發現request仍是以gpt-3.5-turbo-0301處理

**Comment by al123xiaaaa** [comment]
我也是一样

**Comment by Yidadaa** [comment]
已确认为 bug

**Comment by xingke2023** [comment]
可以分享一下gpt4 api吗

**Comment by wejudging** [comment]
我也是！！！

**Comment by wejudging** [comment]
> 已确认为 bug

大佬已经在解决了吗

**Comment by wejudging** [comment]
大佬大概什么时候修复这个bug呀！

**Comment by zhongmeizhi** [comment]
me too

**Comment by zhongmeizhi** [comment]
![image](https://user-images.githubusercontent.com/17895124/229981444-21423041-c545-49bf-8e1a-1c575ededda1.png)
![image](https://user-images.githubusercontent.com/17895124/229981473-8a27869c-f1f6-4a22-a1fd-3e3ad45e7e87.png)

**Comment by wk-mike** [comment]
要在这个网址看 [Usage](https://platform.openai.com/account/usage) `https://platform.openai.com/account/usage`
在下面找到`Daily usage breakdown (UTC) `里面的`Language model usage` 查看调用的模型

我发现我的GPT4可以用，只不过偶尔是正常的，使用的版本是 `9d328e` 倒数第二新的版本。
例如
```
gpt-4-0314, 4 requests
752 prompt + 784 completion = 1,536 tokens
gpt-3.5-turbo-0301, 5 requests 
2,757 prompt + 2,248 completion = 5,005 tokens
```

**Comment by zhongmeizhi** [comment]
我尝试去做bug修复，但是发现目前的”/api/chat-stream“服务model不可用
<img width="480" alt="截屏2023-04-05 下午2 05 36" src="https://user-images.githubusercontent.com/17895124/229994896-1289e73d-6b2d-4eb9-8af4-aa8f3bffdaab.png">
<img width="480" alt="截屏2023-04-05 下午2 05 36" src="https://user-images.githubusercontent.com/17895124/229994971-5167495d-9aee-4528-ae45-7ff3f8002adb.png">
