### ISSUE TITLE
账户余额

### ISSUE THREAD

**Issue by 175986vv** [Yidadaa/ChatGPT-Next-Web#452]
设置里面的账户余额是什么意思？我那里显示的是本月已使用￥0.11

**Comment by leochen12-rgb** [comment]
你已经使用API余额$0.11

**Comment by taylorchen709** [comment]
我的账户余额那里显示两个问号？？  是什么原因？
{
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
}

**Comment by Yidadaa** [comment]
@taylorchen709 更新代码到最新重试。
