### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by zheshidingxiaoke** [Yidadaa/ChatGPT-Next-Web#455]
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by GOWxx** [comment]
从 meesage 来看是额度用尽。检查你的账号是否可以用以及你的 api 余额。

**Comment by shiooic** [comment]
同样的问题，也填入自己的api了，用的3.5 turbo 模型
