### ISSUE TITLE
非常nice的项目，UI设计很简洁好看，我提一点建议

### ISSUE THREAD

**Issue by cokice** [Yidadaa/ChatGPT-Next-Web#46]
日夜转换可以做个选项在首页上方，不必在设置里设置
话题总结效果不好，每次总结对话标题都为闲聊，openai好像有提供方法来自动总结内容来生成标题

**Comment by Yidadaa** [comment]
1. 喜好问题，我希望聊天界面保持简洁，建议使用 auto 与系统的深色模式保持一致
2. 总结的效果与你初次聊天内容的长短有关，如果上来只是简单的问候，那么就只能总结为闲聊了

**Comment by MC-dusk** [comment]
但现在把无边框模式的设置项也加到首页了😂，感觉也不差个夜间模式切换。有时候确实需要经常切换，在设置里面每次都得多点几下稍微麻烦一点，还是希望能把深色模式切换按钮加到首页。

**Comment by Yidadaa** [comment]
@MC-dusk 所以自动主题会有什么问题吗？

**Comment by Yidadaa** [comment]
这是一个很小众的需求，却需要占用主要的聊天界面一个 button 位，我个人认为非常不划算，后面还有相当多的功能要加。

**Comment by Yidadaa** [comment]
尤其是在移动端，顶部三个 button 已经被占满了。
