### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ljk5** [Yidadaa/ChatGPT-Next-Web#460]
部署在同一局域网下使用公共的key,其他设备无法调用具备PLUS key的权限，我使用docker部署的该项目 并且启动容器时使用的key是就具有plus权限的，但无法实现该功能

**Comment by Yidadaa** [comment]
你说的 plus 权限是什么

**Comment by ljk5** [comment]
使用已购买plus的账号分发出来的apikey来作为docker容器启动，应具备访问 api4.0接口的权限，但在容器运行起来后，并没有该权限仍然是3.5

**Comment by Yidadaa** [comment]
plus 账号不代表你能用 gpt 4 的 api，两者没有任何关系
