### ISSUE TITLE
可否恢复默认API的余额查看功能

### ISSUE THREAD

**Issue by aabbccgg** [Yidadaa/ChatGPT-Next-Web#463]
新版本中去除了对默认API花费查询的功能，可否改为输入正确的密码后可以显示默认api的花费呢？

**Comment by gaogao1030** [comment]
这个自己本地改一下就可以了 参考 https://github.com/gaogao1030/ChatGPT-Next-Web/commit/61bf7923803143b58ecaab422879a346a9e11453

**Comment by gaogao1030** [comment]
差异化的需求我就都自己本地改一下，优化的需求给作者提个PR ^-^

**Comment by devyujie** [comment]
确实，本来就是显示余额的，现在还要复制一遍api key进去才能看到，不如加个输入密码查看方便。

**Comment by uurun** [comment]
这个我觉得按照目前就挺好，这个主要是隐私问题， 如果是自己一个人用还好，但需要分享给同伴一起用时这个隐藏起来更好。 再说输入一次APIKEY也不是麻烦事儿！

**Comment by realzsy** [comment]
> 这个自己本地改一下就可以了 参考 https://github.com/gaogao1030/ChatGPT-Next-Web/commit/61bf7923803143b58ecaab422879a346a9e11453

根据这个改了，现在只显示本月用了多少？
