### ISSUE TITLE
内置的提示词怎么选？

### ISSUE THREAD

**Issue by lkbgct** [Yidadaa/ChatGPT-Next-Web#464]
在设置页中不能选哪一个提示词？

**Comment by Yidadaa** [comment]
还没做

**Comment by lkbgct** [comment]
哦，好像代码里链接了两个提示词json，不能启用？
https://raw.githubusercontent.com/PlexPt/awesome-chatgpt-prompts-zh/main/prompts-zh.json
https://cdn.jsdelivr.net/gh/PlexPt/awesome-chatgpt-prompts-zh@main/prompts-zh.json

**Comment by Yidadaa** [comment]
那个是在聊天界面通过斜杠触发的

**Comment by lkbgct** [comment]
哦，谢谢！怎么用，/+序号？
