### ISSUE TITLE
Docker 跑在服务器上一直显示"  出错了，稍后重试吧"?

### ISSUE THREAD

**Issue by danzhewuju** [Yidadaa/ChatGPT-Next-Web#467]
Docker 内可以连接外网

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/24364897/229786057-467f30ac-fb59-4107-93c4-bd177aca64af.png">

一直出错了，稍后重试。

<img width="709" alt="image" src="https://user-images.githubusercontent.com/24364897/229786099-54d4d6dd-d398-4d9d-beb8-0302dc9add23.png">

**Comment by realzsy** [comment]
挂了代理？服务器上的代理设置好了吗？

**Comment by Yidadaa** [comment]
请提供服务端 log
