### ISSUE TITLE
可以添加一个重置当前对话，但保留预设置功能吗

### ISSUE THREAD

**Issue by 54681** [Yidadaa/ChatGPT-Next-Web#469]
在完成预设置后， 需要测试修改几轮。但几轮测试后，为了避免上一轮测试的历史信息的影响，需要调整一次附带历史信息数，但在本轮测试中，又需要调整附带历史信息来做测试是否满足要求。所以希望添加一个重置功能，保证测试时不受上一次调整的影响，同时能关联本轮的历史信息。 

顺便感谢一波大佬，聊表心意，不成敬意。

**Comment by Cp0204** [comment]
总结一下，关于便于 Few-show 的一些功能请求：
1. 重置对话记录，但保留预设
2. 支持删除单条记录（有时返回不及预期，需要废弃）
3. 支持自定义单个Chat的历史消息数
4. 支持自定义是否历史记忆（以system发送的历史对话总结）

**Comment by Yidadaa** [comment]
稍后会增加 context 模板功能，允许用户编辑预设模板并命名、设置默认模板，这样后续的自定义角色等能力也会很方便地实现。
