### ISSUE TITLE
`代码框里面的字号比外面的小了好几个号`, 我要想看清代码框里面的字需要把字号调整得特别大

### ISSUE THREAD

**Issue by picklefan** [Yidadaa/ChatGPT-Next-Web#471]
```
代码框里面的字号比外面的小了好几个号
su -
apt update
就这几个字在Github上显示得都比在 ChatGPT-Next-Web上大, 实在夸张
```
 我要想看清代码框里面的字需要把字号调整得特别大,
这个有办法解决吗,
主要是实在是小得太夸张了, 外面是 `14` 号的字, 代码框里面的估计就是 `7` 号, 就算把字体调整成 `18` , 代码框里面的字体也比 `14` 要小还是看不清.
能不能让代码框里面的字体大一点, 起码不要小一半这么夸张

**Comment by picklefan** [comment]
![](https://i.postimg.cc/1txkJjt1/1111conpair.png)
我两边都截图了, 上面是对比图, 明显看得到字号比github还小, 希望能够优化, 或者告诉我应该在哪个地方修改, 谢谢

**Comment by yinm0591** [comment]
有个变通的方式，按“Ctrl+加号”放大浏览器显示比例到110%或125%

**Comment by Yidadaa** [comment]
请使用 ctrl + 来调整浏览器缩放。

**Comment by picklefan** [comment]
> 有个变通的方式，按“Ctrl+加号”放大浏览器显示比例到110%或125%

我说的是相互对大小不是绝对大小, 你能把我说的话看完吗?

**Comment by picklefan** [comment]
> 请使用 ctrl + 来调整浏览器缩放。

我说的是相对大小, 你自己有在用吗? 我很好奇, 或者说PC chrome 上面字体和你们的 safari 不太一样, android chrome 也没有这个问题.
## 我说的是, 代码框的字体比外面的小了50%, 如果你们觉得很合理, 那就很合理

**Comment by picklefan** [comment]
fork 之后改了 `/app/styles/markdown.scss` 把里面的小于14px 的 font size 全部改成了14, `75%` `85%` 之类的百分比全部改成了95-100, 看不懂哪个是哪个乱調的.
现在就很正常, 外面14号, 里面也是14号, 没有缩放
感谢
