### ISSUE TITLE
每次提问都出现error

### ISSUE THREAD

**Issue by xiaomingcom-cs** [Yidadaa/ChatGPT-Next-Web#474]
![image](https://user-images.githubusercontent.com/75123667/229836467-be7de360-a96d-4808-9a58-0ba3748fe991.png)
我的chatgpt还能正常用，说明openai的key还可以使用，但是每次提问结果都如上图，这是什么原因导致的啊

**Comment by Yidadaa** [comment]
你的 api 余额过期了，去官网绑美国信用卡或者换号。
