### ISSUE TITLE
[Feature Request]: 聊天页面，添加一个清空内容按钮。

### ISSUE THREAD

**Issue by mingyue0094** [Yidadaa/ChatGPT-Next-Web#4770]
### Problem Description

比如从面具，进来了。 修改了用那个模型， 想清空内容，在用这个面具。去点要点好几下。还要在点修改模型。 这个模型就当时那个阶段要用其他的模型，设置直接改也不合适。同时，即便设置改了，重新点面具进来，也要点几下。

如果有个清楚按钮，一键清楚对话里面的所有内容。但是保持其他的设置不变

### Solution Description

就好 了

**Comment by SpiralTower** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50526313/d849246e-b268-4845-b7bb-7d42c5535538)
目前可以使用这个功能清除上下文，虽然仍然显示历史，但是之前的聊天不会发送到大模型。
