### ISSUE TITLE
如何修改docker不使用3000端口？

### ISSUE THREAD

**Issue by realzsy** [Yidadaa/ChatGPT-Next-Web#480]
dockerfile里面EXPOSE修改成3001，启动命令docker run -d -p 3001:3001，日志显示监听端口仍然是3000，是哪里没设置对，还需要做什么文件的修改？

**Comment by Yidadaa** [comment]
无法通过 docker 修改端口，请通过 ngnix 反向代理修改端口。

**Comment by realzsy** [comment]
> 无法通过 docker 修改端口，请通过 ngnix 反向代理修改端口。

能具体说一下怎么修改吗？
同时项目文件我全部过了一遍，只看到dockerfile里面有端口，其他文件都没有看到，启动docker是怎么仍然锁定到3000端口的啊，我不是拉的镜像，是git以后重新build的，按理说能改啊。

**Comment by Yidadaa** [comment]
下面是 ChatGPT 给出的回答：
> 如何在 ubuntu 服务器上使用 ngnix 代理 3000 端口到 80
---
在 Ubuntu 服务器上使用 Nginx 代理 3000 端口到 80 端口，可以按照以下步骤进行操作：

1. 安装 Nginx

如果还未安装 Nginx，可以使用以下命令安装：

```bash
sudo apt update
sudo apt install nginx
```

2. 配置 Nginx

首先，备份 Nginx 的默认配置文件：

```bash
sudo mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
```

然后，创建自定义 Nginx 配置文件：

```bash
sudo nano /etc/nginx/sites-available/myapp
```

文件内容可以如下所示：

```
server {
    listen 80;
    server_name example.com;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```

在这里，Nginx 监听本机的 80 端口，并将请求代理到本机的 3000 端口。其中，`server_name` 指定你的域名，如果没有域名可以填写服务器的公共 IP。

3. 启用配置

创建了自定义配置文件后，需要在 `sites-enabled` 文件夹中创建该配置的软链接，以启用该配置文件：

```bash
sudo ln -s /etc/nginx/sites-available/myapp /etc/nginx/sites-enabled/
```

4. 检查配置

为了确保配置无误，可以使用以下命令检查配置是否有语法错误：

```bash
sudo nginx -t
```

如果配置文件没有语法错误，则应该看到以下输出：

```
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

5. 重启 Nginx

完成以上步骤后，可以使用以下命令重启 Nginx：

```bash
sudo service nginx restart
```

现在，所有从代理服务器 `80` 端口到本地 `3000` 端口的请求都会被正确地处理。

**Comment by Kosette** [comment]
如果只是为了修改映射出来的端口，docker使用默认bridge网络时可以任意映射端口， `docker run -d -p <host port>:3000` 中<host port>可以设置为任何宿主机可以正常使用未被占用的端口，比如 `docker run -d -p 3001:3000` 。当然使用反向代理也是一种方法。

**Comment by hqzh** [comment]
https://zhuanlan.zhihu.com/p/626879469
