### ISSUE TITLE
【需求（原来有的效果，新版本无）】-中文回复

### ISSUE THREAD

**Issue by JeazW** [Yidadaa/ChatGPT-Next-Web#486]
原来的时候，随便甩给GPT英文报错，都会使用中文回答，现在默认英文，估计是修改了某处系统预置prompt
可否增加回复语言设置，设置默认回复语言
觉得不妥的话还希望麻烦您指以下这个预置prompt在哪改了，我自己对比一下老版本改回来哈哈😂😂😂

**Comment by realskyrin** [comment]
添加一条前置上下文即可
<img width="709" alt="image" src="https://user-images.githubusercontent.com/16552732/229972156-595b6c83-26eb-4b22-bf65-06e47b1007e1.png">

**Comment by HenMie** [comment]
`前置上下文`增加一条`user`，填写`Respond in Chinese.`即可
