### ISSUE TITLE
如果没有使用 Vercel 部署，如何关闭相关功能避免输出报错

### ISSUE THREAD

**Issue by longhuan1999** [Yidadaa/ChatGPT-Next-Web#487]
# 服务器部署报错

## 来自你的消息:
使用 pm2 和 yarn 部署他人开源的 nextjs 项目到 centos8 服务器上，项目启动命令为 yarn start，端口为 3000，使用 ngnix 做反向代理，环境变量为 OPENAI_API_KEY、CODE 和 PORT 。部署成功后浏览器控制台有报错：
Failed to load resource: the server responded with a status of 404 () /_vercel/insights/script.js:1

## 来自 ChatGPT 的消息:
可能原因是项目中使用了 Vercel 的 insights 功能，但是没有配置正确的环境变量。建议检查以下几点：
1. 确认环境变量 OPENAI_API_KEY、CODE 和 PORT 配置正确，可以在部署命令中加入环境变量的设置，如：
```
pm2 start yarn --name my-nextjs-app -- start -- --port 3000 --env.OPENAI_API_KEY=xxxx --env.CODE=xxxx --env.PORT=3000
```
2. 确认 nginx 配置正确，反向代理的路径应该与 Vercel insights 路径匹配，如：
```
location /_vercel/insights {
    proxy_pass http://localhost:3000/_vercel/insights;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}
```
3. 如果以上都没有问题，可能是 Vercel 配置相关的问题，可以在 Vercel 控制台中检查相关的设置和日志，或者联系项目的作者寻求帮助。

## 来自你的消息:
这个功能有什么用

## 来自 ChatGPT 的消息:
Vercel Insights 是 Vercel 托管服务提供的高级监控和分析工具，可以帮助开发者更好地了解自己的应用在生产环境下的运行状况。通过 Vercel Insights，可以了解应用的性能、请求时间、错误率、访问量等指标，帮助开发者快速定位和解决问题，提高应用的可靠性和性能，提高用户体验。因此，使用 Vercel Insights 可以让项目的运维效率更高，同时也可以帮助更好地提高产品的质量。

## 来自你的消息:
什么是Vercel 托管服务

## 来自 ChatGPT 的消息:
Vercel 是一个针对 Jamstack 应用开发和部署的全球化托管解决方案的公司，提供了一个开发者友好的应用程序部署平台。开发者可以通过 Vercel 托管服务部署应用程序和网站，从而实现高可靠性、跨平台和快速部署的目标，支持多种语言、框架和静态网站生成器。

Vercel 支持自动化构建、测试和部署操作，而且还内置了许多工具和服务，如实时预览、自动缩放、部署预览、自定义域名、HTTPS、自动化 Git 部署等等，为开发者提供了强大的构建和部署生态系统。

值得一提的是，Vercel 还提供了 Next.js、React 和其他前端框架的开发者工具，用于优化开发体验和提高开发效率。这些工具包括 Vercel CLI、Vercel Analytics、Next.js Analytics 等等。

## 来自你的消息:
我没有用Vercel 托管服务，如何关闭这个功能

## 来自 ChatGPT 的消息:
如果您没有使用Vercel 托管服务，那么您的 Next.js 应用程序不会自动启用Vercel Insights。如果在您的应用程序错误信息中看到了来自Vercel Insights的相关信息，那么可能是因为您使用了与Vercel Insights相关的第三方库或服务，例如使用 next-telemetry 这样的库进行性能测量和分析。在这种情况下，您可以尝试禁用该库或服务，以避免在运行时收到Vercel Insights的错误信息。如果您不确定是哪个库或服务导致了问题，您可以进一步检查您的应用程序代码和相关库的文档以获取更多信息。

**Comment by AprilNEA** [comment]
在`Home.tsx`中根据环境判断是否加入 `<Analysis/>`

**Comment by Kosette** [comment]
如果完全不使用analysis，也可以直接在`page.tsx`中把`<Analysis/>`和相关的包的引用去掉。

**Comment by Yidadaa** [comment]
https://github.com/vercel/analytics/issues/1

**Comment by Yidadaa** [comment]
根据环境变量动态加载：https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables#system-environment-variables

**Comment by longhuan1999** [comment]
> 如果完全不使用analysis，也可以直接在`page.tsx`中把`<Analysis/>`和相关的包的引用去掉。

好吧，还是这个办法简单粗暴
