### ISSUE TITLE
能否加一个用户注册和使用额度统计和分配的功能？

### ISSUE THREAD

**Issue by yintaomu** [Yidadaa/ChatGPT-Next-Web#489]
能否加一个用户注册和使用额度统计和分配的功能？或者付费添加，这样我们直接可以拿去创业了

**Comment by yintaomu** [comment]
可以直接v我yintaomu

**Comment by leochen12-rgb** [comment]
违背了项目的宗旨

**Comment by yintaomu** [comment]
> 违背了项目的宗旗

嗯嗯，我理解你的意思，api也是按字数收费的，因为开发能力有限，但是又想利用ChatGPT创业，所以就出此下策

**Comment by liuruidong4** [comment]
你觉得你想拿别人的东西去赚钱还在这里骑脸合适吗
