### ISSUE TITLE
因为国内无法访问api.openai.com建议加一个API自定义变量

### ISSUE THREAD

**Issue by x-dr** [Yidadaa/ChatGPT-Next-Web#49]
因为国内无法访问`api.openai.com`建议加一个API  [route.ts#L17](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/84d73fa1f2ec79eeb6976ba6654fd89c8a466095/app/api/chat-stream/route.ts#L17)自定义变量
```typescript
const BASE_URL: string = process.env.OPENAI_API_BASE_URL ? process.env.OPENAI_API_BASE_URL : "https://api.openai.com/v1/chat/completions";
const res = await fetch(BASE_URL, {
....
```

**Comment by blogwy** [comment]
绑定自己域名后，不翻墙也可以用的

**Comment by Bian-Sh** [comment]
> 绑定自己域名后，不翻墙也可以用的

如果服务器是腾讯云主机，那主机是不是也要魔法上网？
并且，腾讯云主机允许你魔法上网不？

**Comment by ripenedcat** [comment]
麻烦考虑加入Azure OpenAI的支持，除了上述url之外，model name也需要自定义

**Comment by haoliangwu** [comment]
> > 绑定自己域名后，不翻墙也可以用的
> 
> 如果服务器是腾讯云主机，那主机是不是也要魔法上网？ 并且，腾讯云主机允许你魔法上网不？

域名和 vm 是两码事儿，自用的话，够用了。

**Comment by WM-MXBG** [comment]
> 

vecel部署的时候第一次添加的那个解析记录就避免了因在国内会被封的问题了吧，我添加了两次解析，第一次value绑定的是个ip

**Comment by Yidadaa** [comment]
已增加新的环境变量，请查阅文档 https://github.com/Yidadaa/ChatGPT-Next-Web#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F-environment-variables

**Comment by Yidadaa** [comment]
#172
