### ISSUE TITLE
删除对话后增加撤销按钮，来避免误删

### ISSUE THREAD

**Issue by fangyuan99** [Yidadaa/ChatGPT-Next-Web#499]

**Comment by Yidadaa** [comment]
这么小的按钮也会误删吗，如果加上提示框，连续删除就会很繁琐

**Comment by fangyuan99** [comment]
连续删除是不是可以加个多选按钮，然后就可以批量操作

**Comment by Yidadaa** [comment]
所以你在使用的时候确实会误删？还是只是单纯的“你觉得”会误删？

**Comment by fangyuan99** [comment]
误删过两次，也不算太多

**Comment by Yidadaa** [comment]
好的，感谢反馈，感觉这个可能更多的是使用习惯问题，或许我加一个撤销 toast 会更好？删除之后会在底部弹出，用户可以撤销上次删除操作。

**Comment by fangyuan99** [comment]
好主意

**Comment by Cp0204** [comment]
> 误删过两次，也不算太多

你是最新版？最新的版本删除对话已经加了个二次确认对话框了，想不明白咋还容易误删呢。

**Comment by fangyuan99** [comment]
> > 误删过两次，也不算太多
> 
> 你是最新版？最新的版本删除对话已经加了个二次确认对话框了，想不明白咋还容易误删呢。

你看看上面的对话

**Comment by Yidadaa** [comment]
@Cp0204 我在最近的某次提交删掉了二次确认弹窗，因为我自己用起来感觉很蛋疼

**Comment by JeazW** [comment]
连续点击清空对话不要太爽

**Comment by Cp0204** [comment]
> @Cp0204 我在最近的某次提交删掉了二次确认弹窗，因为我自己用起来感觉很蛋疼

😂 那可能确实需要撤回功能，没二次确认前也误删过。
