### ISSUE TITLE
GitHub Action自动同步版本号对不上提示一直更新

### ISSUE THREAD

**Issue by Moxuan6** [Yidadaa/ChatGPT-Next-Web#502]
大佬，今天发现部署的项目要一直更新我去github fork的项目看了一下，工作流执行正常，我又手动给他执行了一次，还是存在更新，我发现自动同步的版本号会和你的项目版本号不一致，他就一直提示有版本更新。

这是后台界面
<img width="1027" alt="3" src="https://user-images.githubusercontent.com/72002407/230079806-5728584a-d1de-417d-87b3-d651cfb691a8.png">

这是你的项目版本号
<img width="1006" alt="2" src="https://user-images.githubusercontent.com/72002407/230079905-7d3f325b-1c62-484d-9e34-d9b5a14e2940.png">

这是我手动执行工作流之后的版本号
<img width="760" alt="4" src="https://user-images.githubusercontent.com/72002407/230080204-d27b80e0-02b2-4c73-aa59-dac9f1daacd3.png">

和后台的版本号完全对应，我试了几次 还是一样结果，我这边同步上支后会赋予一个新的版本号。

希望大佬能优化一下！谢谢！

**Comment by FROGYu** [comment]
也许需要等一会儿,有延迟

**Comment by Yidadaa** [comment]
如果你本地有修改，那么自动合并之后会产生一个全新的 merge commit，所以就会一直提醒版本号不匹配，这是预期内行为，自己二次修改代码就会面临这种问题。

**Comment by Moxuan6** [comment]
> 

大佬，我修改过action。本来之前他一直报错，然后我就把最后那一行false改成true 运行了一次之后成功了，然后又改回来了  现在可以每天六小时执行一次 ，这玩意儿应该不会影响吧

**Comment by Yidadaa** [comment]
看起来应该是有影响的，你本地的提交会一直领先 upstream：

<img width="883" alt="image" src="https://user-images.githubusercontent.com/16968934/230095751-a1e1bc3b-09bf-4589-8aa6-f75e1d5da698.png">

**Comment by Yidadaa** [comment]
不过这个并不会影响使用，因为项目本身也会一直频繁更新，大部分时间都会提示存在更新，我曾经尝试过使用 release tag 来做版本号，但是会对发版流程产生影响，所以这个问题先暂且就这样吧，感觉不是什么大问题。

**Comment by Moxuan6** [comment]
> 不过这个并不会影响使用，因为项目本身也会一直频繁更新，大部分时间都会提示存在更新，我曾经尝试过使用 release tag 来做版本号，但是会对发版流程产生影响，所以这个问题先暂且就这样吧，感觉不是什么大问题。

好的，谢谢了
