### ISSUE TITLE
生成的代码能否增加高亮显示

### ISSUE THREAD

**Issue by Ducknobee** [Yidadaa/ChatGPT-Next-Web#503]
经常问一些代码问题，希望代码能够高亮显示

**Comment by Yidadaa** [comment]
如果 chatgpt 回复的代码没有指定代码的语言，就不会有高亮显示，当然可以开启自动检测代码语言的功能，但是会对性能产生较大的影响，所以还是暂时关闭了。你可以在提问的时候让 chatgpt 返回指定语言的代码，这样就可以保证是有高亮的。

**Comment by Ducknobee** [comment]
> 如果 chatgpt 回复的代码没有指定代码的语言，就不会有高亮显示，当然可以开启自动检测代码语言的功能，但是会对性能产生较大的影响，所以还是暂时关闭了。你可以在提问的时候让 chatgpt 返回指定语言的代码，这样就可以保证是有高亮的。

懂辽，谢谢了
