### ISSUE TITLE
中文字符截断导致乱码问题

### ISSUE THREAD

**Issue by cxgreat2014** [Yidadaa/ChatGPT-Next-Web#507]
app/requests.ts#L157

```js
      while (true) {
        // handle time out, will stop if no response in 10 secs
        const resTimeoutId = setTimeout(() => finish(), TIME_OUT_MS);
        const content = await reader?.read();
        clearTimeout(resTimeoutId);
        const text = decoder.decode(content?.value);
        responseText += text;

        const done = !content || content.done;
        options?.onMessage(responseText, false);

        if (done) {
          break;
        }
      }
```

其中`reader?.read()`有可能只读出一个汉字的部分数据，在之后的decode中出现解码错误，进而导致显示异常。

出错截图：

![image](https://user-images.githubusercontent.com/15062548/230149485-41d27d51-d2d2-40d0-8b0b-d48073f5e8ce.png)

**Comment by Yidadaa** [comment]
这个问题可能不好解决，毕竟我们无法判断一个流中接受到的中文数据是否是完整的。另外，你是用什么部署的，是否启用了反向代理？

**Comment by cxgreat2014** [comment]
这个问题有个比较简单的解决方案，

在while外面做个cache_buffer，
while内在读到数据之后把数据加到cache_buffer中，
然后对cache_buffer进行decode，得到responseText。

即使尾部有不完整字符，在下一次读到数据之后即可补全并正常显示。

**Comment by cxgreat2014** [comment]
vercel部署，f12看了network下面的stream，响应预览解码出来的内容是正常的

**Comment by Yidadaa** [comment]
@cxgreat2014 

buffer 的想法不错，有机会加一下。

**Comment by Sneezry** [comment]
TextDecoder 本身就支持流解码解决字符被截断出现乱码的问题。只需要加个参数就行了。

```ts
const text = decoder.decode(content?.value, { stream: true });
```

> https://github.com/whatwg/encoding/issues/184#issuecomment-527733881
