### ISSUE TITLE
HMR doesn't work?

### ISSUE THREAD

**Issue by doem97** [Yidadaa/ChatGPT-Next-Web#508]
**Describe the bug**
The HMR is not working properly when editing files. 

**To Reproduce**
After exec `yarn dev` the HMR doesn't work properly. Especially, when editing files under `/app/components/*` the local website won't refresh or recompile.

**Expected behavior**
The project re-compile automatically (update only on modified codes) and refresh website lead to new change.

** Deployment
- [ ] Docker
- [ ] Vercel
- [x] Server

**Desktop (please complete the following information):**
 - OS: WSL2
 - Browser: Edge

**Additional Logs**
When I edit package.json or tsconfig.js, the re-compiling of first-level will happen. However, compiling /page won't happen.

**Comment by Yidadaa** [comment]
I cannot reproduce the issue. I have been developing on Windows and have never encountered this problem before.

**Comment by doem97** [comment]
> I cannot reproduce the issue. I have been developing on Windows and have never encountered this problem before.

Received with thanks, bro. Let me try to make a clean build. Maybe due to WSL local development problem.

**Comment by Yidadaa** [comment]
It seems that it is a WSL2 bug: https://github.com/microsoft/WSL/issues/4417

I just switched to WSL 2 and also encountered this issue.

**Comment by Yidadaa** [comment]
Fixed by https://github.com/microsoft/WSL/issues/4417#issuecomment-529272720
