### ISSUE TITLE
大佬，

### ISSUE THREAD

**Issue by xiaozhang959** [Yidadaa/ChatGPT-Next-Web#51]
大佬，请问这个
1.本项目提供有限的权限控制功能，请在环境变量页增加名为 CODE 的环境变量，值为用英文逗号分隔的自定义控制码：
code1,code2,code3
这个控制码是怎么用呢？
我部署完您的项目打开网页后提问它一直显示出错了。
2.另外能不能在页面上加一个让用户自己输入api-key的输入框呢

**Comment by Yidadaa** [comment]
你加入微信群问吧，第二个功能现在已经加了，更新一下代码就有了。

**Comment by ruixing1001** [comment]
帮大佬回答，可以给不同人不同的code，方便回收权限

**Comment by xiaozhang959** [comment]
> 
好的 谢谢您

**Comment by xiaozhang959** [comment]
> 帮大佬回答，可以给不同人不同的code，方便回收权限

好的 谢谢您

**Comment by xiaozhang959** [comment]
> 你加入微信群问吧，第二个功能现在已经加了，更新一下代码就有了。

好的谢谢，但是您的微信群图片似乎失效了，我打开图片链接并没有看到图片

**Comment by 1441853031** [comment]
> 
群
在哪
