### ISSUE TITLE
[Bug] 随机性调整大或小于1后都会出现乱码

### ISSUE THREAD

**Issue by smoey** [Yidadaa/ChatGPT-Next-Web#515]
**描述问题**
设置中调整随机性数值后，得到的回复大概率会胡说八道 乱码成片 这是啥原因？

**如何复现**
调整随机性不等于1

**截图**
![image](https://user-images.githubusercontent.com/4184607/230224528-484fb726-98c0-4d7a-b5d7-9652214350ef.png)
**一些必要的信息**
 - 系统：ios 16
 - 浏览器：safari
 - 版本： v1.93
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
如果你不知道这个参数是干嘛的，就不要乱动。
