### ISSUE TITLE
[Bug] 移动设备中list排版出现错位

### ISSUE THREAD

**Issue by smoey** [Yidadaa/ChatGPT-Next-Web#516]
**描述问题**
当回答的内容出现1.2.3.4等li时 数字会与内容错位

**如何复现**
随便问个问题

**截图**
![image](https://user-images.githubusercontent.com/4184607/230226848-5ad5a45b-ed79-4951-8ff5-8285195ba5e0.png)
**一些必要的信息**
 - 系统：[ios 16]
 - 浏览器： [chrome, safari]
 - 版本： [v1.93]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
未能复现该问题，请给出图中信息的原始 md 文本，使用复制按钮复制出来即可。

**Comment by smoey** [comment]
> 未能复现该问题，请给出图中信息的原始 md 文本，使用复制按钮复制出来即可。

桌面模拟器开发环境确实没法再现这个问题，我的设备是iPhone 13 Pro Max 我的两台设备上都遇到这个问题，是要它回答带步骤的答案就会出现

**Comment by smoey** [comment]
https://user-images.githubusercontent.com/4184607/230245165-81614739-00f9-469d-8398-c7af46f6b310.MOV

**Comment by Yidadaa** [comment]
安卓手机也没有复现，请提供一下截图中消息的 markdown 原文

**Comment by smoey** [comment]
> 安卓手机也没有复现，请提供一下截图中消息的 markdown 原文
我录了个屏，这个排版问题只有在回答时发生，重新打开后恢复正常，如视频中所示

https://user-images.githubusercontent.com/4184607/230251869-302ea10c-4523-4626-8c53-26f51b555079.mp4

**Comment by Yidadaa** [comment]
需要额外的 iOS 设备验证该问题。

**Comment by jtung4** [comment]
我在iphone 14 pro max有遇過同樣問題。但當我離開網頁再重新開啟網頁後又沒有再移位了。

**Comment by Kosette** [comment]
这个问题很久之前就存在，我的workaround是将字体大小调整为16，默认大小14会有问题。你可以试试看。
