### ISSUE TITLE
[Feature] 希望能通过Environment Variables为更多设置项配置默认值

### ISSUE THREAD

**Issue by RogerProSelf** [Yidadaa/ChatGPT-Next-Web#517]
非常好的项目！
小建议，希望能通过Environment Variables为更多设置项配置默认值，比如模型设置默认为gpt-4-32k，历史消息数量默认为24这样，方便使用，谢谢！

**Comment by Yidadaa** [comment]
请问你在什么情况下需要用到 24 的历史消息？开到 24 非常容易碰到 4096 的 token 上限，到时候又会有一堆人来问我为啥。

**Comment by Yidadaa** [comment]
考虑到提供默认配置后会有相当多的人过来询问相关的问题，所以暂时不考虑做此功能，毕竟现在有相当多的人连设置里 temperature 都不知道是干啥的，我已经不想再回答这些问题了。

**Comment by Yidadaa** [comment]
默认 model 可以，不过 gpt4 很贵，慎重考虑
