### ISSUE TITLE
缺个chat页面返回对话列表机制，和退出程序没有分开

### ISSUE THREAD

**Issue by asaketsu** [Yidadaa/ChatGPT-Next-Web#519]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
需要引入 react-router

**Comment by Yidadaa** [comment]
#959
