### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by zsnjuts** [Yidadaa/ChatGPT-Next-Web#52]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/16850617/227786530-e723bb75-e196-44a3-aca6-0ce7b31248c5.png">

原始markdown为：

要将一个矩阵的值转换为颜色并将其可视化，可以使用 `matplotlib` 库中的 `imshow` 函数。在 `imshow` 函数中，矩阵的每个元素会被映射到一个颜色上，这个映射是根据 `cmap` 参数来指定的。

下面是一个示例代码：

```python
import numpy as np
import matplotlib.pyplot as plt

# 生成随机的二维矩阵a
a = np.random.randn(10, 10)

# 使用 imshow 函数可视化二维矩阵a
plt.imshow(a, cmap='Blues')

# 显示图像
plt.colorbar()
plt.show()
```

在上面的代码中，我们首先生成一个 $10\times 10$ 的随机二维矩阵 `a`，然后使用 `imshow` 函数可视化该二维矩阵。函数中的 `cmap` 参数指定了使用的颜色映射，这里我们使用了 `"Blues"` 映射，也就是随着矩阵元素值越大，颜色越深。执行上述代码，输出的结果类似于下图所示：

![二维矩阵可视化](https://i.imgur.com/2G75V7z.png)

在输出的图像中，颜色越深的地方代表的是矩阵中值越大的位置，而颜色越浅的地方代表的是矩阵中值越小的位置。可以看出，这个可视化方式能够清晰地反映矩阵中的数值信息。

**Comment by Yidadaa** [comment]
chatgpt 不能保证返回的图片地址是可用的，和本项目无关
