### ISSUE TITLE
超出引用上下文字符

### ISSUE THREAD

**Issue by asaketsu** [Yidadaa/ChatGPT-Next-Web#520]
{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4972 tokens (972 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

**Comment by Yidadaa** [comment]
设置里 max_tokens 不要开太大。
