### ISSUE TITLE
[Bug] 左侧概览太窄预览文字太少显示不全，无法很好的区分会话

### ISSUE THREAD

**Issue by seven4x** [Yidadaa/ChatGPT-Next-Web#522]
**描述问题**
 左侧只能显示3～4个单词 不能很好的区分会话

**如何复现**
 

**截图**
![image](https://user-images.githubusercontent.com/1982168/230253414-eff3be32-cdcd-4427-bc0c-4bab17d6ff88.png)

**一些必要的信息**
 - 系统：[Mac os]
 - 浏览器： [edge]
 - 版本： [latest]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
侧边栏需要支持拖拽调整大小。
