### ISSUE TITLE
[Feature] How to use ChatGPT 3.5

### ISSUE THREAD

**Issue by AprilCat** [Yidadaa/ChatGPT-Next-Web#523]
I have set gpt-3.5 in setting page. but it still tell me it's chatgpt-3 when I asked. how could I use chatGPT-3.5?

**Comment by Yidadaa** [comment]
ChatGPT 并不知道自己的模型版本，你在官网体验到的版本是 openai 调教过的，请去 openai 官网查看 api key 调用记录来确定 api 版本。

**Comment by AprilCat** [comment]
thanks
