### ISSUE TITLE
版本更新问题 

### ISSUE THREAD

**Issue by QJQA** [Yidadaa/ChatGPT-Next-Web#524]
**描述问题**
按照提示方法删掉repo，重新fork并部署，依然出现版本不能自动更新的问题。

**如何复现**
没做什么操作。

**一些必要的信息**
 - 系统：[ macos 12.6.4/ ios 16.3.1]
 - 浏览器： [mac用的 chrome，iPhone用的 safari]
 - 版本： [a474303]
 - 部署方式：[ verce部署]

**Comment by Yidadaa** [comment]
请检查 repo 的 github actions 运行记录是否有报错，并提供对应截图。

**Comment by QJQA** [comment]
![WX20230406-105602@2x](https://user-images.githubusercontent.com/126222235/230261172-db12a4c2-c1fd-49c4-9dc5-b9df424f4ed5.png)

![WX20230406-105618@2x](https://user-images.githubusercontent.com/126222235/230261216-78f9d4a7-9000-4b54-a9d8-9247058ae8de.png)

![WX20230406-105629@2x](https://user-images.githubusercontent.com/126222235/230261240-e3dab323-911a-4855-a0cf-ca906d0a108c.png)

**Comment by yorunning** [comment]
> ![WX20230406-105602@2x](https://user-images.githubusercontent.com/126222235/230261172-db12a4c2-c1fd-49c4-9dc5-b9df424f4ed5.png)
> 
> ![WX20230406-105618@2x](https://user-images.githubusercontent.com/126222235/230261216-78f9d4a7-9000-4b54-a9d8-9247058ae8de.png)
> 
> ![WX20230406-105629@2x](https://user-images.githubusercontent.com/126222235/230261240-e3dab323-911a-4855-a0cf-ca906d0a108c.png)

**仓库不是fork仓库，跳过同步工作流执行**

**Comment by QJQA** [comment]
我真的没有其他的额外操作（是纯小白），就是按照作者在页面提示的那4个步骤操作的，不知道为啥会这样...

**Comment by Yidadaa** [comment]
点击本项目右上角的 fork 按钮重新 fork 一份并重新用 vercel 选择部署，不要改名，不要做任何修改。

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/16968934/230265168-ff367fb7-c872-4096-8920-d5f47cedf4a5.png">
