### ISSUE TITLE
问题太长设置max_tokens=5000也没用

### ISSUE THREAD

**Issue by pxsgdsb** [Yidadaa/ChatGPT-Next-Web#527]
**描述问题**
错误：
This model's maximum context length is 4097 tokens. However, you requested 4962 tokens (62 in the messages, 4900 in the completion). Please reduce the length of the messages or completion.

**截图**
![image](https://user-images.githubusercontent.com/52494730/230264854-9ae0b8fc-f5a3-496f-a751-5db181965fe3.png)

**Comment by Yidadaa** [comment]
gpt3.5 的限制，不要发这么长。
