### ISSUE TITLE
[Feature] 总token超过限制则自动缩减携带历史消息数 Automatically reduce the number of historical messages carried when the total token exceeds the limit

### ISSUE THREAD

**Issue by HenMie** [Yidadaa/ChatGPT-Next-Web#528]
**这个功能与现有的问题有关吗？**
附带历史消息数设置较大，或前文回复内容较长时，很容易超出限制。我将其设置为3，并不算大，但仍然碰到了几次因前文回复过长导致总token超额的情况。
When the number of accompanying historical messages is set to a large value or the previous reply content is long, it is easy to exceed the limit. I set it to 3, which is not too large, but I still encountered several instances where the total token exceeded due to the previous reply being too long.

**你想要什么功能或者有什么建议？**
发送请求前，计算总token数，如果超过了限制，则自动缩减携带历史消息数。
Before sending the request, calculate the total number of tokens. If the limit is exceeded, the number of historical messages carried will be automatically reduced.

**其他信息**
该功能生效时，也许应该给予用户“token超过限制，已自动缩减携带历史消息数”的提示。
When this function takes effect, it may be appropriate to give the user a prompt stating that the token has exceeded the limit and the number of historical messages carried has been automatically reduced.

**Comment by lixibi** [comment]
同样情况。

**Comment by Yidadaa** [comment]
请附上你们聊天的截图，看看到底有多长。

**Comment by Yidadaa** [comment]
计算 token 是一个非常消耗算力的操作，并不是简单地统计字符长度，[tiktoken](https://github.com/openai/tiktoken) 这个库做了很多工作，在浏览器里实现这个操作比较困难，不过我们应该可以拟合出来一个大概的函数来做这件事。

**Comment by Yidadaa** [comment]
不过即便如此，该超限还是超限，这是 gpt3.5 的限制。

**Comment by devyujie** [comment]
我也发现了，好像很容易触发4096 token限制，例如这个对话，一共就20条信息，我设置的携带历史消息数是10。（图片有点长）
<img width="947" alt="20230406124904" src="https://user-images.githubusercontent.com/48620527/230275366-81c800b8-8e09-485d-8485-7afd981cfafe.png">

**Comment by Yidadaa** [comment]
这还不长？你把聊天记录导出来，放到 word 里统计一下字数。

**Comment by Yidadaa** [comment]
4000 多 token，也就 2000 多汉字

**Comment by asaketsu** [comment]
做个自动发送验证并中断，优化满足当前最近对话
别让触发4096

**Comment by devyujie** [comment]
> 4000 多 token，也就 2000 多汉字

看了下，最近10条是1800多个汉字，那可能是我携带数开大了。但是过了一会，我再发，就又可以回复了。
![image](https://user-images.githubusercontent.com/48620527/230277862-5c21d81f-a26b-4932-9a31-b02a1923d3cf.png)

**Comment by Scenx** [comment]
我经常写大文档，特别容易撞墙。。。

**Comment by Yidadaa** [comment]
> 做个自动发送验证并中断，优化满足当前最近对话 别让触发4096

@asaketsu 哪这么简单，你上来就粘贴个两千字的文档，神仙来了也会超。

**Comment by AreChen** [comment]
1.7版本的时候我直接发发1975字问题也不会超阿
[链接](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/315)
