### ISSUE TITLE
[Feature Request] 能否增加claude模型的OpenAI格式

### ISSUE THREAD

**Issue by wjh191** [Yidadaa/ChatGPT-Next-Web#5299]
### 🥰 需求描述

这个功能主要是给第三方中转用的，旧版本可以用自定义模型解决这个问题，但是自从更新了支持官方claude的功能后就无法用这个方法了。

### 🧐 解决方案

增加claude模型的OpenAI格式

**Comment by QAbot-zh** [comment]
已经支持自定义格式了，参考：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5001
