### ISSUE TITLE
在docker部署的中项目一直提示有更新是这么回事，已经重新拉取最新镜像了

### ISSUE THREAD

**Issue by PWMFI** [Yidadaa/ChatGPT-Next-Web#530]

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E4%B8%BA%E4%BB%80%E4%B9%88-docker-%E9%83%A8%E7%BD%B2%E7%89%88%E6%9C%AC%E4%B8%80%E7%9B%B4%E6%8F%90%E7%A4%BA%E6%9B%B4%E6%96%B0
