### ISSUE TITLE
[Feature] 希望拖拽的图标换个高画质的

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#537]
**这个功能与现有的问题有关吗？**
/ 

**你想要什么功能或者有什么建议？**
这个小手，可以换个 SVG 之类的，哈哈
![1](https://user-images.githubusercontent.com/48620527/230356013-990a0d64-af9e-4444-afe1-2b8ce5883dfa.gif)

**有没有可以参考的同类竞品？**
/

**其他信息**
/

**Comment by devyujie** [comment]
还有，鼠标滑到这里时，觉得应该改为正常鼠标样式
![image](https://user-images.githubusercontent.com/48620527/230355686-e0cc7e9f-70f0-4f84-a11a-b81f7d01656d.png)

**Comment by Yidadaa** [comment]
1. 拖拽图标用的是你操作系统的图标，不会在此处使用自定义图标
2. 关闭按钮的样式等待 #583 合入。
