### ISSUE TITLE
代码块右上角，复制按钮前能否显示代码语言？

### ISSUE THREAD

**Issue by fancyui** [Yidadaa/ChatGPT-Next-Web#538]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
代码块右上角，复制按钮前能否显示代码语言？

**有没有可以参考的同类竞品？**
![ChatGPT-Web](https://user-images.githubusercontent.com/34978431/230279774-288e5327-d71c-4067-8609-9c2d84133fb5.png)

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
没看出来这个标识有什么用，里面啥语言不是一眼就看出来了？

**Comment by fancyui** [comment]
有些语言用的少，不熟悉，过段时间再翻出来看要看一会才知道。算是对编程初学者友好吧。
