### ISSUE TITLE
IOS的默认浏览器，顶部不会自动适应，有白边，影响美观，如图

### ISSUE THREAD

**Issue by ruixing1001** [Yidadaa/ChatGPT-Next-Web#54]
![image](https://user-images.githubusercontent.com/128834242/227791949-f83ac1eb-61df-4d47-b00f-bf1a77899aee.png)
![image](https://user-images.githubusercontent.com/128834242/227791966-a1d28043-c0b7-4ca2-8628-e6098130f039.png)

**Comment by AprilNEA** [comment]
尝试修复 #64
