### ISSUE TITLE
[Feature] 建议增加超时时间设定

### ISSUE THREAD

**Issue by happylenx** [Yidadaa/ChatGPT-Next-Web#541]
看到有人也提交了类似的问题，但是已经关闭了。
例如：
30s的默认超时看起来太短了
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/299
经常出现“The user aborted a request”错误
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/160

我在使用过程中，经常碰到“出错了，稍后重试吧”的错误，修改超时时间到60s后，出现这种问题已经少很多了。可能原因还是超时时间过短导致的。这个应该部署的服务器和openai服务器之间的网络情况、openai服务器负载情况都可能会产生响应时间较长的问题。

建议增加超时设定，允许根据自己的需要设定超时时间，增强本系统的可用性。
谢谢！

**Comment by Yidadaa** [comment]
30s 的时间对大多数用户来说都已经非常长了，你部署的网站有打字机效果吗？

**Comment by hugoyue** [comment]
> 看到有人也提交了类似的问题，但是已经关闭了。 例如： 30s的默认超时看起来太短了 #299 经常出现“The user aborted a request”错误 #160
> 
> 我在使用过程中，经常碰到“出错了，稍后重试吧”的错误，修改超时时间到60s后，出现这种问题已经少很多了。可能原因还是超时时间过短导致的。这个应该部署的服务器和openai服务器之间的网络情况、openai服务器负载情况都可能会产生响应时间较长的问题。
> 
> 建议增加超时设定，允许根据自己的需要设定超时时间，增强本系统的可用性。 谢谢！

可以考虑本地部署挂代理或者使用代理接口地址部署，vercel 自家的CDN今天看了一下，快爆炸了。

**Comment by JMD110** [comment]
MR: [https://github.com/Yidadaa/ChatGPT-Next-Web/pull/550](#550 ) @Yidadaa @happylenx 可以看看

**Comment by happylenx** [comment]
> 30s 的时间对大多数用户来说都已经非常长了，你部署的网站有打字机效果吗？

没有打字机效果，是一直等待，一次显示全部结果。
我没有使用docker部署，是git clone 源码后，yarn build再手动启动运行的。
请问怎么出打字机效果啊？

**Comment by happylenx** [comment]
> > 看到有人也提交了类似的问题，但是已经关闭了。 例如： 30s的默认超时看起来太短了 #299 经常出现“The user aborted a request”错误 #160
> > 我在使用过程中，经常碰到“出错了，稍后重试吧”的错误，修改超时时间到60s后，出现这种问题已经少很多了。可能原因还是超时时间过短导致的。这个应该部署的服务器和openai服务器之间的网络情况、openai服务器负载情况都可能会产生响应时间较长的问题。
> > 建议增加超时设定，允许根据自己的需要设定超时时间，增强本系统的可用性。 谢谢！
> 
> 可以考虑本地部署挂代理或者使用代理接口地址部署，vercel 自家的CDN今天看了一下，快爆炸了。

我就是部署在自己租的服务器上的，我怀疑有些问题openai响应时间比较长才会超时。

**Comment by Yidadaa** [comment]
修改你的 ngnix 配置：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md

**Comment by happylenx** [comment]
> 修改你的 ngnix 配置：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md

非常感谢！确实是因为用了nginx默认设置进行反向代理，按照上面的方法修改配置后，有效果了。

**Comment by galenzhao** [comment]
> MR: [https://github.com/Yidadaa/ChatGPT-Next-Web/pull/550](#550) @Yidadaa @happylenx 可以看看

/api/chat-stream
最大超时还是60s，
这个是在哪里配置的？我没找到
