### ISSUE TITLE
[Bug] docker获取不到镜像

### ISSUE THREAD

**Issue by F6JO** [Yidadaa/ChatGPT-Next-Web#546]
[root@vultr ~]# docker pull yidadaa/chatgpt-next-web
Using default tag: latest
Trying to pull repository docker.io/yidadaa/chatgpt-next-web ...
manifest for docker.io/yidadaa/chatgpt-next-web:latest not found

[root@vultr ~]# docker pull yidadaa/chatgpt-next-web:latest
Trying to pull repository docker.io/yidadaa/chatgpt-next-web ...
manifest for docker.io/yidadaa/chatgpt-next-web:latest not found

[root@vultr ~]# docker pull yidadaa/chatgpt-next-web:v1.9.3
Trying to pull repository docker.io/yidadaa/chatgpt-next-web ...
manifest for docker.io/yidadaa/chatgpt-next-web:v1.9.3 not found

[root@vultr ~]# docker pull yidadaa/chatgpt-next-web:1.7.2
Trying to pull repository docker.io/yidadaa/chatgpt-next-web ...
manifest for docker.io/yidadaa/chatgpt-next-web:1.7.2 not found

**Comment by Kosette** [comment]
什么平台架构? arm? 这个镜像仓库不支持 amd64 以外的系统架构，可以自行编译。

**Comment by F6JO** [comment]
是linux amd64，我换了好几个服务器都是not found。
我也用arm试过，架构不支持会报错：no matching manifest for linux/arm64/v8 in the manifest list entries。

**Comment by Kosette** [comment]
我刚刚测试了一下可以正常拉取镜像，设置过docker的镜像源吗？或者能成功拉取其他镜像吗？

**Comment by F6JO** [comment]
没有设置过，docker是新装的。国内国外的服务器都试了。很奇怪

**Comment by shishirui** [comment]
我也拉不到镜像，而且我去 dockerhub 看了，上面没有镜像，显示404
https://hub.docker.com/yidadaa/chatgpt-next-web

**Comment by Yidadaa** [comment]
确实有点离谱，我看看为啥 404 了

**Comment by Yidadaa** [comment]
应该是这个链接：https://hub.docker.com/r/yidadaa/chatgpt-next-web/tags

**Comment by F6JO** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/64877810/230305997-d759ea7f-46db-4902-aa1c-54e3497fd9bf.png">
离谱

**Comment by Kosette** [comment]
确实非常奇怪啊，换一个镜像源试试看，https://mirrors.ustc.edu.cn/help/docker-ce.html 这是科大的镜像源。

**Comment by hugoyue** [comment]
arm 架构只有1.7.2是有相应的镜像
```
docker pull yidadaa/chatgpt-next-web:1.7.2
```

**Comment by shishirui** [comment]
> <img alt="image" width="938" src="https://user-images.githubusercontent.com/64877810/230305997-d759ea7f-46db-4902-aa1c-54e3497fd9bf.png">
> 
> search可以，pull不行

你是什么版本的 docker?

**Comment by Yidadaa** [comment]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/16968934/230311248-59d44344-0c68-480f-8217-aa63fa4b32c9.png">

刚刚试了下没问题，建议你们自己看下 docker 版本，或者换个 docker 镜像源重试。

**Comment by shishirui** [comment]
我用 docker 17 不行，换了一台服务器，上面的是 docker 20 就可以了

**Comment by broxiang** [comment]
确实是docker版本的问题

**Comment by Aiurvie** [comment]
Docker 版本有影响，Centos 默认 Yum 源的 Docker 版本过旧。
