### ISSUE TITLE
[Feature]  建议能够允许用户配置 API Endpoint

### ISSUE THREAD

**Issue by shishirui** [Yidadaa/ChatGPT-Next-Web#548]
我们目前在用一家由第三方公司提供的加速后的 ChatGPT API，对方提供的是加速后的 Endpoint （类似 CDN 加速），所以希望能够支持允许用户配置 API Endpoint 的功能。

**Comment by Kosette** [comment]
按照文档描述，设置环境变量`BASE_URL`可以自定义 api 接口地址，可以尝试。

**Comment by shishirui** [comment]
确实可以，谢谢
