### ISSUE TITLE
[Feature Request] 自动生成标题功能支持自定义某个模型

### ISSUE THREAD

**Issue by Silypie** [Yidadaa/ChatGPT-Next-Web#5484]
### 🥰 需求描述

希望自动生成标题功能支持自定义某个模型，因为用比较贵的模型的时候不像浪费模型的token来生成标题

### 🧐 解决方案

生成标题功能支持自定义某个模型

**Comment by QAbot-zh** [comment]
这项设置其实也是用来生成标题的

![image](https://github.com/user-attachments/assets/40465fee-a589-450d-8f5f-f56bc51faffd)

![image](https://github.com/user-attachments/assets/25d245c1-01a4-4ffa-99ce-03e4af8a381b)

![image](https://github.com/user-attachments/assets/d6a6533b-c0f5-4f01-8d69-a3bd2cbd3463)
