### ISSUE TITLE
安卓手机浏览器打开页面无法复制

### ISSUE THREAD

**Issue by moshuixins** [Yidadaa/ChatGPT-Next-Web#55]
机型:红米k50pro
问题:用夸克和手机自带浏览器访问，复制功能无法使用，弹出提示“复制失败，请给予粘贴板权限。”，但是我已反复确认权限已给，将网页打包成webapp也是这个问题。

**Comment by ruixing1001** [comment]
![image](https://user-images.githubusercontent.com/128834242/227830374-9d4f93f8-00e3-4c34-b2f1-13f6e4b746e8.jpeg)
同是红米，安卓没问题，授权以后可以复制
