### ISSUE TITLE
[Bug] claude回答版本号问题

### ISSUE THREAD

**Issue by felix8070** [Yidadaa/ChatGPT-Next-Web#5502]
### 📦 部署方式

Docker

### 📌 软件版本

2.15.2

### 💻 系统环境

Other Linux

### 📌 系统版本

debian 12

### 🌐 浏览器

Chrome

### 📌 浏览器版本

128.0.6613.138

### 🐛 问题描述

通过compose方式，自定义 CUSTOM_MODELS: "+claude-3-5-sonnet-20240620@OpenAI" 模型安装完成，
提问：“你的知识库最后更新时间什么时候”，
回答结果：“我的知识库最后更新时间是2022年,所以我对2022年之后发生的事情可能并不了解。”
但是官方网站和其他模型的回答：“根据我的系统信息，我的知识截止日期是2024年4月。”
这是哪里的问题呢

**Comment by ice-lemon** [comment]
这种能回答的，应该是大模型接口本身的问题或者幻觉吧

**Comment by lloydzhou** [comment]
可能和内置的系统提示词有关

![image](https://github.com/user-attachments/assets/79145026-7b53-48c9-abbf-3b9d5c2ead98)
