### ISSUE TITLE
{   "error": {     "message": "This model's maximum context length is 4097 tokens. However, you requested 4113 tokens (17 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.",     "type": "invalid_request_error",     "param": "messages",     "code": "context_length_exceeded"   } }

### ISSUE THREAD

**Issue by PWMFI** [Yidadaa/ChatGPT-Next-Web#551]
这个问题该怎么解决，重启了项目还是不行

**Comment by Yidadaa** [comment]
history message count 设置了多大？

**Comment by PWMFI** [comment]
4096

Sent from Proton Mail for iOS

2023 年 4 月 6 日星期四 16:11, Yifei Zhang ***@***.***> 来信：

**Comment by yinm0591** [comment]
@PWMFI  使用yidadaa/chatgpt-next-web:v1.9.2镜像，先回退到上一个版本

**Comment by PWMFI** [comment]
说错了 1000

Sent from Proton Mail for iOS

2023 年 4 月 6 日星期四 16:11, Yifei Zhang ***@***.***> 来信：

**Comment by Yidadaa** [comment]
我是指历史消息携带数，你设置了多大：

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/16968934/230316875-0a74122a-61b2-4942-aa53-92667c86e2c8.png">

**Comment by PWMFI** [comment]
4

**Comment by PWMFI** [comment]
有什么解决方法吗

**Comment by yinm0591** [comment]
设置里把max_tokens改小点(<=4087)，就正常了。

**Comment by xiaozhi656** [comment]
我设置的max_tokens是2048不管用呀
