### ISSUE TITLE
[Bug] Docker 1.9.3版本有错误

### ISSUE THREAD

**Issue by yinm0591** [Yidadaa/ChatGPT-Next-Web#552]
我使用Docker版本yidadaa/chatgpt-next-web，原来的1.9.2版本可以正常使用，升级到1.9.3(b1e26a5)后，chat任何内容都会报错：
{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4106 tokens (10 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

回退到1.9.2就恢复正常了。

我部署的yaml文件如下===============
version: "3.9"
services:
  gpt:
    image: yidadaa/chatgpt-next-web:latest
    container_name: gpt
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=sk-xxx
      - CODE=
    ports:
      - 127.0.0.1:3000:3000
    logging:
      driver: "journald"

**Comment by Yidadaa** [comment]
麻烦提供一下网页控制台 network 选项卡，chat-stream 请求的 payload 截图，如下图：


<img width="1003" alt="image" src="https://user-images.githubusercontent.com/16968934/230316660-d330384f-1163-4bcc-9af0-326d8884f662.png">

**Comment by yinm0591** [comment]
我找到原因了，设置里把max_tokens改成<=4087就正常了。

我原来设置成4096，在上一个版本正常，这个版本报错，改成4000后就正常了。
