### ISSUE TITLE
[Bug] 对话较长并且打开预览气泡时，输入框卡顿

### ISSUE THREAD

**Issue by nullcache** [Yidadaa/ChatGPT-Next-Web#553]
**描述问题**
对话较长时，打开预览气泡的情况下，输入框极其卡顿

**如何复现**
对话较长时，打开预览气泡的情况下

**截图**
![Apr-06-2023 16-16-14.gif](https://vip2.loli.io/2023/04/06/ciVTZhsuB4aKqey.gif)

**一些必要的信息**
 - 系统：macos13
 - 浏览器： chrome
 - 版本： 最新
 - 部署方式：vercel
 
 **建议**
 是否应该使用 useDeferredValue ？

**Comment by Yidadaa** [comment]
请提供设置界面的版本号。

**Comment by Yidadaa** [comment]
如果关闭气泡预览，是否还会卡顿

**Comment by nullcache** [comment]
我不是fork的，所以版本号没有参考意义，当前4f25db0，发现1d2a953，对话7w字符，关闭了气泡还会卡顿
两天前创建的，然而我发现直接点击首页的deploy on vercel创建的项目，version和dependencies大有不同，也许我应该fork后重新部署，再重新测试，我现在关闭这个issue，如果复现了我会打开

**Comment by Yidadaa** [comment]
昨天的版本优化了性能，建议 fork 后保持更新。

**Comment by apm29** [comment]
我也遇到了同样的问题，字符数99897，版本86fb361，之前的几个版本也是这样的，
系统版本：macOS 10.15.7
浏览器：Edge 112.0.1722.39 
部署方式： Vercel

**Comment by Yidadaa** [comment]
@apm29 性能优化不好做，昨天尝试上了一版，抖动比较厉害，十分影响体验，对话多了就新开一版吧，之后有时间做分页加载
