### ISSUE TITLE
【Question】这个前情提要是如何实现的？

### ISSUE THREAD

**Issue by ltinerary** [Yidadaa/ChatGPT-Next-Web#556]
![image](https://user-images.githubusercontent.com/79144923/230327460-6eba8829-dd08-4996-8a22-f263952ca986.png)

我在查看[app.ts](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/store/app.ts)文件中，找到了相关插入的代码，但是没有发现相关生成总结的逻辑（或许是有点菜）

所以想请教下这个是如何实现的？谢谢

**Comment by Yidadaa** [comment]
cn.ts 中的 Prompt

**Comment by ltinerary** [comment]
> cn.ts 中的 Prompt

好谢谢~所以我可以理解为这个总结还是chatgpt根据`Summarize`返回的？然后将返回值作为`role为system`的输入值。
![image](https://user-images.githubusercontent.com/79144923/230519913-4beb71de-9525-4ff4-8bc5-c085549b3395.png)

**Comment by Yidadaa** [comment]
是的。
