### ISSUE TITLE
[Feature] 可否考虑增加openapi？

### ISSUE THREAD

**Issue by paulzhn** [Yidadaa/ChatGPT-Next-Web#560]
考虑到大陆地区访问openai的情况，可否将在项目里增加一个openapi，其作用就是直接转发req和resp到openai的api，这样可以方便接其他的应用（比如https://github.com/marcolardera/chatgpt-cli）

**Comment by PaiJi** [comment]
你要找的是 [[BASE_URL](url)](https://github.com/Yidadaa/ChatGPT-Next-Web#base_url-optional) 么？

**Comment by paulzhn** [comment]
看起来并不是，我的意思是在这个项目中开放一个接口，它的req和resp和openai的api完全相同。可以理解成一个proxy。

> 你要找的是 [BASE_URL](https://github.com/Yidadaa/ChatGPT-Next-Web#base_url-optional) 么？

**Comment by Yidadaa** [comment]
不要使用来路不明的 proxy，如果实在需要，建议使用以下项目自己搭建：
https://github.com/fuergaosi233/openai-proxy
https://github.com/diemus/azure-openai-proxy
https://github.com/easychen/openai-api-proxy

**Comment by paulzhn** [comment]
> 不要使用来路不明的 proxy，如果实在需要，建议使用以下项目自己搭建： https://github.com/fuergaosi233/openai-proxy https://github.com/diemus/azure-openai-proxy https://github.com/easychen/openai-api-proxy

Hello作者，我的意思就是能否在本项目中提供类似的功能。我理解实现起来应该不是非常困难，只需要再开一个接口转发一下到openai的openai接口那里就可。
