### ISSUE TITLE
[Feature] 修改一下停止回答的方式

### ISSUE THREAD

**Issue by fangyuan99** [Yidadaa/ChatGPT-Next-Web#561]
在gpt回答的时候，如果在看到一部分回答内容的时候想停止本次回答，会遇到一个问题——停止按钮的位置在不断变化，导致很难点到，必须等到回答达到一定长度换行之后才容易点到。

**Comment by strivingwang** [comment]
停止按钮太小，点不上，我点了好像没反应

**Comment by Yidadaa** [comment]
那就耐心等待一会，它出来也就几秒钟。

**Comment by TCOTC** [comment]
@Yidadaa 真的点不到停止按钮，有种平白多花了钱的感觉。能否在下面这里加个停止按钮？或者别的什么方式

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/78434827/ca3fa612-4488-4b04-8f68-2a02547a099e)
