### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kissyouhunter** [Yidadaa/ChatGPT-Next-Web#568]
**描述问题**
chrome.edge,firefox,safari,四个浏览器里只有使用firefox的时候，ai回答的内容一次性全部回复，如果内容比较长的话，有时间会一下回复很长一段文字，再逐个文字显示出来。其他三个浏览器ai的回复一直是逐个文字显示。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器：chrome.edge,firefox,safari
 - 版本：1.9.3
 - 部署方式：docker

**Comment by Yidadaa** [comment]
不会针对特定浏览器的偶现 bug 做处理，请使用 chrome。
