### ISSUE TITLE
[优化] web 输入框高度不够

### ISSUE THREAD

**Issue by chenwynn** [Yidadaa/ChatGPT-Next-Web#569]
**描述问题**
web 打开，输入框的高度目前默认就2行，还不能调整，遇到要输入很多文字的时候，体验不好，会有输入文字，光标闪跳，看不到正在输入的文字的情况

**如何复现**
web浏览模式

**截图**

**一些必要的信息**
 - 系统：[macos]
 - 浏览器： [chrome,]
 - 版本： [bf8d136]
 - 部署方式：[ vercel]

**Comment by asaketsu** [comment]
![IMG_20230406_135157](https://user-images.githubusercontent.com/422292/230398347-ab6ffc02-22ca-4647-8cd1-e4a890fe32bc.jpg)

我这样都忍了
又不是不能用

**Comment by Yidadaa** [comment]
#318 等待此 pr 合入。

**Comment by Yidadaa** [comment]
#617
