### ISSUE TITLE
用户设置单次回复限制的功能出错

### ISSUE THREAD

**Issue by AndyZarks** [Yidadaa/ChatGPT-Next-Web#575]
**Describe the bug**
设置页面的max_tokens值会影响发送给chatgpt的completion数量，导致超出4097tokens上限报错

**To Reproduce**
1. 开启设置，设置单次回复限制至5000
2. 开始任意新的对话
3. chatgpt直接报错超出上限:
{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 5009 tokens (9 in the messages, 5000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
4. max_tokens 设置成N (N>4086)，gpt的报错中都会告诉你 N in the completion

**Expected behavior**
最大token上限的参数不是对话中发送的completion

**Screenshots**
![image](https://user-images.githubusercontent.com/13665540/230450092-4540d475-1ea9-4f65-8f47-9085af0c366c.png)

![image](https://user-images.githubusercontent.com/13665540/230450011-aaad54ef-1e27-4271-9bc3-f25596ad55a9.png)

**Deployment**
- [ ] Docker
- [✅] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [112.0.5615.50]

**Additional Logs**

**Comment by asaketsu** [comment]
关了吧，爬关闭的帖子

**Comment by Yidadaa** [comment]
这是 openai 的限制，和本项目无关。

**Comment by AndyZarks** [comment]
> 关了吧，爬关闭的帖子

Sorry，我去爬了下关闭的帖，但并不能解决我的问题。
在携带历史消息数量为0的情况下，max_tokens设置为4086你可以发送一个汉字，设置为4085你最多就能发送两个汉字...
如果按照正常携带数个历史消息的情况下这个值还得更低，max_tokens减少多少用户才被允许多发送几个字符。
根据我的使用经验，这个参数在以前的版本完全不是这么工作的，往常我都是直接设置在gpt3.5的4097个token上限。
请问是我对功能说明“单次交互所用的最大token数/Maximum length of input tokens and generated tokens”理解有误，还是这个功能本来就应是如此工作的？

**Comment by AndyZarks** [comment]
> > 关了吧，爬关闭的帖子
> 
> Sorry，我去爬了下关闭的帖，但并不能解决我的问题。
> 在携带历史消息数量为0的情况下，max_tokens设置为4086你可以发送一个汉字，设置为4085你最多就能发送两个汉字...
> 如果按照正常携带数个历史消息的情况下这个值还得更低，max_tokens减少多少用户才被允许多发送几个字符。
> 根据我的使用经验，这个参数在以前的版本完全不是这么工作的，往常我都是直接设置在gpt3.5的4097个token上限。
> 请问是我对功能说明“单次交互所用的最大token数/Maximum length of input tokens and generated tokens”理解有误，还是这个功能本来就应是如此工作的？

目前回退到1.9.2版本才没有问题

**Comment by AndyZarks** [comment]
> 这是 openai 的限制，和本项目无关。

不好意思回复一下您closed的帖，1.9.2版本是正常工作的，1.9.3开始才有的这个问题，具体疑问在回复中我有扩充

**Comment by Yidadaa** [comment]
@AndyZarks 这是因为之前的版本，设置参数有 bug，用户关于模型的自定义数据完全没有被发送到 openai 服务器上，所以你才会觉得没有问题。

**Comment by AndyZarks** [comment]
> @AndyZarks 这是因为之前的版本，设置参数有 bug，用户关于模型的自定义数据完全没有被发送到 openai 服务器上，所以你才会觉得没有问题。

👌
