### ISSUE TITLE
[Feature] Is it possible for each Access Code to limit the number of simultaneous online users?

### ISSUE THREAD

**Issue by LazzaroneS** [Yidadaa/ChatGPT-Next-Web#581]
**Is your feature request related to a problem? Please describe.**
Is it possible for each Access Code to limit the number of simultaneous online users?

**Describe the solution you'd like**
This way we don't have to worry about the Access code being overly distributed when we share it.

**Comment by asaketsu** [comment]
User login and accounts both are not in the plan.
Control by the numbers of your public access Code.

**Comment by LazzaroneS** [comment]
Thanks for letting us get involved in such a cool project.
