### ISSUE TITLE
[Feature] 客户端用 Tauri 慎重

### ISSUE THREAD

**Issue by llccing** [Yidadaa/ChatGPT-Next-Web#582]
**这个功能与现有的问题有关吗？**
如果做客户端版本，可以综合考虑一下是否使用 Tauri，或者可以提前对于可能出现的坑做些准备。我喜欢的一个大佬的看法（https://twitter.com/yetone/status/1643660861805043714）

**你想要什么功能或者有什么建议？**
Fluttter/Electron/Tauri，可以横向比较一下。我没做过相关的，只是提醒一下

**Comment by Yidadaa** [comment]
1. 这个项目是个前端项目，所以不可能使用 flutter 做客户端
2. electron 会使得客户端打包体积巨大
3. tauri 可以保证小体积，但是兼容性比 electron 差很多，而且目前了解到的信息是不兼容 nextjs 的实验性功能

打包客户端这个需求会比较靠后。

**Comment by asaketsu** [comment]
https://juejin.cn/post/7218117377052377143

**Comment by Yidadaa** [comment]
@asaketsu 没有类型检查，我现在都不敢写代码。
