### ISSUE TITLE
发送消息返回错误

### ISSUE THREAD

**Issue by fylm** [Yidadaa/ChatGPT-Next-Web#584]
**描述问题**
对话报错
{
  "cause": {
    "errno": -3001,
    "code": "EAI_AGAIN",
    "syscall": "getaddrinfo",
    "hostname": "api.openai.com"
  }
}
**如何复现**
发送消息

**截图**
![image](https://user-images.githubusercontent.com/48427483/230536401-d881e305-e03f-4ae6-b1cf-eb23fc8f6c50.png)
![image](https://user-images.githubusercontent.com/48427483/230536925-3469fffb-b9f7-4fea-95b1-157fdcbe4fd9.png)

**一些必要的信息**
 - 系统： linux
 - 浏览器： chrome
 - 版本： [latest]
 - 部署方式：docker

**Comment by saimirgx** [comment]
看错误，可能是你的机器无法直连到openai的server

**Comment by saimirgx** [comment]
你可以试试 http://chat-gpt-api.cn/ 提供的镜像服务

**Comment by Yidadaa** [comment]
请确认你的服务器是否能访问 openai。

**Comment by SaintTom** [comment]
请问如何解决的，我也是这样

**Comment by SaintTom** [comment]
请问如何解决的，我也是这样

**Comment by fylm** [comment]
> 请确认你的服务器是否能访问 openai。

![image](https://user-images.githubusercontent.com/48427483/230562681-59f4bbc5-e963-4b94-9861-ca8070a2cb5b.png)
服务器是可以访问

**Comment by SaintTom** [comment]
> > 请确认您的服务器是否可以访问openai。
> 
> ![图像](https://user-images.githubusercontent.com/48427483/230562681-59f4bbc5-e963-4b94-9861-ca8070a2cb5b.png) 服务器是可以访问的
![image](https://user-images.githubusercontent.com/72240631/230564319-28b8f9f6-f1e1-4f61-8d98-f438a4094f76.png)
我是这样...

**Comment by Yidadaa** [comment]
@fylm 是直连，还是透过了 proxy 能连？这一点要区分清楚，curl 会自动使用 http_proxy。

**Comment by fylm** [comment]
> @fylm 是直连，还是透过了 proxy 能连？这一点要区分清楚，curl 会自动使用 http_proxy。

直连的 服务器是 亚马逊东京

**Comment by Yidadaa** [comment]
所以现在问题解决了吗？

**Comment by fylm** [comment]
刚解决，我使用了nginx的问题（要保留代理之前的真是ip）

**Comment by hiroi-sora** [comment]
报：我遇到了同样的错误。

经过：我原先使用正常，然后更换了防火墙（从firewalld换成iptables），之后就出现了与楼主相同的错误。不只是 ChatGPT-Next ，其它容器也ping不通外网域名。

解决：重装整个docker后问题解决。

**Comment by JadeUnicorn51** [comment]
docker dns解析问题，可参考以下链接解决，实测有效
https://blog.csdn.net/Franklin7B/article/details/91411262
