### ISSUE TITLE
[Suggest] 没有OPENAI_API_KEY或无法直连的同学可以看看这里

### ISSUE THREAD

**Issue by saimirgx** [Yidadaa/ChatGPT-Next-Web#585]
http://chat-gpt-api.cn 这个网站提供了一个 OpenAI 的镜像 `Endpoint` 和 `API Key`，只要在 [ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web) 设置好以下环境变量，即可稳定使用：

```
BASE_URL=[他们提供的endpoint]
PROTOCOL=http
OPENAI_API_KEY=[他们提供的key]
```

亲测好用，推荐一下

**Comment by Yidadaa** [comment]
请不要随意使用别人的中转服务，尤其不要在此推荐，此类服务会造成用户的 api key 的泄漏风险。

**Comment by saimirgx** [comment]
> api

老大好，这个服务提供的是他自己生产的 api key，并不要用户的 api key

**Comment by liujianchao1995** [comment]
> @Yidadaa
> 
> 老大好，这个服务提供的是他们自己的 api key，并不要用户的 api key

他们提供的api key在哪里啊，文档里没看到啊

**Comment by Biscuist** [comment]
> http://chat-gpt-api.cn 这个网站提供了一个 OpenAI 的镜像 和 ，只要在 [ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web) 设置好以下环境变量，即可稳定使用：`Endpoint``API Key`
> 
> ```
> BASE_URL=[他们提供的endpoint]
> PROTOCOL=http
> OPENAI_API_KEY=[他们提供的key]
> ```
> 
> 亲测好用，推荐一下

怎么用啊,求教
