### ISSUE TITLE
[Feature] 关于记忆上下文的一点建议

### ISSUE THREAD

**Issue by dale0525** [Yidadaa/ChatGPT-Next-Web#586]
当前版本下，前置上下文、历史记忆、附带历史消息数这三个概念感觉挺混乱的。下面是我的一点想法。
归纳起来，目前使用ChatGPT有三种模式：
- 聊天：需要发送所有历史消息。举例：
    - assistant: what can I do for you?
    - user: 帮我写一篇关于chatgpt的文章
    - assistant: blahblah...
    - user: 太长了，缩短一点
    - assistant: blah...
- 助手：只需要发送第一条system prompt（也包括当前的前置上下文功能，即few shot）和用户的最后一条消息。举例：
    - system: act like an English translator
    - user: 你好
    - assistant: hello
    - user: 早上好
    - assistant: good morning
- 临时：天南海北的临时提问，只需要发送用户的最后一条消息。举例：
    - user: 1+1等于几
    - assistant: 2
    - user: 秦朝持续了几年
    - assistant: 秦朝从公元前221年至公元前206年，持续了15年。

就我个人使用而言，其实很多时候都是临时提问，根本不需要上下文。在助手和临时模式下，发送上下文其实挺浪费token的。
在这两种模式下，偶尔会有个额外需求：在assistant的回答基础上进行一两次追问。这时候，需要把被追问的消息也一起发送。以上述的临时模式举例：

- user: 1+1等于几
- assistant: 2
- user: 秦朝持续了几年
- assistant: 秦朝从公元前221年至公元前206年，持续了15年。

> - user: 皇帝分别是谁？
> - assistant: 秦朝的第一位皇帝是嬴政，他在位期间改称“秦始皇”。秦始皇去世后由他的儿子扶苏继位，但不久被其弟武则天篡位，成为秦朝的第二位皇帝。武则天统治期间不长，仅维持了三年，后被联合起义推翻。随后，秦朝开始了短暂的“秦二世子婴时期”，但在两年后就被刘邦领导的汉军推翻，秦朝宣告灭亡。
- user: 1+3等于几

当然，这就需要记录消息之间的引用历史。

基于上述想法，建议是：
- 在新建聊天的时候，默认聊天模式是临时，不发送历史消息
- 用户可以更改聊天模式，以此更改发送的历史消息
- 只有在助手模式下，才可以设定当前的前置上下文功能
- 在“聊天”模式下，尽可能发送所有上下文，如果超出token，则依次删去最早的消息重试

**Comment by Yidadaa** [comment]
你可以在这里选择不发送记忆：

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/16968934/230546791-817faddf-3c51-4ec0-af70-3b67c11c5a63.png">

**Comment by Yidadaa** [comment]
单个聊天的详细设置需要等后续更新。
