### ISSUE TITLE
[Feature] 在预览气泡和每条回复下面上显示该消息消耗（将会消耗）的token

### ISSUE THREAD

**Issue by RogerProSelf** [Yidadaa/ChatGPT-Next-Web#588]
希望能够在预览气泡和每条回复下面上显示该消息消耗（将会消耗）的token，比如一行小字“本消耗消耗了1234 tokens”，可以参考落格的设计：chat-ai.logcg.com，非常感谢！

**Comment by yorunning** [comment]
每条消息显示所用的token数量，这样会不会让你对剩余额度感到焦虑呢？或许让它保持现状比较好。

**Comment by margox** [comment]
草，还以为是我提的issue

**Comment by Yidadaa** [comment]
引入 token 计算库的成本过高，会增加 2MB 的体积，这是无法接受的，所以不准备增加此功能。
