### ISSUE TITLE
[Feature] 建议在用户未设置 code 之前，弹出一个提示窗口让用户设置。

### ISSUE THREAD

**Issue by saimirgx** [Yidadaa/ChatGPT-Next-Web#589]
建议在用户未设置 code 之前，弹出一个提示窗口让用户设置。

否则，目前对于新用户第一次使用时，他是懵逼的，找不到去哪里填写code。

**Comment by Yidadaa** [comment]
我觉得“前往设置页填写”应该是个有效提示？弹窗非常影响体验，届时依然会有大量人询问这个弹窗是干嘛的。

**Comment by saimirgx** [comment]
我的理由如下：

1. 虽然“前往设置页填写”是个有效的提示，但是设置页的入口其实并不明显（特别是在手机端）
2. 即使进入到设置页，但页面中设置项过多，也很难一眼找到 code 的位置
3. 对于大部分普通用户来说，可能很少会需要到设置去做调整（因为默认设置一般来说就满足需求了），而 code 是他们唯一阻止正常使用的一项功能
4. 要设置 code 的人，肯定都是新人，对于新人，应该降低其开始门槛

**Comment by saimirgx** [comment]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/109264965/230560618-a2bd9049-e000-47b4-8c40-eef368de92ea.png">

这样的体验可能会更好一点

**Comment by cyhhao** [comment]
我 fork 了一个版本，就是一进来没code和apikey的话就弹框输入code，如果着急可以先用这个：https://github.com/cyhhao/ChatGPT-Next-Web
做了些小白友好的优化，默认Enter发送消息，默认紧凑边框，去掉无用设置项

**Comment by doem97** [comment]
> 我 fork 了一个版本，就是一进来没code和apikey的话就弹框输入code，如果着急可以先用这个：https://github.com/cyhhao/ChatGPT-Next-Web 做了些小白友好的优化，默认Enter发送消息，默认紧凑边框，去掉对小白无用设置项
> 
> 比较通用的修改就提PR了，主观的修改就不提了😂

Thanks for contribution.

**Comment by liujianchao1995** [comment]
> 我 fork 了一个版本，就是一进来没code和apikey的话就弹框输入code，如果着急可以先用这个：https://github.com/cyhhao/ChatGPT-Next-Web 做了些小白友好的优化，默认Enter发送消息，默认紧凑边框，去掉对小白无用设置项
> 
> 比较通用的修改就提PR了，主观的修改就不提了😂

大佬镜像不存在😭
