### ISSUE TITLE
点击回复的网址在当前窗口打开了,影响体验

### ISSUE THREAD

**Issue by banduoba** [Yidadaa/ChatGPT-Next-Web#59]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/4811366/227825205-774f97c7-478b-494f-ac75-c5e95f4d65d7.png">
可以在新窗口打开这个网址么

**Comment by Yidadaa** [comment]
ChatGPT 回复的格式问题，不属于该项目范围。
