### ISSUE TITLE
[Bug] 返回信息报错

### ISSUE THREAD

**Issue by SaintTom** [Yidadaa/ChatGPT-Next-Web#596]
描述问题
对话报错
{
"cause": {
"errno": -3001,
"code": "EAI_AGAIN",
"syscall": "getaddrinfo",
"hostname": "api.openai.com"
}
}
如何复现:发送消息
服务器可以ping通openai官网，但是聊天信息返回一致报错，超时

截图
![image](https://user-images.githubusercontent.com/72240631/230562941-4810c1bf-75ca-4d2b-914c-43365f2dc591.png)
![8ed29c82e36f8712fe07d83586cc70e](https://user-images.githubusercontent.com/72240631/230563429-999ef320-06e1-475f-85bf-fe4a495aeac8.png)

一些必要的信息:
系统： linux
浏览器： chrome
版本： [latest]
部署方式：docker

**Comment by SaintTom** [comment]
补充说明：当我选择回复的语言模型gpt-4的时候，返回的报错信息是上述的内容；
选择3.5模型的时候，返回的大部分是超时，少部分有其他的错误

**Comment by asaketsu** [comment]
该错误是因为主机名无法解析为 IP 地址，通常是由于 DNS 解析问题导致的。

其中 "EAI_AGAIN" 错误代码表示发生了 DNS 查询超时错误，导致无法解析主机名。此错误有时可能是暂时性的，因为 DNS 服务器可能会出现短暂的故障或维护工作。重试该操作，也可以尝试连接其他 DNS 服务器，或者使用 IP 地址替换主机名。

**Comment by Yidadaa** [comment]
重复 #584
