### ISSUE TITLE
[Feature] 布局调整优化建议

### ISSUE THREAD

**Issue by hulog** [Yidadaa/ChatGPT-Next-Web#597]
**这个功能与现有的问题有关吗？**
1. stream消息在返回过程中，对话框右上角的按钮随着内容不断填充而移动，过程中难以点击`暂停`
    >1. 在首行内容弹出过程中，顶部的`停止`、`复制`等按钮先向右跑
    >2. 如有多行时，随着新行产生时候，按钮会随着边框向上跑
2. 页面仅提供`新的聊天`来开启新一轮对话，若用户并不想保留之前的对话，期待可以直接`清除当前对话`(特别是移动端需求较旺盛)
3. 头像与内容排列方式，头像在上，内容在下的方式， 可能会挑战用户的接受度

**你想要什么功能或者有什么建议？**
1. 生成过程中，期望将停止按钮置于固定位置，如页面底部，方便用户暂停
2. 紧挨着输入框上部，增加一行操作区，支持用户清除当前session内的聊天内容
3. 是否可部分参考微信的对话布局？比如内容与头像在同一行，

**有没有可以参考的同类竞品？**
1. 参考chatgpt-vercel
![image](https://user-images.githubusercontent.com/21241893/230571936-9f34bd94-1c6d-4052-bb91-7ec272d16584.png)

2. 参考chatgpt-vercel
![image](https://user-images.githubusercontent.com/21241893/230571696-0ecb9f84-c06c-4287-9182-9763114ef2f1.png)
3. 参考chatgpt-web
![image](https://user-images.githubusercontent.com/21241893/230572139-727bdd8d-911f-4422-8252-8e83bdf15936.png)

**其他信息**
无

**Comment by Yidadaa** [comment]
1. 现在支持同时发多条消息，然后 chatgpt 同时回复，如果在页面底部增加停止按钮，无法确定应该停止哪个，除非只允许用户同时发一条消息；只需要耐心等待它回复一行，停止按钮位置就固定了，而且在移动端只要手动滑动了页面，也不会自动滚动，所以我认为现在的交互没什么问题；
2. 点击顶部的大脑图标，里面有你想要的；
3. 设计喜好问题，你说的这种布局会浪费很多横向布局，而且目前这种设计在很多聊天软件里都能看到，我不知道哪一点挑战到了用户的接受度了？
