### ISSUE TITLE
可以为对话命名吗？

### ISSUE THREAD

**Issue by guotao** [Yidadaa/ChatGPT-Next-Web#60]
![image](https://user-images.githubusercontent.com/46209/227826605-c152919c-30c6-48da-ba33-e490643c0e81.png)
如图中的，”new conversation“，我想命名为比如：日常、工具… 的名称，方便后续使用。

**Comment by Yidadaa** [comment]
正常情况下在第一次对话之后会默认总结对话，可以看看控制台是不是请求没发出去。
