### ISSUE TITLE
请教下回答问题需要卡半分钟才输出是什么问题？ 

### ISSUE THREAD

**Issue by jagerzhang** [Yidadaa/ChatGPT-Next-Web#600]
**描述问题**
上午部署的，输入问题立马就开始流式输出了，下午再用发现要卡半分钟才开始流式输出，不知道是不是openai自身的问题。目前部署在vercel美国区域，按理网络应该没问题，也没有使用代理。

**如何复现**
None

**截图**
![image](https://user-images.githubusercontent.com/9711651/230585127-eb5dfe19-1574-40e1-8647-583f6280145b.png)

**一些必要的信息**
 - 版本： 最新
 - 部署方式：vercel

**Comment by etodong** [comment]
我一直用也是 响应特别快， 现在用卡很久

**Comment by jagerzhang** [comment]
> 我一直用也是 响应特别快， 现在用卡很久

是的，下午突然变慢了，那应该是openai那边有什么问题。
TimeoutError: OpenAI timed out waiting for response

**Comment by Yidadaa** [comment]
openai 服务器的问题
