### ISSUE TITLE
[Not Bug] User Input 为什么没有被log

### ISSUE THREAD

**Issue by doem97** [Yidadaa/ChatGPT-Next-Web#602]
**描述问题**
我发现自己搭的好像有人在同时用，但是也不太懂是不是我自己的问题。。我看./app/store/app.ts 是有console.log("User Input")的，为什么我在console里没有看到这个print out呀

**如何复现**
就直接git clone & yarn install & yarn dev

**截图**
![image](https://user-images.githubusercontent.com/19631039/230589788-a5f456da-2dab-49fa-afe7-3251f36878fe.png)

**一些必要的信息**
 - 系统：WSL2
 - 浏览器： chrome
 - 版本：current
 - 部署方式：local

**Comment by starryloki** [comment]
这是在前端 console 输出的吧，要在 docker 输出还是得看看请求 API 的代码

**Comment by Yidadaa** [comment]
这是用户隐私
