### ISSUE TITLE
[Feature] 添加自定义镜像服务器功能
[Feature] Add proxy server's settings

### ISSUE THREAD

**Issue by black-fruit** [Yidadaa/ChatGPT-Next-Web#607]
可以在设置/安装时里设置自己的Proxy服务器
Can be setting the proxy servers in settings

这是个很重要的功能，可以加快用户的回复速度
This is a important module, can let chatgpt's reply faster.

英语不好，请谅解

**Comment by black-fruit** [comment]
另外不建议限制maxtoken，对于我们这种新手开发者来说，gpt的回复完整性很重要，有时候代码长，就无法呈现完整

**Comment by Kosette** [comment]
环境变量`BASE_URL`可以用来设置自定义的api proxy url。如果指的是程序本身的socks代理之类的，暂时似乎没有。

**Comment by black-fruit** [comment]
也就是说可以设置自己的加速地址，只是没有写进文档里吗

**Comment by black-fruit** [comment]
麻烦回复一下 #608

**Comment by black-fruit** [comment]
> 环境变量`BASE_URL`可以用来设置自定义的api proxy url。如果指的是程序本身的socks代理之类的，暂时似乎没有。

看差了，文档最近加了
