### ISSUE TITLE
[Bug] 无法发送请求

### ISSUE THREAD

**Issue by black-fruit** [Yidadaa/ChatGPT-Next-Web#608]
![Screenshot_20230407-204017.png](https://user-images.githubusercontent.com/77201076/230610541-7cd6e145-30eb-4c44-be16-277d0a20276e.png)

**这是最新版，后续未上传docker哦**

**Comment by Yidadaa** [comment]
设置里面 max_tokens 调到 4096 以内。

**Comment by black-fruit** [comment]
> 设置里面 max_tokens 调到 4096 以内。

4096行吗，是不是openai限制，崩溃了
