### ISSUE TITLE
[Bug] (accept-language	*)导致默认回复均为英文

### ISSUE THREAD

**Issue by galenzhao** [Yidadaa/ChatGPT-Next-Web#609]
Next.js Middleware
发出来的请求header的
accept-language	是*
并没有根据浏览器的优先级
比如
Accept-Language	zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6,ja;q=0.5,ko;q=0.4

导致会话都会默认以英文回复

**Comment by Yidadaa** [comment]
openai 只会根据你的输入来确定回复的语言，你问他中文，它就回你中文，否则就是英文。
