### ISSUE TITLE
[Bug] mac使用PWA安装后图标比其他的图标大一些

### ISSUE THREAD

**Issue by wangwu50** [Yidadaa/ChatGPT-Next-Web#612]
**描述问题**
mac使用PWA安装后图标比其他的图标大一些，希望能和其他系统图标保持一致

**如何复现**
在mac段部署后，打开网站，pwa本地安装。

**截图**
![image](https://user-images.githubusercontent.com/15371729/230633177-69e89cf2-2475-43df-b5a7-51379a85f3ab.png)

**一些必要的信息**
 - 系统：macos 13.3
 - 浏览器： chrome
 - 版本： f838591
 - 部署方式：docker部署

**Comment by Yidadaa** [comment]
mac 系统的 pwa 程序图标就是比其他程序大一圈。

**Comment by Yidadaa** [comment]
https://stackoverflow.com/questions/71118094/why-is-my-app-icon-bigger-than-the-others-in-the-macos-dock

**Comment by Yidadaa** [comment]
如果针对 macos dock 栏做处理，那么所有手机上面 icon 都会小一圈，所以暂时不会做特殊处理
