### ISSUE TITLE
[Bug] docker安装的无法使用gpt4模型

### ISSUE THREAD

**Issue by kintzhao** [Yidadaa/ChatGPT-Next-Web#614]
按照说明拉的docker, 是否有更新的docker版本，现在是否支持gpt4. 测试只有模型gpt-3.5-turbo可以使用。

docker pull yidadaa/chatgpt-next-web
docker run -d -p 3000:3000 -e OPENAI_API_KEY="" -e CODE="" yidadaa/chatgpt-next-web

**Comment by tanaer** [comment]
你的API要支持 GPT4~

**Comment by Yidadaa** [comment]
请确认你是否有 gpt4 权限。

**Comment by kintzhao** [comment]
我账号是plus, 网页chatgpt里面可以选择gpt4的功能，生成的key的权限是区分的吗？ 
![Screenshot from 2023-04-08 14-18-34](https://user-images.githubusercontent.com/11779271/230706700-fafcf279-4b4c-47c1-b83c-e6677fc7fc15.png)

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8gpt-4%E7%9A%84api%E8%AE%BF%E9%97%AE
