### ISSUE TITLE
[Feature] 建议在环境变量或配置文件中添加是否禁用“检查更新”一项

### ISSUE THREAD

**Issue by kressety** [Yidadaa/ChatGPT-Next-Web#619]
我在部署的时候对于上游项目做了一些改动，因此每次检查更新总是显示存在新版本，这使得“检查更新”功能无法发挥应有的作用。

实际上启用了自动merge的action后也没必要进行“检查更新”，希望可以提供一个途径来禁用“检查更新”功能，一来让界面更加美观，二来节省资源。

**Comment by Yidadaa** [comment]
你都自己改了，自己手动删掉不就行了
