### ISSUE TITLE
请问如何修改密码和api token

### ISSUE THREAD

**Issue by shexiaobin** [Yidadaa/ChatGPT-Next-Web#622]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-vercel-%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F
