### ISSUE TITLE
[Bug] This model's maximum context length is 4097 tokens，是什么问题，能不能显示成中文，一般人看不懂。

### ISSUE THREAD

**Issue by Jialinvip** [Yidadaa/ChatGPT-Next-Web#625]
{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, your messages resulted in 4619 tokens. Please reduce the length of the messages.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

[Bug] This model's maximum context length is 4097 tokens，是什么问题，能不能显示成中文，一般人看不懂，不知道如何处理。

**Comment by tjefferson** [comment]
token数超过限制了，这是openai API的回复，你减少一些字符或者清空上下文试试。

**Comment by Yidadaa** [comment]
更新到最新本吧试试。
