### ISSUE TITLE
服务器自部署，夸克浏览器浏览报错

### ISSUE THREAD

**Issue by realzsy** [Yidadaa/ChatGPT-Next-Web#626]
其他浏览器访问正常，只有夸克浏览器访问会报错

**Comment by realzsy** [comment]
![Screenshot_20230408-152514.jpg](https://cdn.zsy.life/zpic/230408/2ee4a2cb9f38b.jpg)

**Comment by realzsy** [comment]
https://cdn.zsy.life/zpic/230408/2ee4a2cb9f38b.jpg

**Comment by Yidadaa** [comment]
缓存问题导致的，关闭重进试试

**Comment by realzsy** [comment]
> 缓存问题导致的，关闭重进试试

清除缓存，访问依旧报错

**Comment by Yidadaa** [comment]
检查一下你的 ngnix 配置，是否把报错的这个资源的路径给 block 掉了。

**Comment by realzsy** [comment]
> 检查一下你的 ngnix 配置，是否把报错的这个资源的路径给 block 掉了。

未做什么特殊配置，其他浏览器一切正常

**Comment by realzsy** [comment]
![Screenshot_20230411-194908.jpg](https://user-images.githubusercontent.com/2454959/231155032-7de835ad-5608-4936-b166-e169937c2c32.jpg)

经测试，演示网站用夸克浏览器访问也会报错
