### ISSUE TITLE
[Feature] Shortcuts powered by `/`

### ISSUE THREAD

**Issue by realskyrin** [Yidadaa/ChatGPT-Next-Web#628]
**这个功能与现有的问题有关吗？**

目前 / 只能调出一些内置 prompt

**你想要什么功能或者有什么建议？**

将内置 prompt 触发指令设置为 /act or /prompt
拓展其它例如 /reset、/new 等实用指令

![WeChatd066a900dc60be157d30220780acf3f0](https://user-images.githubusercontent.com/16552732/230710842-94007b82-f0c7-487c-a9aa-102e966251a3.png)

**有没有可以参考的同类竞品？**

Telegram / Slack / Discord 皆可参考

**其他信息**

无

**Comment by Xerrors** [comment]
特别想要一个 `/new` 的功能，因为常年将其固定在浏览器的侧边栏使用，新建一个对话操作太麻烦了。想要一个 `/new` 或者叫 `/clear` 的功能

**Comment by JasonLeeForOnly** [comment]
附议！

**Comment by Yidadaa** [comment]
计划实现的命令：
- `/new` 新建对话
- `/newm` 新建对话，展示面具选择页
- `/next` 下一个对话
- `/prev` 上一个对话
- `/reset` 或 `/clear` 清空上下文
- `/del` 删除当前对话

如果有更多想法，请及时评论。

**Comment by Yidadaa** [comment]
主线代码已更新此功能，为了避免与提示词冲突，使用了 `:` 作为触发键。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/16968934/a9376fbd-d63b-4f25-850a-4586ea54acb5)
