### ISSUE TITLE
补充建议是否可能增加如下一些设定和功能

### ISSUE THREAD

**Issue by wrxx2019** [Yidadaa/ChatGPT-Next-Web#63]
看了之前的issue,参考了一些其他web项目，想补充一些提议供参考：
1.对话页面生成截屏图片，电脑上是复制图片到剪贴板，手机上是直接下载图片。
2.电脑页面底部增加一次删除所有提问和回答的功能，即清空所有对话。
3.点击每条消息前的头像可以锁定本条提问和对应的回答（或本条回答和对应的提问），清空对话时不会清除。
4.对于每条提问，增加修改和删除。点击修改是重新填入输入框等待修改，点击删除会自动删除这条提问和对应的回答。
5.对于每条回答，增加删除。点击重新回答也会自动删除这条提问和对应的回答。删除只会删除对应的回答。
6.点击顶部标题（闲聊）页面自动滚动到顶部，点击输入框滚动到底部。
7.支持显示回复中的图像/表格/数学公式/语法高亮
8.支持语音输入，如果能将回答调用语音库来语音输出更完美。

感谢！

**Comment by Yidadaa** [comment]
这属于深度定制，请找人付费二次开发。
