### ISSUE TITLE
[Bug] "正在输入…" 导致 UI 跳动

### ISSUE THREAD

**Issue by fei-ke** [Yidadaa/ChatGPT-Next-Web#630]
**描述问题**
回答过程中的 "正在输入…"  在头像和消息气泡之间，回答结束后 "正在输入…" 消失，消息气泡上移，导致UI 跳动。
建议把这个状态放到和头像一行，避免 UI 跳动

**如何复现**
正常发送消息，接收消息

**截图**
![](https://user-images.githubusercontent.com/2138570/230716654-aa9d1efa-b257-4414-84f3-5b20870cd198.png)

![](https://user-images.githubusercontent.com/2138570/230716719-60aed3db-8d9b-4a45-816a-09038f55d07b.png)

**一些必要的信息**
 - 系统：[macOS 12.3]
 - 浏览器： [chrome]
 - 版本： [当前版本：2666241]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
这是预期内行为，感觉并不会对正常使用造成影响。
