### ISSUE TITLE
[Feature] 余额查询模块可以显示多个用户的使用量

### ISSUE THREAD

**Issue by TankNee** [Yidadaa/ChatGPT-Next-Web#631]
多个用户关联到一个组织的时候所有消耗都会加在一起，不能直观看到单个消耗，希望增加对多用户用量的显示。

我自己做过一些探索，可以访问 https://api.openai.com/v1/usage 获取单个用户指定日期的token消耗记录，按照模型类型计算得到消耗额度。

**Comment by Yidadaa** [comment]
这是特殊需求，建议自己 fork 后单独开发，requests.ts -> requestUsage() 函数。
