### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by TBNRDev** [Yidadaa/ChatGPT-Next-Web#632]
**Describe the bug**
Whenever I enter a prompt, this will show up. (Already entered my OpenAI Key, which means it should work)

`{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
`

**Comment by Yidadaa** [comment]
Check this: https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq.en.md#it-prompts-you-exceeded-your-current-quota--when-using

Your free credits granted by openai has been expired.
