### ISSUE TITLE
[Bug] 使用fork其中的code无法起到作用

### ISSUE THREAD

**Issue by beiyaohhhc** [Yidadaa/ChatGPT-Next-Web#638]
**描述问题**
通过fork仓库和加上自定义变量code后 使用时提示请到设置里添加 而设置里未有此项 把code变量删了也是如此
**如何复现**
fork仓库 用vercel部署 添加code变量 无启用 删去code变量 设置里无显示填写code位置

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[windows 10/ ios 15.7]
 - 浏览器： [edge safari]
 - 版本： [40b8b22]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
你需要重新 deploy 项目才能使环境变量生效，在 vercel 控制台 - Deployment - 点击列表第一条末尾的三个点 - redeploy。
