### ISSUE TITLE
[Feature] Refactor with React Router

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#643]
We should use React Router to navigate between pages, this will make the development of future features simpler.

Related features: #640 #519 #138

**Comment by AprilNEA** [comment]
Nextjs comes with routing functionality and should not use React Router

**Comment by AprilNEA** [comment]
This will make significant changes to the current code and may affect most of the current PR

**Comment by Yidadaa** [comment]
@AprilNEA 

I prefer to treat this project as a SPA app, and disable most of SSR rendering.

**Comment by AprilNEA** [comment]
SPA can also be implemented by routing, using Next.js's layout.ts and <Link/>.
