### ISSUE TITLE
[Bug] 本地部署后使用pm2运行提示需要输入code,但是并没有设置过code，要在哪里修改呢

### ISSUE THREAD

**Issue by jiangqi9090** [Yidadaa/ChatGPT-Next-Web#644]

**Comment by oooneusop** [comment]
问题解决了么，我也遇到了

**Comment by Yidadaa** [comment]
把你部署命令提供一下。

**Comment by jiangqi9090** [comment]
> 把你部署命令提供一下。

使用这个命令部署 bash <(curl -s https://raw.githubusercontent.com/Yidadaa/ChatGPT-Next-Web/main/scripts/setup.sh)
然后进入根目录执行 npm run start

**Comment by Yidadaa** [comment]
建议使用 docker 部署，用的人多，基本不会遇到啥问题，手动部署受操作系统影响很大，一一排查很费劲。
