### ISSUE TITLE
需要梯子才能用吗

### ISSUE THREAD

**Issue by Gloria0929** [Yidadaa/ChatGPT-Next-Web#646]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/93187500/230759400-263473a6-6d86-41a1-847c-55ac003f6ac9.png">
这种情况是需要梯子才能用吗，key已经输入了

**Comment by drgnchan** [comment]
最终还是会请求openai的api的，这个环节是要梯子的。

**Comment by Yidadaa** [comment]
自己部署当然需要梯子。
