### ISSUE TITLE
本地部署之后，配置HTTP_PROXY,运行之后依旧连接超时，curl https://api.openai.com 返回码为403 证明是可以访问该网址的

### ISSUE THREAD

**Issue by xiqingsong** [Yidadaa/ChatGPT-Next-Web#647]
**描述问题**
我在本地部署的时候制定了HTTP_PROXY,运行之后依然是连接超时

**如何复现**
启动命令：https_proxy=http://10.211.55.2:7890 http_proxy=http://10.211.55.2:7890 all_proxy=socks5://10.211.55.2:7890 CODE="a1234"  HTTP_PROXY=http://10.211.55.2:7890  HTTP_PSROXY=http://10.211.55.2:7890 BASE_URL=api.openai.com PROTOCOL="https" node app/server.js
日志报错：
[Proxy]  v1/chat/completions
[Chat Stream]  [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
}
[Auth] allowed hashed codes:  [ '828c88f34ecb4c1ca8d89e018c6fad1a' ]
[Auth] got access code: a1234
[Auth] hashed access code: 828c88f34ecb4c1ca8d89e018c6fad1a
[Auth] set user token
[Proxy]  v1/chat/completions
[OpenAI]  ReadableStream { locked: true, state: 'closed', supportsBYOB: false } TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
      at node:internal/deps/undici/undici:8338:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8369:13)
      at process.processImmediate (node:internal/timers:476:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
**截图**
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/30694900/230761567-84cc03fb-ee50-4683-9e8f-2412ad3229f0.png">

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/30694900/230761427-4b168b79-0261-43e2-8a3a-8287bbd791ce.png">
<img width="903" alt="image" src="https://user-images.githubusercontent.com/30694900/230761784-33530656-422a-46cd-8f0d-1b1d60754030.png">

**一些必要的信息**
 - 系统：ubuntu20.02
 - 浏览器： chrome
 - 部署方式：本地部署

**Comment by Yidadaa** [comment]
#120 尚未支持 http_proxy

**Comment by yasu1209** [comment]
openai的原生createChatCompletion方法是可以注入options来配置代理的。
不能用这个方法调用吗？（刚开始在摸索，有的不是很清楚）

``` js
  try {
    // get current time stamp in long
    const currentTimeStamp = new Date().getTime();
    const completion = await openai.createChatCompletion({
      //model: "text-davinci-003",
      model: "gpt-3.5-turbo",
      //prompt: generatePrompt(animal),
      messages: [
        {'role': 'user', 'content': generatePrompt(animal)}
      ],
      temperature: 0.6,
    }, {
      proxy: {
        host: "127.0.0.1", 
        port: 7890
      }
    });
```

**Comment by Yidadaa** [comment]
axios 在 vercel edge runtime 用不了。

**Comment by yasu1209** [comment]
> axios 在 vercel edge runtime 用不了。

哦哦这样，了解了，感谢
