### ISSUE TITLE
[Bug] 回复响应延迟

### ISSUE THREAD

**Issue by DDWe11** [Yidadaa/ChatGPT-Next-Web#649]
**描述问题**
响应速度比官网明显慢很多

**如何复现**
我采用的vercel部署,使用国内dnspod解析了自己的域名

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：测试过后,基本所有的都会有延迟
 - 浏览器： [比如 chrome, safari]
 - 版本： d7c98dc
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
openai 对免费账户做了限速。

**Comment by peaceyourself** [comment]
真的是,就这两天突然慢如狗,反而官网web速度快了很多
