### ISSUE TITLE
[Bug] 在显示数学公式的时候如果式子太长会超出对话框边界

### ISSUE THREAD

**Issue by aahowe** [Yidadaa/ChatGPT-Next-Web#650]
**描述问题**
在显示数学公式的时候如果式子太长会超出对话框边界

**如何复现**
问：如何证明拉普拉斯展开式

**截图**

<img width="583" alt="QQ20230409-172359@2x" src="https://user-images.githubusercontent.com/75622829/230765289-678fc128-54eb-453b-b062-54df9744b8af.png">

**Comment by Yidadaa** [comment]
请提供你的浏览器版本、操作系统和设置里面的代码版本号，我无法复现这个问题。

顺便麻烦点击出问题的这个消息的复制按钮，把结果贴到这个 issue 里。

<img width="701" alt="image" src="https://user-images.githubusercontent.com/16968934/230780747-b3fc2f97-b8f5-42a7-8162-9315e375d494.png">
