### ISSUE TITLE
[Feature] 能否为部署设定每日调用上限

### ISSUE THREAD

**Issue by Andy17269** [Yidadaa/ChatGPT-Next-Web#652]

**Comment by Yidadaa** [comment]
不会增加此功能。

**Comment by Andy17269** [comment]
Why?&nbsp;



---原始邮件---
发件人: "Yifei ***@***.***&gt;
发送时间: 2023年4月9日(周日) 晚上7:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Yidadaa/ChatGPT-Next-Web] [Feature] 能否为部署设定每日调用上限 (Issue #652)




 
不会增加此功能。

**Comment by Yidadaa** [comment]
@Andy17269 记录调用上限需要一个持久化状态数据库，vercel 没有提供能力，如果接入一个数据库，会让项目的部署麻烦一倍，所以并不会增加此功能。不过之后会加上一个 api rate limit 功能。
