### ISSUE TITLE
如何修改默认界面语言不用设置直接就是中文？谢谢

### ISSUE THREAD

**Issue by mayichen1987** [Yidadaa/ChatGPT-Next-Web#653]
如何修改默认界面语言不用设置直接就是中文？谢谢
小白一个，找了半天没有找到对应的代码在哪里(=@__@=)

**Comment by Yidadaa** [comment]
语言是根据用户的操作系统语言自动设置的，没有默认语言的说法。

**Comment by mayichen1987** [comment]
> 语言是根据用户的操作系统语言自动设置的，没有默认语言的说法。

原来如此，谢谢。

**Comment by akmumu** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/42561d04de53dd9d2f1a8ef75ab2746b17aa43e7/app/locales/index.ts#L65
修改这一行
