### ISSUE TITLE
[问题] 编译报错

### ISSUE THREAD

**Issue by algol711** [Yidadaa/ChatGPT-Next-Web#655]
**描述问题**
请在此描述你遇到了什么问题。
下载了代码，安装完环境，build报错，能帮忙看看什么原因吗

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![image](https://user-images.githubusercontent.com/1128427/230774317-5207a780-22b3-41eb-83f4-1035487a918d.png)

**Comment by Yidadaa** [comment]
确保你的 nodejs 版本在 18 以上。

**Comment by Yidadaa** [comment]
`node -v`

**Comment by algol711** [comment]
> 

$ node -v
v18.15.0
是16以上的

**Comment by Yidadaa** [comment]
请提供一下你的服务器的系统版本，以及操作系统的架构（x86 或者 arm）。

**Comment by Yidadaa** [comment]
如果是在服务器上部署，建议你使用 docker 部署，就完全不用操心这些东西了。

**Comment by bing-h** [comment]
docker 镜像现在不支持 arm 架构的服务器，有支持的计划吗###

**Comment by Yidadaa** [comment]
@bing-h 已经增加 arm64 镜像
