### ISSUE TITLE
在mac部署报404的错误

### ISSUE THREAD

**Issue by zhaoyuan020** [Yidadaa/ChatGPT-Next-Web#656]
mac已经可以在终端使用全局代理
运行bash <(curl -s https://raw.githubusercontent.com/Yidadaa/ChatGPT-Next-Web/main/scripts/setup.sh)
报这个错误：
Running on MacOS.
curl: (22) The requested URL returned error: 404
/dev/fd/11: line 48: brew: command not found
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/dev/fd/11: line 55: cd: ChatGPT-Next-Web: No such file or directory
/dev/fd/11: line 56: yarn: command not found
Enter OPENAI_API_KEY: aaa
Enter CODE: aaa
Enter PORT: aaa
/dev/fd/11: line 64: yarn: command not found
/dev/fd/11: line 65: yarn: command not found

**Comment by zhaoyuan020** [comment]
https://raw.githubusercontent.com/Homebrew/install/master/install
这个地址的资源您确定还在吗？

**Comment by Yidadaa** [comment]
如果你看不懂这些报错，我建议你不要在自己电脑上部署，不然之后还有会更多的坑等着你。

**Comment by Yidadaa** [comment]
vercel 不香吗？

**Comment by zhaoyuan020** [comment]
> 如果你看不懂这些报错，我建议你不要在自己的电脑上部署，当然之后还会有更多的坑等着你。
确实不太懂，所以就问嘛。。。我觉得这个链接（https://raw.githubusercontent.com/Homebrew/install/master/install）确实有问题。。。


> vercel 不香吗？
挺香的，不过我之前没用过，一般都在自己的电脑上弄。

**Comment by Yidadaa** [comment]
@zhaoyuan020 

第一个链接是 brew 的报错，你可以问一下 brew 是什么，以及如何在你电脑上安装。

**Comment by zhaoyuan020** [comment]
已经部署好了，但是还是遇到了没法跟openai直连的问题，算了，不弄了发自我的 iPhone在 2023年4月10日，01:20，Yifei Zhang ***@***.***> 写道：﻿
@zhaoyuan020
第一个链接是 brew 的报错，你可以问一下 brew 是什么，以及如何在你电脑上安装。
