### ISSUE TITLE
[Bug] 余额查询那里可能显示得有问题

### ISSUE THREAD

**Issue by tjefferson** [Yidadaa/ChatGPT-Next-Web#657]
**Describe the bug**
显示的**本月已使用**数字还是昨天的那个数字，而我今天用了很多，看了下已经跟后台的数据对不上了，低于后台显示得数据，后台地址：https://platform.openai.com/account/usage

**To Reproduce**
1. 看设置页面的本月已使用
2. 看后台页面的本月usage数据
3. 对比这两个，发现前者低于后者

**Expected behavior**
两者基本一样

**Screenshots**

**Deployment**
- [ ] Vercel

**Desktop (please complete the following information):**
 - OS: Windows10
 - Chrome
 - 软件版本9133051

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
正常现象，数据会落后一到两天，vercel 缓存了部分请求。
