### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ETpaladin** [Yidadaa/ChatGPT-Next-Web#661]
我部署完以后，怎么只能选择gpt3.5,gpt4选中以后，一直没有回复。已经开过gpt会员了。请大神教教我

**Comment by StereoApp** [comment]
ChatGPT Plus 只能在ChatGPT首页使用GPT-4，并没有GPT-4模型的API权限，这个需要加入waitlist，好像拿到的人不太多。
