### ISSUE TITLE
[Feature] 用户可选择禁止 "API Key 模式绕过密码访问限制"

### ISSUE THREAD

**Issue by cshuo** [Yidadaa/ChatGPT-Next-Web#663]
**你想要什么功能或者有什么建议？**
目前没有用户登录管理，对于部署在私人服务器上的用户，可能不希望所有人都能通过 API key 模式来访问服务；希望可提供配置禁用 API Key 模式访问服务，强制必须设置访问密码.

![image](https://user-images.githubusercontent.com/13557966/230805825-31c31a8c-df90-4078-8b19-0b8b92a67606.png)

**Comment by yinm0591** [comment]
留着API Key是有必要的。如果配置在系统里的API Key突然失效，使用者可以填入自己的API Key继续使用。

**Comment by dgqyushen** [comment]
> 

我就是私人部署，但是我想分享给我的好友使用，然后我不想他们占用我的额度，叫他们自己买key使用

**Comment by cshuo** [comment]
@dgqyushen 我这里写的是 “可提供配置禁用”，默认保持原来行为。

> **你想要什么功能或者有什么建议？** 目前没有用户登录管理，对于部署在私人服务器上的用户，可能不希望所有人都能通过 API key 模式来访问服务；希望可提供配置禁用 API Key 模式访问服务，强制必须设置访问密码.
> 
> ![image](https://user-images.githubusercontent.com/13557966/230805825-31c31a8c-df90-4078-8b19-0b8b92a67606.png)

**Comment by devyujie** [comment]
搞个单选框

- [ ] 使用访问码
访问码：***

- [ ] 使用API Key
API Key：***

**Comment by calvin886886** [comment]
你在安装的时候不要填KEY.就非常的安全,

**Comment by wss-sosen** [comment]
可以直接在源码中删除这个填写控件：（app/components/settings.tsx），删除大概在地368-380行，如下代码： <SettingItem
            title={Locale.Settings.Token.Title}
            subTitle={Locale.Settings.Token.SubTitle}
          >
            <PasswordInput
              value={accessStore.token}
              type="text"
              placeholder={Locale.Settings.Token.Placeholder}
              onChange={(e) => {
                accessStore.updateToken(e.currentTarget.value);
              }}
            />
          </SettingItem>

**Comment by 2478641181** [comment]
> 

docker部署的可以改吗

**Comment by dgqyushen** [comment]
> docker部署的可以改吗

可以自己fork修改完，打包docker

**Comment by 2478641181** [comment]
> > Docker部署的可以改吗
> 
> 可以自己fork修改完，打包docker

emmm 我去研究研究 我的服务器是国外的 可以直接部署 但是国内访问延迟太高 有没有什么办法搞中转(目前国内外都有服务器)

**Comment by dgqyushen** [comment]
> > > Docker部署的可以改吗
> > 
> > 
> > 可以自己fork修改完，打包docker
> 
> emmm 我去研究研究 我的服务器是国外的 可以直接部署 但是国内访问延迟太高 有没有什么办法搞中转(目前国内外都有服务器)

套cdn什么的吧？或者自己用cloudflare反代openai的api接口（要有域名），然后用国内机器部署

**Comment by 2478641181** [comment]
> > Docker部署的可以改吗
> 
> 可以自己fork修改完，打包docker

有引文参考吗？去搜了一堆没有找到具体方法

**Comment by Moebyte** [comment]
反代的时候加个密码和用户名限制访问就行了

**Comment by hugoyue** [comment]
自己 nginx 配置个 basic auth 就行了吧

**Comment by gngshn** [comment]
> 自己 nginx 配置个 basic auth 就行了吧

前面说页面直接暴露不好, 我参考你这个方法弄了个basic auth, 还不错 :+1: https应该也是安全的, 挺好~

**Comment by dreamagician** [comment]
> 自己 nginx 配置个 basic auth 就行了吧

踩坑，proxy_buffering off，不然没法一边生成一边显示

**Comment by Yidadaa** [comment]
已经增加环境变量：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#hide_user_api_key-%E5%8F%AF%E9%80%89
