### ISSUE TITLE
[Bug] 返回信息报错

### ISSUE THREAD

**Issue by SaintTom** [Yidadaa/ChatGPT-Next-Web#665]
报错信息如下:
{
  "cause": {
    "errno": -104,
    "code": "ECONNRESET",
    "syscall": "read"
  }
}
环境：docker环境部署 谷歌浏览器
请问如何解决？

**Comment by SaintTom** [comment]
![image](https://user-images.githubusercontent.com/72240631/230821579-34280b6e-9fad-4f91-a095-eef7e3ee01a1.png)
补充下版本信息

**Comment by Yidadaa** [comment]
能直连 openai 服务器吗

**Comment by SaintTom** [comment]
可以直联

**Comment by SaintTom** [comment]
![image](https://user-images.githubusercontent.com/72240631/230882849-e0d12add-fd02-486d-ba20-59f661acc432.png)
但是现在经常还报错：
{
  "cause": {
    "name": "ConnectTimeoutError",
    "code": "UND_ERR_CONNECT_TIMEOUT",
    "message": "Connect Timeout Error"
  }
}
这个

**Comment by Yidadaa** [comment]
经常报错，意思是偶尔能用？

**Comment by Yidadaa** [comment]
@SaintTom 能 ping 通，不代表能用，你这是哪里的服务器，香港？

**Comment by SaintTom** [comment]
上午的时候通了，和他说写一篇日记，他回复了。。
珠海的服务器

**Comment by SaintTom** [comment]
下午开始就一直是连接超时，就很疑惑....
还有就是ping通不就是可以访问嘛//

**Comment by Yidadaa** [comment]
不要用国内的服务器，openai 会封，云服务器厂商也封，网安也会封，为什么要和他们过不去？

**Comment by SaintTom** [comment]
那请问用阿里云的国外服务器可以吗或者有没有其他别的办法？

**Comment by J1npen** [comment]
> 不要用国内的服务器，openai 会封，云服务器厂商也封，网安也会封，为什么要和他们过不去？

如果使用国外服务器来部署 NextChat，有什么办法可以让国内直连的设备也能用吗？我初衷是部署给家人用的。
