### ISSUE TITLE
请问这个项目可以作为纯静态页面部署到对象存储吗？

### ISSUE THREAD

**Issue by diemus** [Yidadaa/ChatGPT-Next-Web#666]
我希望以静态页面的方式部署，纯静态成本会低一些，而且可以让用户自己去配置自己的key，而不是用统一的，我用next build完好像不能直接部署，next export会报错

**Comment by LuDaHaMa** [comment]
+1 。我也想问，正常的next项目可以直接export 出来放tomcat中运行，这个项目不可以，解决了吗？请问

**Comment by Yidadaa** [comment]
不能，它有后端，虽然很薄

**Comment by diemus** [comment]
@Yidadaa 后端我可以自己写一个替代的，如果就目前这个项目来说，可以只build前端部分吗
