### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by wakaka123wakaka** [Yidadaa/ChatGPT-Next-Web#667]
建议增加一个密码的有效期，以及可以看到密码的使用量，可以随时对账号停用的功能

**Comment by Yidadaa** [comment]
不看文档是吧

**Comment by wakaka123wakaka** [comment]
> 不看文档是吧

我看文档的描述是需要重新部署，只有一个设置CODE的环境变量呢，并没有看到根据时间的自动停用呢

**Comment by Yidadaa** [comment]
我的意思是这个功能不会考虑加入。
