### ISSUE TITLE
[Feature] 增加对付费用户的 API 使用监控

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#668]
**这个功能与现有的问题有关吗？**
/

**你想要什么功能或者有什么建议？**
可以增加对付费用户的 API 使用情况的监控，有绑卡的显示当月或一共的使用额度，没有绑卡再显示试用额度。

**有没有可以参考的同类竞品？**
/

**其他信息**
/

**Comment by Yidadaa** [comment]
多久没更新代码了？这功能早就有了

**Comment by devyujie** [comment]
在试用状态下，显示`本月已使用 $xxx`，有点不准确，因为可能我的免费额度是 8.1 到期，这样只显示每月用了多少，下个月还会重新显示...应该计算一共使用了多少。毕竟这个功能的定位是`余额` 😛，例如我这个，其实我已经用了 4 美金了，但是现在并不能精确地看到到底还有多少余额。
![image](https://user-images.githubusercontent.com/48620527/230825805-fb2618bb-ce4a-4cd7-ad1c-ade9fd0b6456.png)
