### ISSUE TITLE
[Feature] 显示总使用额度，而不是当月使用额度

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#670]
**这个功能与现有的问题有关吗？**
/

**你想要什么功能或者有什么建议？**
在试用状态下，显示`本月已使用 $xxx`，有点不准确，因为可能我的免费额度是 8.1 到期，这样只显示每月用了多少，下个月还会重新显示...应该计算一共使用了多少。毕竟这个功能的定位是`余额` 😛，例如我这个，其实我已经用了 4 美金了，但是现在并不能精确地看到到底还有多少余额。

**有没有可以参考的同类竞品？**
/

**其他信息**
[#668](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/668#issuecomment-1501376711)
![image](https://user-images.githubusercontent.com/48620527/230826046-219259ce-0d70-49c1-aacc-d0e4bcfaed69.png)

**Comment by Yidadaa** [comment]
但这个功能并不是余额，虽然现在写的是余额，openai 的订阅就是按月付费。等后续更新更详细的余额查询功能。

**Comment by devyujie** [comment]
但是对于免费用户，显示账号里还有多少额度不是更直观么。

**Comment by devyujie** [comment]
可以搞两个模式，一个是免费用户的`余额`模式，一个是付费用户的`订阅`模式，这两个显示逻辑不同。

**Comment by devyujie** [comment]
例如：

你现在是`试用用户`，试用总额 $18，`当前`已用 $5.6，试用到期时间 2023/8/1
你现在是`付费用户`，`当月`已消费 $56，月消费上限 $150

**Comment by devyujie** [comment]
可以再加一个说明，额度标准来自于OpenAI，与本项目无关。

**Comment by tjefferson** [comment]
> 例如：
> 
> 你现在是`试用用户`，试用总额 $18，`当前`已用 $5.6，试用到期时间 2023/8/1
> 你现在是`付费用户`，`当月`已消费 $56，月消费上限 $150

你这里有些信息应该获取不到，比如到期时间
