### ISSUE TITLE
[Bug] Environment Variables Configuration Seems Ineffective

### ISSUE THREAD

**Issue by JohnZengshi** [Yidadaa/ChatGPT-Next-Web#675]
**Describe the bug**
Setting Environment Variables seems to be ineffective. The environment variables only exist in the build environment. When the build is completed, the build environment stops running, and the environment variables no longer exist at that point. As a result, it is not possible to read variables such as OPENAI_API_KEY, CODE, BASE_URL, etc., from process.env in the frontend JavaScript.

**To Reproduce**
Set Environment Variables

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by Yidadaa** [comment]
Please redeploy the project in Vercel dashboard to apply the environment variable settings.

**Comment by Yidadaa** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/16968934/230860519-9041dbd4-985d-4565-abc7-141ba832ea69.png">
