### ISSUE TITLE
[Bug] 提示GPT4模型不可用

### ISSUE THREAD

**Issue by heiheiheibj** [Yidadaa/ChatGPT-Next-Web#677]
当把模型切为GPT4后，提示不可用
{
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

谢谢

**Comment by HenMie** [comment]
是否已有gpt4的api权限？

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8gpt-4%E7%9A%84api%E8%AE%BF%E9%97%AE

**Comment by heiheiheibj** [comment]
> https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8gpt-4%E7%9A%84api%E8%AE%BF%E9%97%AE

忘了这茬了。。。谢谢谢谢
