### ISSUE TITLE
[Bug] 返回报告超时

### ISSUE THREAD

**Issue by gilao** [Yidadaa/ChatGPT-Next-Web#681]
![Uploading 9d2c036f9b5d7cb05ae46b811e33214.png…]()
必要的环境说明：
docker部署 最新
谷歌浏览器
可以直连openAI
![f59cba05393d8cc9172710132843b67](https://user-images.githubusercontent.com/93209652/230885374-7208011a-0add-48be-a0d1-9844f22295a9.png)
上午的时候是通的，现在就不行了，每一次都是返回请求超时的错误

**Comment by gilao** [comment]
![9d2c036f9b5d7cb05ae46b811e33214](https://user-images.githubusercontent.com/93209652/230885657-ade56637-156d-42fd-9ffd-8d35515aa585.png)

**Comment by Yidadaa** [comment]
不要单开 issue 了，在原来的 issue 里聊就行，如果它是一个共性问题，我会重新打开的。
