### ISSUE TITLE
[Feature] 支持 API2D 的余额查询

### ISSUE THREAD

**Issue by CSJiangyj** [Yidadaa/ChatGPT-Next-Web#686]
**支持 API2D 的余额查询**
Vercel 提供的 vercel.app 经常被污染而在境内无法直接访问，科学上网总不如直接访问较为便捷。
API2D（https://api2d.com ）提供的 API 可以在境内直接访问，同时也省去了 OpenAI 绑定海外信用卡的繁琐流程，是一种较为理想的替代方式。

希望能够支持 API2D 余额的查询。

目前的情况：
- 通过改变 BASE_URL 可以使用 API2D 的 ForwardKey
- 无法查询 API2D 的余额
![QQ拼音截图20230410213417](https://user-images.githubusercontent.com/23376352/230911375-999452fe-735d-4ac8-bdb8-af237a18fb88.png)

https://api2d.com/wiki/doc#api-credit 有相关描述，希望可以支持这个特性！

**Comment by CSJiangyj** [comment]
- OpenAI 查询用量使用的是 /dashboard/billing/usage
- API2D 查询余额使用的是 /dashboard/billing/credit_grants

**Comment by Yidadaa** [comment]
用户可以自行通过 BASE_URL 使用 api2d 的服务，绑定域名之后就无需梯子了，没有必要为所有人集成一个来路不明的第三方 api 服务。
