### ISSUE TITLE
[Feature] 在设置界面更换 BASE_URL

### ISSUE THREAD

**Issue by CSJiangyj** [Yidadaa/ChatGPT-Next-Web#692]
**支持在设置界面更换 BASE_URL**
如果不输入就默认是 OpenAI 提供的官方接口，
可以简化在 Vercel 或 Docker 中更改环境变量的流程。

**Comment by yinm0591** [comment]
这个功能是有安全风险的，外网用户可以通过不断更换url地址来探测内网情况的
