### ISSUE TITLE
[Bug] Nginx反向代理问题

### ISSUE THREAD

**Issue by singledog957** [Yidadaa/ChatGPT-Next-Web#693]
**描述问题**
让docker监听本地3000端口，使用Nginx Location块反向代理到3000端口时，无法正常工作。
如:如下配置时，访问`domain.com/chat`,会卡在加载页。
通过Nginx日志发现，发回的request被默认location块接收，没有被/chat接收。

**如何复现**
如上。

**截图**

![conf](https://user-images.githubusercontent.com/125362381/230930393-58f54ecc-c1f6-43a8-ad05-c77bf93c9775.jpg)

**一些必要的信息**
 - 系统：Centos 8 Stream
 - 浏览器：Edge 112.0
 - 版本： 2ec99bb
 - 部署方式：docker

**Comment by yinm0591** [comment]
我也发现了这个问题，项目必须部署到/目录下，不能改目录。

修改目录有1个好处：启动https后，可以防止GFW、国内云服务商探测到系统。

**Comment by Yidadaa** [comment]
https://stackoverflow.com/questions/65465606/how-to-deploy-next-js-app-with-nginx-to-subpath

**Comment by yinm0591** [comment]
@singledog957 ， 我测试了，通过以下方法能实现你需要的功能：
1. nginx.conf 将 proxy_pass http://127.0.0.1:3000/ 改成 proxy_pass http://127.0.0.1:3000

2. 运行以下命令，修改server.js里的配置信息
docker exec [容器名] sed -i 's/"basePath":""/"basePath":"\/chat"/g' /app/server.js

3. 重启容器
docker restart [容器名]

@Yidadaa ， 是否考虑加一个环境变量 PUBLIC_BASE_PATH，然后server.js里：
"basePath": process.env.PUBLIC_BASE_PATH || ''

毕竟，可以自己设置basepath能提升系统的安全性，防止被探测。谢谢了~

**Comment by singledog957** [comment]
感谢解答！
[https://stackoverflow.com/questions/65465606/how-to-deploy-next-js-app-with-nginx-to-subpath]()
在参照该教程后，得到了next.js的404页面
在参照 @yinm0591 的方法后，问题回到issue提出时状态。
现用config如下：
```
server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name domain.com;

        location / {
        alias /home/singledog/www/;
        }
        location /chat {
        proxy_set_header Host $host;
        proxy_cache off;  # 关闭缓存
        proxy_buffering off;  # 关闭代理缓冲
        chunked_transfer_encoding on;  # 开启分块传输编码
        tcp_nopush on;  # 开启TCP NOPUSH选项，禁止Nagle算法
        tcp_nodelay on;  # 开启TCP NODELAY选项，禁止延迟ACK算法
        keepalive_timeout 300;  # 设定keep-alive超时时间为65秒
        proxy_pass http://127.0.0.1:3000; 
        }
}
```

ps:我后来又试了下，在运行`docker exec [容器名] sed -i 's/"basePath":""/"basePath":"\/chat"/g' /app/server.js`后
使用`proxy_pass http://127.0.0.1:3000/; `可以得到next.js的404 page

**Comment by yinm0591** [comment]
@singledog957 

看一下server.js里basepath修改了吗？

```shell
docker exec [容器名] cat /app/server.js
```

**Comment by singledog957** [comment]
@yinm0591 上面的结果都是重启以后得到的
`proxy_pass`改了 问题没有改变 
我用Traefik试试

**Comment by zdian** [comment]
> https://stackoverflow.com/questions/65465606/how-to-deploy-next-js-app-with-nginx-to-subpath

这样操作以后，网页可以正常获取了。但api请求还是没有加上basePath。

**Comment by cui-daniel** [comment]
这个问题也困扰了我很久，试了很多在方法都不行，不清楚管理员为什么要关闭这个问题，要是不支持请直接说明，省得后面的朋友再去尝试了

**Comment by cui-daniel** [comment]
找到解决方法了
location /usa-vps/chatgpt/ {
        proxy_pass http://172.17.0.2:3000/;
}
location / {
        if ($http_referer ~ ^https?://[^/]+/usa-vps/chatgpt/) {
                proxy_pass http://172.17.0.2:3000;
                break;
        }
        if ($request_uri ~ ^/api/openai/v1/) {
                proxy_pass http://172.17.0.2:3000;
                break;
        }
        try_files $uri $uri/ /index.html;
}
基本可以解决问题

**Comment by leeyoshinari** [comment]
> 找到解决方法了 location /usa-vps/chatgpt/ { proxy_pass http://172.17.0.2:3000/; } location / { if ($http_referer ~ ^https?://[^/]+/usa-vps/chatgpt/) { proxy_pass http://172.17.0.2:3000; break; } if ($request_uri ~ ^/api/openai/v1/) { proxy_pass http://172.17.0.2:3000; break; } try_files $uri $uri/ /index.html; } 基本可以解决问题

大佬，好像还有一些路径有问题，例如：点击登陆，输入密码后就会跳转到根路径下面，然后强刷页面，就是返回nginx默认页面了

**Comment by x-ainger** [comment]
这个问题解决了没呀

**Comment by Nonosword** [comment]
用subdomain+http auth的方式，我放在 [https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/720](url)
