### ISSUE TITLE
[疑问提出🤔️] 关于Extensions/Api/UpdataLanZousResources?v=3.138请求

### ISSUE THREAD

**Issue by LovelyLM** [Yidadaa/ChatGPT-Next-Web#698]
这个请求是干什么的
![image](https://user-images.githubusercontent.com/46336155/231031007-28d31f9d-f8db-4005-a4e6-49cde8e518cf.png)
每次刷新都有
我看每次都是返回“非法请求”
![image](https://user-images.githubusercontent.com/46336155/231031197-8c20eec0-94a6-4428-a327-29779b73ec23.png)

可以去掉吗

**Comment by Yidadaa** [comment]
这是你自己装的浏览器插件的请求，和这个项目一点关系都没有。
