### ISSUE TITLE
[Bug] Chrome控制台显示Warning提示：hydration-error-info.js?32aa:27 Warning: Extra attributes from the server: cz-shortcut-listen

### ISSUE THREAD

**Issue by DinoFeng** [Yidadaa/ChatGPT-Next-Web#699]
**Describe the bug**
Chrome  browser console display:
hydration-error-info.js?32aa:27 Warning: Extra attributes from the server: cz-shortcut-listen

**To Reproduce**
1.打开浏览器
2.按F12
3.点选控制台
4.地址栏输入（localhost:3000）
5.网页加载时控制台显示：
![image](https://user-images.githubusercontent.com/15082286/231032603-f532bfc1-c955-4b92-b9a8-c3c83a8d2e01.png)

**Expected behavior**
控制台应该没有任何Warning或Error的提示

**Screenshots**
![image](https://user-images.githubusercontent.com/15082286/231032603-f532bfc1-c955-4b92-b9a8-c3c83a8d2e01.png)

**Deployment**
- 开发中

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser [chrome]
 - Version [96.0.4664.110 64位]

**Comment by Yidadaa** [comment]
有点 warning 很正常，修它性价比太低。
