### ISSUE TITLE
代码高亮有问题

### ISSUE THREAD

**Issue by erbao2001** [Yidadaa/ChatGPT-Next-Web#7]
<img width="753" alt="CleanShot 2023-03-23 at 20 59 06@2x" src="https://user-images.githubusercontent.com/123732260/227211738-55d1f64b-559e-41f9-a63e-25a12cf23d3e.png">

**Comment by Yidadaa** [comment]
感谢反馈，能否提供更多信息来帮助定位问题：
- 刷新页面后是否依然存在该问题？
- 设置中的主题选项是 auto/light/dark？切换主题后问题是否依然存在？
- 能否提供当前所用的操作系统版本和浏览器版本。

**Comment by erbao2001** [comment]
@Yidadaa 主题无论设置成什么，发现首屏的代码高亮是正常的，但是滚动到第二瓶以后得代码高亮都是有问题的，好像是这样的

Chrome：版本 111.0.5563.110
![CleanShot 2023-03-24 at 10 41 12@2x](https://user-images.githubusercontent.com/123732260/227410616-88a7d26b-1427-4250-aeae-dc8b0538ac3b.png)

**Comment by Yidadaa** [comment]
好的，请问你是在自己部署的代码上遇到的该问题，还是在本项目的演示网站中遇到的该问题？

**Comment by Yidadaa** [comment]
请尝试更新 fork 项目的代码与上游同步，该问题应该就自动解决了。具体方法请查阅本项目 readme。

**Comment by erbao2001** [comment]
@Yidadaa 我是看的你们演示站

**Comment by Yidadaa** [comment]
如果这个问题目前还是存在的话，能否提供一下出错信息的原始 markdown 文本？在消息上右键点击即可，然后贴到这里。

**Comment by zsnjuts** [comment]
我现在也遇到了这个问题。原始markdown文本如下：

这个错误提示表明，您在一个 const 成员函数中调用了一个非 const 成员函数。具体来说，你在一个 const 的 `adindex::IndexBitmapBase` 对象上调用了 `get_index` 函数，而 `get_index` 函数本身并没有被标记为 const。由于 const 成员函数中不能修改对象状态，因此不能调用非 const 成员函数。

解决这个问题的方法是，在 `get_index` 函数声明前加上 const 关键字，以表示该函数不会修改对象状态，例如：

```c++
RoaringArray *get_index() const { ... }
```

这样就可以在 const 成员函数中调用 `get_index` 函数了。

**Comment by Yidadaa** [comment]
确实会有这个问题，系统是夜间模式时，如果强制亮色，代码高亮就会出问题，有空修吧，建议先用 auto 凑合用着。
