### ISSUE TITLE
[Bug] Chrome 或 Edge控制台显示Warning提示：Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by DinoFeng** [Yidadaa/ChatGPT-Next-Web#700]
**Describe the bug**
Chrome or Edge browser console display:
Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.

**To Reproduce**
1.打开浏览器
2.按F12
3.点选控制台
4.地址栏输入（localhost:3000）
5.网页加载时控制台显示：(Chrome)
![image](https://user-images.githubusercontent.com/15082286/231033617-a5909246-3405-4fef-b9e4-08f3595dca64.png)

**Expected behavior**
控制台应该没有任何Warning或Error的提示

**Screenshots**
以下是Edge截图：
![image](https://user-images.githubusercontent.com/15082286/231033819-8413291f-92da-4c95-8e07-6e62260098b4.png)

**Deployment**
- 开发中

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [Chrome, Edge]
 - Version [96.0.4664.110 64位, 112.0.1722.34 64位]

**Comment by Yidadaa** [comment]
正常，react-dnd 库的报错，不影响使用。

**Comment by waltcow** [comment]
it seems very annoying in console

**Comment by Yidadaa** [comment]
拖拽排序对很多人是有必要的，所以为什么对这个 warning 这么念念不忘？你把控制台的 log 展示等级调成仅 log 不就行了？

**Comment by DinoFeng** [comment]
@Yidadaa , hello-pangea/dnd已经fix了，等更新
https://github.com/hello-pangea/dnd/issues/450
