### ISSUE TITLE
[Bug] 部署的应用 链接在手机钉钉上无法接收消息  一直在loading

### ISSUE THREAD

**Issue by Nicolasking007** [Yidadaa/ChatGPT-Next-Web#703]
- os：iOS 16.3.1
- 应用： 钉钉
-  部署：vercel，使用自己的域名
# 问题描述

在手机钉钉上打开链接 无法接收消息 一直处于loading 。PC端钉钉在应用内打开链接正常，能正常使用

![image](https://user-images.githubusercontent.com/45583166/231039891-fbadd0e6-e577-435c-bccb-5523fbafd9fb.png)

**Comment by Yidadaa** [comment]
这你应该去问钉钉移动端的人，脑子是不是进了什么东西：https://www.v2ex.com/t/908375

**Comment by ly75x12** [comment]
遇到了同样的问题
