### ISSUE TITLE
[Feature] 增加LaTeX数学公式渲染支持

### ISSUE THREAD

**Issue by RogerProSelf** [Yidadaa/ChatGPT-Next-Web#704]
如题，GPT-4在数学方面的进步非常显著，希望能增加LaTeX渲染的支持。
Nice Project!

**Comment by Yidadaa** [comment]
这不早八百年就有了？这项目刚发布的时候就有这功能啊，你用的哪个平行宇宙的代码？

#650

**Comment by Yidadaa** [comment]
请提供 iOS 版本。

**Comment by Yidadaa** [comment]
目前没有收到关于 Safari 渲染失败的反馈，从你的聊天记录来看，ChatGPT 返回的是用代码块包裹的 LaTex 代码，你可以换个问法，比如：如何证明拉普拉斯展开式
