### ISSUE TITLE
[Bug] 模型好像不支持gpt-4

### ISSUE THREAD

**Issue by Pirit** [Yidadaa/ChatGPT-Next-Web#705]
**描述问题**
请问可以支持gpt-4吗？切换后报错

**如何复现**
切换模型报错

**截图**
![image](https://user-images.githubusercontent.com/33412053/231046598-a8b10bc9-51bc-450e-931f-0edd90af80ff.png)

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8gpt-4%E7%9A%84api%E8%AE%BF%E9%97%AE
