### ISSUE TITLE
提示配额不足，但是明明还有18美元额度

### ISSUE THREAD

**Issue by jyjxqy** [Yidadaa/ChatGPT-Next-Web#706]
刚刚在vercel上搭建了项目，然后使用了openai的key，在后台可以看到这个月18美元额度还没有用，然后在这个项目的设置页面下查询也显示还有18美元。但是在对话里，一直提示
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
在给的demo里也用了个人的api key但是也是提示配额不足

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E4%BD%BF%E7%94%A8%E6%97%B6%E6%8F%90%E7%A4%BAyou-exceeded-your-current-quota-
