### ISSUE TITLE
[Feature] 对话框中的部分字体样式异常,可以优化一下

### ISSUE THREAD

**Issue by LonePheasantWarrior** [Yidadaa/ChatGPT-Next-Web#709]
![image](https://user-images.githubusercontent.com/37655011/231062554-27efc9de-9a58-4f9a-9466-08ad6e6206b7.png)
如图,在本次回话中,AI响应内容中的`param`和`return`字体的样式很奇怪

**Comment by LonePheasantWarrior** [comment]
问题发生在,2023/04/11上午 11:41
不清楚版本号多少,我可以确认在当时我的代码版本是最新的(有点强迫症,每次使用前都会检查代码是否最新,如果不是则会`update fork`等待重新发版后再使用 - -)

**Comment by Yidadaa** [comment]
那是识别成数学公式了，chatgpt 返回的 markdown 格式问题，我无法控制。
