### ISSUE TITLE
[Bug] 提示配额不足，但是明明还有18美元额度

### ISSUE THREAD

**Issue by zhhqiang3** [Yidadaa/ChatGPT-Next-Web#711]
Vercel 一键部署后，设置api key 后
提示
`{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
`

**Comment by lindudu1025** [comment]
和楼主一样，找到解决办法了吗？

**Comment by HemanJJ** [comment]
可以直接用openai提問，有回答沒有qoute的問題！是可以的！
但透過此法linebot就會發生"error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
  能有答案嗎？謝謝！
