### ISSUE TITLE
[Bug] 火狐浏览器的打字机特效异常

### ISSUE THREAD

**Issue by login2005** [Yidadaa/ChatGPT-Next-Web#712]
火狐浏览器的打字机特效异常，开头的一小段会卡一会然后一次性输出。
火狐版本：111.0.1 (64 位)
windows版本：Windows 10 专业工作站版21H2

**Comment by Yidadaa** [comment]
openai 的 api 卡了。

**Comment by login2005** [comment]
> openai 的 api 卡了。

我觉得应该与api无关，我用edge和chrome都是正常的。同个网络环境。同时做的测试

**Comment by Yidadaa** [comment]
那就不用 firefox 吧，浏览器兼容性问题弄起来很费劲，比较浪费时间。
