### ISSUE TITLE
这个问题，我没看明白，是api那边的问题？需要我去修复吗

### ISSUE THREAD

**Issue by mozhu-too** [Yidadaa/ChatGPT-Next-Web#713]
{
  "cause": {
    "errno": -3001,
    "code": "EAI_AGAIN",
    "syscall": "getaddrinfo",
    "hostname": "api.openai.com"
  }
}

**Comment by XSamuel** [comment]
我遇到类似的问题，请问下你最后是怎么解决的？多谢

**Comment by mozhu-too** [comment]
这个问题不是你们的问题，是我服务器的防火墙问题，然后我关闭后就好了

**Comment by mozhu-too** [comment]
所以我自己把问题就关闭了，要是没操作正确你们帮我关闭一下问题哈

**Comment by XSamuel** [comment]
我刚用docker部署，貌似安装好了，https://s3.bmp.ovh/imgs/2023/04/18/70ff6e3dfa1fe455.png
但还是显示这个问题 https://s3.bmp.ovh/imgs/2023/04/18/57060f5bc4b3b698.png。
方便的话帮忙看下？多谢

**Comment by mozhu-too** [comment]
> 但还是显示这个问题 [https://s3.bmp.ovh/imgs/2023/04/18/57060f5bc4b3b698.png。](https://s3.bmp.ovh/imgs/2023/04/18/57060f5bc4b3b698.png%E3%80%82)
> 方便的话帮忙看下？多谢

把你服务器的防火墙关了，iptables也清理一下规则，关掉。具体问chatgpt。如果还不行，把云服的规则改一下

**Comment by ywzheng19** [comment]
打扰，我也遇到同样的错误。docker部署，启动使用了http_proxy参数，海外vps代理。这种模式是不支持的吗

**Comment by whiteCcinn** [comment]
docker情况下的，感觉可以使用--network host解决这个问题，直接用宿主机的网络
