### ISSUE TITLE
[Feature] 想添加一个http请求忽略ssl证书的配置rejectUnauthorized

### ISSUE THREAD

**Issue by tossboy-ai** [Yidadaa/ChatGPT-Next-Web#718]
**这个功能与现有的问题有关吗？**
在使用BASE_URL参数的时候
Host使用错误的SSL证书这种情况下会返回 UNABLE_TO_VERIFY_LEAF_SIGNATURE

**你想要什么功能或者有什么建议？**
想添加出一个env配置项 以设置rejectUnauthorized为false从而忽略证书的报错。
即使证书是错的也应该劲量使用https而不是http。

我是在docker中使用，如果去改代码会有点麻烦，所以恳请作者大大把这个参数设置为可配置。

**Comment by Yidadaa** [comment]
所以为什么要用错误的证书？

**Comment by tossboy-ai** [comment]
> 

可能是自签，也可能是过期。但是总比用http在网上裸着好。: )

**Comment by yinm0591** [comment]
有一种变通的方式，加一个stunnel或者gost容器，先把https解码成http，再提供给next web

**Comment by Chang-Tao** [comment]
使用反向代理不很好吗，配合泛域名证书
