### ISSUE TITLE
[Bug] Nginx subpath仍然不可用

### ISSUE THREAD

**Issue by singledog957** [Yidadaa/ChatGPT-Next-Web#720]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
 #693 
subpath仍然不可用
[已参考:1](https://stackoverflow.com/questions/60849095/nextjs-app-deploying-using-docker-and-nginx-so-i-can-have-a-custom-base-path)
[2](https://stackoverflow.com/questions/65465606/how-to-deploy-next-js-app-with-nginx-to-subpath)
麻烦作者了 

**如何复现**

**截图**

**一些必要的信息**
 - 系统：Centos Stream 8
 - 浏览器：edge
 - 版本： 2ec99bb
 - 部署方式：docker

**Comment by Yidadaa** [comment]
欢迎 pr：https://levelup.gitconnected.com/deploy-your-nextjs-application-on-a-different-base-path-i-e-not-root-1c4d210cce8a

**Comment by ttimasdf** [comment]
可以在反代侧，把 sub path strip 掉。

[Traefik StripPrefix Documentation - Traefik](https://doc.traefik.io/traefik/middlewares/http/stripprefix/)

**Comment by Yidadaa** [comment]
支持 sub path 会让网络资源管理变得麻烦，所以我不准备支持此特性，如果未来找到了更好的方法，再做考虑。

**Comment by leeyoshinari** [comment]
> 支持 sub path 会让网络资源管理变得麻烦，所以我不准备支持此特性，如果未来找到了更好的方法，再做考虑。

建议作者考虑支持一下自定义 prefix。部署在根路径下，很容易被其他人撞到，，issue里就看到好几个这样的提问，建议作者考虑一下吧

**Comment by Nonosword** [comment]
各种方法试了不少，无论docker还是got clone来部署，对于nginx +subpath方式的支持都不太友好。
所以最好的方法就是用 subdomain，然后加个http auth，防止被直接扫到，和subpath效果一样。
nginx里监控分别跟踪子域名和主域名，子域名对http加auth basic，对api忽略auth：

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name ai.xxxxxx.com;
        ssl_certificate
        ......

        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location ^~ /api/ {
            auth_basic off;
            proxy_pass http://localhost:3000;
        }

        # chatgpt-next-web 配置
        location / {
            proxy_pass http://localhost:3000/;
        }
    }

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name xxxxxx.com *.xxxxxx.com;
        ......
