### ISSUE TITLE
[Feature] 看到出现了一个长期记忆功能

### ISSUE THREAD

**Issue by feiyu0** [Yidadaa/ChatGPT-Next-Web#722]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
openai新出了一个插件，提供长期记忆功能，请问会考虑加入这个功能吗

**有没有可以参考的同类竞品？**

https://github.com/openai/chatgpt-retrieval-plugin

https://memorygpt.io/

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
这个需要后端数据库配合，等插件功能加入之后再说吧。

**Comment by Yidadaa** [comment]
#960
