### ISSUE TITLE
fork了项目之后怎么自动同步

### ISSUE THREAD

**Issue by fangyuan99** [Yidadaa/ChatGPT-Next-Web#724]
我是按照readme里面的方式，首先fork了项目，然后再在vercel里面部署的项目，但是我发现好像并没有每天自动同步代码，还是得自己手动sync fork

**Comment by cary-hu** [comment]
默认自动fork是关闭的，你需要去Actions里面自行打开 Upstream Sync

**Comment by Yidadaa** [comment]
已经补充到说明文档：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#%E6%89%93%E5%BC%80%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0

**Comment by Corwin006** [comment]
> @Corwin006 你需要先手动同步一下

谢谢，我试试看！ :)

**Comment by Corwin006** [comment]
@Yidadaa  不好意思，手动同步过一次后，能自动同步了，但是几个小时后，出现了新的问题，是不是每小时同步一次太频繁了？
`remote: Resolving deltas: 100% (26/26), completed with 12 local objects.        
To https://github.com/Corwin006/ChatGPT-Next-Web.git
 ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/sync.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/Corwin006/ChatGPT-Next-Web.git'
ERROR:  exit 1
Could not push changes to target repo.
Try running in test mode to verify your action input. If that does not help, please open an issue.
Resetting git config to previous settings.
Reset Complete

Error: The process '/usr/bin/sh' failed with exit code 1`

![image](https://user-images.githubusercontent.com/130281759/231634502-34738e75-6b63-4338-808c-24540470393c.png)

**Comment by Corwin006** [comment]
@Yidadaa 好吧，请无视我前面的问题，我重新手动同步了一下，再手动执行了一遍action试了一下，成功了。 -_-|||
继续观察。

**Comment by ronsongg** [comment]
我也出现了这个错误，刚开始同步是正常的没有问题，几次之后出现了同样的错误，

**Comment by Tyrone2333** [comment]
+1 刚开始同步是正常的没有问题，几次之后出现了同样的错误. 建议一天一次, 一个小时太频繁了邮箱疯狂报警

**Comment by Yidadaa** [comment]
上游的&nbsp;workflow&nbsp;文件发生改动，下游的自动更新就会失败，这时候需要手动更新，更新完了就没事了，而且并不会天天改动&nbsp;workflow，就这两天改了两次而已。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月13日(周四) 下午2:08
收件人: ***@***.***&gt;;
抄送: &quot;Yifei ***@***.******@***.***&gt;;
主题: Re: [Yidadaa/ChatGPT-Next-Web] fork了项目之后怎么自动同步 (Issue #724)




 
+1 刚开始同步是正常的没有问题，几次之后出现了同样的错误. 建议一天一次, 一个小时太频繁了邮箱疯狂报警
 
&mdash;

**Comment by gooker** [comment]
几百个workflow错误疯了

**Comment by Yidadaa** [comment]
@gooker 

手动 sync 一下就行了，之后并不会频繁改动。
