### ISSUE TITLE
[Bug]关于模型选择问题 

### ISSUE THREAD

**Issue by freefoxcm** [Yidadaa/ChatGPT-Next-Web#729]
我在设置中使用的一直都是gpt-3.5-turbo ，但是查询后台API的调用日志，却是调用的gpt-3.5-turbo-0301，请问下这是有BUG吗？
![image](https://user-images.githubusercontent.com/14037553/231327611-0b653731-f820-4db4-aa7c-4a3f2c605e89.png)
![image](https://user-images.githubusercontent.com/14037553/231327682-49369121-4cd4-4017-b90e-eb5e608bbba8.png)

**Comment by Yidadaa** [comment]
随便聊两句天，然后把浏览器控制台截图提供一下，里面会有 log 记录你用的是什么模型。

**Comment by freefoxcm** [comment]
嗯嗯，看到了，日志里记录的倒是确实是gpt-3.5-turbo
![image](https://user-images.githubusercontent.com/14037553/231331491-c5241907-deef-4489-8eb6-a233b7bbfdd0.png)

**Comment by StereoApp** [comment]
这不是bug，之前在别的项目中也遇到过，其实并不存在两个模型，gpt-3.5-turbo 和 gpt-3.5-turbo-0301 是一样的，有点类似版本控制，gpt-3.5-turbo-0301就是gpt-3.5-turbo现在的最新版。

**Comment by freefoxcm** [comment]
嗯嗯，应该是的，我尝试了其他的一些工具，以及自己写代码调用api，后台的记录确实都是gpt-3.5-turbo-0301 
![image](https://user-images.githubusercontent.com/14037553/231334279-71a7fe82-d0b6-48e5-84d7-b0ad5e8c88ee.png)
