### ISSUE TITLE
页面切回来后,就会滚动到底部了.

### ISSUE THREAD

**Issue by lifetin** [Yidadaa/ChatGPT-Next-Web#73]
页面切回来后,就会滚动到底部了.
切换浏览器tab,回来后他滚动条跑到底部了, 我故意停在我查看信息的位置,回来又要重新滚动
这个不是个BUG吗?

**Comment by lifetin** [comment]
比喻我对话30次.我拉动滚动条,查看第15和内容,然后我切换tab去看一下别的文章,回来后, 滚动条跑到第30条的位置,而不是在我原来15条对话的位置

**Comment by Yidadaa** [comment]
现在的滚动逻辑是当聚焦到输入框时，就会触发自动滚动，你可以先点一下输入框之外的任何地方让它失去焦点就可以了。

**Comment by lifetin** [comment]
漂亮, 果然如此, 建议加个设置,是否自动滚动. 输入模式要是能
