### ISSUE TITLE
[Feature] 快捷配置session级别的model参数

### ISSUE THREAD

**Issue by drgnchan** [Yidadaa/ChatGPT-Next-Web#732]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/40224023/231347458-a27f12bf-3ab5-426c-af15-49d3d64b578b.png">
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/40224023/231347493-a4de9846-02e0-43b6-a5ea-68338e3e9b61.png">

希望能有session隔离的model参数，方便在会话中快速切换模型，且不影响全局的model配置。

**Describe alternatives you've considered**

**Additional context**

**Comment by Yidadaa** [comment]
请关注 #684
