### ISSUE TITLE
[Bug] 消息压缩闸值有什么好建议吗？gpt回复多的话，将频繁进行压缩对话

### ISSUE THREAD

**Issue by liqiujiong** [Yidadaa/ChatGPT-Next-Web#737]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在连续问问题之后，触发了闸值，通过压缩精简了历史对话信息。此时继续发送消息，发的消息让chatgpt又回了很长的消息内容，导致下一次在问问题，又再触发一次压缩。
想问下这两个参数推荐值是多少比较好呢？

**如何复现**
历史消息长度：12
长度压缩闸值：1500

**截图**
![image](https://user-images.githubusercontent.com/5794205/231363132-abd9cfbd-e339-446b-94b5-d8c68824aa65.png)
图片中的日志是自己加的，仅仅是messages中所有是content的长度之和，不代表token。不过中文可以按*2做为token长度

**Comment by Yidadaa** [comment]
压缩阈值拉大，历史信息拉小
