### ISSUE TITLE
[Bug] Docker 部署代理失败

### ISSUE THREAD

**Issue by WangNingkai** [Yidadaa/ChatGPT-Next-Web#738]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
Docker 部署代理失败

**如何复现**
![image](https://user-images.githubusercontent.com/23030927/231364225-12436f6f-e7a4-46d5-8919-0fcca70192c2.png)

**截图**
![image](https://user-images.githubusercontent.com/23030927/231364088-b419aac4-85dc-4fd7-b22d-08818f4706ae.png)

**一些必要的信息**
 - 系统：[linux]
 - 部署方式：[docker]

**Comment by Yidadaa** [comment]
你这应该改 BASE_URL，而不是 proxy
