### ISSUE TITLE
[Bug] Unsupported Linux distribution

### ISSUE THREAD

**Issue by RogerHao** [Yidadaa/ChatGPT-Next-Web#739]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用 Azure，Linux (ubuntu 18.04) 执行部署；
报错：Unsupported Linux distribution
SSH 执行 bash <(curl -s https://raw.githubusercontent.com/Yidadaa/ChatGPT-Next-Web/main/scripts/setup.sh)

**如何复现**
同上

**截图**
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/12681054/231384436-eda4f9d1-38a4-4128-9c7b-84980197c7f8.png">

**一些必要的信息**
 - 系统：Azure，Linux (ubuntu 18.04)

**Comment by Yidadaa** [comment]
强烈建议使用 Docker 部署。

**Comment by RogerHao** [comment]
感谢回复，最开始就优先选择 docker 部署了，但是指定了 PROXY_URL 环境变量时，docker 容器无法启动，且没有报错；又尝试了 bash 模式；
去掉 PROXY_URL 已正常启动；是否可以增加下报错，或是我的使用方式有问题？

**Comment by Yidadaa** [comment]
你可以查看 docker 内的 log，问问 chatgpt 就知道了，一般是由于你的 PROXY_URL 格式有问题，现在不支持带密码的代理地址
