### ISSUE TITLE
[Bug] 代理设置问题

### ISSUE THREAD

**Issue by cui8** [Yidadaa/ChatGPT-Next-Web#740]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用 Cloudflare Workers 免费10万次请求搭建的代理，选项设置为BASE_URL，但是使用报下图错误。
```
docker run -d -p 59172:3000 \
   -e OPENAI_API_KEY="sk-hr****c6X5drA" \
   -e CODE=")nosVxqv#mmcPuLh7#" \
   -e BASE_URL="https://openai.******.tk" \
   yidadaa/chatgpt-next-web
```
![Snipaste_2023-04-12_15-48-15](https://user-images.githubusercontent.com/70044239/231391849-7c111f3a-31ef-4815-b89e-59b158fc402a.png)

**Comment by Yidadaa** [comment]
请仔细阅读 BASE_URL 环境变量的定义，里面不应该有 https，我之后会改掉这个逻辑，不过你目前需要把 `https://` 从里面删掉。

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F
