### ISSUE TITLE
[Feature] 希望增加进入访问页面就提示输入密码/api的弹窗

### ISSUE THREAD

**Issue by CasenChan** [Yidadaa/ChatGPT-Next-Web#741]
希望增加进入访问页面就提示输入密码/api的弹窗，点击设置下拉寻找密码/api输入入口的操作有点繁琐

**Comment by Sneezry** [comment]
我自己试着通过 Next Auth 加了 sso，没登录的时候就只有登录页面。但作者在 readme 里说不会计划加用户功能，所以我没提 PR。如果作者愿意接受 sso 的 PR 我可以 contribute。

**Comment by Yidadaa** [comment]
@Sneezry 主要是加了登录鉴权没啥用，我不准备加数据库。

**Comment by white0dew** [comment]
> @Sneezry 主要是加了登录鉴权没啥用，我不准备加数据库。

你有fork的仓库可以参考一下吗

**Comment by Sneezry** [comment]
> > @Sneezry 主要是加了登录鉴权没啥用，我不准备加数据库。
> 
> 你有fork的仓库可以参考一下吗

SSO 不需要数据库的。https://github.com/Sneezry/Azure-ChatGPT-Next-Web

因为我是自己用的，所以我 SSO 做的比较粗糙，没考虑不启用 SSO 时的逻辑。

**Comment by Sneezry** [comment]
> @Sneezry 主要是加了登录鉴权没啥用，我不准备加数据库。

SSO 不需要数据库的，用户登录的目的其实也不是用于权限控制，主要是不想让 ChatGPT 的页面公开在网上出现。

**Comment by Sneezry** [comment]
> @Sneezry 主要是加了登录鉴权没啥用，我不准备加数据库。

SSO 不需要数据库的，用户登录的目的其实也不是用于权限控制，主要是不想让 ChatGPT 的页面公开在网上出现。

**Comment by Sneezry** [comment]
> @Sneezry 我知道不需要数据库，主要是我不准备增加用户信息存储能力，所以加个鉴权个人感觉没有什么用武之地

我个人的 concern 是我怕我自己域名下的网页公开出现 ChatGPT 字样域名会被污染。

**Comment by Yidadaa** [comment]
这个倒是挺合理的

**Comment by waltcow** [comment]
https://docs.logto.io/ 
sso自己集成了下也很方便

**Comment by yuntian123456** [comment]
> > @Sneezry 主要是加了登录鉴权没啥用，我不准备加数据库。
> 
> SSO 不需要数据库的，用户登录的目的其实也不是用于权限控制，主要是不想让 ChatGPT 的页面公开在网上出现。

没错，我也是这个想法。不想一打开网页，别人就知道这个网址是干嘛的

**Comment by Nicolasking007** [comment]
授权密码前置      整个类似锁屏页面

**Comment by leochen12-rgb** [comment]
> 授权密码前置 整个类似锁屏页面

这个想法不错

**Comment by Sneezry** [comment]
> 授权密码前置 整个类似锁屏页面

如果只是要加个静态密码那就更简单了：https://github.com/Sneezry/Azure-ChatGPT-Next-Web/blob/fdb9e62e4fcc9792d48cfd4b06d052c3998574a6/pages/api/auth/%5B...nextauth%5D.ts#L17-L31

**Comment by Nicolasking007** [comment]
> > 授权密码前置 整个类似锁屏页面
> 
> 如果只是要加个静态密码那就更简单了：https://github.com/Sneezry/Azure-ChatGPT-Next-Web/blob/fdb9e62e4fcc9792d48cfd4b06d052c3998574a6/pages/api/auth/%5B...nextauth%5D.ts#L17-L31

已补充示例图

**Comment by skylinewx** [comment]
大佬 这个静态密码功能会有吗，我也是不想一打开网页，别人就知道这个网址是干嘛的，密码默认走访问密码或者单独加个配置项

**Comment by hceasy** [comment]
这个我都是走nginx的鉴权.

**Comment by saigyouyou** [comment]
> > @Sneezry 主要是加了登录鉴权没啥用，我不准备加数据库。
> 
> SSO 不需要数据库的，用户登录的目的其实也不是用于权限控制，主要是不想让 ChatGPT 的页面公开在网上出现。

嗯，我也是这个需求。因为是我和几个朋友用，不希望其他公网上的人扫到了知道是干啥的。

**Comment by pangao66** [comment]
https://vercel.com/templates/next.js/basic-auth-password
vercel 官方有个例子，  可以进去之前输入账号密码， 但是我没弄明白咋实现的

**Comment by Chandler-Lu** [comment]
> https://vercel.com/templates/next.js/basic-auth-password vercel 官方有个例子， 可以进去之前输入账号密码， 但是我没弄明白咋实现的

这是 basic auth，是服务器来实现的 https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by daipic** [comment]
> 

只需要修改这一点点?

**Comment by Yidadaa** [comment]
目前已经增加欢迎消息的快速跳转到设置按钮。

**Comment by shsunb** [comment]
是否考虑给每个code加个计数？

**Comment by Yidadaa** [comment]
@shsunb 不会考虑

**Comment by woshiwo900228** [comment]
> https://docs.logto.io/ sso自己集成了下也很方便

可否看下如何继承到这个项目的

**Comment by ivanberry** [comment]
**Notice**:

注意使用Nginx来做用户管理的，不要升级最新版本，openai apiKey的key名改为了authorization 头，导致nginx baisc auth 失败

**Comment by GrayXu** [comment]
#https://github.com/Yidadaa/ChatGPT-Next-Web/commit/48ebd74859042aaa3d8cdbb74a61bd7391400b89 
nginx http auth应该还是外部常用的吧，可不可以新feature的实现不通过覆写这个？

**Comment by brodyxchen** [comment]
> **Notice**:
> 
> 注意使用Nginx来做用户管理的，不要升级最新版本，openai apiKey的key名改为了authorization 头，导致nginx baisc auth 失败

我升级最新版本后，发现一直弹nginx的登录界面。  暂时只能降级了
以后总得升级版本， 这个nginx的auth， 有办法解决不？

**Comment by bright2048** [comment]
> https://docs.logto.io/ sso自己集成了下也很方便

大神有偿指导一下，万分感谢

**Comment by sunxiang0918** [comment]
请问一下，这是在哪儿配置呢？ 在设置里面没找到呢？

**Comment by BenYegq** [comment]
难道没有人用 Cloudflare Access 解决么？很方便，1分钟设置搞定，前提是你的域名是托管在 CF 上的

**Comment by yuntian123456** [comment]
> 

有教程吗

**Comment by BenYegq** [comment]
> > 
> 
> 有教程吗

看这里： https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/

**Comment by lainme** [comment]
使用nginx的basic auth，又想升级到最新版的可以试试这里的方法：

https://community.home-assistant.io/t/solved-nginx-basic-auth-not-working/246066/9

如果不希望登陆长期有效可以不写cookie的max-age，这样关闭浏览器cookie就会失效。

**Comment by Joe-dr** [comment]
> 我自己试着通过 Next Auth 加了 sso，没登录的时候就只有登录页面。但作者在 readme 里说不会计划加用户功能，所以我没提 PR。如果作者愿意接受 sso 的 PR 我可以 contribute。

可以分享一下吗？我也是不想让访客知道这个页面是什么，输入验证密码后才显示页面

**Comment by Joe-dr** [comment]
> 授权密码前置 整个类似锁屏页面
> 
> * 原型图
> 
> ![image](https://user-images.githubusercontent.com/45583166/231699400-a0ca76c2-57b6-4893-9c9e-352870c1c72a.png)
> 
> * 中途离开 防止别人看见提交的问题
> * 也可禁止一些外部人员 点链接 看见搭建的服务是干什么用的

可以分享源码吗。我也想有这么一个隐私的页面

**Comment by wangping886** [comment]
> > > @Sneezry 主要是加了登录鉴权没啥用，我不准备加数据库。
> > 
> > 
> > 你有fork的仓库可以参考一下吗
> 
> SSO 不需要数据库的。https://github.com/Sneezry/Azure-ChatGPT-Next-Web
> 
> 因为我是自己用的，所以我 SSO 做的比较粗糙，没考虑不启用 SSO 时的逻辑。

hey bro， git仓库不可访问了，可否帮我开一下权限，借鉴一下。谢谢。我有增加sso鉴权的需求
