### ISSUE TITLE
本地部署如何配置代理

### ISSUE THREAD

**Issue by huangwenhui123** [Yidadaa/ChatGPT-Next-Web#744]
本地部署如何添加代理

**Comment by qianniu2009** [comment]
> 本地部署如何添加代理

走主机上的代理，ip+端口

**Comment by bingbaicai** [comment]
> > 本地部署如何添加代理
> 
> 走主机上的代理，ip+端口

大佬可以细说么。我在clash里面还需要如何设置

**Comment by whengu** [comment]
我看了代码,在代码层面没有让请求走本地代理,如果你用的clash或v2rayN这样的通用代理服务是不能使用该项目的,该项目的代理需要走一个专用的服务器转发;我现在怀疑这个项目是用来窃取key的,请不要继续使用
