### ISSUE TITLE
[Feature] 关于多api key的负载均衡

### ISSUE THREAD

**Issue by SeddonShen** [Yidadaa/ChatGPT-Next-Web#749]
**这个功能与现有的问题有关吗？**
目前OpenAI大幅限制了免费账户api的访问速度，如果有多个账号多个key进行负载均衡的话，应该能大幅优化目前api的使用体验，请问现在有这种功能吗，未来有实现的打算吗，谢谢！

**Comment by MekaYangyi** [comment]
挺好的一个功能，支持

**Comment by sgr997** [comment]
不怕封号吗

**Comment by SeddonShen** [comment]
> 不怕封号吗

目前免费账户api的速度已经到了基本不能用的程度，最不济就是封号呗。

**Comment by sgr997** [comment]
> > 不怕封号吗
> 
> 目前免费账户api的速度已经到了基本不能用的程度，最不济就是封号呗。

好吧😅

**Comment by leochen12-rgb** [comment]
收费功能，建议联系作者
