### ISSUE TITLE
[Feature] 想知道每天通过此项目的api使用量

### ISSUE THREAD

**Issue by 14790897** [Yidadaa/ChatGPT-Next-Web#752]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
手动去 openai 后台查看。

**Comment by 14790897** [comment]
我api用的免费额度，现在被禁止进入openai的后台了，但是chatgpt网页能访问
![image](https://user-images.githubusercontent.com/121866954/231678988-b17b528e-d3ad-4df5-8005-e2d578a1a0be.png)
