### ISSUE TITLE
[Bug] 输入设定好的密码后仍返回现在是未授权状态

### ISSUE THREAD

**Issue by Montaro2017** [Yidadaa/ChatGPT-Next-Web#753]
**Describe the bug**
在设置里输入密码后回到对话界面，输入文字后返回`现在是未授权状态，请点击左下角设置按钮输入访问密码。`

已设置密码
![image](https://user-images.githubusercontent.com/35142778/231628751-4efa79e5-29cf-4d75-bb4f-35557ef26a95.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/35142778/231628369-d18b096d-a374-4719-9f1e-423612a7cef4.png)

**Deployment**
- [x] Vercel

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**查看Vercel日志**
![image](https://user-images.githubusercontent.com/35142778/231639491-8cb203e7-f996-45ef-b48a-39b50303c393.png)

**Comment by zhaifanhua** [comment]
我也遇到了这个问题，单个密码可以，多个密码访问不了

**Comment by Montaro2017** [comment]
> 

我是设置的单个密码

**Comment by Montaro2017** [comment]
> 我也遇到了这个问题，单个密码可以，多个密码访问不了

我是设置的单个密码

**Comment by zhaifanhua** [comment]
单个密码的话，你清一下缓存或者换个浏览器环境试试呢？

**Comment by libaxuan** [comment]
请问 我设置了环境变量CODE，访问密码是这种格式code,code,code 为什么在不输入访问密码的时候也可以使用，只要有key 就可以访问 如何解决这个问题，我不想让所有人访问我的域名&nbsp;


1107590384
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 上午10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [Yidadaa/ChatGPT-Next-Web] [Bug] 输入设定好的密码后仍返回现在是未授权状态 (Issue #753)





 
单个密码的话，你清一下缓存或者换个浏览器环境试试呢？

**Comment by Yidadaa** [comment]
@libaxuan 需要重新部署：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2

**Comment by libaxuan** [comment]
@Yidadaa 我在部署是配置了CODE 可是访问控制仍然不生效，部署过两次了&nbsp;



1107590384
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yidadaa/ChatGPT-Next-Web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 上午10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yidadaa/ChatGPT-Next-Web] [Bug] 输入设定好的密码后仍返回现在是未授权状态 (Issue #753)





 
@libaxuan 需要重新部署：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2

**Comment by zhaifanhua** [comment]
@Montaro2017 我重新部署后可以了

**Comment by Montaro2017** [comment]
> 单个密码的话，你清一下缓存或者换个浏览器环境试试呢？

缓存我都清除了，重新部署了，甚至重新fork项目，重新在vercel上添加项目都是这样

**Comment by Yidadaa** [comment]
@Montaro2017 确实很奇怪，你的 Log 中看到 code 已经匹配成功了，但是后续依然 401 了，你的 OPENAI_API_KEY 确认过能用吗？看一下 OPENAI_API_KEY 环境变量有没有设置正确。

**Comment by Yidadaa** [comment]
@Montaro2017 顺便提供一下浏览器控制台截图，现在猜测是你忘记设置 OPENAI_API_KEY 环境变量了。

**Comment by Montaro2017** [comment]
> @Montaro2017 顺便提供一下浏览器控制台截图，现在猜测是你忘记设置 OPENAI_API_KEY 环境变量了。

解决了，确实是环境变量配置有问题

**Comment by Montaro2017** [comment]
@Yidadaa 我觉得这方面的提示可以完善一下

**Comment by libaxuan** [comment]
@Yidadaa&nbsp;我已经设置了CODE 密码 为什么 访问时候部署入访问密码也能授权 测试过单密码 3密码 2逗号形式 都重新部署了 仍然可以任意访问
&nbsp;


1107590384
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 中午11:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Yidadaa/ChatGPT-Next-Web] [Bug] 输入设定好的密码后仍返回现在是未授权状态 (Issue #753)





 
@Yidadaa 我觉得这方面的提示可以完善一下

**Comment by libaxuan** [comment]
@Yidadaa&nbsp;我已经设置了CODE 密码 为什么 访问时候不输入访问密码也能授权使用
&nbsp;测试过单密码或者 3密码 2逗号形式 都重新部署了 仍然不输入密码情况下可以任意访问
&nbsp; 无痕模式 清理过浏览器


1107590384
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 中午11:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Yidadaa/ChatGPT-Next-Web] [Bug] 输入设定好的密码后仍返回现在是未授权状态 (Issue #753)





 
@Yidadaa 我觉得这方面的提示可以完善一下

**Comment by dqzboy** [comment]
我也是这个问题，日志显示没问题 就是一直提示未授权，直接输入API是没问题的；部署方式是手动构建部署的
![image](https://user-images.githubusercontent.com/42825450/232279282-989c1288-47d6-4822-a40d-d5463e926ebc.png)

**Comment by dqzboy** [comment]
> 我也是这个问题，日志显示没问题 就是一直提示未授权，直接输入API是没问题的；部署方式是手动构建部署的 ![image](https://user-images.githubusercontent.com/42825450/232279282-989c1288-47d6-4822-a40d-d5463e926ebc.png)

可以了，原来是 OPENAI_API_KEY=$OPENAI_API_KEY CODE=$CODE PORT=$PORT 这几个变量名称不能变 哈哈

**Comment by imldy** [comment]
> @Montaro2017 确实很奇怪，你的 Log 中看到 code 已经匹配成功了，但是后续依然 401 了，你的 OPENAI_API_KEY 确认过能用吗？看一下 OPENAI_API_KEY 环境变量有没有设置正确。

我也遇到这个情况了。
确实是因为key无效，OpenAI_API会返回401状态码，后端将401返回给前端，前端误以为是`ChatGPT-Next-Web`的访问密码错误所报的401。

总结来说就是401状态码语义不清晰。

**Comment by d1y6** [comment]
我用5个vercel部署，其中有3个发生了同样的问题，设置的密码无法登录，重新部署很多次都不行。奇怪的是，另外的2个密码可以登录，内置的KEY都是100%有效
