### ISSUE TITLE
OpenAI API只能通过HTTPS访问。 您应该访问https://api.openai.com而不是当前的URL

### ISSUE THREAD

**Issue by ieasyseek** [Yidadaa/ChatGPT-Next-Web#758]
部署完成后出现以下错误提示：
{
  "error": {
    "message": "The OpenAI API can only be accessed over HTTPS. You should access https://api.openai.com rather than the current URL.",
    "type": "invalid_request_error"
  }
}

这是哪里问题？

变量 PROTOCOL   Values: https

BASE_URL：https://x.xxx.com  cf中转自己的域名，

**Comment by Montaro2017** [comment]
BASE_URL不要加https

**Comment by ieasyseek** [comment]
已经在 vercel 更改了 BASE_URL  x.xx.com
之前一直没问题从昨天同步更新仓库后就出现这问题！

PROTOCOL 写 https  这个没有问题吧？

**Comment by Montaro2017** [comment]
> 已经在 vercel 更改了 BASE_URL x.xx.com 之前一直没问题从昨天同步更新仓库后就出现这问题！
> 
> PROTOCOL 写 https 这个没有问题吧？

重新部署试试

**Comment by ieasyseek** [comment]
重新部署可以了。感谢。
