### ISSUE TITLE
请问大佬一下，为啥我默认3.5，但是我提问它却说自己是gpt2，我在官方chatgpt中同样问题，它却回答是3.5

### ISSUE THREAD

**Issue by rookie-LiMr** [Yidadaa/ChatGPT-Next-Web#759]

**Comment by zhujunsan** [comment]
不要相信他的回答...他只是补全你的文本...你去看OpenAI后台调用统计里使用的模型就好了...

**Comment by rookie-LiMr** [comment]
> 不要相信他的回答...他只是补全你的文本...你去看OpenAI后台调用统计里使用的模型就好了...

![Screenshot_2023-04-13-14-08-30-392_com.android.chrome.jpg](https://user-images.githubusercontent.com/58675312/231668735-a33a2fad-5bf6-4c77-bf62-0773bf3618dc.jpg)

大佬后台调用统计里没有看到呀？在哪？

**Comment by rookie-LiMr** [comment]
> 不要相信他的回答...他只是补全你的文本...你去看OpenAI后台调用统计里使用的模型就好了...

找到了感谢感谢，但是我选的是3.5turbo它显示为3.5turbo-0301，不过不碍事，有点稍微奇怪可能是官方调用没有区分吧![Screenshot_2023-04-13-14-14-09-756_com.android.chrome.jpg](https://user-images.githubusercontent.com/58675312/231670300-e2d17845-7a6c-45c5-a4cf-b0753f1486b0.jpg)

**Comment by sadness229** [comment]
为什么我的邮箱一直收到信息

**Comment by rookie-LiMr** [comment]
> 你有空了可以看文档，因为模型可能更新，3.5turbo默认使用最新的该系列的模型，目前是最新的版本号是0301（目前也只有这一个），之后有新的就会用更新版的

感谢大佬，我是应该提前自己去仔细看一下，我大概看了一下没太注意到，不过实在感谢了

**Comment by rookie-LiMr** [comment]
> 你有空了可以看文档，因为模型可能更新，3.5turbo默认使用最新的该系列的模型，目前是最新的版本号是0301（目前也只有这一个），之后有新的就会用更新版的

感谢大佬，我是应该提前自己去仔细看一下，我大概看了一下没太注意到，不过实在感谢
