### ISSUE TITLE
[Bug] Encountered errors in dialogue after deployment

### ISSUE THREAD

**Issue by Geidorf** [Yidadaa/ChatGPT-Next-Web#765]
{
  "error": {
    "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}

**Comment by Yidadaa** [comment]
Have you set `BASE_URL`? What did you set?

**Comment by xingli12** [comment]
![IMG_7322](https://user-images.githubusercontent.com/39153914/231847338-82fc7a48-095e-417d-9a8e-934a1ef0c415.jpeg)
like this

**Comment by kanrun** [comment]
Me too

**Comment by xingli12** [comment]
你好，Email我已收到。

**Comment by Yidadaa** [comment]
确认你的 BASE_URL 是否格式正确，请附上打码了关键信息后的 BASE_URL 信息。

**Comment by xingli12** [comment]
> { "error": { "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?", "type": "invalid_request_error", "param": "model", "code": null } }

Your API key is not valid, just change a key and it will work.

**Comment by Geidorf** [comment]
{
  "error": {
    "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}


> BASE_URL

I haven't set any BASE_URL, and even if I set the BASE_URL to https://api.openai.com/, I still have this issue.

**Comment by Geidorf** [comment]
> > { "error": { "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?", "type": "invalid_request_error", "param": "model", "code": null } }
> 
> Your API key is not valid, just change a key and it will work.
I have tried changing the API key, but it doesn't help.
