### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wangllxxxx** [Yidadaa/ChatGPT-Next-Web#766]
启动后对话出错

状态：
设置key、code

启动后显示未授权，输入code后开始对话，但是对话失败，后台没有日志
试过docker部署、脚本部署、服务器代码部署

![1681377467871](https://user-images.githubusercontent.com/122505992/231714400-8d5305ad-acb6-4061-bc6e-8df7a3f9d35c.png)

**Comment by iiiok** [comment]
I encounter similar issue too.
The response works occasionally, but get the time-out error in most cases.
and my API-key works well in my other App, also deployed to Netlify.

**Comment by Kosette** [comment]
是没有绑定信用卡的免费版api吗？可能是openai的rate limits限制，最近免费版api返回的时间长达~10s，很有可能导致超时，目前chatgpt-next-web好像还没有超时时间设置。

**Comment by wangllxxxx** [comment]
> 是没有绑定信用卡的免费版api吗？可能是openai的rate limits限制，最近免费版api返回的时间长达~10s，很有可能导致超时，目前chatgpt-next-web好像还没有超时时间设置。

这个key是plus的，应该不是这个问题吧，而且这个错基本是秒出。

**Comment by Yidadaa** [comment]
@iiiok 

Do not deploy to netlify, it does not support SSE (streaming response), which will cause time out error.

**Comment by Yidadaa** [comment]
@wangllxxxx 

请提供一下浏览器控制台报错截图，以及浏览器 network 选项卡截图。

**Comment by wangllxxxx** [comment]
> @wangllxxxx
> 
> 请提供一下浏览器控制台报错截图，以及浏览器 network 选项卡截图。

@Yidadaa 刚看了下，404了，另外这个为啥请求有remote address
![1681440858339](https://user-images.githubusercontent.com/122505992/231929714-88298d8d-273c-4c45-a6bb-67caef2f95b7.png)
