### ISSUE TITLE
[Bug] You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by LxzBUG** [Yidadaa/ChatGPT-Next-Web#767]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
You exceeded your current quota, please check your plan and billing details.

**如何复现**
随便发信息

**截图**

**一些必要的信息**
 - 系统：macos 12
 - 浏览器：chrome
 - 版本： 最新
 - 部署方式： vercel
 
 我去后台看了，还有额度，基本没用

**Comment by RobKing9** [comment]
老哥怎么解决的呀
