### ISSUE TITLE
[Bug] 优化未授权的提示文案

### ISSUE THREAD

**Issue by Kosette** [Yidadaa/ChatGPT-Next-Web#768]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
1. 在移动版布局下，未授权提示为“现在是未授权状态，请点击**左下角设置**按钮输入访问密码”，因为移动版页面布局和桌面布局不同，边栏是隐藏的，会话界面左下角并不存在设置按钮，需要先点击上方的返回，再点击左下角的设置按钮。
2. 此外，该提示在不同语言设置时并不一致，简体中文和日文提示到“左下角”，但繁体中文，英文并未明确提示“左下角”。
3. 建议对提示文案进行优化，针对不同版本的布局。

**如何复现**
以未授权状态访问移动版页面

**截图**
未附加

**一些必要的信息**
- 浏览器：Safari
- 系统：iOS 16

**Comment by Yidadaa** [comment]
#741 之后会改成这样。
