### ISSUE TITLE
是否可以使用 ChatGPT 网页端 API (accessToken) 而不是官方 API？

### ISSUE THREAD

**Issue by Root-FTW** [Yidadaa/ChatGPT-Next-Web#77]
是否可以使用我的chatgpt plus账户的会话令牌而不是api？

**Comment by ruixing1001** [comment]
这个是否有封号风险

**Comment by GH-wudi** [comment]
> 这个是否有封号风险
vervel上直连的情况下没有吧

**Comment by GH-wudi** [comment]
> 这个是否有封号风险

vervel上直连的情况下没有吧

**Comment by AprilNEA** [comment]
使用逆向工程是否违反 OpenAI 的 ToS？

**Comment by HenMie** [comment]
挺多项目有类似的功能，目前来看的话，都能正常使用。

**Comment by Yidadaa** [comment]
https://github.com/transitive-bullshit/chatgpt-api#usage---chatgptunofficialproxyapi

需要考虑下列问题：
1. 能否在 edge function 上运行
2. 是否支持 stream 传输

**Comment by Yidadaa** [comment]
鉴于目前 OpenAI 严格的封号政策，不考虑增加此功能。

**Comment by hyh1750522171** [comment]
好的我知道了，谢谢大佬，这个是有封号风险的。
