### ISSUE TITLE
[Bug] Docker Compose 部署后一些域名无法解析

### ISSUE THREAD

**Issue by GF-Huang** [Yidadaa/ChatGPT-Next-Web#773]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4510984/231785336-dfa37d9a-7205-4f26-a911-bf7ad90d89ec.png)

![image](https://user-images.githubusercontent.com/4510984/231786634-090a1f73-6fca-47f0-bbab-48eb1bf70f89.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: 树莓派 4B，debian 11

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
没看懂你想表达什么，这和本项目有什么关系？

**Comment by GF-Huang** [comment]
> 没看懂你想表达什么，这和本项目有什么关系？

部署后使用时产生 `ConnectTimeoutError`，正如上述，进入容器后发现 DNS 解析出问题，没有头绪如何排错。

![image](https://user-images.githubusercontent.com/4510984/231823756-a9aebbda-d2bc-4b8a-8bcc-11ce4edc0fd7.png)

**Comment by Yidadaa** [comment]
你的主机能直连外网吗？如果有代理，请参考说明文档传入 PROXY_URL

**Comment by GF-Huang** [comment]
主机肯定是正常的，装了 [v2raya](https://v2raya.org/) 和 [ufw-docker](https://github.com/chaifeng/ufw-docker)，所以情况有点复杂。

没太看懂这个错误意味着什么。

![image](https://user-images.githubusercontent.com/4510984/231827543-77537068-db86-4849-882a-84c83b5dff85.png)

**Comment by GF-Huang** [comment]
确认了是 `ufw-docker` 的 iptables 规则冲突，谢谢。
