### ISSUE TITLE
[Feature] 增加删除最后一次用户发言和GPT回复内容的功能

### ISSUE THREAD

**Issue by cn-qinqi** [Yidadaa/ChatGPT-Next-Web#777]
有时候提问的话术有问题导致GPT回答的不够理想，再次进行提问则会把存在问题的话术和回复也一起发送，继续导致GPT回复不理想，希望增加删除最后一次用户发言和GPT回复内容的功能

**Comment by Yidadaa** [comment]
关注 #539
