### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nljie1183** [Yidadaa/ChatGPT-Next-Web#778]
![IMG_20230414_001613](https://user-images.githubusercontent.com/59471244/231822781-e37a9246-0b0f-4633-9b89-5218b71bcbda.jpg)
为什么这个一直报错，是出什么问题了吗
![IMG_20230414_001634](https://user-images.githubusercontent.com/59471244/231822861-6dd69ea1-052b-4a6f-98db-e37f0d1c1e06.jpg)

**Comment by nljie1183** [comment]
这个怎么解决啊，作者求解

**Comment by Yidadaa** [comment]
手动更新代码，点 sync fork
