### ISSUE TITLE
[Bug] 手机上的触摸 BUG

### ISSUE THREAD

**Issue by GF-Huang** [Yidadaa/ChatGPT-Next-Web#779]
**Describe the bug**

当键盘弹出时，点击上方空白位置试图收起键盘时，会误触到 “返回” 按钮，导致意外的返回到 “聊天列表”。有时也会误触到 “设置上下文” 按钮，具体看手指点到哪个位置。

视频中移动的 “白点” 代表我的手指触摸了屏幕的具体位置（如果不使用这种方式，观看者无法得知录屏者触摸了屏幕哪个位置），具体看以下视频：

https://user-images.githubusercontent.com/4510984/231845274-060fb545-c679-4785-a7eb-b4886c04a8ce.mp4

**Expected behavior**

不会产生误触行为。

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Smartphone (please complete the following information):**
 - Device: `iPhone6S`
 - OS: `iOS 15.7.5`
 - Browser `Safari`

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
Safari 为会为苹果所谓的 a11y 做很多“额外”的工作，我不准备为苹果的小癖好买单，建议你在收起键盘的时候尽量点击靠近输入框的区域，来避免误触。
