### ISSUE TITLE
关于完善api错误种类提示的建议

### ISSUE THREAD

**Issue by ruixing1001** [Yidadaa/ChatGPT-Next-Web#78]
目前不管是什么错误提示词都一样，还得排查是什么原因，出错后可否加入类似以下的提示，方便用户快速判断。                   
  case "invalid_api_key":
                        layer.msg("API-KEY不合法");
                        break;
                    case "context_length_exceeded":
                        layer.msg("问题和上下文长度超限，请重新提问");
                        break;
                    case "rate_limit_reached":
                        layer.msg("同时访问用户过多，请稍后再试");
                        break;
                    case "access_terminated":
                        layer.msg("违规使用，API-KEY被封禁");
                        break;
                    case "no_api_key":
                        layer.msg("未提供API-KEY");
                        break;
                    case "insufficient_quota":
                        layer.msg("API-KEY余额不足");
                        break;
                    case "account_deactivated":
                        layer.msg("账户已禁用");
                        break;
                    case "model_overloaded":
                        layer.msg("OpenAI模型超负荷，请重新发起请求");
                        break;
                    case null:
                        layer.msg("OpenAI服务器访问超时或未知类型错误");
                        break;
                    default:
                        layer.msg("OpenAI服务器故障，错误类型：" + errcode);

**Comment by Yidadaa** [comment]
优先级较低，排到 prompt 列表之后吧。

**Comment by Yidadaa** [comment]
已增加网页端错误内容提示。
