### ISSUE TITLE
[Feature] 增加对text-davinci-003模型的支持

### ISSUE THREAD

**Issue by zhangever** [Yidadaa/ChatGPT-Next-Web#780]
**这个功能与现有的问题有关吗？**
目前普通的openAi账号， 对gpt-3.5-turbo模型的限速越来越厉害了，直至压根无法忍受的龟速:
`{
    "error": {
        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-XXXXXXX on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
        "type": "requests",
        "param": null,
        "code": null
    }
}`
而`text-davinci-003`效果上更好，当然价格上贵10倍。 但是可用性还是第一位吧？

**你想要什么功能或者有什么建议？**
希望能支持`text-davinci-003`模型

**其他信息**
价格上贵10倍，但是还能接受，而且效果更好

**Comment by Yidadaa** [comment]
`text-davinci-003` 不是为对话设计，两个 api 的使用体验完全不同。我建议花点钱去绑个信用卡，两三百块就能搞定。

<img width="808" alt="image" src="https://user-images.githubusercontent.com/16968934/231928619-305f825e-7bfa-4d83-a52e-f8f6c5e10aae.png">
