### ISSUE TITLE
[Feature] 提示词通过上下方向键选择

### ISSUE THREAD

**Issue by Montaro2017** [Yidadaa/ChatGPT-Next-Web#782]
通过输入`/`可以触发提示词，但是需要使用鼠标去选择
建议增加上下方向键选择功能

![image](https://user-images.githubusercontent.com/35142778/231920096-9871dc43-518a-43d9-82f6-ea6cf17ed2aa.png)

**Comment by zb2947244682** [comment]
要求这么高的吗？
