### ISSUE TITLE
[Bug] 使用第三方api request base url，回答结束后仍处于“正在输入”状态，并最终出现“出错了，稍后重试吧”提示

### ISSUE THREAD

**Issue by lwd-temp** [Yidadaa/ChatGPT-Next-Web#783]
**Describe the bug**
使用第三方api request base url，回答结束后仍处于“正在输入”状态，并最终出现“出错了，稍后重试吧”提示

**To Reproduce**
1. 环境变量使用第三方api request base url，配置key
2. 输入“你好”
3. 回复出现“你好！有什么我可以帮助你的吗？“，但在这句话输出结束后仍提示“正在输入”
4. 等待超时，在“你好！有什么我可以帮助你的吗？“回复后出现“出错了，稍后重试吧”

**Expected behavior**
在有输出回复内容的情况下，无论是否超时，不判定为出错。（或者可选设置）

**Screenshots**
![image](https://user-images.githubusercontent.com/26019675/231930773-2a5f4e8f-9622-4556-912c-1b05f9f10482.png)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.
![image](https://user-images.githubusercontent.com/26019675/231931080-6c746eb0-2073-478f-b3e8-9bb820f17c7e.png)
![image](https://user-images.githubusercontent.com/26019675/231931119-9800697e-7860-41da-b561-968743ca556b.png)

**Comment by yinm0591** [comment]
估计是第三方api的问题。可能是调用/v1/chat/completions后，第三方api回传数据没有加Content-Length头部信息。
