### ISSUE TITLE
希望头像与内容在同一行

### ISSUE THREAD

**Issue by gexiaopeng** [Yidadaa/ChatGPT-Next-Web#788]
希望后续版本能优化一下，让头像与内容在同一行，理由：
1）同一行可以节约空间
2）几乎其他所有的聊天软件界面，头像与内容是在同一行，这样看上去更美观。

如果以后可以个性化设置那更好了。

**Comment by Yidadaa** [comment]
个人喜好问题，你可以自行修改源码来满足自己的需求。

**Comment by gexiaopeng** [comment]
> 个人喜好问题，你可以自行修改源码来满足自己的需求。

我是初学者，请问用什么开发工具可以修改源码？谢谢！
