### ISSUE TITLE
[提问]  请问历史记忆功能怎么使用

### ISSUE THREAD

**Issue by AmossXu** [Yidadaa/ChatGPT-Next-Web#792]
**描述问题**
请问历史记忆功能怎么使用，目前进去都是空的 0 of n 没有数据，也无法操作

**截图**

![image](https://user-images.githubusercontent.com/29244256/231957755-d4a33ab8-7cc2-4756-a7db-99d713ebf6e1.png)

**Comment by Yidadaa** [comment]
这是自动触发的功能，只要当你们的聊天字数触发了压缩阈值的时候，才会总结为历史记忆，大多数时间你不用管他。

**Comment by AmossXu** [comment]
> 这是自动触发的功能，只要当你们的聊天字数触发了压缩阈值的时候，才会总结为历史记忆，大多数时间你不用管他。

感谢回复，  这个功能感觉比较不直观，一般用户进来没法知道它是干啥的

**Comment by WingCH** [comment]
同意，不太直觀
