### ISSUE TITLE
[反馈问题] What is this error message? How to handle it?

### ISSUE THREAD

**Issue by Jialinvip** [Yidadaa/ChatGPT-Next-Web#793]
{
    "error": {
        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-C92hO32J0AGzGOmHi6JKDVk2 on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
        "type": "requests",
        "param": null,
        "code": null
    }
}

What is this error message? How to handle it?

**Comment by Yidadaa** [comment]
openai 限制了免费账号的访问频率，现在只允许免费账号每分钟访问 3 次。
