### ISSUE TITLE
同一段会话内容一长，回答的的结果乱七八糟，官方接口里面没有返回会话id吧？

### ISSUE THREAD

**Issue by stacklesshaha** [Yidadaa/ChatGPT-Next-Web#798]
![mmexport1681456230505](https://user-images.githubusercontent.com/35445580/231970476-9e415c51-46cd-4540-8992-dfece8f3ab2d.png)

[官方会话接口不支持会话id](https://community.openai.com/t/conversation-id/33270/3)

**Comment by stacklesshaha** [comment]
会话内容一长，后面的回答都是错的，前提概要完全都忘记了，还没有在官方web聊天窗口里面免费的gpt3回答的好，api这种形式感觉是在浪费token😂

**Comment by Corwin006** [comment]
实际上，官方免费的ChatGPT，在大量文本对话的情况下，我感觉也会丢失前面的会话内容。经过几轮对话后，给我重新生成了一段内容，我前面提的要求都扔了🤣
本来期望他帮我写一个方案的，结果浪费感情，后来还是我自己写的。
我不知道网上号称用这个写文章的，是怎么实现的...

**Comment by stacklesshaha** [comment]
> 
我也很奇怪，官方接口为什么不返回会话id :）

**Comment by StereoApp** [comment]
如果有回话ID的话，回话内容就要存储在OpenAI的服务器上，再加上存取的逻辑，OpenAI得投入很多成本

**Comment by stacklesshaha** [comment]
> 如果有回话ID的话，回话内容就要存储在OpenAI的服务器上，再加上存取的逻辑，OpenAI得投入很多成本

实际上官方自己的web聊天窗口支持会话id，就api key 的接口不支持

**Comment by stacklesshaha** [comment]
> 如果有回话ID的话，回话内容就要存储在OpenAI的服务器上，再加上存取的逻辑，OpenAI得投入很多成本

实际上官方自己的web聊天窗口支持会话id，就api key 的接口不支持，哭
![企业微信截图_16814598773434](https://user-images.githubusercontent.com/35445580/231985310-b3d4cd70-fc50-489c-9339-d26b32ea8bb6.png)

**Comment by stacklesshaha** [comment]
> 实际上，官方免费的ChatGPT，在大量文本对话的情况下，我感觉也会丢失前面的会话内容。经过几轮对话后，给我重新生成了一段内容，我前面提的要求都扔了🤣 本来期望他帮我写一个方案的，结果浪费感情，后来还是我自己写的。 我不知道网上号称用这个写文章的，是怎么实现的...

是的

**Comment by Corwin006** [comment]
为何不提供会话ID，可以参考我另一个讨论里的回复，这是我的理解：
https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/791#discussioncomment-5612884

简而言之，我的理解是：
OpenAI 开放API接口的目的，不是为了让别人开发一个聊天软件和ChatGPT做竞品⚔的，会话ID是ChatGPT才需要的功能。
你开发的软件不应该需要会话ID。🤣

**Comment by Yidadaa** [comment]
OpenAI 不会放开这个功能的。
