### ISSUE TITLE
请求增加重试按钮

### ISSUE THREAD

**Issue by Nplace-su** [Yidadaa/ChatGPT-Next-Web#8]
尊敬的开发者，

首先，我要感谢您对这个开源项目的贡献和辛勤工作。在使用这个项目的过程中，我遇到了一些问题，希望您能给予帮助。

我发现，在某些情况下，请求可能会因超时而失败。这导致我需要重新复制粘贴对话。因此，我想提出一个建议，即在项目中报错时添加一个重试按钮。这将使用户能够轻松地重新发起请求，从而减少了不必要的麻烦。

如果您能够考虑我的建议并加入这个功能，我会非常感激。我相信，这将使项目更加完善和易于使用。再次感谢您的努力和贡献。期待您的回复。

谢谢！
![image](https://user-images.githubusercontent.com/105898543/227241844-6b635064-7194-4f04-9729-35b5ac9caed5.png)

**Comment by Yidadaa** [comment]
已在 v1.3 版本中增加该功能。
