### ISSUE TITLE
[希望在前端可自定义或选择字体大小及其它功能] 

### ISSUE THREAD

**Issue by lkbgct** [Yidadaa/ChatGPT-Next-Web#808]
1、希望在前端可自定义或选择字体大小，目前好像在app.ts中定义为14号大小，因为有时候在大屏电视上用，字体太小看不清。
2、绕过数据监管，太政治正确，过于道德的聊天场景感觉还是冷冰的机器，靠prompt似乎阻挡不了它努力逼近openai设定的规则。见：
  https://zhuanlan.zhihu.com/p/591003498
  https://github.com/bigemon/ChatGPT-ToolBox
3、vercel有类似CF 的KV 空间功能吗，将部分在前端实现的功能移到后端，是否有助于提升响应速度？类似telegram bot的实现，感觉是所有chatGPT应用方法中响应速度最快的，不知是利用了CF KV的原因，还是TG服务器快？见：
  https://github.com/TBXark/ChatGPT-Telegram-Workers

**Comment by LumenYoung** [comment]
README.md 里面提到了，不会开发字体大小。

**Comment by lkbgct** [comment]
哦，没留意，或者检测屏幕分辨率、大小来自适应？

**Comment by Yidadaa** [comment]
设置里可以调整消息字体大小：

![image](https://user-images.githubusercontent.com/16968934/232123099-3d690186-5e83-4a06-b3fe-2d5af51bc9fc.png)

**Comment by lkbgct** [comment]
谢谢回复，我居然提了这么弱智的问题，浪费大神时间，抱歉！
