### ISSUE TITLE
[支持]建议作者加一下log，统计访问的time、IP和token 支持

### ISSUE THREAD

**Issue by eternalpal** [Yidadaa/ChatGPT-Next-Web#813]
建议作者加一下log，统计访问的time、IP和token

_Originally posted by @leochen12-rgb in https://github.com/Yidadaa/ChatGPT-Next-Web/issues/518#issuecomment-1498382736_

**Comment by Jialinvip** [comment]
是的，我也认为很有必要，想知道有哪个IP在恶意的刷token，这样可以禁止那个IP

**Comment by Yidadaa** [comment]
你可以提一个 pr，在 middleware 中把 ip 打出来
