### ISSUE TITLE
[Feature] 增加Plugin支持以设置Google Search

### ISSUE THREAD

**Issue by vicacheung** [Yidadaa/ChatGPT-Next-Web#815]
**这个功能与现有的问题有关吗？**
无

**你想要什么功能或者有什么建议？**
可以支持设置Google Search Plugin吗？

**有没有可以参考的同类竞品？**
[Chatbot UI](https://github.com/mckaywrigley/chatbot-ui)

**其他信息**
无

**Comment by Yidadaa** [comment]
#165 关注

**Comment by lloydzhou** [comment]
v2.15.0 支持以插件的形式联网
参考这个示例：
https://github.com/ChatGPTNextWeb/NextChat-Awesome-Plugins/tree/main/plugins/duckduckgolite
