### ISSUE TITLE
[Bug] 代码没有缩进

### ISSUE THREAD

**Issue by lookfeeb** [Yidadaa/ChatGPT-Next-Web#816]
![1](https://user-images.githubusercontent.com/57110414/232181028-6b56f4cb-5f36-4f0e-88a7-b4f6850f0b24.png)
![2](https://user-images.githubusercontent.com/57110414/232181032-31eb200f-a44b-4de4-aba5-2cbe73a24f21.png)
将我们的代码复制在输入框时有缩进，但是发送给bot后就出现了两张图的情况

**Comment by Yidadaa** [comment]
你需要用 markdown 的代码块语法裹起来，你可以问问 chatgpt。
