### ISSUE TITLE
[Feature] "滑动底部按钮"的位置以及UI的改进建议

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#817]
**这个功能与现有的问题有关吗？**
/

**你想要什么功能或者有什么建议？**
建议把这个按钮移动到这里，放在那里很容易当成下载按钮，图标也需要换一个。
![image](https://user-images.githubusercontent.com/48620527/232181226-d2c68519-2b70-4c6d-ac0e-c44f7d6d5233.png)

是不是可以给每个按钮加一个类似这种的提示，这样无需点击就能知道按钮是干嘛的，对首次使用的人友好。
![image](https://user-images.githubusercontent.com/48620527/232181326-9b6f0fe1-8bdc-44a8-96f4-72b0b3ea901b.png)

还有这个弹窗，感觉改成跟导出聊天记录那种弹窗的UI，更统一点。
![image](https://user-images.githubusercontent.com/48620527/232181258-a0a8c32d-1a25-4c38-82d6-05baa82e88b9.png)

**有没有可以参考的同类竞品？**
/

**其他信息**
/

**Comment by Yidadaa** [comment]
#839
