### ISSUE TITLE
在哪里可以设置base URL？

### ISSUE THREAD

**Issue by mikaizhu** [Yidadaa/ChatGPT-Next-Web#821]

**Comment by Yidadaa** [comment]
环境变量。

**Comment by mikaizhu** [comment]
> 环境变量。

没有找到环境变量中有base URL，只发现了code和api key两个变量

**Comment by Yidadaa** [comment]
有没有一种可能，你需要手动新增一个？https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%94%B9%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by Yidadaa** [comment]
找找环境变量的 add 按钮，加一个 BASE_URL，然后重新部署一下就生效了。顺便如果你是在 vercel 部署，你应该不需要改动 BASE_URL；如果你是在本地部署，你应该仿照 docker 命令用 `-e BASE_URL=xxx` 来传入新变量。
