### ISSUE TITLE
[Feature] 主题设置似乎没有必要放在对话页面

### ISSUE THREAD

**Issue by RogerProSelf** [Yidadaa/ChatGPT-Next-Web#823]
主题设置似乎没有必要放在对话页面，可以放置本对话的模型设置、历史prompt数量设置、token消耗预览等功能。
感觉主题大部分时候都是开auto也不会去管，没必要在对话页面增加使用学习和视觉成本。
个人看法，供参考，作者加油！

**Comment by Yidadaa** [comment]
建议你和他打一架：https://github.com/Yidadaa/ChatGPT-Next-Web/issues/46#issuecomment-1503050616
