### ISSUE TITLE
请教一下, vue3+ts .  文本输入输出 支持代码和链接怎么处理的啊,用的linkifyjs 好像不大对劲,  百度没找到案例, 

### ISSUE THREAD

**Issue by etodong** [Yidadaa/ChatGPT-Next-Web#825]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Yidadaa** [comment]
这和此项目有什么关系？
