### ISSUE TITLE
[Bug] 键入 “/” 后触发Prompt显示层，最顶层多出一个空元素

### ISSUE THREAD

**Issue by CharleeWa** [Yidadaa/ChatGPT-Next-Web#829]
**Describe the bug**
对话框，键入“/” 触发Prompt显示层，最顶层多出一个Item

**Screenshots**

<img width="1283" alt="" src="https://user-images.githubusercontent.com/22477554/232229714-8e12f74d-9b5a-4330-b7ee-75a954071fcf.png">

<img width="1283" alt="" src="https://user-images.githubusercontent.com/22477554/232229720-99bbe0d5-6559-4b1b-9593-8d06ab2102b9.png">

**Comment by Yidadaa** [comment]
图一正常，样式 bug，图二怎么触发的？

**Comment by CharleeWa** [comment]
> 图一正常，样式 bug，图二怎么触发的？

点击这个空元素触发的
