### ISSUE TITLE
[Bug] Please upgrade Next.js to the latest version

### ISSUE THREAD

**Issue by lzm0** [Yidadaa/ChatGPT-Next-Web#832]
My deployment Throws `Illegal invocation` when calling `.text()` on the request body. This is a known bug in Vercel and Next.js and has been fixed in the latest stable release. Please upgrade to `^13.3.0`.

Reference:
https://github.com/vercel/next.js/issues/46337

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by mikuh** [comment]
原来我前几天花了好几个小时才解决的只有在 Vercel上才出现的Illegal invocation问题是next.js自身的bug  >_<
