### ISSUE TITLE
运行一直爆代码[Bug] 

### ISSUE THREAD

**Issue by HHHHHONORG** [Yidadaa/ChatGPT-Next-Web#840]
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
如上

**Comment by Yidadaa** [comment]
经典不看文档：https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E4%BD%BF%E7%94%A8%E6%97%B6%E6%8F%90%E7%A4%BAyou-exceeded-your-current-quota-

**Comment by Augsst** [comment]
设置里显示还有余额，为什么这里提示余额不足呢
