### ISSUE TITLE
[Feature] 希望能开关右击自动复制粘贴到输入框的功能

### ISSUE THREAD

**Issue by longhuan1999** [Yidadaa/ChatGPT-Next-Web#845]
有时候需要复制之前对话的部分内页时，如果忘记使用快捷键而是右击的话会将右击的内容自动复制粘贴到输入框并且覆盖掉已经输入的内容。
虽然可以使用快捷键避免，但实际使用过程中会有下意识右击的情况，如果输入框有码了很久或者很多的内容会比较让人崩溃。虽然这种情况不常有，但还是希望增加开关此功能的设置。
此外，虽然不影响使用，但所有对话共用一个输入框不太符合我的使用习惯，也就是输入框输入的内容在切换对话的时候仅保留在对应对话下的输入框而不是在所有对话中出现。希望能对此做出修改或者做成设置。

**Comment by Yidadaa** [comment]
只有当没有选中任何文本的时候，才会触发复制。

如果你不想自动复制，就先选中你想要复制的文本，再右键点击。

**Comment by longhuan1999** [comment]
> 只有当没有选中任何文本的时候，才会触发复制。
> 
> 如果你不想自动复制，就先选中你想要复制的文本，再右键点击。

好的，谢谢。不过重要的还不是复制的问题，是自动粘贴的问题
