### ISSUE TITLE
[Feature] 请问是否支持 new bing 

### ISSUE THREAD

**Issue by zaiMoe** [Yidadaa/ChatGPT-Next-Web#847]
**你想要什么功能或者有什么建议？**
对于申请通过 new bing，可以用 cookie 进行代理，目前是否支持

**有没有可以参考的同类竞品？**
- https://github.com/chathub-dev/chathub：chrome 插件，不过这种对比形式挺好玩的。
- https://github.com/danny-avila/chatgpt-clone： 逆向工程的代理

**Comment by Yidadaa** [comment]
#165

**Comment by Yidadaa** [comment]
看错了，没有计划支持 new bing，可以去看看其他开源项目。

**Comment by zaiMoe** [comment]
> 看错了，没有计划支持 new bing，可以去看看其他开源项目。

@Yidadaa  问一下，代理 bing cookie 的方案有什么坑吗？ 我可以帮忙开发
