### ISSUE TITLE
希望增加个登录页和数据库，以保存历史记录和设置配置

### ISSUE THREAD

**Issue by ByteVane** [Yidadaa/ChatGPT-Next-Web#848]
可以环境变量里添加用户名和密码，以实现能保存用户的历史记录，以及保存用户的设置配置

**Comment by Yidadaa** [comment]
自己做，本项目不会提供任何账号系统。

**Comment by zhaobudaomingzi** [comment]
> 自己做，本项目不会提供任何账号系统。

这个历史记录我不太会搞，请问大佬可以指导一下吗
