### ISSUE TITLE
[Feature] 需要支持在单个会话内切换gpt模型

### ISSUE THREAD

**Issue by diemus** [Yidadaa/ChatGPT-Next-Web#849]
目前用上了gpt4，但是gpt4太贵了，只是gpt3.5回答的不好的时候用用，但是每次切换模型都需要去设置里去切换，实在是不方便。我看大家没提这个需求，可能是因为很多人还没用上gpt4，体验不是很明显。希望能改一下，类似于openai官网那种，在顶部可以直接选模型

**Comment by Yidadaa** [comment]
#684
