### ISSUE TITLE
[Bug] 应该是作者测试时，用户测试留下的脏数据，需要删除

### ISSUE THREAD

**Issue by critejon** [Yidadaa/ChatGPT-Next-Web#850]
![image](https://user-images.githubusercontent.com/25192892/232328608-5f3a26fa-5aaf-4ce3-913b-2838357e872f.png)
 
文件位置：public/prompts.json

**Comment by Yidadaa** [comment]
来自开源项目：https://github.com/PlexPt/awesome-chatgpt-prompts-zh
