### ISSUE TITLE
[Discussion] max_token 设置选项是否考虑隐藏？

### ISSUE THREAD

**Issue by zychen20** [Yidadaa/ChatGPT-Next-Web#852]
我翻看了一些 issue，也查阅了代码，这个`max_tokens`选项已经没有用了。
作者要不要考虑在设置页面隐藏该选项？

**Comment by Yidadaa** [comment]
留着吧，安慰剂按钮。

**Comment by wslin1994** [comment]
> 留着吧，安慰剂按钮。

请问下什么版本，这个max_tokens还有作用呢？目前需要使用这个参数传递到服务端
