### ISSUE TITLE
[Bug] 自動生成對話標題功能失靈

### ISSUE THREAD

**Issue by jtung4** [Yidadaa/ChatGPT-Next-Web#853]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [X] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [X] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
自動生成對話標題的功能好像失靈，嘗試了en和tw介面也不會自動生成標題

**Comment by Yidadaa** [comment]
为了保证生成质量，只会在你们聊天长度大于一定长度的时候才会触发自动总结，你可以问它一个长问题，比如：总结一下快排

**Comment by jtung4** [comment]
剛剛嘗試了一下，還是不能生成標題。
![IMG_4692](https://user-images.githubusercontent.com/126780548/232366466-caf61e12-2c8c-459f-bf1d-3d64ffbbca08.jpg)

**Comment by Yidadaa** [comment]
fixed
