### ISSUE TITLE
3000 的端口已經被佔用, 無法修改

### ISSUE THREAD

**Issue by fishredleung** [Yidadaa/ChatGPT-Next-Web#856]
3000的端口被其他程式佔用,使用自定的端口無法進入網頁，已經在docker compose 修改端口為8585, 但是查看container 訊息時仍然看到他使用3000 的端口
`e508e44c3f45   yidadaa/chatgpt-next-web             "docker-entrypoint.s…"   17 minutes ago   Up 3 minutes   3000/tcp, 0.0.0.0:8585->8585/tcp`

日志的顥示如下:
`Listening on port 3000 url: http://e508e44c3f45:3000`
有甚麼方法可以更改此程式的佔用端口?

**Comment by Yidadaa** [comment]
你看到的端口是容器内部端口，从你发的日志来看，你是不是用 `docker run -d 8585:8585 xxx` 来启动的 docker，这是错误用法，请使用 `docker run -p [宿主机端口]:[容器端口] [容器名/镜像名]`，正确的的命令是 `docker run -d 8585:3000 xxx`。

**Comment by liuyang77886** [comment]
有办法修改默认的3000端口号吗

**Comment by fishredleung** [comment]
> 有办法修改默认的3000端口号吗

在environment 內加入 PORT=4000 npx next dev, 數字為你的自定義port
