### ISSUE TITLE
Need to fix docker env vars

### ISSUE THREAD

**Issue by Yidadaa** [Yidadaa/ChatGPT-Next-Web#86]
Now we are using a wrong way to get user config from system env vars, which makes it hard to handle env vars correctly in Docker, need to fix it follows this blog: https://raphaelpralat.medium.com/system-environment-variables-in-next-js-with-docker-1f0754e04cde

**Comment by AprilNEA** [comment]
Is the problem now that environment variables are fixed at build time and not read externally at runtime?

**Comment by Yidadaa** [comment]
Right, now we store config to HTML meta fields, and nextjs generates meta data at build time, the build phrase is done before docker publish.

**Comment by lucky13820** [comment]
It would be nice if we can use docker compose to deploy the docker image.

**Comment by hqwuzhaoyi** [comment]
再次问下需要增加什么变量吗，可以描述下吗，我已经在

 #570 

增加了从.env.production获取变量的机制

我们可以沟通下

<img width="669" alt="CleanShot 2023-04-06 at 23 28 00@2x" src="https://user-images.githubusercontent.com/44605072/230426293-b8e97d45-2c5f-489e-9807-98dff8af9fc4.png">


> 是的，现在我们将配置存储到 HTML 元字段，nextjs 在构建时生成元数据，构建阶段在 docker 镜像发布之前完成。

**Comment by Yidadaa** [comment]
done #697
