### ISSUE TITLE
[Bug] 已经订阅ChatGPT plus，但无法使用GPT4类型的模型

### ISSUE THREAD

**Issue by PaperPlaneDeemo** [Yidadaa/ChatGPT-Next-Web#867]
![Snipaste_2023-04-17_14-36-38](https://user-images.githubusercontent.com/26437093/232403755-353c665a-8ff2-488d-948e-fad752d5615b.png)
问题如图

**Comment by Yidadaa** [comment]
为什么不读文档？https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8gpt-4%E7%9A%84api%E8%AE%BF%E9%97%AE

**Comment by PaperPlaneDeemo** [comment]
> 为什么不读文档？https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8gpt-4%E7%9A%84api%E8%AE%BF%E9%97%AE

抱歉，我再详细阅读下
