### ISSUE TITLE
[Bug] 使用Vercel部署以后，输入正确访问密码仍然显示错误，余额无法刷新

### ISSUE THREAD

**Issue by bravohenry** [Yidadaa/ChatGPT-Next-Web#869]
使用Vercel部署以后，输入正确访问密码仍然显示错误，余额无法刷新，CODE的环境变量没有输入错误。API也正确。API输入到网站里面可以使用。

**Comment by Respawn-ID** [comment]
你有没有redeploy

**Comment by bravohenry** [comment]
> 你有没有redeploy

是的，我redeploy了很多遍，过程没有出错，不知道为什么原因，不过我换了账号重新部署了

**Comment by Malayke** [comment]
我也遇到了同样的问题：
1. 最开始没有设置`CODE`，网页告诉我 “未授权状态，请点击左下角设置按钮输入访问密码”
2. 设置CODE环境变量重新这是CODE，还是告诉我 “未授权状态，请点击左下角设置按钮输入访问密码”
3. 已经redeploy好几遍了，还是这样
请问应该怎么解决 @Yidadaa
