### ISSUE TITLE
[Bug] 回答线性代数数学公式无法正常显示

### ISSUE THREAD

**Issue by aahowe** [Yidadaa/ChatGPT-Next-Web#871]
**Describe the bug**
回答线性代数数学公式无法正常显示

**To Reproduce**
问：方程组无解的充分必要条件是什么
答：……
问：那会出现两行全为0，但是对应增广列不为0的情况吗
答：
<img width="735" alt="QQ20230417-153735@2x" src="https://user-images.githubusercontent.com/75622829/232417795-99426920-6e96-410c-b272-32d69ba08093.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Browser Chrome
 - Version 112.0.5615.121（正式版本） (x86_64)

**Comment by Yidadaa** [comment]
重新问一下，让他以 LaTex 格式返回公式。
