### ISSUE TITLE
[Bug] 帮忙看看Upstream Sync 同步失败

### ISSUE THREAD

**Issue by ERCB** [Yidadaa/ChatGPT-Next-Web#872]
已经先fork，然后再创建到vercel中，开始50几次同步正常，后面一直代码同步失败报错
版本：v1.9.7 

![image](https://user-images.githubusercontent.com/2218697/232425735-5f5d11bb-1f5e-486d-aaa7-fc786d93561e.png)

![image](https://user-images.githubusercontent.com/2218697/232424811-e9e63a61-621e-48d2-82bf-381994c856af.png)

![image](https://user-images.githubusercontent.com/2218697/232424688-5b16fbe6-e232-43ef-bcc4-138afe0b7b5d.png)

**Comment by wowpala** [comment]
手动也不行了。

![1](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/43460225/24c1ef05-33a4-418d-8338-85bdf5c6ca5d)
