### ISSUE TITLE
Strict chain  ...  127.0.0.1:1080  ...  api.openai.com:443 <--socket error or timeout!

### ISSUE THREAD

**Issue by pengxianggui** [Yidadaa/ChatGPT-Next-Web#875]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
我是通过docker容器跑的，代理服务是trojan,在本地的1080端口上。使用时，代理一直出现问题。容器日志显示：
> Strict chain  ...  127.0.0.1:1080  ...  api.openai.com:443 <--socket error or timeout!

而trojan日志显示：
> unknown protocol
我查询trojan信息显示，可能需要通过socket来连接，请问是否支持，如何配置？

**截图**
<img width="934" alt="image" src="https://user-images.githubusercontent.com/16299169/232509893-f13a8a88-e109-4e81-8f79-8a7dc1d11538.png">

**Comment by Yidadaa** [comment]
提供一下 PROXY_URL，确认是否是：

```shell
PROXY_URL=socks5://127.0.0.1:1080
```

**Comment by scyuan** [comment]
@bluexiaowei 请问你解决了吗

**Comment by scyuan** [comment]
@forczc 
<img width="729" alt="image" src="https://user-images.githubusercontent.com/20028204/233529411-49b4ae80-1082-493e-abb3-fc66306b95a3.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/20028204/233529530-c574a91f-c789-4e17-8cf1-55305769480f.png">
启动命令
![image](https://user-images.githubusercontent.com/20028204/233529586-5835fbfb-5ee0-42ca-ab30-3fd2b18b26cc.png)
<img width="514" alt="image" src="https://user-images.githubusercontent.com/20028204/233529468-3dac4171-e664-4fa1-9d59-648ef86dbc06.png">

**Comment by forczc** [comment]
> @forczc <img alt="image" width="729" src="https://user-images.githubusercontent.com/20028204/233529411-49b4ae80-1082-493e-abb3-fc66306b95a3.png"> <img alt="image" width="535" src="https://user-images.githubusercontent.com/20028204/233529530-c574a91f-c789-4e17-8cf1-55305769480f.png"> 启动命令 ![image](https://user-images.githubusercontent.com/20028204/233529586-5835fbfb-5ee0-42ca-ab30-3fd2b18b26cc.png) <img alt="image" width="514" src="https://user-images.githubusercontent.com/20028204/233529468-3dac4171-e664-4fa1-9d59-648ef86dbc06.png">

1. 启动命令，proxy那一行上面加多一行：
```
--net=host \
```
2. proxy的url应该是http的proxy，比如你用的应该是clash，proxy应该是"http://127.0.0.1:7890"

**Comment by scyuan** [comment]
> > @forczc <img alt="image" width="729" src="https://user-images.githubusercontent.com/20028204/233529411-49b4ae80-1082-493e-abb3-fc66306b95a3.png"> <img alt="image" width="535" src="https://user-images.githubusercontent.com/20028204/233529530-c574a91f-c789-4e17-8cf1-55305769480f.png"> 启动命令 ![image](https://user-images.githubusercontent.com/20028204/233529586-5835fbfb-5ee0-42ca-ab30-3fd2b18b26cc.png) <img alt="image" width="514" src="https://user-images.githubusercontent.com/20028204/233529468-3dac4171-e664-4fa1-9d59-648ef86dbc06.png">
> 
> 1. 启动命令，proxy那一行上面加多一行：
> 
> ```
> --net=host \
> ```
> 
> 2. proxy的url应该是http的proxy，比如你用的应该是clash，proxy应该是"http://127.0.0.1:7890"

感谢，已解决 👍

**Comment by bluexiaowei** [comment]
已解决
<img width="935" alt="image" src="https://user-images.githubusercontent.com/20636951/233787294-0fa76922-dc0a-4b9e-a78b-17ad81a13e7b.png">
