### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aixinxino** [Yidadaa/ChatGPT-Next-Web#876]
使用新的代码后一直卡在244
![image](https://user-images.githubusercontent.com/100687109/232520694-a478e5a6-b536-4a11-b6a6-7206e27ff6da.png)

**Comment by Yidadaa** [comment]
用 docker 部署。

**Comment by Yidadaa** [comment]
或者：https://juejin.cn/post/6844903889087496200

**Comment by aixinxino** [comment]
事实上之前是因为这个问题
![5A` 4@5Z1}HJ`RUKDQLK$ED](https://user-images.githubusercontent.com/100687109/232524629-dd17aee5-1b85-4b33-baf8-1729dd703f96.png)
在这之后有人告诉我要下载最新的，但是尝试之后反而下载不了了，跟换镜像源也没有用

**Comment by aixinxino** [comment]
我是想构建成静态文件然后查看一些具体实现的操作，感谢你的答复
