### ISSUE TITLE
[Bug] 手机端添加到桌面没有反应

### ISSUE THREAD

**Issue by zhufacai** [Yidadaa/ChatGPT-Next-Web#877]
手机端访问会弹出添加到桌面的提示框，但是点击后并没有添加到桌面。红米k60，miui14

**Comment by chazzhou** [comment]
请在设置里检查你手机浏览器的权限设置，是否有添加桌面快捷方式权限。

**Comment by Yidadaa** [comment]
miui 默认禁用了浏览器的桌面快捷方式权限，自行打开。
