### ISSUE TITLE
[Feature] 添加修改用户话语按钮。

### ISSUE THREAD

**Issue by q960913** [Yidadaa/ChatGPT-Next-Web#886]
**这个功能与现有的问题有关吗？**
和修改用户话语有关的问题。

**你想要什么功能或者有什么建议？**
可以考虑添加一个修改用户话语的按钮吗，点击后可以删除原来的对话并把用户的话语发送到输入框，或者可以考虑添加一个复制用户一方话语的按钮。

**有没有可以参考的同类竞品？**

**其他信息**
因为现在系统给出的答案有时不如人意，所以不知道可不可以考虑添加一个更方便的修改功能辅助。或者提供一个可以复制用户话语仪方便粘贴修改的功能。

**Comment by Yidadaa** [comment]
移动端双击信息，pc 右键单击
