### ISSUE TITLE
[Feature] 能否考虑添加md聊天记录导入功能或json导出导入功能

### ISSUE THREAD

**Issue by q960913** [Yidadaa/ChatGPT-Next-Web#887]
**这个功能与现有的问题有关吗？**
相当于一个可以自己使用的同步功能，而不需要服务器或数据库支持

**你想要什么功能或者有什么建议？**
可以通过md或json导出聊天记录之后在别的平台手动导入。

**有没有可以参考的同类竞品？**
chatbot-ui类似的功能
![image](https://user-images.githubusercontent.com/87472382/232652205-4b41ee5d-491e-4d1a-840f-2f37e035a294.png)
**其他信息**

**Comment by HenMie** [comment]
这个功能和 https://github.com/Yidadaa/ChatGPT-Next-Web/issues/920 有一定重合度的，个人认为可以先实现这个功能，WebDav 其实就相当于自动地导入导出
