### ISSUE TITLE
[Bug] gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, can't work

### ISSUE THREAD

**Issue by kingyazh** [Yidadaa/ChatGPT-Next-Web#889]
The application is reporting the following error code.

```json
{
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```

**Comment by saigyouyou** [comment]
This because you didn't have permission to access gpt-4 api. Pls join openAI's waiting list and wait.

**Comment by jtung4** [comment]
Please confirm you have access to gpt-4 models.

Reference:
[https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-en.md#how-to-access-the-gpt-4-api](url)
Access to the GPT-4 API requires a separate application. Go to the following address and enter your information to join the waitlist (prepare your OpenAI organization ID): https://openai.com/waitlist/gpt-4-api Wait for email updates afterwards.
