### ISSUE TITLE
使用shell脚本部署后，关闭ssh连接工具后，网站就访问不了了

### ISSUE THREAD

**Issue by yishujia20230303** [Yidadaa/ChatGPT-Next-Web#890]
**描述问题**
使用shell脚本部署后，关闭ssh连接工具后，网站就访问不了了

**如何复现**
使用bash <(curl -s https://raw.githubusercontent.com/Yidadaa/ChatGPT-Next-Web/main/scripts/setup.sh)
部署后，关闭ssh连接工具之后，访问不了chatgpt-next-web，再次连接终端，发现该端口已经关闭，

我需要解决的问题是：使用shell脚本部署完成后如何在后台运行？

 - 部署方式：shell

**Comment by Yidadaa** [comment]
pm2 守护，问 chatgpt
