### ISSUE TITLE
请提供一下录屏，机型，系统版本。

### ISSUE THREAD

**Issue by idjj** [Yidadaa/ChatGPT-Next-Web#896]
请提供一下录屏，机型，系统版本。

_Originally posted by @Yidadaa in https://github.com/Yidadaa/ChatGPT-Next-Web/issues/884#issuecomment-1512369892_
            
我用的苹果12 ，safari网页版把书签添加到主页，然后再打开遇到了同样的问题！，版本是最新的
https://user-images.githubusercontent.com/88609927/232686907-9ad1effe-8511-42f7-a020-8a12f1a324a2.mp4

**Comment by nuclearn** [comment]
添加到主页，这种模式卡得厉害，以前还挺好的。

**Comment by Yidadaa** [comment]
爆内存了，这个功能还需要进一步进行性能优化。

合并到 #884 讨论。
