### ISSUE TITLE
手机模式Shift + Enter 换行的提示没有意思

### ISSUE THREAD

**Issue by gexiaopeng** [Yidadaa/ChatGPT-Next-Web#897]
用手机访问时，文本框提示Shift + Enter 换行是没有意义的，这个功能无法实现。手机模式下，提示 / 触发补全就可以了。

**Comment by Yidadaa** [comment]
懒得改了，现在国际化翻译文本量很大，挨个判断会非常麻烦，你就当看不见就行，或者设置里调成 Enter

**Comment by gexiaopeng** [comment]
> 懒得改了，现在国际化翻译文本量很大，挨个判断会非常麻烦，你就当看不见就行，或者设置里调成 Enter

这个用 isMobileScreen()判断就行了吧？

**Comment by Yidadaa** [comment]
就是要把这个函数穿进去，要改动七八个文件，而且里面都是相同的逻辑，懒得改。
