### ISSUE TITLE
[Feature] 增加按钮，滚到顶部，滚到底部

### ISSUE THREAD

**Issue by ChasLui** [Yidadaa/ChatGPT-Next-Web#901]
当聊天窗口很长的时候，我需要滚动很久才能到顶部或者到底部。

**Comment by Yidadaa** [comment]
滚到底部已经有了，滚到顶部的使用场景是？

**Comment by ChasLui** [comment]
> 滚到底部已经有了，滚到顶部的使用场景是？

review之前的聊天记录，其实主要是没有搜索聊天记录导致的。

**Comment by Yidadaa** [comment]
搜索功能之后会加，现在还有一些性能问题要解决，目前在用的搜索库不好用。

**Comment by Yidadaa** [comment]
耐心等待吧。
