### ISSUE TITLE
[Feature] Share conversations in pictures

### ISSUE THREAD

**Issue by jerry-yuan** [Yidadaa/ChatGPT-Next-Web#913]
**Is your feature request related to a problem? Please describe.**
I have made an interesting conversation and I want to share it with my friends. While in current version I can only share markdown which need render into image format like jpeg or png to make it more convenient to share with IM or social media.

I have tried rolling screenshot to save the conversation picture, while my phone said "there has some elements on screen that made rolling screenshot cannot join single snapshots"

**Describe the solution you'd like**
It is quite excessive to ask the implementation that export conversation as a long picture. As the result that this feature is useful only on mobile phones or tablets, which platforms commonly has rolling screenshot. I want to know if it is possible to be compatible with rolling screenshot? 

**Describe alternatives you've considered**
Hide those fixed elements like input box when taking rolling screenshot and make the conversation area scrollable.

**Comment by Yidadaa** [comment]
Duplicate #580
