### ISSUE TITLE
windows10 pro操作系统 使用最新版gitbash 来调试会报错[Bug] 

### ISSUE THREAD

**Issue by rongmingLi** [Yidadaa/ChatGPT-Next-Web#916]
**Describe the bug**
用gitbash 进入项目目录，执行yarn dev，开启服务后，无法浏览页面。 

**To Reproduce**
1. git bash 进入项目所在目录,
2. 执行 yarn dev 
3. 打开任意浏览器访问，无返回页面
4. gitbash 内报  SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)

说明：这个可能是nextjs app模式自身问题。删除app/component/home.tsx的 ”use client"这一行后报错消除。

**Comment by Yidadaa** [comment]
重新 yarn install 一下，next 最新稳定版有问题，已经升级到 dev 了。
