### ISSUE TITLE
[Bug] 进入再退出设置页面后，memory prompt按钮会变成下拉按钮

### ISSUE THREAD

**Issue by yanglyu902** [Yidadaa/ChatGPT-Next-Web#917]
**Describe the bug**
在网页端，当一个对话页面对话数量没有占满一页时，点击设置再退出设置页面，对话框上方原本的`contextual and memory prompt`按钮会变成"拉到底端"按钮并且无法还原，除非点击别的对话后再重新进入此对话。

**To Reproduce**
1. Create a new chat, or go to any chat with short conversations (haven't filling one page yet).
2. Click on `setting` button.
3. Exist `setting` page.
4. The `prompt` button becomes `to bottom` button and cannot be reverted. 

**Expected behavior**
The `prompt` button should stay there before and after entering/exiting the setting page.

**Screenshots**
<img width="878" alt="Screen Shot 2023-04-18 at 8 54 42 PM" src="https://user-images.githubusercontent.com/15838074/232963850-8013aa43-8350-4c68-ba3f-121553d1dcdd.png">

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [Mac M1]
 - Browser [Edge]
 - Version [111.0.1661.51]

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
#1103
