### ISSUE TITLE
[Bug] 昨天更新了啥，deploy报错了

### ISSUE THREAD

**Issue by asaketsu** [Yidadaa/ChatGPT-Next-Web#918]
**This edge function has crashed**
An unhandled error in the function code triggered the following message:

The deployment failed while serving the request.

===============
Netlify deploy
@Yidadaa

**Comment by asaketsu** [comment]
removed all edge functions

**Comment by Yidadaa** [comment]
我不用 netlify，没时间测试它部署有没有什么问题。

**Comment by asaketsu** [comment]
问题是前天还好好的，昨天更新报错了
哎，算了

**Comment by starlightliu** [comment]
> 我不用 netlify，没时间测试它部署有没有什么问题。
遇到了类似问题，因为netlify没有被墙，比vercel可用，如果能帮忙看看就好了
报错信息如下
2:48:49 PM: Packaging Edge Functions from .netlify/edge-functions directory:
2:48:49 PM:  - next_app_api_chat_stream_route
2:48:49 PM:  - next_app_api_openai_route
2:48:49 PM:  - next_middleware
2:48:49 PM:  - rsc-data
2:48:50 PM: ReferenceError: require is not defined
2:48:50 PM:     at Object.6195 (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:250:86)
2:48:50 PM:     at __webpack_require__ (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:91:42)
2:48:50 PM:     at Object.7451 (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:262:17188)
2:48:50 PM:     at __webpack_require__ (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:91:42)
2:48:50 PM:     at Object.3450 (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:262:12621)
2:48:50 PM:     at __webpack_require__ (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:91:42)
2:48:50 PM:     at Object.7332 (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:250:443)
2:48:50 PM:     at __webpack_require__ (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:91:42)
2:48:50 PM:     at file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:262:40245
2:48:50 PM:     at webpackJsonpCallback (file:///opt/build/repo/.netlify/edge-functions/next_app_api_chat_stream_route/bundle.js:224:39)
2:48:50 PM: ReferenceError: require is not defined
2:48:50 PM:     at Object.6195 (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:250:86)
2:48:50 PM:     at __webpack_require__ (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:91:42)
2:48:50 PM:     at Object.7451 (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:262:17188)
2:48:50 PM:     at __webpack_require__ (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:91:42)
2:48:50 PM:     at Object.3450 (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:262:12621)
2:48:50 PM:     at __webpack_require__ (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:91:42)
2:48:50 PM:     at Object.975 (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:250:452)
2:48:51 PM:     at __webpack_require__ (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:91:42)
2:48:51 PM:     at file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:262:43181
2:48:51 PM:     at webpackJsonpCallback (file:///opt/build/repo/.netlify/edge-functions/next_app_api_openai_route/bundle.js:224:39)
