### ISSUE TITLE
[Feature] add chat playground support

### ISSUE THREAD

**Issue by isee15** [Yidadaa/ChatGPT-Next-Web#919]
**你想要什么功能或者有什么建议？**
支持openai playground。
特别是chat里面 system,user,assistant的message输入

**有没有可以参考的同类竞品？**
https://platform.openai.com/playground?mode=chat
https://play.vercel.ai/

**Comment by Yidadaa** [comment]
没懂你意思，请详细说明。

**Comment by isee15** [comment]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/10377426/233065385-892ae088-bc89-4342-8cd3-687c913a7414.png">

gpt-3.5-turbo支持 message数组，可以在playground里面配置类似这样的prompt
[{ role: ‘system’, content: promptText },
{ role: ‘user’, content: somepreviousquestion.value },
{ role: ‘assistant’, content: somepreviousresponse.value },
{ role: ‘user’, content: somepreviousquestion2.value },
{ role: ‘assistant’, content: somepreviousresponse2.value },
{ role: ‘user’, content: somepreviousquestion3.value },
{ role: ‘assistant’, content: somepreviousresponse3.value },
{ role: ‘user’, content: somepreviousquestion4.value },
{ role: ‘assistant’, content: somepreviousresponse4.value },
{ role: ‘user’, content: inputField.value }
]

**Comment by Yidadaa** [comment]
要不然你试试点击一下输入框上方的大脑图标？

<img width="628" alt="image" src="https://user-images.githubusercontent.com/16968934/233104001-05cbb7f3-c470-45b1-a25f-be7070913588.png">
