### ISSUE TITLE
[Feature] Cloud Sync via WebDAV

### ISSUE THREAD

**Issue by chennishizhu** [Yidadaa/ChatGPT-Next-Web#920]
能否增加对WebDav的支持，让用户使用自己的网盘实现消息记录的自动备份与同步。像坚果云、Dropbox、InfiniCLOUD等等，随便支持一个都可以。

**Comment by Yidadaa** [comment]
在计划中。

**Comment by ChasLui** [comment]
目前我的解决办法是用chrome插件[localStorage manager](https://chrome.google.com/webstore/detail/localstorage-manager/fkhoimdhngkiicbjobkinobjkoefhkap)手动导入导出.

**Comment by adevjoe** [comment]
> 在计划中。

请问计划用什么方式实现

**Comment by ChasLui** [comment]
> 目前我的解决办法是用chrome插件[localStorage manager](https://chrome.google.com/webstore/detail/localstorage-manager/fkhoimdhngkiicbjobkinobjkoefhkap)手动导入导出.

更新, 目前使用自部署的 cookiecloud 同步localStorage

**Comment by daiaji** [comment]
移动版上只能依靠ChatGPT-Next-Web 的原生实现了。
这玩意是存在Root权限才能访问的地方。
而Firefox android没有相关扩展可用。
chrome就别说了。

**Comment by ckt1031** [comment]
就像ChatGPT一样, 不可能同时向多装置Stream输出，但是可以在云端档案中，添加状态元数据，在该讯息ID底下，发送讯息，先向云端查询是否正在Stream，完成后，添加记录并且进行云端储存。在另一个装置底下，对话可以与云端进行日期对比。
同时亦可以添端对端加密的功能，在网盘环境对话内容完全不可见。

**Comment by Yidadaa** [comment]
大多数 webdav 服务均没有开启 cors，无法在网页中直接使用，此特性开发暂时搁置。

**Comment by daiaji** [comment]
> 大多数 webdav 服务均没有开启 cors，无法在网页中直接使用，此特性开发暂时搁置。

使用云盘的api呢？

**Comment by imzhoukunqiang** [comment]
可否考虑一下用后端服务转发到webdav呢？

**Comment by Endlessworld** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2176 我在这个里面描述的可能不够清楚、
这个功能
应该叫基于web3的多端同步

从用户使用效果上来说
1 设置里有个 【开启多端共享】之类的选项 选中即开启 开启后 可选是否 设置【访问密码】 可通过【访问密码】加密解密数据
2 效果1 添加浏览器书签  清空浏览缓存数据 打开书签地址 聊天记录 设置信息依旧存在 除非手动重置。 
3 效果2 另一设备通过旧设备当前链接或其二维码打开相同链接 聊天记录、设置信息 与旧设备相同
4 效果3 多设备在相同链接地址今天聊天时 刷新页面可同步最新消息记录

从开发者使用角度来说 可以在环境变量设置一个稳定的Web3节点服务商、如cloudflare（有免费额度）
实现思路：
参考这里https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2176
1 开启选项后 将当前用户聊天记录与配置选项信息  根据随机字符或用户设置的【访问密码】进行可逆的简单加密 ；
2 将加密后的用户信息 pin到web3供应商例如 cloudflare（ https://www.cloudflare.com/zh-cn/web3/#）
3 pin数据到供应商将获取一个CID,简单理解为数据Hash不同数据Hash值不同，因此随着数据内容变化CID会不断变化、因此需要将CID发布到IPNS IPNS即是一个最新版本的CID固定访问链接。
4 更新当前localtion.href ，query参数附带 IPNS及访问密码
5 页面初始化检测是否携带IPNS 有则提取用户数据 对用户数据进行恢复

**Comment by daiaji** [comment]
> #2176 我在这个里面描述的可能不够清楚、 这个功能 应该叫基于web3的多端同步
> 
> 从用户使用效果上来说 1 设置里有个 【开启多端共享】之类的选项 选中即开启 开启后 可选是否 设置【访问密码】 可通过【访问密码】加密解密数据 2 效果1 添加浏览器书签 清空浏览缓存数据 打开书签地址 聊天记录 设置信息依旧存在 除非手动重置。 3 效果2 另一设备通过旧设备当前链接或其二维码打开相同链接 聊天记录、设置信息 与旧设备相同 4 效果3 多设备在相同链接地址同时进行聊天时 刷新页面可同步最新消息记录
> 
> 从开发者使用角度来说 可以在环境变量设置一个稳定的Web3节点服务商、如cloudflare（有免费额度） 实现思路： 参考这里#2176 1 开启选项后 将当前用户聊天记录与配置选项信息 根据随机字符或用户设置的【访问密码】进行可逆的简单加密 ； 2 将加密后的用户信息 pin到web3供应商例如 cloudflare（ [https://www.cloudflare.com/zh-cn/web3/#）](https://www.cloudflare.com/zh-cn/web3/#%EF%BC%89) 3 pin数据到供应商将获取一个CID,简单理解为数据Hash不同数据Hash值不同，因此随着数据内容变化CID会不断变化、因此需要将CID发布到IPNS IPNS即是一个最新版本的CID固定访问链接。 4 更新当前localtion.href ，query参数附带 IPNS及访问密码 5 页面初始化检测是否携带IPNS 有则提取用户数据 对用户数据进行恢复
> 
> 这个功能还可能为本项目 增加一点有意思社交属性 例如 AI多人在线聊天 哈哈

前沿技术总是很有趣，听起来是cf提供了储存节点和网关？
看cf自己的说明，数据会被放到全球数据中心，那看起来容灾不错。

**Comment by 2-3-5-7** [comment]
我看到 https://github.com/ztjhz/BetterChatGPT 使用 GoogleDrive 实现的同步，是否可以参考一下？

**Comment by 2-3-5-7** [comment]
@ChasLui 问一下，移动端有自动同步 localstorage 的方法吗？我试了 android 手机 kiwi 浏览器装 cookiecloud，无法同步，但是 PC 端是没问题的

**Comment by ttimasdf** [comment]
别整那些花里胡哨的什么web3。那东西没有任何意义。

当你提出解决方案的时候，花时间想想自己要解决的是什么问题。

当我们说同步的时候，我们的需求是：一个隐私、可内网或公网部署 、高速、省空间的同步服务。 

IPFS 没有解决以上任何一点，甚至与之背道而驰🙄

**Comment by ZacharyJia** [comment]
考虑支持S3存储怎么样？S3使用很广泛，不管是原版的，还是各种兼容S3 API的对象存储服务都有，也可以使用MinIO自建。
像Cloudflare也提供了免费的10G存储, 100万次写，1000万次读操作 ( https://www.cloudflare.com/zh-cn/products/r2/ )，个人用户应该是足够的。也提供了CORS支持(https://developers.cloudflare.com/r2/buckets/cors/)

**Comment by daiaji** [comment]
同步ngbung普通的做成
https://chatgpt.xn--b6gac.eu.org/
这种简单的基于导入导出的同步？
？
这样还能导出成json或者压缩过的json。

**Comment by 821869798** [comment]
尝试用了下 [BetterChatGPT](https://github.com/ztjhz/BetterChatGPT)  GoogleDrive方式的同步，还可以，能否能支持下同步消息。

**Comment by leoweyr** [comment]
既然`ChatGPT-Next-Web`存在服务端和客户端关系，是否可以把聊天记录数据选择直接储存在服务端特定位置，在客户端可设定是否同步服务端指定的聊天记录。这样一来就不需要依靠第三方云服务了。但是如果说是分发商直接提供这种服务，那么服务端得有数据容器去储存不同客户的客户端聊天记录，还得是加密的、防止数据泄露

**Comment by yunwuu** [comment]
我有一个想法，但是代码能力渣渣，完整实现尚未完成，不知道有没有大佬可以考虑实现一下：
1. 与其使用WebDav，不如使用 Redis，避免了`cors`的问题的同时可以更便捷的合并冲突的数据。 Redis实例可以直接使用 [Upstash](https://upstash.com/) ，有足够的免费额度，且无论是 Redis URL 还是 `@upstash/redis` 库提供支持的 URL+Token的验证方式，都无需繁琐的配置。
2. 对Redis的相关读写操作可以利用 Edge Functions 来完成。
3. Redis中设两个Hash键值对，`messages` 和 `sessions` ，分别存放消息和会话，在新消息/会话创建完成后通过 edge function直接把消息/会话上传到数据库，而设置中的同步按钮则可以进行云端数据的拉取和本地全部数据的上传。
4. 数据库拥有全部 `messages` 和 `sessions` 的信息后，只需要进行简单的合并就能构造出存储在`localStorage`中的格式（或许也可以直接调用`zustand`或已有的方法，没有仔细研究过，应该是可行的）

**Comment by Yidadaa** [comment]
Done https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2819

**Comment by lovitus** [comment]
webdav服务提供商大部分都提供了cors设置吧, 
通配,
或者认证和域名枚举
