### ISSUE TITLE
[Bug] 导出后，查看文档目录一样

### ISSUE THREAD

**Issue by lsasw** [Yidadaa/ChatGPT-Next-Web#921]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
导出的md文档，标题全是

- 来自 ChatGPT 的消息:
- 来自你的消息:
样式

**如何复现**
导出后，查看文档目录

**截图**
![image](https://user-images.githubusercontent.com/87928705/232989792-3224e14a-8a59-45e5-b3ae-9f850434fee4.png)

**一些必要的信息**
 - 系统：[ windows 11]
 - 浏览器： [ edge]
 - 版本：
![image](https://user-images.githubusercontent.com/87928705/232990311-f994a5e4-09d3-4547-9136-0c94e4b5cd0c.png)

 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by Yidadaa** [comment]
这不是很正常吗？你想让它变成什么样？

**Comment by lsasw** [comment]
之前版本导出时，是以问题作为标题，更新后发现在导出时，是以对话人作为标题，那就没问题了

**Comment by lsasw** [comment]
好的，了解，非常感谢！
