### ISSUE TITLE
[Feature] 提供選項讓用戶選擇用gpt-3.5-turbo來自動生成標題和壓縮對話

### ISSUE THREAD

**Issue by jtung4** [Yidadaa/ChatGPT-Next-Web#928]
延續#864 的建議
希望提供選項讓用戶在利用gpt-4作對話模型時，用gpt-3.5-turbo，而不用gpt-4來自動生成標題和壓縮對話
始終gpt-3.5-turbo較符合成本效益

**Comment by Yidadaa** [comment]
可以提交一个 PR 来完成此功能。

**Comment by jtung4** [comment]
commit 06d5041後無論用户選用gpt-4還是gpt-3.5-turbo，都會使用gpt-3.5-turbo來自動生成標題
但上下文壓縮對話的代碼仍未修改。

**Comment by ChasLui** [comment]
希望可以通过docker环境变量配置模型，不想还要用户自己去设置模型为gpt4.
