### ISSUE TITLE
[BUG]复制记忆功能不生效

### ISSUE THREAD

**Issue by JourneyHans** [Yidadaa/ChatGPT-Next-Web#929]
![image](https://user-images.githubusercontent.com/8108912/233023494-e72b7483-674d-4ab9-88a9-218cbc599881.png)

提示“已经赋值到剪切板”，但是粘贴没有任何东西。

**Comment by Yidadaa** [comment]
上面不是写了“尚未记忆”？这里复制的只是历史记忆，不包含前置上下文
