### ISSUE TITLE
[Bug]  我在CodeSandbox 部署以后，AI回复的消息是直接显示的，没有逐字显示的效果

### ISSUE THREAD

**Issue by anyangmvp** [Yidadaa/ChatGPT-Next-Web#932]
CodeSandbox 部署以后，AI回复的消息是直接显示的，没有逐字显示的效果.
如果AI 回复的消息很长的时候，需要等待好久，然后瞬间把结果显示出来。没有一个一个字慢慢展示回复消息的动效，麻烦问问这个是不是和使用的服务器内置的网络设置有关系？ 还是在哪里设置的？

**Comment by Yidadaa** [comment]
并不是所有平台都支持流式响应，目前已知 netlify 和 aws 不支持，code sandbox 估计用的 aws
