### ISSUE TITLE
[Bug] 没法自动更新

### ISSUE THREAD

**Issue by 2682856025** [Yidadaa/ChatGPT-Next-Web#940]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_2174](https://user-images.githubusercontent.com/106012957/233228585-3c6de101-784d-4152-857c-0c0af9bc8118.png)
![IMG_2175](https://user-images.githubusercontent.com/106012957/233228592-1253c7f5-df2f-43b9-992e-ccac850e785f.png)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Yidadaa** [comment]
手动 sync fork 一次。
