### ISSUE TITLE
使用Azure版的接口后，是不是模型选择没有任何效果？怎么选GPT4？

### ISSUE THREAD

**Issue by Ya-chunJen** [Yidadaa/ChatGPT-Next-Web#941]
使用其他开发者的项目，将Azure的接口反向代理后，可以正常运行。
这个时候，是不是在「设置」页面选择模型类型是无效的？
我们Azure的接口已经申请到了GPT4的版本，怎么同时使用3.5和4的版本？

**Comment by Yidadaa** [comment]
这和你用的反代项目有关，请给出链接。

**Comment by yinm0591** [comment]
@Ya-chunJen 某位大佬的项目，支持GPT3.5/GPT4切换功能：

https://github.com/haibbo/cf-openai-azure-proxy

**Comment by yinm0591** [comment]
@Ya-chunJen 顺便问一下，Azure如何申请GPT4？ 谢谢~
