### ISSUE TITLE
能不能自定义预设的提示词列表

### ISSUE THREAD

**Issue by WYH2004-MC** [Yidadaa/ChatGPT-Next-Web#942]
**这个功能与现有的问题有关吗？**
现在的用户自定义提示词是保存在浏览器缓存中的，更换设备就没了，有无方法可以把需要的提示词写入预设的列表中，方便在其他设备使用时直接调用

**你想要什么功能或者有什么建议？**
希望可以自定义预设的提示词列表

**Comment by Yidadaa** [comment]
#920
