### ISSUE TITLE
[Feature] 最近好多公益网站作者被网信办约谈了！

### ISSUE THREAD

**Issue by fangyuan99** [Yidadaa/ChatGPT-Next-Web#944]
**你想要什么功能或者有什么建议？**

**建议在有授权码的情况下，进入网站首先是填写授权码的页面（同时加上遮罩，不让用户知道这个网站是干什么用的），等正确输入授权码后，才进入正常网页**

**Comment by Yidadaa** [comment]
请灵活使用 ngnix Basic Authentication、cloudflare zero-trust 等技术来控制页面可见性，这些技术无需改动页面代码。
