### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by openaddr** [Yidadaa/ChatGPT-Next-Web#945]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
![image](https://user-images.githubusercontent.com/61171538/233252984-ec150629-f67a-4c53-b9a9-9723f11f1b63.png)

这里的http链接似乎出现了格式问题,点击的话会带上后面呈现蓝色部分的文字,导致跳转异常
**如何复现**
请告诉我们你是通过什么操作触发的该问题。
可以尝试问图片中类似的问题来复现
**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
截图已给出
**一些必要的信息**
 - 系统：windows 11
 - 浏览器： chrome
 - 版本： b7b16aa
 - 部署方式：docker部署

**Comment by Yidadaa** [comment]
github 的 markdown 链接也是这样，你可以试试
