### ISSUE TITLE
[bug] 启动docker镜像时填写proxy后，镜像停止

### ISSUE THREAD

**Issue by taoxq** [Yidadaa/ChatGPT-Next-Web#948]
![image](https://user-images.githubusercontent.com/45961657/233266891-61c21e45-7411-42fa-a3ea-2d586f6461e0.png)

**Comment by yinm0591** [comment]
填错位置了，改成 -e BASE_URL="openai.api2d.net"  试试

**Comment by taoxq** [comment]
感谢···· @yinm0591
