### ISSUE TITLE
能否自定义左侧应用名和应用描述

### ISSUE THREAD

**Issue by YouCanYouUp741** [Yidadaa/ChatGPT-Next-Web#95]
左侧的应用名是否支持自定义修改？

**Comment by YouCanYouUp741** [comment]
已解决，谢谢！

**Comment by 205637827** [comment]
请问怎么解决呢，有劳指导一下

**Comment by YouCanYouUp741** [comment]
> 

在文件app/components/home.tsx中进行修改，找到 function Home()，return的div标签里面有原始的应用名，改成自己的即可

**Comment by YouCanYouUp741** [comment]
> 请问怎么解决呢，有劳指导一下

在文件app/components/home.tsx中进行修改，找到 function Home()，return的div标签里面有原始的应用名，改成自己的即可

**Comment by huwan** [comment]
希望可以自定义应用名称（LOGO）和描述。因为想跟项目更新保持同步，手动修改后就会有冲突。希望可以像其它配置项那样添加环境变量的方式，自定义网站名称和描述。

**Comment by DarriusL** [comment]
> > 问一下在哪里修改？
> 
> 在文件app/components/home.tsx中进行修改，找到 function Home()，return的div标签里面有原始的应用名，改成自己的即可

请问现在是改不了了吗 
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/119288894/002dae94-16ba-4163-8c64-5dc97072efc8)
