### ISSUE TITLE
[Feature] 渲染 Mermaid

### ISSUE THREAD

**Issue by ChasLui** [Yidadaa/ChatGPT-Next-Web#951]
gpt 在绘制流程图的时候希望可以直接渲染出来。

**Comment by Yidadaa** [comment]
Ref: https://mermaid.js.org/config/usage.html#using-mermaid-run

**Comment by WingCH** [comment]
同樣需求+1

**Comment by yzy1996** [comment]
输入：

```mermaid
graph TD;
    A[开始]-->B[步骤1];
    B-->C[步骤2];
    C-->D[结束];
```

输出：
<img width="695" alt="image" src="https://user-images.githubusercontent.com/20658350/236593201-c24a1aea-a696-464c-b432-f69b9ece483f.png">

**Comment by WingCH** [comment]
有時候gpt會生成錯誤格式的Mermaid
如果有個button,可以edit /看到raw格式就體驗更好了

**Comment by yzy1996** [comment]
> 有時候gpt會生成錯誤格式的Mermaid 如果有個button,可以edit /看到raw格式就體驗更好了

可以复制出来，上面一条我复制出来是正常显示的，但网页渲染有问题。
