### ISSUE TITLE
[Bug] 怎么没了上下文记忆了，才第二轮

### ISSUE THREAD

**Issue by Maddaxman** [Yidadaa/ChatGPT-Next-Web#956]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/31379908/233405960-10cce7bf-f251-40ca-b1a8-e7987cb175c8.png">

部署在vercel上的自动同步最先版

**Comment by Maddaxman** [comment]
我在ios正常，在mac的chrome上 上下文失效了

**Comment by Yidadaa** [comment]
设置里面携带历史消息数不要调成 0

**Comment by Maddaxman** [comment]
@Yidadaa  设置里是6，不设置system prompts是 正常的

<img width="2018" alt="image" src="https://user-images.githubusercontent.com/31379908/233412255-f4aaea9f-ebfa-4a9c-a467-ca934dc2a858.png">

**Comment by Yidadaa** [comment]
System Prompt 设置界面截图发一下

**Comment by Maddaxman** [comment]
> System Prompt 设置界面截图发一下

@Yidadaa 
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/31379908/233413534-079879c7-1e8d-45bf-acac-0b3093f999a9.png">

**Comment by Maddaxman** [comment]
> 我感觉第一次应该是 gpt3.5 回复错了，而不是没有上下文

刚刚有问题的时候尝试了两个会话，不同场景一个是问代码一个是问旅游的，都是同样的问题，现在正常了

**Comment by Maddaxman** [comment]
> 我感觉第一次应该是 gpt3.5 回复错了，而不是没有上下文

@Yidadaa 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/31379908/233426637-b0d235fc-0708-482c-9c38-bdb5a31edd1a.png">
貌似又复现了
