### ISSUE TITLE
[Feature] 可否让用户自行设置输入文本的长度限制？

### ISSUE THREAD

**Issue by scxiegangxy** [Yidadaa/ChatGPT-Next-Web#962]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
我的前置上下文比较长，输了以后，在具体发送命令时，软件回答往往不完整。可否让用户自行设置输入文本的长度限制？这样我可以充分输入上下文信息，以便让软件对上下文进行总结归纳或利用。谢谢！

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Yidadaa** [comment]
最大长度是 openai 的模型限制的，你限制了有啥用？

**Comment by scxiegangxy** [comment]
哎....那看来只有去申请GPT-4的key了。
