### ISSUE TITLE
[Bug] 无边框模式和主题无法实时应用，需要刷新

### ISSUE THREAD

**Issue by Chandler-Lu** [Yidadaa/ChatGPT-Next-Web#963]
**Describe the bug**
早期版本的无边框模式，勾选即生效，当前版本需要刷新后才能生效。

**Deployment**
- [x] Docker, a62bca4
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 112

**Comment by Yidadaa** [comment]
已知问题，和昨晚的 react-router 重构有关，边框和主题都是如此。

**Comment by Yidadaa** [comment]
#959

**Comment by lifedever** [comment]
坐等更新

**Comment by AprilNEA** [comment]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/37977109/233568463-152039f5-9393-46f1-bde1-477e61f96b82.png">

可能与 zustand 状态嵌套有关，需要将 tightBorader 作为单独的 state, 否则无法被订阅成功

**Comment by tanghui315** [comment]
你们对 react 不熟啊， 只要改一下 app.ts ， 传递config 用浅拷贝，就解决问题了。 不用单拆一个store出来。
` updateConfig(updater) {
        const config = get().config;
        updater(config);
        set(() => ({ config: {...config} }));
      }`

**Comment by AprilNEA** [comment]
>  不用单拆一个store出来。

拆分 store 与重构有关

**Comment by tanghui315** [comment]
> > 不用单拆一个store出来。
> 
> 拆分 store 与重构有关

我这边跟你们分叉了， 好多bug,  你们没更新，我自己改了。

**Comment by Yidadaa** [comment]
@tanghui315 

有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎

**Comment by tanghui315** [comment]
> @tanghui315
> 
> 有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎

我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。

**Comment by tanghui315** [comment]
> 

我这是在嘲讽吗。

**Comment by Chandler-Lu** [comment]
> > @tanghui315
> > 有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎
> 
> 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。

没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。

**Comment by tanghui315** [comment]
> 
是我在吐槽吗， 是有人在人身攻击好吧

**Comment by tanghui315** [comment]
> > > @tanghui315
> > > 有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎
> > 
> > 
> > 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。
> 
> 没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。
是我在吐槽吗，是有人在人身攻击好吧。

**Comment by tanghui315** [comment]
> > > > @tanghui315
> > > > 有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎
> > > 
> > > 
> > > 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。
> > 
> > 
> > 没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。
> > 是我在吐槽吗，是有人在人身攻击好吧。

是我在吐槽吗，是有人在人身攻击好吧。

**Comment by tanghui315** [comment]
> > > > > @tanghui315
> > > > > 有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎
> > > > 
> > > > 
> > > > 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。
> > > 
> > > 
> > > 没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。
> > > 是我在吐槽吗，是有人在人身攻击好吧。
> 
> 是我在吐槽吗，是有人在人身攻击好吧。

你们学生，就这个素质，搞啥开源，先把做人学好。

**Comment by Chandler-Lu** [comment]
> > > > > > @tanghui315
> > > > > > 有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎
> > > > > 
> > > > > 
> > > > > 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。
> > > > 
> > > > 
> > > > 没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。
> > > > 是我在吐槽吗，是有人在人身攻击好吧。
> > 
> > 
> > 是我在吐槽吗，是有人在人身攻击好吧。
> 
> 你们学生，就这个素质，搞啥开源，先把做人学好。

这句话真是适用你自己

**Comment by tanghui315** [comment]
> > > > > > > @tanghui315
> > > > > > > 有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎
> > > > > > 
> > > > > > 
> > > > > > 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。
> > > > > 
> > > > > 
> > > > > 没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。
> > > > > 是我在吐槽吗，是有人在人身攻击好吧。
> > > 
> > > 
> > > 是我在吐槽吗，是有人在人身攻击好吧。
> > 
> > 
> > 你们学生，就这个素质，搞啥开源，先把做人学好。
> 
> 这句话真是适用你自己

我会把你们这份言论，发到社区。 让大家评判，到底是谁在攻击和贬低别人。我从上至下我都非常讲道理。

**Comment by Chandler-Lu** [comment]
> > > > > > > > @tanghui315
> > > > > > > > 有 bug 不反馈给上游，还搁这嘲讽，觉得自己很牛逼？15 年开发经验还不如别人大一的，你也就这点能耐了 👎
> > > > > > > 
> > > > > > > 
> > > > > > > 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。
> > > > > > 
> > > > > > 
> > > > > > 没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。
> > > > > > 是我在吐槽吗，是有人在人身攻击好吧。
> > > > 
> > > > 
> > > > 是我在吐槽吗，是有人在人身攻击好吧。
> > > 
> > > 
> > > 你们学生，就这个素质，搞啥开源，先把做人学好。
> > 
> > 
> > 这句话真是适用你自己
> 
> 我会把你们这份言论，发到社区。 让大家评判，到底是谁在攻击和贬低别人。我从上至下我都非常讲道理。

嗯，好的，没时间搞开源贡献，有时间折腾社区

**Comment by tanghui315** [comment]
> > > > > > > > > 的，你也就这点能耐了 👎
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。
> > > > > > > 
> > > > > > > 
> > > > > > > 没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。
> > > > > > > 是我在吐槽吗，是有人在人身攻击好吧。
> > > > > 
> > > > > 
> > > > > 是我在吐槽吗，是有人在人身攻击好吧。
> > > > 
> > > > 
> > > > 你们学生，就这个素质，搞啥开源，先把做人学好。
> > > 
> > > 
> > > 这句话真是适用你自己
> > 
> > 
> > 我会把你们这份言论，发到社区。 让大家评判，到底是谁在攻击和贬低别人。我从上至下我都非常讲道理。
> 
> 嗯，好的，没时间搞开源贡献，有时间折腾社区

凭什么，我就让别人攻击 。 我还不能讨个公道。

**Comment by tanghui315** [comment]
> > > > > > > > > 的，你也就这点能耐了 👎
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我只是就事论事，不要如此狭隘。 我不是不想不反馈，人工智能行业太卷了， 我是创业者，那有时间搞开源贡献。
> > > > > > > 
> > > > > > > 
> > > > > > > 没时间你在这吐槽什么？还有要搞事自己发 issue，别在我下面。
> > > > > > > 是我在吐槽吗，是有人在人身攻击好吧。
> > > > > 
> > > > > 
> > > > > 是我在吐槽吗，是有人在人身攻击好吧。
> > > > 
> > > > 
> > > > 你们学生，就这个素质，搞啥开源，先把做人学好。
> > > 
> > > 
> > > 这句话真是适用你自己
> > 
> > 
> > 我会把你们这份言论，发到社区。 让大家评判，到底是谁在攻击和贬低别人。我从上至下我都非常讲道理。
> 
> 嗯，好的，没时间搞开源贡献，有时间折腾社区

凭什么，我就让别人攻击 。 我还不能讨个公道。

**Comment by tanghui315** [comment]
我让大家都看看 ，ChatGPT-Next-Web 开源人是什么素质。

**Comment by Yidadaa** [comment]
@tanghui315 

你爷爷我一直实名上网，不用劳您发到社区，你去新闻上搜搜“腾讯 张义飞”，什么狗屁大公司我都照喷不误，请问您是哪种咖位？要不要我把这条 issue reopen 了置顶？🤣

**Comment by tanghui315** [comment]
原来你就是一个网络喷子，逢人就喷的能力，我自叹不如。我看开了，跟喷子斗气，拉低了我的档次 。88。



在 2023-04-26 10:08:59，"Yifei Zhang" ***@***.***> 写道：

@tanghui315

你爷爷我一直实名上网，不用劳您发到社区，你去新闻上搜搜“腾讯 张义飞”，什么狗屁大公司我都照喷不误，请问您是哪种咖位？要不要我把这条 issue reopen 了置顶？🤣

**Comment by Yidadaa** [comment]
@tanghui315 

希望你能明白我为什么喷你。
