### ISSUE TITLE
[Bug] 检测更新功能是有问题吗？Docker容器已经更新到最新，看最后releases 版本也是 b7b16aa，一直显示有更新

### ISSUE THREAD

**Issue by hello--world** [Yidadaa/ChatGPT-Next-Web#964]
**Describe the bug**
设置更新显示疑问

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/9261185/233524979-9d2df996-ca62-4bed-8e18-2d1414782808.png">
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/9261185/233525062-72c41bf3-ba9c-47fd-ad5e-1da406a369a5.png">

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser 都有问题

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by Chandler-Lu** [comment]
这是最新的 commit，不是最新的 release

**Comment by hello--world** [comment]
显示发现新版本，如何更新都还是这个版本。当前版本显示有问题？

**Comment by Chandler-Lu** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/README_CN.md#%E5%AE%B9%E5%99%A8%E9%83%A8%E7%BD%B2-%E6%8E%A8%E8%8D%90

**Comment by hello--world** [comment]
明白了，刚刚搜索了一下没搜索到，感谢，有点强迫症
