### ISSUE TITLE
[Bug] 加载 UI 出错

### ISSUE THREAD

**Issue by devyujie** [Yidadaa/ChatGPT-Next-Web#965]
**反馈须知**
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。

**描述问题**
加载 UI 出错

**如何复现**
每次重新打开网页时

**截图**
![2](https://user-images.githubusercontent.com/48620527/233531341-d35a1089-7ca8-4499-8ddc-bdf5b9d959e1.gif)

**一些必要的信息**
 - 系统：windows 10
 - 浏览器： chrome
 - 版本：a62bca4
 - 部署方式：vercel

**Comment by Yidadaa** [comment]
没有出错，你看到的加载 logo 是侧边栏的加载动画

**Comment by devyujie** [comment]
这样设计好奇怪啊，总感觉是页面bug
