### ISSUE TITLE
[Bug] Unsupported Linux distribution when running setup.sh on Ubuntu OS

### ISSUE THREAD

**Issue by jzjwonderful** [Yidadaa/ChatGPT-Next-Web#978]
**Describe the bug**
`Unsupported Linux distribution` when running setup.sh. the actual output is `ID=ubuntu` , not `ID="ubuntu"` ,the `centos` `arch` is same as `ubuntu`
```
if [[ "$(cat /etc/*-release | grep '^ID=')" = "ID=\"ubuntu\"" ]]; then
        sudo apt-get update
        sudo apt-get -y install nodejs git yarn
      elif [[ "$(cat /etc/*-release | grep '^ID=')" = "ID=\"centos\"" ]]; then
        sudo yum -y install epel-release
        sudo yum -y install nodejs git yarn
      elif [[ "$(cat /etc/*-release | grep '^ID=')" = "ID=\"arch\"" ]]; then
        sudo pacman -Syu -y
        sudo pacman -S -y nodejs git yarn
      else
        echo "Unsupported Linux distribution"
        exit 1
      fi
```

see also [os-release](https://www.linux.org/docs/man5/os-release.html)

**To Reproduce**
1. change `"ID=\"ubuntu\""` to `"ID=ubuntu"`
2. same to `centos` and `arch`

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [x] Server

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [edge]
 - Version [2204 1804]

**Comment by Yidadaa** [comment]
Thank you for your contribution, but I still suggest using Vercel or Docker for deployment.
