### ISSUE TITLE
[Bug] auto update workflow run error

### ISSUE THREAD

**Issue by YuXiaoDou** [Yidadaa/ChatGPT-Next-Web#981]
![image](https://user-images.githubusercontent.com/82626778/233625317-8910254b-261a-4f8f-b120-e6262854a40a.png)
![image](https://user-images.githubusercontent.com/82626778/233625388-6a59a95a-29d5-419e-93b4-88a250b2467b.png)

**Comment by Yidadaa** [comment]
手动 sync fork 一次。
