### ISSUE TITLE
[Bug] 为什么我开开发环境使用的openai代理可以跑 ，打包后就不能跑了呢？就因为我是https的代理吗

### ISSUE THREAD

**Issue by PuddingJoker** [Yidadaa/ChatGPT-Next-Web#983]
为什么我开开发环境使用的openai代理可以跑 ，打包后就不能跑了呢？就因为我是https的代理吗

**Comment by AprilNEA** [comment]
社区不会对过于细节的问题进行解决，可携带相关报错前往群组询问。

**Comment by PuddingJoker** [comment]
群组在哪呢


AprilNEA ***@***.***> 于2023年4月21日周五 21:23写道：
