### ISSUE TITLE
[Feature] 增加选项 使用access token代替api_key访问chatGPT

### ISSUE THREAD

**Issue by gilgamsh** [Yidadaa/ChatGPT-Next-Web#985]
因为使用api_key的访问免费额度较少，个人使用似乎使用access token即可满足需求。同时与直接访问官网相比，可以不用挂代理。不知道这个建议合不合理？非常感谢您开源的代码。

**Comment by AprilNEA** [comment]
您对本项目的理解有误，本项目目前仅支持官方API，官方API仅支持通过 api key进行访问
