### ISSUE TITLE
[Bug] 为什么浏览器里好使的请求 复制成 curl 就不好使了

### ISSUE THREAD

**Issue by hlf2016** [Yidadaa/ChatGPT-Next-Web#988]
浏览器中是好使的 转换成 curl 在命令行中不好使

curl 'http://localhost:3000/api/openai?_vercel_no_cache=1' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh,zh-CN;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed

本地 测试

**Comment by Yidadaa** [comment]
headers 里面没设置 token，你的网站密码

**Comment by hlf2016** [comment]
加上了 好像也没用 大佬要不要给一份儿能用的模板呢

**Comment by hlf2016** [comment]
> headers 里面没设置 token，你的网站密码

<img width="871" alt="image" src="https://user-images.githubusercontent.com/24551738/233694342-23920749-d851-44f0-929e-2c6730619c1a.png">
@Yidadaa
