### ISSUE TITLE
[Bug] 刚开始可以用，发了两条就变成以下提示

### ISSUE THREAD

**Issue by 1162431386** [Yidadaa/ChatGPT-Next-Web#989]
{
  "cause": {
    "library": "SSL routines",
    "reason": "sslv3 alert handshake failure",
    "code": "ERR_SSL_SSLV3_ALERT_HANDSHAKE_FAILURE"
  }
}

**Comment by Yidadaa** [comment]
你的代理有问题。

**Comment by 1162431386** [comment]
我现在使用ip+端口访问，大多数时间都可以，但偶尔还是抱着个错误，是不是因为域名没有ssl证书的问题呢
