### ISSUE TITLE
[Feature] 国内微信登录和微信支付支持

### ISSUE THREAD

**Issue by clayboby** [Yidadaa/ChatGPT-Next-Web#992]
https://www.vivi-chat.com/#/chat
像这个网站加个微信登录和支付就完美了。
墙外的套壳需求感觉并不大，感觉多数还是中国人在用，后面在加个google登录什么的，完美

**Comment by fishfree** [comment]
@Yidadaa 请问下您close了这个issue，是fixed还是not planned?
