### ISSUE TITLE
GPT-4

### ISSUE THREAD

**Issue by bdawg1989** [Yidadaa/ChatGPT-Next-Web#994]
Hello,

I am having an issue with none of the GPT 4 working.  Only 3.5 and I have a premium subscription on Open AI.

I get this message when I type using GPT 4.

{
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by chazzhou** [comment]
Please check if your OpenAI account has access to GPT-4 API ([Waitlist here](https://openai.com/waitlist/gpt-4-api)). API access is not the same as ChatGPT Plus.

**Comment by bdawg1989** [comment]
Oh!  Dang ok, thank you sm <3

**Comment by bdawg1989** [comment]
I went to my API key page, and Don't see where it says anything about if I have access to GPT-4.  Do you have a screenshot of what I need to look for?

**Comment by Yidadaa** [comment]
Generally speaking, when you see this error message, it means you do not have gpt-4 permission :)

**Comment by Yidadaa** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-en.md#how-to-access-the-gpt-4-api
