### ISSUE TITLE
Github Actions 同步频率问题

### ISSUE THREAD

**Issue by kangfenmao** [Yidadaa/ChatGPT-Next-Web#997]
同步功能很不错，可以自动跟踪上游代码改动，但是目前同步比较频繁，会导致3个问题

1. 消耗 Github Actions 免费时长
2. Vercel 会多次重复部署，而且很容易部署出现错误
3. 网站缓存会经常失效，新部署的网站进去要重新加载，几乎每天都要重新加载

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/8253512/233752145-0ad9d90c-c02e-4a28-a06d-3e7466665124.png">

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/8253512/233752230-326efa72-5415-42dc-ad5a-2164c3d90534.png">

**Comment by jtung4** [comment]
#873

**Comment by dgqyushen** [comment]
自己fork，然后到.github/workflows/sync.yml中进行修改 cron: "0 * * * *" 我把它改成了 cron: "0 0 * * *" 每天同步一次

**Comment by haso2007** [comment]
我从8号到现在都同步出错，有人知道原因吗？
