### ISSUE TITLE
[Feature] 能否提供更详尽的错误提示？

### ISSUE THREAD

**Issue by ProblemFactory** [Yidadaa/ChatGPT-Next-Web#998]
我利用docker+nginx反代https部署了本项目给国内的家人使用，但其中一个人反馈在手机上输入授权码之后聊天总是提示出错了（不是未授权，而是“出错了，稍后重试吧”），也无法刷新余额，换了不同的浏览器也是一样的结果。因为他没有电脑，我也无法远程控制帮助他debug，其他人那边也都是正常工作，很难让我知道到底是为什么出错。服务器后台看上去也没有任何错误信息，能否在前端提示更详尽的错误信息以便我发现问题所在？

**Comment by tjefferson** [comment]
这种很多时候是ChatGPT的问题，ChatGPT服务拥堵导致的。

**Comment by ProblemFactory** [comment]
> 

不是的，在错误发生的时候我也测试过，我这边访问是正常的。后台也没出现什么api访问的错误。

**Comment by Yidadaa** [comment]
目前应该很少出现“出错了，稍后重试”的提示，而是会直接返回 openai 报错。
